owncloud/ocis

.github/settings.yml

Properly configure the repository settings transparently and version controlled.

Enable github settings config

---

README.md
docs/content/building.md

Fixes https://github.com/owncloud/ocis/issues/39

Raise minimal Go version to v1.12

---

README.md

Just a small Typo in the readme Link

Fixed Link to readme, hosted on GitHub

---

go.mod
go.sum
pkg/command/phoenix.go
pkg/command/phoenix_ocis.go
pkg/command/phoenix_simple.go

configures the apps and external apps for the
ocis & ocis-simple build by conditionally including a
different configurePhoenix function

configure phoenix apps

---

go.mod
go.sum
pkg/command/graph-explorer.go
pkg/config/config.go
pkg/micro/runtime/runtime.go

Adding ocis-graph-explorer to ocis

---

pkg/command/root.go
pkg/command/server.go
pkg/micro/runtime/command.go
pkg/micro/runtime/runtime.go

fixes #115 however magical. Currently looking into why adding a logging line fixes the execution...

Fix ocis runtime

---

docs/_index.md
docs/bridge.md
docs/building.md
docs/extensions.md
docs/getting-started.md
docs/license.md

- adds edit links
- adds a new bridge.md to document how to run ocis next to an owncloud 10 instance

update docs and add bridge status

---

docs/bridge.md

This documents how to run and configure phoenix in a bridge deployment

Add how to run and configure phoenix in the bridge setup

---

.drone.star
Makefile
changelog/CHANGELOG.tmpl
docs/bridge.md
docs/building.md
docs/extensions.md
docs/getting-started.md

- Align the changelog format
- Add TOC links for long doc pages
- Correct the heading levels

Align the changelog formatting

---

README.md

Rename "einstein" to "albert" as only the latter works.

Fix demo user name

---

changelog/unreleased/start-proxy-with-server.md
go.mod
go.sum
pkg/command/proxy.go
pkg/config/config.go
pkg/micro/runtime/runtime.go

Start proxy with ocis server command 

---

changelog/unreleased/updated-extensions.md
go.mod
go.sum

update reva to v0.1.0

---

.drone.star

running oC 10 API tests in CI using ocis-server

[Tests-Only] run API tests from oC 10 in CI

---

.drone.star
tests/config/drone/identifier-registration.yml
tests/config/drone/ocis-config.json

running phoenix webui acceptance tests in CI using ocis-server

[Tests-Only] Run phoenix webui acceptance tests

---

docs/configuration.md
go.mod
go.sum
templates/CONFIGURATION.tmpl

Update the template to a improved format.

Update flaex template

---

docs/request-flow.md

- adds a sequence diagram for https://github.com/owncloud/ocis-glauth/issues/13

Initial request flow documentation

---

docs/_index.md

Was initially planned for the deployment-workshop but would also make for a first good overview.
Preview here: https://bit.ly/2KFLDyH

Extensions diagram

---

docs/testing.md

analog to https://github.com/owncloud/ocis-reva/pull/141
part of owncloud/ocis#211

[Tests-only] document how to use oC10 API tests for BDD in ocis

---

README.md
docs/getting-started.md

- Quick fix for the credentials

fix wrong credentials in docs

---

docs/basic-remote-setup.md
docs/configuration.md

add simple remote setup to docs

---

docs/login-flow.md

Shows two scenarios:
1. using an external idp
2. using ocis built in konnectd idp
Basis for discussion

Document login flow

---

Makefile

- use eos `v4.7.12`
Closes: https://github.com/owncloud/enterprise/issues/3976

Use latest eos docker image

---

.drone.star
go.mod
go.sum

Bringing ocis-reva to the state from https://github.com/owncloud/ocis-reva/pull/192

Update ocis-reva, fixing CI issues

---

.drone.star

analog to https://github.com/owncloud/ocis-reva/pull/185 in this repo

[Tests-only] Create test-skeleton files while creating user

---

.drone.star

This PR changes the skeleton directory path that is created by PR https://github.com/owncloud/ocis/pull/275

[Tests-only] Fix skeleton directory path

---

docs/tracing.md

More or less dumped from chat log, so this basically belongs to @refs
Adding basic documentation for how to get started with tracing.

Add basic docs for tracing

---

.drone.star

[Tests-Only] fix configuration variables for ui test in CI

---

README.md

Added redis docker for an even quicker quick start.

Update README with redis docker

---

.drone.star

skip tests tagged with the new tag in https://github.com/owncloud/core/pull/37554

[tests-only] skip tests that are tagged @skipOnOcis-OC-Storage

---

.drone.star

Issue #343 
Split the phoenix test pipelines to speed up the total test run time.

[CI] Split phoenix tests into multiple pipelines

---

.drone.star
changelog/unreleased/update-extensions-01_07_2020
go.mod
go.sum

- ocis-reva from 0.8.0 to 0.9.0

update extensions 2020-07-01

---

docs/basic-remote-setup.md

Add newly added config to Basic Remote Setup

add config for datagateway and silent redirect

---

changelog/unreleased/update-extensions-2020-07-10.md
go.mod
go.sum

- ocis-phoenix v0.9.0
- ocis-reva v0.10.0

Update extensions 2020-07-10

---

.drone.star
tests/acceptance/expected-failures.txt

Gets the tests running that were enabled in core PR https://github.com/owncloud/core/pull/37809

[Tests-Only] Bump core commit to run extra tests

---

docker-compose.yml

Following https://github.com/owncloud/ocis/pull/465

add REVA_LDAP_IDP to docker compose

---

.drone.star

Following up reenabling public link tests

[Tests-Only] Update commit for Phoenix tests

---

.gitignore
tests/acceptance/expected-failures-on-OC-storage.txt
tests/acceptance/features/apiOcisSpecific/apiTrashbin-trashbinDelete.feature
tests/acceptance/features/apiOcisSpecific/apiTrashbin-trashbinFilesFolders.feature

This PR adds `apiTrashbin` bug verification scenarios.

[Tests-Only] Add api trashbin tests

---

changelog/unreleased/update-ocis-ocs.md
go.mod
go.sum

update ocis-ocs to v0.3.0

---

.drone.star

Includes core test changes:
https://github.com/owncloud/core/pull/37839 [Tests-Only] Assert created user
https://github.com/owncloud/core/pull/37849 [Tests-Only] remove UI tests from expected failures if rerun is successful
https://github.com/owncloud/core/pull/37847 [Tests-Only] Improve header response checks in theHeaderChecksumShoudMatch
https://github.com/owncloud/core/pull/37851[Tests-Only] Fix theseUsersHaveBeenCreatedUsingTheOccCommand so it works with mixed-case usernames
https://github.com/owncloud/core/pull/37855 [Tests-Only] Process unexpected Behat exit status in acceptance tests
https://github.com/owncloud/core/pull/37852 [Tests-Only] Reporting expected failures when running a single feature

[Tests-Only] Bump oC10 test commit id

---

.drone.star

This PR runs latest webUI tests. This PR is required to run https://github.com/owncloud/phoenix/pull/3982  on ocis.

[Tests-Only] Run latest phoenix webUI tests

---

.drone.star
tests/acceptance/expected-failures-on-OC-storage.txt

Gets us these core test changes:
https://github.com/owncloud/core/pull/37879 [Tests-Only] Remove some toImplementOnOCIS tags
https://github.com/owncloud/core/pull/37880 [Tests-Only] Make scenario outline for creating a share with no permissions
https://github.com/owncloud/core/pull/37889 [Tests-Only] Acceptance tests for issue 37883

[Tests-Only] Bump core commit

---

tests/acceptance/expected-failures-on-EOS-storage.txt

Update the expected failures file  for EOS storage backend.

[Tests-Only] update expected failures for eos tests

---

.drone.star
tests/acceptance/config/behat.yml
vendor-bin/behat/composer.json

Support for this in the core acceptance test runner was added in https://github.com/owncloud/core/pull/37915 (see that PR for details - tests can be can be run 1 step at a time)
- bump the core commit to get that
- add the extension to the Behat pieces here for the test runner

[Tests-Only] Add StepThroughExtension to acceptance test runner

---

.drone.star

- No CI needed on PR, skipping
- Only relevant for `refs/heads/master`

Re enable deployment pipeline [skip ci]

---

accounts/Makefile
glauth/Makefile
konnectd/Makefile
ocis-phoenix/Makefile
ocis-pkg/Makefile
ocis-reva/Makefile
ocis/Makefile
ocs/Makefile
proxy/Makefile
settings/Makefile
store/Makefile
thumbnails/Makefile
webdav/Makefile

adapt import paths in the makefiles

---

ocis/pkg/command/proxy.go
proxy/changelog/unreleased/proxy-version-command.md
proxy/go.mod
proxy/go.sum
proxy/pkg/command/root.go
proxy/pkg/command/server.go
proxy/pkg/command/version.go
proxy/pkg/config/config.go
proxy/pkg/flagset/flagset.go
proxy/pkg/metrics/metrics.go
proxy/pkg/server/debug/server.go
proxy/pkg/server/http/option.go
proxy/pkg/server/http/server.go

The cli version command for the proxy service.

add version command and add build information to metrics

---

.drone.star
Makefile

Simplify the docs build pipeline if someone only commits changes to the docs.
- Add `[docs-only]`  to the PR title (exact match)

[docs-only] simplify docs pipeline

---

.drone.star

1) Split Ui Tests in 4 parts
2) Do not run acceptance tests on merge commits

[Tests-Only] Optimize the test Suite

---

ocs/go.mod
ocs/go.sum
ocs/pkg/server/http/svc_test.go

Enable OCS HTTP API tests
These tests were skipped when moving ocis to monorepo.

[Tests-Only] enable ocs http integration tests

---

ocs/pkg/server/http/svc_test.go

Add tests for HTTP api for
- Listing groups
- Creating new group (not implemented)
- Listing members in a group
- Delete Group 
Moved from https://github.com/owncloud/ocis-ocs/pull/63

[Tests-only] Add ocs http tests for groups endpoints

---

Dockerfile
README.md

rebased https://github.com/owncloud/ocis/pull/652

Add Image builder

---

.drone.star
.gitignore
sonar-project.properties

Enable Sonarcloud Scanning
@phil-davis It shows ~18% oc coverage. codacy shows more than 50% ?
I cannot figure that out.

Enable sonarcloud scanning and coverage

---

ocs/pkg/server/http/svc_test.go

The related test is currently skipped, but may as well fix this while I notice it.

[Tests-Only] Fix provisioning API groups endpoint  in svc_test

---

docs/ocis/deployment/_index.md
docs/ocis/deployment/basic-remote-setup.md
docs/ocis/deployment/bridge.md
docs/ocis/development/_index.md
docs/ocis/development/building-docs.md
docs/ocis/development/building.md
docs/ocis/development/debugging.md
docs/ocis/development/getting-started.md
docs/ocis/development/testing.md
docs/ocis/development/tracing.md
docs/ocis/eos.md
docs/ocis/extensions.md
docs/ocis/getting-started.md
docs/ocis/license.md
docs/ocis/login-flow.md
docs/ocis/public-upload-flow.md
docs/ocis/request-flow.md

In some places the edit-path linked to an old place
sorry for the spaces and empty lines noise, the IDE did that :-(

[docs-only] fix edit path

---

docs/ocis/eos.md

after switching to mono-repo the path has changed

[docs-only] fix path to docker-compose.yml

---

accounts/package.json

the normal UI tests are retried on failure, so lets do the same for accounts

[tests-only] retry failing accounts tests

---

ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt
ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt

update the issue links for expected failure files.

[Tests-Only] update issues in expected failure file for owncloud storage

---

docs/ocis/development/testing.md

analog to #666 use the new path

[docs-only] update testing docs

---

changelog/unreleased/update-reva-to-dd3a8c0f38.md
ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt
storage/go.mod
storage/go.sum

update reva to dd3a8c0f38

---

.drone.star

there are more suites running currently in the phoenix repo (specially sharing tests), I will add those to this repo in a separate PR

[tests-only] bump phoenix commit it to current top of master

---

.drone.star
ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt
ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt

Includes core test-related PRs:
https://github.com/owncloud/core/pull/38028 [tests-only] add tests to demonstrate issue 38027
https://github.com/owncloud/core/pull/38031 [tests-only] test favorites related scenarios when shares are recieved in subfolder
https://github.com/owncloud/core/pull/38030 [Tests-Only]Bug demonstration scenarios added separately for cli tests
The similar PR in `cs3org/reva` is https://github.com/cs3org/reva/pull/1270

[tests-only] Bump core test commit

---

.drone.star
ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt
ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt

run the favourites tests added/changed in https://github.com/owncloud/core/pull/38047

[tests-only] expected failures of favourites tests

---

.drone.star
changelog/unreleased/update-phoenix-0.23.0
ocis-phoenix/Makefile

This brings a first version of the accordion instead of tabs in the right sidebar

Update phoenix to 0.23.0

---

.codacy.yml
deployments/examples/ocis_external_konnectd/idpnode/docker-compose.yml
deployments/examples/ocis_external_konnectd/ocisnode/docker-compose.yml
deployments/examples/ocis_oc10_backend/docker-compose.yml
deployments/examples/ocis_oc10_backend/oc10/Dockerfile
deployments/examples/ocis_oc10_backend/oc10/overlay/etc/templates/config.php
deployments/examples/ocis_oc10_backend/ocis/proxy-config.json
deployments/examples/ocis_oc10_backend/ocis/web/config.json
deployments/examples/ocis_traefik/docker-compose.yml

Updated bridge setup according to latest changes and developments
- oc10.5 to 0c10.6-beta1
- Phoenix/web config
- Switching app in ocis and oc10
- bugfixes for glauth
- oc10 opened connect login fixed

Improve deployment scenarios

---

scripts/zombies.sh

- following the [golang standards project layout](https://github.com/golang-standards/project-layout)
- adding a script to add zombie users using curl and the ocs api

add zombie script

---

ocis/docker/eos-ocis/entrypoint

fix #812
needs follow up  fix in example 
https://github.com/owncloud-docker/compose-playground/blob/master/examples/eos-compose/docker-compose.yml#L28

remove usage of missing config folder

---

deployments/examples/ocis_oc10_backend/docker-compose.yml
deployments/examples/ocis_traefik/docker-compose.yml
ocis/docker-compose-eos-test.yml
ocis/docker-compose.yml

Fileupload in examples is not working, since the environmentvariable for the file upload target changed
STORAGE_FRONTEND_URL -> STORAGE_FRONTEND_PUBLIC_URL
STORAGE_DATAGATEWAY_URL -> STORAGE_DATAGATEWAY_PUBLIC_URL

fix file upload in examples

---

docs/ocis/deployment/basic-remote-setup.md

the name was changed in https://github.com/owncloud/ocis/pull/729 but never got fixed in this documentation

fix redis address variable name

---

.drone.star
ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt
ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt

Update core commit id for testrunner in CI
Enable groups tests and update issue links for expected failure file

[tests-only] Add group tests on expected failure file

---

deployments/examples/ocis_oc10_backend/oc10/overlay/etc/templates/config.php
deployments/examples/ocis_oc10_backend/ocis/config/identifier-registration.yaml

add redirect uris for logout from oc10

[docs-only] fix logout from OC10

---

.drone.star

update the phoenix commit id for the tests and add new suites that have been added in https://github.com/owncloud/phoenix/commit/4b7cd01a3dc2065fff369f896ed87cb135ed3469 (use the same list that is used in phoenix repo)

[tests-only] bump phoenix commit id for tests and add new suites

---

.drone.star

fixes #736 
I did not manage to reproduce the issue again, so lets get rid of that comment
merge after #922

delete comment about resharing in drone

---

.drone.star

see https://github.com/owncloud/ocis/pull/922#issuecomment-731985967

[tests-only] allow single suite pipeline to be defined without a list

---

tests/k6/README.md
tests/k6/package.json
tests/k6/rollup.config.js
tests/k6/yarn.lock

* make rollup externals accept globs
* fix README.md

K6 rollup externals

---

.drone.star
tests/acceptance/expected-failures-on-OCIS-storage.txt
tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt
vendor-bin/behat/composer.json

Get's new core API test scenarios added in:
https://github.com/owncloud/core/pull/38141 [Tests-Only] add more tests to cover ocis issues
https://github.com/owncloud/core/pull/38142 [tests-only] first TUS upload tests

[Tests-Only] update testrunner commitid

---

proxy/pkg/middleware/oidc_auth.go

fix oidc middleware provider lazy initialization

---

accounts/pkg/service/v0/accounts.go
ocis-pkg/cache/cache.go
tests/k6/src/test-issue-162.ts

harden accounts cache security

---

accounts/go.mod
accounts/go.sum
changelog/unreleased/update-reva-to-ac85e68.md
glauth/go.sum
konnectd/go.sum
ocis-phoenix/go.sum
ocis-pkg/go.mod
ocis-pkg/go.sum
ocis/go.sum
ocs/go.mod
ocs/go.sum
proxy/go.mod
proxy/go.sum
settings/go.sum
storage/go.mod
storage/go.sum
store/go.sum
tests/acceptance/expected-failures-on-OCIS-storage.txt
thumbnails/go.mod
thumbnails/go.sum
webdav/go.sum

Update reva to get the fix for the move operation in ocis driver. Fixes https://github.com/owncloud/ocis/issues/975

Update reva to ac85e68

---

changelog/unreleased/update-reva-to-e6a621.md

fix changelog links

---

docs/extensions/onlyoffice/_index.md
docs/extensions/onlyoffice/building.md
docs/extensions/onlyoffice/getting-started.md
docs/extensions/onlyoffice/license.md

Fix onlyoffice docs

---

.drone.star
tests/acceptance/config/behat.yml
tests/acceptance/expected-failures-on-OCIS-storage.txt
tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt
tests/acceptance/features/apiOcisSpecific/apiWebdavUploadTUS-optionsRequest.feature

create tests to demonstrate https://github.com/owncloud/ocis/issues/1012 and get https://github.com/owncloud/core/pull/38187 from core

[tests-only] adjust TUS OPTIONS test expectations to current behaiviour

---

.drone.star

[tests-only] Update commit ids for tests

---

accounts/go.mod
accounts/go.sum
accounts/pkg/command/server.go
accounts/pkg/config/config.go
accounts/pkg/flagset/flagset.go
accounts/pkg/service/v0/tracing.go
changelog/unreleased/accounts-service-tracing.md
ocis/pkg/command/accounts.go

Added tracing to the accounts service.

implement tracing in the account service

---

.drone.star
changelog/unreleased/update-phoenix-0.28.0.md
glauth/go.sum
konnectd/go.sum
ocis-phoenix/Makefile
ocis-phoenix/go.sum
onlyoffice/go.sum
settings/go.sum
store/go.sum
thumbnails/go.sum
webdav/go.sum

Update phoenix assets to 0.28.0

Update phoenix assets to 0.28.0

---

.drone.star

update phoenix and oc10 core commit ids to get the newest tests﻿

[tests-only] bump core & phoenix commid id

---

.drone.star

Make sure these are up-to-date and passing before renaming of phoenix...

[tests-only] Update commit ids for tests 20201210

---

docs/extensions/accounts/_index.md
docs/extensions/glauth/_index.md
docs/extensions/konnectd/_index.md
docs/extensions/ocis-phoenix/_index.md
docs/extensions/ocs/_index.md
docs/extensions/onlyoffice/_index.md
docs/extensions/proxy/_index.md
docs/extensions/settings/_index.md
docs/extensions/storage/_index.md
docs/extensions/store/_index.md
docs/extensions/thumbnails/_index.md
docs/extensions/webdav/_index.md
docs/ocis/deployment/_index.md
docs/ocis/development/_index.md
docs/ocis/flow-docs/_index.md

Will make use of collapsable menu items: https://github.com/thegeeklab/hugo-geekdoc/pull/23
Will only take effect after merging: https://github.com/owncloud/owncloud.github.io/pull/21
Solves: https://github.com/owncloud/owncloud.github.io/issues/20

[docs-only] make menu lists collapsed

---

deployments/examples/cs3_users_ocis/.env
deployments/examples/cs3_users_ocis/README.md
deployments/examples/cs3_users_ocis/config/ldap/ldif/10_owncloud_schema.ldif
deployments/examples/cs3_users_ocis/config/ldap/ldif/20_users.ldif
deployments/examples/cs3_users_ocis/config/ldap/ldif/30_groups.ldif
deployments/examples/cs3_users_ocis/config/ocis/.gitignore
deployments/examples/cs3_users_ocis/config/ocis/identifier-registration.dist.yaml
deployments/examples/cs3_users_ocis/config/ocis/proxy-config.json
deployments/examples/cs3_users_ocis/docker-compose.yaml

Ocis cs3 ldap compose

---

deployments/examples/ocis_keycloak/docker-compose.yml
deployments/examples/ocis_traefik/docker-compose.yml

As found in #1054 sharing failed. Also thumbnails where not displayed.

fix thumbnails and sharing in example deployments

---

deployments/examples/cs3_users_ocis/docker-compose.yaml

Disable auto-provisioning in CS3 example 

---

.drone.star
tests/acceptance/expected-failures-on-EOS-storage.txt
tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt

Covered more issues from product issues to expected failures.

[tests-only] Updates expected failures with product issues

---

.drone.star
tests/acceptance/expected-failures-on-OCIS-storage.txt
tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt

to run TUS tests for file with invalid-name, see https://github.com/owncloud/core/pull/38217 and https://github.com/owncloud/core/pull/38226

[tests-only] run tus test for file with invalid-name

---

deployments/examples/cs3_users_ocis/.env
deployments/examples/cs3_users_ocis/docker-compose.yaml

Bind didn't work before.
Mapped ldap ports to host to be abe to use ldap gui-tools.

Change ldap domain to dc=com

---

.drone.star
tests/acceptance/expected-failures-on-OCIS-storage.txt
tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt
tests/acceptance/features/apiOcisSpecific/apiWebdavUploadTUS-uploadFile.feature

added tests to demonstrate #1141 and bump core commit id

[tests-only] adjust TUS test using resource URL to current behaviour

---

proxy/config/proxy-example-migration.json
proxy/config/proxy-example.json
proxy/pkg/command/root.go
proxy/pkg/config/config.go
proxy/pkg/proxy/policy/selector.go
proxy/pkg/proxy/policy/selector_test.go
proxy/pkg/proxy/proxy.go
proxy/pkg/proxy/proxy_integration_test.go

rename reva to proxy where applicable

---

.drone.env
.drone.star

remove core commitid and branch name from .drone.star file
fixes: https://github.com/owncloud/ocis/issues/1132
reason: https://github.com/owncloud/ocis/pull/1117#issuecomment-747571408

[CI] remove commit id from .drone.star file

---

proxy/pkg/proxy/policy/selector_test.go
proxy/pkg/proxy/proxy.go
proxy/pkg/proxy/proxy_test.go
thumbnails/pkg/thumbnail/encoding.go
thumbnails/pkg/thumbnail/encoding_test.go

Since I don't want to start any big things right now I did some small refactorings of some methods and tests.

small refactorings of test code and some methods

---

accounts/templates/CONFIGURATION.tmpl
glauth/templates/CONFIGURATION.tmpl
konnectd/templates/CONFIGURATION.tmpl
ocis/templates/CONFIGURATION.tmpl
ocs/templates/CONFIGURATION.tmpl
onlyoffice/templates/CONFIGURATION.tmpl
proxy/templates/CONFIGURATION.tmpl
settings/templates/CONFIGURATION.tmpl
storage/templates/CONFIGURATION.tmpl
store/templates/CONFIGURATION.tmpl
thumbnails/templates/CONFIGURATION.tmpl
web/templates/CONFIGURATION.tmpl
webdav/templates/CONFIGURATION.tmpl

needed for documentation of #1148

[docs-only] add multiple env vars to templates

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.txt
tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.txt

bump id of core to get the newest tests and add them to the expected failures list

[tests-only] bump core commit id

---

.codacy.yml
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
.github/stale.yml

- Pull request template.
- Issue templates.
- Feature request.
- Bug report.
The Pull Request template was copied and adapted from owncloud/core

Introduce github templates

---

ocis/docker/Dockerfile.linux.amd64
ocis/docker/Dockerfile.linux.arm
ocis/docker/Dockerfile.linux.arm64

Pin Alpine docker image version which is used for oCIS docker releases
- Fixes #1218 
Build failed after Release of Apline 3.13
- CI
- test case 1:
- test case 2:
- ... fix (non-breaking change which fixes an issue)
test environment:
- test case 1:
- test case 2:
- ...

pin alpine version

---

ocis/docker-compose.yml

Add onlyoffice mount in docker-compose setup
- Fixes eos docker-compose setup
Running ocis with eos using docker-compose was giving error
```
docker-compose up ocis                                                                                                             ✔ ▓▒░
Starting ocis ... done
Attaching to ocis
ocis          | fatal: Not a git repository (or any parent up to mount point /ocis)
ocis          | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
ocis          | go build -v -tags '' -ldflags '-s -w -X "github.com/owncloud/ocis/ocis/pkg/version.String=" -X "github.com/owncloud/ocis/ocis/pkg/version.Date=20210118"' -o bin/ocis ./cmd/ocis
ocis          | go: github.com/owncloud/ocis/onlyoffice@v0.0.0-00010101000000-000000000000: parsing …
```

Add onlyoffice mount on docker-compose setup

---

tests/acceptance/expected-failures-API-on-EOS-storage.md
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md

To get the format to match what is in https://github.com/cs3org/reva/pull/1420
This will make it easier to cut-paste between the lists in each repo.

[tests-only] Adjust some text in expected-failures to match cs3org/reva

---

accounts/templates/CONFIGURATION.tmpl
docs/extensions/onlyoffice/getting-started.md
glauth/templates/CONFIGURATION.tmpl
konnectd/templates/CONFIGURATION.tmpl
ocis/templates/CONFIGURATION.tmpl
ocs/templates/CONFIGURATION.tmpl
onlyoffice/templates/CONFIGURATION.tmpl
proxy/templates/CONFIGURATION.tmpl
storage/templates/CONFIGURATION.tmpl
store/templates/CONFIGURATION.tmpl
thumbnails/templates/CONFIGURATION.tmpl
web/templates/CONFIGURATION.tmpl
webdav/templates/CONFIGURATION.tmpl

The following link does no exist
[our repository ] (https://github.com/owncloud/ocis/tree/master/config),
https://github.com/owncloud/ocis/tree/master/config
The link into the Page (https://owncloud.github.io/ocis/configuration/#configuration-using-config-files) does not exist
[our repository ] (https://github.com/owncloud/ocis/tree/master/config), - https://github.com/owncloud/ocis/tree/master/config

[docs-only] Update CONFIGURATION.tmpl

---

changelog/reva-update-2020-11-26.md

On changelog item is removed which was not placed into "unreleased".
It confuses people where to put changelogs. Also it will never picked up from there.
- test case 1:
- test case 2:
- ...

[docs-only] remove misplaced changelog item

---

deployments/continuous-deployment-config/cs3_users_ocis/latest.yml
deployments/continuous-deployment-config/cs3_users_ocis/released.yml
deployments/continuous-deployment-config/ocis_keycloak/released.yml
docs/ocis/deployment/continuous_deployment.md

Add a page to the documentation with all the links to the continuous deployed examples. It also fixes some URL configurations for the examples.
- fixes #1387

[docs-only] document and fix continuous deployment

---

docs/ocis/deployment/continuous_deployment.md

Added docs in #1582 had two minor errors. These are resolved in this PR.

[docs-only] fix continuous deployment docs

---

.drone.star

#1381 introduced a bug that prevents pushing docker images to Dockerhub.
- see it fail here: https://drone.owncloud.com/owncloud/ocis/3220/75/4

fix CI: push images to Dockerhub fails since PR 1381

---

deployments/examples/cs3_users_ocis/docker-compose.yml
deployments/examples/ocis_keycloak/docker-compose.yml
deployments/examples/ocis_traefik/docker-compose.yml
deployments/examples/owncloud10_with_oc_web/docker-compose.yml

Update Traefik to the latest minor version available.

[docs-only] bump traefik version

---

docs/_index.md

Just some minor punctuation and language fixes.
- test case 1:
- test case 2:
- ...

[docs-only] Update _index.md

---

changelog/unreleased/update-web-2.0.1.md
web/Makefile
web/go.sum

Update web to 2.0.1

---

docs/ocis/getting-started.md

updated the tech preview version from 1.1 to 1.2

[docs-only] Update getting-started.md

---

.drone.env

To match the same commit id in `cs3org/reva` https://github.com/cs3org/reva/pull/1489

[tests-only] Bump core commit for tests

---

settings/pkg/proto/v0/settings.pb.micro_test.go

issues https://github.com/owncloud/ocis-settings/issues/57 & https://github.com/owncloud/ocis-settings/issues/18 got moved to this repo and https://github.com/owncloud/ocis-settings/issues/19 is closed
#1445
#1455

[tests-only] update issue links in gRPC tests

---

graph-explorer/go.mod
graph-explorer/go.sum
graph-explorer/pkg/server/debug/server.go
graph-explorer/pkg/server/http/server.go
graph-explorer/pkg/service/v0/service.go

resolve linter issues

---

.drone.env

Bump core commit id 
Part of issue https://github.com/owncloud/QA/issues/661

[tests-only] Bump commit id for API tests

---

docs/ocis/development/getting-started.md

Small changes to better reflect what ocis does. or will do. ;-)

[docs-only] Update development getting-started.md

---

docs/ocis/release_notes.md

Added changelog for the upcoming 1.3.0 release of oCIS.

[docs-only] Add Release Notes for oCIS release 1.3.0

---

docs/ocis/development/build.md

Just a tiny change to fix incorrect usage of the 'help requested' flag
Just a tiny change to fix incorrect usage of the 'help requested' flag on the build instructions.
- test case 1:
- test case 2:
- ...

[docs-only] Update development build.md

---

docs/ocis/development/build.md

Build instructions have been outdated and also not explanatory.
- test case 1:
- test case 2:
- ...

[docs-only] fix build instructions

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md

[tests-only] Bump core and web commit ids

---

.drone.env

That was easy - no changes needed to expected-failures.

[tests-only] Bump commit id for tests

---

ocis/docker/eos-ocis/Dockerfile

fix failing eos test by bumping go version
- test case 1:
- test case 2:
- ...

bump go version for eos test

---

.dockerignore
Dockerfile
ocis/docker/Dockerfile.linux.amd64
ocis/docker/Dockerfile.linux.arm
ocis/docker/Dockerfile.linux.arm64

Update Alpine base image to 3.13 and fix docker build context for developer dockerfile
- test case 1:
- test case 2:
- ...

update alpine base image to 3.13

---

.make/l10n.mk

- test case 1:
- test case 2:
- ...

fix clean deletes translations.js

---

docs/ocis/release_notes.md

[docs-only] 1.4.0 Release Notes

---

docs/ocis/release_notes.md

Adds information to the changelog about a breaking change:
`Despite a breaking change in the oCIS storage driver file layout, data is not automatically migrated. You will be affected if you plan to update from a previous version of oCIS to oCIS 1.4.0 and are using the oCIS storage driver, which is currently the default storage driver. ....`
- test case 1:
- test case 2:
- ...

[docs-only] add breaking change to changelog and update strategy

---

.gitignore
.vscode/launch.json

Adds VS Code debug configuration. Enables developers to easily debug oCIS.
- test case 1:
- test case 2:
- ...

add vscode debug

---

.drone.star

Update of several CI dependencies.
CI dependency summary after this PR:
```
List of used docker images:
57x	owncloudci/nodejs:14
74x	owncloudci/golang:1.16
58x	meltwater/drone-cache:v1
19x	plugins/s3:1
4x	alpine/git:latest
3x	minio/mc:RELEASE.2021-03-23T05-46-11Z
1x	plugins/codacy:1
1x	sonarsource/sonar-scanner-cli:latest
84x	owncloudci/alpine:latest
57x	thegeeklab/wait-for:latest
24x	owncloudci/php:7.4
8x	plugins/docker:latest
1x	plugins/manifest:1
1x	sheogorath/readme-to-dockerhub:latest
4x	plugins/github-release:1
1x	plugins/git-action:1
1x	plugins/gh-pages:1
1x	plugins/downstream:latest
1x	plugins/webhook:1
3x	owncloudci/drone-ansible:latest
1x	plugins/slack:1
```

update ci deps

---

.drone.star

replace legacy sheogorath/readme-to-dockerhub with chko/docker-pushrm

replace legacy sheogorath/readme-to-dockerhub with chko/docker-pushrm

---

.make/protobuf.mk

adds ` logtostderr=true` to protobuf generation where applicable
- Fixes #223

add logtostderr=true to protobuf generation

---

.drone.star

remove microbadger update action since microbadger will be shut down

remove microbadger update

---

docs/extensions/graph-explorer/_index.md
docs/extensions/onlyoffice/license.md
docs/extensions/settings/glossary.md
docs/extensions/storage/users.md
docs/ocis/deployment/monitoring-tracing.md
docs/ocis/storage-backends/eos.md
settings/templates/CONFIGURATION.tmpl

Found some broken links in the oCIS docs and fixed them.

[docs-only] Fix a bunch of broken links within the docs

---

.drone.star
.make/release.mk
ocis/docker/Dockerfile.linux.amd64
ocis/docker/Dockerfile.linux.arm
ocis/docker/Dockerfile.linux.arm64

fix docker releases
- Fixes release blocker introduced by #1941 
docker releases do not work

fix docker release

---

.make/l10n.mk

- test case 1:
- test case 2:
- ...

fix translation push

---

tests/acceptance/expected-failures-API-on-EOS-storage.md
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md

Issue owncloud/product#203 has been closed but there were some tests claiming that they fail because of that issue. This PR removes the closed issue and assigns appropriate issue to the failing tests.
- Fixes https://github.com/owncloud/ocis/issues/1953
- :robot:

[tests-only] Refactor expected-to-fail file to assign correct issue to failing test

---

.drone.star

enable continuous deployment examples for oCIS WOPI server, was missing in #1940

add deployment config for wopi

---

.drone.star

- Closes https://github.com/owncloud/ocis/issues/2013

[CI] Remove redis server when running ocis server with ocis storage

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md

This PR bumbs to the latest the core and web commit id.
- https://github.com/owncloud/QA/issues/662
- CI

[Tests-Only]Bumps to latest core and web commit

---

docs/ocis/adr/0004-support-hot-migration.md
docs/ocis/adr/0005-cs3-api-account-management.md
docs/ocis/adr/0006-service-discovery.md
docs/ocis/adr/0007-api-for-spaces.md

Fix a couple of duplicate lines in the headers of the adrs and add a proper one for 0007.

[docs-only] Fix headers for the adrs, remove duplicate lines and reword.

---

docs/ocis/adr/0006-service-discovery.md
docs/ocis/adr/0007-api-for-spaces.md

Accept some adrs
- test case 1:
- test case 2:
- ...

accept some adrs

---

docs/ocis/release_notes.md

[docs-only] 1.6.0 Release Notes

---

.drone.star

Adds the ability to skip pipelines and debug specific test suites. That will make it easier when debugging tests in drone CI.
- part of https://github.com/owncloud/QA/issues/670

[tests-only] Feature to skip and debug test suites in CI

---

docs/ocis/release_notes.md

add breaking changes of 1.6.0 release to docs
- #2043

[docs-only] add 1.6.0 breaking changes to docs

---

.drone.star

Changes the depends-on logic to have a append behavior instead of the current overwrite behavior. Does not change the behavior of the current oCIS pipeline, changes are brought back from another project where theses changes were needed for flexibility improvements.

[CI-only] change dependson logic

---

docs/ocis/release_notes.md

Add another breaking change to the release nots
- Fixes #2057

[docs-only] add breaking change to docs

---

.drone.star

reduce the log output to error
less output should reduce the load on drone a bit

[tests-only] reduce ocis output log for tests

---

deployments/examples/ocis_traefik/.env
deployments/examples/ocis_wopi/docker-compose.yml

- This disables the annoying Collabora welcome message for or deployment examples.
- fix the deployment for owncloud/ocis-wopiserver#5

[deployment examples] improve WOPI server example

---

.drone.star

- Added `@skipOnOcis` tag to skip the test on `ocis` completely without caring which storage driver is used

[Tests-Only] Added skipOnOcis tag for localApiTest suite

---

tests/acceptance/features/apiBugDemonstration/apiWebdavPreviews-previews.feature

`ocis` related API previews bug demonstrations scenarios are moved from core repo to this repo
- https://github.com/owncloud/ocis/issues/1472

[Tests-Only] Added conflicting previews tests

---

deployments/examples/ocis_wopi/docker-compose.yml

change WOPISERVER_REVA_GATEWAY to WOPISERVER_REVA_GATEWAY_ADDR
- Needed because of changes in https://github.com/owncloud/ocis-wopiserver/pull/5

[deployment examples] adapt WOPI example

---

changelog/unreleased/update-web-3.2.0.md
web/Makefile

This PR updates the assets of the web service to version 3.2.0 of ownCloud Web.
- test case 1:
- test case 2:
- ...

Update web to 3.2.0

---

.drone.star

selenium not starting for settings UI tests
https://drone.owncloud.com/owncloud/ocis/5291/45/3
- test case 1:
- test case 2:
- ...

[Tests-Only] Used different version of selenium for settings UI test

---

docs/ocis/adr/0007-api-for-spaces.md

Add the link to our open Graph Api Spec.
- test case 1:
- test case 2:
- ...

[docs-only] Update 0007-api-for-spaces.md

---

docs/ocis/deployment/ocis_wopi.md

Signed-off-by: Muhammet Kara <muhammet.kara@collabora.com>
- test case 1:
- test case 2:
- ...

[docs-only] Fix broken url and path on ocis_wopi.md

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md

This PR adjusts the issues in the expected failures file such that the closed issues are replaced with the existing correct issues.
- https://github.com/owncloud/ocis/issues/2078
- CI

[Tests-Only]Adjust expected failures file by adjusting the issues

---

deployments/examples/ocis_wopi/.env
deployments/examples/ocis_wopi/docker-compose.yml
docs/ocis/deployment/ocis_wopi.md

Deployment changes needed after https://github.com/owncloud/ocis-wopiserver/pull/6 is merged

fix jwt secrets for wopiserver example

---

scripts/create-files.sh
scripts/create-tree.sh

add two scripts to create
- 1. lots of files in a folder
- 2. a deep folder hierarchy

[docs-only] add create scripts

---

.drone.star
settings/nightwatch.conf.js
settings/ui/tests/acceptance/stepDefinitions/settingsContext.js

Remove after step for restoring the settings for settings ui tests.
- Fixes https://github.com/owncloud/ocis/issues/2208
🤖

[Tests-Only] do not restore settings value in ui tests

---

docs/ocis/migration.md

Adding more details to the migration stages with sections on:
- Why?
- User impact
- steps
- verification
- rollback
- notes
- FAQ
I'll also add TODOs where I run into missing things.

[docs-only] flesh out migration docs

---

accounts/go.mod
accounts/go.sum
changelog/unreleased/update-reva-v1.9.1-0.20210628143859-9d29c36c0c3f.md
glauth/go.sum
graph-explorer/go.sum
graph/go.mod
graph/go.sum
idp/go.sum
ocis-pkg/go.mod
ocis-pkg/go.sum
ocis/go.mod
ocis/go.sum
ocs/go.mod
ocs/go.sum
onlyoffice/go.sum
proxy/go.mod
proxy/go.sum
settings/go.mod
settings/go.sum
storage/go.mod
storage/go.sum
store/go.mod
store/go.sum
tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
thumbnails/go.mod
thumbnails/go.sum
web/go.sum
webdav/go.sum

Update REVA to get https://github.com/cs3org/reva/pull/1833

update reva to v1.9.1-0.20210628143859-9d29c36c0c3f

---

.drone.star
tests/acceptance/expected-failures-webUI-on-OCIS-storage.md

This PR fixes the `linter: duplicate pipeline names` issue in full-ci case.

[Tests-Only][full-ci] Fix full-ci issue

---

.drone.star

When we put `full-ci` in the PR title, the minimal web UI "smoke test" pipeline was not being run. But that pipeline has its own expected-failures file. Sometimes that expected-failures file would get out-of-date and we would not notice. The problem would be noticed by the next developer PR that does not have `full-ci`.
This PR makes it so that all PRs run the minimal web UI "smoke test" pipeline. So "full CI" really will be "full CI"!
CI

[full-ci] [tests-only] Always run minimal web UI test pipeline

---

docs/ocis/adr/0008-extension-template.md

This PR introduces an ADR for the extension template.
I also want to use this PR to this discuss this topic.

[docs-only] draft an adr for extension templates

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

This PR bumps the latest core commit.
- https://github.com/owncloud/QA/issues/679
- CI

[Tests-Only][full-ci] Run latest core changes in ocis

---

CONTRIBUTING.md
README.md
docs/_index.md

Fresh PR that supersedes #2189 that has had an rebase accident.

[docs-only] Add the Contribution Guidelines plus linking to it.

---

docs/ocis/development/continuous-integration.md

[docs-only] document full ci flag

---

.drone.env
tests/acceptance/expected-failures-webUI-on-OCIS-storage.md

Bump the commit ids for tests to the latest.
- test environment: CI

[tests-only] [full-ci] Bump commit ids for tests

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md

Link issues in expected failure file
- Fixes https://github.com/owncloud/QA/issues/675
🤖

[Tests-Only] Link issues in expected failure file

---

docs/ocis/release_notes.md

- test case 1:
- test case 2:
- ...

[docs-only] Add release notes for 1.9.0

---

.drone.env

This PR updates the core commit id.
- https://github.com/owncloud/QA/issues/679
- CI

[Tests-Only][full-ci] Update the core commit id

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
tests/acceptance/expected-failures-webUI-on-OCIS-storage.md

- Bump web and core commit ids for tests
- update expected-failures list

[full-ci][tests-only] Bump commit ids for tests 

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md

This PR bumps core and web commit ids to make sure that tests are behaving as expected
- part of: https://github.com/owncloud/QA/issues/680
- ci

[full-ci][tests-only]bump core and web commit id

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md

Bump core and web commit id 
- part of : https://github.com/owncloud/QA/issues/680#issuecomment-888057804
- CI

[tests-only][full-ci]Bump commit id 20210728

---

deployments/examples/cs3_users_ocis/.env
deployments/examples/cs3_users_ocis/docker-compose.yml
deployments/examples/ocis_hello/.env
deployments/examples/ocis_hello/docker-compose.yml
deployments/examples/ocis_keycloak/.env
deployments/examples/ocis_keycloak/docker-compose.yml
deployments/examples/ocis_s3/.env
deployments/examples/ocis_s3/docker-compose.yml
deployments/examples/ocis_traefik/.env
deployments/examples/ocis_traefik/docker-compose.yml
deployments/examples/ocis_wopi/.env
deployments/examples/ocis_wopi/docker-compose.yml
docs/ocis/deployment/_index.md
docs/ocis/deployment/ocis_hello.md
docs/ocis/deployment/ocis_keycloak.md
docs/ocis/deployment/ocis_s3.md
docs/ocis/deployment/ocis_traefik.md
docs/ocis/deployment/ocis_wopi.md

Document the existence and importance of changing the default transfer token secret.

[docs-only] document storage transfer token

---

docs/extensions/idp/theming.md

Fixes https://github.com/owncloud/web/issues/5568

[docs-only] add how to theme idp

---

.drone.env
.drone.star
changelog/unreleased/update-web-4.0.0.md
tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
tests/config/drone/ocis-config.json
web/Makefile
web/pkg/flagset/flagset.go

[full-ci] Update web to 4.0.0

---

deployments/examples/ocis_hello/README.md
deployments/examples/ocis_s3/README.md
docs/ocis/deployment/_index.md
docs/ocis/deployment/ocis_hello.md
docs/ocis/deployment/ocis_s3.md
docs/ocis/getting-started/_index.md

This add a short note about how to make remote access work in the quickstart setup. It also fixes a few broken links and some Markdown issues.

[docs-only] Add note about remote setup to quickstart

---

accounts/yarn.lock
onlyoffice/yarn.lock
settings/yarn.lock

Supersedes #2360 #2361 #2362 #2381 #2382 #2383

Supersede dependabot bumps

---

docs/ocis/adr/0011-global-url-format.md

[docs-only] move adr 0011 to the accepted state

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

This PR removes the tests from expected to fail that are tagged `notToImplementOnOcis` and updates commit id
- https://github.com/owncloud/ocis/issues/1332
- CI

[full-ci] [tests-only] Remove ocsGETAuth.feature:243 from expected to fail and update commit id

---

docs/ocis/release_notes.md

This is a draft. Some parts might still be missing.

[docs-only] 1.11 Release Notes

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

This PR updates the core commit id
- https://github.com/owncloud/QA/issues/686
- CI

[Tests-Only][full-ci]Update core commit id

---

accounts/Makefile
glauth/Makefile
graph-explorer/Makefile
graph/Makefile
idp/Makefile
ocis-pkg/Makefile
ocis/Makefile
ocs/Makefile
proxy/Makefile
settings/Makefile
storage/Makefile
store/Makefile
thumbnails/Makefile
web/Makefile
webdav/Makefile

see https://github.com/owncloud/ocis/issues/2421
- Fixes #2421
- test case 1:
- test case 2:
- ...

fix `make generate`

---

changelog/unreleased/create-space-permission.md
settings/pkg/service/v0/settings.go

In preparation for the upcoming spaces features a `Create Space` permission was added.
Permissions for the spaces API
it hasn't  been

add create space permission

---

.drone.env

This PR bumps core commit id to the latest
- Part of : https://github.com/owncloud/QA/issues/688
- test case 1:
- test case 2:
- ...

[tests-only]Bump core commit id

---

changelog/unreleased/remove-proxy-route-fix-cs3-example.md
deployments/examples/cs3_users_ocis/config/ocis/entrypoint-override.sh
deployments/examples/cs3_users_ocis/config/ocis/proxy-config.json
deployments/examples/cs3_users_ocis/config/ocis/web-config.dist.json
deployments/examples/cs3_users_ocis/docker-compose.yml
proxy/pkg/proxy/proxy.go

- removed a non working route in the proxy default config
- fixed the cs3 users example, since it still used the accounts service

remove non working proxy route and fix cs3 users example

---

go.mod
go.sum

update reva to pull in https://github.com/cs3org/reva/pull/2076

update reva to d83f20c3148d

---

docs/ocis/deployment/kubernetes.md

The Kubernetes docs will not be visible until mid of October. This PR publishes them right now
- test case 1:
- test case 2:
- ...

[docs-only] publish kubernetes docs

---

docs/ocis/deployment/monitoring-tracing.md

add a link to our demo monitoring and tracing instance
- test case 1:
- test case 2:
- ...

[docs-only] link monitoring and tracing instance

---

docs/ocis/deployment/systemd.md

adds a systemd deplyoment guide to the docs

[docs-only] add systemd deployment guide

---

changelog/unreleased/fix-redirect-invalid-links-to-oC-web.md
changelog/unreleased/redirect-invalid-links-to-oC-web.md

Squashing a feature with a subsequent fix changelog item

squash redirect changelog item

---

tests/acceptance/expected-failures-webUI-on-OCIS-storage.md

- Fixes [#5840](https://github.com/owncloud/web/issues/5840)
We fixed this scenario on #2557 
CI

[tests-only] [full-ci] Remove webUIPreview/imageMediaViewer.feature:56

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

- Latest core id bump (as of Oct 2 2021) 
- Part of https://github.com/owncloud/QA/issues/690

[tests-only] [full-ci] bump latest core commit id for tests

---

deployments/examples/cs3_users_ocis/.env
deployments/examples/cs3_users_ocis/docker-compose.yml
deployments/examples/oc10_ocis_parallel/.env
deployments/examples/oc10_ocis_parallel/docker-compose.yml
deployments/examples/ocis_hello/.env
deployments/examples/ocis_hello/docker-compose.yml
deployments/examples/ocis_keycloak/.env
deployments/examples/ocis_keycloak/docker-compose.yml
deployments/examples/ocis_s3/.env
deployments/examples/ocis_s3/docker-compose.yml
deployments/examples/ocis_traefik/.env
deployments/examples/ocis_traefik/docker-compose.yml
deployments/examples/ocis_wopi/.env
deployments/examples/ocis_wopi/docker-compose.yml
docs/ocis/deployment/_index.md
docs/ocis/deployment/oc10_ocis_parallel.md
docs/ocis/deployment/ocis_hello.md
docs/ocis/deployment/ocis_keycloak.md
docs/ocis/deployment/ocis_s3.md
docs/ocis/deployment/ocis_traefik.md
docs/ocis/deployment/ocis_wopi.md

document the machine auth api key
- test case 1:
- test case 2:
- ...

document machine auth api key

---

go.mod
go.sum

Cleanup go.mod

---

changelog/unreleased/remove_proxy_assets.md
proxy/pkg/config/config.go
proxy/pkg/flagset/flagset.go
proxy/pkg/proxy/proxy_integration_test.go

removes an unused configuration option
- None
- locally

remove proxy asset path configuration

---

.drone.star

- update minio image
- switch to thegeeklab/drone-github-comment:1 since jmccann/drone-github-comment:1 is 3 years old
- don't add new comments about killed builds, reuse the existing one
- remove intermediate step to generate message (oCIS only has one message, compared to the much more sophisticated setup in Web)
- was tested on https://drone.owncloud.com/owncloud/ocis/7534/33/1, see also comment by ownclouders below

update ci images and early fail

---

Dockerfile

applies a quick fix the Dockerfile in the repository root in order to unblock docker based acceptance test.

quickfix root dockerfile to unblock docker based acceptance tests

---

docs/extensions/storage/apps.md

Document the app provider and how to use it.
- Follow up https://github.com/owncloud/ocis/pull/2705

[docs-only] add app provider docs

---

docs/ocis/adr/0013-locking.md

accept the locking ADR after yesterday's meeting
- Follow up of #2701 
- Fixes #2678

[docs-only] accept locking adr

---

.gitignore
.php-cs-fixer.dist.php
Makefile
deployments/examples/oc10_ocis_parallel/config/oc10/oidc.config.php
deployments/examples/oc10_ocis_parallel/config/oc10/web.config.php
phpcs.xml
tests/acceptance/features/bootstrap/RevaContext.php
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/bootstrap.php
vendor-bin/behat/composer.json
vendor-bin/owncloud-codestyle/composer.json
vendor-bin/php_codesniffer/composer.json

introduce the same code-style for PHP as in owncloud/core
as we add more ocis specific API tests that are written in PHP we should take care about the code style in PHP

[skip-ci] format PHP code same as in owncloud/core

---

docs/ocis/development/testing.md

the insecure option was introduced in https://github.com/owncloud/ocis/pull/2745
mention it here, so that people will not be confused
https://github.com/owncloud/ocis/issues/2700

[docs-only] mention insecure option

---

tests/acceptance/features/apiArchiver/downloadById.feature
tests/acceptance/features/bootstrap/ArchiverContext.php

check if downloading multiple mixed items works
part of #2510

[tests-only] test downloading multiple items with archiver

---

Makefile
tests/acceptance/features/bootstrap/SpacesContext.php

- run phpcbf on make test-php-style-fix
- fix codestyle of SpacesContext
keep the php style consistent
`make test-php-style`

[tests-only] run php code beautifier on test-php-style-fix

---

tests/acceptance/features/apiArchiver/downloadById.feature
tests/acceptance/features/bootstrap/ArchiverContext.php

check if an other user can download a file that does not belong to him
part of #2510
check basic security
:robot:

[tests-only] test downloading a file as not owner

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

This PR bumps core commit id to match the latest
- Part of : https://github.com/owncloud/QA/issues/695
- CI

[tests-only][full-ci]Bump core commit id to match latest

---

tests/acceptance/features/apiArchiver/downloadById.feature

the expected file-names were not correct.
The test still fails because of #2751 but at least we should have the expectations fixed
make it possible that the test could pass when the bug is fixed

[tests-only] fix archiver tests expectations

---

.drone.env

- test case 1:
- test case 2:
- ...

[tests-only][full-ci]Bump ocis commit id to match latest

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiArchiver/downloadByPath.feature
tests/acceptance/features/bootstrap/ArchiverContext.php

the archiver endpoint can also take a path parameter, check if that is working correctly
part of #2510

[tests-only] use archiver endpoint with path

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-webUI-on-OCIS-storage.md

There were some issues in the `expected-to-fail-file` that weren't linked to any scenarios and some of them were closed. This PR removes such issues
- Fixes https://github.com/owncloud/ocis/issues/2539
- CI

[full-ci][tests-only]Remove issues not linked to scenarios

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md

Updated related issues in expected failure file.
- Related https://github.com/owncloud/ocis/issues/766#issuecomment-912379609

[Test-Only] update correct issues on expected failure file

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

Latest core commit id bump [Nov 17 2021]
- PR for https://github.com/owncloud/QA/issues/699

[tests-only] [full-ci] latest core commit id bump

---

changelog/unreleased/update-reva.md
go.mod
go.sum
storage/pkg/command/gateway.go
storage/pkg/command/storagepubliclink.go
storage/pkg/flagset/gateway.go
storage/pkg/flagset/storagepubliclink.go
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md

[full-ci] update REVA

---

changelog/unreleased/update-reva.md
go.mod
go.sum

Update REVA for the oCIS release
- Needed for https://github.com/owncloud/ocis/issues/2766

[full ci] update REVA to v1.16.0

---

tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

Add api tests: change quota and name of space
- test case 1:
- test case 2:
- ...

Test: change data of space 

---

.drone.env

Bump core commit id to the latest for tests
part of https://github.com/owncloud/QA/issues/699

[tests-only][full-ci] Bump core commit id for tests

---

tests/acceptance/features/bootstrap/ArchiverContext.php
tests/acceptance/features/bootstrap/RevaContext.php
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/bootstrap.php

Enable strict type checking in local API tests.
- Related https://github.com/owncloud/QA/issues/694
:robot:

[Tests-Only][full-ci] enforce strict type checking for php api tests

---

ocs/pkg/service/v0/data/meta.go
ocs/pkg/service/v0/groups.go
ocs/pkg/service/v0/users.go

Addition to https://github.com/owncloud/ocis/pull/2825
- Follow up of https://github.com/owncloud/ocis/pull/2825

introduce string constants for user / group not found messages

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/apiSpaces/listSpaces.feature
tests/acceptance/features/apiSpaces/quota.feature
tests/acceptance/features/apiSpaces/uploadSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

- add api tests: state of the quota
- failed test added to expected failures and create bug: https://github.com/owncloud/ocis/issues/2829
- test case 1:
- test case 2:
- ...

[tests-only] ApiTest: state of the quota

---

docs/extensions/graph/spaces.md

just a small fix to make it render correctly

fix formatting

---

changelog/unreleased/update-libregraph-api.md
go.mod
go.sum
graph/pkg/service/v0/drives.go
graph/pkg/service/v0/errorcode/errorcode.go

Update Libre Graph Api
Use the latest version of the spec
- CI

graph update

---

tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/ArchiverContext.php
tests/acceptance/features/bootstrap/RevaContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

Just minor changes that PHPstorm IDE told me about.
CI

[tests-only] Minor local API test changes

---

changelog/unreleased/space-membership.md
storage/pkg/command/frontend.go

Added a missing config value to the ocs config related to the space membership endpoint.

add missing config for space membership endpoint

---

tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/apiSpaces/shareSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

Add test:
- test case 1:
- test case 2:
- ...

[tests-only] ApiTest: share space

---

tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/apiSpaces/listSpaces.feature
tests/acceptance/features/apiSpaces/quota.feature
tests/acceptance/features/apiSpaces/shareSpaces.feature
tests/acceptance/features/apiSpaces/uploadSpaces.feature

These are suggested scenario descriptions for the `apiSpaces` features.
Discussion is welcome! I think we should remove the detail about expected HTTP status and other expectations from the description. Those are written in the test steps. The description can just be a "short" sentence about what the scenrio is supposed to test.
Some scenarios were already in the form "some user can do something", so I kept with that "can do"/"cannot do" form. It reads nicely for me. I removed specific mention of Alice and Brian from the descriptions - that is just test step detail that is intended to help someone who reads the scenario.
What do you think?
CI

[tests-only] Reword Spaces API scenario descriptions

---

tests/acceptance/features/bootstrap/SpacesContext.php

1) refactor `userHasSharedSpace` to reduce code duplication
2) get `baseUrl` once and store it in SpacesContext and use it from there, to remove the duplication of processing the value with `str_ends_with` etc
That's enough from me!
CI

[tests-only] Refactor SpacesContext

---

docs/ocis/getting-started/_index.md

update the getting started docs section to make it work again
CC @KatGiz

update getting started

---

docs/extensions/accounts/tests.md
docs/extensions/settings/tests.md

[docs-only] Add docs for locally running accounts&settings ui tests

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

This PR bumps core commit id and updates the expected to fail file
- Part of: https://github.com/owncloud/QA/issues/713
- CI

[tests-only][full-ci]Bump the commit id for tests

---

docs/extensions/storage/storagedrivers.md

[docs-only] add known kernel limits, deprecate owncloud driver

---

.drone.star

Pin acceptance test middleware version

---

graph/pkg/service/v0/graph_test.go

One of the ginkgo tests was flaky because of a not ordered json.
See here: https://drone.owncloud.com/owncloud/ocis/8825/6/4

[tests-only] Fix flaky yaml tests

---

changelog/unreleased/delete-spaces.md
go.sum
graph/pkg/service/v0/drives.go

When a user tries to purge an enabled space we want to return an error.
Spaces need to be deleted in 2 steps. First disabling second deleting the space.
- locally using curl

prevent purging of enabled spaces

---

graph/pkg/service/v0/drives.go

Just refactored the filter handling for list storage spaces

refactor ListStorageSpaces filter handling

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/shareSpaces.feature
tests/acceptance/features/apiSpaces/uploadSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

I have added tests in which a user with different permissions tries to create a folder/file in a shared space
But not everything is fine, there is a bug: https://github.com/owncloud/ocis/issues/3002

Share space api test

---

docs/ocis/deployment/kubernetes.md

The ocis-charts were move to the owncloud org.

[docs-only] Change helm repo url

---

go.mod
go.sum
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md

fixes failing spaces sharing tests. See https://github.com/owncloud/ocis/issues/3002 for details

[full-ci][tests-only] Bump reva

---

graph/pkg/identity/backend.go
graph/pkg/identity/cs3.go
graph/pkg/identity/ldap.go
graph/pkg/identity/ldap/reconnect.go
sonar-project.properties
storage/pkg/config/defaultconfig.go

Fixed some code smells pointed out by sonarcloud.

Fix code smells

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/deleteSpaces.feature
tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
tests/acceptance/features/apiSpaces/removeSpaces.feature
tests/acceptance/features/apiSpaces/uploadSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

- added test "create subfolder"
- added the ability to search objects in subfolders of the space 
- added tests "deleting object from space" and "deleting space"
- created bug: https://github.com/owncloud/ocis/issues/3031

ApiTests. remove objects from space.

---

changelog/unreleased/graph-api-user-groups.md
go.mod
go.sum
graph/pkg/identity/backend.go
graph/pkg/identity/cs3.go
graph/pkg/identity/ldap.go
graph/pkg/service/v0/groups.go
graph/pkg/service/v0/instrument.go
graph/pkg/service/v0/logging.go
graph/pkg/service/v0/service.go
graph/pkg/service/v0/tracing.go

This depends on: https://github.com/owncloud/libre-graph-api/pull/23 for the libre-graph-api updates

Support for Group Management via Graph

---

.drone.env

That was easy - none of the renamed feature files are in expected-failures. So no expected-failure edits needed.
https://github.com/owncloud/QA/issues/715
CI

[tests-only] [full-ci] bump core commit id to include 39743 feature name changes

---

.drone.env

https://github.com/owncloud/QA/issues/715

[tests-only] [full-ci] bump commit id for core dav spaces refactor 39746

---

storage/pkg/config/config.go

add STORAGE_PERMISSIONS_ENDPOINT env variable

add STORAGE_PERMISSIONS_ENDPOINT env variable

---

tests/acceptance/features/apiSpaces/restoreSpaces.feature
tests/acceptance/features/apiSpaces/shareSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

- added tests: user without permissions try to restore space
- added checking: who is owner and who has be granted

ApiTest. Checking owner and permissions

---

.drone.env

Bump core commit to the latest up to `2022-02-15`
- Part of https://github.com/owncloud/QA/issues/721
- CI

[tests-only][full-ci] bump core commit to the latest upto `2022-02-15`

---

changelog/unreleased/change-use-description-during-space-creation.md
go.mod
go.sum
graph/pkg/service/v0/drives.go
tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

Add Space Description during space creation

Create space with description

---

changelog/unreleased/update-reva.md

Prepare the reva changelog for the upcoming oCIS release

[docs-only] prepare reva update changelog

---

docs/ocis/release_notes.md

draft mode. reva changelog still missing.

oCIS 1.17 release notes

---

changelog/unreleased/add-ordering-list-drives.md
graph/pkg/service/v0/drives_test.go
graph/pkg/service/v0/ordering.go

adds to #3200 
- test case 1:
- test case 2:
- ...

fix ordering of names

---

docs/ocis/adr/0003-external-user-management.md
docs/ocis/adr/0017-allow-read-only-external-user-management.md

ADR about integrating with external read-only identity management solutions.
cc @micbar @butonic

[docs-only] ADR: Add first draft for readonly external user management

---

nats/pkg/command/server.go
nats/pkg/logging/nats.go
nats/pkg/server/nats/nats.go
nats/pkg/server/nats/options.go

- makes NATS killable by passing a context from the runtime (`ocis kill nats`)
- NATS will die when it encounters an fatal error (like we noticed in the CI during nightlies)
- Fixes nightly CI issues? Hopefully!
- manually

[full-ci] NATS integration fixes

---

.drone.star

We will upload our binaries to following locations:
- for master builds:
`/ocis/ocis/daily/...`
- for rc / beta / alpha builds:
`/ocis/ocis/testing/...`
- for non rc / beta / alpha builds:
`/ocis/ocis/stable/...`
- fixes #3263

adapt new folder layout on the download mirror

---

accounts/pkg/service/v0/service.go
docs/ocis/getting-started/demo-users.md
ocs/pkg/server/http/svc_test.go
settings/pkg/service/v0/settings.go

adds katherine as a new user with space-manager permissions
- requested by @michaelstingl 
easily play around with spaces

add katherine to demo users

---

graph/pkg/config/reva.go

fix graph jwt secret from `OCS_JWT_SECRET` to `GRAPH_JWT_SECRET`

fix graph jwt secret

---

storage/pkg/command/sharing.go

This PR adds support for the cs3 metadata storage public share manager.
Manual testing
- [] Documentation ticket raised: <link>

[full-ci] Add support for the cs3 publicshare manager

---

docs/clients/rclone/webdav-sync-basic-auth.md
docs/ocis/development/testing.md
docs/ocis/getting-started/_index.md
docs/ocis/migration.md

Little grammar changes that were in PR #3380 
We can merge these and discuss other changes separately.
N/A

[docs-only] Some grammar that the IDE noticed while I had these docs open

---

docs/ocis/getting-started/_index.md

- Update ocis Download URLs
- test case 1:
- test case 2:
- ...

new download urls

---

changelog/unreleased/fix-docs.md
ocis-pkg/log/option.go

we can add this changelog to add more doc fixes

Fix golang api docs

---

changelog/unreleased/update-web-5.4.0.md

Fix typo in web bump readme

---

.bingo/Variables.mk
.bingo/variables.env
.drone.star
Makefile
audit/Makefile
graph-explorer/Makefile
idp/Makefile
web/Makefile

- fail in for loops
- make curl fail
- since we fail now, I also needed to remove unused make targets from the audit service (it has no yarn and no protobuf)

improve makefile error handling

---

changelog/unreleased/alias-links.md
go.mod
go.sum
proxy/pkg/middleware/basic_auth.go
tests/acceptance/expected-failures-API-on-OCIS-storage.md

Allows links with empty permissions. These are considered alias links.
Adds endpoint to get data about these links
See reva PR for curl examples: https://github.com/cs3org/reva/pull/2687
- test case 1:
- test case 2:
- ...

[full-ci] Alias Links

---

.drone.star

Add cs3ApiValidator https://github.com/owncloud/cs3api-validator#readme
API Acceptance tests for the CS3 APIs
- CI

[tests-only] add cs3api validator

---

docs/ocis/development/beta-testplan.md

For the beta program we need test plan which the participants can work through and report feedback.
https://jira.owncloud.com/browse/OCB-4

[docs-only] manual testplan for ocis beta

---

docs/ocis/development/beta-testplan.md

extra docs and links for the IDP configuration
https://jira.owncloud.com/browse/OCB-4
- test case 1:
- test case 2:
- ...

[docs-only] IDP documentation for the beta testplan

---

docs/ocis/deployment/ocis_traefik.md

Add C:\Windows\System32\Drivers\etc\hosts

Add C:\Windows\System32\Drivers\etc\hosts to the doc

---

idp/pkg/server/debug/server.go
ocis-pkg/shared/healthchecklist.go

This PR adds a reference implementation for health & readiness endpoint in IDP

Add reference implementation for health & readiness endpoint in IDP

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
tests/acceptance/features/bootstrap/SpacesContext.php

added apiTest:
- users can see the files in the trash
- and restore files from the trash

[tests-only] apiTest: list of trash files and restore files from the trash

---

.drone.star
changelog/unreleased/update-reva.md
go.mod
go.sum

Bumps reva version and removes forked go-cs3apis
- test case 1:
- test case 2:
- ...

Bump reva version

---

changelog/unreleased/update-reva.md
go.mod
go.sum

- test case 1:
- test case 2:
- ...

[full-ci] update reva to 2.2.0

---

.drone.star

Retry on all HTTP response codes indicating and error.

[tests-only] Improve wait-for-ocis check

---

.dockerignore

fixes the dockerfile in the ocis repo root
make ocis buildable with only docker installed (no go and no nodejs / yarn)
- test case 1:
- test case 2:
- ...

fix dockerfile in the ocis root

---

tests/acceptance/features/apiSpaces/shareSpaces.feature
tests/acceptance/features/apiSpaces/shareSubItemOfSpaceViaPublicLink.feature

- rework shareSpaces.feature
- add test creating public link to file with edit permissions
pr will be ready after merge https://github.com/owncloud/core/pull/39973

[test-only]apiTest: create public link to file with edit permissions

---

.gitignore

modifies the gitignore:
- removes uneeded entries (we don't write certificates / autogenerated config / ... into the repo anymore)
- orders the entries
- adds comments
just some basic housekeeping
- test case 1:
- test case 2:
- ...

update and order gitignore, remove uneeded entries

---

deployments/examples/ocis_wopi/config/wopiserver/entrypoint-override.sh
deployments/examples/ocis_wopi/config/wopiserver/wopiserver.conf.dist
deployments/examples/ocis_wopi/docker-compose.yml

updates the wopiserver configuration in the wopi deployment example to reflect the latest featureset
- 
- test case 1:
- test case 2:
- ...

[deployment-examples] update wopiserver config

---

docs/extensions/idm/_index.md
docs/extensions/idm/configuration_hints.md

Just some minor wording/spelling fixes.

[docs-only] Language review on new IDM section

---

ocis/pkg/command/accounts.go
ocis/pkg/command/audit.go
ocis/pkg/command/glauth.go
ocis/pkg/command/graph.go
ocis/pkg/command/graphexplorer.go
ocis/pkg/command/idm.go
ocis/pkg/command/idp.go
ocis/pkg/command/natsserver.go
ocis/pkg/command/notifications.go
ocis/pkg/command/ocdav.go
ocis/pkg/command/ocs.go
ocis/pkg/command/proxy.go
ocis/pkg/command/settings.go
ocis/pkg/command/storageappprovider.go
ocis/pkg/command/storageauthbasic.go
ocis/pkg/command/storageauthbearer.go
ocis/pkg/command/storageauthmachine.go
ocis/pkg/command/storagefrontend.go
ocis/pkg/command/storagegateway.go
ocis/pkg/command/storagegroupprovider.go
ocis/pkg/command/storagemetadata.go
ocis/pkg/command/storagepubliclink.go
ocis/pkg/command/storageshares.go
ocis/pkg/command/storagesharing.go
ocis/pkg/command/storageuserprovider.go
ocis/pkg/command/store.go
ocis/pkg/command/thumbnails.go
ocis/pkg/command/web.go
ocis/pkg/command/webdav.go

fixes config parsing for subcommands
- test case 1:
- test case 2:
- ...

fix ocis config parsing for subcommands

---

extensions/search/pkg/config/defaults/defaultconfig.go
extensions/search/pkg/search/index/index.go
extensions/search/pkg/search/provider/events.go
extensions/search/pkg/search/provider/searchprovider.go
extensions/search/pkg/search/provider/searchprovider_test.go

This PR fixes searching files in shares.

[full-ci] Fix searching shares

---

.vscode/launch.json

some env vars seem to be wrong
bug tracked in https://github.com/owncloud/ocis/issues/3677

set OCIS_SYSTEM_USER_ID

---

ocis/pkg/command/init.go

When a user tries oCIS for the first time he will most likely use `ocis init` to generate the configuration.
This users first impression of oCIS will be a typo.
- test case 1:
- test case 2:
- ...

[tests-only] Fix first contact typo

---

extensions/settings/pkg/config/defaults/defaultconfig.go
extensions/storage-system/pkg/command/server.go
extensions/storage-system/pkg/revaconfig/config.go
ocis/pkg/init/init.go

align more storage-system names

---

changelog/unreleased/update-reva.md
go.mod
go.sum

Update reva to the released version `v2.3.0`
- #3627 
- Full CI

[full-ci] update reva to v2.3.0

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

https://github.com/owncloud/QA/issues/738

[tests-only] [full-ci] Bump CORE_COMMITID for tests

---

.drone.env

https://github.com/owncloud/QA/issues/738
Runs trashbin test changes that were just merged to core master in PR https://github.com/owncloud/core/pull/40050

[tests-only] [full-ci] Bump CORE_COMMITID to include new trashbin test code

---

.make/go.mk

adapts compile time options after switch to v2
- Fixes #3688
- test case 1:
- test case 2:
- ...

fix compile time options after switch to v2

---

extensions/proxy/pkg/middleware/basic_auth.go

- [Fixes TUS Uploads to public links](https://github.com/owncloud/ocis/issues/3588)
- test case 1:
- test case 2:
- ...

[tests-only] [full-ci] Add "/data" to list of public URLs in proxy

---

docs/ocis/development/testing.md

documentation got outdates, these days we have to 
1. set `IDM_ADMIN_PASSWORD=admin` for init to get a default not-random admin password
2. run init with `--insecure true` to make it not care about certificates 
3. set more variables when running the tests to be able to test with the graph API
correct documentation

[docs-only] improve docs of running API acceptance tests

---

extensions/storage-users/pkg/config/config.go
extensions/webdav/pkg/config/config.go

two env vars have wrong naming
fixes: https://github.com/owncloud/ocis/issues/3710

Fix env var naming

---

changelog/unreleased/update-reva.md
go.mod
go.sum

- test case 1:
- test case 2:
- ...

[full-ci] update reva to v2.3.1

---

ocis/pkg/command/init.go

reword ocis init from ocis to Infinite Scale

---

changelog/unreleased/webdav-env-doc.md
extensions/webdav/pkg/config/http.go
extensions/webdav/pkg/config/log.go
extensions/webdav/pkg/config/tracing.go

Added descriptions to webdav config structs to include them in the config documentation.
/cc @mmattel

add description tags to webdav config

---

deployments/continuous-deployment-config/ocis_keycloak/released.yml
deployments/continuous-deployment-config/ocis_ldap/released.yml
deployments/continuous-deployment-config/ocis_traefik/released.yml
deployments/continuous-deployment-config/ocis_wopi/released.yml

- test case 1:
- test case 2:
- ...

switch "released" continous deployment instances to v2.0.0-beta1

---

docs/ocis/deployment/systemd.md

Just wanted to highlight this section since this is important and can be easily overlooked.

[docs-only] highlight critical section via a warning box

---

extensions/users/pkg/config/config.go
extensions/users/pkg/config/defaults/defaultconfig.go
extensions/users/pkg/revaconfig/config.go

Add descriptions for users service config

---

extensions/storage-shares/pkg/config/config.go
extensions/storage-shares/pkg/config/defaults/defaultconfig.go
extensions/storage-shares/pkg/revaconfig/config.go

Configure the provider id of the shares storage provider. Based on https://github.com/cs3org/reva/pull/2829

Configure the provider id of the shares storage provider

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-webUI-on-OCIS-storage.md

https://github.com/owncloud/QA/issues/739

[tests-only] [full-ci] Bump commit id for API tests

---

extensions/audit/pkg/config/config.go

highligh the independence of the stdout and file log options of the audit service
- test case 1:
- test case 2:
- ...

add comment about independence of log outputs

---

extensions/app-provider/pkg/config/config.go
extensions/app-registry/pkg/config/config.go
extensions/audit/pkg/config/debug.go
extensions/auth-basic/pkg/config/config.go
extensions/auth-bearer/pkg/config/config.go
extensions/auth-machine/pkg/config/config.go
extensions/frontend/pkg/config/config.go
extensions/gateway/pkg/config/config.go
extensions/graph-explorer/pkg/config/debug.go
extensions/graph/pkg/config/debug.go
extensions/groups/pkg/config/config.go
extensions/idm/pkg/config/debug.go
extensions/idp/pkg/config/debug.go
extensions/nats/pkg/config/debug.go
extensions/notifications/pkg/config/debug.go
extensions/ocdav/pkg/config/config.go
extensions/ocs/pkg/config/debug.go
extensions/proxy/pkg/config/debug.go
extensions/search/pkg/config/debug.go
extensions/settings/pkg/config/debug.go
extensions/sharing/pkg/config/config.go
extensions/storage-publiclink/pkg/config/config.go
extensions/storage-shares/pkg/config/config.go
extensions/storage-system/pkg/config/config.go
extensions/storage-users/pkg/config/config.go
extensions/store/pkg/config/debug.go
extensions/thumbnails/pkg/config/debug.go
extensions/users/pkg/config/config.go
extensions/web/pkg/config/debug.go
extensions/webdav/pkg/config/debug.go

add debug config setting descriptions
- test case 1:
- test case 2:
- ...

add descriptions to the debug config

---

docs/ocis/development/beta-testplan.md

- We create user via graph api, so I changed docs in: https://owncloud.dev/ocis/development/beta-testplan/

beta-plan docs: change method creating user

---

changelog/unreleased/save-katherine.md
extensions/idm/ldif/demousers.ldif

We lost Katherine in the depths of IDM. Now she gloriously returns.
- Fixes https://github.com/owncloud/ocis/issues/3823
- test case 1:
- test case 2:
- ...

Bring katherine back

---

extensions/settings/package.json
extensions/settings/yarn.lock

Only bumping the dependencies that finally land in the shipped JS bundle (for now)

Bump prod deps of settings service UI

---

extensions/search/pkg/search/index/index.go
extensions/storage-system/pkg/config/config.go
extensions/storage-users/pkg/revaconfig/config.go
extensions/webdav/pkg/service/v0/search.go
go.mod
go.sum

This PR adds the required config for the `FileUploaded` event fix from https://github.com/cs3org/reva/pull/2882.
It also fixes a problem where recursive updates in the index were only applied to the first 10 children.

Fix file uploaded event

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/changeSpaces.feature

ApiTests. set no restriction quota

---

extensions/users/pkg/config/config.go

found while setting up https://github.com/owncloud/ocis/issues/3847

add missing USERS_DRIVER env var

---

changelog/unreleased/update-web-5.5.0.md

Had a wrong PR link in the changelog item of https://github.com/owncloud/ocis/pull/3862
Fixing it here in a followup

Fix pr link in changelog item

---

changelog/unreleased/update-reva.md
go.mod
go.sum

- test case 1:
- test case 2:
- ...

[full-ci] update reva to 2.4.1

---

deployments/examples/ocis_keycloak/docker-compose.yml

fixes the oidc config in the keycloak deployment example
- test case 1:
- test case 2:
- ...

fix oidc issuer config in the keycloak example

---

extensions/sharing/pkg/config/defaults/defaultconfig.go

add missing owncloudsql default config to sharing service

add missing default config

---

.drone.env

Bump core commit id on OCIS to match the latest master.
- Part of https://github.com/owncloud/QA/issues/744
- CI

[tests-only] [full-ci] Bump core commit id on ocis to match latest

---

changelog/unreleased/update-reva.md
go.mod
go.sum

update reva to v2.5.1

---

.drone.star
tests/config/drone/setup-for-litmus.sh

This PR add litmus tests on CI
- old-endpoint ( TESTS= " basic copymove props http " )
- new-endpoint ( TESTS= " basic copymove props http " )
- new-shared ( TESTS= " basic copymove props http " )
- old-shared ( TESTS= " basic copymove props http " )
- public-share ( TESTS= " basic copymove http " )
- spaces-endpoint ( TESTS= " basic copymove props http " )
- [Litmus test results](https://github.com/owncloud/ocis/issues/1266)
- CI

[full-ci][tests-only] Add litmus tests on CI

---

.drone.env

- Part of https://github.com/owncloud/QA/issues/744
- test case 1:
- test case 2:
- ...

[full-ci][tests-only] bumped core commit id to latest in ocis

---

.drone.star

This PR skips litmus tests in docs-only.
- [litmus tests fail on docs-only PRs](https://github.com/owncloud/ocis/issues/3947)
- CI [https://drone.owncloud.com/owncloud/ocis/12464]

[tests-only]Skip litmus on docs-only title

---

docs/ocis/getting-started/_index.md

Use the beta3 in the Getting Started Guide.

[docs-only] Bump getting started guide to beta3

---

deployments/continuous-deployment-config/ocis_keycloak/released.yml
deployments/continuous-deployment-config/ocis_ldap/released.yml
deployments/continuous-deployment-config/ocis_traefik/released.yml
deployments/continuous-deployment-config/ocis_wopi/released.yml

updates the "released" deployment examples to beta.3
- test case 1:
- test case 2:
- ...

update "released" deployment examples to beta.3

---

.drone.env

Includes core API test fix from core PR https://github.com/owncloud/core/pull/40133
https://github.com/owncloud/QA/issues/744
CI

[tests-only] [full-ci] Bump CORE_COMMITID

---

docs/helpers/configenvextractor.go

This PR adds missing error handling to the config extractor.

Add missing error handling to configextractor

---

changelog/unreleased/audit-service.md
extensions/audit/pkg/service/service_test.go
extensions/audit/pkg/types/constants.go
extensions/audit/pkg/types/conversion.go
extensions/graph/pkg/service/v0/groups.go
extensions/graph/pkg/service/v0/password.go
extensions/graph/pkg/service/v0/users.go

Added the acting user to the events in the audit log.

Add the acting user to the events in the audit log.

---

.drone.env

Bump core commit id for the tests
part of https://github.com/owncloud/QA/issues/747

[tests-only][full-ci] Bump core commit id for the tests

---

extensions/search/pkg/search/provider/events.go
extensions/search/pkg/search/provider/events_test.go
extensions/search/pkg/search/provider/searchprovider.go
extensions/search/pkg/service/v0/service.go
go.mod
go.sum

This PR makes the search provider listen and react to `FileTouched` events.
- Fixes https://github.com/owncloud/ocis/issues/3154

Handle file touched events

---

.gitignore

for more detail please read https://go.dev/blog/get-familiar-with-workspaces

ignore go.work files

---

changelog/2.0.0_2022-06-22/update-reva-beta.4.md
go.mod
go.sum

Update reva to version 2.6.1
- Needed for #3986 
- test case 1:
- test case 2:
- ...

[full-ci] update reva to 2.6.1

---

deployments/examples/ocis_wopi/.env

Pin the cs3org/wopiserver to version `8.3.0`
- Related to #3986 
- test case 1:
- test case 2:
- ...

Pin wopiserver version

---

deployments/continuous-deployment-config/ocis_keycloak/released.yml
deployments/continuous-deployment-config/ocis_ldap/released.yml
deployments/continuous-deployment-config/ocis_traefik/released.yml
deployments/continuous-deployment-config/ocis_wopi/released.yml
docs/ocis/getting-started/_index.md

update released deployments and docs to beta.4
- test case 1:
- test case 2:
- ...

update docs and deployments from beta.3 to beta.4

---

services/graph/pkg/identity/ldap.go

graph: Fix LDAP filter formatting for GetUsers and GetGroups

---

.drone.star
services/settings/.eslintrc.js
services/settings/package.json
services/settings/ui/app.js
services/settings/ui/tests/acceptance/pageobjects/filesPageSettingsContext.js
services/settings/ui/tests/acceptance/pageobjects/settingsPage.js
services/settings/yarn.lock

Tried my best bumping dependencies of the settings service and updated the linting to be more similar to other oC `web` projects

Bump & sort & update settings service deps, update linting

---

.drone.star
services/graph-explorer/Makefile
services/idp/Makefile
services/settings/.eslintrc.js
services/settings/Makefile
services/settings/package.json
services/settings/ui/app.js
services/settings/ui/tests/acceptance/helpers/language.js
services/settings/ui/tests/acceptance/pageobjects/filesPageSettingsContext.js
services/settings/ui/tests/acceptance/pageobjects/settingsPage.js
services/settings/yarn.lock
services/web/Makefile

Reactivate currently skipped settings service (perhaps needs more work than a boolean switch)
Fixes #4056

Unskip settings service acceptance tests

---

.github/CODEOWNERS
.github/dependabot.yml

Update dependabot & codeowners after accounts removal & extension->service renaming

---

.drone.star

This PR caches the yarn for webUITets so that it will be reused across the webUI pipelines
- Fixes https://github.com/owncloud/ocis/issues/4047
- CI

[full-ci][tests-only]cache yarn dependencies for web UI tests

---

Dockerfile
docs/ocis/_index.md
docs/ocis/deployment/bridge.md
docs/ocis/storage/users.md
docs/services/settings/tests.md
ocis-pkg/config/envdecode/README.md
ocis/pkg/runtime/README.md

This is a simple change to documentation to avoid a popular issue with adjective order relating to words like 'above', 'below', 'follows', etc.
None.  It's trivial.
- improve readibility
- follow standards
- reduce frowns in readers
As a doc change, I've done no testing.  I don't currently use the software, nor have a test rig.

nit - adjective order in documentation

---

services/frontend/pkg/config/config.go
services/idp/pkg/config/http.go
services/ocdav/pkg/config/config.go
services/proxy/pkg/config/http.go

add missing config descriptions
- Fixes #4147
-

add missing config descriptions

---

go.mod
go.sum

Bump libregraph/idm to latest master

---

.drone.star
tests/acceptance/expected-failures-API-on-OCIS-storage.md

This PR skips `caldav` and `carddav` api request on `OCIS`
https://github.com/owncloud/ocis/issues/4130

[tests-only][full-ci]Skip caldav and carddav request on OCIS CI

---

deployments/examples/ocis_wopi/.env

fetch latest docker for wopiserver

deployments: unpin wopiserver version

---

.drone.star

continuation of https://github.com/owncloud/ocis/pull/4112
This PR drops more pipelines for tagging as mentioned in https://github.com/owncloud/ocis/issues/3630#issuecomment-1189102282
- Fixes https://github.com/owncloud/ocis/issues/3630
- CI

[full-ci][tests-only] Drop more piplines for tagging

---

.drone.env
tests/acceptance/expected-failures-webUI-on-OCIS-storage.md

Gets recent test changes including https://github.com/owncloud/core/pull/40222
https://github.com/owncloud/QA/issues/753
CI

[tests-only] [full-ci] Bump CORE_COMMITID for API tests

---

.drone.star

- Part of: https://github.com/owncloud/ocis/issues/3962
- CI

[tests-only][full-ci]Cache web repo for tests

---

.drone.star

This PR adds retry option in: 
-  make command in `makeNodeGenerate()`
- make command in `makeGoGenerate()`
- make command in `build()`
- Part of: https://github.com/owncloud/ocis/issues/3962
- CI

[full-ci][tests-only] Add retry option

---

services/audit/pkg/config/config.go
services/graph/pkg/config/config.go
services/notifications/pkg/config/config.go
services/search/pkg/config/config.go
services/sharing/pkg/config/config.go
services/storage-system/pkg/config/config.go
services/storage-users/pkg/config/config.go

Adds more description to the various `Events` structs used for configuring eventing
- test case 1:
- test case 2:
- ...

[docs-only] Update description for event structs

---

.drone.star
services/search/Makefile
services/search/pkg/search/index/index_test.go
services/search/pkg/search/provider/searchprovider_test.go

Search unit test where not running in ci. Now they do
- test case 1:
- test case 2:
- ...

[tests-only] Add search unit test to ci

---

.github/CODEOWNERS
deployments/continuous-deployment-config/oc10_ocis_parallel/latest.yml
deployments/continuous-deployment-config/ocis_hello/latest.yml
deployments/continuous-deployment-config/ocis_individual_services/latest.yml
deployments/continuous-deployment-config/ocis_keycloak/latest.yml
deployments/continuous-deployment-config/ocis_keycloak/released.yml
deployments/continuous-deployment-config/ocis_ldap/latest.yml
deployments/continuous-deployment-config/ocis_ldap/released.yml
deployments/continuous-deployment-config/ocis_s3/latest.yml
deployments/continuous-deployment-config/ocis_traefik/latest.yml
deployments/continuous-deployment-config/ocis_traefik/released.yml
deployments/continuous-deployment-config/ocis_wopi/latest.yml
deployments/continuous-deployment-config/ocis_wopi/released.yml

- test case 1:
- test case 2:
- ...

update code owners and continous deployment config

---

.drone.star

This PR updates the image `meltwater/drone-cache:v1` to official S3 cache plugin `plugins/s3-cache:1`.
Changes done in `.drone.star`:
1. Used official S3 cache plugin image `plugins/s3-cache:1` for cache rebuild, restore, and purge instead of `meltwater/drone-cache:v1` image
2. Refactored the steps settings configuration as per the S3 cache plugin
- Fixes https://github.com/owncloud/ocis/issues/4123
- CI

[full-ci] [tests-only] Using `plugins/s3-cache:1` instead of `meltwater/drone-cache:v1`

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
tests/acceptance/features/apiSpaces/shareSpacesViaLink.feature
tests/acceptance/features/bootstrap/SpacesContext.php

- added api test to edit public link
- to the expected failures added issues: https://github.com/owncloud/ocis/issues/4260 https://github.com/owncloud/ocis/issues/4262

[tests-only] [full-ci] Api test. edit public link

---

go.mod
go.sum
services/notifications/pkg/command/server.go
services/notifications/pkg/service/service.go
services/postprocessing/pkg/postprocessing/postprocessing.go
services/postprocessing/pkg/service/service.go

Send the user an email when an infected file was found
- test case 1:
- test case 2:
- ...

[tests-only][full-ci]Notify user on infected files

---

.drone.env
.drone.star

[full-ci] Run e2e tests in ocis CI

---

.drone.env
changelog/unreleased/update-web-beta.6.md
services/web/Makefile
tests/acceptance/expected-failures-webUI-on-OCIS-storage.md

Bump web assets to v5.7.0-rc.7

[full-ci] bump web to v5.7.0-rc.7

---

go.mod
go.sum

Bump reva to pull in the upload cleanup feature.

[full-ci] Bump reva

---

changelog/unreleased/add-drives-endpoint-and-userfilter.md
services/graph/pkg/service/v0/users.go

Fix listing of drives on a single user.
- test case 1:
- test case 2:
- ...

fix listing of drives and quota

---

changelog/unreleased/update-web-beta.6.md
services/web/Makefile

[full-ci] bump web to v5.7.0-rc.8

---

services/storage-users/pkg/command/root.go
services/storage-users/pkg/command/uploads.go
services/storage-users/pkg/config/config.go
services/storage-users/pkg/config/defaults/defaultconfig.go
services/storage-users/pkg/revaconfig/config.go

Fixes #2622
Depends on https://github.com/cs3org/reva/pull/3095

Add a cli for listing and cleaning up expired uploads

---

docs/templates/ADOC.tmpl

- test case 1:
- test case 2:
- ...

remove unused length from adoc template

---

changelog/unreleased/update-web-beta.6.md
services/web/Makefile

NEEDS REBASE after #4369  is merged
- test case 1:
- test case 2:
- ...

[full-ci] Update web 5.7.0.rc9

---

ocis-pkg/bytesize/bytesize.go
ocis-pkg/bytesize/bytesize_test.go
services/graph/pkg/config/config.go
services/graph/pkg/service/v0/drives.go
services/graph/pkg/service/v0/graph.go
services/graph/pkg/service/v0/service.go
services/proxy/pkg/command/server.go
services/proxy/pkg/config/config.go
services/proxy/pkg/middleware/create_home.go
services/proxy/pkg/middleware/options.go

We can now define default and maximum quota amounts for personal and project spaces
- test case 1:
- test case 2:
- ...

[full-ci] [tests-only] Max and Default Quotas

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/shareOperations.feature
tests/acceptance/features/bootstrap/SpacesContext.php

This PR adds tests removed by core PR https://github.com/owncloud/core/pull/40275, these tests were removed form core because they request in path `/shares` in `spaces` endpoint and as there is no `shares` in `spaces` and `spaces` won't be implemented in `oc10` the tests weren't relevant there. Thus they're added here.
- part of: 
- https://github.com/owncloud/ocis/issues/4154
- https://github.com/owncloud/QA/issues/759
- locally
- CI

[tests-only][full-ci]Add tests removed by core 40275 and bump core commit id

---

changelog/unreleased/enhancment-admin-pwreset.md
docs/services/idm/admin_password_reset.md
go.mod
go.sum
services/idm/pkg/command/resetpw.go
services/idm/pkg/command/root.go

This allows resetting the ocis admin user's password (when ocis is not running) when running with the builtin LDAP server.
- Fixes #4084
```
ocis idm resetpassword
```

Add `ocis idm resetpassword` subcommand

---

.drone.star

In this PR, short-term artifacts are cached into the `cache` bucket and cached artifacts in the particular build are purged after the build is completed with status success or failure. 
The purge method cannot be called when the build is canceled so purging is done on the nightly build. 
Also, it clears empty directories which were created during the rebuilding cache and those not cleared by the build purge.
- Fixes https://github.com/owncloud/QA/issues/757
- Fixes https://github.com/owncloud/QA/issues/758
- CI

[full-ci] [tests-only] Cache short-term artifacts to `cache` bucket

---

.drone.star

Follow-up on https://github.com/owncloud/ocis/pull/4311
```
Error: depends_on github-comment for pipeline purge_build_artifact_cache is not defined
Error: depends_on stop-build for pipeline purge_build_artifact_cache is not defined
```
The build is failing on build https://drone.owncloud.com/owncloud/ocis/14494, this might be due to the pipeline `purge_build_artifact_cache` depending on `failEarly`. Earlier the motive to add this was to purge the cache when there is an early fail but we are not going to purge the cache immediately after build. So the purging after `failEarly` does not make any sense.
- Fixes https://drone.owncloud.com/owncloud/ocis/14494
- CI

[full-ci] [tests-only] Removing dependency with earlyfail for purge

---

services/graph/pkg/service/v0/drives.go
services/graph/pkg/service/v0/service.go
services/proxy/pkg/middleware/create_home.go

Adds simple endpoint to get the current default quotas defined in the server. Usage:
Simple get to the the new endpoint does the trick. NOTE: default personal quota cannot be reported at the moment
```
curl --insecure -X GET -u admin:admin https://localhost:9200/graph/v1.0/drivequotas
{"max_personal_quota":1000000000000000,"default_project_quota":10000000000,"max_project_quota":1000000000000}
```
endpoint is only reachable when authenticated
```
curl --insecure -X GET https://localhost:9200/graph/v1.0/drivequotas
{"error":{"code":"InvalidAuthenticationToken","innererror":{"date":"2022-08-12T11:15:38Z","request-id":"jkoberg-20ud0010ge/TDWen7LUUz-000006"},"message":"Access token is empty."}
```
- test case 1:
- test case 2:
- ...

[tests-only] Expose default quotas to client

---

.drone.star

Pin selenium image to `standalone-chrome:104.0-20220812` which has an updated chrome version.
run webui tests against ;latest browser version

[tests-only][full-ci] Pin selenium image to standalone-chrome:104.0-20220812

---

ocis-pkg/config/envdecode/README.md
services/notifications/pkg/config/config.go

While investigating issue #4460 I was using these typo fixes to test what CI triggered. We may as well apply the fixes.
N/A

[docs-only] Fix typo 2022-08-26

---

services/graph/pkg/service/v0/users.go

This add support for expanding the user's group membershiips to '/me':
```
{
"displayName": "Albert Einstein",
"id": "4c510ada-c86b-4815-8820-42cdf82c3d51",
"mail": "einstein@example.org",
"memberOf": [
{
"displayName": "users",
"id": "509a9dcd-bb37-4f4f-a01a-19dca27d9cfa"
},
{
"displayName": "sailing-lovers",
"id": "6040aa17-9c64-4fef-9bd0-77234d71bad0"
},
{
"displayName": "violin-haters",
"id": "dd58e5ec-842e-498b-8800-61f2ec6f911f"
},
{
"displayName": "physics-lovers",
"id": "262982c1-2362-4afa-bfdf-8cbfef64a06e"
}
],
"onPremisesSamAccountName": "einstein"
}
```
The spec update for the generated clients is in: https://github.com/owncloud/libre-graph-api/pull/53
Fixes: #4283

graph: Add $expand=memberOf support to /me

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

related #4485 and https://github.com/owncloud/core/pull/40330

[tests-only] removed the search test from the expected failures

---

changelog/unreleased/update-reva-beta8.md
go.mod
go.sum
tests/acceptance/features/bootstrap/SpacesContext.php

Update reva to latest edge.
- test case 1:
- test case 2:
- ...

[full-ci] update Reva to latest edge

---

services/graph/pkg/service/v0/users.go

DELETE requess on /graph/v1.0/users also work when specifing a user by name. For deleting the home space in that case we need to get the User's id from the backend first.
Fixes: #4195

Fix home space deletion when deleting user by name

---

tests/acceptance/config/behat.yml

- part of: https://github.com/owncloud/QA/issues/764
- CI

[tests-only]Add context in behat.yml

---

.drone.star
.php-cs-fixer.dist.php
Makefile
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/SpacesTUSContext.php

This PR fixes all the errors that appears with command for checking coding-standard-php (locally) and also adds the `coding-standard-php` pipeline on ocis.
https://github.com/owncloud/ocis/issues/4503

[tests-only][full-ci]Add coding standard php pipeline

---

tests/acceptance/features/apiSpaces/favorite.feature
tests/acceptance/features/bootstrap/SpacesContext.php

Refactor step and reuse code from core for `favorite.feature`.
https://github.com/owncloud/ocis/issues/4509

[full-ci][tests-only]Refactor and Reuse code from core

---

tests/acceptance/features/bootstrap/SpacesContext.php

Reuse code (resource) from core for `checksum.feature`
https://github.com/owncloud/ocis/issues/4509

[tests-only][full-ci]Reuse code from core

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/search.feature
tests/acceptance/features/bootstrap/SpacesContext.php

I added some cases: 
- find hidden/deleted/pending/declined folders
- find folder- shares mountpoint
- find project space by name (#4506)

[tests-only] ApiTests. add more search tests

---

tests/acceptance/features/apiAccountsHashDifficulty/addUser.feature
tests/acceptance/features/apiAccountsHashDifficulty/createShareToSharesFolder.feature
tests/acceptance/features/apiAccountsHashDifficulty/uploadFile.feature
tests/acceptance/features/apiAccountsHashDifficulty/webDavPUTAuthInvalid.feature

This PR skips the tests related to `apiAccountsHashDifficulty` in reva as those are ocis specific
- Part of: https://github.com/owncloud/QA/issues/764
- CI

[tests-only][full-ci]Skip ocis specific tests in reva

---

tests/acceptance/features/bootstrap/SpacesContext.php

This PR implements the missing undefined steps for `localSpaceApiTests`.
https://github.com/owncloud/ocis/issues/4563

[tests-only][full-ci]Check for the undefined steps after update on core

---

.drone.env
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/apiSpaces/copySpaces.feature
tests/acceptance/features/apiSpaces/createFileFolderWhenSharesSpaceExist.feature
tests/acceptance/features/apiSpaces/download.feature
tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
tests/acceptance/features/apiSpaces/filePreviews.feature
tests/acceptance/features/apiSpaces/listSpaces.feature
tests/acceptance/features/apiSpaces/moveSpaces.feature
tests/acceptance/features/apiSpaces/quota.feature
tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
tests/acceptance/features/apiSpaces/restoreSpaces.feature
tests/acceptance/features/apiSpaces/search.feature
tests/acceptance/features/apiSpaces/shareSpaces.feature
tests/acceptance/features/apiSpaces/shareSpacesViaLink.feature
tests/acceptance/features/apiSpaces/shareSubItemOfSpace.feature
tests/acceptance/features/apiSpaces/shareSubItemOfSpaceViaPublicLink.feature
tests/acceptance/features/apiSpaces/uploadSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

This PR makes use of the code already present in OC10 inorder to limit duplication
- part of: 
- https://github.com/owncloud/ocis/issues/4509
- https://github.com/owncloud/QA/issues/766
- CI
- locally

[tests-only][full-ci]Reuse the core code

---

services/sharing/pkg/config/defaults/defaultconfig.go

Default to jsoncs3 share manager

[tests-only][full-ci] Default to jsoncs3 share manager

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/shareUploadTUS.feature
tests/acceptance/features/apiSpaces/tusUpload.feature
tests/acceptance/features/bootstrap/SpacesTUSContext.php

This PR adds the tests for TUS upload related to /Shares which are removed from the core with this PR https://github.com/owncloud/core/pull/40305 as /Shares related implementation is not in core and is shifted to oCIS.
Bump commit id of core to include PR https://github.com/owncloud/core/pull/40369
- Part of https://github.com/owncloud/ocis/issues/4154#issuecomment-1206026045
- Part of https://github.com/owncloud/QA/issues/766
- Locally
- CI

[full-ci] [tests-only] Move tests from `core` to `oCIS` related to `/Shares` of TUS upload

---

services/notifications/pkg/config/config.go

Referencing: #4564 (Add email templating)
Just a small text update for the environmet variable description.
(I was too late getting it into the main PR)

Update Notification Service eMail Template env var description

---

go.mod
go.sum
services/ocdav/pkg/command/server.go
services/ocdav/pkg/config/config.go
services/ocdav/pkg/config/defaults/defaultconfig.go

Allows configuring ocis to scan files before download

[tests-only] OnAccess scanning

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/expected-failures-webUI-on-OCIS-storage.md

This PR check the expected to failure file and make sure there is not any tests that is not mentioned to an issue.
Also cleans up some description and lines to make maintain format consistency.
https://github.com/owncloud/QA/issues/716

[tests-only][full-ci]Check for issue not mentioned to a test

---

services/postprocessing/pkg/service/service.go

Fixes nasty panic in postprocessing service

[tests-only] Don't panic in Postprocessing service

---

docs/ocis/storage/_index.md
docs/ocis/storage/namespaces.md
docs/ocis/storage/proposedchanges.md
docs/ocis/storage/spaces.md
docs/ocis/storage/spacesprovider.md
docs/ocis/storage/spacesregistry.md
docs/ocis/storage/storagedrivers.md
docs/ocis/storage/terminology.md
docs/ocis/storage/users.md

some doc fixes and clarification for storage drivers related to https://github.com/owncloud/ocis/issues/4638

[docs-only] update storage docs

---

services/notifications/pkg/email/templates/virusdetected.email.tmpl
services/notifications/pkg/service/service.go

Uses templating system also for virus detected emails

[tests-only] Virusdetected email template

---

docs/ocis/storage-backends/dcfsnfs.md

This PR improves a few inconsistencies in NFS share docs after testing it manually, so that it works as expected.
- Part of: https://github.com/owncloud/ocis/issues/4595
In order to make sure that the documents are up-to-date with the current system
- manually

[docs-only]Improve the documentation for NFS share

---

tests/acceptance/features/bootstrap/SpacesContext.php

`sendPropfindRequestToUrl` is only used once and it directly uses `send` request so we can remove it and send request from the function it self
- Part of: https://github.com/owncloud/ocis/issues/4509
- locally
- CI

[tests-only] Remove the propfind method

---

CHANGELOG.md
changelog/unreleased/tokeninfo-endpoint-auth.md
go.mod
go.sum
services/proxy/pkg/middleware/authentication.go
services/proxy/pkg/middleware/authentication_test.go

Keep experimental up-to-master

[full-ci][tests-only] Merge master into experimental

---

services/search/pkg/service/grpc/v0/service.go

On every search request bleve opens the index file, for which it needs to allocate some memory. Bombing the server with search requests will therefore cause the pod being OOM killed. 
To Avoid that we added a simple cache (ttl 1 second - not configurable). 
One could still ddos the system by sending different search request, we need to think about a solution for that too.

[tests-only] Cache search results

---

services/postprocessing/pkg/postprocessing/postprocessing.go

[tests-only] Fix DelayPostprocessing functionality

---

services/frontend/pkg/revaconfig/config.go
services/ocdav/pkg/config/defaults/defaultconfig.go

enables enterprise features for clients

[tests-only] Enable enterprise features

---

go.mod
go.sum
services/storage-users/pkg/revaconfig/user.go

adds the cache config also to s3ng

[full-ci][tests-only] Configure cache for s3ng

---

go.mod
go.sum

[tests-only][full-ci] Use experimental reva instead fork

---

services/web/pkg/config/defaults/defaultconfig.go

Merge back we branch

---

services/search/pkg/engine/bleve.go

update bleve document mapping and use fulltext analyser.

fulltext search mapping

---

services/search/pkg/search/provider.go

Use userIDs instead of userNames when indexing spaces

[skip ci] Use userID when indexing spaces

---

services/search/pkg/command/index.go

Update search cli flag description

Change search cli command flag description

---

ocis-pkg/registry/registry.go

We want caching for all registries except "memory".

Fix condition for registry cache

---

tests/acceptance/expected-failures-webUI-on-OCIS-storage.md

This PR removes lines from expected failures which were skipped by PR https://github.com/owncloud/web/pull/7766
- Fixes https://github.com/owncloud/ocis/issues/4804
- CI

[full-ci] [tests-only] Removed lines from expected failures

---

.drone.env

Update ownCloud core commit ID for the tests.
- Part of https://github.com/owncloud/QA/issues/767
- :robot: 
---

[tests-only] bump ownCloud core commit id for the tests

---

services/search/pkg/engine/bleve.go
services/search/pkg/search/provider.go

[skip ci] FixSpaceIndexing

---

changelog/unreleased/logging-improvements.md
ocis-pkg/log/log.go
ocis-pkg/middleware/logger.go
services/graph/pkg/identity/cs3.go
services/graph/pkg/identity/ldap.go
services/graph/pkg/middleware/auth.go
services/graph/pkg/service/v0/drives.go
services/graph/pkg/service/v0/errorcode/errorcode.go
services/graph/pkg/service/v0/graph.go
services/graph/pkg/service/v0/groups.go
services/graph/pkg/service/v0/users.go
services/proxy/pkg/middleware/accesslog.go
services/thumbnails/pkg/service/http/v0/service.go
services/webdav/pkg/service/v0/search.go
services/webdav/pkg/service/v0/service.go

#4815 forward port
Better debugging experience
- test case 1:
- test case 2:
- ...

[experimental] harden drives api and improve logging

---

services/search/pkg/config/search.go
services/search/pkg/search/events.go

Allow multiple event consumers per search instance

[tests-only] Multi consumer search

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

This PR refactor  expected failure file related to the closed issue 
- https://github.com/owncloud/core/pull/40392
- locally

[tests-only][full-ci]Refactor expected-failure-api-on-ocis-file

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

Bump the ownCloud core commit ID to the latest upto Oct 20, 2022.
- Part of https://github.com/owncloud/QA/issues/767
---

[tests-only][full-ci] bump ownCloud core commit ID for the tests

---

services/webdav/pkg/service/v0/search.go

Display Tags in search

---

services/notifications/pkg/service/service.go

We use now private links to create the link

Fix space invitation link

---

services/web/pkg/assets/server.go

Expires header was set even if no-cache header is present, this pr removes it.

Remove expires header for no-cache assets

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

This PR bump core commit id to latest.
- Part of : https://github.com/owncloud/QA/issues/768
Updates tests/line changes made by pr https://github.com/owncloud/core/pull/40393
- CI

[full-ci][tests-only]Bump core commit id for tests

---

.drone.star
tests/acceptance/config/behat.yml
tests/acceptance/features/apiContract/report.feature
tests/acceptance/features/apiSpaces/search.feature
tests/acceptance/features/bootstrap/SpacesContext.php

Idea: 
- Create api tests as contract tests. 
- Tests should check the status of the response and check elements in the body of the response

[test-only] ApiTest.check all response items 

---

services/thumbnails/README.md

@mmattel, here is the README for the thumbnails service including the warning about large files crashing the thumbnails service.

add a readme file for the thumbnails service

---

services/webdav/README.md

adds a `README.md` to the webdav service

Readme for Webdav service

---

services/nats/README.md

Adds a readme to the nats service

Readme for Nats service

---

services/proxy/pkg/config/config.go

This is just a small rephrasing of one env var of the proxy service for better readability.

Proxy env var description rephrasing

---

services/proxy/README.md

This is my first draft for the proxy readme file.
/cc @mmattel

add proxy README

---

docs/ocis/development/beta-testplan.md

just a small typo, the user should be logged in not the admin

fix typo in beta testplan

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

Bump core commit id to include PR https://github.com/owncloud/core/pull/40463.
- Part of https://github.com/owncloud/QA/issues/768
- :robot:

[full-ci] [tests-only] Bump core commit id

---

services/web/pkg/assets/server.go

bring experimental asset caching back into master
- From https://github.com/owncloud/ocis/pull/4876
disable caching for assets that delivers underlying library files with hash.
- local installation with header inspection

cherry-pick - remove expires header in no-cache cases

---

services/frontend/README.md

add an initial frontend readme

[docs-only] add frontend readme

---

ocis/README.md

Here is a README for the ocis package with some information about the service registries.
/cc @mmattel

add a README to the ocis package

---

services/auth-basic/README.md

Adds a readme file for the auth-basic service

Readme for Auth-Basic

---

README.md

bump copyright

---

services/notifications/pkg/service/service.go

Cherry-picks this: https://github.com/owncloud/ocis/pull/4872

Cherry-pick spaceinvite fix

---

changelog/unreleased/logging-improvements.md
services/frontend/pkg/revaconfig/config.go
services/ocdav/pkg/config/config.go
services/ocdav/pkg/config/defaults/defaultconfig.go
services/storage-users/pkg/revaconfig/config.go

We improve the logging of several http services. If possible and present, we now log the `X-Request-Id`.
Better debuggability
- test case 1:
- test case 2:
- ...

add requestID middleware

---

deployments/continuous-deployment-config/ocis_keycloak/released.yml
deployments/continuous-deployment-config/ocis_ldap/released.yml
deployments/continuous-deployment-config/ocis_traefik/released.yml
deployments/continuous-deployment-config/ocis_wopi/released.yml

- Part of #4986 
- test case 1:
- test case 2:
- ...

update released deployments to 2.0.0-rc.1

---

README.md

fixes https://github.com/owncloud/ocis/issues/4995

[docs-only] update readme

---

.drone.star
.make/release.mk
changelog/unreleased/remove-windows.md

Enhancement: Remove windows from ci & relase makefile
We have removed windows from the ci & release makefile
refs #5011

remove windows from ci & release makefile

---

tests/acceptance/features/apiSpacesShares/shareSpaces.feature

Added API tests for sharing spaces with and without `manager` permission.
1. `Scenario Outline: A user with editor or viewer role cannot share a space to another user`
2. `Scenario Outline: A user with manager role can share a space to another user`
- Part of https://github.com/owncloud/ocis/issues/4937 (share space without manager permission)
- Locally
- CI

[full-ci] [tests-only] Added api test for sharing spaces with/out manager permission

---

deployments/examples/oc10_ocis_parallel/docker-compose.yml
deployments/examples/ocis_hello/docker-compose.yml
deployments/examples/ocis_keycloak/docker-compose.yml
deployments/examples/ocis_ldap/docker-compose.yml
deployments/examples/ocis_s3/docker-compose.yml
deployments/examples/ocis_traefik/docker-compose.yml
deployments/examples/ocis_wopi/docker-compose.yml

improves the debugability of our deplyoment examples
- helped during https://github.com/owncloud/client/issues/10275
have the access log in ocis and traefik
- -

improve debugability of deployment examples

---

docs/architecture/efficient-stat-polling.md
docs/architecture/upload-processing.md

I'm not sure this is actually accurate ... but I was cleaning up branches ...
- fixes broken diagrams on https://owncloud.dev/architecture/efficient-stat-polling/
- adds docs on upload processing

[docs-only] Upload processing docs

---

tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature

This PR expands the existing share test of a public link to permission 0 (internal).
- :robot: 
- Locally

[full-ci] [tests-only] Share test expanded for permission 0, internal

---

tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

This PR adds api tests for changing the role of a member of the space
- Part of : https://github.com/owncloud/ocis/issues/4937
- locally
- CI

[tests-only][full-ci]Add api tests for changing role of a space

---

services/app-provider/pkg/config/config.go
services/idp/pkg/config/config.go
services/nats/pkg/config/config.go
services/proxy/pkg/config/config.go

Fixes: https://github.com/owncloud/ocis/issues/5073#issuecomment-1325185490
@wkloucek pls have a look if the WOPI_INSECURE change is correct

Fix some env descriptions

---

go.mod
go.sum

Update the Graph API to the released version `v1.0.0`
- test case 1:
- test case 2:
- ...

bump libre graph API to v1.0.0

---

docs/ocis/deployment/ocis_keycloak.md

changed path to .env

---

docs/ocis/development/deprecating-variables.md

This PR adds dev-docs for deprecating variables.
refs #3917 
refs #5143

Add dev-docs for variable deprecation process

---

tests/acceptance/features/apiGraph/deleteUser.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR adds an acceptance API test for user delete using graph API.
Scenarios Added:
1. `Scenario: the admin user deletes a user`
2. `Scenario: Delete a user and specify the user name in different case`
3. `Scenario Outline: the admin user deletes another user with different role`
4. `Scenario: the admin user tries to delete his/her own account`
5. `Scenario: the admin user tries to delete a non-existent user`
6. `Scenario Outline: Non-admin user tries to delete another user`
- Locally
- :robot:

[full-ci] [tests-only] Added api test for delete user using graph API

---

README.md

Announcement of supported and released status of oCIS in the README.md file
:rocket:

Update README.md - announcement of supported and released status

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

This PR bumps core commit id for tests
- Part of: https://github.com/owncloud/QA/issues/782
- 
- CI

[tests-only][full-ci]Bump commit id for tests

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md

The failing tests were linked to issue https://github.com/owncloud/ocis/issues/3872 which is closed now and the current issue is https://github.com/owncloud/ocis/issues/5049. So this PR updates the issue link and title
- CI

[tests-only]Update the expected to fail to use correct issue link

---

.drone.star

- test case 1:
- test case 2:
- ...

fix changelog pipeline

---

services/graph/README.md

@micbar, I don't know if there is anything more to say about this service, what do you think?

add a README to the graph package

---

docs/ocis/deployment/ocis_keycloak.md

Fixed punctuation and added the (intended) line break
- test case 1:
- test case 2:
- ...

Fixed punctuation and layout

---

tests/acceptance/features/apiSpaces/listSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

[tests-only][full-ci] Extend API contract tests for GET drives/spaces

---

docs/ocis/storage/storagedrivers.md

I guess `NFSv45` should be `NFSv4`

Corrected typo

---

docs/helpers/adoc-generator.go.tmpl
docs/helpers/configenvextractor.go
docs/helpers/environment-variable-docs-generator.go.tmpl
ocis-pkg/ldap/ldap.go
ocis-pkg/log/logrus_wrapper.go
ocis-pkg/service/grpc/client.go
ocis/pkg/init/init.go
services/gateway/pkg/revaconfig/config.go
services/graph/pkg/service/v0/driveitems_test.go
services/graph/pkg/service/v0/graph_test.go
services/graph/pkg/service/v0/groups_test.go
services/graph/pkg/service/v0/service.go
services/graph/pkg/service/v0/users_test.go
services/idp/pkg/service/v0/service.go
services/proxy/pkg/middleware/authentication.go
services/proxy/pkg/middleware/oidc_auth.go
services/proxy/pkg/proxy/proxy.go
services/proxy/pkg/proxy/proxy_integration_test.go
services/settings/pkg/store/filesystem/assignments.go
services/settings/pkg/store/filesystem/bundles.go
services/settings/pkg/store/filesystem/io.go
services/settings/pkg/store/filesystem/values.go
services/store/pkg/service/v0/service.go
services/web/pkg/command/server.go

remove deprecated use of ioutil

---

tests/acceptance/features/apiGraph/editUser.feature
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/RoleAssignmentContext.php

This PR adds an acceptance API test for user delete using graph API.
Scenarios Added:
1. `  Scenario: the admin user can edit another user email`
2. `Scenario: the admin user can override an existing user email of another user`
3. `Scenario: the admin user cannot clear an existing user email`
4. `Scenario Outline: a normal user should not be able to change their email address`
5. `Scenario Outline: a normal user should not be able to edit another user's email`
6. `Scenario: the admin user can edit another user display name`
7. `Scenario: the admin user cannot clear another user display name`
8. `Scenario Outline: a normal user should not be able to change their display name`
9. `Scenario Outline: a normal user should not be able to edit another user's display name`
10. `Scenario: the …

[full-ci] [tests-only] Added api test for edit user using graph API

---

ocis-pkg/middleware/token.go
ocis-pkg/middleware/token_test.go

followup PR of https://github.com/owncloud/ocis/pull/5199#issuecomment-1346331838

token middleware: use constant time comparison

---

tests/acceptance/features/apiGraph/deleteUser.feature
tests/acceptance/features/apiGraph/editUser.feature
tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/RoleAssignmentContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

Merge commit from `master` to `stable-2.0`
These https://github.com/owncloud/ocis/pull/5150, https://github.com/owncloud/ocis/pull/5102, https://github.com/owncloud/ocis/pull/5023 are the PRs merged to `master` 
- :robot:

[full-ci] [tests-only] Port api test

---

.drone.star
tests/acceptance/config/behat.yml
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiCors/cors.feature

Getting PR #5187 to the master

[tests-only][full-ci] Add CORS API tests (#5187)

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

- Updates the changes made by - https://github.com/owncloud/core/pull/40534
- CI

[tests-only][full-ci] Bump commit id for tests

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

Updates expected to fail file for changes made by https://github.com/owncloud/core/pull/40534
- Part of: https://github.com/owncloud/QA/issues/785
- CI

[tests-only][full-ci]Bump core commit id for tests

---

tests/acceptance/features/apiContract/propfind.feature
tests/acceptance/features/apiContract/report.feature
tests/acceptance/features/bootstrap/SpacesContext.php

- Part of: https://github.com/owncloud/ocis/issues/4937
- locally
- CI

[tests-only][full-ci]Add api test for propfind

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature

- Part of: https://github.com/owncloud/ocis/issues/4937
- locally
- CI

[tests-only][full-ci]Extended public link tests to have more checks

---

tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
tests/acceptance/features/bootstrap/SpacesContext.php

merge commit from master to stable 2.0

check unrestricted quota (#5173)

---

.make/l10n.mk
services/settings/l10n/.tx/config

Fix translation sync. https://github.com/owncloud-ci/transifex/pull/52

fix: fix syntax after switching to golang tx client

---

services/settings/ui/components/settings/SettingMultiChoice.vue
services/settings/ui/components/settings/SettingSingleChoice.vue

- test case 1:
- test case 2:
- ...

[settings] Do not use v-model and input event for the same component

---

.golangci.yml
services/graph/pkg/service/v0/drives.go
services/graph/pkg/service/v0/drives_test.go
services/graph/pkg/service/v0/groups.go
services/graph/pkg/service/v0/users.go
services/idp/pkg/command/server.go
services/ocs/pkg/service/v0/groups.go
services/ocs/pkg/service/v0/users.go
services/settings/pkg/store/filesystem/assignments.go
services/settings/pkg/store/filesystem/bundles.go
services/settings/pkg/store/filesystem/values.go
services/sharing/pkg/config/parser/parse.go
services/thumbnails/pkg/service/grpc/v0/service.go
services/webdav/pkg/propfind/propfind.go

* Exclude some directories from the linting step.
* Fix some linting issues.

Linter fixes

---

README.md

No code change
Adding a TOC to README.md as discussed with @kobergj + updating the copyright year to 2023

Add a toc to readme.md

---

services/postprocessing/README.md
services/postprocessing/pkg/config/config.go

Adds a readme for new postprocessing service.
@EParzefall @phil-davis a language review is very welcomed 😄

[docs-only] Postprocessing Readme

---

docs/.gitignore
docs/apis/_index.md

- test case 1:
- test case 2:
- ...

add more api docs

---

tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

technical debt:
create test  for https://github.com/owncloud/ocis/issues/3402
If I send random UUIDs I get 404

[test-only] ApiTest. sending invalid data to graph API

---

tests/acceptance/features/apiContract/propfind.feature
tests/acceptance/features/apiContract/report.feature
tests/acceptance/features/bootstrap/SpacesContext.php

This test has been added in `stable` branch in https://github.com/owncloud/ocis/pull/5138, this PR ports the changes to master branch as well
- https://github.com/owncloud/ocis/issues/4937
To make the tests in both branches the same.
-CI

[tests-only][full-ci]Port api test for propfind to master

---

tests/acceptance/features/apiContract/propfind.feature
tests/acceptance/features/apiContract/report.feature
tests/acceptance/features/bootstrap/SpacesContext.php

Backport this PR https://github.com/owncloud/ocis/pull/5266 merged on `stable-2.0` to `master` branch.

[tests-only][full-ci]Backport response should contain refactor to `master` branch

---

tests/acceptance/features/apiContract/propfind.feature

Backport the PR merged https://github.com/owncloud/ocis/pull/5252 on `stable-2.0` to `master`

[tests-only][full-ci]Backport expand propfind test for spacemember

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

- This PR bump commits id of the core and web to check core API test scenario passes in ocis
https://github.com/owncloud/QA/issues/791
- test case 1:
- test case 2:
- ...

[tests-only][full-ci]Bump commit id 

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/getUser.feature
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

1. `admin user gets the information of a user`
2. `non-admin user tries to get the information of a user`
3. `admin user gets all users`
4. `non-admin user tries get all user`
5. `admin user gets the drive information of a user`
6. `normal user gets his/her own drive information`
https://github.com/owncloud/ocis/issues/4937

[tests-only][full-ci]Added test for getting user information by admin or normal user using Graph API

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/getUser.feature
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

This is a port of PR #5149 from master to stable-2.0
CI

[tests-only][full-ci]Added test for getting user information by admin or normal user using Graph API (stable-2.0)

---

deployments/continuous-deployment-config/ocis_wopi/latest.yml
deployments/examples/ocis_wopi/.env
deployments/examples/ocis_wopi/docker-compose.yml

- test case 1:
- test case 2:
- ...

[tests-only] add tika and inbucket to wopi example

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

There was a bug that when a user sends a patch request to another user's space they could list drive information even though they don't have the necessary permission to do so.  this adds the tests to cover this fixed bug. 
- Adds test for: https://github.com/owncloud/ocis/issues/5030
- locally 
- CI

[tests-only][full-ci]Adds tests for sending PATCH request to other user's space

---

tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

These changes were made by https://github.com/owncloud/ocis/pull/5275 on `stable-2.0` branch but weren't ported to master so this PR fixes that.
- Test for https://github.com/owncloud/ocis/issues/3402
- CI

[tests-only][full-ci] Forward port send invalid UUID master

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

Bump core commit id to the latest
Part of https://github.com/owncloud/QA/issues/792

[tests-only][full-ci] Bump core commitid (master)

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

This PR forward ports the changes made by PR https://github.com/owncloud/ocis/pull/5320 to master
- test for https://github.com/owncloud/ocis/issues/5030
- CI
- locally

[tests-only][full-ci]Adds tests for sending PATCH request to other user's space - porting from stable to master

---

tests/acceptance/features/apiContract/copy.feature
tests/acceptance/features/bootstrap/SpacesContext.php

[tests-only] [full-ci] Apitest. check Copy response headers test

---

tests/acceptance/config/behat.yml
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpacesShares/publicLinkDownload.feature
tests/acceptance/features/bootstrap/SpacesContext.php

[tests-only] [full-ci] Add api tests public link folder download master

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md

This was accidentally committed to stable-2.0 in PR #5311 - fix it.
The problem is not in master.
CI

[tests-only] [full-ci] Remove accidental HEAD line from expected-failures

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature

[tests-only] [full-ci] Extended public link tests to have more checks

---

docs/ocis/deployment/kubernetes.md

Path was incorrect
- Fixes incorrect path
Confusing documentation 
- clone repo
- check path

Incorrect charts path

---

tests/acceptance/features/bootstrap/PublicWebDavContext.php
tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
tests/acceptance/features/coreApiWebdavOperations/propfind.feature

Add PROPFIND tests for the public link endpoint
- Part of https://github.com/owncloud/ocis/issues/5336

[tests-only][full-ci] Add PROPFIND tests for public link endpoint

---

docs/ocis/guides/ocis-local-docker.md

Final Solution translates to "Endlösung", which is connotated with the holocaust. We can do better.

[docs-only] Update ocis-local-docker.md

---

tests/TestHelpers/HttpRequestHelper.php
tests/acceptance/features/bootstrap/AuthContext.php
tests/acceptance/features/bootstrap/WebDavPropertiesContext.php

Porting php codes from PR https://github.com/owncloud/ocis/pull/5328

[tests-only][full-ci] Port async upload php codes

---

tests/acceptance/features/apiSpaces/tusUpload.feature
tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature
tests/acceptance/features/bootstrap/SpacesTUSContext.php

ApiTest. Forward port - change test create new tus resource

---

docs/apis/http/graph/_index.md
docs/apis/http/graph/groups.md
docs/apis/http/graph/spaces.md
docs/apis/http/graph/users.md

- add graph api authentication section
- some edit link fixes

[docs-only] graph api authentication, edit link fixes

---

docs/helpers/extendedEnv.go
docs/templates/ADOC_extended.tmpl

Leftover from PR https://github.com/owncloud/ocis/pull/5364

[docs-only] Leftover fix

---

Makefile
docs/Makefile
docs/helpers/README.md
docs/helpers/adoc-generator.go.tmpl
docs/helpers/configenvextractor.go
docs/helpers/environment-variable-docs-generator.go.tmpl
docs/helpers/extendedEnv.go
docs/helpers/extended_vars.yaml
docs/helpers/main.go
docs/templates/ADOC_extended.tmpl
docs/templates/ADOC_global.tmpl

Backports new docs helpers (extended and global envvars)
fixes: https://github.com/owncloud/ocis/issues/5377

[docs-only] Backport Docs Helpers to 2.0

---

services/graph/pkg/identity/ldap_test.go

This tests the CreateUser functions.
Fixes #5375

Test CreateUser

---

tests/acceptance/features/coreApiVersions/fileVersions.feature

Porting PR https://github.com/owncloud/ocis/pull/5379
Test for https://github.com/owncloud/ocis/issues/5010

[tests-only][full-ci] Added tests for checking version of file uploaded with same mtime twice

---

changelog/unreleased/enhancement-name-attributes.md
services/graph/pkg/identity/ldap.go
services/graph/pkg/identity/ldap_test.go

This PR makes it so that givenName and surname attributes are returned for users.
Fixes #5386

Display surname and givenName attributes.

---

.drone.env
services/web/Makefile
tests/acceptance/expected-failures-webUI-on-OCIS-storage.md

- test case 1:
- test case 2:
- ...

[full-ci] chore: update web assets to v7.0.0-rc.7

---

docs/helpers/README.md

backports https://github.com/owncloud/ocis/pull/5393

[docs-only] Backport docs README

---

tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature

This PR forward ports the changes made by PR https://github.com/owncloud/ocis/pull/5401 
- Test for: https://github.com/owncloud/ocis/issues/4758
- local
- CI

[tests-only][full-ci] Adds tests for checking href of the public link share - master

---

tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature

This PR adds test scenarios for updating role of a public link to internal.
- Issue #4979 
- Locally
- CI

[tests-only][full-ci] Add tests scenarios for updating role of public link to internal

---

.drone.star
Makefile
docs/ocis/development/testing.md

* change docs
backport https://github.com/owncloud/ocis/pull/5430 to stable-2.0

[docs-only] Change Testing section in the doc (#5430)

---

tests/acceptance/features/apiSpaces/tag.feature
tests/acceptance/features/bootstrap/TagContext.php

- added test for deleting tags

[test-only] ApiTest. deleteTag test. increase coverage

---

go.mod
go.sum
services/graph/pkg/identity/cs3.go

Bump to latest master to get recent change for 'education' endpoints

Bump libregraph-api-go

---

services/graph/pkg/identity/ldap_education_school.go
services/graph/pkg/identity/ldap_education_school_test.go

GET /education/schools/{school-id}/users
POST /education/schools/{school-id}/users/$ref
and
DELETE /education/schools/{school-id}/users/$ref
are supposed to also work when using the schoolNumber as the '{school-id}' parameter. This fix that functionality. This also makes the the mocks for the LDAP Modify operations more specific to avoid using the generic mock.Anything

graph: fix adding users to educationSchool by schoolNumber

---

changelog/unreleased/space-management-permissions.md
go.mod
go.sum
services/settings/pkg/store/defaults/defaults.go

Adds new space management permissions

Space Management Permissions

---

docs/helpers/adoc-generator.go.tmpl
docs/templates/ADOC.tmpl
docs/templates/ADOC_deprecation.tmpl

Fixes broken documentation when deprecating envvars

[docs-only] Fix Envvar Deprecation

---

docs/apis/http/graph/spaces.md

- test case 1:
- test case 2:
- ...

[docs-only] rewrite spaces API docs

---

go.sum
services/graph/pkg/service/v0/groups.go
services/graph/pkg/service/v0/service.go

In some case we want to run the graph service standalone without depending on any of the other ocis services. This PR fixes a couple of issue with that.

Fix running the graph service standalone

---

.drone.star
deployments/examples/ocis_wopi/docker-compose.yml

keep offices and wopiserver up to date in the deployment examples
- -
prevent bitrot
- docker-compose up on my pc and use the office suites

keep offices and wopi server up to date

---

.golangci.yml

set readonly mode as proposed in https://github.com/golangci/golangci-lint/discussions/1920#discussioncomment-2873371
CI is currently very unstable and often fails in the linting phase, trying to fix it
ran tests 3 times and all linting passed

[tests-only] fix flacky go linting

---

.golangci.yml

[tests-only][master]run golangci-lint in readonly mode

---

tests/acceptance/features/apiSpaces/quota.feature
tests/acceptance/features/bootstrap/OCSContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

It is forward-port of PR https://github.com/owncloud/ocis/pull/5479 into `master` branch.

[tests-only][full-ci] Forward-port of relative quota amount of personal space tests

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/bootstrap/OccContext.php
tests/acceptance/features/bootstrap/PublicWebDavContext.php
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/TrashbinContext.php
tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature

This PR removes step `the administrator has enabled DAV tech_preview`, and DAV tech preview related implementations and codes.
https://github.com/owncloud/ocis/issues/5519
- :robot:

[full-ci] [tests-only] Remove dav tech preview step

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/bootstrap/OccContext.php
tests/acceptance/features/bootstrap/PublicWebDavContext.php
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/TrashbinContext.php
tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature

This PR forward port changes related to remove DAV tech preview steps 
-  https://github.com/owncloud/ocis/pull/5526
- Locally

[tests-only][full-ci]Forward port remove DAV tech preview steps 

---

tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

fixed tests `shareSpaces.feature:37` `shareSpaces.feature:45`
- test case 1:
- test case 2:
- ...

[test-only] Fix failed test

---

.drone.env
services/web/Makefile
tests/acceptance/features/bootstrap/SpacesContext.php

[full-ci] chore: bump web v7.0.0-rc.12

---

tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature

This PR adds a test to delete the expiration of a share subitem of space
- Part of: https://github.com/owncloud/ocis/issues/5413
- local
- ci

[full-ci][tests-only]Add api test to delete the expiration date from a share subitem of space

---

tests/acceptance/features/apiSpacesShares/shareSpaces.feature

- Added more test cases to share space to groups

[test-only]ApiTest. increases permissions for one member of the group

---

tests/acceptance/features/bootstrap/SpacesContext.php

This PR fixes the flaky test 
- Fixes : https://github.com/owncloud/ocis/issues/5544
The test was failing because it searched for the index `group` in the array it was looping through and the index doesn't exist in every loop so the check fails with `Undefined index: group in /drone/src/tests/acceptance/features/bootstrap/SpacesContext.php line 3285` this PR checks if the index is set . 
- locally
- CI

[tests-only][full-ci]fix flaky test apiSpacesShares/shareSpaces.feature:42

---

docs/ocis/development/testing.md
docs/ocis/guides/ocis-local-docker.md
tests/acceptance/docker/Makefile
tests/acceptance/docker/src/acceptance.yml
tests/acceptance/docker/src/ocis-base.yml
tests/acceptance/docker/src/run-tests.sh

The docs for testing with docker is outdated so this PR makes it according to the current system configuration
https://owncloud.dev/ocis/development/testing/#testing-with-test-suite-in-docker

[docs-only]Update testing docs

---

changelog/unreleased/space-trashbin-purge-cli.md
services/storage-users/pkg/command/root.go
services/storage-users/pkg/command/server.go
services/storage-users/pkg/command/trash_bin.go
services/storage-users/pkg/config/config.go
services/storage-users/pkg/config/defaults/defaultconfig.go
services/storage-users/pkg/event/event.go
services/storage-users/pkg/event/service.go
services/storage-users/pkg/event/trigger.go
services/storage-users/pkg/task/task.go
services/storage-users/pkg/task/task_suite_test.go
services/storage-users/pkg/task/trash_bin.go
services/storage-users/pkg/task/trash_bin_test.go

Introduction of a new cli command to purge old trash-bin items.
The command is part of the `storage-users` service and can be used as follows:
`ocis storage-users trash-bin purge-expired`.
The `purge-expired` command configuration is done in the `ocis`configuration or as usual by using environment variables.
ENV `STORAGE_USERS_PURGE_TRASH_BIN_USER_ID` is used to obtain space trash-bin information and takes the system admin user as the default `OCIS_ADMIN_USER_ID`.
It should be noted, that this is only set by default in the single binary. The command only considers spaces to which the user has access and delete permission.
ENV `STORAGE_USERS_PURGE_TRASH_BIN_PERSONAL_DELETE_BEFORE` has a default value of `30 days`, which means the command will delete all files older than `30 days`.
The …

Space Trash-bin expiration cli

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiGraph/getApplications.feature
tests/acceptance/features/bootstrap/GraphContext.php

- added tests for getting application list https://owncloud.dev/libre-graph-api/#/applications/ListApplications https://owncloud.testrail.io/index.php?/cases/view/2404

[test-only] Api test. get applications list.

---

changelog/unreleased/enhancement-change-username.md
services/graph/pkg/identity/ldap.go
services/graph/pkg/identity/ldap_group.go
services/graph/pkg/identity/ldap_test.go

This adds support for username changing.
Fixes #4988

Add username changing functionality.

---

services/web/README.md

References: #5559 (Branding api)
@mmattel, here is a small README.
I don't really know what else to add.

[docs-only] add a small README for the web service

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiAccountsHashDifficulty/assignRole.feature

- I closed bug #5079 and deleted it from expected failures

[tests-only] delete bug #5079 from expected failures

---

services/graph/pkg/identity/ldap.go
services/graph/pkg/identity/ldap_test.go

This fixes issue #5581 by properly parsing the old DN and replacing the
first part with the new DN.

Properly generate new DN.

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiContract/propfind.feature
tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/apiSpaces/deleteSpaces.feature
tests/acceptance/features/apiSpaces/download.feature
tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
tests/acceptance/features/apiSpaces/restoreSpaces.feature
tests/acceptance/features/apiSpaces/tag.feature
tests/acceptance/features/apiSpaces/uploadSpaces.feature
tests/acceptance/features/apiSpacesShares/copySpaces.feature
tests/acceptance/features/apiSpacesShares/moveSpaces.feature
tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
tests/acceptance/features/bootstrap/SpacesContext.php

[test-only][full-ci] ApiTest. share space with expiration date

---

protogen/gen/ocis/messages/settings/v0/settings.pb.go
protogen/gen/ocis/services/settings/v0/settings.swagger.json
services/settings/pkg/config/defaults/defaultconfig.go

- test case 1:
- test case 2:
- ...

fix settings service bunldes config merge problems

---

services/proxy/pkg/user/backend/cs3.go

With 078698fdf4e7c684669172f82df6efa8c84ac0b1 the semantics of the ListRoleAssignments Call in the settings service change. It no no longer returns a "not found" error when there is not RoleAssignment for a user. We'll just get an empty list as the result.
This changes the behaviour of the default role assignment to work with the new semantics.

proxy: Fix provsioning new users with the default role

---

services/eventhistory/README.md

References: #5600 (Eventhistory Service)
Just adds an item to the readme of the eventhistory service

[docs-only] improve eventhistory service readme

---

go.mod
go.sum

To get ModifyDN support for renaming users.

Bump libregraph/idm

---

changelog/unreleased/configure-bundles.md
services/settings/pkg/config/config.go
services/settings/pkg/config/defaults/defaultconfig.go
services/settings/pkg/config/parser/parse.go

- test case 1:
- test case 2:
- ...

load bundles from JSON

---

tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

This PR adds scenarios to update the expiration date of the space in user and group share.
- Part of: https://github.com/owncloud/ocis/issues/5413
- locally
- CI

[full-ci][tests-only]Api tests for updating the expiration date of a space

---

tests/acceptance/run.sh

Port #5624 from `master` to `stable-2.0` branch.

[tests-only] Fix command format in tests/acceptance/run.sh

---

tests/acceptance/features/apiSpaces/listSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

[test-only] increase coverage test for creating space (#5616)

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiGraph/getUser.feature
tests/acceptance/features/bootstrap/GraphContext.php

[test-only] ApiTest. test for filter appRoleAssigment

---

services/frontend/pkg/config/config.go
services/proxy/README.md
services/storage-users/pkg/config/config.go

References: #5617 (add config option to set default quota per role)
This PR updates the text and descriptions added by the referenced PR.
Note that if the code gets changed to support size abbreviations like G,M etc, we either need to adapt this PR or add a subsequent PR for the text/description.

[docs-only] Update quota related texts and descriptions

---

deployments/examples/ocis_ldap/config/ldap/docker-entrypoint-override.sh
deployments/examples/ocis_ldap/config/ldap/ldif/10_base.ldif
deployments/examples/ocis_ldap/config/ldap/ldif/20_users.ldif
deployments/examples/ocis_ldap/config/ldap/ldif/30_groups.ldif
deployments/examples/ocis_ldap/config/ldap/schemas/10_owncloud_schema.ldif
deployments/examples/ocis_ldap/docker-compose.yml

Switch away from the unmaintained osixia image to the more uptodate bitnami image.
Also update the owncloud schema to include the latest changes
Fixes #5636
cc @ScharfViktor

ocis_ldap: Update to a more update OpenLDAP image

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/getGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

Forward Port: https://github.com/owncloud/ocis/pull/5593

Forward port `getallgroupmemberswithallmembers` to master

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/bootstrap/AppConfigurationContext.php
tests/acceptance/features/bootstrap/CapabilitiesContext.php
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/OCSContext.php
tests/acceptance/features/coreApiCapabilities/capabilities.feature
tests/acceptance/features/coreApiCapabilities/capabilitiesWithNormalUser.feature
vendor-bin/behat/composer.json

This is a sample PR to drill down the json response using library `helmich/phpunit-json-assert`.
Other API `suites` be followed up with PR by PR similar to this.
https://github.com/owncloud/ocis/issues/3179

[tests-only][full-ci] Json drill for `coreApiCapabilities` Suite using library

---

.drone.star
Makefile
tests/config/drone/check_go_bin_cache.sh

Forward port of PR https://github.com/owncloud/ocis/pull/5543

[tests-only] Cache go/bin as a long term cache (port #5543)

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/bootstrap/AppConfigurationContext.php
tests/acceptance/features/bootstrap/CapabilitiesContext.php
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/OCSContext.php
tests/acceptance/features/coreApiCapabilities/capabilities.feature
tests/acceptance/features/coreApiCapabilities/capabilitiesWithNormalUser.feature
vendor-bin/behat/composer.json

[tests-only][full-ci] Json drill for coreApiCapabilities Suite (port #5621)

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/bootstrap/OccContext.php
tests/acceptance/features/coreApiWebdavOperations/listFiles.feature
tests/acceptance/features/coreApiWebdavOperations/propfind.feature

This PR removes the following steps and their implementations:
- `When the administrator has set depth_infinity_allowed to :depth_infinity_allowed`
- :robot:

[full-ci] [tests-only] Remove depthinfinity related steps from occ context

---

.drone.env
services/web/Makefile

[full-ci] chore: bump web to v7.0.0-rc.16

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/apiGraph/createGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR adds tests related to adding users in a group with single request. Previous closed PR https://github.com/owncloud/ocis/pull/5609#discussion_r1116551265 contains some discussion
- https://github.com/owncloud/ocis/issues/5569
- Locally

[full-ci][tests-only] Extend tests coverage for adding users in a group with single request

---

services/graph/README.md

References: #5694 
Adding support to use `or` when filtering.

[docs-only] Update graph service readme

---

tests/acceptance/features/apiGraph/assignRole.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR expand tests coverage for assign role
- https://github.com/owncloud/ocis/issues/5564
- locally

[tests-only][full-ci]Extend tests related to assign role

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/apiGraph/createUser.feature
tests/acceptance/features/apiGraph/deleteUser.feature
tests/acceptance/features/apiGraph/editUser.feature
tests/acceptance/features/apiGraph/getUser.feature
tests/acceptance/features/apiGraph/removeUserFromGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

[test-only] ApiTest. Disable/enable user (#5639)

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/apiGraph/createGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR forward port PR https://github.com/owncloud/ocis/pull/5678
- locally

[tests-only][full-ci]Forward-port add users to a group at once 

---

.drone.env
services/web/Makefile

[full-ci] bump web to v7.0.0-rc.17

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiGraph/getGroup.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/coreApiCapabilities/capabilities.feature
tests/acceptance/features/coreApiCapabilities/capabilitiesWithNormalUser.feature

This PR adds the test for getting the details of a single group (`displayName` and `id`)
Related to issuse: https://github.com/owncloud/ocis/issues/5567

[tests-only][full-ci] test for getting details of single group

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/Provisioning.php

Follow up of: [tests-only][full-ci]Seperate test steps for positive and negative cases #5733
- Part of: https://github.com/owncloud/ocis/issues/5646
- locally
- CI

[tests-only][full-ci]Refactor test function for handeling errors

---

docs/ocis/development/getting-started.md

The go version need to be updated to v1.19

[docs-only] Update getting-started.md (for owncloud.dev)

---

changelog/unreleased/public-link-password.md
services/frontend/pkg/config/config.go
services/frontend/pkg/revaconfig/config.go
services/sharing/pkg/config/config.go
services/sharing/pkg/revaconfig/config.go

Added a new config option to enforce passwords on public links with "Uploader, Editor, Contributor" roles.

add config options to enforce passwords on public links

---

ocis-pkg/version/version.go

- test case 1:
- test case 2:
- ...

[full-ci] bump version

---

tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/apiGraph/removeUserFromGroup.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/Provisioning.php

Forward porting: https://github.com/owncloud/ocis/pull/5733 https://github.com/owncloud/ocis/pull/5745

[tests-only][full-ci]Seperate test steps for positive and negative cases

---

tests/acceptance/features/apiGraph/getGroup.feature

This PR adds the test for getting details of group having UTF-8 characters in group name.
Related to issue: https://github.com/owncloud/ocis/issues/5567

[tests-only][full-ci]Test for getting group with utf8 characters in name

---

go.mod
go.sum

Bump libre-graph-api-go to get the additional userType flags.

Bump libre-graph-api-go to latest main

---

tests/TestHelpers/OcisHelper.php
tests/acceptance/features/bootstrap/FeatureContext.php

This PR removes the method `isTestingOnOc10` and refactors the code where it is used.
- :robot:

[full-ci] [tests-only] Remove `isTestingOnOc10` method

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/apiSpaces/deleteSpaces.feature
tests/acceptance/features/apiSpaces/listSpaces.feature
tests/acceptance/features/apiSpaces/quota.feature
tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
tests/acceptance/features/apiSpaces/spaceManagement.feature
tests/acceptance/features/apiSpaces/uploadSpaces.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

This PR refactors the json schema drill down for api suite `apiSpaces`.
The old code is not cleaned up for now since it might be used be other api suite. so that can be cleaned later. 
TODO: covers features:
https://github.com/owncloud/ocis/issues/3179

[tests-only][full-ci]Json drill suite `apiSpaces`

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiGraph/getUser.feature
tests/acceptance/features/bootstrap/GraphContext.php

I added test for filter `or` https://github.com/owncloud/ocis/pull/5694

[test-only] add test to filter or

---

tests/acceptance/features/apiGraph/getGroup.feature

This PR adds test for getting details of non-existing gruop.
Related to issue: https://github.com/owncloud/ocis/issues/5567

[tests-only][full-ci]Test for getting non existing group

---

tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/SpacesContext.php

Forward port: https://github.com/owncloud/ocis/pull/5775

[full-ci][tests-only]Refactor test for updating the share

---

tests/TestHelpers/OcisHelper.php
tests/acceptance/features/bootstrap/FeatureContext.php

Forward port of PR https://github.com/owncloud/ocis/pull/5722
Part of https://github.com/owncloud/ocis/issues/5337

[full-ci] [tests-only] Removed method isTestingOnOc10, and refactored code

---

tests/TestHelpers/OcisHelper.php
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/Provisioning.php
tests/acceptance/features/bootstrap/SearchContext.php
tests/acceptance/features/bootstrap/WebDav.php

This PR removes the method isTestingOnOcis and refactors the code where it is used.
- :robot:

[full-ci] [tests-only] Remove `isTestingOnOcis` method

---

tests/TestHelpers/OcisHelper.php
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/Provisioning.php
tests/acceptance/features/bootstrap/SearchContext.php
tests/acceptance/features/bootstrap/WebDav.php

Forward port of PR https://github.com/owncloud/ocis/pull/5780
Part of https://github.com/owncloud/ocis/issues/5337

[full-ci] [tests-only] Removed method `isTestingOnOcis`, and refactored code

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/editUser.feature
tests/acceptance/features/bootstrap/GraphContext.php

[test-only] Port tests from #5769

---

tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
tests/acceptance/features/bootstrap/SpacesContext.php

This PR adds tests for checking the end of the expiration date, to see if the share has been removed or not.
-  check the end of expiration of a space in user share
-  check the end of expiration of a space in group share
- check the end of expiration date in user share [sub-item of the space]
- check the end of expiration date in group share [sub-item of the space] -> which is currently skipped because of https://github.com/owncloud/ocis/issues/5823
- Part of: https://github.com/owncloud/ocis/issues/5413
In this PR we check the end of the expiration of the share meaning check if it's removed after it reaches the end date. In order to test that at first we share a resource with certain expiration date of future and after that the user who shared the resource will …

[tests-only][full-ci] Add tests for checking the end of expiration date

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/apiSpaces/deleteSpaces.feature
tests/acceptance/features/apiSpaces/listSpaces.feature
tests/acceptance/features/apiSpaces/quota.feature
tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
tests/acceptance/features/apiSpaces/spaceManagement.feature
tests/acceptance/features/apiSpaces/uploadSpaces.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/coreApiCapabilities/capabilities.feature
tests/acceptance/features/coreApiCapabilities/capabilitiesWithNormalUser.feature

Forward port of this PR https://github.com/owncloud/ocis/pull/5651.
Also made some changes since in master some key value pairs we additional to that of `stable-2.0`

Forward port json drill `apispaces`

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiGraph/getGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/coreApiCapabilities/capabilities.feature

This PR forward port PR https://github.com/owncloud/ocis/pull/5641

[tests-only][full-ci]forward-port added test for getting details of a single group

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR forward port https://github.com/owncloud/ocis/pull/5693
- https://github.com/owncloud/ocis/pull/5693
- Locally

[tests-only][full-ci]Forward-port extend tests scenario to add users to a group at once 

---

tests/acceptance/features/apiGraph/getGroup.feature

This PR forward-port PR https://github.com/owncloud/ocis/pull/5748

[tests-only][full-ci] Forward-port added test for getting group with UTF-8 characters in name

---

tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
tests/acceptance/features/bootstrap/SpacesContext.php

backport https://github.com/owncloud/ocis/pull/5819
part of: https://github.com/owncloud/ocis/issues/5413

[full-ci][tests-only][backport]Add tests to check the end of an expiration date

---

.drone.star
changelog/unreleased/set-project-space-quota-permission.md
go.mod
go.sum
services/graph/pkg/service/v0/drives.go
services/graph/pkg/service/v0/graph_test.go
services/settings/pkg/store/defaults/defaults.go
sonar-project.properties
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md

Replaces https://github.com/owncloud/ocis/pull/5662

Change Project Space Quota Permission

---

changelog/unreleased/use-gotext-master.md
go.mod
go.sum
services/userlog/pkg/service/conversion.go

Use master version of gotext package

Use `gotext` master

---

.drone.env
.drone.star
services/web/Makefile

[full-ci] Bump web to v7.0.0-rc.22

---

services/proxy/README.md

The Readme update promised with: #5784

[docs-only] proxy: update README with notes about role assignment

---

docs/helpers/README.md

Clarify and improve the extended envvar process.

[docs-only] Update docs/helpers/README.md

---

tests/TestHelpers/SetupHelper.php
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/bootstrap/AuthContext.php
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/Provisioning.php
tests/acceptance/features/bootstrap/WebDav.php
tests/acceptance/features/coreApiAuthWebDav/webDavDELETEAuth.feature

This PR removes `occ` related remaining codes after cleanup of `runOcc` and `occ` related methods.
- :robot:

[full-ci] [tests-only] Remove occ related leftovers

---

tests/TestHelpers/SetupHelper.php
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/bootstrap/AuthContext.php
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/Provisioning.php
tests/acceptance/features/bootstrap/WebDav.php
tests/acceptance/features/coreApiAuthWebDav/webDavDELETEAuth.feature

This PR is forward port of PR https://github.com/owncloud/ocis/pull/5856
Part of https://github.com/owncloud/ocis/issues/5337

[full-ci] [tests-only] Remove occ related leftovers `master`

---

docs/services/proxy/_index.md

This PR updates the `_index.md` file of the proxy service so it will be visible in owncloud.dev.

[docs-only] Update proxy _index.md for owncloud.dev

---

tests/acceptance/features/bootstrap/Provisioning.php

This PR reverts the code related to ldap, which was removed when cleaning `isTestingOnOcisOrReva` and `isTestingOnOcis` methods. Needed for `reva`

[full-ci] [tests-only] Revert ldap related code removed

---

.drone.env
changelog/unreleased/no-notification-own-action.md
services/userlog/pkg/service/service.go
services/userlog/pkg/service/service_test.go

Do not send notifications on `SpaceDeleted` and `SpaceDisabled` when user executed the actions herself.

No Notifications for own actions

---

services/graph/pkg/identity/ldap_group.go

When trying to PATCH group with members, return another error string than the unfiltered ldap error.
- Partially fixes #5855 
Tested only with curl.

graph: Hide ldap error on group membership patch.

---

docs/_index.md

To give readers a prominent located info what they will find here (dev-docs) and where to go if they are looking for admin docs.

[docs-only] Update the ownCloud.dev main page

---

services/idp/pkg/config/http.go

Post a discussion with @rhafer, the description needs an update to be clear what it is about.
Note the default (false) == disable, therefore the sort order is changed.

[docs-only] Clarify the description of the IDP_TLS envvar

---

docs/ocis/development/deprecating-variables.md

[docs-only] depreaction -> deprecation

---

.drone.env
services/web/Makefile

PR: https://github.com/owncloud/ocis/pull/5873 change the branch of the web which branch got deleted after the merge of this PR https://github.com/owncloud/web/pull/8658
So this PR changes the branch to master.
changing the commit id to the test fix https://github.com/owncloud/web/commit/ed2c175142de407463ff2664c76ba52e31b4ecae

[full-ci][tests-only]Change web branch to master

---

tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR adds the tests for adding members in a group using invalid JSON.
Related to issue: https://github.com/owncloud/ocis/issues/5569

[tests-only][full-ci] Test for adding users to a group using invalid JSON

---

changelog/unreleased/notify-about-policies.md
services/userlog/pkg/service/conversion.go
services/userlog/pkg/service/service.go
services/userlog/pkg/service/templates.go

Inform the user when a file was deleted because the `policies` service said so

Inform about Policies-Outcome

---

docs/services/new-service-checklist.md

Improve the handling of additional ressources used by README.md

[docs-only] Update new-service-checklist.md

---

go.mod
go.sum

Bump reva to to add user type property.

Bump reva to to add user type property.

---

.drone.env
services/web/Makefile

[full-ci] chore: bump web to v7.0.0-rc.24

---

tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR forward ports PR https://github.com/owncloud/ocis/pull/5898

[tests-only][full-ci] Fordward-port test for adding users to a group using invalid JSON

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR forward ports PR https://github.com/owncloud/ocis/pull/5875

[tests-only][full-ci] Forwardport test for send wrong host for adding user in group

---

tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/apiGraph/createUser.feature
tests/acceptance/features/apiGraph/deleteUser.feature
tests/acceptance/features/apiGraph/removeUserFromGroup.feature

This PR unskips some of the tests that pass in stable branch

[tests-only]Unskip passing tests from CI

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

Json schema assertion for suite `apiShareSpaces`. for remaining `match key and value pairs` steps.
https://github.com/owncloud/ocis/issues/3179

[tests-only][full-ci] Added schema for key and value pair assertion

---

services/invitations/md-sources/example-realm.json

Remove not necessary source code ticks from json file (have been added accidentially)
Refs: #5956, forgotten to fix it there

[docs-only] Update example-realm.json

---

.drone.env
services/web/Makefile

chore: update web to v7.0.0-rc.25

[full-ci] chore: update web to v7.0.0-rc.25

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

This PR forward port PR https://github.com/owncloud/ocis/pull/5861

[tests-only][full-ci]Forwardport json drill apispacesshares

---

changelog/unreleased/bump-reva.md
changelog/unreleased/personal-data-export-capability.md
services/frontend/pkg/revaconfig/config.go

Capability for the personal data export endpoint (GDPR)

Add capability for personal data export

---

changelog/unreleased/fix-oidc-auth-cache.md
services/proxy/pkg/middleware/oidc_auth.go

This PR fixes the OIDC auth cache which was rendered useless with a previous PR.

Fix OIDC cache

---

services/idp/pkg/config/config.go

Add new new name for environment variable and a deprecation warning.
Fixes #5907

idp: Change name of environment variable to be more consistent.

---

changelog/unreleased/av-more-logging.md
services/antivirus/pkg/service/service.go

Enhancement: Add more logging to av service
We need more debug logging sometimes to understand the state of a virus scan.

add more logging to antivirus

---

services/antivirus/pkg/config/config.go
services/audit/pkg/config/config.go
services/eventhistory/pkg/config/config.go
services/graph/pkg/config/config.go
services/notifications/pkg/config/config.go
services/policies/pkg/config/config.go
services/postprocessing/pkg/config/config.go
services/search/pkg/config/search.go
services/sharing/pkg/config/config.go
services/storage-users/pkg/config/config.go
services/userlog/pkg/config/config.go

Introduced the global variables OCIS_EVENTS_ENDPOINT and OCIS_EVENTS_CLUSTER for the antivirus, audit, eventhistory, graph, notifications, policies, postprocessing, search, sharing, storage-users and userlog services
- Fixes [<https://github.com/owncloud/ocis/issues/5901>](https://github.com/owncloud/ocis/issues/5901)

Introduced global OCIS_EVENTS_ENDPOINT and OCIS_EVENTS_CLUSTER #5901

---

changelog/unreleased/configure-grpc-in-ocs.md
services/ocs/pkg/command/server.go
services/ocs/pkg/config/config.go
services/ocs/pkg/config/defaults/defaultconfig.go

Fixes panic when ocs is not running in single binary
Fixes https://github.com/owncloud/ocis/issues/5985

Fix Panic in OCS service

---

.drone.env

- change web commit and web branch to master after merging https://github.com/owncloud/web/pull/8779

change web branch and commit

---

docs/helpers/adoc-generator.go.tmpl
docs/templates/ADOC.tmpl

Fixes https://github.com/owncloud/ocis/issues/6006

[docs-only] Add Timestamp to Deprecation section

---

ocis-pkg/keycloak/client.go
ocis-pkg/keycloak/types.go
services/graph/README.md
services/graph/pkg/config/config.go
services/graph/pkg/server/http/server.go
services/graph/pkg/service/v0/graph.go
services/graph/pkg/service/v0/option.go
services/graph/pkg/service/v0/personaldata.go
services/graph/pkg/service/v0/service.go
services/invitations/pkg/config/config.go
services/invitations/pkg/mocks/client.go

This PR adds the data from keycloak and events into the GDPR export of
the graph service.

Integrate keycloak and events data into graph.

---

.drone.env
services/web/Makefile

[full-ci] chore: bump oC Web to v7.0.0-rc.30

---

.drone.env

fixing flaky e2e test https://github.com/owncloud/web/pull/8835 and bring it to ocis

[test-only] bump web commit. fixing e2e flaky #8833

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

Previously test was a combination of two valid endpoints which was not the right thing to do because it may get into json parsing problem
```
curl --location --request PATCH 'https://localhost:9200/graph/v1.0/groups/167cbee2-0518-455a-bfb2-031fe0621e5d' \
--header 'Content-Type: application/json' \
--data-raw '{
"@odata.id": "https://localhost:9200/graph/v1.0/groups/cedc21aa-4072-4614-8676-fa9165f598ff"
}'
```
This PR separate tests for endpoint POST and PATCH
```
curl --location --request PATCH 'https://localhost:9200/graph/v1.0/groups/90d2d879-2a1b-4f6b-a8fb-0ebb2904a317/' \
--header 'Content-Type: application/json' \
--data-raw '{
"members@odata.bind": [
"https://localhost:9200/graph/v1.0/groups/df0144ec-c1aa-44e5-88ff-29416c2c4ef4"
]
}'
curl --location --request POST …
```

[tests-only] [full-ci] Refactor api endpoint for adding group to group 

---

.drone.star

use proxy for build step

---

docs/services/general-info/_index.md

[docs-only] Fix typo in docs services general info title

---

.drone.env
services/web/Makefile

[full-ci] chore: bump web to v7.0.0-rc.31

---

docs/apis/http/graph/spaces.md
docs/architecture/upload-processing.md
docs/clients/rclone/webdav-sync-oidc.md
docs/helpers/README.md
docs/ocis/adr/0021-service-accounts.md
docs/ocis/guides/ocis-and-containers.md
docs/ocis/guides/ocis-local-docker.md
docs/services/antivirus/_index.md
docs/services/eventhistory/_index.md
docs/services/frontend/_index.md
docs/services/policies/_index.md
docs/services/postprocessing/_index.md
docs/services/proxy/_index.md
docs/services/userlog/_index.md

[docs-only] Various docs edits

---

tests/TestHelpers/HttpRequestHelper.php
tests/TestHelpers/SetupHelper.php
tests/TestHelpers/SharingHelper.php
tests/TestHelpers/UploadHelper.php
tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/apiSpaces/notification.feature
tests/acceptance/features/apiSpaces/resharing.feature
tests/acceptance/features/apiSpacesShares/copySpaces.feature
tests/acceptance/features/apiSpacesShares/etagPropagation.feature
tests/acceptance/features/apiSpacesShares/favorite.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/FilesVersionsContext.php
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/OCSContext.php
tests/acceptance/features/bootstrap/Provisioning.php
tests/acceptance/features/bootstrap/RoleAssignmentContext.php
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/SpacesTUSContext.php
tests/acceptance/features/bootstrap/TUSContext.php
tests/acceptance/features/bootstrap/WebDav.php
tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
tests/acceptance/features/coreApiWebdavOperations/search.feature
tests/acceptance/features/coreApiWebdavProperties1/setFileProperties.feature

Tidy up a few other typos, grammar etc in the acceptance tests.
CI

[tests-only] tidy up acceptance tests

---

services/graph/pkg/service/v0/users.go
tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/getUser.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR adds the api test to get the personal drive information of users by admin or non-admin users using endpoint `/graph/v1.0/users/{userid}/drive`.
Closes https://github.com/owncloud/ocis/issues/6011
Fixes #6017

[tests-only][full-ci] api test to get personal drive information of other users

---

tests/acceptance/features/apiGraph/getApplications.feature
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/PublicWebDavContext.php

1) remove an invalid double-quote from a test step (note: the test step does not seem to be used at the moment)
2) adjust the words of some test steps so that they read more easily
I noticed these when I was reviewing other PRs last week.
CI

[tests-only] Fix invalid acceptance test step

---

changelog/unreleased/fix-userlog-panic.md
services/userlog/pkg/service/service.go

Fixes https://github.com/owncloud/ocis/issues/5823

Fix userlog panic

---

.drone.env
services/web/Makefile

[full-ci] chore: bump web to v7.0.0-rc.32

---

services/eventhistory/README.md
services/frontend/README.md
services/gateway/README.md
services/graph/README.md
services/ocs/README.md
services/proxy/README.md
services/storage-system/README.md
services/storage-users/README.md
services/userlog/README.md

References: #6019 ([full-ci] Refactor stores)
**DO NOT MERGE** before the referenced PR got merged !
Adds/corrects missing info in README.md for services with respect to caching/storing.
@aduffeck @butonic fyi

[docs-only] Add caching/storing info to services where missing

---

docs/helpers/extendedEnv.go

Vendor folder should not be scanned by docs helper

[docs-only] Exclude Vendor Folder from docs

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/coreApiAuth/webDavAuth.feature
tests/acceptance/features/coreApiAuthOcs/ocsDELETEAuth.feature
tests/acceptance/features/coreApiAuthOcs/ocsGETAuth.feature
tests/acceptance/features/coreApiAuthOcs/ocsPOSTAuth.feature
tests/acceptance/features/coreApiAuthOcs/ocsPUTAuth.feature
tests/acceptance/features/coreApiAuthWebDav/webDavCOPYAuth.feature
tests/acceptance/features/coreApiAuthWebDav/webDavDELETEAuth.feature
tests/acceptance/features/coreApiAuthWebDav/webDavLOCKAuth.feature
tests/acceptance/features/coreApiAuthWebDav/webDavMKCOLAuth.feature
tests/acceptance/features/coreApiAuthWebDav/webDavMOVEAuth.feature
tests/acceptance/features/coreApiAuthWebDav/webDavPOSTAuth.feature
tests/acceptance/features/coreApiAuthWebDav/webDavPROPFINDAuth.feature
tests/acceptance/features/coreApiAuthWebDav/webDavPROPPATCHAuth.feature
tests/acceptance/features/coreApiAuthWebDav/webDavPUTAuth.feature
tests/acceptance/features/coreApiAuthWebDav/webDavSpecialURLs.feature

This PR
- adds the description about the feature file
- updates the line changes in expected to fail file
- Part of: https://github.com/owncloud/QA/issues/804
This is because we want to have a well defined structure of feature file
- CI

[tests-only][full-ci]Refactor feature files to add proper description

---

changelog/unreleased/add-debug-to-idm.md
services/idm/pkg/command/server.go
services/idm/pkg/config/defaults/defaultconfig.go

This PR adds a debug server to idm
refs #5003 
refs #5712

add debug server to idm

---

changelog/unreleased/add-notifications-debug-server.md
services/notifications/pkg/command/server.go
services/notifications/pkg/config/config.go
services/notifications/pkg/config/defaults/defaultconfig.go

This PR adds a debug server to the notifications service
refs #5002 
refs #5712

add debug server to notifications

---

deployments/examples/ocis_ldap/config/ldap/ldif/20_users.ldif
deployments/examples/ocis_ldap/config/ldap/schemas/10_owncloud_schema.ldif

Update LDAP schema with latest changes (ownCloudUserType was introduced).

Update to latest schema

---

changelog/fix-compile-date.md
ocis-pkg/version/version.go

fix  wrong compile date

---

tests/acceptance/features/apiGraph/userGDPRExport.feature

Added scenario
```feature
generate a GDPR report and check events when user uploads a file
```

[tests-only]Gdpr upload file1

---

services/graph/pkg/service/v0/drives.go

This PR speeds up the `me/drives` by gathering space information in parallel (handling up to 20 spaces in parallel, can be made configurable in the future).

Speed up me/drives by gathering space information in parallel

---

ocis-pkg/markdown/markdown.go
ocis-pkg/markdown/markdown_test.go

Fix newline handling in markdown creation

[docs-only] Fix Markdown Creation

---

tests/acceptance/features/bootstrap/AppConfigurationContext.php
tests/acceptance/features/bootstrap/AuthContext.php
tests/acceptance/features/bootstrap/CapabilitiesContext.php
tests/acceptance/features/bootstrap/ChecksumContext.php
tests/acceptance/features/bootstrap/FavoritesContext.php
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/FilesVersionsContext.php
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/NotificationContext.php
tests/acceptance/features/bootstrap/OCSContext.php
tests/acceptance/features/bootstrap/Provisioning.php
tests/acceptance/features/bootstrap/PublicWebDavContext.php
tests/acceptance/features/bootstrap/RoleAssignmentContext.php
tests/acceptance/features/bootstrap/SearchContext.php
tests/acceptance/features/bootstrap/ShareesContext.php
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/SpacesTUSContext.php
tests/acceptance/features/bootstrap/TUSContext.php
tests/acceptance/features/bootstrap/TagContext.php
tests/acceptance/features/bootstrap/TrashbinContext.php
tests/acceptance/features/bootstrap/WebDav.php
tests/acceptance/features/bootstrap/WebDavLockingContext.php
tests/acceptance/features/bootstrap/WebDavPropertiesContext.php

- Fixup minor typos nd grammar (for example "non-current")
- declare types of private properties,function parameters
- remove parameters from calls where the parameters are already the defaults
- remove unneeded curly brackets from string substitutions
- remove unused variables
- remove all remaining references to GraphContext and Graph API (they were for ocis only)
- refactor some code so that variables are guaranteed to be set
- refactor code to use the `??` operator, as suggested by my IDE
Now the code uses the features of PHP 7.4 as much as reasonable.
This is similar to what was done in core https://github.com/owncloud/core/pull/40754
CI

[tests-only] [full-ci]Cleanup acceptance tests

---

changelog/unreleased/add-debug-to-postprocessing.md
docs/services/general-info/port-ranges.md
services/postprocessing/pkg/command/server.go
services/postprocessing/pkg/config/config.go
services/postprocessing/pkg/config/defaults/defaultconfig.go

This PR adds a debug server to postprocessing
refs #5712 
refs #5002 
refs https://github.com/owncloud/ocis-charts/issues/111

add debug to postprocessing

---

deployments/examples/ocis_ldap/docker-compose.yml

The idm run excluded for the ocis ldap docker-compose
- Fixes https://github.com/owncloud/ocis/issues/6184
- test environment: local docker-compose with the ocsi image owncloud/ocis:3.0.0-rc.1
- test case 1:  tested manualy

the idm run excluded for the ocis ldap stack #6184

---

services/web/README.md

[docs-only] Typo fix in web service README.md

---

.drone.env

Bring test codes from https://github.com/owncloud/web/pull/8971
Fixes https://github.com/owncloud/ocis/issues/6206

[tests-only][full-ci]Bump web commit for the tests

---

go.mod
go.sum
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
vendor/github.com/cs3org/reva/v2/internal/grpc/interceptors/auth/scope.go
vendor/github.com/cs3org/reva/v2/internal/grpc/services/storageprovider/storageprovider.go
vendor/github.com/cs3org/reva/v2/pkg/publicshare/manager/json/json.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/decomposedfs.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/node/permissions.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/spaces.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/upload.go
vendor/modules.txt

testing https://github.com/cs3org/reva/pull/3843 in ocis
fixes https://github.com/owncloud/ocis/issues/5229

[full-ci] bump reva to 2118139f5420

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
tests/acceptance/features/coreApiShareManagementToShares/acceptSharesToSharesFolder.feature
tests/acceptance/features/coreApiShareManagementToShares/mergeShare.feature
tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
tests/acceptance/features/coreApiShareManagementToShares/moveShareInsideAnotherShare.feature
tests/acceptance/features/coreApiShareOperationsToShares1/accessToShare.feature

- adds the description of the feature file
- updates the line changes in expected to fail file
- start the scenario title with a small letter and without the article
- remove the duplication of scenario title within a feature file
- Part of: https://github.com/owncloud/QA/issues/804
- CI

[tests-only][full-ci]Refactor feature files to add correct description

---

changelog/unreleased/bump-reva.md
go.mod
go.sum
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/tree/tree.go
vendor/modules.txt

to pull in https://github.com/cs3org/reva/pull/3845

bump reva to 756a84314af0

---

tests/acceptance/features/coreApiWebdavProperties2/getFileProperties.feature

This PR adds the tests to `PROPFIND` a folder with files in then and checks the size of the folder.
- Test for: https://github.com/owncloud/ocis/issues/6215
The bug https://github.com/owncloud/ocis/issues/6215 wasn't covered by the test yet, so this PR adds the test case .
- locally
- CI

[tests-only][full-ci]Add test to propfind the size of a folder

---

tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature

The following scenario `check the end of expiration date in group share` was skipped by https://github.com/owncloud/ocis/pull/5819/files because of this issue https://github.com/owncloud/ocis/issues/5823. The issue has been closed and the test behaves as expected now so we can unskip the test so that it can run in the CI
- Part of: https://github.com/owncloud/ocis/issues/5823
- locally
- CI

[tests-only]Unskip the test related to expiration date

---

tests/acceptance/features/apiGraph/userGDPRExport.feature

This PR adds scenario for GDPR export: 
```feature
Scenario: generate a GDPR report and check events when a user is added to a group
```

[tests-only][full-ci]Added GDPR export when user is added to a group

---

services/frontend/pkg/config/config.go
services/frontend/pkg/config/defaults/defaultconfig.go
services/frontend/pkg/revaconfig/config.go
services/ocdav/pkg/config/config.go

- test case 1:
- test case 2:
- ...

make edition configurable

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/apiGraph/deleteGroup.feature
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
tests/acceptance/features/coreApiShareOperationsToShares1/accessToShare.feature
tests/acceptance/features/coreApiShareOperationsToShares1/changingFilesShare.feature
tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesPendingFiltered.feature
tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFiltered.feature
tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFilteredEmpty.feature
tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFiltered.feature
tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFilteredEmpty.feature
tests/acceptance/features/coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature
tests/acceptance/features/coreApiShareOperationsToShares2/shareAccessByID.feature
tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature
tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShareToShares.feature
tests/acceptance/features/coreApiSharePublicLink1/deletePublicLinkShare.feature

This PR
- adds the description about the feature file
- updates the line changes in expected to fail file
- Part of: https://github.com/owncloud/QA/issues/804
This is because we want to have a well-defined structure of the feature file
- CI

[tests-only][full-ci]Add proper description to a feature file

---

tests/TestHelpers/Asserts/WebDav.php
tests/TestHelpers/GraphHelper.php
tests/TestHelpers/HttpRequestHelper.php
tests/TestHelpers/OcisHelper.php
tests/TestHelpers/OcsApiHelper.php
tests/TestHelpers/SetupHelper.php
tests/TestHelpers/SharingHelper.php
tests/TestHelpers/TranslationHelper.php
tests/TestHelpers/UploadHelper.php
tests/TestHelpers/UserHelper.php
tests/TestHelpers/WebDavHelper.php
tests/acceptance/features/bootstrap/PublicWebDavContext.php
tests/acceptance/features/bootstrap/Sharing.php

Similar to core PR https://github.com/owncloud/core/pull/40775
Cleanup acceptance test helpers code.
CI

[tests-only] [full-ci] Cleanup code in TestHelpers

---

.drone.star
docs/ocis/development/testing.md
tests/TestHelpers/EmailHelper.php
tests/acceptance/config/behat.yml
tests/acceptance/features/apiEmailNotification/emailNotification.feature
tests/acceptance/features/bootstrap/NotificationContext.php

This PR adds the API test for email notification for shares.
Related to issue: https://github.com/owncloud/ocis/issues/6061

[tests-only] [full-ci] api test for email notification

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
tests/acceptance/features/coreApiSharePublicLink3/uploadToPublicLinkShare.feature

related #6238 
https://github.com/owncloud/ocis/pull/6271 
added new test:
- User cannot create share for personal space to user/group
- User cannot create public link for personal space
deleted issue tags

[test-only] Api-test for sharing personal space

---

services/search/README.md

Feedback and request from dev:
For dev purposes, it would be good to know that there is a tika container available ready to use - added to dev docs.

[docs-only] Add Tika container link to search for dev purposes

---

changelog/unreleased/postprocessing-store.md
services/postprocessing/README.md
services/postprocessing/pkg/command/server.go
services/postprocessing/pkg/config/config.go
services/postprocessing/pkg/postprocessing/postprocessing.go
services/postprocessing/pkg/service/service.go
tests/acceptance/features/apiGraph/userGDPRExport.feature

Add store functionality to postprocessing service

Postprocessing Store

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/unassignRole.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR adds the scenarios for unassigning the role of users,
- `Scenario Outline: admin user unassigns the role of a user with different role using graph API`
- `Scenario: admin user tries to unassign his/her own role using graph API`
- Part of https://github.com/owncloud/ocis/issues/6012
- Locally
- :robot:

[full-ci] [tests-only] unassign app role assignment of user

---

services/search/README.md

* Add a note that tika containers are only available for the amd64 platform.
* Restructure container usage hint.

[docs-only ]Update search README.md

---

.drone.env
.drone.star
services/web/Makefile

enable e2e test again
bump web commit ID

[test-only] [full-ci] enable e2e tests. bump web to v7.0.0-rc.37

---

services/settings/pkg/store/defaults/defaults.go

[docs-only] Fix settings typos

---

changelog/unreleased/id-cache.md
go.mod
go.sum
services/storage-users/pkg/config/config.go
services/storage-users/pkg/revaconfig/drivers.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/decomposedfs.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/node/xattrs.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/options/options.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/tree/tree.go
vendor/modules.txt

Makes id cache configurable
Needs its reva cousin to work: https://github.com/cs3org/reva/pull/3903

Configurable IDCache

---

tests/acceptance/features/apiGraph/changeRole.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR adds the scenarios for changing the role of users,
- `Scenario Outline: admin user changes the role of another user with different roles`
- `Scenario Outline: admin user tries to change his/her own role`
- Part of https://github.com/owncloud/ocis/issues/6012
- Locally
- :robot:

[full-ci] [tests-only] Change user role

---

.drone.env
changelog/unreleased/update-web-7.0.0-rc.38.md
services/web/Makefile

[full-ci] chore: bump web to v7.0.0-rc.38

---

services/graph/pkg/config/config.go
services/graph/pkg/service/v0/users.go
services/proxy/pkg/middleware/account_resolver.go
services/proxy/pkg/user/backend/cs3.go

proxy: Return an error when autoprovision a user fails

---

tests/acceptance/features/apiSpaces/tusUpload.feature
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/SpacesTUSContext.php

I added test for https://github.com/owncloud/ocis/issues/6335

[test-only] ApiTest. Upload file after renaming first

---

tests/acceptance/features/apiSpaces/uploadSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

test for https://github.com/cs3org/reva/pull/3834 and closed bug https://github.com/owncloud/ocis/issues/6136

[tests-only] Api tests for checking conflict status code while creating folder

---

changelog/unreleased/fulltextsearch-capability.md
go.mod
go.sum
services/frontend/pkg/config/config.go
services/frontend/pkg/revaconfig/config.go
services/search/README.md
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocdav/copy.go
vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/data/capabilities.go
vendor/modules.txt

Adds capability for fulltextsearch
fixes https://github.com/owncloud/ocis/issues/6367

Add Fulltextsearch Capability

---

tests/acceptance/features/apiGraph/userGDPRExport.feature

This PR adds the GDPR report test for the events.SpaceShared.
`Scenario: generate a GDPR report and check events when a space is shared`
- Part of https://github.com/owncloud/ocis/issues/6059
- Locally
- :robot:

[full-ci] [tests-only] Added GDPR report test for events.SpaceShared

---

services/search/README.md
services/search/pkg/config/config.go
services/search/pkg/config/defaults/defaultconfig.go
services/search/pkg/content/tika.go

Both tika and ocis do not handle large files/archives very well.

Do not try to fulltext-index large files.

---

tests/acceptance/features/apiGraph/userGDPRExport.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR adds the GDPR report test for the events.SpaceShared.
`Scenario: generate a GDPR report and check events when a space is created`
Closes https://github.com/owncloud/ocis/issues/6059
- Locally
- :robot:

[full-ci] [tests-only] Added GDPR report test for events.SpaceCreated

---

.drone.star
changelog/unreleased/rename-permissions.md
go.mod
go.sum
services/settings/pkg/store/defaults/defaults.go
vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/spaces.go
vendor/github.com/cs3org/reva/v2/pkg/permission/permission.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/spacepermissions.go
vendor/modules.txt

Renames permissions
ATTENTION: DISABLES E2E TESTS

[full-ci] Rename Permissions

---

changelog/unreleased/rename-permissions.md
services/web/pkg/service/v0/branding.go

Forgotten permission with old name

Use correct Logo Permission

---

tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/NotificationContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

This PR refactors the use of `JsonAssertion traits` in correct way for the tests.
Fixes https://github.com/owncloud/ocis/issues/6404

[tests-only][full-ci]Use `traits` in correct way for `JsonAssertion`

---

changelog/unreleased/fix-disable-user.md
services/graph/pkg/identity/ldap.go

Bugfix: Fix error message when disabling users
When we disable users by adding them to a group we do not need to update the user entry.
```sh
curl 'https://###.owncloud.works/graph/v1.0/users/9327e0c1-6dc7-4edd-a0a3-03d47c3ade70' \
-X 'PATCH' \
--data-raw '{"accountEnabled":false}' \
--compressed
```
```json
{
"error": {
"code": "notAllowed",
"innererror": {
"date": "2023-06-02T16:01:34Z",
"request-id": "b1e1cf5c-f658-4aa0-9196-b163bec831ae"
},
"message": "error updating user"
}
}
```
- test case 1:
- test case 2:
- ...

fix disable users by group

---

.drone.env
changelog/unreleased/update-web-7.0.0.md
services/web/Makefile

update to to `v7.0.0` final for the upcoming ocis `v3.0.0` release.

[full-ci] chore: Update web to v7.0.0 final

---

changelog/unreleased/bump-reva.md
go.mod
go.sum
vendor/modules.txt

- test case 1:
- test case 2:
- ...

[full-ci] update reva to v2.14.0

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiCors/cors.feature
tests/acceptance/features/apiSpaces/quota.feature
tests/acceptance/features/bootstrap/OcisConfigContext.php

This PR adds test to set and test the quota feature for `oCIS` when quota is set with env `OCIS_SPACES_MAX_QUOTA`
https://github.com/owncloud/ocis/issues/6231

[tests-only][full-ci]Add step to set quota with env `OCIS_SPACES_MAX_QUOTA`

---

ocis/pkg/command/services.go

Fixes ocis standalone services

[tests-only] Fix ocis

---

tests/acceptance/features/apiAntivirus/antivirus.feature

Antivirus service is not available in Reva so skip the tests related to antivirus in reva.

[tests-only] Skip antivirus related tests in reva

---

CHANGELOG.md
changelog/3.0.0_2023-06-06/fix-share-locked-file.md

list of changes was typo. Fixed it

Changed issue number in changelog

---

go.mod
go.sum
vendor/github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/jsoncs3.go
vendor/github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/providercache/providercache.go
vendor/github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/receivedsharecache/receivedsharecache.go
vendor/github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/sharecache/sharecache.go
vendor/github.com/cs3org/reva/v2/pkg/share/share.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/metadata/cs3.go
vendor/modules.txt

https://github.com/cs3org/reva/pull/3960
https://github.com/cs3org/reva/pull/3959
https://github.com/cs3org/reva/pull/3955

[full-ci] Bump reva to latest edge

---

changelog/unreleased/app-provider-service-name.md
services/app-provider/pkg/config/config.go

We needed to make the service name of the app provider configurable. This needs to be changed when using more than one app provider. Each of them needs be afound by a unique service name. Possible examples are: `app-provider-collabora`, `app-provider-onlyoffice`, `app-provider-office365`.
- test case 1:
- test case 2:
- ...

make the app provider service name configurable

---

.drone.env

bumping web commit id to bring in the adjusted tests, fixing https://github.com/owncloud/ocis/issues/6431

[full-ci] ci: bump web commit id for updated tests (to master)

---

changelog/unreleased/fix-groupname-validation.md
services/graph/pkg/identity/ldap_group.go
services/graph/pkg/service/v0/educationclasses.go
services/graph/pkg/service/v0/educationschools.go
services/graph/pkg/service/v0/educationuser.go
services/graph/pkg/service/v0/errorcode/errorcode.go
services/graph/pkg/service/v0/groups.go
services/graph/pkg/service/v0/users.go
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md

- Fixes [https://github.com/owncloud/ocis/issues/5050](https://github.com/owncloud/ocis/issues/5050)
- test case 1:
```text
curl -XPOST  "https://localhost:9200/graph/v1.0/groups" -d '{"displayName":""}' -uadmin:admin -ik 
HTTP/1.1 400 Bad Request
Content-Length: 167
Content-Security-Policy: frame-ancestors 'none'
Content-Type: application/json; charset=utf-8
Date: Fri, 09 Jun 2023 16:05:33 GMT
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Graph-Version: 3.1.0-next.1+dev
{"error":{"code":"invalidRequest","innererror":{"date":"2023-06-09T16:05:33Z","message":"Invalid displayName"}}
```

fixed the ability to create a group with an empty name #5050
