owncloud/ocis

changelog/unreleased/dont-reindex-twice.md
services/search/pkg/search/provider/events.go
services/search/pkg/search/provider/events_test.go

This PR changes the search service so that it doesn't reindex a space while another reindex process is still in progress.

Dont reindex twice

---

changelog/unreleased/fix-notifications-web-ui-url.md
services/notifications/pkg/command/server.go
services/notifications/pkg/config/config.go
services/notifications/pkg/config/defaults/defaultconfig.go

We've fixed the configuration of the notification service's Web UI url that appears in emails.
Previously it was only configurable via the global "OCIS_URL" and is now also configurable via "NOTIFICATIONS_WEB_UI_URL".
- found in https://github.com/owncloud/ocis-charts/pull/105
- -

add NOTIFICATIONS_WEB_UI_URL

---

changelog/unreleased/filter-hidden-files.md
services/search/pkg/search/index/index.go
services/search/pkg/search/index/index_test.go

With this PR hidden files (dotfiles) will no longer be part of the search results.

Filter hidden files

---

.drone.env
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/createGroup.feature
tests/acceptance/features/apiGraph/createUser.feature
tests/acceptance/features/bootstrap/GraphContext.php

Added API tests for group creation
1. `Scenario Outline: admin user creates a group`
```feature
| simplegroup     |
| España§àôœ€     |
| नेपाली            |
| $x<=>[y*z^2+1]! |
| 😅 😆           |
| comma,grp1      |
| Finance (NP)    |
| slash\Middle    |
```
2. `Scenario: admin user tries to create a group that already exists`
3. `Scenario: normal user tries to create a group`

[tests-only][full-ci] Add API tests for creating groups (graph API)

---

.drone.env

Updated the oC/core commit iD for the tests to the latest upto november 14, 2022
https://github.com/owncloud/QA/issues/772

[tests-only][full-ci]Bump core commit 2022-11-14

---

tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature

Added API tests for sharing disabled space to another user and via public link.
1. `Scenario Outline: A user cannot share a disabled space to another user`
2. `Scenario: A user cannot share a disabled space to public via link`
- Part of https://github.com/owncloud/ocis/issues/4937 (share disabled space is not possible (ink public link))
- Locally
- CI

[full-ci] [tests-only] Added api test for sharing disabled space

---

.drone.env
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/createGroup.feature
tests/acceptance/features/apiGraph/getGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

Added API tests for listing groups and group members
1. `Scenario: admin user lists all the groups`
2. `Scenario: normal user cannot get the groups list`
3. `Scenario: admin user gets users of a group`
4. `Scenario: normal user tries to get users of a group`

[tests-only][full-ci] Add API tests for getting groups and group members (graph API)

---

services/settings/pkg/store/metadata/bundles.go

This we moved the settings service to the metadata storage with its own gateway and permissions service, we no longer need the hardcoded initial replies in order to bootstrap the role assignments.
This fixes a panic in the settings service when the first request to the service is a read request on anything else but an existing role or assignment.
This should fix: https://github.com/owncloud/ocis/issues/5033#issuecomment-1313446295

Remove no longer needed bootstrap code

---

services/settings/pkg/service/v0/service.go
services/settings/pkg/service/v0/settings.go
services/settings/pkg/store/defaults/defaults.go

We've fixed the duplicate assignment of `79e13b30-3e22-11eb-bc51-0b9f0bad9a58` for both: `create-space` and `settings-management` permissions. We also deduplicate role ids after listing them internally to make permission retrieval more efficient.
fixes https://github.com/owncloud/ocis/issues/5033

Make permission and role ids unique

---

changelog/unreleased/find-spaces.md
services/search/pkg/search/index/index.go
services/search/pkg/search/index/index_test.go
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md

This PR fixes finding spaces by their name in the search service.
Fixes https://github.com/owncloud/ocis/issues/4506

Find spaces

---

.drone.env

Bump latest core commit id on `oCis`
https://github.com/owncloud/QA/issues/772

[tests-only][full-ci]Bump core latest commit-id

---

changelog/unreleased/fix-cache-store-env.md
services/gateway/pkg/config/config.go
services/storage-users/pkg/config/config.go

We've adjusted cache related configuration options of the
gateway and storage-users service to the other services.
- -
-
- -

adjust cache related configuration options

---

changelog/unreleased/initial-role-assignment.md
services/proxy/pkg/user/backend/cs3.go
services/settings/pkg/service/v0/service.go
services/settings/pkg/service/v0/service_test.go

When using an external user management we need to allow users to self-assign the default role. This adds an explicit check for that to the settings service. This also means we no longer need to fiddle with the account id in the proxy upon first login.
Fixes: #5045

Allow initial self-assignemnt of UserRole

---

changelog/unreleased/change-lower-idp-token-lifespans.md
services/idp/pkg/config/config.go
services/idp/pkg/config/defaults/defaultconfig.go

We've lowered the IDP token lifespans to more reasonable durations.
- -
-
- -

lower default access / id / refresh token lifespans

---

tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

Added API tests for adding user to groups
1. `Scenario: adding a user to a group`
2. `Scenario: adding a user to a group with special character in its name`
3. `Scenario: adding a user to a group with % and # in its name`
4. `Scenario: adding a user to a group that has a forward-slash in the group name`
5. `Scenario: normal user tries to add himself to a group`
6. `Scenario: normal user tries to other user to a group`
7. `Scenario: admin tries to add user to a non-existing group`
8. `Scenario: admin tries to add a non-existing user to a group`
9. `Scenario: admin tries to add user to a group without sending the group`

[tests-only][full-ci] Add API tests for adding user to group (graph API)

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/editGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

Added API tests for editing group display name
1. `Scenario Outline: admin user renames a group`
```feature
| grp1      | grp101        |
| grp1      | España§àôœ€   |
| grp1      | नेपाली          |
| grp1      | $x<=>[y*z^2]! |
| grp1      | staff?group   |
| grp1      | 50%pass       |
```

[tests-only][full-ci] Add API tests for editing group displayName (graph API)

---

changelog/unreleased/add-tracing-to-serach.md
services/search/pkg/search/index/index.go
services/search/pkg/search/index/index_test.go
services/search/pkg/search/provider/searchprovider.go

We added tracing to search and its indexer
refs #5063

Add tracing to search + indexer

---

deployments/examples/ocis_wopi/docker-compose.yml

Just adding a blank line between the last entry of the `ocis-appdriver-onlyoffice` block and the start of `wopiserver` for ease of readability.

Update the docker-compose example for wopi

---

Dockerfile
ocis/docker/Dockerfile.linux.amd64
ocis/docker/Dockerfile.linux.arm
ocis/docker/Dockerfile.linux.arm64

switches the base image for image builds to a more recent version of alpine
keep things up to date
- using dev image with the ocis-traefik deployment example

switch to a more recent alpine image for image builds

---

.vscode/launch.json
changelog/unreleased/mount-ids.md
ocis/pkg/init/init.go
services/gateway/pkg/config/config.go
services/gateway/pkg/config/parser/parse.go
services/gateway/pkg/revaconfig/config.go
services/storage-users/pkg/config/defaults/defaultconfig.go
services/storage-users/pkg/config/parser/parse.go

The mount ID of the storage users provider needs to be unique by default. We made this value configurable and added it to ocis init to be sure that we have a random uuid v4. This is important for federated instances.
- Fixes #5064 
- test case 1:
- test case 2:
- ...

Bugfix: Make storage users mount ids unique by default

---

changelog/unreleased/filelock-duration-factor-config.md
services/storage-system/pkg/config/config.go
services/storage-system/pkg/config/defaults/defaultconfig.go
services/storage-system/pkg/revaconfig/config.go
services/storage-users/pkg/config/config.go
services/storage-users/pkg/config/defaults/defaultconfig.go
services/storage-users/pkg/revaconfig/user.go

We made the file lock duration per lock cycle for decomposedfs configurable and increased it to make locks work on top of NFS.
see https://github.com/owncloud/ocis/issues/5024
This PR does not bump reva, but it will add the necessary config which will be picked up when bumping it as soon as https://github.com/cs3org/reva/pull/3493 is merged

decomposedfs increase filelock duration factor

---

tests/acceptance/features/apiGraph/removeUserFromGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

Added API tests for removing user from groups
1. `Scenario: admin removes a user from a group`
2. `Scenario: admin removes a user from a group with special characters`
3. `Scenario: admin removes a user from a group having % and # in their names`
4. `Scenario: admin removes a user from a group that has a forward-slash in the group name`
5. `Scenario: admin tries to remove a user from a non-existing group`
6. `Scenario: normal user tries to remove a user in their group`
- Part of https://github.com/owncloud/ocis/issues/4937 

[tests-only][full-ci] Add API tests for removing user from groups (graph API)

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiGraph/getUser.feature
tests/acceptance/features/apiGraph/getUserOwnInformation.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR adds API test scenarios to get user own information with `Graph API` 
1. `Scenario: user gets his/her own information with no group involvement`
2. `Scenario: user gets his/her own information with group involvement`
https://github.com/owncloud/ocis/issues/4937

[tests-only][full-ci]Added test to get user information with GraphAPI

---

changelog/unreleased/add-deprecation-annotation.md
docs/helpers/adoc-generator.go.tmpl
docs/templates/ADOC.tmpl

Enhancement: Add deprecation annotation
We have added the ability to annotate variables in case of deprecations:
refs #3917 
Example code for testing:
`services/nats/pkg/config/config.go`
```
Host string `yaml:"host" env:"NATS_HOST_ADDRESS,NATS_NATS_HOST" desc:"Bind address." deprecationVersion:"1.6.2" removalVersion:"1.7.5" deprecationInfo:"the name is ugly" deprecationReplacement:"NATS_HOST_ADDRESS"`
```

Add depreaction annotations to variables

---

docs/ocis/development/deprecating-variables.md

In the deprecation document there is a typo `on` --> `one` Missed that one while reviewing.

[Docs] Fix minor typo

---

tests/acceptance/features/apiSpaces/changeSpaces.feature

related https://github.com/owncloud/ocis/issues/4328
- check that ` "total": 0` after setting an unrestricted quota to personal and project space

[test-only] ApiTest. check unrestricted quota

---

services/graph/pkg/service/v0/driveitems.go
services/graph/pkg/service/v0/driveitems_test.go
services/graph/pkg/service/v0/drives.go
services/graph/pkg/service/v0/graph_test.go
services/graph/pkg/service/v0/groups_test.go
services/graph/pkg/service/v0/instrument.go
services/graph/pkg/service/v0/logging.go
services/graph/pkg/service/v0/service.go
services/graph/pkg/service/v0/tracing.go

Increase test coverage of the graph service.
Fixes #5016

Graph test coverage driveitems

---

.drone.star

We need some more triggers for Drone to run also on the stable branch.
- Helps #5160 
- test case 1:
- test case 2:
- ...

[tests-only] prepare stable-2.0 branch for CI

---

docs/ocis/storage/storagedrivers.md

Corrected path in docs Storage drivers section `<a href="https://github.com/owncloud/ocis/edit/master/docs/ocis/storage/storages.md">Edit page</a>` to `<a href="https://github.com/owncloud/ocis/edit/master/docs/ocis/storage/storagedrivers">Edit page</a>`

corrected storagedrives.md path in the doc

---

.drone.star

Fix CI on stable-2.0 branch
Drone was not running on the stable-2.0 branch because we were exceeding the `depends_on` limit.
- test case 1:
- test case 2:
- ...

[tests-only] Fix stable ci 2

---

tests/acceptance/features/apiSpaces/publicLink.feature

This PR adds API tests scenarios for public link of space from viewer role perspective
`public tries to upload resource in the public space`
`public tries to create resource in the public space`
`public tries to delete a file in the public space`
`public tries to delete a folder in the public space`
`public tries to change content of a resource in the public space`
https://github.com/owncloud/ocis/issues/4937

[tests-only][full-ci]Added test for `space` public link

---

.drone.env
tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
tests/acceptance/features/bootstrap/SpacesContext.php

related: https://github.com/owncloud/ocis/issues/5144#issuecomment-1329753744
add checking that the user or recipient can restore a file even if there is not enough quota to do so

[tests-only] ApiTest. restore file while quota is exceeded

---

services/graph/pkg/service/v0/drives.go
services/graph/pkg/service/v0/graph_test.go
services/graph/pkg/service/v0/groups.go
services/graph/pkg/service/v0/groups_test.go
services/graph/pkg/service/v0/password.go
services/graph/pkg/service/v0/users.go
services/graph/pkg/service/v0/users_test.go
services/notifications/pkg/service/service.go
services/search/pkg/search/provider/events.go
services/search/pkg/search/provider/searchprovider.go

we had some duplicate imports, this PR removes the `ctxpkg` in favor of the more expressive `revactx`

align revactx package import

---

tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

Added API tests for sharing spaces with the group.
1. `Scenario Outline: A user share a space to group with any role`
- Part of https://github.com/owncloud/ocis/issues/4937 (share space to group. check that is deny)
- Locally
- CI

[full-ci] [tests-only] Added api test for sharing spaces to group

---

.drone.star
tests/acceptance/config/behat.yml
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiCors/cors.feature

Skipping core CORS API tests in https://github.com/owncloud/core/pull/40527
So adding cors tests locally here.
- part of https://github.com/owncloud/core/issues/40104
- Depends on: https://github.com/owncloud/core/pull/40527

[tests-only][full-ci] Add CORS API tests

---

.drone.star

The local API tests were not running nightly after PR #5187. This PR has the fix for the CI trigger.
Nightly run: https://drone.owncloud.com/owncloud/ocis/17544

[tests-only][full-ci] Fix stable2 nightly CI trigger

---

tests/acceptance/config/behat.yml
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpacesShares/publicLinkDownload.feature
tests/acceptance/features/bootstrap/SpacesContext.php

- Adds API test for
- https://github.com/owncloud/ocis/issues/5229 
- https://github.com/owncloud/ocis/issues/5027
- locally
- CI

[tests-only][full-ci]Add api tests public link folder download

---

services/notifications/pkg/command/server.go
services/notifications/pkg/email/templates/spaces/unsharedSpace.email.body.tmpl
services/notifications/pkg/email/templates/spaces/unsharedSpace.email.subject.tmpl
services/notifications/pkg/service/service.go
services/notifications/pkg/service/spaces.go

The notification when a user was added to a space was already implemented so adding the unshare notification was fairly straightforward.

Spaces member notifications

---

tests/acceptance/features/apiContract/propfind.feature
tests/acceptance/features/apiContract/report.feature
tests/acceptance/features/bootstrap/SpacesContext.php

We don't really need to mention the user name in the step:
```
Then for user "Alice" the "PROPFIND" response should contain a space "new-space" with these key and value pairs:
```
That user is used to find out information about the space, and compare it with what came in a previous response (which was remembered from the result of a When step). We already remember the user who created each space, so we can use that user inside the Then step, when we want to do any extra requests about the space.
IMO this reduces confusion a bit when reading the scenarios.
CI

[tests-only] [full-ci] Refactor the response should contain

---

changelog/unreleased/fix-postprocessing.md
services/postprocessing/pkg/command/server.go
services/postprocessing/pkg/config/config.go

Makes it possible to use postprocessing service without `OCIS_INSECURE` flag

Fix Postprocessing service

---

changelog/unreleased/enhancement-tags.md
services/frontend/pkg/revaconfig/config.go

tags are technically ported but where not enabled in the capabilities.
This is fixed now.
- Extends https://github.com/owncloud/ocis/pull/5227

enable tags in capabilities

---

services/graph/pkg/identity/backend.go
services/graph/pkg/identity/err_school.go
services/graph/pkg/identity/ldap.go
services/graph/pkg/identity/ldap_education_user.go
services/graph/pkg/identity/ldap_education_user_test.go
services/graph/pkg/identity/ldap_school.go
services/graph/pkg/identity/ldap_school_test.go
services/graph/pkg/identity/mocks/education_backend.go
services/graph/pkg/service/v0/educationschools.go
services/graph/pkg/service/v0/educationschools_test.go
services/graph/pkg/service/v0/educationuser.go
services/graph/pkg/service/v0/instrument.go
services/graph/pkg/service/v0/logging.go
services/graph/pkg/service/v0/service.go
services/graph/pkg/service/v0/tracing.go

This implements GetEducationUser, GetEducationUsers, DeleteEducationUser and  CreateEducationUser methods for the LDAP backend. It's still very basic and  no fancy filtering or expanding is there yet.:
Note: This is currently based on #5213.  Let's get that merged first.

[full-ci] graph: Initial LDAP support for /education/users

---

services/postprocessing/pkg/config/config.go

This PR fixes the descriptions of the new postprocessing service. It aligns the text where possible to existing or similar descriptions.
* Though I have improved the `POSTPROCESSING_VIRUSSCAN` desc - this still needs improvement as the text is not final. The reason / usecase setting this envvar is not clear.
* Same for `POSTPROCESSING_DELAY`. Why is this setting needed, do we also have ms (milliseconds) and what is the impact when set.
@kobergj can you add the missing pieces?
none
Make the envvars well described.
Text change only

Fix the description of the postprocessing service

---

docs/helpers/extended_vars.yaml
docs/templates/ADOC_global.tmpl

Just a small update of an:
* extended envvar description to be more precise and avoid misinterpretation.
* use the correct word in the table headline (extended instead of global, was a remnant)

Improve extended env var description

---

protogen/gen/ocis/messages/settings/v0/settings.pb.go
protogen/gen/ocis/services/thumbnails/v0/thumbnails.pb.go

When running `make docs-generate` two files always get blank comment lines added. This is annoying when running make locally as the files pop up as change.
By adding the blank comment lines by default, we get rid of the unrelated change note when running the make command.

Add blank comment lines

---

docs/helpers/extended_vars.yaml

The extended envvar yaml file needs a small update because `make docs-generate` adds a linebreak. This would pop up as change on every lokal make run 😢

Update extended envvar yaml file

---

tests/acceptance/features/apiContract/copy.feature
tests/acceptance/features/bootstrap/SpacesContext.php

- I check the value of the response headers in the test
- I did not add a folder copy test because there is no folder ID in the response headers.
- I'm not sure which items I should test (maybe hint in the review process): 
- `content-length = 0` though file isn't 0 bytes - Probably it's bug
and I have lint error `make: *** [test-php-style] Error 8` when I run `make test-php-style-fix`

[test-only] Apitest. check Copy response headers test

---

changelog/unreleased/425-on-thumbnails.md
services/thumbnails/pkg/service/grpc/v0/service.go
services/webdav/pkg/service/v0/service.go

Returns `425` on thumbnails when file is processing. Also passes `425` through webdav handler.

425 Friendly Thumbnails

---

tests/acceptance/features/apiContract/propfind.feature

Expanding the `PROPFIND` of a space to not only the space-admin who created it but also to the member of a space with different role.
https://github.com/owncloud/ocis/issues/4937
https://github.com/owncloud/ocis/pull/5138#issuecomment-1357087867

[tests-only][full-ci]Extend Propfind of space to space-member

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

Bump the core latest commit id on ocis `master`.
https://github.com/owncloud/QA/issues/791

[tests-only][full-ci]Bump core latest commit id on ocis

---

.drone.star
changelog/unreleased/bump-libregraph.md
changelog/unreleased/drive-group-permissions.md
go.mod
go.sum
services/graph/pkg/service/v0/drives.go
tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

Expose drive group permissions
Bump libre-graph-api-go
* rename drive permission grantedTo to grantedToIdentities tob be ms graph spec compatible.
* drive.name is a required property now.
* add group property to the identitySet.
Expose drive group permissions
* libregraph.Drive response contains group permission informations.

[full-ci] Bump libre-graph-api-go and drive group permissions

---

.drone.env
tests/acceptance/expected-failures-API-on-OCIS-storage.md

Bump core commit id to the latest
Part of https://github.com/owncloud/QA/issues/792

[tests-only][full-ci] Bump core commitid (stable)

---

.drone.star
tests/TestHelpers/HttpRequestHelper.php
tests/acceptance/config/behat.yml
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiAsyncUpload/delayPostprocessing.feature
tests/acceptance/features/bootstrap/AuthContext.php
tests/acceptance/features/bootstrap/WebDavPropertiesContext.php

Add API tests with delayed postprocessing to check too early response code
- GET a file
- PROPFIND a file
- PROPFIND a folder having file that is in processing
Closes https://github.com/owncloud/ocis/issues/4095

[tests-only][full-ci] Add tests with explicit delay post-processing enabled

---

tests/acceptance/features/apiSpaces/tusUpload.feature
tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature
tests/acceptance/features/bootstrap/SpacesTUSContext.php

I changed apiTest in ocis like in https://github.com/owncloud/core/pull/40539 and according to
comment: https://github.com/owncloud/ocis/issues/5054#issuecomment-1352776560
`upload-length: 24` header corresponds to the content "The file content is 24 bytes"
methods `When user "Alice" creates a new TUS resource for the space "Project Jupiter" using the WebDAV API with these headers:` and `And user "Alice" has created a new TUS resource for the space "Personal" using the WebDAV API with these headers:` used by default content = "" but `Upload-Length` in headers is not 0. is it correct?

ApiTest. Change test create new tus resource

---

services/storage-users/pkg/config/config.go

The description of the `STORAGE_USERS_DRIVER` envvar was incomplete. It missed the `s3ng` and `owncloudsql` driver.
This came up while documenting [s3ng bucket policy](https://github.com/owncloud/docs-ocis/issues/288) (issue in docs-ocis).
When reading the helm chart referenced, also see its [representation in the admin docs](https://doc.owncloud.com/ocis/next/deployment/container/orchestration/tab-pages/values-tab-1.html) (search for `storageUsers:`) you see that we have described in the comment the `ocis` driver but not `s3ng`.
Note that you can see all three values also in the [storage-user](https://doc.owncloud.com/ocis/next/deployment/services/s-list/storage-users.html) documentation (both envvar and yaml). Means, most likely just forgotten - pls check.
Post merging this, we need to …

Complete description of STORAGE_USERS_DRIVER

---

services/_includes/adoc/storage-users_configvars.adoc

References: #5345 (Complete description of STORAGE_USERS_DRIVER)
Backports the above PR to the `docs-stable-2.0` branch

Backport of STORAGE_USERS_DRIVER description changes to docs-stable-2.0

---

services/graph/pkg/identity/backend.go
services/graph/pkg/identity/ldap.go
services/graph/pkg/identity/ldap_education_user.go
services/graph/pkg/identity/ldap_school.go

This makes the identity errors public so other packages can match on them.
It also moves them to the same file as the interface, as that makes them more discoverable.

Make identity errors public.

---

changelog/unreleased/bugfix-disassociate-users-from-deleted-school.md
services/graph/pkg/service/v0/educationschools.go
services/graph/pkg/service/v0/educationschools_test.go

This PR alters the `DeleteEducationSchool` to also disassociate the
users that were associated with the to-be-deleted school.
- Fixes #5246 
It solves that users still point to a non-existent school.
- test environment: I tested it with a local ldap, removing a school and checking if users were disassociated.
- ...

Disassociate users from schools on school delete.

---

services/graph/pkg/service/v0/drives.go
services/graph/pkg/service/v0/educationschools.go
services/graph/pkg/service/v0/educationuser.go
services/graph/pkg/service/v0/groups.go
services/graph/pkg/service/v0/ordering.go
services/graph/pkg/service/v0/users.go

As suggested in: https://github.com/owncloud/ocis/pull/5213#discussion_r1054343754 
Switch to sort.Slice() instead of sort.Sort(), which requires less boilerplate.

Simplify sort code a bit

---

changelog/unreleased/enhancement-add-configurable-group-members-patch-limit.md
services/graph/pkg/config/config.go
services/graph/pkg/config/defaults/defaultconfig.go
services/graph/pkg/service/v0/groups.go
services/graph/pkg/service/v0/groups_test.go

This PR changes the following:
* Create an API config section for API configurables.
* Add a setting `UserPatchLimit` that controls how many users can be changed in a PATCH request.
* Use this setting in the API to limit the amount of users that can be changed.

Make amount of group members in patch configurable.

---

tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

- Tests for removing a group from a space

[test-only] apiTest. Delete group from the space

---

services/graph/pkg/service/v0/groups_test.go

since https://github.com/owncloud/ocis/pull/5347, NewService also returns a [error](https://github.com/owncloud/ocis/blob/0a97af2793416e113284931ec2a624f59126902b/services/graph/pkg/service/v0/service.go#L81). 
The pipeline was green but https://github.com/owncloud/ocis/commit/43a98c0485c86bc09c9985a98f15486977617a83 introduced a new test which fails (no err return value).
bad luck :cry.

fix failing master unit tests that arose during the merge

---

changelog/unreleased/collect-global-envvars.md
docs/helpers/adoc-generator.go.tmpl
docs/templates/ADOC_global.tmpl

Compose a list of envvars living in more than 1 service

Collect global Envvars

---

services/graph/pkg/identity/backend.go
services/graph/pkg/identity/err_school.go
services/graph/pkg/identity/ldap_school.go
services/graph/pkg/identity/ldap_school_test.go
services/graph/pkg/identity/mocks/education_backend.go
services/graph/pkg/service/v0/educationschools.go
services/graph/pkg/service/v0/educationschools_test.go

This adds the missing PATCH functionality for updating a school using a school name or number.
As we can't have an atomic operation when updating the OU and another property, this only allows mutually exclusive updates of school number or name.
Note: The ldap update functions themselves do not have tests, but rather the "glue" function to select which operation to perform in UpdateEducationUser.
- Fixes #5245 
This adds the missing update implementation.
I tested this locally with curl and added testcases for the different input data scenarios.

Adding so education PATCH updates school name or number.

---

.drone.star

Rolls wopi back to `v9.3.0`  as it seems to be stable (unlike `v9.3.2`)

[tests-only] Rollback Wopi

---

tests/acceptance/features/coreApiVersions/fileVersions.feature

Added these scenarios:
```feature
Scenario: Upload the same file twice with the same mtime and a version is available
Scenario: Upload the same file more than twice with the same mtime and only one version is available
Scenario: Upload the same file twice with the same mtime and no version after restoring
```
Test added for https://github.com/owncloud/ocis/issues/5010

[tests-only][full-ci] Added tests for checking version of file uploaded with same mtime twice

---

go.mod
go.sum
ocis/pkg/init/init.go
services/graph/pkg/config/application.go
services/graph/pkg/config/config.go
services/graph/pkg/config/defaults/defaultconfig.go
services/graph/pkg/config/parser/parse.go
services/graph/pkg/config/service.go
services/graph/pkg/service/v0/application.go
services/graph/pkg/service/v0/application_test.go
services/graph/pkg/service/v0/approleassignments.go
services/graph/pkg/service/v0/approleassignments_test.go
services/graph/pkg/service/v0/educationuser_test.go
services/graph/pkg/service/v0/instrument.go
services/graph/pkg/service/v0/logging.go
services/graph/pkg/service/v0/service.go
services/graph/pkg/service/v0/tracing.go
services/graph/pkg/service/v0/users.go
services/graph/pkg/service/v0/users_test.go
services/settings/pkg/service/v0/service.go
services/settings/pkg/settings/settings.go
services/settings/pkg/store/errortypes/errortypes.go
services/settings/pkg/store/filesystem/bundles.go
services/settings/pkg/store/filesystem/io.go
services/settings/pkg/store/filesystem/permissions.go
services/settings/pkg/store/metadata/assignments.go
services/settings/pkg/store/metadata/bundles.go
services/settings/pkg/store/metadata/permissions.go
services/settings/pkg/store/metadata/store_test.go
services/settings/pkg/store/metadata/values.go

For now, I decided to intdroduce an application that is configured with `GRAPH_APPLICATION_ID` and `GRAPH_APPLICATION_DISPLAYNAME`. They are necessary to represent an application that owns the roles. In our case that is oCIS.
First question: is it only oCIS Web? I currently default to `"oCIS Web"`. 
Second question: the application id should be randomized on init. AFAICT it resembles the oc10 instance id. Although I'm not sure if it is the web client or the server side, see first question. The more I type the more I think it is the server side.
Third question: if we make the id configurable then we require clients to know the application id in advance. Should we implement listing applications at `/applications`? That way clients could discover the applications that are available. The …

graph: add appRoleAssignments and minimal application resource

---

.drone.env
services/settings/ui/components/settings/SettingMultiChoice.vue
services/settings/ui/components/settings/SettingSingleChoice.vue
services/web/Makefile
services/web/pkg/config/defaults/defaultconfig.go
tests/config/drone/ocis-config.json

This PR updates ownCloud Web to v7.0.0-rc.6. Which is the first version of ownCloud Web running on vue3 in compat mode.
@dschmidt could you please push fixes for the settings ui into this branch?

[full-ci] update web assets to v7.0.0-rc.6

---

docs/helpers/README.md

References: #5377 (Content of the 'docs-stable-2.0' branch gets magically deleted)
The docs/helpers and the processes behind need a proper description and how to handle backports.
Language review welcomed.
Backport to the `stable-2.0` necessary.

[docs-only] Properly describe docs/helpers and processes

---

services/graph/pkg/identity/ldap.go
services/graph/pkg/identity/ldap_test.go

To make the `CreateUser` flow easier to test, the attributes of the
LDAP add request need to be added consistently. This way we can
expect that argument with the mock.
This PR does the following:
* Add a method `getUserAttrTypes` that returns a static list of attr names.
* Alter `userToAddRequest` to iterate over the static list, and add the attr
if it exists in the `attrMap`.
Closes #5390

Consistently add user attributes to AddRequest

---

changelog/unreleased/share-expiration.md
go.mod
go.sum
services/frontend/pkg/revaconfig/config.go
services/sharing/pkg/revaconfig/config.go

Added expiration to user and group shares.
- locally with a web browser

add expiration to user and group shares

---

services/graph/pkg/service/v0/graph_test.go
services/graph/pkg/service/v0/groups_test.go
services/graph/pkg/service/v0/users_test.go

The path part of requests in the tests are not really evaluated because of https://github.com/owncloud/ocis/issues/5209
This PR at corrects the path by removing an accidential c'n'p `/me`

drop superflous /me in test urls

---

tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature

- Test for: https://github.com/owncloud/ocis/issues/4758
- Locally
- CI

[tests-only][full-ci] Adds tests for checking  href of the public link share

---

services/graph/pkg/config/config.go
services/graph/pkg/config/defaults/defaultconfig.go
services/graph/pkg/config/parser/parse.go
services/graph/pkg/service/v0/educationuser.go
services/graph/pkg/service/v0/users.go
services/graph/pkg/service/v0/users_test.go

Via configuration you can now configure to skip the validation of username and instead decide to trust the upstream system that is adding users.
- Fixes #5255 
I have added two tests for checking that bypassing the default regex works.
Also did some exploratory testing with adding users with spaces in the username. I did not test that extensively, but found some bugs.
```
Exploratory testing notes:
--------------------------
After adding a user with spaces in the name, I can log in with that user in the UI.
Sharing a text file from user with spaces in the name works.
Sharing an image to/from user with spaces works 
Sharing a gif to a user with spaces in the name does not work.
Looking in the UI gives a 500 when trying to get thumbnail:
<d:error xmlns:d="DAV" …
```

graph: Allow provisioning users with legacy names (#5255)

---

changelog/unreleased/populate-expanded-properties.md
services/graph/pkg/identity/ldap.go
services/graph/pkg/identity/ldap_group.go
services/graph/pkg/service/v0/drives.go
services/graph/pkg/service/v0/drives_test.go
services/graph/pkg/service/v0/educationuser.go
services/graph/pkg/service/v0/graph_test.go
services/graph/pkg/service/v0/users.go

We now return an empty array when an expanded relation has no entries. This makes consuming the responses a little easier.
fixes https://github.com/owncloud/ocis/issues/5419

Populate expanded properties

---

.drone.star
Makefile
docs/ocis/development/testing.md

when @Excds  tried to run api test based on the documentation, it turned out that the docs is not up to date
I updated docs tests agains ocis binary
@phil-davis @individual-it could you please have look on the https://owncloud.dev/ocis/development/testing/#testing-with-test-suite-in-docker part. it practically doesn't work. does it need to be fixed?

[docs-only] Change Testing section in the doc

---

tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature

- It is the back-port of PR https://github.com/owncloud/ocis/pull/5415 merged on `master` to `stable-2.0`

[tests-only][full-ci] Backport test scenarios for changing role of public link to internal to stable-2.0

---

services/graph/pkg/service/v0/users.go
services/graph/pkg/service/v0/users_test.go
tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiGraph/createUser.feature

Allow creating users without email via API.
Fixes https://github.com/owncloud/ocis/issues/5253
Updated acceptance tests to check for this and also tested manually with curl.

graph: Allow creating users without email (#5253)

---

docs/ocis/development/testing.md

The formatting seemed off in the docs. It looked like this 
This Pr adds a line break to make it look nicer

[docs-only] Fix formatting in the docs related to testing

---

services/settings/pkg/store/defaults/defaults.go

PR needed because stupid me cannot spell `Enabled`

[tests-only] Fix Space Management Permissions

---

changelog/unreleased/populate-expanded-properties.md
services/graph/pkg/service/v0/users.go
services/graph/pkg/service/v0/users_test.go

continuation of https://github.com/owncloud/ocis/pull/5421
The personal `drive` should not be part of the `drives` list.
And when decomposedfs supports the space owner filter we should use that instead of a user + space type "personal" filter, but not part of this PR.

fix populating user drive and drives

---

docs/helpers/adoc-generator.go.tmpl
docs/templates/ADOC.tmpl
docs/templates/ADOC_deprecation.tmpl

Backports deprecation fixes for the docs. Original PR: https://github.com/owncloud/ocis/pull/5467

[docs-only] Backport Deprecation Fixes

---

ocis-pkg/log/log.go

Add a runtime hook for the zerolog setup to log line number and file when log level is set to debug.
I was trying to run ocis and to add users via /graph/v1.0/users API, but some environment variable or configuration was wrong and I was getting 500 errors. In the log I only saw this:
```
2023-01-26T11:33:40+01:00 ERR error initializing metadata client error="error: not found: create container: error: not found: f1bdd61a-da7c-49fc-8203-0558109d1b4f!f1bdd61a-da7c-49fc-8203-0558109d1b4f/settings" service=ocis
2023-01-26T11:33:40+01:00 ERR Could not load roles error="{\"id\":\"go.micro.server\",\"code\":500,\"detail\":\"panic recovered: runtime error: invalid memory address or nil pointer dereference\",\"status\":\"Internal Server Error\"}" service=proxy
2023-01-26T11:33:40+01:00 ERR Could …
```

Add line number and file to log messages when at debug level.

---

services/graph/pkg/identity/backend.go
services/graph/pkg/identity/err_education.go
services/graph/pkg/identity/ldap_education_class.go
services/graph/pkg/identity/ldap_education_class_test.go
services/graph/pkg/identity/ldap_education_school.go
services/graph/pkg/identity/ldap_education_school_test.go
services/graph/pkg/identity/ldap_education_user.go
services/graph/pkg/identity/mocks/education_backend.go
services/graph/pkg/service/v0/educationschools.go
services/graph/pkg/service/v0/educationschools_test.go
services/graph/pkg/service/v0/instrument.go
services/graph/pkg/service/v0/logging.go
services/graph/pkg/service/v0/service.go
services/graph/pkg/service/v0/tracing.go

This PR does the following:
Adds handlers for `/education/schools/{schoolID}/classes/{$ref,classID,}` to allow the requesting and manipulation of classes.
This fixes #5412

Allow assiging/unassigning classes to schools

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/getUser.feature
tests/acceptance/features/bootstrap/GraphContext.php

I added test for getting group info of the user: `curl -X GET 'https://localhost:9200/graph/v1.0/users/2569c4ad-4abc-4f40-9490-5db0b66dcedc?%24expand=memberOf' -uadmin:admin -vk`

[test-only] api tests for getting group info of user

---

.drone.star
deployments/continuous-deployment-config/oc10_ocis_parallel/latest.yml
deployments/continuous-deployment-config/ocis_hello/latest.yml
deployments/continuous-deployment-config/ocis_keycloak/latest.yml
deployments/continuous-deployment-config/ocis_keycloak/released.yml
deployments/continuous-deployment-config/ocis_ldap/released.yml
deployments/continuous-deployment-config/ocis_s3/latest.yml
deployments/continuous-deployment-config/ocis_traefik/daily.yml
deployments/continuous-deployment-config/ocis_traefik/latest.yml
deployments/continuous-deployment-config/ocis_traefik/released.yml
deployments/continuous-deployment-config/ocis_wopi/daily.yml
deployments/continuous-deployment-config/ocis_wopi/latest.yml
deployments/continuous-deployment-config/ocis_wopi/released.yml
deployments/examples/ocis_wopi/docker-compose.yml
docs/ocis/deployment/continuous_deployment.md

add "daily" deployments to the continuous deployment to provide a more stable up-to-date alternative to "latest" deployments
- Web part https://github.com/owncloud/web/pull/8346 
provide more stable, but up-to-date deployments
- -

add "daily" deployments to the continuous deployment

---

.drone.env
services/web/Makefile

Bump web to v7.0.0-rc.11. One of the things it brings are the web changes for space member expirations. So this should unblock https://github.com/owncloud/ocis/pull/5453

[full-ci] bump web to v7.0.0-rc.11

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/restoreSpaces.feature
tests/acceptance/features/apiSpaces/spaceManagement.feature
tests/acceptance/features/apiSpaces/tag.feature
tests/acceptance/features/bootstrap/SpacesContext.php

related https://github.com/owncloud/ocis/pull/5441
created tests in which a user with space administrator rights can:
-  get all project spaces
- get all personal spaces - not secure
- edit the space name
- edit the space description
- edit quota of project spaces
- edit quota personal spaces - I have my doubts here @micbar . I think this should only be available to the administrator/ created bug https://github.com/owncloud/ocis/issues/5475
- disable spaces
- disable personal space
- enable spaces
- delete a space

[test-only]ApiTest. tests for spaceManagement

---

tests/acceptance/features/apiSpaces/quota.feature
tests/acceptance/features/bootstrap/OCSContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

This PR adds test scenario for confirming the relative quota amount of personal space.
- Related to https://github.com/owncloud/ocis/issues/4357
- Locally
- CI

[tests-only][full-ci] Test scenarios for relative quota amount of personal space

---

services/search/README.md

I wrote down what comes to mind about the search service, @mmattel  please read what you think about it.
I haven't proofread much, please check for spelling mistakes too ;)

[docs-only] search service readme

---

docs/_index.md
docs/ocis/_index.md
docs/ocis/deployment/basic-remote-setup.md
docs/ocis/deployment/monitoring-tracing.md
docs/ocis/getting-started/_index.md
docs/services/port-ranges.md
docs/services/settings/_index.md
docs/services/settings/bundles.md
docs/services/settings/glossary.md

Replace some legacy used `Extensions` by `Services`
Just found while reading dev docs.
Will show up in owncloud.dev harmonized with admin docs.
Text change only

[docs-only] Replace the legacy Extensions with Services

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

I have extended the check: after sharing space with a group, I check the request "me/spaces" to make sure that it contains the group type and groupId

[test-only] ApiTests. check group in the space request

---

go.mod
go.sum
services/graph/pkg/service/v0/drives.go

This PR changes the structure of the space permissions and adds an optional expiration date.
Now the `permissions` array holds one object per grant instead of holding one object per role like before.

add an expiration to the space member permissions

---

ocis-pkg/config/config.go
ocis-pkg/shared/shared_types.go
services/idm/pkg/config/config.go
services/settings/pkg/config/config.go

Fixes: #5517 (Inconsistant description of OCIS_ADMIN_USER_ID)
The description had room for improvement. Fixed based on input of @micbar, see referenced issue.
Needs backporting to stable-2.0 @kobergj

[docs-only] Improve the description of the OCIS_ADMIN_USER_ID envvar

---

services/graph/pkg/service/v0/service.go
services/graph/pkg/service/v0/users.go

This PR adds two endpoints:
```
GET /graph/v1.0/me/drive
GET /graph/v1.0/users/{userid}/drive
```
which will return the users drive:
```
{
"driveAlias": "personal/einstein",
"driveType": "personal",
"id": "1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51",
"lastModifiedDateTime": "2023-02-09T11:02:01.958840593Z",
"name": "Albert Einstein",
"owner": {
"user": {
"displayName": "",
"id": "4c510ada-c86b-4815-8820-42cdf82c3d51"
}
},
"quota": {
"remaining": 160010825728,
"state": "normal",
"total": 0,
"used": 0
},
"root": {
"eTag": "\"8d566fda9a7d143f7e6c16fe78230e71\"",
"id": "1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51",
"webDavUrl": "https://cloud.ocis.test/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d …
```

allow GETing a users personal drive

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature
tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature

As ownclouders decided https://github.com/owncloud/ocis/issues/4052#issuecomment-1168655027
> It was officially agreed that we do act differently than oc10. If the permissions requested by the client are not applicable we return an error (unlike oc10 which will downgrade permissions to 1)
Share permission behavior is different in oc10 and ocis.
This PR changes coreApiSharePublicLinkShare folder
- refactor public link share permission related scenario
- remove @skipOnOcis tagged scenario
- https://github.com/owncloud/ocis/issues/5249
- https://github.com/owncloud/ocis/pull/5490 (master branch)
- locally

[full-ci][tests-only]Refactor share permission in coreApiSharePublicLinkShare

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature
tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature

As ownclouders decided https://github.com/owncloud/ocis/issues/4052#issuecomment-1168655027
> It was officially agreed that we do act differently than oc10. If the permissions requested by the client are not applicable we return an error (unlike oc10 which will downgrade permissions to 1)
Share permission behavior is different in oc10 and ocis.
This PR changes coreApiSharePublicLinkShare folder
- refactor public link share permission related scenario
- remove @skipOnOcis tagged scenario
https://github.com/owncloud/ocis/issues/1317    https://github.com/owncloud/ocis/issues/4623 
we will work on this https://github.com/owncloud/ocis/issues/5519
- https://github.com/owncloud/ocis/issues/5249
- https://github.com/owncloud/ocis/pull/5490 (master branch)
- locally

[full-ci][tests-only]Forward-port refactor share permission in coreApiSharePublicLinkShare

---

docs/ocis/deployment/continuous_deployment.md

The demo user can be found in https://owncloud.dev/ocis/getting-started/demo-users/ the current link https://owncloud.dev/ocis/getting-started/#login-to-owncloud-web requires clicking on another link.

Change link reference for demo users

---

.drone.env
services/web/Makefile

Bumps web to v7.0.0-rc.13
Contains `group filtering` for the user list in `admin-settings` and the `logo upload / reset` in the appearance section of the `admin-settings`. Should only be merged after following ocis PRs have been merged.
- https://github.com/owncloud/ocis/pull/5559
- https://github.com/owncloud/ocis/pull/5533

[full-ci] chore: bump web to v7.0.0-rc.13

---

go.mod
go.sum
services/audit/pkg/service/service.go
services/audit/pkg/service/service_test.go
services/notifications/pkg/service/service.go
services/notifications/pkg/service/service_test.go
services/postprocessing/pkg/service/service.go
services/search/pkg/search/events.go
services/storage-users/pkg/event/service.go

This bumps reva to v2.12.1-0.20230214085134-ec27f5f8feb3, pulling in the events change from https://github.com/cs3org/reva/pull/3637 causing several changes.

[full-ci] bump reva to ec27f5f8feb3

---

changelog/unreleased/list-permissions.md
services/settings/pkg/service/v0/service.go

Quickfix: adds constraints to the listed permission names.
Will have a follow up PR to clean up the broken naming pattern.
Unblocks @JammingBen 
| value |
|---|
| unknown |
| own |
| shared |
| all | 
```sh
curl -L -k -X POST 'https://localhost:9200/api/v0/settings/permissions-list' \
-H 'Content-Type: application/json' \
--data-raw '{
"account_uuid": "4c510ada-c86b-4815-8820-42cdf82c3d51"
}'
```
```json
{
"permissions": [
"list-all-spaces.all",
"language-readwrite.own",
"self-management.own",
"create-space.own",
"Drive.ReadWrite.all",
"Drive.ReadWriteEnabled.all",
"set-space-quota.all",
"create-space.all"
]
}
```
- test case 1:
- test case 2:
- ...

add constraints to permissions listing

---

services/graph/pkg/config/config.go
services/graph/pkg/config/defaults/defaultconfig.go
services/graph/pkg/identity/ldap.go
services/graph/pkg/identity/ldap_education_class_test.go
services/graph/pkg/identity/ldap_education_school_test.go
services/graph/pkg/identity/ldap_group_test.go
services/graph/pkg/identity/ldap_test.go

Add boolean accountEnabled property to users in the ldap backend.
- Fixes #5553 
Tested manually with curl and added unit tests.

graph: Add accountEnabled flag to ldap backend.

---

.drone.env
services/web/Makefile

bump web to v7.0.0-rc.14
includes permission checks, so this should unblock further work on defining roles via config. cc @micbar

[full-ci] chore: bump web to v7.0.0-rc.14

---

deployments/examples/ocis_ldap/docker-compose.yml
services/graph/pkg/config/config.go
services/graph/pkg/identity/ldap.go

When refint is enabled on an LDAP server, it will rename all references
to an entity if its DN is modified. If this happens, the member
renames will not be needed, and will also return an error.
This PR does the following:
* Detects the attribute error, and don't return an error.
* Log that the server has been misconfigured.
* Add config value that skips renaming if set.

Add refint support to user rename.

---

tests/acceptance/lint-expected-failures.sh
tests/acceptance/run.sh

When using GitHub workflows (for example, in cs3org/reva) the acceptance test output is not being formatted nicely. There are lots of escape sequences that would normally select different colors for text. But the escape sequences are being shown, rather than rendering the colors.
This PR allows the acceptance tests to be run with plain output by defining the environment variable PLAIN_OUTPUT when running the tests. Just defining it is enough, the value does not matter.
CI

[tests-only] allow plain acceptance test output

---

services/graph/pkg/service/v0/users_filter.go
services/graph/pkg/service/v0/users_test.go

This add support for filtering on the `appRoleAssignment` relation of users.  E.g.
```
$filter=appRoleAssignments/any(m:m/appRoleId eq '262982c1-2362-4afa-bfdf-8cbfef64a06e')
```
combining it with a filter on groupMemberShip does also work:
```
$filter=memberOf/any(m:m/id eq '262982c1-2362-4afa-bfdf-8cbfef64a06e') and appRoleAssignments/any(m:m/appRoleId eq 'd7beeea8-8ff4-406b-8fb6-ab2dd81e6b11')
```
The filter is still very inefficient as it always needs to get the full users list. We need to adapt it to only filter on a subset of users when using this filter 'and' combined with other filters.
Closes: #5488

Add support for $filter on appRoleAssignment

---

tests/acceptance/lint-expected-failures.sh
tests/acceptance/run.sh

Port PR #5598 to `stable-2.0` so that it can be used there when needed.

[tests-only] Allow plain acceptance test output stable

---

tests/acceptance/features/apiSpaces/listSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

[test-only] increase coverage test for creating space

---

tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

This PR adds tests to remove the expiration date from a space share in user and group space share
- Part of https://github.com/owncloud/ocis/issues/5413
- CI
- local

[tests-only][full-ci]Api tests for deleting  the expiration date of a space

---

changelog/unreleased/role-quota.md
go.mod
go.sum
services/frontend/pkg/config/config.go
services/frontend/pkg/revaconfig/config.go
services/proxy/README.md
services/proxy/pkg/command/server.go
services/proxy/pkg/config/config.go
services/proxy/pkg/middleware/create_home.go
services/proxy/pkg/middleware/options.go
services/storage-users/pkg/config/config.go
services/storage-users/pkg/revaconfig/drivers.go

Admins can assign default quotas to users with certain roles by added the following config to the `proxy.yaml`.
E.g.:
```
role_quotas:
d7beeea8-8ff4-406b-8fb6-ab2dd81e6b11: 2300000
```
It maps a role ID to the quota in bytes.
When https://github.com/cs3org/cs3apis/pull/203 was merged we should use the explicit parameter here and in Reva.

add config option to set default quota per role

---

tests/acceptance/run.sh

I got the assignment format wrong in PR #5598 
When running acceptance tests, `run.sh` emits:
```
./tests/acceptance/run.sh: line 38: RED_COLOR: command not found
./tests/acceptance/run.sh: line 39: GREEN_COLOR: command not found
./tests/acceptance/run.sh: line 40: YELLOW_COLOR: command not found
```
There should not be spaces around the `=` assignment operator.
CI

[tests-only] Fix command format in tests/acceptance/run.sh

---

changelog/unreleased/bump-reva.md
go.mod
services/storage-system/pkg/config/config.go
services/storage-system/pkg/config/defaults/defaultconfig.go
services/storage-system/pkg/revaconfig/config.go
services/storage-users/pkg/config/config.go
services/storage-users/pkg/config/defaults/defaultconfig.go
services/storage-users/pkg/revaconfig/drivers.go

bump reva to include https://github.com/cs3org/reva/pull/3649

[full-ci] Bump reva to include ini metadata backend

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/assignRole.feature
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/RoleAssignmentContext.php

This scenario adds scenario assign a role to a user using the graph API and check if its correctly listed by the graph API and and by the settings API
- https://github.com/owncloud/ocis/issues/5565#
- locally

[tests-only][full-ci]Add api tests to assign role using graph api

---

.drone.star
Makefile
tests/config/drone/check_go_bin_cache.sh

Caching `/go/bin` binaries as a long-term cache so that each linting and unit-testing pipeline won't have to rebuild the binaries again and again. This also makes the pipeline faster due to not having to rebuild the 
make work more efficient
annoy developers less
- running CI multiple times

[tests-only] Cache go/bin as a long term cache

---

services/userlog/pkg/service/service.go

Userlog panics on `FileDownloaded` and `ItemPurged` events because there is no owner in project spaces

[tests-only] Fix userlog panic

---

changelog/unreleased/portrait-thumbnails.md
services/thumbnails/pkg/config/defaults/defaultconfig.go

This adds corresponding portrait-orientation resolutions for each existing landscape-orientation resolution to the thumbnailer service's default config.
This improves, but does not actually fix, the following bug (affecting web):
- https://github.com/owncloud/ocis/issues/5179 
- https://github.com/owncloud/web/issues/7728 
Cropping portrait-orientation photos to landscape greatly reduces the usefulness of the resulting thumbnails (see the screenshots section below.)
I added these three portrait-orientation resolutions to the config on my own server, and it improved the behavior by allowing a portrait-orientation photo to have a portrait-orientation preview. (The behavior is still not ideal because the preview should not be cropped at all, but this at least allows me to see most of the …

thumbnails: Add portrait resolutions to default config

---

deployments/examples/ocis_ldap/config/ldap/ldif/10_owncloud_schema.ldif

When moving to the bitnami OpenLDAP image, we forgot to remove the owncloud schema file from the `ldif` directory.

ocis_ldap: Remove leftover schema file

---

deployments/examples/ocis_ldap/config/ldap/docker-entrypoint-override.sh
deployments/examples/ocis_ldap/docker-compose.yml

In the current docker-compose example the ldap server fails to start with
```
ocis_ldap-ldap-server-1  | writing new private key to '/opt/bitnami/openldap/certs/openldap.key'
ocis_ldap-ldap-server-1  | req: Can't open "/opt/bitnami/openldap/certs/openldap.key" for writing, Permission denied
```
This is due to `/opt/bitnami/openldap/certs/` being only writeable by root not the 1001 user used in the container. Possible directories to use are listen in https://github.com/bitnami/containers/blob/ca697710be7e425fbf07aa04649209e4279bf29e/bitnami/openldap/2.6/debian-11/rootfs/opt/bitnami/scripts/openldap/postunpack.sh#L18. @wkloucek and myself decided to use  `/opt/bitnami/openldap/share`
Non-starting ldap container in example
Tested by myself

fix: make ldap example use share for certs

---

docs/clients/rclone/webdav-sync-oidc.md
ocis/pkg/command/benchmark.go

For stress testing and analysis we added a two cli benchmark commands to gather different statistics or to put a system under load. use the cli help
```console
$ ocis/bin/ocis benchmark syscalls help
NAME:
ocis benchmark syscalls - test how fast syscalls are
USAGE:
ocis benchmark syscalls [command options] [arguments...]
CATEGORY:
benchmark
OPTIONS:
--path value        Path to test
--iterations value  Number of iterations to execute (default: "100")
--help, -h          show help
$ ocis/bin/ocis benchmark client help
NAME:
ocis benchmark client - Start a client that continuously makes web requests and prints stats. The options mimic curl, but URL must be at the end.
USAGE:
ocis benchmark client [command options] [arguments...]
CATEGORY:
benchmark
OPTIONS:
--request value, -X value …
```

Benchmark cli

---

services/storage-system/pkg/config/config.go
services/storage-users/pkg/config/config.go

The local envvars should have a common global envvar as we do with other services.
`OCIS_DECOMPOSEDFS_METADATA_BACKEND`; `STORAGE_SYSTEM_OCIS_METADATA_BACKEND`
and
`OCIS_DECOMPOSEDFS_METADATA_BACKEND`; `STORAGE_USERS_OCIS_METADATA_BACKEND`
- References: #5613
Keep things consitent, quote from @butonic 
> That can be done in a subsequent PR.
No code change

Add a global variable for the metadata backend

---

changelog/unreleased/graph-education-errors.md
services/graph/pkg/identity/ldap_education_class.go
services/graph/pkg/service/v0/educationclasses.go
services/graph/pkg/service/v0/educationschools.go
services/graph/pkg/service/v0/errorcode/errorcode.go

Aligned the error messages when creating schools and classes fail and changed the response code from 500 to 409.
Fixes: https://github.com/owncloud/ocis/issues/5660

make graph/education API errors more consistent

---

services/userlog/pkg/service/http.go
services/userlog/pkg/service/service.go

Forces userlog to not spread panic to other services.
Follow ups we tackled with notifications implementation this sprint

[tests-only] Fix userlog panics

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/bootstrap/OccContext.php
tests/acceptance/features/coreApiWebdavOperations/listFiles.feature
tests/acceptance/features/coreApiWebdavOperations/propfind.feature

Forward port of PR https://github.com/owncloud/ocis/pull/5642
Part of https://github.com/owncloud/ocis/issues/5337

[full-ci] [tests-only] Remove depthinfinity related steps from occ context master

---

README.md

Found while compiling ocis from scratch - with the help of @butonic - we need to add
a C compile environment like `build-essentials` as prerequisite to readme.md

[docs-only] Add build-essentials as prerequisite to README.md

---

.drone.star

Enable Github comment for e2e tracing results on tests failure

[ci] Enable Github comment for e2e tracing results on failure

---

.drone.star

Enable Github comment for e2e tracing results on tests failure

[ci][ci] Enable Github comment for e2e tracing results on failure (stable-2)

---

.drone.star
tests/config/drone/check_go_bin_cache.sh

Archive `/go/bin` and push the archive to the cache bucket. Then restore the archive, extract it to the `/go/bin` path in the linting pipelines.
This reduces the requests to get go bin caches to a single request.
Fixes https://github.com/owncloud/ocis/issues/5704
- Reduce the requests to the cache bucket server

[ci] Cache the go/bin content as a single archive file

---

services/graph/pkg/command/server.go
services/graph/pkg/config/config.go
services/graph/pkg/config/defaults/defaultconfig.go
services/graph/pkg/identity/ldap.go
services/graph/pkg/identity/ldap_test.go
services/graph/pkg/service/v0/service.go

This allows for a local admin to disable a user by adding to a local group
* A new config option for disabling users with the options "none", "attribute" and "group".
* Disable/enable group name DN as config parameter
* Adding/removing users to specified group on user update
* Changing log level for service initialization failure to error
- This adds the management of the local disabling of users for #5554 
This has been tested locally using curl and adding unit tests.

graph: Allow disabling user by adding to local group

---

changelog/unreleased/branding-api.md
services/web/pkg/service/v0/branding.go

- Make `common` logo key also replacable
- Make the logic theme name agnostic
- test case 1:
- test case 2:
- ...

add common part, make the logic theme name agnostic

---

tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/apiGraph/removeUserFromGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR separates the positive and negative test steps. 
- Fixes https://github.com/owncloud/ocis/issues/5646
The test step that used to be 
```feature
When the administrator tries to add user "Alice" to group "nonexistentgroup" using the Graph API
```
This is now defined as
```feature
When the administrator tries to add user "Alice" to a nonexistent group using the Graph API
```
This is because previously we followed the following logic to randomly generate the user-id of a non-existing user/group 
```php
try {
$groupId = $this->featureContext->getAttributeOfCreatedGroup($group, "id");
} catch (Exception $e) {
$groupId = WebDavHelper::generateUUIDv4();
}
try {
$userId = $this->featureContext->getAttributeOfCreatedUser($user, "id");
} catch (Exception $e) {
$userId = …
```

[tests-only][full-ci]Seperate test steps for positive and negative cases

---

tests/acceptance/features/apiGraph/assignRole.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR backport https://github.com/owncloud/ocis/pull/5584
- Locally

[tests-only][full-ci] Backport extend assign role test coverage

---

ocis/pkg/command/benchmark.go

benchmark clients now remember cookies the server sent (for oc10 basic auth), we added a `--rate {num}(/{unit})` option to limit the number of requests a client is allowed to make, and we fixed a bug caused by reusing the request.
These options allow setting up clients the continuously PUT a file e.g. once every second while another process starts 10 clients that continuuosly sends PROPFINDs. Also works against oc10.
Together this can be used to simulate various access patterns.

Benchmark options

---

.drone.env
services/web/Makefile

Bumps web to v7.0.0-rc.18.
This brings the new notifications implementation, so should unblock https://github.com/owncloud/ocis/pull/5699
cc @micbar @kobergj

[full-ci] chore: bump web to v7.0.0-rc.18

---

deployments/examples/ocis_keycloak/config/keycloak/ocis-realm.dist.json

This adds the roles ocisAdmin, ocisSpaceAdmin, ocisUser and ocisGuest as realm roles to the the oCIS realm. It also assigns those roles to the demo users.
Additionally the missing demo user "Katherine Johnson" is added with the role of "ocisSpaceAdmin".
The changes to actually evaluate the roles from ocis will follow in a later PR.

ocis_keycloak: Add ocis roles as realm roles

---

services/frontend/pkg/config/config.go

Referencing: #5749
Fixing descriptions in the frontend service.
* Make descriptions more clear what it is about.
* Add notes where `/` are required respectively must not be set.
* Align redis descriptions to what we have in other services.
Needs backport to `stable-2.0`
@C0rby fyi

[docs-only] Fix descriptions of envvars in the frontend service

---

services/graph/pkg/identity/ldap.go
services/graph/pkg/identity/ldap_education_school_test.go
services/graph/pkg/identity/ldap_education_user.go
services/graph/pkg/identity/ldap_education_user_test.go

This implements https://owncloud.dev/libre-graph-api/#/educationUser/UpdateEducationUser for the ldap education backend.
I am still wondering how this fell through the cracks :man_facepalming:

graph: Add missing patch support for education/users

---

tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/SpacesContext.php

With the current code if we send the following data
```feature
When user "Alice" changes the last share with settings:
| expireDate | 2044-01-01T23:59:59.999+01:00 |
| role | editor |
```
This won't work as expected because only the `expireDate` is sent as data. To fix that send the data as it comes to form the feature file as the format of data is the same as what we send in the request.

[full-ci][tests-only]Refactor test for updating the share

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/editUser.feature
tests/acceptance/features/bootstrap/GraphContext.php

created tests to editing user name: 
created bugs:
- #5755 
- #5763

[test-only] add api tests to editing user name

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR adds difference scenario related adding users in a group at once
- try to add users to the group that are already part of the group https://github.com/owncloud/ocis/issues/5702
- try to add a group to a group https://github.com/owncloud/ocis/issues/5793
- https://github.com/owncloud/ocis/issues/5569
- Locally

[full-ci][tests-only] Extend tests coverage to add users in a group 

---

.drone.star
go.mod
go.sum

- test case 1:
- test case 2:
- ...

[full-ci] messagepack metadata backend

---

changelog/unreleased/fix-duplicated-demouser-roles.md
services/settings/pkg/config/config.go
services/settings/pkg/store/defaults/defaults.go
services/settings/pkg/store/metadata/store.go

Avoid repeated default role assignments
When using the metadata storage (the current default) the default role
assignments were recreated at every start of the settings service. Leading to
duplicated role assignments
Fixes: #3432

Avoid repeated default role assignment

---

services/frontend/pkg/config/config.go

References: https://github.com/owncloud/ocis/pull/5812#pullrequestreview-1337191759 ([docs-only] Backport Frontend descriptions)
The backport got one word added which needs to be in master too.

[docs-only] Syncing one frontend envvar description from backport

---

services/graph/pkg/service/v0/educationuser.go
services/graph/pkg/service/v0/educationuser_test.go

This allows for creating an educationUser without an email.
- Fixes #5817 
Tested with curl and adding a unit test.

graph: Change so that educationUsers can be created without email.

---

.drone.star

After github plugin was updated in https://github.com/drone-plugins/drone-gh-pages/pull/34 the copy behaviour has changed. We now need to add a trailing slash to the path and set `copy_contents` to true

[docs-only] Fix Docs Creation

---

services/graph/pkg/config/config.go
services/graph/pkg/config/defaults/defaultconfig.go
services/graph/pkg/service/v0/educationuser.go
services/graph/pkg/service/v0/users.go

Introduces a switch ('GRAPH_ASSIGN_DEFAULT_USER_ROLE') to allow to disable the assignment of the default role "User" to newly created users. This will be used for setups where the role-assignments are populated either manually or during first login (e.g. from OIDC claims)

graph: Allow to disable the default role assignment on user creation

---

ocis-pkg/config/parser/parse.go
services/idm/pkg/command/server.go
services/idm/pkg/config/parser/parse.go
services/settings/pkg/config/parser/parse.go

For certain setups we don't need the ADMIN_USER_ID to be set. It is mainly needed for bootstrapping the internal idm and the initial role assignment.  If roles are assign by other means (e.g. OIDC claims) we don't need it.
This makes the ADMIN_USER_ID optional, also if ADMIN_USER_ID is unset we don't need to configure a password for the admin user. We will still generated the admin_id and password when running 'ocis init', but it is ok to run manual setups without those settings.

Allow ADMIN_USER_ID being empty

---

docs/services/eventhistory/_index.md
docs/services/eventhistory/configuration.md
docs/services/policies/_index.md
docs/services/port-ranges.md
docs/services/postprocessing/_index.md
docs/services/postprocessing/configuration.md
docs/services/userlog/_index.md
docs/services/userlog/configuration.md
docs/services/webfinger/_index.md
services/policies/README.md
services/webfinger/README.md

This PR adds missing services and fixes content in services for owncloud.dev
Added / changed:
* `eventhistory`
* `policies`
* `postprocessing`
* `userlog`
* `webfinger`
Content is now aligned to what we have in the admin docs - with some adaptions.

[docs-only] Adds missing services and fixes content for owncloud.dev

---

docs/services/port-ranges.md

This fixes the edit path for the `port-ranges.md` file. Missed to correct it.

[docs-only] Fix edit path for port-ranges.md

---

.drone.env
services/web/Makefile

Bump web to `v7.0.0-rc.21`.
This includes a bugfix regarding the password input prompt for enforced passwords on public links.

[full-ci] chore: bump web to v7.0.0-rc.21

---

changelog/unreleased/add-decomposedfs-metadata-command.md
go.mod
go.sum
ocis/pkg/command/decomposedfs.go

This PR adds a 'ocis decomposedfs metadata' command for inspecting and manipulating node metadata.
CLI:
```
ocis decomposedfs metadata
NAME:
ocis decomposedfs metadata - cli tools to inspect and manipulate node metadata
USAGE:
ocis decomposedfs metadata command [command options] [arguments...]
COMMANDS:
dump     print the metadata of the given node. String attributes will be enclosed in quotes. Binary attributes will be returned encoded as base64 with their value being prefixed with '0s'.
get      print a specific attribute of the given node. String attributes will be enclosed in quotes. Binary attributes will be returned encoded as base64 with their value being prefixed with '0s'.
set      manipulate metadata of the given node. Binary attributes can be given hex encoded (prefix by '0x') …
```

Add command for inspecting and manipulating node metadata

---

helpers/extended_vars.yaml

These entries are not present in the source `master/helpers/extended_envvars.yaml`. They seem to be a leftover from some tuning at the beginnig but create 2 entries in the admin docs that should not show up. Of course they could be marked as `do_ignore: true`, but deleting them will now make the file identical to that what we have in master and fixes things on a long term. Remember that this PR is in the docs branch and not in master.

Remove faulty enties in extended_vars.yaml

---

docs/helpers/extended_vars.yaml

There is an issue that is threefold:
1. When file extended_envvars.yml is not present, it is generated in master.
When it is present, nothing gets deleted, but added only - all fine.
2. When a source file gets changed and line numbers change, the converter identifies items as new because changed linenumbers - items will get added and need manual maintenance - all fine too. (rare cases, but happens, standard task)
3. What is missing, that the source file in master gets transported to the docs branch automatically and _overwrites_ the file. Currently the content is merged = things get added.
What happened now is, that we have a mismatch between what is in master vs what is in the docs branch causing items appear multiple times and making it extremely hard to check for validity. …

[docs-only] Fix extended_envvars.yaml has wrong referenced lineno in master

---

deployments/examples/ocis_keycloak/docker-compose.yml

Use the new PROXY_ROLE_ASSIGNMENT_DRIVER "oidc". This also means we can now run with OCIS_ADMIN_USER_ID being empty. So that no admin user will be created on startup and no default role assignment will happen.
By setting GRAPH_ASSIGN_DEFAULT_USER_ROLE to "false", we make sure to not create the default "user" role assignment when auto provisioning a user.

ocis_keycloak: Move to role assignment via oidc claim

---

services/graph/pkg/identity/ldap.go
services/graph/pkg/identity/ldap_education_school_test.go
services/graph/pkg/identity/ldap_education_user.go
services/graph/pkg/identity/ldap_education_user_test.go
services/graph/pkg/service/v0/educationuser_test.go

Fix so that the accountEnabled attribute will be updated on PATCH requests for educationUser.
- Fixes #5816 
Tested using curl and updated unit tests.

graph: Fix so that accountEnabled updates work for educationUser.

---

changelog/unreleased/use-accept-language-header.md
services/userlog/pkg/service/http.go

Use the widely accepted `Accept-Language` Header instead of the custom `Prefered-Language` one

Use Accept-Language Header

---

changelog/unreleased/add-parameters.md
services/userlog/pkg/service/conversion.go

`antivirus` and `policies` didn't have the messageRichParameters field but web relies on it.

Add Parameters for av and po events

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR adds the test for adding multiple users in a group using invalid host name in the host part of user-id
Related to issue: https://github.com/owncloud/ocis/issues/5569

[tests-only][full-ci] Test for adding multiple member to a group using invalid host in host part of user-id

---

tests/acceptance/features/apiSpaces/setQuota.feature

This PR adds API test to set quota by users with different roles
Related to issue: https://github.com/owncloud/ocis/issues/5565

[tests-only][full-ci] api test to set quota by users with different roles

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/setQuota.feature

This PR backport PR https://github.com/owncloud/ocis/pull/5854

[tests-only][full-ci] Backport test for set quota for differnt users

---

tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR adds tests coverage 
- Scenario Outline: try to a user-id with invalid characters to a group
- Scenario Outline: try to add user-ids with invalid characters to a group at once
- Scenario: add the same user to a group at once
- [Fixes <issue_link>](https://github.com/owncloud/ocis/issues/5569)
- Locally

[tests-only][full-ci]Expand tests coverage for adding multiple members to a group at single request

---

.drone.env
services/web/Makefile

bump web to v7.0.0-rc.26
includes a fix for password enforcement on single file public links with editor role.

[full-ci] chore: bump web to v7.0.0-rc.26

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php

This PR forward port tests related to adding multiple user at once in a group
- https://github.com/owncloud/ocis/pull/5864/
- test case 1:
- test case 2:
- ...

[tests-only] [full-ci] Forward port  5864 PR

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiSpaces/notification.feature
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/NotificationContext.php

[api-test] first notification test

---

.drone.env
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiAccountsHashDifficulty/assignRole.feature
tests/acceptance/features/apiArchiver/downloadById.feature
tests/acceptance/features/apiArchiver/downloadByPath.feature
tests/acceptance/features/apiCors/cors.feature
tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/apiGraph/createGroup.feature
tests/acceptance/features/apiGraph/createGroupCaseSensitive.feature
tests/acceptance/features/apiGraph/deleteGroup.feature
tests/acceptance/features/apiGraph/editGroup.feature
tests/acceptance/features/apiGraph/editUser.feature
tests/acceptance/features/apiGraph/getGroup.feature
tests/acceptance/features/apiGraph/removeUserFromGroup.feature
tests/acceptance/features/apiSpaces/createSpace.feature
tests/acceptance/features/apiSpacesShares/copySpaces.feature
tests/acceptance/features/apiSpacesShares/moveSpaces.feature
tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature

I've cleaned up a bit
- deleted closed issue from expected failures file 
- added issue tag to tests
I analyzed the number of failed tests:
| Passed |Failed |% of failed tests | 
|-------|-------|-------|
| 1549 | 277 | 17,9% |
If we talk about the new api, then
| Passed |Failed |% of failed tests | 
|-------|-------|-------|
| 860 | 122 | 14,2% |
if we fix #5125 #5938 #5939 we remove 56 failed tests from expected failures list

[test-only] add issue tag to failed tests

---

services/proxy/pkg/middleware/oidc_well-known.go

Avoids the panic. Doesn't fix underlying problems

[tests-only] Avoid panic when using WellknownRewrite

---

tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

The tests fail when ran with PHP 8.1 like described in the issue.
In PHP a non optional parameter cannot be after an optional one. PHP 7.4 and 8.0 seem not to care too much, but these functions break with PHP 8.1
With this PR the last parameter of the affected functions are made nullable and by that optional and checked later for correct content.
~~PLEASE NOTE: This PR breaks compatibility with PHP 7.4 because of `PyStringNode|string $schemaString = "`, if we want to keep compatibility with PHP7.4 I can change that~~
- Fixes #5914
- :robot:

[tests-only] fix not optional parameter after optional

---

.drone.env
services/web/Makefile

bump web to v7.0.0-rc.27
This includes fixes to the token renewal behaviour in web.

[full-ci] chore: bump web to v7.0.0-rc.27

---

changelog/unreleased/www-authenticate-header.md
services/proxy/pkg/middleware/authentication.go

Bugfix: Fix authenticate headers for API requests
We changed the www-authenticate header which should not be sent for "basic-auth" when the `XMLHttpRequest` header is set.
Fixes #5986 
- test case 1:
- test case 2:
- ...

do not send www-authenticate basic for Api requests

---

services/graph/pkg/service/v0/approleassignments.go
services/graph/pkg/service/v0/drives.go
services/graph/pkg/service/v0/educationclasses.go
services/graph/pkg/service/v0/educationschools.go
services/graph/pkg/service/v0/educationuser.go
services/graph/pkg/service/v0/groups.go
services/graph/pkg/service/v0/password.go
services/graph/pkg/service/v0/tags.go
services/graph/pkg/service/v0/users.go
services/graph/pkg/service/v0/utils.go
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md

Adding strict json decoding so that receiving unknown parameters (or with typos) will return an error.
- Fixes #5888 
Tested with curl and current unit tests.

graph: Add strict json decoding to return errors when receiving unknown parameters

---

services/eventhistory/README.md
services/eventhistory/pkg/config/config.go
services/idp/pkg/config/config.go
services/userlog/README.md
services/userlog/pkg/config/config.go

Fixes: #5999 (eventhistory and userlog service caching envvar naming mismatch)
Harmonize the name of envvars to be inline with similar ones.
`EVENTHISTORY_STORE_ADDRESSES` --> `EVENTHISTORY_STORE_NODES`
`USERLOG_STORE_ADDRESSES` --> `USERLOG_STORE_NODES`
(we use the term nodes with other services, so: addresses --> nodes)
Consider that we do not have caching here!
Aligned with the new name, the readme.md files were updated too.

[docs-only] Rename / Deprecate userlog and eventhistory envvars

---

services/gateway/README.md
services/graph/README.md
services/ocs/README.md

References: #6000 
This PR just fixes the service names used in the text in readme.md files. Copy/Paste error 🤦‍♂️

[docs-only] Fixing the service name in the text used in readme.md

---

changelog/unreleased/bump-go-ldap-version.md
go.mod
go.sum
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md

Updates go-ldap package to its current master.
Fixes https://github.com/owncloud/ocis/issues/5966

Bump go-ldap version

---

changelog/unreleased/enhancement-ldap-group-create-basedn.md
go.mod
go.sum
services/graph/pkg/config/config.go
services/graph/pkg/config/defaults/defaultconfig.go
services/graph/pkg/config/parser/parse.go
services/graph/pkg/identity/ldap.go
services/graph/pkg/identity/ldap_group.go
services/graph/pkg/identity/ldap_group_test.go
services/graph/pkg/service/v0/errorcode/errorcode.go
services/graph/pkg/service/v0/groups.go

By setting GRAPH_LDAP_GROUP_CREATE_BASE_DN a distinct subtree can be configure
where new LDAP groups are created. That subtree needs to be subordinate to
GRAPH_LDAP_GROUP_BASE_DN. All groups outside for
GRAPH_LDAP_GROUP_CREATE_BASE_DN are considered read-only and only group below
that DN can be updated and deleted.
This is introduced for a pretty specific usecase where most groups are managed
in an external source (e.g. a read-only replica of an LDAP tree). But we still
want to allow the local administrator to create groups in a writeable subtree
attached to that replica.
To test this you can start ocis with
```
IDM_CREATE_DEMO_USERS=true GRAPH_LDAP_GROUP_CREATE_BASE_DN=ou=users,o=libregraph-idm GRAPH_LDAP_GROUP_BASE_DN=o=libregraph-idm ocis/bin/ocis server
```
This will make all the demo …

graph: user groupTypes property to indicate read-only groups

---

deployments/examples/ocis_keycloak/config/keycloak/ocis-realm.dist.json

This fixes the DCR issue where clients got a 500 error from oCIS because they did not send the roles in the access token.
- test case 1:
- test case 2:
- ...

[deployment] add roles to scope

---

.drone.env
services/web/Makefile

chore: bump web to v7.0.0-rc.29

---

docs/services/new-service-checklist.md

When referencing images or code, you must to use raw access. Adding a bad and good example to make it clear.
No impact on readme.md but mandatory for owncloud.dev

[docs-only] Update new-service-checklist.md

---

services/graph/README.md

An image source referenced must be the raw source to be shown properly in owncloud.dev.
No impact on showing the readme here.

[docs-only] Update Graph README.md to properly show the image in owcloud.dev

---

services/idp/pkg/config/config.go

Fixes: #5906
After clarification and renaming the envvar via #6008 and post a discussion with @rhafer, we should align the yaml name to the envvar name. Note that the backend name (`Insecure`) is not changed.
* In the deployment examples, we use ennvars and no yaml - no issue
* ocis init does not use it - no issue
The only issue that could raise is, if one used the old yaml name. This is possible but quite unlikely.

Update IDM config.go

---

services/idm/pkg/config/config.go

While working on admin docs, I identified  two IDM envvars that can safely be removed:
* `ACCOUNTS_DEMO_USERS_AND_GROUPS`
This envvar was stated in https://github.com/owncloud/ocis/pull/3474 to be removed after switching to LibreIDM. I have checked the whole ocis repo for occurences of this envvar and it is only present in the IDM service as leftover.
* `OCIS_ACCOUNTS_DEMO_USERS_AND_GROUPS`
This one was "accidentially" added but there is no global use of one of the underlaying envvar.
@micbar adding you as you have written the referenced PR.

Remove dead and unused IDM envvar

---

services/audit/README.md

References: https://github.com/owncloud/docs-ocis/pull/452
`autit` --> `audit`

[docs-only] Fix typo in audit service readme

---

.drone.star

Use a proxy to avoid 403 responses when trying to load go modules.

use a proxy for the golangci-lint step

---

changelog/unreleased/gdpr-export.md
ocis-pkg/keycloak/client.go
ocis-pkg/keycloak/gocloak.go
ocis-pkg/keycloak/types.go

- manually on schule.owncloud.works
```json
{
"events":[ ],
"keycloak":{
"UserData":{
"accountEnabled":true,
"givenName":"Michael",
"id":"",
"identities":[
{
"issuer":"https://keycloak.schule.owncloud.works",
"issuerAssignedId":"7e0c2ecb-7235-4a5b-b012-be3037c12d95"
}
],
"mail":"mbarz@owncloud.com",
"surname":"Barzow"
},
"Sessions":[
{
"clients":{
"7357f443-2206-46de-8b67-cffbe2c9da67":"web-0002",
"dba27084-63ad-4718-8195-a2abd9cebe2e":"xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69",
"e030bbba-1fb2-4e1e-bebf-21170ebc826b":"web-0001"
},
"id":"4c1d1b5b-dc51-41d2-8d4a-ead321ead63e",
"ipAddress":"109.250.73.209",
"lastAccess":1681734426000,
"start":1681734401000,
"userId":"7e0c2ecb-7235-4a5b-b012-be3037c12d95",
"username":"mbarz"
}
]
},
"user":{
"id":{ …
```

add sessions to report, remove credentials

---

docs/templates/ADOC.tmpl

Fixing a typo
Backporting to `docs-stable-2.0` neccessary.

[docs-only] Fixing ADOC.tmpl typo

---

tests/acceptance/features/apiContract/sharesReport.feature
tests/acceptance/features/apiContract/spacesSharesReport.feature

Add API test scenarios to search when user tries to search the shared folder which is not accepted yet.
https://github.com/owncloud/ocis/issues/4489#issuecomment-1505094923

[tests-only][full-ci]Added test to search when share is no accepted yet

---

changelog/unreleased/runtime.md
ocis-pkg/config/config.go
ocis-pkg/config/envdecode/envdecode.go
ocis-pkg/config/envdecode/envdecode_test.go
ocis/pkg/runtime/service/service.go

Enhancement: Add optional services to the runtime
Make it possible to start optional services in the ocis runtime. Instead of using `OCIS_RUN_SERVICES` to define all services we can now use `OCIS_ADD_RUN_SERVICES` to add a comma separated list of additional services which are not started in the single process by default.
Our envdecoder was parsing string slices differently than documented. It was using `;` as a separator.
@wkloucek @mmattel FYI
Make the usage of the single process runtime easier
- manualle

[full-ci] add optional services and fix config slice parser

---

changelog/unreleased/role-assignment-from-oidc.md
services/proxy/README.md
services/proxy/pkg/command/server.go
services/proxy/pkg/config/config.go
services/proxy/pkg/config/defaults/defaultconfig.go
services/proxy/pkg/userroles/oidcroles.go
services/proxy/pkg/userroles/userroles.go

If multiple claims values have a valid matching for ocis roles, we'll pick the ocis role that appears first in the mapping configuration.

proxy: Rework oidc role mapper to allow multiple matching roles

---

deployments/examples/service_policies/policies/postprocessing.rego
deployments/examples/service_policies/policies/proxy.rego
deployments/examples/service_policies/policies/utils.rego
go.mod
go.sum
services/proxy/pkg/middleware/policies.go

when uploading files via uppy (tus), the path does not give any information about the file, PUT contains the filename in the path, tus POST not.
this pr extracts the HeaderUploadMetadata from that POST request and enhances the policies grpc environment request with that information. 
Therefore, the policies service is now able to evaluate proxy requests for tus uploads too.

fix: proxy policies middleware tus filename evaluation

---

docs/ocis/development/deprecating-variables.md

The removal version can only be, according to semver, a major version.
Note that I will update the removal version in existing deprications in an own PR.

[docs-only] update the deprecation description (removal version rule)

---

services/eventhistory/pkg/service/service.go
services/userlog/pkg/service/service.go

Using `Metadata` is not supported by some stores. This would lead to a panic as it would convert incorrectly.
We now save the event type as part of the event body
NOTE: Might lead to lost events after update as data structure changed

[tests-only] Avoid Metadata Functionality in Eventhistory

---

ocis-pkg/config/config.go

Fixes: #6084 (OCIS_ADD_RUN_SERVICES description is not clear)
`OCIS_EXCLUDE_RUN_SERVICES` and `OCIS_ADD_RUN_SERVICES` description improved.
Note that I will add a text description how to get the default list in the admin docs as footnote to the table.

[docs-only] Improve special envvar description

---

changelog/unreleased/fix-search-reindexing-performance-regression.md
go.sum
services/search/pkg/content/basic.go

We've fixed a regression in the search service reindexing step, causing the whole space to be reindexed instead of just the changed resources.
Stats from testing (this was with a really small space, the effects for larger spaces will be more dramatic):
```
Upload file into the space root with 24 files and 2 subdirs (warm cache):
Before:                                             After:
+-----------+------------------+-------+            +-----------+------------------+-------+
| Function  | last 5 second(s) | total |            | Function  | last 5 second(s) | total |
+-----------+------------------+-------+            +-----------+------------------+-------+
| Chtimes   |                1 |    11 |            | Chtimes   |                1 |    14 |
| Create    |                0 | …
```

Fix Search reindexing performance regression

---

services/notifications/README.md
services/notifications/pkg/email/templates.go

References: #6025 (Make Emails translatable via transifex)
This PR updates the:
* README.md to clarify how things get assembled
* comment strings so one can see with which placeholders a string is resolved

[docs-only] Fix notification readme and translation comments

---

tests/acceptance/features/coreApiWebdavMove1/moveFolder.feature
tests/acceptance/features/coreApiWebdavProperties1/copyFile.feature

This PR adds tag `skipOnReva` to the 2 scenarios. Those 2 scenarios were explicitly skipped with this tag in drone `issue-ocis-3023`. This is the issue https://github.com/owncloud/ocis/issues/3023 that occurs only in `reva-master`. But is fixed in `reva-edge` -> https://github.com/owncloud/ocis/issues/3023#issuecomment-1175180108.
since the refactor PR https://github.com/cs3org/reva/pull/3776#issuecomment-1515818527 the issue tag, the scenarios were running which hung the drone.
Fixes https://github.com/cs3org/reva/pull/3776 this bump

[tests-only][full-ci]Add skip on reva instead

---

services/graph/pkg/service/v0/graph.go
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md

Overwriting URL.RawPath with EscapedPath to avoid problems with unescaping values.
Fixes #5083

Try to fix problems with unescaping values.

---

services/notifications/README.md
services/userlog/README.md

Post a discussion with regards to translations, we need to clarify which language-code types are supported by ocis and which one by onwcloud web.
This PR makes this hopefully clear.
When merged, will be transported to the admin docs.
@micbar @kulmann @2403905 fyi

[docs-only] Note that we only support language but not language_territory (web frontend)

---

ocis-pkg/oidc/client.go
services/graph/pkg/identity/ldap_education_school.go
services/proxy/pkg/command/server.go
services/proxy/pkg/middleware/oidc_auth.go

Use access token to lookup session id. The userinfo endpoint does not return the session id. Also add some debug logging.

Fix backchannel logout

---

changelog/unreleased/add-webfinger.md
ocis-pkg/middleware/oidc.go
ocis-pkg/middleware/options.go
services/webfinger/pkg/config/config.go
services/webfinger/pkg/config/defaults/defaultconfig.go
services/webfinger/pkg/server/http/server.go

This PR fixes a nill pointer exception in webfinger
refs #6102

Fix nil pointer exception in webfinger

---

changelog/unreleased/bad-request-on-gdpr-endpoint.md
services/graph/pkg/service/v0/personaldata.go

This is an enhancement NOT a security fix. The request userID is never used.
Fixes https://github.com/owncloud/ocis/issues/6114

`BadRequest` when exporting GDPR for other user

---

.drone.env
.drone.star

This PR bumps the commit id of web to pull the changes made by  https://github.com/owncloud/web/pull/8905 in ocis.
This will unblock the CI

[tests-only][full-ci]Bump web commit id

---

docs/services/general-info/envvar-scopes.md

References: #6142 (adoc table generator should separate envvars by semicolon AND comma)
Note to use semicolon as correct envvar separator because of the automated documentation process.

[docs-only] Update envvar-scopes.md (owncloud.dev)

---

.drone.env
.drone.star

after https://github.com/owncloud/ocis/pull/6135 we disabled e2e tests
example: https://drone.owncloud.com/owncloud/ocis/21802/68/10
fixed in the web repo https://github.com/owncloud/ocis/pull/6135
cc @SwikritiT looks like old style : `cucumber --tags ~@skip` doesn't work

enable e2e tests in ocis CI again

---

changelog/unreleased/nats-debug.md
services/nats/pkg/command/server.go
services/nats/pkg/config/config.go
services/nats/pkg/config/defaults/defaultconfig.go

This PR opens the debug server for the nats services
refs #5002 
refs #5712

open debug endpoint for nats

---

ocis-pkg/oidc/client.go
ocis-pkg/oidc/client_test.go
ocis-pkg/oidc/options.go
services/proxy/pkg/command/server.go
services/proxy/pkg/config/config.go
services/proxy/pkg/config/defaults/defaultconfig.go

The "aud" claim of the logout token is supposed to contain the client-id of the client for which the token was issued. Our current implementation of validating that claim is somewhat broken. We only allow to configure a single value for the allowed client id. But we have different client-ids accessing oCIS.
This completely removes the current validation of the `aud` claim until we come up with a working solution. As we currently require a session id to be present in the logout token the risk not validating the `aud` claim is pretty low.
Related: #6149

oidc: Remove "aud" claim validation of logout tokens

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiGraph/userGDPRExport.feature
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/WebDav.php

This PR adds the scenario for a user to generate a GDPR report for event as uploading a single file.
For now this PR adds just a single scenario.
```feature
Scenario: generate a GDPR report and check user data in the downloaded report
Scenario: generate a GDPR report and check when a user is created
````

[tests-only]Added GDPR export. check events when user is created

---

changelog/unreleased/disable-notifications.md
services/notifications/pkg/service/service.go
services/settings/pkg/store/defaults/defaults.go

Adds new setting to disable email  notifications

Disable Email Notifications

---

services/idp/README.md

References: #6163 (Transifex localisation of the IDP service is not existent)
Translations provided by the IDP service are not maintained via ownCloud but part of the embedded vendor package: LibreGraph Connect Identifier.

[docs-only] Update IDP README.md

---

changelog/unreleased/add-debug-to-audit.md
services/audit/pkg/command/server.go
services/audit/pkg/config/config.go
services/audit/pkg/config/defaults/defaultconfig.go

This PR adds the debug server to the audit service.
refs #5002 
refs #5712

add debug to audit

---

services/storage-system/pkg/config/config.go
services/storage-users/pkg/config/config.go

References: #6166 (Default value of STORAGE_SYSTEM_OCIS_METADATA_BACKEND)
The `ini` backend for metadata as formerly mentioned in the descriptions is now `messagepack`.
This PR _does not_ change the default value `xattrs`.

[docs-only] Fix that envvars use messagepack instead of ini as supported values.

---

go.mod
go.sum
services/graph/pkg/service/v0/drives.go
services/graph/pkg/service/v0/graph_test.go
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/decomposedfs.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/grants.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/node/node.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/options/options.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/spacepermissions.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/spaces.go
vendor/modules.txt

when a user lists all spaces he has access to (unrestricted==false) we should send a user filter, so decomposedfs has a chance to use an index instead of iterating over ALL spaces.
part of todays tracing session, the reva part is in https://github.com/cs3org/reva/pull/3809
~~blocked by https://github.com/cs3org/reva/pull/3826~~
blocked by https://github.com/cs3org/reva/pull/3827

listing drives sould use the user filter

---

services/graph/pkg/service/v0/drives.go

this saves a getQuota trip to the storage when the quota information is already present in the space opaque properties
makes use of https://github.com/cs3org/reva/pull/3828 but can be merged without it

Read quota from opaque

---

.drone.env
services/web/Makefile

[full-ci] chore: bump web to v7.0.0-rc.35

---

changelog/unreleased/update-web-7.0.0-rc.35.md

Add changelog item for ownCloud Web `v7.0.0-rc.35`.
Assets were already bumped in https://github.com/owncloud/ocis/pull/6190

docs: add changelog for web updpate v7.0.0-rc.35

---

changelog/unreleased/web-config.md
services/web/pkg/config/config.go
services/web/pkg/config/defaults/defaultconfig.go
services/web/pkg/config/options.go

Fixes https://github.com/owncloud/ocis/issues/4921

Hardcoded web options

---

changelog/unreleased/add-debug-to-userlog.md
docs/services/general-info/port-ranges.md
services/userlog/pkg/command/server.go
services/userlog/pkg/config/config.go
services/userlog/pkg/config/defaults/defaultconfig.go

This PR adds a debug server to the userlog serice.
refs #5712 
refs #5002 
refs https://github.com/owncloud/ocis-charts/issues/111

add debug to userlog

---

changelog/unreleased/add-eventhistory-debug.md
docs/services/general-info/port-ranges.md
services/eventhistory/pkg/command/server.go
services/eventhistory/pkg/config/config.go
services/eventhistory/pkg/config/defaults/defaultconfig.go

this PR adds a debug server to the eventhistory
refs #5002 
refs #5712 
refs https://github.com/owncloud/ocis-charts/issues/111

add debug to eventhistory

---

services/proxy/README.md
services/proxy/pkg/config/http.go

This PR clarifies that the setting `PROXY_TLS` needs to be set to true when using the embedded IDP service. Also adds a note in the proxy readme.
The envvar description should be backported to `docs-stable-2.0`

[docs-only] Update the PROXY_TLS envvar description

---

services/web/README.md

References: #6188 (Hardcoded web options)
Just a small addon to the readme to describe that we have options to configure the webui.

[docs-only] Add a readme descriton to webui option envvars

---

docs/ocis/identity-provider/_index.md
docs/ocis/identity-provider/ldap-active-directory.md

Referencing: [graph: Allow using binary LDAP UUIDs as user ids](https://github.com/owncloud/ocis/pull/6182#top)
Adding the config example in the referenced PR into a new section in owncloud.dev.
As discussed with @micbar @rhafer 
Intended as starting point for more content.

[docs-only] Adding a Identity Provider section in owncloud.dev

---

services/graph/pkg/identity/ldap.go
services/graph/pkg/identity/ldap_education_class.go
services/graph/pkg/identity/ldap_group.go

As the standard LDAP groups (groupOfNames) require at least one "member" value to be present in a group, we have workarounds in place that add an empty member ("") when creating a new group or when removing the last member from the group. This can cause a race condition when e.g. multiple request to remove members from a group an running in parallel, as we need to read the group before we can construct the modification request. If some other request modified the group (e.g. deleted the 2nd last member) after we read it, we create non-working modification request.
These changes try to catch those errors and retry the modification request once.
Fixes: #6170

graph-ldap: Fix possible races when editing group membership in parallel

---

services/graph/pkg/config/defaults/defaultconfig.go
services/graph/pkg/service/v0/driveitems.go
services/graph/pkg/service/v0/drives.go
services/graph/pkg/service/v0/graph.go
services/graph/pkg/service/v0/graph_test.go
services/graph/pkg/service/v0/service.go

When listing drives we now cach special drive items until the space root changes again or the TTL is reached.
brings back the cache that was dropped in https://github.com/owncloud/ocis/pull/3141

cache special drive items until space root changes

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/coreApiCapabilities/capabilities.feature
tests/acceptance/features/coreApiCapabilities/capabilitiesWithNormalUser.feature
tests/acceptance/features/coreApiFavorites/favorites.feature
tests/acceptance/features/coreApiFavorites/favoritesSharingToShares.feature
tests/acceptance/features/coreApiMain/checksums.feature
tests/acceptance/features/coreApiMain/main.feature
tests/acceptance/features/coreApiMain/status.feature
tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareResourceCaseSensitiveName.feature
tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareUniqueReceivedNames.feature
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareGroupAndUserWithSameName.feature
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithInvalidPermissions.feature
tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
tests/acceptance/features/coreApiSharees/sharees.feature

This PR
- adds the description about the feature file
-  updates the line changes in expected to fail file
-  start the scenario title with small letter and without article
-  remove the duplication of scenario title within a feature file
- Part of: https://github.com/owncloud/QA/issues/804
This is to maintain uniformity within the scenarios in a feature file
- CI

[tests-only]Refactor feature files to add correct description

---

services/storage-system/README.md
services/storage-users/README.md

References: #6213 [docs-only] Set messagepack as default metadata backend 
Per suggestion of @aduffeck, we should add a note that `xattrs` should not be used anymore.

[docs-only] Add readme.md note to not use xattrs anymore

---

tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/apiSpaces/disableAndDeleteSpaces.feature
tests/acceptance/features/apiSpaces/listSpaces.feature
tests/acceptance/features/apiSpaces/quota.feature
tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
tests/acceptance/features/apiSpaces/setQuota.feature
tests/acceptance/features/apiSpaces/spaceManagement.feature
tests/acceptance/features/apiSpaces/uploadSpaces.feature
tests/acceptance/features/apiSpacesShares/shareSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

This PR 
- separate steps regarding successful JSON response and failure JSON response and remove 
`And for user "Alice" the JSON response should contain space called "Project Jupiter" and match`
steps from negative testing scenario
- `And for user "Alice" the JSON response should contain space called "Project Jupiter" and match` has been removed from the scenario where **When** scenario returns JSON response replaced with steps like
```
And the JSON data of the response should match
And the JSON response should contain space called "Project Jupiter" owned by "Alice" with description file ".space/readme.md" and match
```
which assert the expected Json with above step response
-  https://github.com/owncloud/ocis/issues/5792
- Locally.

[tests-only] [full-ci] Refactor scenario related to checking json response

---

changelog/unreleased/fix-web-config.md
services/web/pkg/config/options.go

Bugfix: Fix Logout Url config name
We fixed the yaml and json name of the logout url option.
- Fixes https://github.com/owncloud/enterprise/issues/5716
- test case 1:
- test case 2:
- ...

Fix config name for the web logout url

---

tests/acceptance/features/coreApiWebdavMove2/moveFile.feature
tests/acceptance/features/coreApiWebdavProperties2/getFileProperties.feature
tests/acceptance/features/coreApiWebdavUpload1/uploadFile.feature

We have a app to automatically update the line numbers of a feature file in the expected to failure
https://github.com/JankariTech/expected-failures-updater
But currently, it doesn't work because we have the following error
```bash
-> Found Scenarios with same title on same file
Scenario 1: coreApiWebdavMove2/moveFile.feature:421
Scenario 2: coreApiWebdavMove2/moveFile.feature:422
-> Found Scenarios with same title on same file
Scenario 1: coreApiWebdavProperties2/getFileProperties.feature:127
Scenario 2: coreApiWebdavProperties2/getFileProperties.feature:150
-> Found Scenarios with same title on same file
Scenario 1: coreApiWebdavUpload1/uploadFile.feature:33
Scenario 2: coreApiWebdavUpload1/uploadFile.feature:54
-> Found Scenarios with same title on same file
Scenario 1: …
```

[tests-only][full-ci] Remove duplication of steps and scenario name within a feature file

---

services/storage-users/pkg/config/config.go

Found by chance,
for proper docs generation, envvars need to be separated by semicolons and not comma:
`STORAGE_USERS_PERMISSION_ENDPOINT,STORAGE_USERS_OCIS_PERMISSIONS_ENDPOINT` -->
`STORAGE_USERS_PERMISSION_ENDPOINT;STORAGE_USERS_OCIS_PERMISSIONS_ENDPOIN`

[docs-only] An envvar in the storage-users service needs separation by semicolon

---

services/storage-users/pkg/config/config.go

References: https://github.com/owncloud/ocis-charts/pull/241 (Add a warning to the documentation for upload cleanup job to prevent cancelling unfinished uploads)
Reflecting the warning in the helm chart in the corresponding service envvar.

[docs-only] Add note that uploads could be canceled when setting is too low

---

.drone.env
changelog/unreleased/update-web-7.0.0-rc.36.md
services/web/Makefile

Bump web to `v7.0.0-rc.36`. This includes the reverted access denied redirect on 401 for notifications.

[full-ci] chore: bump web to v7.0.0-rc.36

---

services/web/README.md
services/web/pkg/config/config.go

Fixes: #6226 (Fix WEB_UI_CONFIG und WEB_UI_PATH envvars)
* The `WEB_UI_CONFIG` and `WEB_UI_PATH` envvars need deprecations and decription rewrites to make the use clear.
* Update the `web` readme

[docs-only] Deprecate some web envvars

---

.gitignore
changelog/unreleased/fix-leaks-existence.md
go.mod
go.sum
services/graph/pkg/service/v0/drives.go
tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/apiSpaces/disableAndDeleteSpaces.feature
tests/acceptance/features/apiSpaces/spaceManagement.feature
vendor/github.com/cs3org/reva/v2/internal/grpc/services/storageprovider/storageprovider.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/node/permissions.go
vendor/modules.txt

- Fixes [<issue_link>](https://github.com/owncloud/ocis/issues/5031)
- test environment: local. admin created the space 1f6ff55a-e87a-4430-a902-9dc07a3b63a7. einstein try to delete/update the space
- test case 1:  DELETE
```bash
$ curl -k -s -u einstein:relativity -X DELETE 'https://localhost:9200/graph/v1.0/drives/storage-users-1$1f6ff55a-e87a-4430-a902-9dc07a3b63a7' | jq .
{
"error": {
"code": "itemNotFound",
"innererror": {
"date": "2023-05-03T14:48:39Z",
"request-id": "Julias-MacBook-Pro.local/QMepEAscMQ-000072"
},
"message": "drive not found"
}
}
$ curl -k -s -u einstein:relativity -X DELETE 'https://localhost:9200/graph/v1.0/drives/storage-users-1$1f6ff55a-e87a-4430-a902-9dc07a3b63a1' | jq .
{
"error": {
"code": "generalException",
"innererror": {
"date": "2023-05-03T14:48:52Z", …
```

fix Graph delete request leaks existence of space #5031

---

services/graph/pkg/identity/ldap.go
services/graph/pkg/identity/ldap_group.go
services/graph/pkg/identity/ldap_group_test.go
services/graph/pkg/identity/ldap_test.go

This allows a couple of update request to complete even if `GRAPH_LDAP_SERVER_WRITE_ENABLED=false`:
* When using a group to disable users (`OCIS_LDAP_DISABLE_USER_MECHANISM=group`) updates to the `accountEnabled` property of a user will be allowed
* When a distinct base dn for new groups is configured ( `GRAPH_LDAP_GROUP_CREATE_BASE_DN` is set to a different value than `GRAPH_LDAP_GROUP_BASE_DN`), allow the creation/update of local groups.

Allow selected updates even when GRAPH_LDAP_SERVER_WRITE_ENABLED=false

---

changelog/unreleased/add-debug-result-for-av.md
services/antivirus/pkg/config/config.go
services/antivirus/pkg/scanners/scanners.go
services/antivirus/pkg/service/service.go

This PR adds the ability to enforce a specific scan result for antivirus for debugging.

add debug switch for antivirus

---

tests/acceptance/features/apiGraph/userGDPRExport.feature
tests/acceptance/features/bootstrap/GraphContext.php

Adds more scenarios on GDPR related export.
```feature
Scenario: generate a GDPR report and check when admin updates the quota of personal space
Scenario Outline: user tries to generate GDPR report of other users
```

[tests-only][full-ci]Added GDPR export for quota update, export another users GDPR

---

tests/acceptance/features/bootstrap/ArchiverContext.php
tests/parallelDeployAcceptance/features/bootstrap/ParallelContext.php
vendor-bin/behat/composer.json
vendor-bin/owncloud-codestyle/composer.json
vendor-bin/php_codesniffer/composer.json

I just made a new release 4.1.0 of owncloud coding-standard https://github.com/owncloud/coding-standard/releases/tag/4.1.0
That uses a newer version of php-cs-fixer, which passes locally for me.
This PR updates the version numbers of dependencies in `vendor-bin` to the current minor versions that are in use. That can be helpful when there are problems with some new release of a dependency - at least we have "documented" which minor version is currently working correctly.
CI
Similar core PR is https://github.com/owncloud/core/pull/40780

[tests-only] [full-ci] Update vendor-bin dependencies

---

changelog/unreleased/fix-omitempty-givenName.md
services/graph/pkg/identity/ldap.go
services/graph/pkg/identity/ldap_test.go

- Fixes [<issue_link>](https://github.com/owncloud/ocis/issues/5431)
- test environment: local, curl
- test case 1: 
```bash 
curl -k -X 'POST' -u admin:admin  'https://localhost:9200/graph/v1.0/users' --data '{ "onPremisesSamAccountName": "test1", "displayName":"test1", "mail":"test1@test.test"}' | jq .
{
"displayName": "test1",
"id": "681dca41-b674-49f6-84c2-5ebf48b92851",
"mail": "test1@test.test",
"onPremisesSamAccountName": "test1",
"surname": "test1",
"userType": "Member"
}
```

Omitempty givenName attribute when create user #5431

---

services/proxy/README.md

Referencing: https://github.com/owncloud/docs-ocis/pull/494 (Update proxy.adoc)
The proxy readme contained a typo in the yaml example.

[docs-only] Fix typo in proxy readme yaml example

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/createUser.feature

Some test scenario examples in coreApiTrashbin/trashbinFilesFolders.feature used usernames that are just numbers: 123, -123, 0.0
Those examples were failing because a username like that cannot be created. So as part of PR #6270 those examples are being removed.
This PR adds some examples to `createUser.feature` for:
- username with letters and numbers (works)
- username with letters and dots (works)
- username is only digits (cannot be created)
- username is 0.0 (looks like a float) (cannot be created)
This will help "document" which usernames can and cannot be created in a default installation.
See doc issue https://github.com/owncloud/docs-ocis/issues/495 - it seems that this is configurable with `GRAPH_USERNAME_MATCH=none` so the default behavior here is expected.
CI

[tests-only] [full-ci] Add examples of more username combinations

---

.drone.star
go.mod
go.sum
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
vendor/github.com/cs3org/reva/v2/internal/grpc/services/gateway/ocmshareprovider.go
vendor/github.com/cs3org/reva/v2/internal/grpc/services/gateway/usershareprovider.go
vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/shares.go
vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/spaces.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/upload/upload.go
vendor/modules.txt

Fix tests to match the changed behavior in reva regarding sharing of space roots.
/cc @micbar

[full-ci] Fix test expectations

---

changelog/unreleased/policies-response-body.md
services/proxy/pkg/middleware/policies.go

Adds the missing response body to blocked requests.
```json
{
"error":{
"code":"deniedByPolicy",
"message":"Operation denied due to security policies",
"innererror":{
"date":"2023-05-10T19:52:19Z",
"filename":"policies.yaml",
"method":"POST",
"path":"/remote.php/dav/spaces/storage-users-1$some-admin-user-id-0000-000000000000",
"request-id":"5e55a8ad-cd5f-40c9-a002-db9e30f24585"
}
}
}
```
```json
{
"error":{
"code":"deniedByPolicy",
"message":"Operation denied due to security policies",
"innererror":{
"date":"2023-05-10T20:05:00Z",
"filename":"Neue Datei.md",
"method":"PUT",
"path":"/remote.php/dav/spaces/storage-users-1$some-admin-user-id-0000-000000000000/Neue Datei.md",
"request-id":"9302a92e-c7eb-4c41-9a98-62eb37cf5db4"
}
}
}
```
- test case 1: …

add missing response body to blocked requests

---

services/storage-users/pkg/config/defaults/defaultconfig.go

References: #6213 ([docs-only] Set messagepack as default metadata backend)
The `storage-users` service has two locations for defining the default metadata backend. One was missed to fix in the referenced PR.
Many thanks @d7oc for catching this.

[docs-only] Fix missed default metadata backend

---

go.mod
go.sum
services/settings/pkg/command/server.go
services/settings/pkg/config/config.go
services/settings/pkg/config/defaults/defaultconfig.go
services/settings/pkg/server/grpc/option.go
services/settings/pkg/server/grpc/server.go
services/settings/pkg/server/http/option.go
services/settings/pkg/server/http/server.go
services/settings/pkg/store/metadata/cache.go
services/settings/pkg/store/metadata/store.go
vendor/github.com/go-micro/plugins/v4/store/redis/redis.go
vendor/modules.txt

This moves the settings cache to use a go-micro/store based caching implementation, similar to what we're using in many other services meanwhile.
This also switches to a different fork of go-micro/v4/store/redis as we need this fix: https://github.com/go-micro/plugins/pull/110 for making the cacheinvalidation (https://github.com/owncloud/ocis/pull/6264/files#diff-9426c2b35f285118038505973e5852f93b8a31c9240420ebfd2057d3a3aaa9d9R162) work.

settings: Move cache implementation go-micro/store

---

vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/spaces.go
vendor/github.com/cs3org/reva/v2/pkg/storage/cache/cache.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/node/node.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/node/xattrs.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/tree/tree.go
vendor/modules.txt

Reva updated in https://github.com/owncloud/ocis/commit/62878b6428e22c93e4982f2c3aa7bb3e019876ef but not the vendor files.
Cannot generate/build ocis
```
...
go: inconsistent vendoring in /mnt/workspace/owncloud/ocis:
github.com/cs3org/reva/v2@v2.13.3-0.20230515075524-e00c55c0a4d3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
github.com/cs3org/reva/v2@v2.13.3-0.20230510083816-98d8707dea33: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
To ignore the vendor directory, use -mod=readonly or -mod=mod.
To sync the vendor directory, run:
go mod vendor
make: *** [../.make/go.mk:102: bin/ocis] Error 1
make: Leaving directory '/mnt/workspace/owncloud/ocis/ocis'
```
Failing CI …

[full-ci] update reva vendor files

---

changelog/unreleased/update-roles.md
services/settings/pkg/store/defaults/defaults.go
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md

Bugfix: Update the default admin role
The admin role was missing two permissions. We added them to make the space admin role a subset of the admin role. This matches better with the default user expectations.
https://github.com/owncloud/ocis/pull/6310
- Prerequisite for https://github.com/owncloud/ocis/issues/5872
- test case 1:
- test case 2:
- ...

update the default roles

---

services/eventhistory/README.md
services/frontend/README.md
services/gateway/README.md
services/postprocessing/README.md
services/userlog/README.md

References: https://github.com/owncloud/docs-ocis/pull/500 (Fix cache envvar names)
Some envvar names were not correct when it comes to caching in the servcies readme.

[docs-only] Use correct envvar caching names in service readme's

---

changelog/unreleased/remove-quota-from-api-for-shares.md
services/graph/pkg/service/v0/drives.go

We have removed the quota object from api responses for share jails, 
which would permanently show exceeded due to restrictions in the permission system.
refs #4472

remove quote from api response in share jails

---

services/search/pkg/search/events.go

Trigger a space reindex when the space has been renamed.
Fixes #6289 (in combination with https://github.com/cs3org/reva/pull/3889)

Trigger a space reindex when the space has been renamed

---

changelog/unreleased/fix-graph-ttl-cache.md
services/graph/pkg/config/defaults/defaultconfig.go
services/graph/pkg/service/v0/service.go

The old default ttl of 30 minutes for the caches seems way too long. It could cause outdated information users or groups to be returned for quite a while. Especially since the TTL was reset every time an entry was fetched from the cache. This is disabled now as well.
Fixes: #6320

graph: Adjust defaults for user, group and SpaceProperties caches

---

changelog/unreleased/bump-reva.md
go.mod
go.sum
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
vendor/github.com/cs3org/reva/v2/internal/grpc/interceptors/auth/scope.go
vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/shares.go
vendor/modules.txt

Changelog for reva 2.13.3 (2023-05-17)
=======================================
*   Bugfix [cs3org/reva#3890](https://github.com/cs3org/reva/pull/3890): Bring back public link sharing of project space roots
*   Bugfix [cs3org/reva#3888](https://github.com/cs3org/reva/pull/3888): We fixed a bug that unnecessarily fetched all members of a group
*   Bugfix [cs3org/reva#3886](https://github.com/cs3org/reva/pull/3886): Decomposedfs no longer deadlocks when cache is disabled
*   Bugfix [cs3org/reva#3892](https://github.com/cs3org/reva/pull/3892): Fix public links
*   Bugfix [cs3org/reva#3876](https://github.com/cs3org/reva/pull/3876): Remove go-micro/store/redis specific workaround
*   Bugfix [cs3org/reva#3889](https://github.com/cs3org/reva/pull/3889): Update space root mtime when changing …

[full-ci] update reva to 2.13.3

---

docs/ocis/development/testing.md
tests/acceptance/docker/Makefile
tests/acceptance/docker/src/acceptance.yml
tests/acceptance/docker/src/email.yml
tests/acceptance/docker/src/ocis-base.yml

We can run tests locally using the docker-compose setup. But the tests that require email service fail because the email service is not set up.
This PR adds the email service in the setup and allows the user to start the service using `START_EMAIL=true` envvar while running the tests.
Also, the doc has been updated.
- :gear: Setup :heavy_check_mark: 
- :scroll: Documentation :heavy_check_mark: 
Fixes https://github.com/owncloud/ocis/issues/6314
able to run email tagged tests locally using docker-compose setup
locally

[docs-only] Add email service to the docker-compose setup for tests

---

services/search/pkg/engine/bleve.go

This commit removes the full-text and tag data from the composite field ("_all") which can be used for default term queries which we don't do anyways.
As a result the search index shrinks considerably in size,  my test index went from 13MB down to 7,6MB, for example.
/cc @fschade

Do not include full-text and tag data in the composite field

---

changelog/unreleased/default-ldap-write-enabled.md
services/frontend/pkg/config/defaults/defaultconfig.go

Default `{OCIS|FRONTEND|GRAPH}_LDAP_SERVER_WRITE_ENABLED` to true

Default `LDAP_WRITE_ENABLED` to true

---

services/storage-users/README.md

References: #6354 (Configurable IDCache)
This PR adds the new `STORAGE_USERS_ID_CACHE_STORE` envvar to the caching description.

[docs-only] Add new caching envvar to storage-users service

---

tests/acceptance/features/apiGraph/userGDPRExport.feature

This PR adds a `GDPR API test for : 
```feature
Scenario: generate a GDPR report and check events when user creates a folder
Scenario: generate a GDPR report and check events when user share a file
Scenario: generate a GDPR report and check events when user creates a link for a resource
Scenario: generate a GDPR report and check events when user deletes a resource
```

[tests-only][full-ci]Added GDPR export for folder creation, sharing a file

---

services/search/pkg/engine/bleve.go
services/search/pkg/engine/bleve_test.go
services/search/pkg/search/service.go

This PR fixes a problem when searching for the `:` character. It also makes field based search case-insensitive to make it consistent with simple searches.

Improve complex search

---

services/idp/pnpm-lock.yaml

Updated pnpm-lock file to comply with pnpm v8
- Fixes https://github.com/owncloud/ocis/issues/6384
[Migration instruction](https://github.com/pnpm/pnpm/releases/tag/v8.0.0)
> Before updating pnpm to v8 in your CI, regenerate your pnpm-lock.yaml. To upgrade your lockfile, run pnpm install and commit the changes. Existing dependencies will not be updated; however, due to configuration changes in pnpm v8, some missing peer dependencies may be added to the lockfile and some packages may get deduplicated.
>
> You can commit the new lockfile even before upgrading Node.js in the CI, as pnpm v7 already supports the new lockfile format.

[full-ci] Migrate pnpm-lock file version from 5.4 to 6

---

services/search/pkg/engine/bleve.go

This PR fixes a problem where timestamp search terms weren't being found because they were lowercased.

Do not mess with non-lowercased fields

---

.drone.star

bring https://github.com/owncloud/web/pull/9063 to ocis CI

[test-only] using api token in e2e instead of basic auth

---

.drone.env
.drone.star
services/web/Makefile

Bumps web and reenables e2e tests

[tests-only][full-ci] Bump Web to 7.0.0-rc39

---

tests/acceptance/filesForUpload/'single'quotes.txt
tests/acceptance/filesForUpload/new-'single'quotes.txt

Using ocis as dependency (e.g. for ocis-hello) is not possible when the repo contains files with `'` in the filename. See https://github.com/owncloud/ocis-hello/pull/140#discussion_r1212534079
This PR deletes those problematic files (they are used in any tests)
- :robot:

delete problematic files for go get

---

changelog/unreleased/fix-email-xsite-scripting.md
deployments/examples/ocis_wopi/docker-compose.yml
go.sum
services/notifications/pkg/email/composer.go
services/notifications/pkg/email/email.go
services/notifications/pkg/email/templates/html/email.html.tmpl
services/notifications/pkg/service/service.go
services/notifications/pkg/service/service_test.go
services/notifications/pkg/service/shares.go
services/notifications/pkg/service/spaces.go

To prevent the email notification X-Site scripting the untrusted data are escaped in a email HTML body.
- Fixes [https://github.com/owncloud/ocis/issues/6411](https://github.com/owncloud/ocis/issues/6411)
- test environment: local, unit test

Fix to prevent the email notification X-Site scripting

---

tests/acceptance/features/bootstrap/TrashbinContext.php

This was fixed in core https://github.com/owncloud/core/pull/40816/files#diff-0c858bb3764da8bd386a1833efc1ed57756c4e3e6ae854820435659e95fddf1d
Fix it here in ocis.
A request to list the contents of the trashbin could return the `original-location` of a resource with or without a `/` on the front. In oC10 core, for example, a file that was deleted from a share seems to return `original-location` like `/sharedFolder/file.txt`, but a file in the trashbin that was just a local file of the user has something like `myFolder/myFile.txt` - when we want to delete a specific file from the trashbin, we should match either in the list-trashbin response. Otherwise the test might tell us that the file does not exist in the trashbin, when actually it does exist.
CI

[tests-only] [full-ci] Adjust test method tryToDeleteFileFromTrashbin

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpacesShares/copySpaces.feature
tests/acceptance/features/apiSpacesShares/moveSpaces.feature

I deleted closed issue from expected failures and fixed test
- moving test: behavior here https://github.com/owncloud/ocis/issues/4797#issuecomment-1576550992
- copying test. еhe receiver could not see the version of the file. We disabled version for receivers

[test-only] fixing tests of copying and moving files with the same name. removing from expected

---

changelog/unreleased/update-go-micro-kubernetes-registry-to-a179a6b8.md
go.mod
go.sum
vendor/github.com/go-micro/plugins/v4/registry/kubernetes/client/watch/body.go
vendor/github.com/go-micro/plugins/v4/registry/kubernetes/watcher.go
vendor/modules.txt

Update go-micro kubernetes registry to v1.1.2-0.20230605104008-a179a6b8f8e6
https://github.com/owncloud/ocis/pull/6457
https://github.com/go-micro/plugins/pull/114
https://github.com/go-micro/plugins/pull/113

Enhancement: Update go-micro kubernetes registry

---

services/graph/pkg/config/application.go

Just a small envvar text fix: `id` --> `ID`

[docs-only] GRAPH_APPLICATION_ID envvar text fix

---

changelog/unreleased/enhancement-add-companion-url-config.md
services/web/pkg/config/defaults/defaultconfig.go
services/web/pkg/config/options.go

The config can be set via env var `WEB_OPTION_UPLOAD_COMPANION_URL`. This is needed for https://github.com/owncloud/web/pull/9150.

feat: add uppy companion url config

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/createUser.feature

I reopened https://github.com/owncloud/ocis/issues/3516
- changed createUser tests and delete tests from expected failures
- `federated sharee` is not implement in OCIS (will be near in the feature) so I linked tests with existing issue https://github.com/owncloud/ocis/issues/1329
@2403905 we should have failed tests with a link to the issue in the expected failures file, and the issue should not be closed. (if the issue is closed -> that means no tests in the list)

[test-only] Fix code expectation

---

docs/ocis/deployment/ocis_s3.md

The path in the docs is incorrect `deployment/` is no longer inside `ocis/` so this PR fixes the path in docs

[docs-only]fix path in documentation

---

changelog/unreleased/enhancement-add-imprint-privacy-url-config.md
services/web/pkg/config/options.go

Introduce a config to set the imprint and privacy URL via `WEB_OPTION_IMPRINT_URL` `WEB_OPTION_PRIVACY_URL`.
- https://github.com/owncloud/web/issues/9174

feat: add imprint and privacy url config

---

.drone.env
changelog/unreleased/update-web-7.0.1.md
services/web/Makefile

Bumps web to v7.0.1 to bring in a performance improvement for initial space preloading

[full-ci] chore: bump web to v7.0.1

---

tests/acceptance/features/apiSpaces/tag.feature
tests/acceptance/features/bootstrap/SpacesContext.php

Add API test scenarios for using a comma-separated list of tag names.
This demonstrates the current API behavior, which has been agreed in the issue. The tags can be set by passing a comma-separated list, and are reported as a comma-separated list.
#6425 
CI

[tests-only] [full-ci] Test comma-separated list of tags

---

deployments/examples/ocis_wopi/docker-compose.yml
ocis-pkg/version/version.go
sonar-project.properties

> **Warning**
> BREAKING CHANGE in the Deployment
> The app provider config needs to be changed to keep working [example](https://github.com/owncloud/ocis/pull/6483/commits/a86aba1c4144d54d80fd956ddcb9139518cbfc04)
>
* Enhancement - Make the app provider service name configurable: [#6482](https://github.com/owncloud/ocis/pull/6482)
* Enhancement - Use reva client selectors: [#6452](https://github.com/owncloud/ocis/pull/6452)
* Enhancement - Add companion URL config: [#6453](https://github.com/owncloud/ocis/pull/6453)
* Enhancement - Add imprint and privacy url config: [#6462](https://github.com/owncloud/ocis/pull/6462)
* Enhancement - Fix the username validation: [#6437](https://github.com/owncloud/ocis/pull/6437)
* Enhancement - Update go-micro kubernetes registry: …

[full-ci] Release 3.1.0-next.1

---

docs/templates/ADOC_global.tmpl

This is just a small adoc global template fix and adds a necessary explanation text.
This text will be removed when we will refactor the code behind which will bring many improvements.
This text is already added manually in the `docs-stable-3.0` branch in the global-envvars adoc file.

[docs-only] Fix adoc global template

---

docs/ocis/development/testing.md
tests/acceptance/docker/Makefile
tests/acceptance/docker/src/antivirus.yml
tests/acceptance/docker/src/ocis-base.yml

This PR changes the compose file to add the flexibility to run tests using `antivirus` service.
Also changes some wording in the docs.
Part of: https://github.com/owncloud/ocis/issues/6255

[tests-only]Add configuration for antivirus in docker compose for tests

---

.drone.env

bumping web commit id to bring in the adjusted tests, fixing https://github.com/owncloud/ocis/issues/6431

[full-ci] ci: bump web commit id for updated tests (to stable-3.0)

---

changelog/unreleased/retry-postprocessing.md
go.mod
go.sum
services/antivirus/pkg/service/service.go
services/postprocessing/README.md
services/postprocessing/pkg/command/postprocessing.go
services/postprocessing/pkg/command/root.go
services/postprocessing/pkg/command/server.go
services/postprocessing/pkg/postprocessing/postprocessing.go
services/postprocessing/pkg/service/service.go
vendor/github.com/cs3org/reva/v2/pkg/events/postprocessing.go
vendor/modules.txt

Adds a ctl command to retry failed postprocessing by upload id
Fixes https://github.com/owncloud/ocis/issues/6495

[full-ci] Retry Postprocessing

---

ocis/pkg/command/decomposedfs.go

Don't strip off the first two characters of the target value to set unconditionally. Also print an error if decoding hex/base64 values fails (falling back to treating the values as strings).

Fix 'decomposedfs meta set' value handling

---

changelog/unreleased/add-remote-item-metadata.md
services/graph/pkg/service/v0/driveitems.go
services/graph/pkg/service/v0/graph_test.go

This adds the needed metadata to the remote item which represents the real location of a share in the storage space of the share owner.
This is needed to access shares via the `storage-users` provider to have the same URL for all participants of a share.
- Needs https://github.com/cs3org/reva/pull/3836
- Needed for https://github.com/owncloud/ocis/issues/6120
Access shares via the original Url of the owner
Admin shares `Test/Test2/Test3` with Einstein
```json
{
"driveAlias":"mountpoint/test3",
"driveType":"mountpoint",
"id":"a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668!storage-users-1:some-admin-user-id-0000-000000000000:405575a4-6543-47f5-badf-df0012074105",
"name":"test3",
"owner":{
"user":{
"displayName":"",
"id":"some-admin-user-id-0000-000000000000"
}
}, …
```

add remote item metadata

---

tests/acceptance/features/apiSpaces/quota.feature
tests/acceptance/features/bootstrap/SpacesContext.php

This PR adds the scenario for creation for the space when `OCIS_SPACES_MAX_QUOTA` is set and when space is created with default quota than the `OCIS_SPACES_MAX_QUOTA`.
https://github.com/owncloud/ocis/issues/6231

[tests-only][full-ci]Added scenarios for quota exceed with API

---

tests/TestHelpers/OcisConfigHelper.php

This PR adds test code to throw better error messages when ocis-wrapper is not reachable during the test run.
Now the error will be thrown like this
- Fixes https://github.com/owncloud/ocis/issues/6315
- Locally

[tests-only][full-ci]Throw proper ocis-wrapper connection error message

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/coreApiSharees/sharees.feature

This PR removes the test scenarios related to `federated shares`.
-  Scenario Outline: federated sharee for files
- Scenario Outline: federated sharee for calendars not allowed
- https://github.com/owncloud/ocis/issues/5337

[tests-only] [full-ci] removed scenario related to federated share

---

services/notifications/pkg/command/server.go
services/notifications/pkg/config/config.go

The nullpointer was cause by not properly initializing the GRPC client, this just adds the initialization.
- Fixes #6541
Tested in my local k3s cluster.

Fix nullpointer problems

---

changelog/unreleased/audit-events.md
go.mod
go.sum
services/graph/pkg/service/v0/approleassignments.go
services/graph/pkg/service/v0/approleassignments_test.go
services/graph/pkg/service/v0/educationuser.go
services/graph/pkg/service/v0/users.go
services/graph/pkg/service/v0/users_test.go
vendor/github.com/cs3org/reva/v2/pkg/events/users.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/decomposedfs.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/grants.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/metadata.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/node/node.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/node/permissions.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/recycle.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/revisions.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/spacepermissions.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/spaces.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/upload/processing.go
vendor/modules.txt

We have added old & new values to the audit logs
We have added the missing events for role changes
refs #3753

Show changes between old an new values in audit log

---

changelog/unreleased/wopi-disable-chat.md
go.mod
go.sum
services/app-provider/pkg/config/config.go
services/app-provider/pkg/revaconfig/config.go
vendor/github.com/cs3org/reva/v2/pkg/app/provider/wopi/wopi.go
vendor/github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/providercache/providercache.go
vendor/github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/receivedsharecache/receivedsharecache.go
vendor/github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/sharecache/sharecache.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/node/node.go
vendor/modules.txt

Adds the envvar to disable wopi chat. 
Needs https://github.com/cs3org/reva/pull/3986
Fixes https://github.com/owncloud/ocis/issues/6540
*   Bugfix [cs3org/reva#3978](https://github.com/cs3org/reva/pull/3978): Decomposedfs no longer os.Stats when reading node metadata
*   Bugfix [cs3org/reva#3948](https://github.com/cs3org/reva/pull/3948): Handle the bad request status
*   Bugfix [cs3org/reva#3977](https://github.com/cs3org/reva/pull/3977): Prevent direct access to trash items
*   Bugfix [cs3org/reva#3975](https://github.com/cs3org/reva/pull/3975): Decomposedfs now resolves the parent without an os.Stat
*   Change [cs3org/reva#3947](https://github.com/cs3org/reva/pull/3947): Bump golangci-lint to 1.51.2
*   Change [cs3org/reva#3945](https://github.com/cs3org/reva/pull/3945): Revert …

[full-ci] DisableWopiChat envvar

---

tests/acceptance/features/apiAntivirus/antivirus.feature
tests/acceptance/features/bootstrap/NotificationContext.php

This PR back ports https://github.com/owncloud/ocis/pull/6523.
Part of <https://github.com/owncloud/ocis/issues/6255>

[tests-only] [full-ci]Added antivirus notification tests for different languages (#6523)

---

changelog/unreleased/enhancement-add-logged-out-url-config
services/web/pkg/config/options.go

Introduce a config to set the more button url on the access denied page in web via `WEB_OPTION_ACCESS_DENIED_HELP_URL`.

feat: add logged out url config

---

services/search/pkg/engine/bleve.go

This PR fixes a problem were `Name` and `Tags` field queries were case-sensitive in some cases.

Always make Name and Tags queries case-insensitive

---

changelog/unreleased/add-token-to-linkAccessed-event.md
go.mod
go.sum
services/audit/pkg/service/service_test.go
services/audit/pkg/types/conversion.go
services/audit/pkg/types/messages.go
vendor/github.com/cs3org/reva/v2/internal/grpc/interceptors/eventsmiddleware/conversion.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/decomposedfs.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/lookup/lookup.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/mtimesyncedcache/map.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/mtimesyncedcache/mtimesyncedcache.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/recycle.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/spaces.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/tree/tree.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/upload/processing.go
vendor/modules.txt

We added the link token to the LinkAccessedEvent
refs #3753

add token to LinkAccessedEvent

---

services/app-provider/pkg/config/config.go

References: #4682
This PR does the following:
* Move the item below the `_DEBUG_ZPAGES` entry so it appears in docs in alignment as all other have this (on top we always have logging, debugging, tracing...)
* Fix the description

Update APP_PROVIDER_SERVICE_NAME description

---

changelog/unreleased/dont-connect-ldap-on-startup.md
services/graph/pkg/identity/ldap/reconnect.go

~Reducing log level of the ldap connect error messages to debug. Corresponding reva code already logs on debug. See here: https://github.com/cs3org/reva/blob/edge/pkg/utils/ldap/reconnect.go#L206~
We removed the call to connect to ldap instead. It will connect on the first request now. This should remove the misleading error messages on startup
Fixes https://github.com/owncloud/ocis/issues/4520

Don't connect to ldap on startup

---

docs/ocis/development/testing.md

We have an antivirus api test. To run this test suit locally, we need to run the antivirus process as described here https://github.com/owncloud/ocis/blob/master/docs/ocis/development/testing.md#running-test-suite-with-antivirus-service-antivirus.
I've added the ability to run antivirus (locally and via docker) for Mac OS users

Change testing docs. Antivirus for mac 

---

.drone.star
tests/acceptance/docker/src/antivirus.yml
tests/acceptance/docker/src/ocis-base.yml

This PR refactors the CI and docker-compose to use TCP to communicate with antivirus. Previously we used volumes to share sockets but that's not needed any more

[tests-only][full-ci] use tcp for antivirus service in ci 

---

tests/acceptance/docker/src/antivirus.yml

Use `mkodockx/docker-clamav` image  https://hub.docker.com/r/mkodockx/docker-clamav in docker-compose file instead of `owncloudci/clamavd:latest` https://hub.docker.com/r/owncloudci/clamavd/tags
The owncloud image is built only for `amd` which might not be suitable for developers with `arm`. This PR changes the image so that it can provide support for all the OS

[tests-only] Use different image of clamav in docker compose

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature

This PR adds API test for setting the config `OCIS_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD` to true and update the public share to edit permission.
- Related to issue: https://github.com/owncloud/ocis/issues/6231

[tests-only] [full-ci] API test for enforce password config and update the public share to edit permission

---

changelog/unreleased/add-default-store-to-postprocessing.md
services/postprocessing/pkg/config/defaults/defaultconfig.go

Adds a default store to postprocessing service. Especially `database` and `table` are needed.
A migration is imo not necessary as it only stores data during uploads (which might be breaking during update anyways)
Fixes https://github.com/owncloud/ocis/issues/6547
Fixes https://github.com/owncloud/ocis/issues/6514

Add default store to postprocessing service

---

tests/acceptance/docker/src/antivirus.yml

Backport: https://github.com/owncloud/ocis/pull/6588
Use `mkodockx/docker-clamav` image  https://hub.docker.com/r/mkodockx/docker-clamav in docker-compose file instead of `owncloudci/clamavd:latest` https://hub.docker.com/r/owncloudci/clamavd/tags
The owncloud image is built only for `amd` which might not be suitable for developers with `arm`. This PR changes the image so that it can provide support for all the OS 
Part of: https://github.com/owncloud/ocis/issues/6255

[tests-only]Backport/use different clamav image docker compose

---

services/search/pkg/command/server.go
services/search/pkg/config/config.go
services/search/pkg/config/defaults/defaultconfig.go
services/search/pkg/config/reva.go
services/search/pkg/search/service.go
services/search/pkg/search/service_test.go
services/search/pkg/server/grpc/option.go
services/search/pkg/server/grpc/server.go
services/search/pkg/service/grpc/v0/option.go
services/search/pkg/service/grpc/v0/service.go

When executing a search we were listing ALL spaces of an instance without a filter on spaces the currently logged in user has access to. That might run into the 10sec timeout for search requests when a lot of spaces are in the system.

unmarshal token to filter spaces for current user

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature

This PR backports PR https://github.com/owncloud/ocis/pull/6409

[tests-only][full-ci] Backport enforce password test scenarios

---

services/idm/README.md

Fix idm default port typo in README

[docs-only] Fix idm default port typo in README

---

changelog/unreleased/fix-oidc-role-assigner.md
services/proxy/pkg/userroles/oidcroles.go

Fixes https://github.com/owncloud/enterprise/issues/5805

Fix OIDC role assigner

---

changelog/unreleased/bump-reva.md
go.mod
go.sum
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
vendor/github.com/cs3org/reva/v2/internal/http/services/archiver/handler.go
vendor/github.com/cs3org/reva/v2/internal/http/services/archiver/manager/archiver.go
vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/shares.go
vendor/modules.txt

Bumps reva
Fixes https://github.com/owncloud/ocis/issues/5139
Fixes https://github.com/owncloud/ocis/issues/6555

[full-ci] Bump Reva

---

changelog/unreleased/add-decomposedfs-check-treesize-command.md
ocis/pkg/command/decomposedfs.go

This adds a cli command to verify  the treesize metadata of a Space in decomposedfs
```
ocis decomposedfs check-treesize -r /root/.ocis/storage/users/ -n cc1a4ba9-75d5-43e7-853c-548e1726ef60
Checking treesizes in space: Admin (id: cc1a4ba9-75d5-43e7-853c-548e1726ef60)
treesizes mismatch for node: /test2/folder/folder/folder/folder/folder
NodeId: 2f8d8188-8c66-4c4d-a29b-cee85e3097c3
InternalPath: /root/.ocis/storage/users/spaces/cc/1a4ba9-75d5-43e7-853c-548e1726ef60/nodes/2f/8d/81/88/-8c66-4c4d-a29b-cee85e3097c3
calculated treesize: 1998
treesize in metadata: 1996
treesizes mismatch for node: /test2/folder/folder/folder/folder
NodeId: 73ccc33f-0a8b-4513-9e2c-161a9e551279
InternalPath: /root/.ocis/storage/users/spaces/cc/1a4ba9-75d5-43e7-853c-548e1726ef60/nodes/73/cc/c3/3f/-0a8b-4513-9e2c-16 …
```

Decomposedfs treesizecheck

---

changelog/unreleased/add-web-oidc-post-logout-redirect-uri.md
services/web/pkg/config/config.go

Enhancement: Make the post logout redirect uri configurable
We added a config option to change the redirect uri after the logout action of the web client.
https://github.com/owncloud/ocis/issues/6536
- test case 1:
- test case 2:
- ...

add web post redirect uri config

---

tests/acceptance/features/apiContract/spacesReport.feature

This PR adds contract tests for report request in project spaces. We had tests for REPORT in spaces
- https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiSpaces/search.feature
We also have contract tests for REPORT requests in project spaces for shared resources
- https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiContract/spacesSharesReport.feature
However, the contract tests for the resources of project space (not received through shares) weren't covered yet. So this PR adds some test coverage.
- Covers: https://github.com/owncloud/ocis/issues/6525

[tests-only][full-ci]Add tests for checking response of REPORT request in project spaces

---

tests/acceptance/features/apiAntivirus/antivirus.feature

This PR adds the API test scenarios for overwrite file with virus content in user share:
- Scenario for trying to overwrite a file with the virus content in user share
- Scenario for trying to overwrite a file with the virus content in user share using spaces dav endpoint
- Part of: https://github.com/owncloud/ocis/issues/6255
- There was no test coverage for overwrite file with virus content in user share. So, this PR coves the required scenario test case.
- locally
- CI

[tests-only] added scenarios for overwrite file with virus content in user share

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/SpacesContext.php

related https://github.com/owncloud/ocis/issues/6606
after fixing https://github.com/owncloud/ocis/commit/b108482649498acefe0b2b7379a403df09816406 I changed tests

[full-ci][tests-only] Check id file owner in response

---

tests/acceptance/features/apiSpacesShares/changingFilesShare.feature

This PR adds different roles for sharee and then checks for the file versioning.
- Part of <https://github.com/owncloud/ocis/issues/6606#event-9646533873>
- locally
- ci

[tests-only] [full-ci] added different roles for sharee

---

ocis/pkg/command/decomposedfs.go

Add linebreak after errormessages

Fix output formatting of 'decomposedfs treesize-check` command

---

tests/acceptance/features/bootstrap/ArchiverContext.php
tests/acceptance/features/bootstrap/FilesVersionsContext.php
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/Provisioning.php
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/WebDav.php
tests/acceptance/features/bootstrap/WebDavPropertiesContext.php

This PR implements the DRY principle on the existing code.
- https://github.com/owncloud/ocis/issues/6130

[tests-only][full-ci] implement DRY principle

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiGraph/fullSearch.feature

- search file using tag
- there was no test coverage for api test for search file using tag. so, this PR covers the require scenario test case
- locally
- CI

[tests-only][full-ci]Add api test for search file through tag

---

tests/acceptance/features/apiGraph/assignRole.feature
tests/acceptance/features/apiGraph/changeRole.feature
tests/acceptance/features/apiGraph/createUser.feature
tests/acceptance/features/bootstrap/GraphContext.php

related: #6606 
https://doc.owncloud.com/ocis/next/deployment/services/s-list/graph.html
tests for Env

[test-only] expand createUser.feature

---

tests/TestHelpers/HttpRequestHelper.php
tests/TestHelpers/SharingHelper.php
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/WebDav.php
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
tests/acceptance/features/coreApiVersions/fileVersions.feature

This PR refactors the step definition code relating to unshare scenerio.
- Part of  <https://github.com/owncloud/ocis/issues/6325#issuecomment-1590750636>
- locally
- ci

[tests-only] [full-ci] Refactoring unshare step definition code

---

tests/acceptance/features/apiGraph/fullSearch.feature

- search file using tag by sharee
- there was no test coverage for api test for search file using tag by sharee. so, this PR covers the require scenario test case
- locally
- CI

[tests-only] [full-ci] Added API test to search shared files by sharee using tag

---

tests/TestHelpers/SharingHelper.php
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/WebDav.php
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
tests/acceptance/features/coreApiVersions/fileVersions.feature

This PR back ports https://github.com/owncloud/ocis/pull/6608
Part of  <https://github.com/owncloud/ocis/issues/6325#issuecomment-1590750636>

[tests-only] [full-ci] Refactoring unshare step definition code (#6608)

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/apiGraph/editUser.feature
tests/acceptance/features/apiGraph/getUser.feature
tests/acceptance/features/apiSpaces/quota.feature
tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
tests/acceptance/features/coreApiAuthWebDav/webDavCOPYAuth.feature
tests/acceptance/features/coreApiCapabilities/capabilities.feature
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
tests/acceptance/features/coreApiShareReshareToShares1/reShare.feature
tests/acceptance/features/coreApiShareReshareToShares2/reShareSubfolder.feature
tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
tests/acceptance/features/coreApiSharees/sharees.feature
tests/acceptance/features/coreApiTrashbin/trashbinDelete.feature
tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
tests/acceptance/features/coreApiVersions/fileVersions.feature
tests/acceptance/features/coreApiWebdavLocks2/independentLocks.feature
tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
tests/acceptance/features/coreApiWebdavOperations/propfind.feature

This PR refactors the scenario example tables in feature files.
- https://github.com/owncloud/ocis/issues/5337

[tests-only][full-ci] refactor scenario example table

---

tests/acceptance/features/apiSpaces/quota.feature
tests/acceptance/features/apiSpaces/trashBin.feature
tests/acceptance/features/bootstrap/SpacesContext.php

after https://github.com/owncloud/ocis/pull/6625 I added tests where:

[test-only][full-ci]ApiTests. purge trash bin tests

---

changelog/unreleased/fix-searching-shares.md
services/search/pkg/search/service.go

This fixes searching received shares that were not shared from the space root.

Use the owner auth to get the path of shared resources

---

services/userlog/README.md
services/userlog/pkg/command/server.go
services/userlog/pkg/server/http/option.go
services/userlog/pkg/server/http/server.go
services/userlog/pkg/service/conversion.go
services/userlog/pkg/service/globalevents.go
services/userlog/pkg/service/http.go
services/userlog/pkg/service/options.go
services/userlog/pkg/service/service.go
services/userlog/pkg/service/templates.go

Adds global notifications to userlog service
To store a deprovision notification `POST` on `/global` endpoint:
```bash
curl --insecure -X POST -v -u admin:admin -d '{"type":"deprovision", "data":{"deprovision_date": "2023-07-04T12:23:12Z"}}' https://localhost:9200/ocs/v2.php/apps/notifications/api/v1/notifications/global
```
You can define the format of the date with the `deprovision_date_format` parameter
```bash
curl --insecure -X POST -v -u admin:admin -d '{"type":"deprovision", "data":{"deprovision_date": "2023-07-04 15:17", "deprovision_date_format":"2006-01-02 15:04"}}' https://localhost:9200/ocs/v2.php/apps/notifications/api/v1/notifications/global 
```
See [go time formating](https://pkg.go.dev/time#pkg-constants) for format details
To delete a deprovision notification `DELETE` on …

Deprovisioning Notification

---

README.md
changelog/unreleased/clarify_license.md
docs/ocis/license.md

Clarification of the license of Infinite Scale, especially the stable binary builds under EULA

[docs-only] Clarify the license of ownCloud Infinite Scale binary packages.

---

.drone.star

Sometimes the wopiValidation pipeline can fail due to the race condition between `fakeoffice` and `ocis-server` steps. This was due to running both steps parallelly. This PR adds the wait for fakeoffice service so that there won't be a race condition between fakeoffice and ocis-server steps.
fixes https://github.com/owncloud/ocis/issues/6750

[tests-only][full-ci][ci] Wait for fakeoffice to be ready

---

tests/acceptance/features/apiGraph/fullSearch.feature

- search folder using tag
- there was no test coverage for api test for search folder using tag. so, this PR covers the require scenario test case
- locally
- CI

[tests-only][full-ci]add scenario for search folder tag

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/coreApiWebdavPreviews/previews.feature
tests/acceptance/features/coreApiWebdavPreviews/previewsAutoAdustedSizing.feature

This PR adds tests for previewing shared animated gif by sharee
- Fixes https://github.com/owncloud/ocis/issues/5418
- Locally

[tests-only][full-ci]Add test for preview of shared animated GIFs

---

tests/ociswrapper/cmd/cmd.go
tests/ociswrapper/ocis/config/config.go
tests/ociswrapper/ocis/ocis.go

While restarting ocis server with ociswrapper during the tests, sometimes the ocis server is not started properly. In order to heal the restarting of ocis server, this PR has implemented starting ocis server with a certain number of retries (current default is `5`). The retries can be configured at the time of running ociswrapper command with `--retry` option.
```bash
ociswrapper serve --bin=/bin/ocis --retry=2
```
Fixes https://github.com/owncloud/ocis/issues/6751

[tests-only][full-ci] Retry ocis startup with ociswrapper

---

tests/acceptance/features/apiGraph/fullSearch.feature
tests/acceptance/features/bootstrap/TagContext.php

- search file using deleted tag
- there was no test coverage for api test for search file using deleted tag. so, this PR covers the require scenario test case
- locally
- CI

[tests-only][full-ci]Test api search by deleted tag

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md

This PR update the issue link for the issue that was still in open. The issue tag wasn't updated in the expected failures file in the main branch. 
https://github.com/owncloud/QA/issues/816

[tests-only][full-ci]Updated expected to failure for closed issue to new issue

---

tests/ociswrapper/log/log.go
tests/ociswrapper/ocis/ocis.go
tests/ociswrapper/wrapper/wrapper.go

Separate ocis server logs and ociswrapper logs. wrapper logs have `[ociswrapper]` scope prepended.
```bash
2023/07/12 09:54:54 [ociswrapper] some log message here
```

[tests-only][full-ci](ociswrapper): separate ociswrapper logs from ocis logs

---

tests/acceptance/features/bootstrap/TrashbinContext.php

This PR  addresses this issue: https://github.com/owncloud/ocis/issues/6628
Findings:
- Passes locally (reproducing locally is not possible)
- status code is checked after when step but following steps also calls api for listing trashbin where status is not checked
So asserting is added to check the status code after listing trashbin api call which returns 207 and also returning response on failing assertion if this intermittent test failure is encountered again.
Also filtering the response according to the wevdav request (note: there is no endpoint for trashbin in old dav version)
https://github.com/owncloud/ocis/issues/6628
to solve https://github.com/owncloud/ocis/issues/6628
- locally
- CI
- ...

[tests-only][full-ci]refactor for Intermittent test failures on coreApiTrashbin/trashbinDelete.feature

---

go.mod
go.sum
services/graph/pkg/config/config.go
services/graph/pkg/identity/ldap_education_school.go
services/graph/pkg/identity/ldap_education_school_test.go
services/graph/pkg/service/v0/educationschools.go
services/graph/pkg/service/v0/educationschools_test.go
vendor/github.com/owncloud/libre-graph-api-go/api_education_school.go
vendor/github.com/owncloud/libre-graph-api-go/model_education_school.go
vendor/modules.txt

Schools can now have a terminationDate set. Schools can only be deleted if the terminationDate is in the past. Schools without a terminationDate cannot be deleted.
The minimal period that the terminationDate needs be be in the future can be configured using the `GRAPH_LDAP_SCHOOL_TERMINATION_MIN_GRACE_DAYS` setting.
Example:
```
GRAPH_LDAP_SCHOOL_TERMINATION_MIN_GRACE_DAYS=1 ocis/bin/ocis graph server
```
To set a termination date on a school:
```
curl -kv -X 'PATCH'   'https://provisioning.owncloud.test/graph/v1.0/education/schools/1234'  \
-H 'accept: application/json' \
-H 'Authorization: Bearer xxxxxxx' \
-d '{ "terminationDate": "2023-07-12T14:55:00+02:00"}'
```
If that date is before the configured `GRAPH_LDAP_SCHOOL_TERMINATION_MIN_GRACE_DAYS` (or in the past) it will trigger in …

graph: New 'terminationDate' property on educationSchool

---

tests/TestHelpers/WebDavHelper.php
tests/acceptance/features/apiContract/copy.feature
tests/acceptance/features/apiContract/propfind.feature
tests/acceptance/features/apiContract/sharesReport.feature
tests/acceptance/features/apiContract/spacesReport.feature
tests/acceptance/features/apiContract/spacesSharesReport.feature
tests/acceptance/features/bootstrap/SearchContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

related https://github.com/owncloud/ocis/pull/6715
I added checking `X-Request-Id` in response header to the existing contract tests

[test-only] Api test. Checking X-Request-Id in response header

---

tests/acceptance/features/apiContract/propfind.feature
tests/acceptance/features/bootstrap/SpacesContext.php

Related #4727 
- added test to check `parentId` in Propfind response
- tests for checking `parentId` in Report response have already been implemented

[test-only] apiTest. check parentId in the Propfind response

---

changelog/unreleased/restart-postprocessing.md
services/postprocessing/pkg/service/service.go

Fixes ocis postprocessing restart command:
Restarts complete postprocessing pipeline if there is no active postprocessing.
https://github.com/owncloud/ocis/pull/6728 refused to get green

Restart Postprocessing

---

.drone.star

Last week we removed the drone code to stop previous PR builds, and to cancel a build early when a single pipeline fails.
The remaining special CI feature that we have is the drone code that posts a comment to GitHub about a failing acceptance test pipeline. That no longer works because it needs a GitHub token with too many permissions, and we do not make that available to PRs.
This PR removes the GitHub comment code from the drone CI. The `earlyFail` setting is also removed, because there is nothing that uses it any more
the link for tracing result id shown in the console instead of comments
Part of: https://github.com/owncloud/QA/issues/820

[tests-only]Remove GitHub comment

---

changelog/unreleased/enhancement-add-search-filter-for-location.md
services/search/pkg/engine/bleve.go
services/search/pkg/search/search.go
services/search/pkg/search/service.go
services/search/pkg/search/service_test.go

- Enhancement: [ocis] Provide Search filter for locations OCIS-3705
Acceptance Criteria
- provide possibility for the client to restrict the search to the current folder via api (recursive)
- scope needed for "current folder" (default is to search all available spaces) - part of the `oc-pattern:"scope:<uuid>/Test"`
- search service only retruns results in the given scope
- API call is documented in dev docs
- test environment: Local
- test case 1:  
1.1 Login as admin; go to the Personal; create the file 'testfile.txt'; create the folder 'nfolder' and create inside the file 'newfile.txt'.
1.2 Call the API by name and location `<oc:pattern>file scope:storage-users-1$some-admin-user-id-0000-000000000000!some-admin-user-id-0000-000000000000/nfolder</oc:pattern>` have to return only the …

Provide Search filter for locations

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiGraph/fullSearch.feature

This PR adds the API tests for search restored files through a tag. The scenarios added in this PR are
- search restored files through a tag
- there was no test coverage for api test for search restored files through a tag. so, this PR covers the require scenario test case
- locally
- CI

[tests-only][full-ci] Added API test to search for restored resources having tag

---

.drone.star

Backport: https://github.com/owncloud/ocis/pull/6783
Last week we removed the drone code to stop previous PR builds, and to cancel a build early when a single pipeline fails.
The remaining special CI feature that we have is the drone code that posts a comment to GitHub about a failing acceptance test pipeline. That no longer works because it needs a GitHub token with too many permissions, and we do not make that available to PRs.
This PR removes the GitHub comment code from the drone CI. The `earlyFail` setting is also removed, because there is nothing that uses it any more
the link for tracing result id shown in the console instead of comments
Part of: https://github.com/owncloud/QA/issues/820

[tests-only][full-ci]Remove GitHub comment from ci stable 3.0

---

services/search/pkg/command/server.go

@aduffeck and I stumbled over this in distributed deployments.
maybe @Excds can verify?
cc @wkloucek

use correct config struct for jwt token

---

tests/acceptance/features/coreApiWebdavPreviews/previews.feature
tests/acceptance/features/coreApiWebdavPreviews/previewsAutoAdustedSizing.feature

Previously, the scenarios of feature files `previews.feature` and `previewsAutoAdjustedSizing.feature` were skipped using the tag `@preview-extension-required` but tag was removed in recent PR (https://github.com/owncloud/ocis/pull/6766), so the scenarios are failing in both Reva edge (https://drone.owncloud.com/cs3org/reva/2307/16/6) and master (https://drone.owncloud.com/cs3org/reva/2313/12/7).
This PR adds tag `@skipOnReva`.

[tests-only][full-ci]add tag skipOnReva

---

.drone.star

e2e tests pipeline runs for about 30 mins which is huge. So, this PR splits the pipeline into two
- Fixes https://github.com/owncloud/ocis/issues/6810

ci: split e2e test pipeline

---

ocis-pkg/shared/shared_types.go

Fixes: [Content of owncloud.dev/admin docs does not match code (envvar in gateway service)](https://github.com/owncloud/ocis/issues/6816#top)
* Replacing `\"` --> `'` missed when doing
#6723 and
#6724
* Correct the removalVersion for `REVA_GATEWAY` from `3.1` --> `4.0.0`

[docs-only] Fix envvar descriptions in shared_types.go

---

docs/ocis/development/testing.md
tests/acceptance/run.sh

Sometimes when running tests locally, it is necessary to have an option to "abort the test after the first failure". 
@aduffeck please use `STOP_ON_FAILURE=true` in the script to enable it. 
CI does not need this option because it must compare failed tests with the expected failures file

[tests-only] [full-ci] ApiTest. added option. stop running tests after first failure

---

.drone.star
tests/acceptance/config/behat.yml
tests/acceptance/features/apiFullTextSearch/search.feature

- search file using context
- there was no test coverage for api test for search file using context. so, this PR covers the require scenario test case
- locally
- CI

[tests-only][full-ci]Search files by content

---

changelog/unreleased/bump-reva.md
go.mod
go.sum
vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocdav/move.go
vendor/modules.txt

Enhancement: Update reva to v2.15.0
*   Bugfix [cs3org/reva#4004](https://github.com/cs3org/reva/pull/4004): Add path to public link POST
*   Bugfix [cs3org/reva#3993](https://github.com/cs3org/reva/pull/3993): Add token to LinkAccessedEvent
*   Bugfix [cs3org/reva#4007](https://github.com/cs3org/reva/pull/4007): Close archive writer properly
*   Bugfix [cs3org/reva#3982](https://github.com/cs3org/reva/pull/3982): Fixed couple of smaller space lookup issues
*   Bugfix [cs3org/reva#4003](https://github.com/cs3org/reva/pull/4003): Don't connect ldap on startup
*   Bugfix [cs3org/reva#4032](https://github.com/cs3org/reva/pull/4032): Temporarily exclude ceph-iscsi when building revad-ceph image
*   Bugfix [cs3org/reva#4042](https://github.com/cs3org/reva/pull/4042): Fix writing 0 byte msgpack …

[full-ci] bump reva, adapt changelog

---

tests/acceptance/features/apiNotification/deleteNotification.feature
tests/acceptance/features/bootstrap/NotificationContext.php

This PR adds tests coverage for deleting notifcations
- Fixes https://github.com/owncloud/ocis/issues/6712
- Locally

[tests-only][full-ci]Add tests for deleting notification

---

tests/acceptance/features/apiGraph/fullSearch.feature

This is a backport of PR https://github.com/owncloud/ocis/pull/6725

[tests-only][full-ci] Backport of add scenario for search folder tag

---

tests/TestHelpers/UploadHelper.php
tests/acceptance/features/bootstrap/WebDav.php

This PR extends #6796 
Straight after creating a user, test scenarios often create a folder or file(s) in the user's personal space. There seems to be a very small chance that the folder create MKCOL request or the file upload request gets a `409` "conflict" response. That happens when the server processing doesn't quite "see" the new user yet.
PR #6796 implemented code in the HTTP Request Helper to automatically retry the request if a `409` happens on a folder-create Given step.
This PR does the same for Given steps that upload a file - steps with the pattern "Given...has uploaded..."
The functions that are called in these cases now pass `isGivenStep` through to the HTTP Request Helper so that it knows that these are "Given" steps, and that it should retry the API  request if a `409` …

[tests-only] [full-ci] Retry if 409 is received when uploading in a Given step

---

tests/TestHelpers/UploadHelper.php
tests/acceptance/features/bootstrap/WebDav.php

Backport PR #6835 to `stable-3.0`
CI

[tests-only] Retry if 409 is received when uploading in a Given step

---

tests/acceptance/features/apiFullTextSearch/search.feature

- sharee search files using content
- there was no test coverage for api test for sharee search files using content. so, this PR covers the require scenario test case
- locally
- CI

[tests-only][full-ci]Search files through content by sharee

---

tests/acceptance/features/apiFullTextSearch/search.feature

This PR adds the API tests for search deleted files using content. The scenarios added in this PR are
- search deleted files using content
- there was no test coverage for api test for search deleted files using content. so, this PR covers the require scenario test case
- locally
- CI

[tests-only][full-ci]Add test for search deleted files using content

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/bootstrap/Provisioning.php
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
tests/acceptance/features/coreApiWebdavOperations/refuseAccess.feature

The steps where admin disable any user issue were marked failed as it uses OCS API. At present, this task couldn't be done using ocs API as the curl request to that endpoint results in an error. This PR redacted that step so that the feature now uses graph API and the Scenario gets passed and they were removed from the expected failure file. 
- https://github.com/owncloud/QA/issues/816
- locally
- ci

[tests-only][full-ci] make user enable disable feature use graphapi

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiSpaces/spaceDownload.feature
tests/acceptance/features/bootstrap/ArchiverContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

This PR adds the API test scenario for downloading space.
[ApiTest. next iteration](https://github.com/owncloud/ocis/issues/6606)
There was no test coverage for api test to download space and check the content of archive. So, this PR covers the required scenario test case.
- locally
- CI

[tests-only] [full-ci] add test for downloading space

---

tests/acceptance/features/bootstrap/NotificationContext.php

Part of: https://github.com/owncloud/QA/issues/817
Sometimes tests try to get the notification before the server sends it, so the in this PR if the `message` is not set, then try to get the notification again. This will hopefully prevent error's like https://github.com/owncloud/QA/issues/817#issuecomment-1632153289
`apiAntivirus/antivirus.feature:294`
`apiAntivirus/antivirus.feature:296`: https://drone.owncloud.com/owncloud/ocis/24228/56/7
```feature
Scenario Outline: upload a file with virus smaller than the upload threshold                                             # /drone/src/tests/acceptance/features/apiAntivirus/antivirus.feature:283
Given the config "ANTIVIRUS_MAX_SCAN_SIZE" has been set to "100"                                                       # …
```

[tests-only][full-ci]Retry listing notifications

---

tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature

The test step started with `And` instead of `When` as this is not the convention we follow, this PR fixes that

[tests-only][full-ci] Fix the syntax of the test step

---

tests/acceptance/config/behat.yml
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/SpacesContext.php

Backport: https://github.com/owncloud/ocis/pull/6627
the feature `uid_file_owner = spaceId for project space` was not merged to the stable branch, so this check is not done here.

[full-ci][tests-only][backport] Check id file owner in response

---

.drone.star
tests/acceptance/config/behat.yml
tests/acceptance/features/apiFullTextSearch/search.feature

This is the backport of master PR https://github.com/owncloud/ocis/pull/6678

[tests-only][full-ci]Backport-search files using content

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiFullTextSearch/search.feature

This PR adds the API tests for search restored files through a tag. The scenarios added in this PR are
- search restored files using a content
- there was no test coverage for api test for search restored files through a content. so, this PR covers the require scenario test case
- locally
- CI

[tests-only][full-ci]Add test for search restored files using content

---

changelog/unreleased/configurable_max_message_size.md
docs/services/general-info/additional-information.md
ocis-pkg/shared/shared_types.go

Needs https://github.com/cs3org/reva/pull/4074
Fixes https://github.com/owncloud/ocis/issues/6746

[docs-only] Configurable max message size

---

services/antivirus/pkg/config/config.go
services/app-provider/pkg/config/config.go
services/auth-basic/pkg/config/tracing.go
services/idm/pkg/config/config.go
services/idp/pkg/config/config.go

Found while reviewing.
This PR increases the value readability in the documentation by replacing `\"` with `'`
(escaped double quote with single quote).
`echo '\"output\"' | sed "s/\\\\\"/'/g"` --> `'output'`
`grep -rl "desc:" * | xargs sed -i -e "/desc:/ s/\\\\\"/'/g"`

[docs-only] Replace double quotes with single quotes in envvar descriptions

---

tests/acceptance/features/apiAntivirus/antivirus.feature
tests/acceptance/features/bootstrap/NotificationContext.php

This PR consist refactoring antivirus feature step where antivirus notification is checked.
- new step is added where the notification message for `resource` with `subject` is checked and then it is deleted
Previously in some scenarios in antivirus feature which contained two when then steps and checked for their respective notifications pass only if the file containing antivirus in both steps has same name.
These tests will fail if the files have different name because previously notifications were checked with parameters `user` and `subject` only which are same for two files containing virus. So, second notification check will return the notification from previous when then. 
So, new step is added which checks notification response with `user` and `subject` of notification in this PR …

[tests-only][full-ci] refactor check notification and delete it

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiFullTextSearch/search.feature

This is the backport of the master PR https://github.com/owncloud/ocis/pull/6709

[tests-only][full-ci]Backport of search restored files using context

---

tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/Sharing.php

Currently, response details of the user shares is stored in different variables like `$lastShareDataByUser`, `$lastShareIdByUser`, `$userWhoCreatedLastShare`. Instead of using different stores to store these data, all this can be stored on a single store and needed information can be retrieved from it where needed. This PR implements the storing of all the information of the created user shares in a single place and the important data are retrieved from it when the user share data are required.
- https://github.com/owncloud/core/issues/40285

[tests-only][full-ci] refactored acceptance code to store the response data related to user or group shares on single store

---

changelog/unreleased/fix-onlyoffice-default-document-language.md
go.mod
go.sum
vendor/github.com/cs3org/reva/v2/pkg/app/provider/wopi/wopi.go
vendor/modules.txt

Fix the default document language for OnlyOffice
- Fixes [https://github.com/owncloud/enterprise/issues/5807](https://github.com/owncloud/enterprise/issues/5807)
- test environment: The local docker stack [wopi](https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_wopi) setup: 
- checkout to the issue branch and build the dev image `make -C ocis dev-docker`
- go to deployments/examples/ocis_wop 
- run `export OCIS_DOCKER_TAG=dev` and `docker-compose up -d`
- test case 1: Change the language to desirable in the Account settings (Galego is not supported). Create the new Microsoft Word document.
Expected result: The UI and document language match to ocis language.

[full-ci] Fix the default document language for OnlyOffice

---

.drone.env
changelog/3.1.0_2023-07-18/update-web-7.1.0-rc.1.md
services/web/Makefile

The following issues have been fixed since the last RC:
- fix: add missing translations: [owncloud/web#9443](https://github.com/owncloud/web/pull/9443)
- fix: access token renewal during cloud imports: [owncloud/web#9460](https://github.com/owncloud/web/pull/9460)
- fix: broken cloud import dashboard when upload failed before: [owncloud/web#9471](https://github.com/owncloud/web/pull/9471)
- fix: prevent uploads when a cloud import is running: [owncloud/web#9470](https://github.com/owncloud/web/pull/9470)
- fix: concurrent uploads: [owncloud/web#9463](https://github.com/owncloud/web/pull/9463)
- fix: generate unique request ids for tus upload requests: [owncloud/web#9418](https://github.com/owncloud/web/pull/9418)
- fix: merging folders: …

[full-ci] chore: bump web to v7.1.0-rc.2

---

services/notifications/pkg/command/server.go

This changes to use a package local grpc client variable instead of the grpc.DefaultClient().

Separate out grpc client to package local for notifications service.

---

changelog/unreleased/check-public-auth-first.md
services/proxy/pkg/command/server.go

Fixes https://github.com/owncloud/ocis/issues/6887

Check public link auth first

---

services/userlog/pkg/command/server.go

Separate out grpc client to package local for userlog service.

---

services/webdav/pkg/command/server.go
services/webdav/pkg/config/config.go
services/webdav/pkg/service/v0/service.go

Separate out grpc client to package local for webdav service.

---

ocis-pkg/service/grpc/service.go
services/thumbnails/pkg/command/server.go
services/thumbnails/pkg/config/config.go
services/thumbnails/pkg/server/grpc/server.go

Separate out grpc client to package local for thumbnails service.

---

services/search/pkg/command/index.go
services/search/pkg/command/server.go

Separate out grpc client to package local for search service.

---

services/ocs/pkg/command/server.go
services/ocs/pkg/config/config.go
services/ocs/pkg/service/v0/users.go

Separate out grpc client to package local for ocs service.

---

changelog/unreleased/fix-error-message-on-400-code-thumbnail.md
services/webdav/pkg/service/v0/service.go
tests/acceptance/expected-failures-API-on-OCIS-storage.md

Whenever the file preview requests fail with `400 Bad Request`, full error object was returned as error message for the webdav response. For example (try to get folder preview);
```bash
curl "https://localhost:9200/remote.php/dav/files/admin/folder?x=32&y=32&forceIcon=0&preview=1" \
-uadmin:admin -vk
```
**_Current,_**
```xml
...
< HTTP/1.1 400 Bad Request
...
<?xml version="1.0" encoding="UTF-8"?>
<d:error
xmlns:d="DAV"
xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
<s:message>{"id":"com.owncloud.api.thumbnails","code":400,"detail":"Unsupported file type","status":"Bad Request"}</s:message>
</d:error>
```
This PR fixes the redundancy in the error message and only return detail from the error object.
**_With PR,_**
```xml
... …
```

fix: use error detail as message instead of whole error object

---

changelog/unreleased/fix-cache-header.md
services/web/pkg/service/v0/service.go

Bugfix: Let clients cache web and theme assets
We needed to remove "must-revalidate" from the cache-control header to allow clients to cache the web and theme assets.
- Fixes https://github.com/owncloud/ocis/issues/5754
- test case 1:
- test case 2:
- ...

Fix cache header for web and theme assets

---

go.mod
go.sum
ocis/pkg/command/migrate.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/migrator/0001_create_spaces_directory_structure.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/migrator/0002_move_spacetypes_to_indexes.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/migrator/0003_switch_to_messagepack_metadata.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/migrator/0004_switch_to_messagepack_space_index.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/migrator/0005_fix_messagepack_space_index_format.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/migrator/migrator.go
vendor/modules.txt

This pr adds a command for listing and rolling back decomposedfs migrations, e.g. before downgrading to an older release.
Example output:
```
$ ocis migrate decomposedfs -r /home/andre/.ocis/storage/users/ -h
NAME:
ocis migrate decomposedfs - run a decomposedfs migration
USAGE:
ocis migrate decomposedfs [command options] [arguments...]
OPTIONS:
--direction value, -d value  direction of the migration to run ('up' or 'down') (default: "up")
--migration value, -m value  ID of the migration to run
--root value, -r value       Path to the root directory of the decomposedfs
--list, -l                   Print a list of migrations incl. their state (default: false)
--help, -h                   show help
$ ocis migrate decomposedfs -r /home/andre/.ocis/storage/users/ -l …
```

[full-ci] Add support for running/rolling back decomposedfs migrations

---

services/proxy/pkg/command/server.go
services/proxy/pkg/config/config.go
services/proxy/pkg/middleware/policies.go

This replaces grpc.DefaultClient() with package local variable and uses one grpc client for all parts.

Remove grpc.DefaultClient() reference from policies and use only one grpc client in proxy.

---

ocis-pkg/service/grpc/client.go
ocis-pkg/service/grpc/service.go
ocis/pkg/command/server.go
services/eventhistory/pkg/command/server.go
services/eventhistory/pkg/config/config.go
services/eventhistory/pkg/server/grpc/server.go
services/graph/pkg/command/server.go
services/graph/pkg/service/v0/application_test.go
services/graph/pkg/service/v0/approleassignments_test.go
services/graph/pkg/service/v0/driveitems_test.go
services/graph/pkg/service/v0/educationclasses_test.go
services/graph/pkg/service/v0/educationschools_test.go
services/graph/pkg/service/v0/educationuser_test.go
services/graph/pkg/service/v0/groups_test.go
services/graph/pkg/service/v0/users_test.go
services/notifications/pkg/service/service_test.go
services/policies/pkg/command/server.go
services/search/pkg/command/server.go
services/search/pkg/config/config.go
services/search/pkg/server/grpc/server.go
services/settings/pkg/command/server.go
services/settings/pkg/config/config.go
services/settings/pkg/server/grpc/server.go
services/store/pkg/command/server.go
services/store/pkg/config/config.go
services/store/pkg/server/grpc/server.go

Removing the remaining references to grpc.DefaultClient() and the related methods.

Replacing implicit grpc client initialization with explicit package local variables

---

.drone.star
tests/acceptance/config/behat.yml
tests/acceptance/features/apiReshare/disableReshare.feature

This PR adds the API tests for sharing by setting FRONTEND_ENABLE_RESHARING to false. The scenarios added in this PR are:
- share folder with different roles
- try to re-share folder
-  https://github.com/owncloud/ocis/issues/6606#event-9635806756
- there was no test coverage for api test for disabling  FRONTEND_ENABLE_RESHARING env variable. So, this PR covers the required scenarios test cases.
- locally
- CI

[tests-only][full-ci] added scenarios for disabling frontend_enable_resharing

---

.drone.env
changelog/3.1.0_2023-07-18/update-web-7.1.0-rc.4.md
services/web/Makefile

Fixes since last rc:
* Bugfix [owncloud/web/#9507](https://github.com/owncloud/web/pull/9507): Space description edit modal is cut off vertically
* Bugfix [owncloud/web/#9501](https://github.com/owncloud/web/pull/9501): Add cloud importer translations
* Bugfix [owncloud/web/#9510](https://github.com/owncloud/web/pull/9510): Double items after moving a file with the same name

[full-ci] chore: bump web to v7.1.0-rc.4

---

docs/ocis/development/testing.md
tests/acceptance/docker/Makefile
tests/acceptance/docker/src/ocis-base.yml

Updated local docker-compose setup for tests making it able to run Unicode text preview tests locally. Also, updated the testing docs indicating the requirement of a special env variable when starting the oCIS server to run such tests.
follow up https://github.com/owncloud/ocis/issues/6931
run tests locally

[tests-only][full-ci] Update local test docker-compose setup to allow unicode preview tests

---

tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/PublicWebDavContext.php
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/WebDav.php
tests/acceptance/features/bootstrap/WebDavLockingContext.php
tests/acceptance/features/bootstrap/WebDavPropertiesContext.php

Currently, response details of the public shares are stored in different variables like `$userWhoCreatedLastPublicShare`, `$lastPublicShareData`, `$lastPublicShareId`, etc. Instead of using different stores to store these data, all this can be stored in a single store, and needed information can be retrieved from it where required. This PR implements the storing of all the information of the created user shares in a single place `$createdPublicShares` and the important data are retrieved from it when the public share data are required
- https://github.com/owncloud/core/issues/40285

[tests-only][full-ci] refactored acceptance test code to store response data related to public shares on single store

---

tests/acceptance/features/apiGraph/assignRole.feature
tests/acceptance/features/apiGraph/createUser.feature
tests/acceptance/features/apiGraph/editUser.feature
tests/acceptance/features/apiGraph/getApplications.feature
tests/acceptance/features/apiGraph/getUser.feature
tests/acceptance/features/apiSpaces/spaceManagement.feature
tests/acceptance/features/apiSpaces/tag.feature
tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature

Part of: https://github.com/owncloud/ocis/issues/6726
As we don't run the tests in `stable-2.0` branch these tags are not need so this PR removes them

[tests-only][full-ci] Remove `@skipOnStable2.0` tag

---

tests/acceptance/features/apiGraph/assignRole.feature
tests/acceptance/features/apiGraph/createUser.feature
tests/acceptance/features/apiGraph/editUser.feature
tests/acceptance/features/apiGraph/getApplications.feature
tests/acceptance/features/apiGraph/getUser.feature
tests/acceptance/features/apiSpaces/spaceManagement.feature
tests/acceptance/features/apiSpaces/tag.feature
tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature

Fixes: https://github.com/owncloud/ocis/issues/6726
Backport: https://github.com/owncloud/ocis/pull/6959
As we don't run the tests in `stable-2.0` branch these tags are not need so this PR removes them

[tests-only][full-ci] Remove `@skipOnStable2.0`  tag

---

changelog/unreleased/fix-search.md
services/search/pkg/engine/bleve.go
services/search/pkg/engine/bleve_test.go
services/search/pkg/search/service.go

We fixed the issue when searching using the current folder option shows the file/folders outside the folder if the search keyword is the same as the current folder
- Fixes [https://github.com/owncloud/ocis/issues/6935](https://github.com/owncloud/ocis/issues/6935)
- test case 1: Described in a ticket

[full-ci]Fix the search

---

tests/TestHelpers/WebDavHelper.php
tests/acceptance/features/apiGraph/fullSearch.feature
tests/acceptance/features/bootstrap/WebDav.php

- search files by tag using new DAV path in Project spaces
In this PR there is refactored on:
- search files by tag
- there was no test coverage for api test for search files using tag in project spaces. This PR covers the global search using tag on  personal space and global spaces. There is only search scanerio test done only by using new Dav path. There is also done refactor on `search files by tag` there are some changes like:
1. The file name is changes
2. There is also check for search for file inside folder and subfolder
- locally
- CI

[tests-only][full-ci]add api test for search files using tag in project spaces

---

changelog/unreleased/add-rebuild-jsoncs3-index-command.md
ocis/pkg/command/migrate.go

We added a command for rebuilding the jsoncs3 share manager indexes.
Example output:
```
$ ocis migrate rebuild-jsoncs3-indexes
Scanning storage storage-users-1 (1/1)
Rebuilding space 1/1...  done
done
```

Rebuild jsoncs3 index

---

tests/acceptance/features/apiGraph/fullSearch.feature
tests/acceptance/features/bootstrap/WebDav.php

This PR is the backport of the master PR https://github.com/owncloud/ocis/pull/6853

[tests-only][full-ci]Backport search project space files using context

---

tests/acceptance/features/apiSpaces/search.feature
tests/acceptance/features/bootstrap/SearchContext.php

This PR adds Api test for searching inside current folder in space(Location Filter). Following scenario is added:
- user can search inside folder in space
https://github.com/owncloud/ocis/issues/6606
There is no test coverage for api test for searching by enabling current folder on where files and folders are searched inside that particular folder only in spaces
- locally
- CI

[tests-only][full-ci] added test scenario for searching inside folder in space

---

tests/acceptance/features/apiGraph/fullSearch.feature

This PR adds the API tests for search version restored files through a tag. The scenarios added in this PR are
- search version restored files using a tag
- there was no test coverage for api test for search version restored files through a tag. so, this PR covers the require scenario test case
- locally
- CI

[tests-only][full-ci]add test for search version restored files by tag

---

ocis/cmd/ocis/main.go

when we reach this line we should print the error instead of swallowing it ...

log error in cli

---

tests/acceptance/features/apiGraph/fullSearch.feature

- Search project space folders using a tag
- there was no test coverage for api test for search project space folders using tag. so, this PR covers the require scenario test case
- locally
- CI

[tests-only][full-ci]add test for search project folders by tag

---

changelog/unreleased/add-rebuild-jsoncs3-index-command.md
ocis/pkg/command/migrate.go

This PR makes the `migrate rebuild-jsoncs3-indexes` command exit with status code 1 when something went wrong during the migration.

Fail on errors

---

ocis/pkg/command/migrate.go

Remove subcommand from rebuild-jsoncs3-indexes that doesn't belong there

Remove subcommand from rebuild-jsoncs3-indexes that doesn't belong there

---

tests/acceptance/features/apiFullTextSearch/search.feature

This PR adds the API tests for search version restored files through a content. The scenarios added in this PR are
- search version restored files using a content
- there was no test coverage for api test for search version restored files through a content. so, this PR covers the require scenario test case
- locally
- CI

[tests-only][full-ci]add test for search version restored files by content

---

.drone.env
changelog/3.1.0_2023-08-02/update-web-7.1.0-rc.5.md
services/web/Makefile
tests/acceptance/expected-failures-webUI-on-OCIS-storage.md

Changes since the last rc:
* Enhancement [owncloud/web#9449](https://github.com/owncloud/web/issues/9449): Error notifications include x-request-id
* Enhancement [owncloud/web#9426](https://github.com/owncloud/web/pull/9426): Add error log to upload dialog

[full-ci] chore: bump web to v7.1.0-rc.5

---

tests/acceptance/features/apiGraph/fullSearch.feature

This PR is Backport of master PR https://github.com/owncloud/ocis/pull/6968

[tests-only][full-ci]Backport search folder by tag in project space

---

docs/helpers/extended_vars.yaml

As discussed with @butonic, the supported value `mdns` was missing in the MICRO_REGISTRY envvar description.

[docs-only] Add mdns as supported value in MICRO_REGISTRY envvar description

---

deployments/examples/ocis_keycloak/config/keycloak/ocis-realm.dist.json

The Keycloak example has `revokeRefreshToken` enabled right now, this leads to sessions being terminated with the error `Maximum allowed refresh token reuse exceeded`. This PR disables this setting.
None
No session termination in example setups.
Tested locally once with the setting turned on and once with the setting turned off.

Disabled revokeRefreshToken in Keycloak config

---

.drone.star

Allow sonarcloud and codacy to run even if the golint and unit test pipelines are skipped
prevents sonarcloud checks from being stuck

ci: do not skip sonarcloud and codacy even if golint and unit-tests are skipped

---

tests/acceptance/features/apiNotification/deprovisioningNotification.feature
tests/acceptance/features/bootstrap/NotificationContext.php

related: https://github.com/owncloud/ocis/pull/6672
tests for next PR:

[test-only]ApiTest. Deprovisioning notification tests

---

ocis-pkg/tracing/tracing.go

This removes unused and kind of duplicated tracing initialization.

Remove unused reva tracing initialization.

---

tests/acceptance/features/apiSpaces/search.feature

This PR adds Api test for searching inside current folder in shares(Location Filter). Following scenario is added:
- user can search inside folder in shares
https://github.com/owncloud/ocis/issues/6606
There is no test coverage for api test for searching by enabling current folder on where files and folders are searched inside that particular folder in shares
- locally
- CI

[tests-only][full-ci] added test scenario for searching inside folder in shares

---

tests/acceptance/features/apiFullTextSearch/search.feature

This PR adds the API tests for searching project space files by sharee using content. The scenarios added in this PR are
- sharee searches shared project spaces files by content
- there was no test coverage for the API test for Sharee searches project files using content. so, this PR covers the require scenario test case
- locally
- CI

[tests-only][full-ci]add test for sharee searches project spaces files by content

---

tests/acceptance/features/apiSpaces/search.feature
tests/acceptance/features/bootstrap/SearchContext.php

This PR backports https://github.com/owncloud/ocis/pull/6972 and https://github.com/owncloud/ocis/pull/6982

[tests-only][full-ci] Backport search inside folder shares and spaces

---

.drone.star
tests/acceptance/config/behat.yml
tests/acceptance/features/apiSpacesDavOperation/getFileByFileId.feature
tests/acceptance/features/bootstrap/SpacesContext.php

This PR adds the test scenarios for reading the content of a file inside personal space, project space, inside sub-folder, and shared files/folders. 
The added test is done with and without `remote.php`, in the destination URL.
- `/remote.php/dav/spaces/<fileId>`
- `/dav/spaces/<fileId>`

[test-only][full-ci] added tests for reading content of a file by fileId using WebDav API

---

tests/acceptance/features/apiGraph/fullSearch.feature

This PR adds the API tests for searching project space files by sharee using a tag. The scenarios added in this PR are
- sharee searches shared project spaces files using a tag
- there was no test coverage for the API test for Sharee searches project files using a tag. so, this PR covers the require scenario test case
- locally
- CI

[tests-only][full-ci]add test for sharee searches project spaces files using a tag

---

tests/acceptance/features/apiGraph/fullSearch.feature
tests/acceptance/features/bootstrap/TagContext.php

This PR consists of refactoring `created tags` step where multiple tags are created for a file.
- new step is added where the multiple tags can be added with multiple files
https://github.com/owncloud/ocis/issues/6606#event-9635806756
several tags may only be added to one file at a time in the previous step, thus that step must be repeated in order to add tags to several files. That will lengthen the scenario.
So, a new step has been added in which several tags can be placed in multiple files at once and it will cut short the length of the scenario
- locally
- ci

[tests-only][full-ci]refactoring the tag creating step using data table

---

tests/acceptance/features/apiGraph/fullSearch.feature
tests/acceptance/features/bootstrap/TagContext.php

This PR is backport of master https://github.com/owncloud/ocis/pull/7051

[tests-only][full-ci]Backport refactoring the tag creating step using data table

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md

Related issue: https://github.com/owncloud/ocis/issues/1239
These tests were linked in the wrong issue in expected to fail file 
- [coreApiWebdavProperties1/copyFile.feature:271](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/coreApiWebdavProperties1/copyFile.feature#L271)
- [coreApiWebdavProperties1/copyFile.feature:272](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/coreApiWebdavProperties1/copyFile.feature#L272)
- [coreApiWebdavProperties1/copyFile.feature:289](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/coreApiWebdavProperties1/copyFile.feature#L289)
- [coreApiWebdavProperties1/copyFile.feature:290](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/coreApiWebdavProperties1/copyFile.feature#L …

[tests-only]Update expected to fail file to link failing tests to correct issue

---

services/frontend/pkg/command/server.go

The tracing initialization was obviously commented out by mistake and missed in reviews, so re-enabling it...

Re-enable commented out tracing in frontend.

---

.drone.star
deployments/examples/ocis_wopi/docker-compose.yml

The default wopiserver version in the examples should be raised to 10.1.0
Keep version of depending services up to date
Tested by executing the example again

Raised default wopiserver version to 10.1.0

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md

backport https://github.com/owncloud/ocis/pull/7081
Related issue: https://github.com/owncloud/ocis/issues/1239
These tests were linked in the wrong issue in expected to fail file 
- [coreApiWebdavProperties1/copyFile.feature:271](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/coreApiWebdavProperties1/copyFile.feature#L271)
- [coreApiWebdavProperties1/copyFile.feature:272](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/coreApiWebdavProperties1/copyFile.feature#L272)
- [coreApiWebdavProperties1/copyFile.feature:289](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/coreApiWebdavProperties1/copyFile.feature#L289)
- [coreApiWebdavProperties1/copyFile.feature:290](https://github.com/owncloud/ocis/blob/master/tests/acceptance/ …

[tests-only] Backport/7081

---

tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature
tests/acceptance/features/apiSpaces/quota.feature
tests/acceptance/features/apiSpaces/uploadSpaces.feature
tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
tests/acceptance/features/coreApiSharePublicLink3/uploadToPublicLinkShare.feature

fix some of the steps ordering in the tests 
I was trying to run https://github.com/JankariTech/expected-failures-updater to check if the app still works in catching the repetitive `Given` `Then` step and these are some of the changes the app made. Some of the changes were also manually done depending on the context of the scenario

[tests-only] Fix the test step keyword ordering

---

services/gateway/pkg/config/config.go

The `...ENDPOINT` ennvars do not bring any value as their counterpart cannot be configured. We do not want them in the release. 
We need to come up with a proper solution after the release

[tests-only] Remove `...ENDPOINT` Envvars from gateway

---

docs/ocis/identity-provider/ldap-active-directory.md

For Active Directory we need: OCIS_LDAP_DISABLE_USER_MECHANISM=none. Until we add support for evaluating the "userAccountControl" bitmask, we don't supported display the account enable/disable state for Active Directory users.
related: https://github.com/owncloud/enterprise/issues/5858

Fix AD example

---

ocis-pkg/config/config.go
ocis-pkg/shared/shared_types.go

This are the two remaining locations in the `stable-3.0` branch where we have missed to correct the removal version for deprecations. They are printed in the admin docs as 3.1 but should be 4.0.0
Found via:
* the ocis admin documentation
* `grep -rn removalVersion | grep 3.1` in the ocis `stable-3.0` branch
When the PR is merged, CI will update the `docs-stable-3.0` branch automatically --> admin docs.

Forgotten wrong deprecation version fix (3.1 --> 4.0.0)

---

tests/acceptance/features/bootstrap/FeatureContext.php

Currently theHTTPStatusCodeShouldBe() uses response that is set early to check status code. This pr refactors theHTTPStatusCodeShouldBe() so that it can also accept response object as parameter to get statuscode from and check it.
As we are removing the setResponse() in given steps we should make theHTTPStatusCodeShouldBe() also to be able to take the returned response as parameter and check the status code from it to verify that given steps have passed. …

[tests-only][full-CI] make httpresponse check function able to accept response object as parameter

---

tests/acceptance/features/apiContract/spacesReport.feature
tests/acceptance/features/bootstrap/SpacesContext.php

While searching with `REPORT` request in our test code only the status code is checked as asserting `207` while the request gives the status `207` when the response is empty. So This PR adds some strict checks to the `multistatus` response from `REPORT` request.
https://github.com/owncloud/ocis/issues/7185#issuecomment-1702422487
fixes: https://github.com/owncloud/ocis/issues/7185

[tests-only][full-ci]Check `multistatus` response strictly in test code

---

changelog/unreleased/access-token-issuer.md
ocis-pkg/oidc/client.go
ocis-pkg/oidc/metadata.go

AD FS `/adfs/.well-known/openid-configuration` has an optional `access_token_issuer` which, in violation of the OpenID Connect spec, takes precedence over `issuer`.
Evn MS had to patch its own clients: https://jpassing.com/2022/02/04/using-adfs-access-tokens-for-workload-identity-federation/

support AD FS

---

deployments/examples/ocis_keycloak/docker-compose.yml

Set 'GRAPH_USERNAME_MATCH' to 'none'. To accept any username that is also valid for keycloak.

deployment: Disable username validation for keycloak example

---

tests/acceptance/features/bootstrap/AppConfigurationContext.php
tests/acceptance/features/bootstrap/AuthContext.php
tests/acceptance/features/bootstrap/FeatureContext.php

- Given steps
So this pr make the above changes in `AppConfigurationContext` and `ArchiverContext`
- locally
- CI

[tests-only][full-ci] removing the setresponse in given/then step in AppConfigurationContext and AuthContext

---

tests/TestHelpers/EmailHelper.php
tests/TestHelpers/GraphHelper.php
tests/TestHelpers/WebDavHelper.php
tests/acceptance/features/apiContract/copy.feature
tests/acceptance/features/apiContract/propfind.feature
tests/acceptance/features/apiContract/sharesReport.feature
tests/acceptance/features/apiContract/spacesReport.feature
tests/acceptance/features/apiContract/spacesSharesReport.feature
tests/acceptance/features/bootstrap/ArchiverContext.php
tests/acceptance/features/bootstrap/NotificationContext.php
tests/acceptance/features/bootstrap/SearchContext.php
tests/acceptance/features/bootstrap/SettingsContext.php
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/TagContext.php
tests/acceptance/features/bootstrap/WebDavLockingContext.php

This PR includes the use of `X-Request-Id` header in each API requests. The `X-Request-Id` header consists the line reference of the scenario under test. If any of the test fails then oCIS server will log the error which contains `request-id` which represents the line reference of the failed scenario. For example, when any of the test fails oCIS server will provide the log as:
`
{"level":"error","service":"ocdav","name":"com.owncloud.web.ocdav","traceid":"00000000000000000000000000000000","request-id":"apiContract/propfind.feature:16-18","spaceid":"a428260f-6f47-4e9d-a939-6236977c3f8a$bbac7138-4375-4c27-8241-7ebe1e5af89d","path":"/","status":{"code":15,"message":"error getting upload id: Decomposedfs: error walking path: Decomposedfs: error walking path: decomposedfs: Wrap: readlink …

[tests-only][full-ci]send X-Request-Id in header of every request

---

tests/acceptance/features/apiSpacesDavOperation/updateFileByFileId.feature
tests/acceptance/features/bootstrap/FeatureContext.php

This PR backports the PR https://github.com/owncloud/ocis/pull/6990
- test case 1:
- test case 2:
- ...

[tests-only][full-ci] Backport added test to update file using file id

---

Makefile
tests/acceptance/docker/Makefile

Currently run tests with docker depend in local php due to `composer update`. This PR removes that part of code.
```
../../../vendor-bin/behat/composer.lock: ../../../vendor-bin/behat/composer.json
@echo behat composer.lock is not up to date.
@composer update --no-progress -d ../../../vendor-bin/behat
../../../composer.lock: ../../../composer.json
@echo composer.lock is not up to date.
@composer update --no-progress -d ../../../
```
- Fixes https://github.com/owncloud/ocis/issues/7071
- locally

[tests-only][full-ci] Eliminate local system PHP-dependent code for running tests in Docker

---

changelog/unreleased/fix-keycloak-example-username-validation.md
deployments/examples/ocis_keycloak/docker-compose.yml

Set 'GRAPH_USERNAME_MATCH' to 'none'. To accept any username that is also valid for keycloak.
(cherry picked from commit 48306cbef31a45c4d35e430d7f9b5573ad95f4d6)

Backport-4.0: deployment: Disable username validation for keycloak example

---

changelog/unreleased/auto-accept-shares.md
go.mod
go.sum
ocis/pkg/init/init.go
services/frontend/README.md
services/frontend/pkg/command/events.go
services/frontend/pkg/command/server.go
services/frontend/pkg/config/config.go
services/frontend/pkg/config/defaults/defaultconfig.go
services/frontend/pkg/config/parser/parse.go
services/ocs/README.md
services/settings/pkg/store/defaults/defaults.go
vendor/github.com/cs3org/reva/v2/internal/grpc/services/usershareprovider/usershareprovider.go
vendor/github.com/cs3org/reva/v2/pkg/cbox/share/sql/sql.go
vendor/github.com/cs3org/reva/v2/pkg/share/manager/cs3/cs3.go
vendor/github.com/cs3org/reva/v2/pkg/share/manager/json/json.go
vendor/github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/jsoncs3.go
vendor/github.com/cs3org/reva/v2/pkg/share/manager/memory/memory.go
vendor/github.com/cs3org/reva/v2/pkg/share/manager/owncloudsql/owncloudsql.go
vendor/github.com/cs3org/reva/v2/pkg/share/share.go
vendor/modules.txt

Auto accepts shares when configured
Fixes https://github.com/owncloud/ocis/issues/4834
According to story `auto-accept` should be true by default, but test pipeline cannot handle this for now. Steps to test auto acceptance:
- Make sure service accounts are enabled by setting `OCIS_SERVICE_ACCOUNT_ID` and `OCIS_SERVICE_ACCOUNT_SECRET` (or running ocis init on a fresh system)
- Enable auto-accept by setting `FRONTEND_AUTO_ACCEPT_SHARES` to `true`
- Disable auto-accept for einstein:
```
curl --insecure -X POST -u einstein:relativity https://localhost:9200/api/v0/settings/values-save -d '{"value":{"accountUuid":"me","bundleId":"2a506de7-99bd-4f0d-994e-c38e72c28fd9","settingId":"ec3ed4a3-3946-4efc-8f9f-76d38b12d3a9","resource":{"type":"TYPE_USER"},"boolValue":false}}'
```
- share a file with …

Auto Accept Shares

---

changelog/unreleased/kql-fix-unary.md
services/search/pkg/query/bleve/compiler.go
services/search/pkg/query/bleve/compiler_test.go

- test case 1:
- test case 2:
- ...

fix unary in the beginning. add tests

---

tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature

This PR adds a test for server panicking when the user try to update or add a password to the public link which for a newly created file which was deleted previously with the same name.
https://github.com/owncloud/ocis/issues/6929

[tests-only][full-ci]Added test for server getting panic when adding password to a public link

---

changelog/unreleased/fix-skip-user-info-option.md
services/proxy/pkg/command/server.go

backport https://github.com/owncloud/ocis/pull/7216 to stable 4.0

backport: actually use skip user info config option

---

tests/acceptance/features/apiSearch/apiSpaceSearch.feature
tests/acceptance/features/apiSearch/contentSearch.feature
tests/acceptance/features/apiSearch/tagSearch.feature
tests/acceptance/features/bootstrap/SearchContext.php

KQL feature:
Another
@2403905 I commented out failed tests

[test-only] KQL api search tests

---

changelog/unreleased/add-passwod-policies.md
go.mod
go.sum
services/frontend/README.md
services/frontend/pkg/config/config.go
services/frontend/pkg/config/defaults/defaultconfig.go
services/frontend/pkg/revaconfig/config.go
vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/shares.go
vendor/github.com/cs3org/reva/v2/pkg/password/password_policies.go
vendor/modules.txt

Value
applies only to links
enable/ disable password policy (default: disabled)
If the pw policy is enabled, it gets enforced by the backend
If the pw policy is enabled, it tells the clients about the pw requirements
Minimum password length.
Minimum number of uppercase letters.
Minimum number of lowercase letters.
Minimum number of digits.
Minimum number of special characters.
List of allowed special character; default: "!"#$%&'()*+,-./:;<=>?@[]^_`{|}~"
- Issue OCIS-3767
- test environment:  local
- test case 1: 
1. Set environment variables 
FRONTEND_PASSWORD_POLICIES_MIN_CHARACTERS=4
FRONTEND_PASSWORD_POLICIES_MIN_LOWER_CASE_CHARACTERS=1
FRONTEND_PASSWORD_POLICIES_MIN_UPPER_CASE_CHARACTERS=1
FRONTEND_PASSWORD_POLICIES_MIN_DIGITS=1
FRONTEND_PASSWORD_POLICIES_MIN_SPECIAL_CHARACTERS=1
2. …

[full-ci] The password policy added. Bump reva

---

services/graph/pkg/service/v0/driveitems.go
services/graph/pkg/service/v0/driveitems_test.go
services/graph/pkg/service/v0/drives.go
services/graph/pkg/service/v0/educationclasses_test.go
services/graph/pkg/service/v0/educationschools_test.go
services/graph/pkg/service/v0/errorcode/errorcode.go
services/graph/pkg/service/v0/graph.go
services/graph/pkg/service/v0/groups_test.go
services/graph/pkg/service/v0/service.go

This PR adds two endpoints that allow navigating the file tree via the graph API:
* `/drives/{driveID}/items/{driveItemID}` as a stat
* `/drives/{driveID}/items/{driveItemID}/children` to list all children of a folder
This is just a basic implementation, but I needed some fun today ...

give graph driveItems some love

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/bootstrap/WebDav.php
tests/acceptance/features/coreApiWebdavPreviews/previews.feature

Previously there was test coverage for previewing resources using new wed-dav only. This PR has added tests coverage of preview using old and spaces wed-dav version in personal spaces.
This PR does not cover the test for previewing the resources using spaces dav version for shared resources. Previewing the shared resource requires the `virtual shares id` or `mount point id` and the method to get the id exits in `SpacesContext` file and to get them in `WebDabHelper` might require some refactoring. So, the previewing of the shared resource is implement in this follow up PR https://github.com/owncloud/ocis/pull/7234
- Part of https://github.com/owncloud/ocis/issues/6752
- Locally

[tests-only][full-ci] Add test coverage for file preview using space dav version

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiGraph/editUser.feature
tests/acceptance/features/apiGraph/getUser.feature
tests/acceptance/features/bootstrap/AppConfigurationContext.php
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/Provisioning.php
tests/acceptance/features/bootstrap/WebDav.php
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareGroupAndUserWithSameName.feature
tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
tests/acceptance/features/coreApiVersions/fileVersions.feature
tests/acceptance/features/coreApiWebdavProperties1/getQuota.feature

This PR backports to https://github.com/owncloud/ocis/pull/7019

[tests-only][full-ci] refactoring user creation `Given` steps (#7019)

---

tests/acceptance/features/bootstrap/FilesVersionsContext.php
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/WebDav.php

[tests-only][full-ci] removing the setresponse in given/then step in FileVersionsContext

---

tests/acceptance/features/bootstrap/ChecksumContext.php
tests/acceptance/features/bootstrap/FavoritesContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

- Given steps
So this pr make the above changes in `CheckSumContext.php` and `FavoritesContext`
- locally
- CI

[tests-only][full-ci] removing the setresponse in given/then step in CheckSumContext and FavoritesContext

---

tests/acceptance/features/bootstrap/FeatureContext.php

This pr backports https://github.com/owncloud/ocis/pull/7169 to stable-4.0

[tests-only][full-CI]  backport make httpresponse check function able to accept response object as parameter(7169)

---

tests/acceptance/features/bootstrap/FilesVersionsContext.php
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/WebDav.php

This pr backports https://github.com/owncloud/ocis/pull/7111 to stable-4.0

[tests-only][full-ci] backport removing the setresponse in given/then step in FileVersions Context

---

tests/acceptance/features/bootstrap/ChecksumContext.php
tests/acceptance/features/bootstrap/FavoritesContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

This pr backports https://github.com/owncloud/ocis/pull/7202 to stable 4.0

[tests-only][full-ci] backport removing the setresponse in given/then step in CheckSumContext and FavoritesContext

---

tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature

This test was added recently by https://github.com/owncloud/ocis/pull/7233 and the issue that this test was covering was fixed on reva edge so skip this test in reva master to unblock the bumping of the commit id in reva

[tests-only]Skip test in reva master

---

.drone.star

we're currently running the nighly continous deployment cronjob on both the master and stable-4.0 branches.
That proabably leads to race conditions that breaks the deployments.
- Broken example deployments

don't run CD on stable-4.0 branch cronjob

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpacesShares/copySpaces.feature

Since this issue https://github.com/owncloud/ocis/issues/4393 was closed so that needs to be updated according to this issue linke for it. https://github.com/owncloud/ocis/issues/4393#issuecomment-1672885146. But New issue is created according to the actual behavior since the expected behavior is unknown. So This PR updates the expected to failure with the new issue created for the same failing test.
https://github.com/owncloud/ocis/issues/4393#issuecomment-1672885146

[tests-only][full-ci]Update expected to failure based on correct issue

---

tests/acceptance/features/bootstrap/TagContext.php
tests/acceptance/features/bootstrap/TrashbinContext.php

- Given steps
So this pr make the above changes in `TrashbinContext.php` and `TagsContext.php`
- locally
- CI

[tests-only][full-ci] removing the setresponse in given/then step in TrashbinContext and TagsContext

---

tests/acceptance/features/apiSearch/contentSearch.feature
tests/acceptance/features/bootstrap/SearchContext.php
tests/acceptance/features/bootstrap/WebDav.php

This PR adds test for searching content across files with different formats
- part of: https://github.com/owncloud/ocis/issues/6606
- locally
- CI

[tests-only][full-ci]Add test for searching content across files with different format with search text highlight

---

tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature
tests/acceptance/features/bootstrap/OcisConfigContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

[test-only] ApiTest. test for password policy

---

docs/templates/ADOC_global.tmpl
services/postprocessing/README.md
tests/acceptance/features/bootstrap/OcisConfigContext.php

Use `OCIS_ASYNC_UPLOADS` because `STORAGE_USERS_ASYNC_UPLOADS` is gone

[tests-only] Use OCIS_ASYNC_UPLOADS in docs

---

.drone.star

The deployments configs were already removed with commit 84381750f0e5d. So let's cleanup the drone steps as well.

Remove the hello and parallel deployments from drone config

---

.drone.star

We use different oCIS setup for different tests like cs3api, wopi and acceptance tests (local and core api, e2e and acceptance webUI). cs3api and wopi need special oCIS envs to be set. This PR separates those envs and set only if application to the requires setup.
Removed envs (Some are defaults, some are not available and use defaults for some):
```bash
"STORAGE_USERS_DRIVER_LOCAL_ROOT": "%s/local/root" % dirs["ocis"]        (Not available)
"STORAGE_USERS_DRIVER_OCIS_ROOT": "%s/storage/users" % dirs["ocis"]      (Not available)
"STORAGE_SYSTEM_DRIVER_OCIS_ROOT": "%s/storage/metadata" % dirs["ocis"]  (Not available)
"SHARING_USER_JSON_FILE": "%s/shares.json" % dirs["ocis"]                (Use default)
"SETTINGS_DATA_PATH": "%s/settings" % dirs["ocis"]                       (Use default) …
```

[ci][full-ci] Use only necessary envs for different ocis setup

---

tests/ociswrapper/cmd/cmd.go
tests/ociswrapper/ocis/config/config.go
tests/ociswrapper/ocis/ocis.go

Instead of just sending request to server's base url, we now send request to get admin user information to check whether ocis is ready or not

[full-ci][ociswrapper] Check ocis connection by requesting user info

---

tests/ociswrapper/log/log.go
tests/ociswrapper/ocis/ocis.go
tests/ociswrapper/wrapper/handlers/handler.go

Improves:
- restart ocis server if it exists with error during startup
- do not panic if the process is already finished while stopping the process
- mark server ready if the server sends the response
Part of https://github.com/owncloud/ocis/issues/6850

[tests-only][ociswrapper] Fix oCIS restart when it exits unexpectedly during startup

---

changelog/unreleased/fix-jsoncs3-share-manager-migration.md
ocis/pkg/command/migrate.go

This PR fixes a problem with the "ocis migrate rebuild-jsoncs3-indexes" command which reset the state of received shares to "pending".
Fixes https://github.com/owncloud/ocis/issues/7319

Do not reset share state

---

changelog/unreleased/improve-sses.md
services/clientlog/pkg/service/events.go
services/clientlog/pkg/service/service.go
services/sse/pkg/service/service.go

Improves SSE notifications format to fulfill the needs of the web client

Improve SSE Notifications

---

tests/acceptance/features/bootstrap/NotificationContext.php

- Given steps
So this pr make the above changes in `NotificationContext`
- locally
- CI

[tests-only][full-ci] removing the setresponse in given/when/then step in Notification Context

---

tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/SettingsContext.php
tests/acceptance/features/bootstrap/SpacesTUSContext.php
tests/acceptance/features/bootstrap/TUSContext.php

- Given steps
So this pr make the above changes in `SettingContext` and `TUSContext`
- locally
- CI

[tests-only][full-ci] removing the setresponse in given/then step in SettingContext and TUSContext

---

changelog/unreleased/do-not-reset-received-share-state.md
ocis/pkg/command/migrate.go

Backport fix for https://github.com/owncloud/ocis/issues/7319

Do not reset received share state to pending if there is a state already

---

tests/acceptance/features/apiSpacesDavOperation/propfindByFileId.feature

This PR adds tests for the `PROPFIND` request to a file not by its name but by its `file-id` in the spaces `dav-path-url`.
https://github.com/owncloud/ocis/issues/6737

[tests-only][full-ci]Added test for the `propfind` with `file-id`

---

services/graph/pkg/identity/cs3.go

reva never uses `groupid`. actually only the ldap group manager knows about `group_id`. the fixme makes a little funny.

fix group id claim

---

tests/acceptance/features/apiSpacesDavOperation/propfindByFileId.feature

Backport of PR : https://github.com/owncloud/ocis/pull/7335

[tests-only][full-ci]Backport propfind by fileid

---

changelog/unreleased/dont-reload-web-config.md
services/web/pkg/service/v0/service.go

Doesn't reload the webconfig file on request because this invalides envvars

Dont reload Webconfig on request

---

changelog/unreleased/fix-graph-education-createschool.md
services/graph/pkg/identity/ldap_education_class_test.go
services/graph/pkg/identity/ldap_education_school.go
services/graph/pkg/identity/ldap_education_school_test.go
services/graph/pkg/identity/ldap_education_user_test.go
services/graph/pkg/identity/ldap_group_test.go
services/graph/pkg/identity/ldap_test.go
services/graph/pkg/service/v0/educationschools.go
services/graph/pkg/service/v0/errorcode/errorcode.go

Fixes https://github.com/owncloud/enterprise/issues/6051
Also contains a few minor cleanups. E.g. to make returned errors more consistent.

graph/education: Check school number for duplicates before adding a school

---

changelog/unreleased/fix-graph-education-createschool.md
services/graph/pkg/identity/ldap_education_class_test.go
services/graph/pkg/identity/ldap_education_school.go
services/graph/pkg/identity/ldap_education_school_test.go
services/graph/pkg/identity/ldap_education_user_test.go
services/graph/pkg/identity/ldap_group_test.go
services/graph/pkg/identity/ldap_test.go
services/graph/pkg/service/v0/educationschools.go
services/graph/pkg/service/v0/errorcode/errorcode.go

This cherry-picks #7351 into stable/4.0

[Backport/4.0] graph/education: Check school number for duplicates before adding a school

---

services/policies/README.md

Adds more info about a denied error response in the proxy policies middleware
- Related https://github.com/owncloud/enterprise/issues/6037
- test case 1:
- test case 2:
- ...

[docs-only] Add denied error body to docs

---

changelog/unreleased/sse-scalability.md
services/sse/pkg/command/server.go
services/sse/pkg/server/http/server.go

There is a technical issue when running multiple `sse` service instances.
Consider running two `sse` instances `A` and `B`. When calling `/sse` endpoint you will be connected to one of them, let's say `A`. But when an event happens only one of the services will get it, because they are both in the same consumer group. If service `B` gets the event it will not be able to send a message to the client because the `sse` library we are using is storing connections in memory (which makes sense because there is no need to persist them).
This PR adds unique consumer groups to each `sse` service. This way all services will get all events and can therefore always transmit the message to the client.

SSE Scalability

---

tests/acceptance/features/bootstrap/NotificationContext.php

This pr backports  https://github.com/owncloud/ocis/pull/7324 from master to stable-4.0

[tests-only][full-ci] backport refactoring the setresponse in given/then step in notification context

---

.drone.star
docs/ocis/development/testing.md
tests/acceptance/docker/src/acceptance.yml
tests/acceptance/run.sh

Now core tests have been transferred to ocis repo so we don't need `TEST_OCIS` and `RUN_ON_OCIS` env. So removing `TEST_OCIS` and `RUN_ON_OCIS`
- Fixes https://github.com/owncloud/ocis/issues/7300
- Locally

[docs-only]Remove deprecated env

---

tests/acceptance/features/bootstrap/OCSContext.php
tests/acceptance/features/bootstrap/ShareesContext.php
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/WebDavLockingContext.php

- Given steps
So this pr make the above changes in `OCSContext` and `WebDavLockingContext`
- locally
- CI

[tests-only] removing the setresponse in given/when/then step in ocs and webdavlocking context

---

tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
tests/acceptance/features/bootstrap/SpacesContext.php

This PR adds test coverage for moving/renaming the files within personal space with the `url` consisting of the `file-id` not name.
This PR adds moving/renaming with file id only within `Personal` Space
https://github.com/owncloud/ocis/issues/6737

[tests-only]Added test for the `move` with file-id in `web-dav-url`

---

.drone.env
services/web/Makefile

Brings current web master to ocis (and hopefully fix https://github.com/owncloud/web/issues/9742).

[full-ci] chore: bump web to v8.0.0-alpha.3

---

tests/acceptance/features/apiSpacesShares/shareOperations.feature
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/WebDav.php
tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
tests/acceptance/features/coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature
tests/acceptance/features/coreApiWebdavProperties1/createFileFolder.feature
tests/acceptance/features/coreApiWebdavProperties2/getFileProperties.feature

- Given steps
So this pr make the above changes in `WebdavPropertiesContext`
- locally
- CI

[tests-only] removing the setresponse in given/when/then step in webdavproperties context

---

changelog/unreleased/bump-reva.md
changelog/unreleased/delete-outdated-userlog-events.md
go.mod
go.sum
services/userlog/pkg/service/http.go
vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocdav/copy.go
vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocdav/move.go
vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocdav/ocdav.go
vendor/github.com/cs3org/reva/v2/pkg/utils/grpc.go
vendor/modules.txt

Deletes outdated userlog events
Fixes https://github.com/owncloud/ocis/issues/6773

[full-ci] Delete userlog events

---

.drone.star
changelog/unreleased/enhancement-notifications-auto-auth-settings.md
changelog/unreleased/fix-notifications-redundant-settings.md
services/notifications/pkg/channels/channels.go
services/notifications/pkg/config/config.go
services/notifications/pkg/config/defaults/defaultconfig.go
services/notifications/pkg/config/parser/parse.go

This makes a couple changes to the Mail client configuration of the notifications service
- automatically pick a suitable auth mechanism
- deprecate some redundant setting of the encryption config
- remove some not really helpful default settings of the config
Please specifically review the deprecation notice. As were not deprecating a whole config variable but just specific configuration settings.
Closes: #7356 #7345

notifcations: Sanitize SMTP configuration

---

tests/TestHelpers/HttpRequestHelper.php
tests/acceptance/features/apiNotification/emailNotification.feature
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/WebDav.php

- Refactored share methods so that they do only the creation requests.
- Refactored Given/Then step defs and methods to not save response
- Removed used steps (related to share creation)
- Fixes https://github.com/owncloud/ocis/issues/7393 :crossed_fingers:

[tests-only] Fix share creation methods

---

tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature

This PR adds test coverage for copying the files within project space with the `url` consisting of the `file-id` not name.
This PR adds copying with file id only within `Project` Space

[tests-only][full-ci]add test for copy with fileID

---

tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature

This PR adds test coverage for moving the files within project space with the `url` consisting of the `file-id` not name.
This PR adds moving with file id only within `Project` Space

[tests-only][full-ci]add test for move with fileID in project space

---

changelog/unreleased/default-language.md
services/settings/README.md
services/settings/pkg/command/server.go
services/settings/pkg/config/config.go
services/settings/pkg/server/grpc/option.go
services/settings/pkg/server/http/option.go
services/settings/pkg/service/v0/service.go
services/settings/pkg/service/v0/servicedecorator.go
services/settings/pkg/settings/settings.go
services/settings/pkg/store/defaults/defaults.go

- Fixes [https://github.com/owncloud/enterprise/issues/5915](https://github.com/owncloud/enterprise/issues/5915)
- test environment: Local.
- Please fist read the notice in a readme!
- test case 1: Set SETTINGS_DEFAULT_LANGUAGE=de, run ocis. Log in as admin, the UI language has to be DE. admin creates a file and shares it with einstein. 
Expected result: 
- If einstein did change a language in a setting to a language different from DE then einstein would receive a letter in DE.
- If einstein already changed a language in a setting to language then einstein would receive a letter in selected language. But not all languages that we can see in a setting already exist for email notifications! If the language exits for UI but not exist for the email notifications then email notifications fail …

the default language added to the setting service

---

ocis-pkg/registry/register.go
ocis-pkg/service/debug/option.go
ocis-pkg/service/debug/service.go
services/storage-users/pkg/command/server.go
services/storage-users/pkg/event/service.go
services/storage-users/pkg/server/debug/server.go

This contains some smaller cleanups to prepare for a more graceful shutdown of the storage-users service. The main context is now passed to all members of the run.Group so that e.g. the event handler's service runner and the debugServer are properly be stopped.
This also fixes a bug when de-registering a service which could keep the ServerRegister go-routine running in a tight loop when the context was canceled.
This does not provide a complete fix for a proper shutdown of storage-users.  More changes are coming via the reva repo.

storage-users:  cleanups and preparation for allowing cleaner shutdown

---

tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature

This PR is backport of master PR https://github.com/owncloud/ocis/pull/7421

[tests-only][full-ci] Backport add test for move with fileID in project space (#7421)

---

tests/acceptance/features/apiAntivirus/antivirus.feature
tests/acceptance/features/apiSpaces/publicLink.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/TrashbinContext.php
tests/acceptance/features/bootstrap/WebDav.php
tests/acceptance/features/coreApiSharePublicLink2/multilinkSharing.feature
tests/acceptance/features/coreApiWebdavUpload1/uploadFile.feature

- Given steps
So this pr make the above changes in `WebdavContext`
- locally
- CI

[tests-only] [full-ci] removing the setresponse in given/then step in webdav context

---

docs/services/general-info/port-ranges.md
services/auth-service/pkg/config/defaults/defaultconfig.go

Adds the missing auth service to the port-ranges.md

[docs-only] Add `auth-service` to `port-ranges.md`

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/bootstrap/WebDav.php
tests/acceptance/features/coreApiWebdavPreviews/previews.feature

This PR implements the previewing of shared files using the spaces WebDav. For `spaces` DAV path, getting preview or uploading content on shared resource requires `mount point id`. Method to get mount point id `getMountPointId` is added and used for previewing the shared resources.
- Part of https://github.com/owncloud/ocis/issues/6752

[tests-only][full-ci] added test for previewing shared resource using spaces dav version

---

ocis-pkg/service/grpc/option.go
ocis-pkg/service/grpc/service.go
services/eventhistory/pkg/server/grpc/option.go
services/eventhistory/pkg/server/grpc/server.go
services/search/pkg/server/grpc/option.go
services/search/pkg/server/grpc/server.go
services/settings/pkg/server/grpc/option.go
services/settings/pkg/server/grpc/server.go
services/store/pkg/server/grpc/option.go
services/store/pkg/server/grpc/server.go
services/thumbnails/pkg/server/grpc/option.go
services/thumbnails/pkg/server/grpc/server.go

This PR removes leftovers from the old cli options.
refs #4088

remove obsolete cli flags

---

services/frontend/pkg/revaconfig/config.go

Set an empty Credentials chain. In ocis all non-reva token authentication is
handled by the proxy. This avoid irritating error messages about the missing
'auth-bearer' service.
Fixes: #6692

Fix reva config of frontend service to not try to contact auth-bearer

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiNotification/emailNotification.feature
tests/acceptance/features/apiNotification/notification.feature

test for ne env: see here https://github.com/owncloud/ocis/pull/7417

[test-only] Api-test. added test for default language

---

tests/acceptance/features/bootstrap/SpacesTUSContext.php

- Given steps
So this pr make the above changes in `SpacesTusContext`
- locally
- CI

[tests-only] [full-ci] removing the setresponse in given/then step in spacestus context

---

changelog/unreleased/bump-reva.md
changelog/unreleased/fix-users-by-claim-lookup-binary-uuid.md
go.mod
go.sum
vendor/github.com/cs3org/reva/v2/pkg/trace/trace.go
vendor/github.com/cs3org/reva/v2/pkg/utils/ldap/identity.go
vendor/modules.txt

To get https://github.com/cs3org/reva/pull/4249
Fixes: #7469

Bump reva to latest edge

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/bootstrap/WebDav.php
tests/acceptance/features/coreApiWebdavPreviews/previews.feature

This PR forward port: https://github.com/owncloud/ocis/pull/7234

[tests-only][full-ci] Forwardport added test coverage for previewing shared resources using spaces dav path

---

changelog/unreleased/bump-reva.md
changelog/unreleased/set-mountpoint-on-autoaccept.md
services/frontend/pkg/command/events.go
tests/ociswrapper/cmd/cmd.go

Sets the mountpoint when auto accepting shares
Fixes https://github.com/owncloud/ocis/issues/7441
Fixes https://github.com/owncloud/ocis/issues/7440
also fixes a race condition in the ocis wrapper

[full-ci] Set mountpoints when auto accepting shares

---

tests/acceptance/features/apiAntivirus/antivirus.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/TrashbinContext.php
tests/acceptance/features/bootstrap/WebDav.php
tests/acceptance/features/coreApiSharePublicLink2/multilinkSharing.feature
tests/acceptance/features/coreApiWebdavUpload1/uploadFile.feature

This pr backports https://github.com/owncloud/ocis/pull/7403 from master to stable-4.0

[tests-only][full-ci] Backport refactoring webdav context removing setresponse() in given/then step

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
tests/acceptance/features/bootstrap/PublicWebDavContext.php
tests/acceptance/features/bootstrap/WebDavLockingContext.php
tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
tests/acceptance/features/coreApiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature

- Given steps
So this pr make the above changes in `PublicWebdavContext`
- locally
- CI

[tests-only] [full-ci] removing the setresponse in given/then step in publicwebdav context

---

changelog/unreleased/disabled-web-extensions-config.md
services/web/pkg/config/options.go

Adds a new config for disabling specific Web extensions via their id.
See https://github.com/owncloud/web/pull/9800.

feat: add config for disabling web extensions

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
tests/acceptance/features/bootstrap/PublicWebDavContext.php
tests/acceptance/features/bootstrap/WebDavLockingContext.php
tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
tests/acceptance/features/coreApiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature

This pr backports https://github.com/owncloud/ocis/pull/7439 from master to stable-4.0

[tests-only] [full-ci] backport refactor publicwebdav context removing setresponse in given/then steps

---

services/proxy/pkg/middleware/authentication.go
services/proxy/pkg/proxy/proxy.go
services/proxy/pkg/router/router.go
services/proxy/pkg/router/router_test.go

With Go 1.20 the "Rewrite" hook for ReverseProxy was introduced to supersede of the "Director" hook (see:
https://github.com/golang/go/commit/a55793835f16d0242be18aff4ec0bd13494175bd)
The Rewrite hooks allows for better separation between the incoming and outgoing request. In particular it makes it pretty easy to set the  correct X-Forwarded-* Headers on the outgoing request.  The need for using "Rewrite" came up when trying to embed authelia. It uses the X-Forwarded-Host and X-Forwared-Proto headers to e.g. compute the correct return values for the various endpoints in .well-known/openid-configuration.
Note: This commit is outcome of the prove of concept work on embedding authelia into ocis: https://github.com/rhafer/ocis/tree/authelia-experiment but I think it is useful on its own.

proxy: User ReverseProxy.Rewrite instead of Director

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/apiGraph/addUserToGroup.feature
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/Provisioning.php
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature

This PR refactors the user addition to group test code from ocs api to graphapi
- Part of https://github.com/owncloud/ocis/issues/6998
- locally
- ci

[tests-only][full-ci] refactoring user addition to group to graphapi

---

tests/acceptance/features/apiNotification/emailNotification.feature
tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

- Given steps
So this pr make the above changes in `SpacesContext`
- locally
- CI

[tests-only] [full-ci] removing the setresponse in given/then step in spaces context

---

changelog/unreleased/fix-default-mail-language-fallback.md
services/notifications/README.md
services/notifications/pkg/command/server.go
services/notifications/pkg/config/config.go
services/notifications/pkg/email/composer.go
services/notifications/pkg/email/email.go
services/notifications/pkg/email/l10n/locate.go
services/notifications/pkg/service/service.go
services/notifications/pkg/service/service_test.go
services/settings/README.md
services/settings/pkg/config/config.go
services/userlog/README.md
services/userlog/pkg/config/config.go
services/userlog/pkg/service/conversion.go
services/userlog/pkg/service/http.go
services/userlog/pkg/service/service.go
tests/acceptance/features/apiNotification/emailNotification.feature
tests/acceptance/features/apiNotification/notification.feature

Added the global variable OCIS_DEFAULT_LANGUAGE. Now `settings`, `notification`, and `userlog` services support the default language fallback.
The `OCIS_DEFAULT_LANGUAGE` impacts depend on existing translation.
These changes are needed because if the transaction does not exist for notification or userlog services we want to fall down to the OCIS_DEFAULT_LANGUAGE first and after that to the English
- Fixes [https://github.com/owncloud/ocis/issues/7465](https://github.com/owncloud/ocis/issues/7465)
- test case 1:
- test case 2:
- ...

fix default language fallback

---

tests/acceptance/features/apiNotification/emailNotification.feature
tests/acceptance/features/apiSpaces/changeSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

This pr backports https://github.com/owncloud/ocis/pull/7496 from master to stable-4.0

[tests-only] [full-ci] backport refactor spaces context remove setting response in given/then steps

---

changelog/unreleased/fix-too-early-preview-request.md
services/webdav/pkg/service/v0/service.go

Fix the status code and message when a thumbnail request is made too early.
For `old`/`new`/`spaces` endpoints.
**Current:**
```xml
< HTTP/1.1 500 Internal Server Error
< 
<?xml version="1.0" encoding="UTF-8"?>
<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns">
<s:exception></s:exception>
<s:message>
{&#34;id&#34;:&#34;com.owncloud.api.thumbnails&#34;,&#34;code&#34;:425,&#34;detail&#34;:&#34;File Processing&#34;,&#34;status&#34;:&#34;Too Early&#34;}
</s:message>
</d:error>
```
**With Fix:**
```xml
< HTTP/1.1 425 Too Early
< 
<?xml version="1.0" encoding="UTF-8"?>
<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns">
<s:exception></s:exception>
<s:message>File Processing</s:message>
</d:error>
```
- Fixes https://github.com/owncloud/ocis/issues/7502
- Closes …

fix: request to preview gives 500 error for old/new webdav if file is in processing

---

.drone.star
changelog/unreleased/fix-docs-pipeline.md

Hopefully fixes nasty `403` errors in docs pipeline
Fixes https://github.com/owncloud/ocis/issues/7509

Pass docs pipeline requests through proxies

---

services/frontend/README.md

Add capabilities docs to frontend service.
- test case 1:
- test case 2:
- ...

[docs-only] add capabilities docs for password policy

---

.drone.env
services/web/Makefile
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature

Includes the recent changes to the preview rendering.

[full-ci] chore: bump web to v8.0.0-alpha.4

---

changelog/unreleased/fix-auth-service-jwt.md
services/auth-service/pkg/config/reva.go

fix the auth service env variable to the service specific name. Before it was configurable via `AUTH_MACHINE_JWT_SECRET` and now is configurable via `AUTH_SERVICE_JWT_SECRET`.
Consistent env variable naming
- not tested other than CI

fix auth service env variable

---

docs/ocis/adr/0023-index-and-store-metadata.md

[Rendered](https://github.com/owncloud/ocis/blob/adr-metadata/docs/ocis/adr/0023-index-and-store-metadata.md#store-everything-from-extractors)
See also #7490

[docs-only][ADR] Index and store metadata

---

.drone.star
Makefile
sonar-project.properties

Try to run linter and unit test from top-level directory
Instead of starting a separate pipeline for each service we now just run the linter and unit tests from the top-level directory. This allows us to run the linter it with '--modules-download-mode vendor' and should also reduce the resource usage.
Also remove some unused code.

[full-ci] Try to run linter and unit test from top-level

---

changelog/unreleased/add-last-modified-filter-chip.md
services/frontend/pkg/revaconfig/config.go
services/search/pkg/query/kql/cast.go
services/search/pkg/query/kql/dictionary.peg
services/search/pkg/query/kql/dictionary_gen.go
services/search/pkg/query/kql/dictionary_test.go

- [https://github.com/owncloud/ocis/issues/7431](https://github.com/owncloud/ocis/issues/7431)
- test case 1:
- test case 2:
- ...

add last modified filter chip

---

tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature

This PR adds the test for copying the files betweeen project space and personal space with the `url` consisting of the `file-id` not name

[tests-only][full-ci]add test for copy file between project and personal space

---

services/frontend/pkg/config/config.go
services/notifications/pkg/config/config.go

This is a small PR using semicolons instead of commas when there are multiple envvars for the same task allowed.
The reason to fix this is that the ocis docs helper creating the envvar adoc table separates via semicolons only but not commas. When using commas, it creates a loooong single string instead two strings separated by line breakes.
There is no impact for the ocis code itself.
We should btw document this in the dev docs for envvars.
@2403905 fyi

[docs-only] Use semicolon instead of comma separating envvars

---

tests/acceptance/features/apiNotification/spaceNotification.feature
tests/acceptance/features/apiSpaces/listSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php

Added test for getting virtual shares information for when the user has a pending share 
- Fixes: https://github.com/owncloud/ocis/issues/7471
To provide test coverage for https://github.com/owncloud/ocis/issues/7160. According to the issue the etag of the virtual share drive wasn't provided when there was a pending share, so this is the test coverage to ensure that regression is caught. 
- Locally
- CI

[tests-only][full-ci]Adds test for getting share jail space information of the user when user has pending share

---

.drone.star

Might reduce failure like https://drone.owncloud.com/owncloud/ocis/27980/49/3
```bash
go: downloading google.golang.org/genproto v0.0.0-20220112215332-a9c7c0acf9f2
/go/pkg/mod/google.golang.org/grpc@v1.43.0/status/status.go:35:2: google.golang.org/genproto@v0.0.0-20220112215332-a9c7c0acf9f2: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20220112215332-a9c7c0acf9f2.zip: 403 Forbidden
make: *** [../.bingo/Variables.mk:72: /go/bin/mutagen-v0.13.1] Error 1
```

[ci][full-ci] use drone http proxy where go-image is used

---

changelog/unreleased/storage-registry-envvar-config.md
services/gateway/pkg/config/config.go

Allows configuring the storage registry in the gateway service using envvars

Allow configuring storage registry with envvars

---

tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
tests/acceptance/features/coreApiTrashbin/trashbinSharingToShares.feature
tests/acceptance/features/coreApiVersions/fileVersionAuthor.feature

related https://github.com/owncloud/ocis/issues/7555
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature:462 is flaky
I run it some times and get different result. I skip this test to don't unexpected failures unexpected success in CI

[test-only] skip tests moving between shares jail

---

changelog/unreleased/enhancement-search-content-extraction-cleanup.md
services/search/README.md
services/search/pkg/config/content.go
services/search/pkg/config/defaults/defaultconfig.go
services/search/pkg/content/content.go
services/search/pkg/content/content_test.go
services/search/pkg/content/tika.go
services/search/pkg/content/tika_test.go

So far it has not been possible to determine whether
the content for the search should be cleaned of stop words or not.
This can now be set with the newly introduced settings option `SEARCH_EXTRACTOR_TIKA_CLEAN_STOP_WORDS=false`
which is enabled by default.
In addition, the stop word cleanup is no longer as aggressive and now ignores numbers, urls,
basically everything except the defined stop words.
- Fixes https://github.com/owncloud/ocis/issues/6674
..., no bugs, ... yummy
- unit tests

enhancement: improve content extraction stop word cleaning

---

services/ocm/pkg/config/config.go

Make the ocm env vars consistent with the rest of ocis.

Streamline ocm env vars

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiSearch/contentSearch.feature

related https://github.com/owncloud/ocis/issues/6674
added test for searching on some words or characters

[test-only] increase test coverage for content search

---

changelog/unreleased/fix-mountpoint-autoaccept.md
services/frontend/pkg/command/events.go

When already having a share for a specific resource, auto accept would use custom mountpoints which lead to other errors. Now auto-accept is using the existing mountpoint of a share.
Fixes: https://github.com/owncloud/ocis/issues/7541

Reuse existing mountpoints on auto accept

---

changelog/unreleased/423-on-tag-create.md
services/graph/pkg/service/v0/tags.go

Returns `423` instead `500` when trying to create a tag on a locked file 
Fixes https://github.com/owncloud/ocis/issues/7590

Return 423 on tag create when file is locked

---

tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

This PR adds the test for copying the files of shares space with the `url` consisting of the `file-id` not name
In this PR following scenario are added:
- Copy a file from sub-folder to root inside share space

[tests-only][full-ci] add tests for copy file within shares using file-id

---

tests/acceptance/config/behat.yml
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/lockFiles.feature
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/WebDavLockingContext.php

related #7561
We have lock test which we moved from core repo. Out of 98 scenarios related to locking, only 6 of them work. 
and the existing tests can't: 
- set a timeout
- work in project space
- use space dav
- no tests that check if the lock expires
I created first PR where: 
found issue: 
- https://github.com/owncloud/ocis/issues/7599
- https://github.com/owncloud/ocis/issues/7600
next test, next PRs: 
- unlock file
- check if the lock expires

[test-only] new lock tests

---

.drone.env
changelog/unreleased/bump-web-7.1.1.md
services/web/Makefile

Bumps Web to `v7.1.1`. This includes the following fixes:
* Bugfix [owncloud/web#9833](https://github.com/owncloud/web/pull/9833): Resolving external URLs

chore: bump web to v7.1.1

---

tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/SpacesContext.php

This PR is backport of master PR https://github.com/owncloud/ocis/pull/7593

[tests-only][full-ci] Backport add tests for copy file within shares using file-id

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/Provisioning.php
tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature

This PR refactors the user deletion test code from provisioning to graphapi
- Part of https://github.com/owncloud/ocis/issues/6998
- locally
- ci

[tests-only][full-ci] refactoring the user delete code from ocs to graphapi

---

tests/acceptance/features/apiSearch/dateSearch.feature
tests/acceptance/features/bootstrap/SpacesTUSContext.php

Skipping search using `Mtime: "last month"` test until issue https://github.com/owncloud/ocis/issues/7629 is fixed. Didn't find any solution to it from test code.
Unblocks the CI.

[tests-only] skip search by last month test

---

tests/acceptance/features/apiSearch/apiSpaceSearch.feature

This PR adds tests for searching for resources with white space in its name
- Fixes: https://github.com/owncloud/ocis/issues/7552
- locally
- ci

[tests-only][full-ci]Add tests for searching for resources with whitespace chars in its name

---

tests/acceptance/config/behat.yml
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpaces/lockFiles.feature
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/WebDavLockingContext.php

This PR backports https://github.com/owncloud/ocis/pull/7595

[test-only] [full-ci] Backport lock tests 

---

tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature

This PR adds the test for copying the files betweeen personal space and Shares space with the `url` consisting of the `file-id` not name

[tests-only][full-ci] Add test for copy file between personal space and share space using fileID

---

tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature

This PR is the backport of master PR https://github.com/owncloud/ocis/pull/7627

[tests-only][full-ci] Backport add test on copy between file id share space and personal space

---

.drone.star
tests/acceptance/check-deleted-suites-in-expected-failure.sh

This PR adds a pipeline that checks whether there are the tests scenarios in the expected failure files that is in the tests suites inside `/features`.
https://github.com/owncloud/web/issues/9778

[tests-only][full-ci]Added script to check the deleted suites in the expected to failure

---

tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature

This PR adds the test for copying the file between spaces in project space with the `url` consisting of the `file-id` not name

[tests-only][full-ci] Add test for copy file between project spaces

---

services/graph/pkg/service/v0/driveitems.go
services/graph/pkg/service/v0/educationclasses_test.go
services/graph/pkg/service/v0/service.go
services/graph/pkg/service/v0/sharedbyme.go
services/graph/pkg/service/v0/sharedbyme_test.go

This adds a (still incomplete) implementation of the new /me/drives/sharedByMe endpoint. 
Still missing / clarifications needed:
IMO the open items should be tackled in follow-up pull-request. To keep this PR from growing to big.

Initial implementation of /me/drives/sharedByMe endpoint

---

services/web/pkg/config/options.go

References: #7486 (feat: add config for disabling web extensions)
@JammingBen some questions:
* As written in plural, how to separate multiple ID's?
By blank as usual?
* As one needs to enter ID's, how does he be able to identify or get an ID?
* We name `Web extensions`. Can you explain?
Knowing this, we can further improve the text.

[docs-only] Fix web service envvar text

---

services/thumbnails/README.md

References: #7409 (feature(thumbnails): add the ability to define custom image processors)
The `Thumbnail Processor` section needed an update to clarify the usecase and behaviour. In addition, the list of sizes above now shows as in a single line each and not in one line.

[docs-only] Text fix for thumbnail README.md

---

.drone.star
changelog/unreleased/natsjs-registry.md
go.mod
go.sum
ocis-pkg/natsjsregistry/options.go
ocis-pkg/natsjsregistry/registry.go
ocis-pkg/registry/registry.go
ocis/pkg/runtime/service/service.go
vendor/github.com/go-micro/plugins/v4/store/nats-js/context.go
vendor/github.com/go-micro/plugins/v4/store/nats-js/nats.go
vendor/github.com/go-micro/plugins/v4/store/nats-js/options.go
vendor/modules.txt

Introduces  a natsjs based registry
Basic functionality works, but breaking bug:
To use natsjs based registry:
```bash
export MICRO_REGISTRY=natsjs # set natsjs as registry
export MICRO_REGISTRY_ADDRESS="127.0.0.1:9233" # set address for nats
```

Natsjs registry

---

tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature

This PR is bacport of master PR https://github.com/owncloud/ocis/pull/7647

[tests-only][full-ci] Backport add test on copy between spaces in project spaces

---

services/frontend/pkg/config/config.go
services/frontend/pkg/config/defaults/defaultconfig.go
services/frontend/pkg/revaconfig/config.go

Expose variable (`list_ocm_shares`, `FRONTEND_OCS_LIST_OCM_SHARES`) to enable/disable the listing of ocm shares.

Expose variable to enable/disable the listing of ocm shares

---

services/graph/pkg/service/v0/service.go

Fix url path for getsharedbyme

---

services/graph/pkg/identity/backend.go
services/graph/pkg/identity/cache.go
services/graph/pkg/identity/cs3.go
services/graph/pkg/service/v0/drives.go
services/graph/pkg/service/v0/graph.go
services/graph/pkg/service/v0/service.go
services/graph/pkg/service/v0/sharedbyme.go

This makes the  user and group lookup cache in drives.go re-usable so that it e.g. graph/sharedbyme can use it as well.

graph: reuse user- and group cache in graph/sharedbyme

---

services/audit/pkg/config/config.go

References: https://github.com/owncloud/docs-ocis/pull/657 (Improve the description of the audit service)
While working on the above PR, it turned out that some audit envvar descriptions need to be precised/corrected.
@dragonchaser as discussed

[docs-only] Fix some Audit envvar description texts

---

changelog/CHANGELOG.tmpl

References: #7691 ([docs-only] add toc to changelog)
After checking the outcome for the part where we have a text as date field, it turned out that the required casing for markdown was wrong. This is already corrected in the other repos.
* link created: `changelog-for-unreleased-UNRELEASED`
* link required: `changelog-for-unreleased-unreleased`

[docs-only] fix changelog template for the date field

---

services/ocm/pkg/config/config.go

References: https://github.com/owncloud/docs-ocis/pull/658 (Add the OCM service)
Fixes the OCM envvar descriptions as they have not been covered by the other cleanup and harmonisation processes.

[docs-only] Fix ocm service envvar descriptions

---

services/web/pkg/config/config.go
services/web/pkg/config/defaults/defaultconfig.go

Adds a config option for the `loadUserInfo` property of the ocis web oidc client. For AD FS this must be set to false because that idp is ... picky and will not return userinfo ... for whatever reason.
@kulmann I think we can omit that request completely, because web sibsequently makes graph api calls to fetch user metdadata. So we could default it to `false` instead of the current `true`.
Allows setting an ENV var to make AD FS support in the helm charts more manageable, see https://github.com/owncloud/ocis-charts/issues/425

allow configuring loadUserInfo for web

---

services/ocm/README.md

There is a typo in the `providers.json` example. `https://example.com.com` --> `https://example.com`

[docs-only] Typo fix in OCM service example

---

tests/acceptance/features/bootstrap/TagContext.php

Listing tags immediately after creating one or deleting one might not return the desired result. So, we are waiting for some seconds in the test so that search indexing can complete and then do the tags listing.
This should reduce the frequent flakiness of the tags API tests that we are facing currently in the CI.
- Fixes https://github.com/owncloud/ocis/issues/7693

[tests-only] wait for few seconds before listing tags

---

tests/acceptance/features/apiNotification/notification.feature

`enum` was misspelled and because of that not used
The whole test only checked for `string` type.
After fixing the typo I understood that `%user_id%` is the wrong thing in the first place. `%user_id%` is substituted to the requesting user, but in this case its the id of the user that initiated the share
that check does not work with that type
:robot:

fix typo in test

---

tests/acceptance/features/bootstrap/SearchContext.php

Increase wait time before doing search request
- Fixes https://github.com/owncloud/ocis/issues/7694

[tests-only] wait 5 seconds before performing search

---

services/graph/pkg/service/v0/rolemanagement.go
services/graph/pkg/service/v0/sharedbyme.go
services/graph/pkg/service/v0/sharedbyme_test.go
services/graph/pkg/unifiedrole/unifiedrole.go
services/graph/pkg/unifiedrole/unifiedrole_suite_test.go
services/graph/pkg/unifiedrole/unifiedrole_test.go

Try to map CS3 resource permissions on a share to one of the default libregraph
UnifiedRoleDefinitions. If a match if found return the roleid in 'permissions.roles'
attribute of the response. If no match if found convert the
ResourcePermissions in to `libre.graph.permissions.actions` and return
those in the response.

graph: Set roles/actions in `sharedByMe` response

---

tests/acceptance/features/apiSearch/dateSearch.feature

Unskip  API test: date search with lastmonth filter
Fixed issue https://github.com/owncloud/ocis/issues/7629
revert https://github.com/owncloud/ocis/pull/7631

[tests-only] unskip lastmonth date search API test

---

tests/acceptance/features/apiLocks/unlockFiles.feature
tests/acceptance/features/bootstrap/WebDavLockingContext.php

This PR adds the test for unlocking project space file
- Part of: https://github.com/owncloud/ocis/issues/7625
- Locally
- CI

[tests-only][full-ci] Add test for unlocking project space file

---

services/web/pkg/config/config.go
services/web/pkg/config/defaults/defaultconfig.go

As discussed here https://github.com/owncloud/ocis/pull/7714#issuecomment-1812047910 we're removing the env var for making the LoadUserInfo bool configurable. Reason is that oC Web disabled fetching the userinfo via oidc entirely. There are different endpoints in oCIS where we get all the userinfo, so we want to omit the userinfo request entirely.

revert: don't make loadUserInfo configurable because web disabled it

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature

This PR adds the test for moving the files of shares space with the `url` consisting of the `file-id` not name
In this PR following scenario are added:
- move a file from sub-folder to root inside Shares space

[tests-only][full-ci] Add tests for move file within shares using file-id

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/Provisioning.php
tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature

This PR backports https://github.com/owncloud/ocis/pull/7020

[tests-only][full-ci] refactoring the user delete code from ocs to graph api

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature

This PR adds the test for moving and renaming the files betweeen project space and personal space with the `url` consisting of the `file-id` not name
In this PR following scenario are added:
- move a file from project to personal space
- move a file from personal to project space
- rename a file and move a file from project space to personal space
- rename a file and move a file from personal space to project space

[tests-only][full-ci] Add tests for move rename file between personal and project space with file id

---

tests/acceptance/features/bootstrap/SettingsContext.php

While listing the user roles via settings API, sometimes the response body is incomplete causing the json decoder to throw an error. This PR has implemented retrying for certain numbers if the response body is not valid json. 
- Fixes https://github.com/owncloud/ocis/issues/6524

[tests-only] Retry listing roles if the response body is invalid

---

.drone.env
changelog/5.0.0_2023-11-08/update-web-8.0.0.md
services/web/Makefile

Includes the latest changes regarding the Web embed mode.

chore: bump web to v8.0.0-alpha.10

---

services/settings/pkg/service/v0/settings.go
services/settings/pkg/store/defaults/defaults.go

This PR adds languages to the list of accepted languages which have 70% or more translation coverage in transifex + Swedish by request of a community member who promised to help with translations, see https://github.com/owncloud/web/issues/10007 
The reason for this change is that the settings services only persists language codes which are known in the definition of the setting. The user facing changes (available languages in the dropdown of the account page) will happen in web only. Hence I didn't include a changelog item, yet. Will be part of the next web bump then.
- Brought up by https://github.com/owncloud/web/issues/10007 
Make community happy.

feat: add more accepted languages

---

changelog/unreleased/add-user-filter-startswith-and-contains.md
services/graph/pkg/service/v0/users_filter.go

Enhancement: Add user filter startswith and contains
We add two new filters to the user list endpoint. The `startswith` filter allows to
filter users by the beginning of their name. The `contains` filter allows to
filter users by a substring of their name.
refs #5486

add user filter startsWith and contains

---

tests/acceptance/features/apiLocks/lockFiles.feature
tests/acceptance/features/bootstrap/WebDavLockingContext.php

- Part of: https://github.com/owncloud/ocis/issues/7625
- locally
- CI

[tests-only][full-ci]tests: add tests for lock expiration

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/coreApiSharePublicLink2/copyFromPublicLink.feature
tests/acceptance/features/coreApiWebdavOperations/listFiles.feature

This PR adds `@env-config` so the test won't run for Reva.
PR https://github.com/cs3org/reva/pull/4355 will add the tag `@env-config` to the `BEHAT_FILTER_TAGS` list.

[full-ci] [tests-only] Added @env-config tags

---

changelog/unreleased/add-default-link-permission-config.md
services/frontend/pkg/config/config.go
services/frontend/pkg/config/defaults/defaultconfig.go
services/frontend/pkg/revaconfig/config.go

Adds a new config for default link permissions that is being announced via capabilities. It defaults to `1` (= public link with viewer permissions).
Needs a part in reva: https://github.com/cs3org/reva/pull/4358.
- refs https://github.com/owncloud/web/issues/9919

feat: add a config for default link permissions

---

tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature

This PR adds the test for naming and moving the files betweeen personal space and Shares space with the `url` consisting of the `file-id` not name

[tests-only][full-ci] Add test for rename and move the file between personal and share space using fileid

---

changelog/5.0.0_2023-11-22/enhancement-sharing-ng.md
services/graph/pkg/service/v0/driveitems.go
services/graph/pkg/service/v0/driveitems_test.go
services/graph/pkg/unifiedrole/unifiedrole.go
services/graph/pkg/unifiedrole/unifiedrole_test.go
services/graph/pkg/validate/libregraph.go
services/graph/pkg/validate/libregraph_test.go
services/graph/pkg/validate/validate.go
services/graph/pkg/validate/validate_suite_test.go

Up to now the graph beta invitation endpoint made use of the cs3 permission objects (named set aka role). 
With the implementation of the new unified roles the api is now able to use those as described in the [swagger spec](https://owncloud.dev/libre-graph-api/#/drives.permissions/Invite).
* https://github.com/owncloud/ocis/pull/7633
* https://github.com/owncloud/ocis/pull/7686
* https://github.com/owncloud/ocis/pull/7684
* https://github.com/owncloud/ocis/pull/7683
* https://github.com/owncloud/ocis/pull/7239
* https://github.com/owncloud/ocis/pull/7687
* https://github.com/owncloud/ocis/pull/7751
* https://github.com/owncloud/libre-graph-api/pull/112
* https://github.com/owncloud/ocis/issues/7436
* https://github.com/owncloud/ocis/issues/6993
make use of the unified roles as described …

enhancement: make use of unified role for the graph invitation endpoint

---

tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature

This PR adds a `@skipOnReva` tag for the tests that won't run for reva-edge.
https://drone.owncloud.com/cs3org/reva/3469/13/6

[full-ci] [tests-only] Skip test that won't run for reva-edge

---

changelog/unreleased/fix-search-service-init.md
ocis-pkg/config/defaultconfig.go
services/search/pkg/config/parser/parse.go

Fixes a bug with search service crashing on startup because it can't find the jwt secret
Fixes https://github.com/owncloud/ocis/issues/7757

Init search service correctly

---

tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature

This PR adds the test for naming and moving the files betweeen project space with the `url` consisting of the `file-id` not name

[tests-only][full-ci] Add test for move and rename file between space in project-space

---

tests/acceptance/features/apiDepthInfinity/propfind.feature
tests/acceptance/features/coreApiWebdavOperations/propfind.feature

Extended test coverage for depth:infinity enabled config.
~Blocked until https://github.com/owncloud/ocis/issues/7359~

[tests-only] Extended test coverage for depth:infinity enabled config

---

tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature

This PR is the backpor of master PR https://github.com/owncloud/ocis/pull/7637/files

[tests-only][full-ci] Backport add test for rename and move the file between personal and share space using fileid

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiAntivirus/antivirus.feature
tests/acceptance/features/apiNotification/deprovisioningNotification.feature
tests/acceptance/features/apiNotification/emailNotification.feature
tests/acceptance/features/apiNotification/notification.feature
tests/acceptance/features/apiNotification/spaceNotification.feature
tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/SettingsContext.php

Fixes: https://github.com/owncloud/ocis/issues/7764

[tests-only][full-ci] tests: add api tests for changing system language using graph api

---

services/graph/pkg/service/v0/utils_test.go

This avoids running into the WaitForCA waitloop that is running in with the default (LDAP) identity backend when starting up in a clean environment.

graph unit test: Use mocked identity backend in utils_test

---

services/graph/pkg/service/v0/driveitems.go
services/graph/pkg/service/v0/driveitems_test.go

Don't return 201 on a successful share creation (invite) but 200
https://github.com/owncloud/libre-graph-api/pull/147
get the behavior straight with the API definition
- :robot: 
- running tests of https://github.com/owncloud/ocis-php-sdk/pull/77

return 200 on successful invite

---

services/graph/pkg/service/v0/driveitems.go
services/graph/pkg/service/v0/service.go

I needed a way to create an upload session and checked out how it is done in ms graph. This PR implements a PoC for this.
Unfortunately, the ms graph api can only return a single url while cs3 supports multiple protocols. To work around that I added a `cs3protocols` that can be used to access all possible uploads.
This might help when trying to debug some uploads, because the existing upload methods via TUS or simple PUT do not expose the simple PUT url endpoint, which I was trying to debug.

allow creating an upload session via graph

---

go.mod
go.sum
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/recycle.go
vendor/modules.txt

This PR bumps reva to 2.16.3 to tackle the timeout issues with the trashbins 
refs #7844

Backport trashbin fixes

---

deployments/examples/ocis_keycloak/config/keycloak/clients/cyberduck.json

Cyberduck & Mountain Duck now support WebDAV with OAuth 2.0 / OpenID Connect. Infinite Scale instances can be accessed using [`Connection Profiles`](https://docs.cyberduck.io/protocols/profiles/)
- https://github.com/iterate-ch/cyberduck/issues/14876
- https://github.com/iterate-ch/cyberduck/pull/14877
Connection Profile:
- https://github.com/iterate-ch/profiles/issues/47
- https://github.com/iterate-ch/profiles/pull/48
- https://github.com/iterate-ch/cyberduck/issues/14166
- https://github.com/owncloud/web/issues/9714
This change would make it easy to understand connections with modern 3rd party WebDAV clients.
1. Import `cyberduck.json` to `https://keycloak.ocis-keycloak.latest.owncloud.works/admin/master/console/#/oCIS/clients/import-client`
2. Create …

Add example config for 3rd party WebDAV client Cyberduck (and Mountain Duck)

---

services/graph/pkg/service/v0/users_filter.go

This is a small fix that allows whitespaces in startsWith and Contains user filters.

allow whitespaces in contains & startsWith Filter

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/apiSpacesShares/shareOperations.feature
tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature

part of: https://github.com/owncloud/ocis/issues/7823

[tests-only][full-ci] tests: add api tests for deleting public link password

---

services/graph/pkg/service/v0/links.go
services/graph/pkg/service/v0/links_test.go

Analog to #7851 return 200 and not 201 when a link is created on resource
do what the libreGraph documentation says it would do
:robot:

return 200 and not 201 when creating sharing link

---

services/thumbnails/README.md

Observed with ownCloud Web UI 7.1.0 (Spaces overview):
```
scalingup: 0
preview: 1
a: 1
c: ce88e69a448ab8acf7ff554be5bb5521
x: 1000
y: 1000
```
Adding thumbnail query parameters to the thumbnail service docs.
This helps to align x-platform client implementations.

[docs-only] Adding thumbnail query parameters to thumbnail README.md

---

services/graph/pkg/service/v0/links.go
services/graph/pkg/service/v0/links_test.go

according to the [libre-graph definition](https://github.com/owncloud/libre-graph-api/blob/main/api/openapi-spec/v1.0.yaml#L427-L430), the return of the create link call should be a single permission, not an array of permissions
do what the specification says
- :robot: with unit tests
- creating links in integration tests of ocis-php-sdk

return only single permission on link creation

---

services/policies/pkg/config/config.go
services/policies/pkg/config/defaults/defaultconfig.go
services/policies/pkg/config/parser/parse.go

While tracing the calls for a diagram I noticed that the postprocessing service does not actually use the reva config options that can be configured.
so, only killing dead code, AFAICT

drop unused reva config from policies

---

.drone.env
changelog/5.0.0_2023-11-30/update-web-8.0.0.md
services/web/Makefile

[full-ci] chore: bump web to v8.0.0-alpha.12

---

deployments/examples/oc10_ocis_parallel/docker-compose.yml
deployments/examples/ocis_hello/docker-compose.yml
deployments/examples/ocis_keycloak/docker-compose.yml
deployments/examples/ocis_ldap/docker-compose.yml
deployments/examples/ocis_s3/docker-compose.yml
deployments/examples/ocis_traefik/docker-compose.yml
services/frontend/README.md

Follow up of #7877 
Use the global variables also in
- test case 1:
- test case 2:
- ...

[docs-only] feat: use global variables for password policy

---

tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/apiSpacesShares/shareOperations.feature
tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature

Part of: https://github.com/owncloud/ocis/issues/7823
Updates the scenarios added in https://github.com/owncloud/ocis/pull/7540 to use `ocs-v2` as well

[tests-only][full-ci] tests: update tests related to deletion of public link password to use ocsv2 as well

---

docs/Makefile

Fixes the `make help` command in docs folder to include the relevant information

[docs-only] Fix Makefile Help

---

services/graph/pkg/service/v0/driveitems.go
services/graph/pkg/service/v0/driveitems_test.go
services/graph/pkg/service/v0/service.go
services/graph/pkg/service/v0/sharedbyme.go
services/graph/pkg/unifiedrole/unifiedrole.go
services/graph/pkg/validate/libregraph.go

This is an initial implementation of PATCH support on drives/{driveid}/items/{itemid}/permissions/{id}.
It focusses on updating user shares for now. It's possible to update the expirationDate, roles and/or libregraphResourceActions.
Updating the permissions of a space root or a public link share is currently not implemented. Both should come with a follow up PR.
Somehow the usershareprovider is also still lacking checks if the sharer is actually allowed to set the requested permissions (e.g. when re-sharing). Still need to investigate that, but that something for a reva PR.

graph: update permissions

---

changelog/unreleased/fix-auth-allow-empty-cred-chain.md
go.mod
go.sum
services/frontend/pkg/revaconfig/config.go
vendor/github.com/cs3org/reva/v2/internal/http/interceptors/auth/auth.go
vendor/modules.txt

Backport of https://github.com/owncloud/ocis/pull/7453 to stable-4.0

[stable-4.0][backport]Fix reva config of frontend service 

---

docs/ocis/deployment/ubernauten.md

Added Supervisord URL, removed deprecated $THUMBNAIL advice from Troubleshooting section, moved Cert stuff to Troubleshooting section again (because no ubernauten user should be confronted with Cert issues, since ubernauten take over all of that.

[docu-only] Added Supervisord URL, removed deprecated $THUMBNAIL advice

---

changelog/unreleased/add-edit-public-share.md
services/graph/pkg/errorcode/cs3.go
services/graph/pkg/errorcode/cs3_test.go
services/graph/pkg/errorcode/errorcode.go
services/graph/pkg/linktype/linktype.go
services/graph/pkg/service/v0/driveitems.go
services/graph/pkg/service/v0/driveitems_test.go
services/graph/pkg/service/v0/links.go
services/graph/pkg/service/v0/service.go
services/graph/pkg/validate/libregraph.go

- Relates to #6993 
Improve our APIs 🎉 
- manually
- unit tests

Edit public links and setPassword

---

changelog/unreleased/add-trach-bin-cli.md
services/gateway/pkg/config/config.go
services/storage-users/README.md
services/storage-users/pkg/command/trash_bin.go
services/storage-users/pkg/command/trash_bin_test.go
services/storage-users/pkg/config/config.go
services/storage-users/pkg/config/defaults/defaultconfig.go

- Fixes [https://github.com/owncloud/ocis/issues/7845](https://github.com/owncloud/ocis/issues/7845)
- test case 1: Create the any files in personal and some space for moss. delete them.
command examples 
```bash
// ocis v4
// moss personal
OCIS_MACHINE_AUTH_API_KEY=some-ocis-machine-auth-api-key \
./ocis storage-users trash-bin list '058bff95-6708-4fe5-91e4-9ea3d377588b' 'storage-users-1$058bff95-6708-4fe5-91e4-9ea3d377588b'
OCIS_MACHINE_AUTH_API_KEY=some-ocis-machine-auth-api-key \
./ocis storage-users trash-bin restore -o=keep-both '058bff95-6708-4fe5-91e4-9ea3d377588b' 'storage-users-1$058bff95-6708-4fe5-91e4-9ea3d377588b' 'cc67c6f8-d353-4f99-89a6-17c723fd85f8'
OCIS_MACHINE_AUTH_API_KEY=some-ocis-machine-auth-api-key \
./ocis storage-users trash-bin …
```

[stable-4.0][backport]  cli has been exteneded by the list and restore commands

---

.drone.env
changelog/unreleased/update-web-8.0.0.md
services/web/Makefile

This includes some fixes for the most recent right sidebar panel enhancement.

[full-ci] chore: bump web to v8.0.0-beta.2

---

.drone.star

We used to have 300 seconds (5 mins) timeout for service to be ready with wait-for -it. command to wait for ocis connection was changed and the timeout was approx. ~2 mins. There can be some pipeline where image pull could take some time and `wait-for-ocis-server` step fails due to timeout. e.g. https://drone.owncloud.com/owncloud/ocis/30033/11/6
With this PR, we are waiting for ocis to be ready with the same old curl command but with the added timeout of 300 seconds

[tests-only][full-ci] wait for ocis server with timeout (5 mins timeout)

---

tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature

these tests were added recently as a part of the issue https://github.com/owncloud/ocis/issues/7823 but these tests aren't how the Reva is expected to behave so skip these tests in Reva. 
This will unblock the bump commit id PR  in Reva https://github.com/cs3org/reva/pull/4399

[tests-only]tests: skip tests in reva

---

changelog/unreleased/bump-reva.md
changelog/unreleased/fix-update-share-ng.md
go.mod
go.sum
services/graph/pkg/service/v0/driveitems.go
services/graph/pkg/service/v0/driveitems_test.go
vendor/github.com/cs3org/reva/v2/internal/grpc/services/gateway/usershareprovider.go
vendor/github.com/cs3org/reva/v2/internal/grpc/services/usershareprovider/usershareprovider.go
vendor/modules.txt

This fixes two smaller issue in the UpdateShare handler:
- We were using some deprecated attribute in the CS3 UpdateShare request
- a return statement was missing under some error conditions we return an invalid response
This needs: https://github.com/cs3org/reva/pull/4405

[full-ci] graph sharing: Fixes for UpdateShare

---

changelog/unreleased/kv-nats-registry.md
ocis-pkg/natsjsregistry/registry.go

Uses the new natsjs-kv store instead of the object store in the nats registry

Use KV store in nats registry

---

docs/helpers/README.md
docs/helpers/extended_vars.yaml

This PR sets two internal vars gathered automatically to the `no-show` state so they will not be processed when creating the extended envvar list pulled from the admin docs.
Note that we have to investigate why the envvars `MICRO_REGISTRY` and `MICRO_REGISTRY_ADDRESS` have a `foundincode: false` state, they are actively used, it should be true. We need to check the parser if all is queried correctly. @kobergj 
@ScharfViktor fyi

[docs-only] Set special internal extended envvars to not-show state

---

changelog/unreleased/fix-upload-session-purging.md
go.mod
go.sum
services/storage-users/pkg/command/uploads.go
vendor/github.com/cs3org/reva/v2/pkg/rhttp/datatx/manager/tus/tus.go
vendor/github.com/cs3org/reva/v2/pkg/storage/storage.go
vendor/github.com/cs3org/reva/v2/pkg/storage/uploads.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/upload.go
vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/upload/processing.go
vendor/modules.txt

backport of https://github.com/owncloud/ocis/pull/7859 to stable-4.0 to prevent deleting unprocessed uploads

backport UploadSessionLister interface to stable 4.0

---

tests/acceptance/features/bootstrap/GraphContext.php
tests/acceptance/features/bootstrap/Provisioning.php

In this PR, provision API is removed for group creation
- Part of https://github.com/owncloud/ocis/issues/6998
The group is unable to create using the provision endpoint since it has been removed from test also.
```zsh
curl -k -v "https://localhost:9200/ocs/v2.php/cloud/groups" --data '{"grouped" : "sales"}' -u admin:admin
```
<b>Output</b>
```
*   Trying 127.0.0.1:9200...
* Connected to localhost (127.0.0.1) port 9200 (#0)
.
.
.
> POST /ocs/v2.php/cloud/groups HTTP/1.1
> Host: localhost:9200
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 19
> Content-Type: application/x-www-form-urlencoded
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental …
```

[tests-only][full-CI] Remove OCS endpoint for group creation

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiSharingNg/shareInvitations.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/SharingNgContext.php

This PR adds a test for the new sharing graph API.
```feature
- Scenario Outline: send sharing invitation to user with different roles via the Graph API
```
- Locally
- :robot:

[full-ci] [tests-only] Added test for sending share invitation to user with role

---

changelog/unreleased/default-registry.md
docs/services/general-info/registry.md
ocis-pkg/registry/registry.go
ocis/pkg/command/server.go
services/graph/pkg/service/v0/graph_suite_test.go
services/notifications/pkg/service/notification_suite_test.go
services/search/pkg/search/search_suite_test.go
services/storage-users/pkg/task/task_suite_test.go
services/userlog/pkg/service/service_suit_test.go

- Switches the default registry to `nats-js-kv`
- Deprecates `consul`, `nats`, `etcd` and `mdns` registries
- Documents registry usage

Switch default registry to `nats-js-kv`

---

changelog/unreleased/add-trach-bin-cli.md
services/gateway/pkg/config/config.go
services/storage-users/README.md
services/storage-users/pkg/command/trash_bin.go
services/storage-users/pkg/command/trash_bin_test.go
services/storage-users/pkg/config/config.go
services/storage-users/pkg/config/defaults/defaultconfig.go

As an admin of a larger instance I want to be able to help users to restore files from the trashbin of their instance if they can not do it in self service.
For that, a CLI tool would be handsome that is able to
* list the trashbin content of a certain space
* restore all files in the space trashbin
* optional: restore by Id selected files
The CLI tool could be completely separate from oCIS but should be maintained in the oCIS repo with the main code. A backport to v4 needs to be provided.
- test case 1:
- test case 2:
- ...

trash-bin cli has been exteneded by the list and restore commands

---

changelog/unreleased/fix-empty-traceids.md
ocis-pkg/tracing/tracing.go

Fixes #7928 (in combination with https://github.com/cs3org/reva/pull/4422)

Use a on-sampling instead of noop traceprovider to get proper traceids

---

services/settings/pkg/store/defaults/defaults.go

Same old problem: The settings service only allows to save values for the language that are defined in the source code.
- Works towards https://github.com/owncloud/ocis/issues/7999
- Pre-requisite for https://github.com/owncloud/web/pull/10214

feat: allow settings service to store "zh" as language value

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/bootstrap/SharingNgContext.php

If `libre.graph.recipient.type` is empty, we expect a 400 error, so I changed the tests
fix tests for https://github.com/owncloud/ocis/pull/8019
@fschade please rebase after merging this PR
cc @grgprarup

apiTest. set recipient type in body

---

services/storage-users/pkg/config/config.go

This is just a small fix where the envvar `OCIS_ASYNC_UPLOADS` in the `storage-users` service contained a semicolon as remnant. This caused the envvar to appear in the docs as the following. Note the single quotes in the next line:

[docs-only] fix envvar where a semicolon was a remnant

---

changelog/unreleased/fix-empty-traceids.md
services/proxy/pkg/middleware/accesslog.go

Also log the traceid alongside the request id.

Also log the traceid alongside the request id

---

docs/helpers/extended_vars.yaml

References: #8011 (Switch default registry to nats-js-kv)
Post merging the referenced PR changing `MICRO_REGISTRY_xxx` envvars, we need to update the `extended-envvars.yaml` to reflect these changes in the envvar docs.
Note that post merging this, the data will get pulled automatically to the admin docs on the next merge there.
@ScharfViktor @saw-jan fyi

[docs-only] Fixes the extended-envvars.yaml because of changes in MICRO_REGISTRY

---

docs/helpers/extended_vars.yaml

References: #8031 ([docs-only] Fixes the extended-envvars.yaml because of changes in MICRO_REGISTRY)
To my shame, I missed to press save before pushing, so not all changes needed did get in the referenced PR... 🤦‍♂️ Fixed now.

[docs-only] Fixing the description text of MICRO_REGISTRY

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSharingNg/createLink.feature
tests/acceptance/features/bootstrap/SharingNgContext.php

This PR adds the implementation for new `v1beta1` graph-api to create a share link with different roles.
```feature
Scenario Outline: create a link share of a folder
Scenario Outline: create a link share of a file
```

[tests-only][full-ci]Added tests for creating link for a resource

---

changelog/unreleased/fix-traces.md
go.mod
go.sum
ocis-pkg/tracing/tracing.go
services/proxy/pkg/middleware/accesslog.go
vendor/github.com/cs3org/reva/v2/pkg/rgrpc/rgrpc.go
vendor/modules.txt

Backport the tracing fixes to always generate proper trace ids and properly pass the trace ids down the stack.

Backport tracing fixes

---

changelog/unreleased/fix-search-by-exact-mail.md
services/graph/pkg/identity/odata.go
services/graph/pkg/service/v0/users.go

Search terms from the graph API can be enclosed with double quotes. The double quotes are intended to prevent the interpretation of some tokens from the parser. However, the parser doesn't remove the double quotes.
This PR will remove those double quotes.
As a practical example, searching by email (such as `marie@example.org`) can give problems because the `@` char is interpreted as a different token (likely as a parameter alias, although I'm not fully sure). With this PR, you can search it by enclosing the email in double quotes, like `$search="marie@example.org"` (note that url-encoding might be needed)
https://github.com/owncloud/ocis/issues/7990
Allow searching users by email
Manually tested via API, running something like `curl -vk -ueinstein:relativity …

fix: double quotes will be trimmed from the search token

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSharingNg/createLink.feature

Added Test scenarios for creating share link with `displayname` and `expirydate`
```feature
Scenario Outline: create a link share of a folder with display name and expiry date
Scenario Outline: create a link share of a file with display name and expiry date
```

[tests-only][full-ci]Added tests for the expirydate with displaName for share link

---

changelog/unreleased/fix-search-by-exact-mail.md
services/graph/pkg/identity/backend.go
services/graph/pkg/identity/cs3.go
services/graph/pkg/identity/ldap_group.go
services/graph/pkg/identity/ldap_group_test.go
services/graph/pkg/identity/ldap_test.go
services/graph/pkg/identity/mocks/backend.go
services/graph/pkg/identity/odata.go
services/graph/pkg/service/v0/groups.go
services/graph/pkg/service/v0/groups_test.go
services/graph/pkg/service/v0/users.go
services/graph/pkg/service/v0/users_test.go

graph/groups: Handle quoted search terms for in GetGroups

---

changelog/unreleased/add-RED-metrics.md
services/proxy/README.md
services/proxy/pkg/command/server.go
services/proxy/pkg/metrics/metrics.go
services/proxy/pkg/middleware/metrics.go

The proxy service in ocis has the ability to expose metrics in the prometheus format. The metrics are exposed on the `/metrics` endpoint. There are two ways to run the ocis proxy service which has an impact on the number of metrics exposed.
In the single process mode, all ocis services are running inside a single process. This is the default mode when using the `ocis server` command to start the services. In this mode, the proxy service exposes metrics about the proxy service itself and about the ocis services it is proxying. This is due to the nature of the prometheus registry which is a singleton. The metrics exposed by the proxy service itself are prefixed with `ocis_proxy_` and the metrics exposed by other ocis services are prefixed with `ocis_<service-name>_`.
In this mode, the proxy …

feat: RED metrics

---

.drone.env
changelog/unreleased/update-web-8.0.0.md
services/web/Makefile

Bumps Web to `v8.0.0-rc.1`. Please see the changelog for more details.
Known issue: some German translation strings are missing.

[full-ci] chore: bump web to v8.0.0-rc.1

---

services/frontend/pkg/revaconfig/config.go

As per product management requirements, this PR reduces the set of available `mdate` filter keywords, see https://github.com/owncloud/web/issues/9779#issuecomment-1807930111
- Relates to https://github.com/owncloud/web/issues/9779#issuecomment-1807930111
Keep filter options simple until we have more feedback what's actually needed.

fix: reduce mtime keywords to the required ones

---

changelog/unreleased/fix-remove-unused-idp-dependency.md
services/idp/package.json
services/idp/pnpm-lock.yaml

The idp ui uses `kpop` (opinionated react component library), which declares an outdated `cldr` version without even using it. Since that currently has a security issue, we're patching the idp ui to remove the `cldr` dependency from `kpop` entirely.
Asked upstream, if we can safely remove the dependency. https://github.com/Kopano-dev/kpop/issues/40
- Works towards https://github.com/owncloud/ocis/issues/7957
Security

[full-ci] remove outdated and unused cldr dep from kpop in idp package

---

tests/acceptance/config/behat.yml
tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSharingNg/createLink.feature
tests/acceptance/features/bootstrap/SharingNgContext.php

Added tests for creating share link without password.
```feature
Scenario Outline: create a link share of a file without password
```

[tests-only][full-ci]Added tests for create link share without password

---

changelog/unreleased/service-account-roles.md
services/settings/README.md
services/settings/pkg/config/config.go
services/settings/pkg/config/defaults/defaultconfig.go
services/settings/pkg/service/v0/service.go
services/settings/pkg/store/defaults/defaults.go
services/settings/pkg/store/metadata/assignments.go
services/settings/pkg/store/metadata/bundles.go

Adds a hidden role for service accounts. This role will give the service account all permissions it needs but will not appear in list roles calls. Also it doesn't need the default role assignments to work.
Fixes: https://github.com/owncloud/enterprise/issues/6286
Also deprecates `filesystem` settings store 
NOTE: This is a breaking change. It removes the (unreleased) `SETTINGS_SERVICE_ACCOUNT_ID_ADMIN` environment variable without deprecation

[full-ci] Service Account Roles

---

tests/acceptance/features/apiSharingNg/shareInvitations.feature

This PR adds a test for sending share invitation to group with different permissions.
```feature
- Scenario Outline: send share invitation for file to group with different permissions
- Scenario Outline: send share invitation for folder to group with different permissions
```
- Locally
- :robot:

[full-ci] [tests-only] Added test for sending share invitation to group with permissions

---

.drone.star

Since k6 pipeline uses the remote servers to run ocis server and k6 tests, we cannot run more than one k6 pipeline parallelly. So we have to run k6 pipeline only in on of the branches. This PR makes it to run only with master branch.

[tests-only][ci] Run k6 tests only for master branch

---

tests/ociswrapper/cmd/cmd.go
tests/ociswrapper/ocis/config/config.go
tests/ociswrapper/ocis/ocis.go

That way we don't need to have authentication, nor have to enable basic auth in the SUT

use capabilites and not `me/drives` in ociswrapper to check if ocis is online

---

changelog/unreleased/bump-reva.md
go.mod
go.sum
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
tests/acceptance/features/apiSpacesShares/moveSpaces.feature
tests/acceptance/features/coreApiShareManagementToShares/moveShareInsideAnotherShare.feature
tests/acceptance/features/coreApiShareOperationsToShares1/changingFilesShare.feature
tests/acceptance/features/coreApiWebdavMove2/moveShareOnOcis.feature
vendor/github.com/cs3org/reva/v2/internal/grpc/services/gateway/storageprovider.go
vendor/github.com/cs3org/reva/v2/internal/grpc/services/sharesstorageprovider/sharesstorageprovider.go
vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocdav/move.go
vendor/modules.txt

Update reva to fix status codes.
- Fixes https://github.com/owncloud/ocis/issues/8063
- test case 1:
- test case 2:
- ...

fix: update reva to fix status codes

---

changelog/unreleased/enhancement-disabled-password-policy.md
services/frontend/README.md
services/frontend/pkg/config/config.go
services/frontend/pkg/revaconfig/config.go
services/sharing/pkg/config/config.go
services/sharing/pkg/revaconfig/config.go

**!! Related from the REVA changes [https://github.com/cs3org/reva/pull/4409](https://github.com/cs3org/reva/pull/4409)**
add the environment variable that allow to disable the password policy
The `password_policy.disabled` has been added to the capabilities
```json
"password_policy": {
"disabled": true,
"min_characters": 3,
"max_characters": 72,
"min_lowercase_characters": 0,
"min_uppercase_characters": 0,
"min_digits": 0,
"min_special_characters": 0
},
```
- Fixes [https://github.com/owncloud/ocis/issues/7916](https://github.com/owncloud/ocis/issues/7916)
- test case 1:
- test case 2:
- ...

add the environment variable that allow to disable the password policy

---

tests/acceptance/features/coreApiWebdavUpload1/uploadFile.feature

In this PR, added issue tag `@issue-7257` on the added scenario in PR: https://github.com/owncloud/ocis/pull/8088
- https://github.com/owncloud/ocis/issues/8044

[tests-only][full-ci] added issue tag `@issue-7257` on added scenarios

---

tests/acceptance/config/behat-core.yml
tests/acceptance/expected-failures-API-on-OCIS-storage.md
tests/acceptance/features/apiSpacesShares/moveSpaces.feature
tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
tests/acceptance/features/coreApiShareOperationsToShares1/changingFilesShare.feature
tests/acceptance/features/coreApiWebdavMove2/moveFile.feature
tests/acceptance/features/coreApiWebdavMove2/moveShareOnOcis.feature

Extends MOVE API test coverage:
**Using file path**
| from       | from (role)           | to                  | to (role)             | result         | API coverage       |
| ---------- | --------------------- | ------------------- | --------------------- | -------------- | ------------------ |
| project    | manager/editor        | project(same)       |                       | 201 :+1:       | :heavy_check_mark: |
| project    | viewer                | project(same)       |                       | 403 :+1:       | :heavy_check_mark: |
| project    | manager/editor        | project             | manager/editor        | 502 :question: | :heavy_check_mark: |
| project    | manager/editor        | project             | viewer                | 403 :+1:       | :heavy_check_mark: |
| project …

[tests-only] Extend API test coverage for MOVE between spaces

---

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
tests/acceptance/features/apiSpacesShares/moveSpaces.feature
tests/acceptance/features/bootstrap/SpacesContext.php
tests/acceptance/features/bootstrap/WebDav.php

Extends MOVE API test coverage:
**Using file-id**
| from       | from (role)           | to                  | to (role)             | result         | API coverage       |
| ---------- | --------------------- | ------------------- | --------------------- | -------------- | ------------------ |
| project    | manager/editor        | project(same)       |                       | 201 :+1:       | :heavy_check_mark: |
| project    | viewer                | project(same)       |                       | 403 :+1:       | :heavy_check_mark: |
| project    | manager/editor        | project             | manager/editor        | 502 :question: | :heavy_check_mark: |
| project    | manager/editor        | project             | viewer                | 403 :+1:       | :heavy_check_mark: |
| project …

[tests-only] Extend API test coverage for MOVE between spaces using file-id

---

changelog/unreleased/fix-race-in-tests.md
services/search/pkg/search/debouncer_test.go
services/search/pkg/search/events_test.go

Fix the race conditions in tests
- Fixes [https://github.com/owncloud/ocis/issues/7846](https://github.com/owncloud/ocis/issues/7846)
- test case 1:
- test case 2:
- ...

the race conditions in tests

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/config/behat.yml
tests/acceptance/features/apiSharingNg/linkShare.feature
tests/acceptance/features/bootstrap/PublicWebDavContext.php
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/SharingNgContext.php

This PR adds the tests scenarios to set and update(if already created) the password for the public link share for shareNg
```feature
Scenario: set password for a file's link share
Scenario: update password for a file's link share
```

[tests-only][full-ci]Added tests for setting password in a public share link

---

changelog/unreleased/fix-cs3-backend.md
services/idp/pkg/backends/cs3/identifier/cs3.go
services/idp/pkg/backends/cs3/identifier/session.go

We now correctly reinitialize the CS3 backend session after the IDP has been restarted.
I still had login problems when using the cs3 backend for my oc10 parallel deployment. This fixes them.
I'm not on a misson to make the code beautiful ... just trying to make it work here ...

fix idp cs3 backend session refresh

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiSharingNg/linkShare.feature
tests/acceptance/features/apiSharingNg/shareInvitations.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/SharingNgContext.php

after discution https://github.com/owncloud/ocis/pull/8130#discussion_r1441655159
In our tests, I found some confusion about the names. 
I suggest to define and solve it at an early stage.
example:  <img width="687" alt="image" src="https://github.com/owncloud/ocis/assets/84779829/ba86ff9a-4b3c-4a9a-8c1a-028b707f7dd3">
so I suggest to use: 
| old naming         | new naming in test  | 
|------------|-------|
|role|permissionsRole|
|roleId|permissionsRoleId|
|permission|permissionsAction|
|shareId|permissionsId|
2. Changed` When user "Alice" updates the following password for the last link share using the Graph API:` to `When user "Alice" sets the following password for the last link share using the Graph API:` not to be confused PATCH request with POST setPassword request

[test-only] Change naming in sharingNG api-tests

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/bootstrap/Sharing.php
tests/acceptance/features/bootstrap/SharingNgContext.php

Previously I fetched the `permissionId` with the extra request but the `permissionId` is what we knew to be `shareId` so we can store the shareId directly from the share invite response and use it from the stored array. This removes the necessity for extra request. 
https://github.com/owncloud/ocis/issues/8008

[tests-only] tests: refactor test script for removing permission from share

---

deployments/examples/oc10_ocis_parallel/config/ldap/ldif/10_owncloud_schema.ldif
deployments/examples/ocis_ldap/config/ldap/schemas/10_owncloud_schema.ldif
tests/parallelDeployAcceptance/drone/ldap/ldif/10_owncloud_schema.ldif

In oCIS the quota is a setting of the personal or project spaces. We never stored quotas in LDAP for ocis nor are there plans to do so.
Fixes: #8059

Remove unused ownCloudQuota attribute from LDAP Schema

---

tests/TestHelpers/GraphHelper.php
tests/acceptance/features/apiSharingNg/deletePermissions.feature
tests/acceptance/features/apiSharingNg/linkShare.feature
tests/acceptance/features/apiSharingNg/shareInvitations.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/SharingNgContext.php

Backport https://github.com/owncloud/ocis/pull/8140

[test-only] [back-port] Change naming in sharingNG api-tests
