owncloud/ocis

- tests/acceptance/features/apiSpacesShares/shareSpaces.feature
api test for https://github.com/owncloud/ocis/issues/6353
> [test-only] ApiTest. last space manager cannot change his role

- composer.json
- vendor-bin/behat/composer.json
Keep these up-to-date like in core https://github.com/owncloud/core/tree/master/vendor-bin/behat and https://github.com/cs3org/behat/pull/1
CI
> [tests-only] [full-ci] Update PHP API test dependencies

- .github/release_template.md
- I created release template like in the client https://github.com/owncloud/client/blob/master/.github/release_template.md
Separately, I put the out existing smoke tests to https://github.com/owncloud/QA and link it
Note: some links will be available after merging https://github.com/owncloud/QA/pull/813
> Release template

- tests/acceptance/features/coreApiWebdavProperties2/getFileProperties.feature
This PR adds the refactoring of the feature file:
- getFileProperties.feature
- https://github.com/owncloud/QA/issues/804
> [tests-only] [full-ci] refactored feature file

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiCors/cors.feature
- tests/acceptance/features/apiSpaces/quota.feature
- tests/acceptance/features/bootstrap/OcisConfigContext.php
Backport of PR https://github.com/owncloud/ocis/pull/6402 into `stable-3.0`
> [tests-only][full-ci]Back port spaces max quota feature

- changelog/unreleased/bump-reva-latest.md
- go.mod
- go.sum
- vendor/github.com/cs3org/reva/v2/internal/grpc/services/storageprovider/storageprovider.go
- vendor/modules.txt
- test case 1:
- test case 2:
- ...
> [full-ci] bump a reva according the #issue-6469

- tests/acceptance/features/apiAntivirus/antivirus.feature
- tests/acceptance/features/bootstrap/NotificationContext.php
This PR adds API test for notification test for virus file upload i[for Deutsch and Spanish language.
- Part of <https://github.com/owncloud/ocis/issues/6255>
- coverage for https://github.com/owncloud/enterprise/issues/5706
- locally
- CI
> [tests-only][full-ci]Test/antivirus testnotificationlanguage

- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiGraph/createGroup.feature
- tests/acceptance/features/apiGraph/createGroupCaseSensitive.feature
https://github.com/owncloud/ocis/issues/3516 fixed but tests were failed because expected code was `400` instead of `409`
I changed code and deleted tests from expected failures list
> [test-only] changing status code of the api tests

- changelog/unreleased/bump-reva-latest.md
- changelog/unreleased/bump-reva.md
Fix the reva changelog
- test case 1:
- test case 2:
- ...
> [docs-only] update the reva changelog

- .drone.star
- tests/acceptance/features/apiSpaces/quota.feature
- tests/acceptance/features/bootstrap/SpacesContext.php
This PR backports the PR merged in master:  https://github.com/owncloud/ocis/pull/6450
> [tests-only][full-ci]Backport spaces max quota second

- .drone.star
- docs/ocis/development/testing.md
- tests/acceptance/docker/src/antivirus.yml
- tests/acceptance/docker/src/ocis-base.yml
This PR backports following PR's
- https://github.com/owncloud/ocis/pull/6573
- https://github.com/owncloud/ocis/pull/6566
> [tests-only][full-ci]Backport/antivirus refactoring pr

- services/search/pkg/search/events.go
- test case 1:
- test case 2:
- ...
> Handle events asynchronously

- tests/acceptance/features/apiAntivirus/antivirus.feature
This PR adds API test for antivirus with various environment variable setting. The added scenarios are
- upload a file with virus with various infected file handling setting set to continue
- Part of <https://github.com/owncloud/ocis/issues/6255>
- locally
- CI
> [tests-only]Add test for ANTIVIRUS_INFECTED_FILE_HANDLING

- services/idp/pkg/middleware/static.go
- services/invitations/pkg/service/v0/tracing.go
- services/ocs/pkg/middleware/logtrace.go
- services/thumbnails/pkg/service/grpc/v0/decorators/tracing.go
- services/webfinger/pkg/service/v0/tracing.go
Adds span kind where missing.
- Fixes #5801 
Tested by running in my local k3s cluster.
> Add missing span kind for tracing.

- tests/acceptance/features/apiAntivirus/antivirus.feature
This PR adds the API test scenario for overwrite file with virus content in public link share
- Part of: https://github.com/owncloud/ocis/issues/6255
- There was no test coverage for overwrite file with virus content in public link share. So, this PR coves the required scenario test case.
- locally
- CI
> [tests-only][full-ci]added scenario for overwrite file with virus content in a public link

- changelog/unreleased/add-ids-to-graph-education-logging.md
- services/graph/pkg/service/v0/educationclasses.go
- services/graph/pkg/service/v0/educationschools.go
- services/graph/pkg/service/v0/educationuser.go
Fixes https://github.com/owncloud/ocis/issues/6576
> Add IDs to graph access logs

- changelog/unreleased/fix-oidc-role-assigner.md
- services/proxy/pkg/userroles/oidcroles.go
See this comment for details: https://github.com/owncloud/ocis/pull/6605#pullrequestreview-1495340701
> Fix OIDC Role Assigning

- tests/acceptance/features/bootstrap/SettingsContext.php
This PR aims to address the occurrence of a JSON Exception error during test execution. Although the error cannot be replicated locally, it is likely caused by an unsuccessful API request (sendRequestAssignmentsList). The success of the API request is checked in this added code
- Fixes https://github.com/owncloud/ocis/issues/6524
- locally
> [full-ci][tests-only] Implement validation code while request for user app role id in `Then` step

- tests/acceptance/features/apiSpacesShares/changingFilesShare.feature
This PR adds different roles for sharee and then checks for the file versioning.
- Part of <https://github.com/owncloud/ocis/issues/6606#event-9646533873>
- locally
- ci
> [tests-only] [full-ci] added different roles for sharee

- services/webdav/pkg/config/config.go
References: #6577 ([full-ci] allow to disable previews in webdav & web)
Missed to get the suggestion committed before merging.
> [docs-only] Fix webdav envvar description

- tests/acceptance/features/bootstrap/WebDav.php
Added a check for downloading file as user as there is intermediate failure related to scenario:
`Scenario Outline: uploading a file with checksum should work for file with special characters`
Added following line of code in https://github.com/owncloud/ocis/blob/753c8f2372cf42fffbf1ba13606516577119dca3/tests/acceptance/features/bootstrap/WebDav.php#L1184
```
$actualStatus = $this->response->getStatusCode();
if ($actualStatus !== 200) {
throw new Exception(
"Expected status code to be '200', but got '$actualStatus'"
);
}
```
- https://github.com/owncloud/ocis/issues/6629
> [tests-only] [full-ci] check response for download file as user

- tests/acceptance/features/bootstrap/ArchiverContext.php
- tests/acceptance/features/bootstrap/FilesVersionsContext.php
- tests/acceptance/features/bootstrap/GraphContext.php
- tests/acceptance/features/bootstrap/Provisioning.php
- tests/acceptance/features/bootstrap/Sharing.php
- tests/acceptance/features/bootstrap/SpacesContext.php
- tests/acceptance/features/bootstrap/WebDav.php
- tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
This PR backport PRs https://github.com/owncloud/ocis/pull/6553 and https://github.com/owncloud/ocis/pull/6643
> [tests-only][full-ci] Backport implementing code refactoring

- tests/acceptance/features/apiGraph/deleteUser.feature
> [test-only] personal space is deleted after a user is deleted test

- go.mod
- go.sum
- tests/acceptance/features/apiContract/propfind.feature
- tests/acceptance/features/coreApiShareManagementToShares/mergeShare.feature
- vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/conversions/role.go
- vendor/modules.txt
This adds a new WebDAV permission to the matrix.
`P` stands for `PurgeRecycle` which means that the user is allowed to delete files from the trash.
- test case 1:
- test case 2:
- ...
> [full-ci] Update Reva to include 4013

- docs/clients/rclone/webdav-sync-oidc.md
the slash for multi line bash commands needs to be the other way around
> [docs-only] fix slash in bash command

- tests/acceptance/features/bootstrap/FeatureContext.php
`SpaceContext` was registered in `FeatureContext`. Due to hooks running for Reva gets a test to fail.
- Related to failure in PR https://github.com/cs3org/reva/pull/4013
- https://drone.owncloud.com/cs3org/reva/2144
> [tests-only] [full-ci] Do not register space context for reva

- services/userlog/README.md
Add a note about how many connections are possible with SSE to avoid pitfalls.
To be in sync with admin docs.
> [docs-only] Update userlog README.md

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiGraph/fullSearch.feature
This PR backports
- https://github.com/owncloud/ocis/pull/6641
- https://github.com/owncloud/ocis/pull/6653/
> [tests-only][full-ci]Backport full search test

- tests/acceptance/features/coreApiSharePublicLink1/deletePublicLinkShare.feature
- tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
- tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature
- tests/acceptance/features/coreApiWebdavEtagPropagation2/copyFileFolder.feature
- tests/acceptance/features/coreApiWebdavEtagPropagation2/createFolder.feature
- tests/acceptance/features/coreApiWebdavEtagPropagation2/restoreVersion.feature
- tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature
This PR updates the `@issue-product` tag to current ocis issue number tag.
- https://github.com/owncloud/ocis/issues/5337
> [tests-only][full-ci] update issue-product tag to ocis issue tag

- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/apiGraph/editUser.feature
- tests/acceptance/features/apiGraph/getUser.feature
- tests/acceptance/features/apiSpaces/quota.feature
- tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
- tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
- tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
- tests/acceptance/features/coreApiAuthWebDav/webDavCOPYAuth.feature
- tests/acceptance/features/coreApiCapabilities/capabilities.feature
- tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
- tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
- tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
- tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
- tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
- tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
- tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
- tests/acceptance/features/coreApiShareReshareToShares1/reShare.feature
- tests/acceptance/features/coreApiShareReshareToShares2/reShareSubfolder.feature
- tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
- tests/acceptance/features/coreApiSharees/sharees.feature
- tests/acceptance/features/coreApiTrashbin/trashbinDelete.feature
- tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
- tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
- tests/acceptance/features/coreApiVersions/fileVersions.feature
- tests/acceptance/features/coreApiWebdavLocks2/independentLocks.feature
- tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
- tests/acceptance/features/coreApiWebdavOperations/propfind.feature
This PR backports https://github.com/owncloud/ocis/pull/6694
> [tests-only][full-ci] Backport refactor scenario example table

- tests/acceptance/features/coreApiSharePublicLink1/deletePublicLinkShare.feature
- tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
- tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature
- tests/acceptance/features/coreApiWebdavEtagPropagation2/copyFileFolder.feature
- tests/acceptance/features/coreApiWebdavEtagPropagation2/createFolder.feature
- tests/acceptance/features/coreApiWebdavEtagPropagation2/restoreVersion.feature
- tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature
This PR backports https://github.com/owncloud/ocis/pull/6708
> [tests-only] [full-ci] Backport update issue-product tag to ocis issue tag

- .drone.star
Backport from `master` branch.
- test case 1:
- test case 2:
- ...
> [CI] [tests-only] Backport CI secrets change

- .drone.star
These PR backport changes done in CI of master branch
#6714
> [full-ci][tests-only] Backport drone update

- tests/acceptance/features/apiGraph/fullSearch.feature
- search by tag accepted sharee
- there was no test coverage for api test for search by tag accepted sharee. so, this PR covers the require scenario test case
- locally
- CI
> [tests-only][full-ci] Added API test to search shared items using a tag

- deployments/examples/ocis_wopi/config/wopiserver/wopiserver.conf.dist
fixes onlyoffice with wopi
- test case 1:
- test case 2:
- ...
> fix onlyoffice with wopi

- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/coreApiWebdavPreviews/previews.feature
- tests/acceptance/features/coreApiWebdavPreviews/previewsAutoAdustedSizing.feature
This Pr forward port https://github.com/owncloud/ocis/pull/6693
- Fixes https://github.com/owncloud/ocis/issues/5418
- test case 1:
- test case 2:
- ...
> [full-ci][tests-only] Forward port preview test coverage

- services/userlog/pkg/command/server.go
- services/userlog/pkg/config/config.go
- services/userlog/pkg/config/tracing.go
- services/userlog/pkg/server/http/option.go
- services/userlog/pkg/server/http/server.go
- services/userlog/pkg/service/http.go
- services/userlog/pkg/service/service.go
fixes https://github.com/owncloud/ocis/issues/6177
> add userlog tracing

- tests/ociswrapper/cmd/cmd.go
- tests/ociswrapper/log/log.go
- tests/ociswrapper/ocis/config/config.go
- tests/ociswrapper/ocis/ocis.go
- tests/ociswrapper/wrapper/wrapper.go
Porting https://github.com/owncloud/ocis/pull/6768 and https://github.com/owncloud/ocis/pull/6776
> [tests-only][full-ci] Retry ocis startup with ociswrapper and separate logs

- go.mod
- go.sum
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/lookup/lookup.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/metadata/messagepack_backend.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/metadata/metadata.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/metadata/xattrs_backend.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/revisions.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/tree/tree.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/upload/processing.go
- vendor/github.com/google/renameio/v2/.golangci.yml
- vendor/github.com/google/renameio/v2/CONTRIBUTING.md
- vendor/github.com/google/renameio/v2/LICENSE
- vendor/github.com/google/renameio/v2/README.md
- vendor/github.com/google/renameio/v2/doc.go
- vendor/github.com/google/renameio/v2/option.go
- vendor/github.com/google/renameio/v2/tempfile.go
- vendor/github.com/google/renameio/v2/writefile.go
- vendor/modules.txt
This PR pulls in reva from https://github.com/cs3org/reva/tree/hotfix-zero-byte
> Bump reva to pull in the 0-byte fix

- tests/acceptance/features/bootstrap/TrashbinContext.php
This PR backports https://github.com/owncloud/ocis/pull/6718
Part of https://github.com/owncloud/ocis/issues/6628
> [tests-only][full-ci] refactor for Intermittent test failures on coreApiTrashbin/trashbinDelete.feature

- .drone.star
Port of https://github.com/owncloud/ocis/pull/6817
> ci: split e2e test pipeline (#6817)

- tests/acceptance/features/apiGraph/fullSearch.feature
This PR backport https://github.com/owncloud/ocis/pull/6659
> [tests-only][full-ci]Backport test api search tag by user

- tests/TestHelpers/HttpRequestHelper.php
- tests/TestHelpers/WebDavHelper.php
- tests/acceptance/features/bootstrap/WebDav.php
Backport PR #6796 to `stable-3.0`
See the linked PR for details.
It will be useful to have this acceptance test code enhancment in the stable branch.
CI
> [tests-only] [full-ci] retry on 409 - backport 6796 to stable-3.0

- tests/acceptance/features/coreApiWebdavUpload1/uploadFile.feature
related https://github.com/owncloud/ocis/issues/1248
see https://github.com/owncloud/ocis/issues/1248#issuecomment-1596932748
> [test-only][full-ci]ApiTest. added test for uploading zero file with mtime

- tests/TestHelpers/HttpRequestHelper.php
- tests/TestHelpers/UploadHelper.php
- tests/TestHelpers/WebDavHelper.php
- tests/acceptance/features/bootstrap/WebDav.php
Backport #6796 and #6835 to `education-3.1`
CI
> [tests-only] Retry 409 for education 3.1

- tests/acceptance/features/apiGraph/fullSearch.feature
- tests/acceptance/features/bootstrap/TagContext.php
This is backport of PR of master https://github.com/owncloud/ocis/pull/6660
> [tests-only][full-ci]Backport of test for search by deleted tag

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiGraph/fullSearch.feature
This is backport of PR of master https://github.com/owncloud/ocis/pull/6661
> [tests-only][full-ci]Backport test api search restore resource having tag

- tests/acceptance/features/bootstrap/NotificationContext.php
Backport : https://github.com/owncloud/ocis/pull/6839 
Part of: https://github.com/owncloud/QA/issues/817
> [tests-only][full-ci]Retry listing notifications (#6839)

- changelog/unreleased/improve-notification-logs.md
- services/notifications/pkg/service/service.go
- services/notifications/pkg/service/shares.go
- services/notifications/pkg/service/spaces.go
Improve the notification logs when the user has no email address
- Fixes [https://github.com/owncloud/ocis/issues/6855](https://github.com/owncloud/ocis/issues/6855)
> Improve the notification logs when the user has no email address

- tests/acceptance/features/apiFullTextSearch/search.feature
This is the backport of master PR https://github.com/owncloud/ocis/pull/6698
> [tests-only][full-ci]Backport search files through content by sharee

- tests/acceptance/features/apiFullTextSearch/search.feature
This is the backport of the master PR https://github.com/owncloud/ocis/pull/6707
> [tests-only][full-ci]Backport search deleted using context

- tests/acceptance/features/bootstrap/FeatureContext.php
- tests/acceptance/features/bootstrap/Sharing.php
This PR backports the PR https://github.com/owncloud/ocis/pull/6775
> [tests-only][full-ci] Backport refactoring acceptance code to store response data of user or group shares on single store

- tests/acceptance/features/apiAntivirus/antivirus.feature
- tests/acceptance/features/bootstrap/NotificationContext.php
This pr backports https://github.com/owncloud/ocis/pull/6675
> [tests-only][full-ci] Backport refactor check notification and delete it

- ocis-pkg/service/grpc/client.go
- ocis-pkg/tracing/tracing.go
- services/eventhistory/pkg/command/server.go
- services/eventhistory/pkg/config/config.go
- services/eventhistory/pkg/config/defaults/defaultconfig.go
- services/eventhistory/pkg/config/tracing.go
- services/eventhistory/pkg/server/grpc/option.go
- services/eventhistory/pkg/server/grpc/server.go
This adds tracing to the event history service.
> Add tracing to eventhistory service.

- changelog/unreleased/fix-cors.md
- services/frontend/pkg/config/defaults/defaultconfig.go
- services/ocdav/pkg/config/defaults/defaultconfig.go
- services/ocs/pkg/config/defaults/defaultconfig.go
- services/webdav/pkg/config/defaults/defaultconfig.go
- Fixes [https://github.com/owncloud/ocis/issues/5108](https://github.com/owncloud/ocis/issues/5108)
> Fix CORS issues

- go.mod
- go.sum
- services/storage-users/pkg/config/config.go
- services/storage-users/pkg/config/defaults/defaultconfig.go
- services/storage-users/pkg/revaconfig/drivers.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/lookup/lookup.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/options/options.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/tree/propagator/async.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/tree/propagator/propagator.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/tree/propagator/sync.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/tree/tree.go
- vendor/modules.txt
Depends on https://github.com/cs3org/reva/pull/4070
> Make the storage-users propagator configurable

- changelog/unreleased/fix-routing.md
- services/webdav/pkg/service/v0/service.go
- Fixes [https://github.com/owncloud/web/issues/9367](https://github.com/owncloud/web/issues/9367)
Allow to call /remote.php/dav/spaces/
- test environment: locally via API
> Fix the routing capability

- .drone.star
- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiReshare/disableReshare.feature
This PR backports https://github.com/owncloud/ocis/pull/6665
> [tests-only][full-ci] added scenarios for disabling frontend_enable_resharing (#6665)

- services/proxy/pkg/command/server.go
- services/proxy/pkg/config/defaults/defaultconfig.go
- services/webdav/pkg/service/v0/service.go
part of https://github.com/owncloud/ocis/issues/6924
reva part in https://github.com/cs3org/reva/pull/4091 but can be merged independently
> properly register webdav methods with chi

- docs/ocis/development/testing.md
- tests/acceptance/docker/Makefile
- tests/acceptance/docker/src/ocis-base.yml
> [tests-only][full-ci] Update local test docker-compose setup to allow unicode preview tests (#6940)

- .drone.star
- changelog/unreleased/bump-sonarcloud.md
Bumps sonarcloud image to avoid java errors
> Bump Sonarcloud

- changelog/unreleased/enhancement-extendable-policy-mimetype-extension-mapping.md
- services/policies/README.md
fixes accidentally wrong policies env variable
References: #6869
> fix: fix readme and changelog env var

- tests/acceptance/features/apiGraph/fullSearch.feature
- tests/acceptance/features/bootstrap/SearchContext.php
This PR backports https://github.com/owncloud/ocis/pull/6949
> [tests-only][full-ci] Backport searching inside folder in personal space(#6949)

- changelog/unreleased/global-notifications-static-secret.md
- changelog/unreleased/gn-static-secret.md
- services/frontend/pkg/config/config.go
- services/frontend/pkg/revaconfig/config.go
- services/userlog/README.md
- services/userlog/pkg/config/config.go
- services/userlog/pkg/service/http.go
- services/userlog/pkg/service/service.go
Fixes https://github.com/owncloud/ocis/issues/6938
> Global Notifications Static Secret

- tests/acceptance/features/apiGraph/fullSearch.feature
This PR is backport of Master PR https://github.com/owncloud/ocis/pull/6974
> [tests-only][full-ci] Backport add test for search version restored files by tag

- tests/acceptance/features/apiFullTextSearch/search.feature
- search files by content
- there was no test coverage for api test for search files through a content. so, this PR covers the require scenario test case
- locally
- CI
> [tests-only][full-ci]add test for search project space files by content

- services/frontend/pkg/config/config.go
- Part of https://github.com/owncloud/enterprise/issues/5941
- test case 1:
- test case 2:
- ...
> [docs-only] Enhance description of ReadOnlyUserAttributes

- tests/acceptance/features/apiFullTextSearch/search.feature
This PR is the backport of master https://github.com/owncloud/ocis/pull/6970
> [tests-only][full-ci]Backport search version restored files by content

- deployments/examples/ocis_wopi/docker-compose.yml
Fix for https://github.com/owncloud/ocis/issues/7040
The docker-compose example should work out-of-the-box
> Add fulltext search frontend part to ocis_wopi

- tests/acceptance/features/apiFullTextSearch/search.feature
This PR is the backport of master https://github.com/owncloud/ocis/pull/6987
> [tests-only][full-ci]backport of add test for search project space files by content

- go.mod
- go.sum
- vendor/github.com/libregraph/lico/identifier/backends/ldap/ldap.go
- vendor/modules.txt
This is need for getting this fix: libregraph/lico#104
> Bump libregraph/lico to latest master

- tests/acceptance/features/apiFullTextSearch/search.feature
This PR is the Backport of master https://github.com/owncloud/ocis/pull/7039
> [tests-only][full-ci]backport add test for sharee searches project spaces files by content

- .drone.star
> ci: do not skip sonar and codacy in ci (#7015)

- .drone.star
- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiSpacesDavOperation/getFileByFileId.feature
- tests/acceptance/features/bootstrap/SpacesContext.php
This PR backports https://github.com/owncloud/ocis/pull/6958
> [tests-only] [full-ci] Backport access file using file id

- tests/acceptance/features/apiGraph/fullSearch.feature
This PR is backport of master https://github.com/owncloud/ocis/pull/7036
> [tests-only][full-ci]backport add test for sharee searches project spaces files using a tag

- ocis-pkg/tracing/tracing.go
In PR https://github.com/owncloud/ocis/pull/7011 I removed what I believed was leftovers of reva tracer initialization, but it seems that there are some things still not using the provided traceprovider. This adds back setting the default traceprovider, but initializing only one instead of two as in the old code.
> Partially revert removal of believed unused reva tracing initialization.

- tests/acceptance/features/apiFullTextSearch/search.feature
- tests/acceptance/features/apiGraph/fullSearch.feature
This PR consists of 
- `refactoring steps` where multiple tag with files are assigned in single step
- adding the tag @skipOnStable-3.0
- @skipOnStable-3.0 is added to skip some scenarios on CI of stable-3.0 and pass CI successfully
- There was a repeated step for assigning a tag on files which lengthen the scenario so a single step has to be added in order to make the scenario short.
- locally
- ci
> [tests-only][full-ci]add `skipOnStable3.0` and single step for creating tag on files

- tests/acceptance/features/apiGraph/fullSearch.feature
This PR is backport of master https://github.com/owncloud/ocis/pull/7078
> [tests-only][full-ci]Backport adding skip on stable3.0

- go.mod
- services/antivirus/pkg/command/server.go
- services/antivirus/pkg/config/config.go
- services/antivirus/pkg/config/defaults/defaultconfig.go
- services/antivirus/pkg/config/tracing.go
- services/antivirus/pkg/service/service.go
- services/postprocessing/pkg/service/service.go
This PR adds tracing to the Antivirus service.
> Add tracing to antivirus.

- tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature
- tests/acceptance/features/apiSpaces/quota.feature
- tests/acceptance/features/apiSpaces/uploadSpaces.feature
- tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
- tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
- tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
- tests/acceptance/features/coreApiSharePublicLink3/uploadToPublicLinkShare.feature
back port https://github.com/owncloud/ocis/pull/7095
fix some of the steps ordering in the tests
> [tests-only][backport] Fix the test step ordering

- services/postprocessing/pkg/command/server.go
- services/postprocessing/pkg/config/config.go
- services/postprocessing/pkg/config/tracing.go
- services/postprocessing/pkg/service/service.go
This adds tracing to the postprocessing service.
> Add tracing to postprocessing service

- tests/acceptance/features/apiSpacesDavOperation/updateFileByFileId.feature
- tests/acceptance/features/bootstrap/FeatureContext.php
This PR adds the test scenarios for updating the content of a file inside personal space, project space, inside sub-folder, and shared files/folders.
The added test is done with and without `remote.php`, in the destination URL.
- `/remote.php/dav/spaces/<fileId>`
- `/dav/spaces/<fileId>`
> [tests-only][full-ci] added test to update file using file id

- services/policies/pkg/command/server.go
- services/policies/pkg/config/config.go
- services/policies/pkg/config/defaults/defaultconfig.go
- services/policies/pkg/config/tracing.go
- services/policies/pkg/service/event/service.go
This adds tracing to the policies service.
Note: I don't know how to trigger so that the policies service receives events, so please test that part since I'm not sure if that works properly.
> Add tracing to policies service

- tests/acceptance/features/apiSpacesDavOperation/updateFileByFileId.feature
- tests/acceptance/features/bootstrap/FeatureContext.php
This PR backports https://github.com/owncloud/ocis/pull/6990
> [tests-only][full-ci] Backport added test to update file using file id 

- docs/ocis/development/deprecating-variables.md
The text how deprecation works was not clear enough. This is now fixed.
> [docs-only] Update deprecating-variables.md

- docs/services/app-registry/apps.md
Clarify, app icons URL are only examples
- https://github.com/owncloud/core/issues/40953
- test case 1:
- test case 2:
- ...
> Update app icon example URL's

- services/userlog/pkg/server/http/server.go
- services/userlog/pkg/service/http.go
- services/userlog/pkg/service/options.go
- services/userlog/pkg/service/service.go
- services/userlog/pkg/service/service_test.go
This passes the treaceprovider to more places where it belongs
and also adds tracing to the event processing.
> Add tracing to more places in userlog.

- services/search/pkg/engine/bleve.go
- services/search/pkg/engine/bleve_test.go
- services/search/pkg/search/service.go
- test case 1:
- test case 2:
- ...
> [full-ci] fix: disallow sharee to search sharer files outside the share

- services/search/pkg/engine/bleve.go
- services/search/pkg/engine/bleve_test.go
- services/search/pkg/search/service.go
Backmerge of the hotfix https://github.com/owncloud/ocis/pull/7184
Fixes https://github.com/owncloud/ocis/issues/7092
> [full-ci] 4.0.1 Hotfix Backmerge

- tests/acceptance/features/apiContract/spacesReport.feature
- tests/acceptance/features/bootstrap/SpacesContext.php
Backport of PR: https://github.com/owncloud/ocis/pull/7190
> [tests-only][full-ci]Check multistatus response strictly in test code

- Dockerfile
- ocis/docker/Dockerfile.linux.amd64
- ocis/docker/Dockerfile.linux.arm64
This bumps the docker base images of our Dockerfile to more recent versions.
> Bump base images for Dockerfiles

- tests/acceptance/features/apiSearch/apiSpaceSearch.feature
I added case for https://github.com/owncloud/enterprise/issues/6000 issue
> [test-only] apiTest. user cannot find not shared data

- services/proxy/pkg/command/server.go
> actually use skip user info config option

- services/graph/pkg/identity/ldap.go
"error" log level is definitely wrong here.
> Fix wrong log-level for debug output

- tests/TestHelpers/EmailHelper.php
- tests/TestHelpers/GraphHelper.php
- tests/TestHelpers/WebDavHelper.php
- tests/acceptance/features/apiContract/copy.feature
- tests/acceptance/features/apiContract/propfind.feature
- tests/acceptance/features/apiContract/sharesReport.feature
- tests/acceptance/features/apiContract/spacesReport.feature
- tests/acceptance/features/apiContract/spacesSharesReport.feature
- tests/acceptance/features/bootstrap/ArchiverContext.php
- tests/acceptance/features/bootstrap/NotificationContext.php
- tests/acceptance/features/bootstrap/SearchContext.php
- tests/acceptance/features/bootstrap/SettingsContext.php
- tests/acceptance/features/bootstrap/SpacesContext.php
- tests/acceptance/features/bootstrap/TagContext.php
- tests/acceptance/features/bootstrap/WebDavLockingContext.php
This PR backports PR https://github.com/owncloud/ocis/pull/7085
- Fixes https://github.com/owncloud/ocis/issues/7022
> [tests-only][full-ci] backport send X-Request-Id in header of every request

- tests/acceptance/features/bootstrap/AppConfigurationContext.php
- tests/acceptance/features/bootstrap/AuthContext.php
- tests/acceptance/features/bootstrap/FeatureContext.php
This pr backports https://github.com/owncloud/ocis/pull/7186 from master
> [tests-only][full-ci] backport removing the setresponse in given/then step in AppConfigurationContext and AuthContext

- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/bootstrap/WebDav.php
- tests/acceptance/features/coreApiWebdavPreviews/previews.feature
This PR forward ports PR https://github.com/owncloud/ocis/pull/7218
> [tests-only][full-ci ]Forwardport add test coverage for file preview using space dav version

- changelog/unreleased/passwod-policies-renaming.md
- go.mod
- go.sum
- services/frontend/README.md
- services/frontend/pkg/config/config.go
- services/frontend/pkg/revaconfig/config.go
- vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/data/capabilities.go
- vendor/modules.txt
- References: #7195
- Fixes OCIS-3767
The variables renaming
- test case 1:
- test case 2:
- ...
> the variables renaming

- changelog/unreleased/change-default-config-tus.md
- services/frontend/pkg/config/defaults/defaultconfig.go
We changed the default TUS chunk size from 100MB to 10MB. You can still use the old value by configuring it in your deployment.
- test case 1:
- test case 2:
- ...
> change the default value for TUS

- tests/TestHelpers/WebDavHelper.php
- tests/acceptance/features/apiSearch/apiSpaceSearch.feature
- tests/acceptance/features/apiSearch/contentSearch.feature
- tests/acceptance/features/apiSearch/tagSearch.feature
- tests/acceptance/features/bootstrap/WebDav.php
While checking the file entry in the profind response, the existing code checks with the ends with the method which results false positive outcome.
https://github.com/owncloud/ocis/blob/96e5e2e1ba3dddf965edeb51cdad2378e29414c5/tests/acceptance/features/bootstrap/WebDav.php#L5310-L5313
In this PR the entry name is checked strictly with a response from propfind result
Fixes https://github.com/owncloud/ocis/issues/7006
> [tests-only][full-ci] Check the file entries' full path in REPORT response

- docs/helpers/markdowncreation.go
Fixes Markdown creation for new services
> [docs-only] Fix Markdown creation for new services

- docs/services/general-info/additional-information.md
> [docs-only] Fix docs typo

- changelog/2.0.0_2022-11-30/fix-search-report.md
Fixes wrong changelog reference from: https://github.com/owncloud/ocis/pull/4485
> [docs-only] Fix changelog reference

- docs/ocis/adr/0022-sharing-and-space-management-api.md
Adds  front matter block in ADR For sharing and space management api
```
date: 2023-09-08T02:29:00+01:00
weight: 22
geekdocRepo: https://github.com/owncloud/ocis
geekdocEditPath: edit/master/docs/ocis/adr
geekdocFilePath: 0022-sharing-and-space-management-api.md
```
- Before 
- After
> [docs-only]Add front matter block in ADR for sharing and space management api

- tests/acceptance/features/bootstrap/TagContext.php
- tests/acceptance/features/bootstrap/TrashbinContext.php
This pr backports https://github.com/owncloud/ocis/pull/7261 to stable-4.0 from master
> [tests-only][full-ci] backport removing the setresponse in given/then step in TrashbinContext and TagsContext

- tests/TestHelpers/WebDavHelper.php
- tests/acceptance/features/apiSearch/apiSpaceSearch.feature
- tests/acceptance/features/apiSearch/contentSearch.feature
- tests/acceptance/features/apiSearch/tagSearch.feature
- tests/acceptance/features/bootstrap/WebDav.php
This PR is backport of master PR https://github.com/owncloud/ocis/pull/7007
> [tests-only][full-ci] Backport refactor step search result should contain only these files

- changelog/unreleased/add-passwod-banned-password-list.md
- go.mod
- go.sum
- services/frontend/README.md
- services/frontend/pkg/command/server.go
- services/frontend/pkg/config/config.go
- services/frontend/pkg/revaconfig/config.go
- tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature
- vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocdav/put.go
- vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/data/capabilities.go
- vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/public.go
- vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/shares.go
- vendor/github.com/cs3org/reva/v2/pkg/password/password_policies.go
- vendor/modules.txt
Added an option to enable a password check against a Banned-Password List
- Fixes [https://jira.owncloud.com/browse/OCIS-3809](urhttps://jira.owncloud.com/browse/OCIS-3809)
- test case 1:
- test case 2:
- ...
> Added an option to enable a password check against a Banned-Password List

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiSearch/dateSearch.feature
- tests/acceptance/features/apiSearch/tagSearch.feature
- tests/acceptance/features/bootstrap/SearchContext.php
- tests/acceptance/features/bootstrap/SpacesTUSContext.php
- tests/ban.txt
- related https://github.com/owncloud/ocis/pull/7263
> [test-only] ApiTest. search by date

- services/search/pkg/search/events.go
aaaaand another panic prevented
> prevent panic when user is nil

- services/idp/pkg/backends/cs3/identifier/session.go
> prevent panic when session is nil

- services/settings/pkg/store/metadata/cache.go
> store: decrease log level

- tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature
- tests/acceptance/features/bootstrap/OcisConfigContext.php
- tests/acceptance/filesForUpload/bannedPassword/banned-password-list.txt
tests for: #https://github.com/owncloud/ocis/pull/7315
> [test-only] apiTest. banned password list

- tests/acceptance/features/bootstrap/FeatureContext.php
- tests/acceptance/features/bootstrap/SettingsContext.php
- tests/acceptance/features/bootstrap/SpacesTUSContext.php
- tests/acceptance/features/bootstrap/TUSContext.php
This pr backports https://github.com/owncloud/ocis/pull/7298 from master to stable-4.0
> [tests-only][full-ci] backport refactoring the setresponse in given/then step in settings and tus contexts

- tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
- tests/acceptance/features/bootstrap/SpacesContext.php
Backport of PR : https://github.com/owncloud/ocis/pull/7308
> [tests-only][full-ci]Added test for the copy with file-id in url

- go.mod
- go.sum
- vendor/github.com/cs3org/reva/v2/pkg/appctx/ctxmap.go
- vendor/github.com/cs3org/reva/v2/pkg/store/store.go
- vendor/modules.txt
bring https://github.com/cs3org/reva/pull/4214 to ocis stable 4
> [full-ci] Stable 4.0 bump reva

- changelog/unreleased/bump-reva.md
add changelog for https://github.com/owncloud/ocis/pull/7350
> add reva bump changelog

- tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
- tests/acceptance/features/bootstrap/SpacesContext.php
This PR backports: https://github.com/owncloud/ocis/pull/7318
> [tests-only][full-ci]Backport move byfileid

- tests/acceptance/features/apiSpacesShares/shareOperations.feature
- tests/acceptance/features/bootstrap/SpacesContext.php
- tests/acceptance/features/bootstrap/WebDav.php
- tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
- tests/acceptance/features/coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature
- tests/acceptance/features/coreApiWebdavProperties1/createFileFolder.feature
- tests/acceptance/features/coreApiWebdavProperties2/getFileProperties.feature
This pr backports https://github.com/owncloud/ocis/pull/7368 from master to stable-4.0
> [tests-only] [full-ci] backport refactor set response in given/when/then step in webdavproperties context

- changelog/unreleased/default-async-uploads.md
- services/search/pkg/config/defaults/defaultconfig.go
- services/storage-users/pkg/config/defaults/defaultconfig.go
Sets default for async uploads to true
> [full-ci] Set default AsyncUploads to true

- tests/TestHelpers/HttpRequestHelper.php
- tests/acceptance/features/apiNotification/emailNotification.feature
- tests/acceptance/features/bootstrap/Sharing.php
- tests/acceptance/features/bootstrap/SpacesContext.php
- tests/acceptance/features/bootstrap/WebDav.php
> [tests-only] Fix share creation methods

- tests/acceptance/features/bootstrap/SearchContext.php
- tests/acceptance/features/bootstrap/WebDav.php
- tests/acceptance/features/coreApiWebdavOperations/search.feature
In this PR,
- function `findEntryFromPropfindResponse` is refactor for strictly path checking
- method REPORT is removed from function `findEntryFromPropfindResponse` since there is separate function make for REPORT which is `findEntryFromSearchResponse`.
Closes https://github.com/owncloud/ocis/issues/7006
- locally
- CI
> [tests-only][full-ci] refactor profind response

- tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
This PR is backport of master PR https://github.com/owncloud/ocis/pull/7398
> [tests-only][full-ci] Backport add test for copy with fileID (#7398)

- services/sse/pkg/service/service.go
Sends the type in the `event` field of the sse notification
> [tests-only] Adjust SSE Notification

- tests/acceptance/features/bootstrap/SearchContext.php
- tests/acceptance/features/bootstrap/WebDav.php
- tests/acceptance/features/coreApiWebdavOperations/search.feature
This PR is backport of master PR https://github.com/owncloud/ocis/pull/7327
> [tests-only][full-ci] Backport refactor profind response (#7327)

- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/bootstrap/AuthContext.php
- tests/acceptance/features/coreApiAuthOcs/ocsDELETEAuth.feature
- tests/acceptance/features/coreApiAuthOcs/ocsGETAuth.feature
- tests/acceptance/features/coreApiAuthOcs/ocsPUTAuth.feature
Fixed steps that were not working previously
> [tests-only] Fix API test steps

- tests/acceptance/features/apiGraph/createUser.feature
- tests/acceptance/features/apiGraph/deleteUser.feature
- tests/acceptance/features/apiGraph/editUser.feature
- tests/acceptance/features/bootstrap/GraphContext.php
- tests/acceptance/features/bootstrap/Provisioning.php
This PR refactors the user creation feature file steps so that all the steps used in the entire file will be coherent and meaningful. No test code is changed in the process.
- locally
- ci
> [tests-only] [full-ci] refactored feature file related to GraphAPI steps

- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/bootstrap/AuthContext.php
- tests/acceptance/features/coreApiAuthOcs/ocsDELETEAuth.feature
- tests/acceptance/features/coreApiAuthOcs/ocsGETAuth.feature
- tests/acceptance/features/coreApiAuthOcs/ocsPUTAuth.feature
> [tests-only] Fix API test steps (#7457)

- services/settings/README.md
Just two small doc fixes for the settings service.
> [docs-only] Update README.md of the settings service

- services/frontend/README.md
The readme of the frontend service was not in line with the changes made in the code.
Found while working on: https://github.com/owncloud/docs-ocis/pull/640 (Add the password policy to the frontend service).
> [docs-only] Update frontend service README.md

- tests/TestHelpers/HttpLogger.php
Enhancement to https://github.com/owncloud/ocis/pull/7371
> [tests-only] Add query params to the API calls log

- .drone.star
- tests/TestHelpers/HttpLogger.php
- tests/TestHelpers/HttpRequestHelper.php
- tests/acceptance/.gitignore
- tests/acceptance/features/apiDownloads/download.feature
- tests/acceptance/features/bootstrap/FeatureContext.php
Port PRs https://github.com/owncloud/ocis/pull/7371 and https://github.com/owncloud/ocis/pull/7493
> [tests-only] Log requests and responses for the failing tests

- changelog/unreleased/access-token-issuer.md
- ocis-pkg/oidc/client.go
- ocis-pkg/oidc/metadata.go
backport https://github.com/owncloud/ocis/pull/7140 to stable4
> Backport ADFS access token issuer to stable 4

- changelog/unreleased/bump-reva.md
- go.mod
- go.sum
- vendor/github.com/cs3org/reva/v2/pkg/utils/ldap/identity.go
- vendor/modules.txt
to get fix for https://github.com/owncloud/ocis/issues/7469
> [full-ci] bump reva to 2.16.2

- tests/acceptance/features/bootstrap/SpacesContext.php
Sometimes while listing own spaces `/me/drives/`, newly created/shared/edited spaces were not listed in the response (could be due to indexing?). So, inorder to fix that this PR implements retry drives listing for certain number until required space is found.
Test passes on retry:
```feature
Scenario: user space admin set readme file as description of the space via the Graph API                                                  # /drone/src/tests/acceptance/features/apiSpaces/changeSpaces.feature:150
Given user "Alice" has created a folder ".space" in space "Project Jupiter"                                                             # SpacesContext::userHasCreatedAFolderInSpace()
And user "Alice" has uploaded a file inside space "Project Jupiter" with content "space description" to …
```
> [tests-only] Retry space listing if required space is not found

- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
- tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
- tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
- tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
- tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesPendingFiltered.feature
- tests/acceptance/features/coreApiWebdavPreviews/previews.feature
fix tests from https://github.com/owncloud/ocis/issues/7504
> [test-only] fix tests after auto-accepting enabling

- docs/ocis/adr/0023-index-and-store-metadata.md
In the second the original PR merged I realised I had forgotten something 😂
> [docs-only] Mark index and store metadata ADR accepted and add deciders

- .drone.star
- Makefile
- sonar-project.properties
Backport PR https://github.com/owncloud/ocis/pull/7537
> [full-ci] run linter and unit test from top-level

- tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
This PR is backport of master PR https://github.com/owncloud/ocis/pull/7495
> [tests-only][full-ci] Backport copy file between personal and project space with file

- changelog/unreleased/fix-token-storage-config-web.md
- services/web/pkg/config/options.go
Bugfix: Token storage config fixed
The token storage config in the config.json for web was missing when it was set to `false`.
```json
{
"server": "https://localhost:9200",
"theme": "https://localhost:9200/themes/owncloud/theme.json",
"openIdConnect": {
"metadata_url": "https://localhost:9200/.well-known/openid-configuration",
"authority": "https://localhost:9200",
"client_id": "web",
"response_type": "code",
"scope": "openid profile email"
},
"apps": [
"files",
"search",
"text-editor",
"pdf-viewer",
"external",
"admin-settings"
],
"external_apps": [
{
"id": "preview",
"path": "web-app-preview",
"config": {
"mimeTypes": [
"image/tiff",
"image/bmp",
"image/x-ms-bmp",
"image/heic"
]
}
}
],
"options": {
"previewFileMimeTypes": [
"image/gif",
"image/png",
"image/jpeg",
"text/plain", …
```
> [Backport] fix token storage config for web

- .drone.star
- deployments/examples/ocis_wopi/docker-compose.yml
keep office integrations up to date
keep office integrations up to date
- wopi validator tests
- run wopi deployment example
> bump wopi server, collabora and onlyoffice for deployment examples and ci

- changelog/unreleased/auto-accept-shares.md
Changes `Enhancement` -> `Change`
> [docs-only] Auto Accept Shares is a Change

- tests/TestHelpers/SharingHelper.php
- tests/acceptance/features/apiSpaces/filePreviews.feature
- tests/acceptance/features/bootstrap/Sharing.php
- tests/acceptance/features/bootstrap/SpacesContext.php
This PR adds test scenarios for previewing the shared resource inside of project space. Added scenarios:
- Scenario Outline: download preview of shared file inside project space
- Scenario: download preview of shared file inside sub folder in project space
- https://github.com/owncloud/ocis/issues/6752
> [tests-only][full-ci] added test for previewing shared resource inside project space

- tests/TestHelpers/SharingHelper.php
- tests/acceptance/features/apiSpaces/filePreviews.feature
- tests/acceptance/features/bootstrap/Sharing.php
- tests/acceptance/features/bootstrap/SpacesContext.php
This PR backports https://github.com/owncloud/ocis/pull/7544
> [tests-only][full-ci] backport added test for previewing shared resource inside project space

- changelog/unreleased/readable-share-enforce-password.md
- test case 1:
- test case 2:
- ...
> [docs-only] Fix changelog

- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/apiGraph/addUserToGroup.feature
- tests/acceptance/features/bootstrap/GraphContext.php
- tests/acceptance/features/bootstrap/Provisioning.php
- tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
- tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
This PR backports to https://github.com/owncloud/ocis/pull/7360
> [tests-only] [full-ci]  backporting the PR related to user addition to group to graphapi

- .drone.star
- tests/acceptance/check-deleted-suites-in-expected-failure.sh
Backport of PR : https://github.com/owncloud/ocis/pull/7639
> [tests-only][full-ci]Backport of check for deleted scenarios in expected to failure file

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/user-story.md
Adding a user story issue template...
> chore: update issue templates

- services/search/README.md
References: #7553 (enhancement: improve content extraction stop word cleaning)
Making the term `stop word` and the use of the envvar more clear.
> [docs-only] Update search README.md

- services/graph/pkg/service/v0/service.go
To align with the current spec.
> Make v1beta1/roleManagement/permissions/roleDefinitions/ beta

- docs/apis/http/tus_upload.md
- test case 1:
- test case 2:
- ...
> [docs-only] Update tus_upload.md

- .gitignore
- docs/apis/http/webdav/_index.md
Document the WebDAV Api.
- test case 1:
- test case 2:
- ...
> [docs-only] WebDAV Api docs

- changelog/unreleased/fix-last-month-search.md
- services/search/pkg/query/kql/cast.go
- services/search/pkg/query/kql/dictionary_test.go
Fix the last month edge case when currently is 31-th [https://github.com/golang/go/issues/31145](https://github.com/golang/go/issues/31145)
- Fixes [https://github.com/owncloud/ocis/issues/7629](https://github.com/owncloud/ocis/issues/7629)
- unit tests added
> fix last month search

- changelog/unreleased/fix-space-unlock.md
- Fixes [https://github.com/owncloud/ocis/issues/7708](https://github.com/owncloud/ocis/issues/7708)
- Related changes [https://github.com/cs3org/reva/pull/4338](https://github.com/cs3org/reva/pull/4338)
- test case 1: Try to lock and unlock the file
```bash
curl --location --request LOCK 'https://:9200/dav/spaces/fileID' \
--header 'timeout: Second-3600' \
--header 'Content-Type: application/xml' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data '<?xml version='\''1.0'\'' encoding='\''UTF-8'\''?>
<d:lockinfo xmlns:d='\''DAV:'\''>
<d:lockscope>
<d:shared/>
</d:lockscope>
</d:lockinfo>'
```
```bash
curl --location --request UNLOCK 'https://:9200/dav/spaces/fileID' \
--header 'Lock-Token: <file-lock-token>' \
--header 'Content-Type: application/xml' \
--header …
```
> [full-ci] fix space unlock

- changelog/unreleased/allow-configuring-additional-routes.md
- services/proxy/pkg/config/config.go
- services/proxy/pkg/config/defaults/defaultconfig.go
Allows configuring custom routes in the ocis proxy. This enables development of custom ocis extensions
> Allow configuring custom proxy routes

- services/clientlog/pkg/service/events.go
- services/clientlog/pkg/service/service.go
- test case 1:
- test case 2:
- ...
> feat: Add parentitemid to FileReadyEvent

- services/proxy/README.md
Fixes: #7749 (Proxy service readme update needed)
Documents proxy route configuration
> [docs-only] Add documentation for proxy routes

- tests/acceptance/features/apiLocks/unlockFiles.feature
- tests/acceptance/features/bootstrap/WebDavLockingContext.php
- Part of: https://github.com/owncloud/ocis/issues/7625
> [tests-only]tests: add tests for unlocking using file id

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
This PR is backported from master PR https://github.com/owncloud/ocis/pull/7606
> [tests-only][full-ci] Backport add step move for shares with file

- tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
Unskip share related test which was skipped in PR #7556
> [tests-only] Unskip share test

- tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
This PR is backport PR of master https://github.com/owncloud/ocis/pull/7535
> [tests-only][full-ci]add tests for move rename file between personal and project space with file id

- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiLocks/lockFiles.feature
- tests/acceptance/features/apiLocks/unlockFiles.feature
- tests/acceptance/features/bootstrap/WebDavLockingContext.php
-  part of: https://github.com/owncloud/ocis/issues/7625
> [tests-only][full-ci]tests: add test for lock/unlock in public link share

- tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
This PR is a backport of master PR https://github.com/owncloud/ocis/pull/7653
> [tests-only][full-ci] Backport add test for move and rename file between space in project-space

- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/bootstrap/GraphContext.php
- tests/acceptance/features/bootstrap/Provisioning.php
- tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
This PR refactors the user removal to group test code from ocs api to graphapi
- locally
- ci
> [tests-only][full-ci] refactoring user remove from group test code 

- tests/acceptance/features/bootstrap/SpacesContext.php
- tests/acceptance/features/bootstrap/WebDavLockingContext.php
Followup of this review https://github.com/owncloud/ocis/pull/7780#discussion_r1402939324 in PR https://github.com/owncloud/ocis/pull/7780
> [tests-only][full-ci]tests: refactor send profind request to space function

- tests/acceptance/features/bootstrap/GraphContext.php
- tests/acceptance/features/bootstrap/Provisioning.php
- tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
This PR backports https://github.com/owncloud/ocis/pull/7380
> [tests-only][full-ci] use graph api to remove remove user from group

- tests/acceptance/features/apiSearch/mediaTypeSearch.feature
- tests/acceptance/features/bootstrap/SpacesContext.php
This PR adds the test for searching files using media type `<oc:pattern>mediatype:(&quot;pdf&quot;)</oc:pattern>`. 
- https://github.com/owncloud/ocis/issues/7825
> [tests-only][full-ci]add tests for search files using media type

- services/graph/pkg/service/v0/users_filter.go
This PR makes the contains and startsWith filter case insensitive.
> make user filter contains and startsWith case insensitive

- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
- tests/acceptance/features/coreApiWebdavOperations/propfind.feature
This PR backports to https://github.com/owncloud/ocis/pull/7856
> [tests-only] adding skip on reva tag (#7856)

- tests/TestHelpers/SharingHelper.php
- tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
- tests/acceptance/features/bootstrap/Sharing.php
- tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
Part of: https://github.com/owncloud/ocis/issues/7823
> [tests-only][full-ci]tests: add tests for update public link to delete password (permission `0`)

- .drone.star
Separate k6 tess pipeline so that it doesn't depend on or block other pipelines
> [tests-only][ci] separate k6 tests pipeline

- tests/ociswrapper/ocis/ocis.go
> [tests-only] remove unnecessary checks

- Dockerfile
> Dockerfile: Bump go version to the require go1.21 release

- .drone.env
- changelog/unreleased/update-web-8.0.0-alpha.13.md
- services/web/Makefile
> [full-ci] chore: bump web to v8.0.0-alpha.13

- .drone.star
Fix changelog build process
- test case 1:
- test case 2:
- ...
> ci: fix changelog build for prereleases

- .drone.star
- deployments/examples/ocis_wopi/docker-compose.yml
keep the wopi server up to date
- https://github.com/cs3org/wopiserver/compare/v10.2.0...v10.2.2
prevent bitrot
- WOPI validator in CI only
> update wopiserver to v10.2.2

- docs/ocis/deployment/ubernauten.md
Added information about certificates and updates with supervisorctl running
> [DOCS-ONLY] certificates and updates with supervisorctl

- ocis/pkg/init/init.go
- test case 1:
- test case 2:
- ...
> apply ocis init insecure option also to FRONTEND_APP_HANDLER_INSECURE

- changelog/unreleased/retry-postprocessing-steps.md
> Add changelog for the retry postprocessing change

- changelog/unreleased/fix-return-code-password-policy.md
- services/graph/pkg/service/v0/links.go
Relates to #6993 
- test case 1:
- test case 2:
- ...
> fix: missing return statement

- tests/ociswrapper/ocis/ocis.go
Recently, there are some builds that has error trying to restart ocis server. So, I want to revert PR https://github.com/owncloud/ocis/pull/7903 and see if it was helpful.
> [tests-only][full-ci] Revert wrapper cleanup #7903

- docs/apis/http/tus_upload.md
Improve tus docs based on feedback in:
- #7882
This helps to align x-platform client implementations.
> [docs-only] TUS - incorporate feedback from #7882

- services/webfinger/README.md
Example response shows an user account, but it isn't known at this stage.
```bash
curl -s "https://ocis.ocis-keycloak.latest.owncloud.works/.well-known/webfinger?resource=https://ocis.ocis-keycloak.latest.owncloud.works" | jq
{
"subject": "https://ocis.ocis-keycloak.latest.owncloud.works",
"links": [
{
"rel": "http://openid.net/specs/connect/1.0/issuer",
"href": "https://keycloak.ocis-keycloak.latest.owncloud.works/realms/oCIS"
}
]
}
```
> [docs-only] Fix inconsistency in unauthenticated WebFinger example response

- Makefile
- changelog/unreleased/ocm.md
- ocis/pkg/command/services.go
Add the ocm subcommand to ocis
> Add the ocm subcommand to ocis

- changelog/unreleased/fix-upload-session-purging.md
- services/storage-users/pkg/command/uploads.go
fixes https://github.com/owncloud/ocis/pull/7941/files#r1424043826
> fix upload purge filter and naming

- services/gateway/README.md
> [docs-only] Update Gateway Readme

- .drone.star
Port PR https://github.com/owncloud/ocis/pull/7974
> [tests-only][full-ci] wait for ocis server with timeout (5 mins timeout)

- changelog/unreleased/fix-permissions-duplicate.md
- services/settings/pkg/store/defaults/defaults.go
Removed the permissions of a role with duplicate ID
- Fixes [https://github.com/owncloud/ocis/issues/7931](https://github.com/owncloud/ocis/issues/7931)
- test case 1:
- test case 2:
- ...
> [full-ci] remove the permissions of a role with duplicate ID

- tests/ociswrapper/ocis/ocis.go
Prevent panic due to closed channel
https://drone.owncloud.com/owncloud/ocis/30150/14/3
```go
2023/12/18 04:23:26 [ociswrapper] Stopping oCIS server...
panic: send on closed channel
goroutine 263 [running]:
ociswrapper/ocis.Start.func1()
/drone/src/tests/ociswrapper/ocis/ocis.go:61 +0x4f
created by ociswrapper/ocis.Start in goroutine 377
/drone/src/tests/ociswrapper/ocis/ocis.go:59 +0x449
```
> [full-ci][tests-only] Close channel after log scanner has completed

- go.mod
- go.sum
- vendor/github.com/studio-b12/gowebdav/client.go
- vendor/modules.txt
Sync gowebdav client with reva edge
> Sync gowebdav client with reva edge

- changelog/unreleased/default-registry.md
- ocis-pkg/registry/registry.go
Fixes small mistake done during default registry implementation and  not found on review.
> Fix default registry

- tests/acceptance/features/apiSharingNg/shareInvitations.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
This PR adds a test for the new sharing graph API.
```feature
- Scenario Outline: send share invitation to group with different roles
```
- Locally
- :robot:
> [full-ci] [tests-only] Added test for sending share invitation to group with role

- tests/acceptance/features/bootstrap/GraphContext.php
- tests/acceptance/features/bootstrap/Provisioning.php
This PR is a backport of master PR https://github.com/owncloud/ocis/pull/7864
> [tests-only][full-ci][backport] Remove OCS endpoint for group creation

- changelog/unreleased/service-account-roles.md
- ocis/pkg/init/init.go
- services/settings/pkg/store/metadata/bundles.go
https://github.com/owncloud/ocis/pull/8051 had some bugs not found by ci and review. Luckily QA did catch the error.
Fixes https://github.com/owncloud/ocis/issues/8068
> Fix Service Account Roles for external IDPs

- changelog/unreleased/service-account-roles.md
- ocis/pkg/init/init.go
- services/settings/pkg/store/metadata/bundles.go
Backport of #8074 
- test case 1:
- test case 2:
- ...
> [full-ci] [backport] Fix roles

- tests/TestHelpers/GraphHelper.php
- tests/acceptance/features/apiSharingNg/shareInvitations.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
This PR adds a test for sending share invitation to user with different permissions.
```feature
- Scenario Outline: send share invitation for a file to user with different permissions
- Scenario Outline: send share invitation for a folder to user with different permissions
```
- Locally
- :robot:
> [full-ci] [tests-only] Added test for sending share invitation to user with permissions

- tests/TestHelpers/GraphHelper.php
- tests/acceptance/features/apiSharingNg/shareInvitations.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
Backport PR https://github.com/owncloud/ocis/pull/8046, https://github.com/owncloud/ocis/pull/8047
> [full-ci] [tests-only] Backport PR 8046, 8047

- tests/TestHelpers/GraphHelper.php
- tests/acceptance/features/apiSharingNg/shareInvitations.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
- Scenario Outline: send share invitation with expiration date to user with different roles
- Scenario Outline: send share invitation with expiration date to group with different roles
- Locally
- :robot:
> [full-ci] [tests-only] Added test for share invitation with expiration date

- tests/acceptance/features/bootstrap/SpacesContext.php
Port PR #7521
Stable-4 is also facing `space not found` errors now: https://drone.owncloud.com/owncloud/ocis/30487/12/5
> [tests-only] Retry space listing if required space is not found (#7521)

- tests/TestHelpers/GraphHelper.php
- tests/acceptance/features/apiSharingNg/shareInvitations.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
Forward port of PR https://github.com/owncloud/ocis/pull/8092
> [full-ci] [tests-only] Forward port of PR #8092

- tests/acceptance/features/coreApiWebdavUpload1/uploadFile.feature
In this PR, added test to update file with empty content.
```feature
Scenario Outline: user updates a file with empty content
Scenario Outline: user updates a file inside a folder with empty content
Scenario Outline: user updates a shared file with empty content
Scenario: user updates a file inside a project space with empty content
Scenario: user updates a file inside a shared space with empty content
```
- https://github.com/owncloud/ocis/issues/8044
> [tests-only][full-ci] added test to update a file with empty content

- tests/acceptance/features/coreApiWebdavUpload1/uploadFile.feature
Forward Port PR: https://github.com/owncloud/ocis/pull/8088
> [tests-only][full-ci] forward port added test to update file with empty content

- tests/TestHelpers/GraphHelper.php
- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiSharingNg/linkShare.feature
- tests/acceptance/features/bootstrap/Sharing.php
- tests/acceptance/features/bootstrap/SharingNgContext.php
Backport of PR: https://github.com/owncloud/ocis/pull/8071
> [tests-only][full-ci] Added test to update role and expiration date for share link (sharingNg)

- tests/acceptance/features/coreApiWebdavUpload1/uploadFile.feature
Forward port PR: https://github.com/owncloud/ocis/pull/8093
> [tests-only][full-ci] added issue-7257 tag on scenario

- tests/TestHelpers/GraphHelper.php
- tests/acceptance/features/apiSharingNg/deletePermissions.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
https://owncloud.dev/libre-graph-api/#/drives.permissions/DeletePermission
Scenarios added:
1. Scenario Outline: user removes access from a resource in the user share
2. Scenario Outline: user removes access from a resource inside of a project space in the user share
- Part of: https://github.com/owncloud/ocis/issues/8008
To provide test coverage for `/v1beta1/drives/{drive-id}/items/{item-id}/permissions/{perm-id}` 
- locally
- CI
> [tests-only]tests: add tests for removing share permission

- tests/TestHelpers/GraphHelper.php
- tests/acceptance/features/apiSharingNg/deletePermissions.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
https://owncloud.dev/libre-graph-api/#/drives.permissions/DeletePermission
Scenarios added:
1. Scenario Outline: user removes access to a resource in a group share
2. Scenario Outline: user removes access to a resource inside of a project space in group share
- Part of: https://github.com/owncloud/ocis/issues/8008
To provide test coverage for `/v1beta1/drives/{drive-id}/items/{item-id}/permissions/{perm-id}` 
- locally
- CI
> [tests-only]tests: add tests for removing share permission in group share

- .drone.star
- changelog/unreleased/natsjskv-registry-fix.md
- ocis-pkg/natsjsregistry/registry.go
- ocis-pkg/registry/registry.go
Fixes a leftover of the previous implementation
> Fix nats-js-kv name

- tests/TestHelpers/GraphHelper.php
- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiSharingNg/linkShare.feature
- tests/acceptance/features/bootstrap/PublicWebDavContext.php
- tests/acceptance/features/bootstrap/Sharing.php
- tests/acceptance/features/bootstrap/SharingNgContext.php
Backport of PR : https://github.com/owncloud/ocis/pull/8079
> [tests-only][full-ci]Added tests for setting password in a public share (#8079)

- tests/TestHelpers/GraphHelper.php
- tests/acceptance/features/apiSharingNg/deletePermissions.feature
- tests/acceptance/features/bootstrap/Sharing.php
- tests/acceptance/features/bootstrap/SharingNgContext.php
Part of: https://github.com/owncloud/ocis/issues/8008
- https://github.com/owncloud/ocis/pull/8099
- https://github.com/owncloud/ocis/pull/8098
- https://github.com/owncloud/ocis/pull/8134
> [tests-only] tests: add tests for removing share permission

- tests/acceptance/features/apiGraph/addUserToGroup.feature
- tests/acceptance/features/apiGraph/createUser.feature
- tests/acceptance/features/apiGraph/deleteUser.feature
- tests/acceptance/features/apiGraph/editUser.feature
- tests/acceptance/features/apiGraph/getUser.feature
- tests/acceptance/features/apiGraph/removeUserFromGroup.feature
- tests/acceptance/features/apiSharingNg/shareInvitations.feature
- tests/acceptance/features/bootstrap/GraphContext.php
Forward port https://github.com/owncloud/ocis/pull/8139
> [full-ci] [tests-only] Added test for sending share invitation to disabled user

- deployments/examples/ocis_wopi/docker-compose.yml
forward-port of #8143 to master
> [docs-only] fix NATS configuration in wopi example

- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiSharingNg/deletePermissions.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
fordward port: https://github.com/owncloud/ocis/pull/8128
part of: https://github.com/owncloud/ocis/issues/8008
> [tests-only][fordward-port] Add tests for remove permissions link share

- .drone.star
- tests/config/drone/run_k6_tests.sh
Added a step to show ocis logs in k6 pipeline
> [ci] Add step to show ocis logs in k6 pipeline

- tests/TestHelpers/GraphHelper.php
- tests/acceptance/features/apiSharingNg/shareInvitations.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
Added test to send share invitation to multiple groups at once.
Expected: sharing should fail with status code `400`
> [tests-only][full-ci] added test to send share invitation to multiple groups at once

- tests/TestHelpers/GraphHelper.php
- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiSharingNg/shareInvitations.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
Backport of PR: https://github.com/owncloud/ocis/pull/8167
> [tests-only][full-ci] backport added test to send share invitation to multiple groups at once

- tests/acceptance/features/apiSharingNg/shareInvitations.feature
Added test to send share invitation to user and group at once.
Expected: sharing should fail with status code `400`
> [tests-only][full-ci] added test to send share invitation to user and gruop at once

- tests/acceptance/features/apiSharingNg/reshare.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
In this PR, added test to reshare a share invitation to other user.
```feature
Scenario Outline: reshare a file to user with different roles
Scenario Outline: reshare a folder to user with different roles
Scenario Outline: reshare a file inside project space to a user with different roles
Scenario Outline: reshare a folder inside project space to a user with different roles
```
Currently, user with a role with no sharing permission trying to reshare the share invitation returns `500` status code, mentioned in this issue https://github.com/owncloud/ocis/issues/8112. Those tests will be added in next PR. 
> [tests-only][full-ci] added test to reshare a share invitation to other user

- changelog/unreleased/fix-search-logging.md
> [docs-only] Add changelog

- CHANGELOG.md
- changelog/unreleased/fix-search-logging.md
- changelog/unreleased/fix-upload-reset-logo.md
- services/search/pkg/search/search.go
- services/web/pkg/service/v0/branding.go
Pull in latest changes from master.
> Merge master b758d28 stable 5.0

- changelog/unreleased/disabled-password-policy-rework.md
- services/frontend/README.md
- services/frontend/pkg/revaconfig/config.go
- services/sharing/pkg/revaconfig/config.go
We reworked and moved disabling the password policy logic from the reva to the ocis.
- Fixes [https://github.com/owncloud/ocis/issues/7916](https://github.com/owncloud/ocis/issues/7916)
- test case 1:
- test case 2:
- ...
> rework disabling the password policy

- tests/TestHelpers/UserHelper.php
- tests/acceptance/features/bootstrap/GraphContext.php
- tests/acceptance/features/bootstrap/Provisioning.php
- tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
In this PR, provision API is removed for group deletion
- Part of https://github.com/owncloud/ocis/issues/6998
- locally
- ci
> [tests-only][full-ci] Restructure the steps implementation for group delete to use graph API endpoint

- tests/TestHelpers/UserHelper.php
- tests/acceptance/features/bootstrap/GraphContext.php
- tests/acceptance/features/bootstrap/Provisioning.php
- tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
This PR is backport of master PR https://github.com/owncloud/ocis/pull/8006
> [tests-only][full-ci] Backport Restructure the steps implementation for group deletion

- changelog/unreleased/fix-policies-jwt-config.md
- services/policies/pkg/config/config.go
removes the policies jwt config after #7672
- not at all
> remove jwt config from policies after #7672

- services/proxy/README.md
- test case 1:
- test case 2:
- ...
> [docs-only] Fix proxy debug env name

- tests/TestHelpers/GraphHelper.php
- tests/acceptance/features/apiSharingNg/shareInvitations.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
Modified Scenarios:
- Scenario Outline: send share invitation to user with different roles
- Scenario Outline: send share invitation to group with different roles
Added step to check the existence of share by the recipient.
- locally
- :robot:
> [full-ci] [tests-only] Modified tests so sharee can check for received shares

- tests/acceptance/features/apiSharingNg/shareInvitations.feature
Added test to share resource to an already shared group.
Expected: sharing should fail with status code `409`
```feature
Scenario Outline: send sharing invitation to already shared group
```
> [tests-only][full-ci]added test to share resource to an already shared group

- .drone.star
Added grafana dasboard link to CI
> [test-only] Add grafana link to CI

- changelog/unreleased/fix-deleting-during-postprocessing.md
Disallow to delete a file during the processing.
Related fix [https://github.com/cs3org/reva/pull/4446](https://github.com/cs3org/reva/pull/4446)
- Fixes [https://github.com/owncloud/ocis/issues/8127](https://github.com/owncloud/ocis/issues/8127)
- test case 1:
- test case 2:
- ...
> [skip-ci][changelog] disallow to delete a file during the processing

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiCors/cors.feature
- tests/acceptance/features/bootstrap/SettingsContext.php
added CORS test for settings api: https://github.com/owncloud/ocis/pull/8254
> [test-only] Cors test for settings api

- tests/acceptance/features/apiSharingNg/shareInvitations.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
- Scenario Outline: send share invitation to user with wrong recipient type
- Scenario Outline: send share invitation to group with wrong recipient type
- Locally
- :robot:
> [full-ci] [tests-only] Add test to send share invitation with wrong recipient type

- .github/CODEOWNERS
Removing Paul from code owners
> chore: remove lookacat from code owners

- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
- tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
Fixed the sharing sub-folder scenarios to have the correct steps and assertions
- Related https://github.com/owncloud/ocis/issues/1231
> [tests-only] fix sharing sub-folder test scenario

- tests/acceptance/features/apiSharingNg/shareInvitations.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
- Scenario: send share invitation to user for deleted file
- Scenario: send share invitation to group for deleted file
- Locally
- :robot:
> [tests-only] Add test to share deleted resource

- tests/acceptance/features/apiSharingNg/sharedByMe.feature
This PR adds test scenario to list sharedByMe when resources are shared to a group i.e.
```feature
Scenario: user lists shared resources to a group
```
https://github.com/owncloud/ocis/issues/8111
- locally
- CI
> [tests-only]Added test for list shared by me when shared to group

- .github/release_template.md
Added some new items to release template
> [docs-only] changed release template

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiSharingNg/sharedWithMe.feature
- tests/acceptance/features/bootstrap/SettingsContext.php
- `Scenario: user lists the file shared with them when sync is disabled`
- `Scenario: user lists the folder shared with them when sync is disabled`
- Locally
- :robot:
> [full-ci] [tests-only] Added tests to lists file shared with them when sync is disabled

- tests/acceptance/features/apiSharingNg/sharedWithMe.feature
- `Scenario: group member lists the file shared with them when auto-sync is disabled`
- `Scenario: group member lists the folder shared with them when auto-sync is disabled`
- Locally
- :robot:
> [full-ci] [tests-only] Add tests sharing with group when auto-sync is disabled 

- changelog/unreleased/fix-cs3-backend.md
> [docs-only] Fix unrelease text

- changelog/unreleased/fix-signed-url-expiry.md
- services/proxy/pkg/command/server.go
- services/proxy/pkg/middleware/signed_url_auth.go
- services/proxy/pkg/middleware/signed_url_auth_test.go
- test case 1:
- test case 2:
- ...
> fix: signed url expiry check and signature validation - stable-5.0

- changelog/unreleased/fix-signed-url-expiry.md
- services/proxy/pkg/command/server.go
- services/proxy/pkg/middleware/signed_url_auth.go
- services/proxy/pkg/middleware/signed_url_auth_test.go
- test case 1:
- test case 2:
- ...
> fix: signed url expiry check and signature validation - stable-4.0

- tests/acceptance/features/bootstrap/FeatureContext.php
In this PR, spaceContext substitutions is skip for reva
- locally
- ci
> [tests-only][full-ci] skip spacecontext subsitutions for reva

- docs/templates/ADOC_extended.tmpl
- docs/templates/ADOC_global.tmpl
Fixes two doc adoc templates.
Tested locally, works fine.
> [docs-only] Fixes doc adoc table templates

- .drone.env
- changelog/unreleased/update-web-8.0.0.md
- services/web/Makefile
> [full-ci] bump web to v8.0.0-rc.4

- docs/ocis/adr/0026-application-based-user-settings.md
> [docs-only] ADR-0026 Application based user settings

- docs/ocis/adr/0019-file-search-index.md
- docs/ocis/adr/0025-distributed-search-index.md
> [docs-only] ADR-0025 Distributed Search Index

- docs/ocis/adr/0024-msgpack-metadata.md
forgot the name in the preamble
> [docs-only] fix ADR0024 name

- docs/ocis/adr/0001-introduce-accounts-service.md
- docs/ocis/adr/0002-persist-accounts-using-cs3-storage.md
- docs/ocis/adr/0003-external-user-management.md
- docs/ocis/adr/0004-support-hot-migration.md
- docs/ocis/adr/0005-cs3-api-account-management.md
- docs/ocis/adr/0006-service-discovery.md
- docs/ocis/adr/0007-api-for-spaces.md
- docs/ocis/adr/0008-configuration.md
- docs/ocis/adr/0009-extension-template.md
- docs/ocis/adr/0010-policy-enforcement.md
- docs/ocis/adr/0011-global-url-format.md
- docs/ocis/adr/0012-tracing.md
- docs/ocis/adr/0013-locking.md
- docs/ocis/adr/0014-microservices-runtime.md
- docs/ocis/adr/0015-events.md
- docs/ocis/adr/0016-files-metadata.md
- docs/ocis/adr/0017-allow-read-only-external-user-management.md
- docs/ocis/adr/0018-file-search-api.md
- docs/ocis/adr/0019-file-search-index.md
- docs/ocis/adr/0020-file-search-query-language.md
- docs/ocis/adr/0021-service-accounts.md
- docs/ocis/adr/0022-sharing-and-space-management-api.md
- docs/ocis/adr/0023-index-and-store-metadata.md
- docs/ocis/adr/0024-msgpack-metadata.md
- docs/ocis/adr/0025-distributed-search-index.md
- docs/ocis/adr/0026-application-based-user-settings.md
> link users in adr

- deployments/continuous-deployment-config/ocis_keycloak/latest.yml
- deployments/continuous-deployment-config/ocis_keycloak/released.yml
- deployments/continuous-deployment-config/ocis_ldap/latest.yml
- deployments/continuous-deployment-config/ocis_ldap/released.yml
- deployments/continuous-deployment-config/ocis_s3/latest.yml
- deployments/continuous-deployment-config/ocis_traefik/daily.yml
- deployments/continuous-deployment-config/ocis_traefik/latest.yml
- deployments/continuous-deployment-config/ocis_traefik/released.yml
- deployments/continuous-deployment-config/ocis_wopi/daily.yml
- deployments/continuous-deployment-config/ocis_wopi/latest.yml
- deployments/continuous-deployment-config/ocis_wopi/released.yml
> chore: upgrade deployments

- .drone.env
- changelog/unreleased/update-web-8.0.0.md
- services/web/Makefile
Forward port of #8492
- test case 1:
- test case 2:
- ...
> [forward-port] chore: bump web to v8.0.0-rc.5

- tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
Added scenario:
-  Scenario: user lists the file with same name shared by two users with him/her
-  Scenario: user lists the folder with same name shared by two users with him/her
- Locally
- :robot:
> Sharing resources with same name auto sync disabled

- tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
- tests/acceptance/features/bootstrap/SpacesContext.php
coverage for https://github.com/owncloud/enterprise/issues/6423
> [test-only] share items with share permission if resharing is disabled

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiCors/cors.feature
- tests/acceptance/features/bootstrap/SpacesTUSContext.php
- tests/acceptance/features/bootstrap/TUSContext.php
test for [#8380](https://github.com/owncloud/ocis/issues/8380)
> [test-only] add test for uploading with Tus using CORS

- deployments/continuous-deployment-config/ocis_keycloak/released.yml
- deployments/continuous-deployment-config/ocis_ldap/released.yml
- deployments/continuous-deployment-config/ocis_traefik/released.yml
- deployments/continuous-deployment-config/ocis_wopi/released.yml
QA needs to do the smoke testing on a remote instance.
We update all "released" versions to `v5.0.0-rc.5`.
- test case 1:
- test case 2:
- ...
> ci: use release candidate for released deployments

- .drone.star
Do not deploy from the stable branch.
- test case 1:
- test case 2:
- ...
> [full-ci] ci: do not deploy from stable branch

- changelog/unreleased/fix-default-roles-assignment.md
- services/proxy/pkg/config/defaults/defaultconfig.go
Fix default config for the default role assignment.
- test case 1:
- test case 2:
- ...
> fix: change default config for the role mapping

- changelog/unreleased/fix-default-roles-assignment.md
- services/proxy/pkg/config/defaults/defaultconfig.go
Backport of #8534 
- test case 1:
- test case 2:
- ...
> [backport] fix: change default config for the role mapping

- changelog/unreleased/change-presigned-key-store.md
- ocis/pkg/runtime/service/service.go
- services/ocs/README.md
- services/ocs/pkg/config/config.go
- services/ocs/pkg/config/defaults/defaultconfig.go
- services/ocs/pkg/server/http/server.go
- services/ocs/pkg/service/v0/option.go
- services/ocs/pkg/service/v0/service.go
- services/ocs/pkg/service/v0/users.go
- services/proxy/README.md
- services/proxy/pkg/command/server.go
- services/proxy/pkg/config/config.go
- services/proxy/pkg/config/defaults/defaultconfig.go
- services/proxy/pkg/middleware/options.go
- services/proxy/pkg/middleware/signed_url_auth.go
- services/proxy/pkg/middleware/signed_url_auth_test.go
- services/store/pkg/store/options.go
- services/store/pkg/store/store.go
backport of https://github.com/owncloud/ocis/pull/8419 to stable 5
> Backport configurable store

- .drone.star
sending notification to ~~the matrix channel https://matrix.to/#/#ocis-CI-notification:matrix.org~~ to the https://talk.owncloud.com/channel/infinitescale
> [test-only] send notification to the rocket talk infinitescale channel

- .drone.star
- tests/ociswrapper/cmd/cmd.go
- tests/ociswrapper/ocis/config/config.go
- tests/ociswrapper/ocis/ocis.go
Reverting https://github.com/owncloud/ocis/pull/8085
Add option to allow checking ocis connection by authenticated user.
- Probably Fixes https://github.com/owncloud/ocis/issues/8539
> [tests-only][full-ci] Add option to check ocis connection by authenticating user

- .drone.star
- tests/ociswrapper/cmd/cmd.go
- tests/ociswrapper/ocis/config/config.go
- tests/ociswrapper/ocis/ocis.go
> [tests-only] Port pr #8547 and #8540

- changelog/unreleased/fix-remove-update-share.md
- test case 1:
- test case 2:
- ...
> 8273 changelog

- docs/ocis/identity-provider/oidc.md
Fix link in the docs
- test case 1:
- test case 2:
- ...
> fix: correct link to api docs

- docs/ocis/identity-provider/oidc.md
- test case 1:
- test case 2:
- ...
> fix: link path

- changelog/unreleased/more-sse-events.md
- services/clientlog/pkg/command/server.go
- services/clientlog/pkg/service/events.go
- services/clientlog/pkg/service/service.go
Send sse events when:
- an item is moved to the trashbin
- an item is restored from trashbin
- an item is renamed
- a folder is created
Fixes https://github.com/owncloud/ocis/issues/7568
Fixes https://github.com/owncloud/ocis/issues/7567
Fixes https://github.com/owncloud/ocis/issues/7435
> Additional SSE Events

- docs/ocis/flow-docs/login-flow.md
Improving the Flow Chart by
- test case 1:
- test case 2:
- ...
> [docs-only] Simplify login-flow and add PKCE

- changelog/unreleased/add-spaceid-to-sse.md
- services/clientlog/pkg/service/events.go
- services/clientlog/pkg/service/service.go
Adds the spaceID to all server sent events
> Add SpaceID to SSEs

- .drone.env
- changelog/unreleased/update-web-8.0.0.md
- services/web/Makefile
- tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
> [full-ci] chore: bump web to v8.0.0 final

- changelog/unreleased/add-spaceid-to-sse.md
- services/clientlog/pkg/service/service.go
Fix the spaceid format so it is the same accross all sse events
> Fix format of SpaceID in SSE

- services/storage-users/pkg/config/config.go
Backport of https://github.com/owncloud/ocis/pull/8633 done by a person whose is not *that* expensive.
> [docs-only] Backport infamous typo

- tests/acceptance/features/apiSharingNg/sharedWithMe.feature
- tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
- tests/acceptance/features/bootstrap/FeatureContext.php
This PR refactors the json schema validator function when no of items in the array of schema is less than that of the min max value of the provided json schema.
> [tests-only][full-ci]Refactor check for no of items in json schema

- deployments/continuous-deployment-config/ocis_keycloak/released.yml
- deployments/continuous-deployment-config/ocis_ldap/released.yml
- deployments/continuous-deployment-config/ocis_traefik/released.yml
- deployments/continuous-deployment-config/ocis_wopi/released.yml
Update the "released" deployment examples to the last release candidate.
This is needed for QA purposes.
@individual-it @ScharfViktor @jesmrec @TheOneRing FYI
> chore: update continuous deployments to rc.6

- services/storage-users/README.md
The `storage-users` readme needed an update as it was disaligned from the content of the admin docs. Realigning was upfront discussed with @2403905
> [docs-only] Update storage-users readme

- changelog/unreleased/non-default-multipartuploads.md
- services/storage-users/pkg/config/defaults/defaultconfig.go
5.0 Backport of https://github.com/owncloud/ocis/pull/8666
> [Backport] Disable Multipart Uploads

- tests/acceptance/features/apiContract/propfind.feature
- tests/acceptance/features/apiLocks/lockFiles.feature
- tests/acceptance/features/apiSharingNg/propfindShares.feature
- tests/acceptance/features/apiSpaces/tag.feature
- tests/acceptance/features/bootstrap/SpacesContext.php
- tests/acceptance/features/bootstrap/WebDavLockingContext.php
As sharee, PROPFIND the shares, when two users share resources with the same name using graph API.
- `Scenario: sharee PROPFIND a shares when multiple user shares resources with same name`
- Part of https://github.com/owncloud/ocis/issues/8493
- Locally
- :robot:
> [full-ci] [tests-only] Added tests for PROPFIND as sharee

- services/frontend/pkg/config/defaults/defaultconfig.go
fixes https://github.com/owncloud/ocis/issues/8380
> add PATCH to default allowed CORS methods

- tests/acceptance/features/apiAccountsHashDifficulty/addUser.feature
- tests/acceptance/features/apiAccountsHashDifficulty/assignRole.feature
- tests/acceptance/features/apiAccountsHashDifficulty/createShareToSharesFolder.feature
- tests/acceptance/features/apiAccountsHashDifficulty/uploadFile.feature
kebab-case is used for the example table header name.
- Part of https://github.com/owncloud/QA/issues/829
- :robot:
> [full-ci] [tests-only] Used kebab case for example table header name

- ocis-pkg/middleware/oidc.go
fixes https://github.com/owncloud/ocis/issues/8672 by using a mutex when lazy initializing the OIDC provider
> use mutex when lazy initializing the OIDC provider

- changelog/unreleased/bump-keycloak.md
- deployments/examples/ocis_keycloak/docker-compose.yml
Bump the keycloak version to 24.0.1
- test case 1:
- test case 2:
- ...
> bumps keycloak version

- services/web/README.md
References: https://github.com/owncloud/docs-ocis/pull/754
Web readme needed an alignment and clarification post a discussion with @fschade.
> [docs-only] Align web service readme with admin docs

- tests/acceptance/features/apiSharingNg/propfindShares.feature
As sharee, PROPFIND the resource with bracket in name, when two users share resources with the same name using graph API.
- `Scenario: sharee PROPFIND shares with bracket in the name`
- Part of https://github.com/owncloud/ocis/issues/8493
- Locally
- :robot:
> [full-ci] [tests-only] sharee PROPFINDs on resource containing brackets

- tests/TestHelpers/GraphHelper.php
- tests/acceptance/features/apiSharingNg/acceptDeclineShares.feature
- tests/acceptance/features/apiSharingNg/mountOrUnmountShare.feature
- tests/acceptance/features/bootstrap/FeatureContext.php
- tests/acceptance/features/bootstrap/GraphContext.php
- tests/acceptance/features/bootstrap/SharingNgContext.php
This PR adds test code and feature file for declining an accepted share.
- locally
- CI
> [tests-only][full-ci]added test for declining a share

- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiReshare/resharing.feature
- tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
- tests/acceptance/features/bootstrap/SpacesContext.php
- fix tests which were added to expected failures file here https://github.com/owncloud/ocis/pull/8704/files#diff-733a682a252e8a35d985692d58d7b793107aa0abe81eac800edd774e3415fc07R288-R293
> [test-only] update share without permission

- docs/ocis/deployment/ocis_wopi.md
fixes https://github.com/owncloud/ocis/issues/8757
> fix: pnpm i

- Makefile
Activates pipeline for graph translations.
> [docs-only] Fix graph translation pipeline

- docs/helpers/env_vars.yaml
- docs/helpers/extended_vars.yaml
Regular maintenance, check via `make -C docs docs-generate` for changes.
* Auto fix for `env_vars.yaml` - just merging necessary
* chore: manual fixes for `extended_vars.yaml` applied
> [docs-only] Updates doc process related env_var yaml files

- changelog/unreleased/file-touched-sse.md
- services/clientlog/pkg/command/server.go
- services/clientlog/pkg/service/service.go
Send a sse event when a file is touched (aka 0 byte upload)
> FileTouched SSE

- tests/acceptance/features/apiSharingNg/mountOrUnmountShare.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
Test scenario when one member of the group mounts/unmounts share of the group.
Part of https://github.com/owncloud/ocis/issues/8486
> [tests-only][full-ci]adding scenerio for enable and disable sync feature in group share

- changelog/unreleased/fix-create-personal-space-cache.md
- services/gateway/pkg/revaconfig/config.go
Backport of the cache fix from https://github.com/owncloud/ocis/pull/8799
> Stable 5.0 backport 8799

- docs/apis/http/authorization.md
- docs/ocis/development/testing.md
- docs/ocis/identity-provider/oidc.md
This PR updates the test scenario line number and feature file name. Adds link to oidc doc
- Fixes https://github.com/owncloud/ocis/issues/8572
- locally
> [docs-only]Update docs outdated content

- docs/helpers/env_vars.yaml
- docs/services/app-registry/_index.md
Autogenerated updates from `make -C docs docs-generate`, these need to be checked in manually.
> [docs-only] [chore] Autogenerated updates from 'make -C docs docs-generate'

- .drone.star
With this PR, notification will be sent on rocketchat for successful builds in nightly.
> [tests-only][full-ci] notify chat also on nightly success

- .drone.star
This PR updates the `.drone.star` file to manage pipelines in order of the trigger time.
> [tests-only][full-ci] updated drone file to display pipeline in order by trigger

- .drone.star
Backport of PR: https://github.com/owncloud/ocis/pull/8832
> [tests-only][full-ci] backport notify chat on nightly success also

- .drone.star
Backport of PR: https://github.com/owncloud/ocis/pull/8823
> [tests-only][full-ci] backport updated drone file to display pipeline in order by trigger (#8823)

- .drone.star
Renamed the e2e test suites from `basic` to `part`.
> [tests-only][full-ci]rename e2e test suite

- docs/helpers/README.md
Just a small text change based on recent experiences.
> [docs-only] Update the docs helpers readme

- .drone.star
With this PR, the normal build notifications are sent to the `infinitescale` channel and nightly build notifications are sent to the `builds` channel. Previously all the build notifications were sent on `infinitescale` channel, due to which there might be a chance of missing some build status.
> [tests-only][full-ci]send nightly notification to builds channel

- .drone.star
Backport of PR: https://github.com/owncloud/ocis/pull/8866
> [tests-only][full-ci] backport send nightly notification to builds channel

- .drone.env
fix failed e2e test https://github.com/owncloud/web/pull/10803
> update web commit: fix flaky #10803

- deployments/examples/ocis_wopi/README.md
- docs/ocis/deployment/ocis_wopi.md
Refrences: #8845 and #8846
While working on the easy install guide, I identified some readme changes for the ocis_wopi deployment example.
> [docs-only] updating the ocis-wopi deployment readme's

- tests/acceptance/docker/src/acceptance.yml
Fixes https://github.com/owncloud/ocis/issues/8831
> [tests-only] [full-ci] updated php version to 8.2

- .drone.star
- composer.json
- tests/acceptance/docker/src/acceptance.yml
- vendor-bin/behat/composer.json
Backport of https://github.com/owncloud/ocis/pull/8889
Related issue: https://github.com/owncloud/ocis/issues/8831
> [tests-only][full-ci]changed php version

- tests/acceptance/features/bootstrap/Sharing.php
> delete php string deprecation

- tests/acceptance/features/bootstrap/Sharing.php
> Port #8911 to stable branch

- tests/acceptance/features/apiSharingNg/removeAccessToDrive.feature
tests for https://github.com/owncloud/ocis/issues/8819
> [test-only]remove members from space. more tests

- changelog/unreleased/shareeid-sses.md
- services/clientlog/pkg/service/events.go
- services/clientlog/pkg/service/service.go
Adds the shareeID (or multiple if this was a group share) to the sses
> Add ShareeIDs to SSEs

- changelog/unreleased/fix-admin-role-assignment.md
- services/settings/pkg/store/metadata/store.go
- services/settings/pkg/store/metadata/store_test.go
> [backport] [full-ci] Fix admin role

- .drone.star
This PR removes `Web-Tests-ocis-smoke-ocis-storage-` pipelines from `nightly` and PR title with `full-ci`.
> [tests-only] [full-ci] remove web smoke tests from nightly and full ci

- .golangci.yml
- changelog/unreleased/bump-natsjskv.md
- go.mod
- go.sum
- vendor/github.com/go-micro/plugins/v4/store/nats-js-kv/keys.go
- vendor/github.com/go-micro/plugins/v4/store/nats-js-kv/nats.go
- vendor/github.com/go-micro/plugins/v4/store/nats-js-kv/options.go
- vendor/modules.txt
Removing the custom fork from `nats-js-kv` package
> [full-ci] Bump nats-js-kv package

- tests/TestHelpers/GraphHelper.php
- tests/acceptance/features/apiSharingNg/shareInvitations.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
This PR add tests scenario related to share invite . Sending share invite on drive roots
-  https://github.com/owncloud/ocis/issues/8810
- locally
> [tests-only][full-ci]Add tests for share invite on drives root 

- services/webfinger/pkg/command/server.go
- services/webfinger/pkg/config/parser/parse.go
- services/webfinger/pkg/relations/openid_discovery.go
- services/webfinger/pkg/server/debug/server.go
- services/webfinger/pkg/server/http/option.go
- services/webfinger/pkg/server/http/server.go
- services/webfinger/pkg/service/v0/service.go
Came across some bits while browsing the code base ....
- test case 1:
- test case 2:
- ...
> chore: code cleanup service/webfinger

- deployments/examples/ocis_wopi/.env
- deployments/examples/ocis_wopi/docker-compose.yml
> feat: add OCIS_LOG_LEVEL to .env and also to the app-providers

- tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
Added test to enable share sync for resource which exist but not shared.
- ` Scenario: try to enable share sync with not shared resource id`
- Locally
- :robot:
> [full-ci] [tests-only] Added tests for enabling share sync with not shared resource id

- services/collaboration/pkg/server/http/server.go
`Secure` middleware has been removed
No open issue, but has problems building
- test case 1:
- test case 2:
- ...
> fix: remove obsolete secure middleware in collaboration service

- changelog/unreleased/rework-virus-handling.md
> [docs-only] Add forgotten changelog

- tests/acceptance/features/apiSharingNg/updateShareInvitations.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
This PR adds test coverage for updating roles for the project space shared and also its item:
```feature
Scenario Outline: space admin updates role of a member in project space (permissions endpoint)
Scenario Outline: user updates role of a shared resource of project space
```
https://github.com/owncloud/ocis/issues/8888
- Locally
- CI
> [tests-only][full-ci]Extend ShareNg test for updating share permission for project space

- tests/acceptance/features/apiAntivirus/antivirus.feature
adding extra example temple for antivirus test and changing given steps
- Part of https://github.com/owncloud/ocis/issues/8717#event-12535134605
- locally
- CI
> [tests-only][full-ci]updating antivirus feature file

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiContract/propfind.feature
changing given steps to use graph API for sharing space
- Part of  https://github.com/owncloud/ocis/issues/8717#event-12535134605
- locally
- CI
> [tests-only][full-ci]change given step from ocs to graph

- ocis-pkg/config/helpers.go
- ocis-pkg/config/helpers_test.go
Just some tests .....
- test case 1:
- test case 2:
- ...
> test: unit test BindSourcesToStructs

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiContract/spacesSharesReport.feature
changing given step to use graph API from sharing api
- Part of https://github.com/owncloud/ocis/issues/8717#event-12535134605
- locally
- CI
> [tests-only][full-ci]changing given step of creating share in feature file

- .drone.star
In this PR, made the return type of functions in drone file smiliar. Make most of the functions to return lists of steps.
Part of: https://github.com/owncloud/ocis/issues/8794
> [tests-only][full-ci] make function's return type in drone file similar

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiDepthInfinity/propfind.feature
- tests/acceptance/features/bootstrap/WebDav.php
changing step of feature file to use graph API for creating link
- Part of https://github.com/owncloud/ocis/issues/8717#event-12535134605
- locally
- CI
> [tests-only][full-ci]changing given step of creating link share in feature file

- .drone.star
Backport of PR: https://github.com/owncloud/ocis/pull/9039
> [tests-only][full-ci] backport make function's return type in drone file similar

- services/collaboration/README.md
Referencing: https://github.com/owncloud/docs-ocis/pull/815 (Add the collaboration service)
Transporting the text fixes to the collaboration readme
> [docs-only] Fix Collaboration readme

- .github/release_template.md
related: https://github.com/owncloud/ocis/issues/7940#issuecomment-2084518127
> removing ocis-helm items from the release template

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature
- tests/acceptance/features/apiGraph/userGDPRExport.feature
- tests/acceptance/features/bootstrap/PublicWebDavContext.php
- tests/acceptance/features/bootstrap/Sharing.php
Use sharingNG graph API in the given steps for sharing.
- `apiGraph`
- Locally
- :robot:
> [full-ci] [tests-only] Use sharingNG for sharing in given step, refactored accordingly

- services/storage-users/README.md
References: #9041
Missed when reviewing:
IMPOTANT --> IMPORTANT
> [docs-only] Typo in storage-users README.md

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiSearch1/dateSearch.feature
- tests/acceptance/features/apiSearch1/search.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
Use sharingNG graph API in the given steps for sharing.
- `apiSearch1`
- Locally
- :robot:
> [full-ci] [tests-only] Use sharing ng in given steps api search1 suite

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiSearch2/mediaTypeSearch.feature
- tests/acceptance/features/apiSearch2/tagSearch.feature
Use sharingNG graph API in the given steps for sharing.
- `apiSearch2`
- Locally
- :robot:
> [full-ci] [tests-only] Use sharing ng in given steps api search2 suite

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiSearchContent/contentSearch.feature
Use sharingNG graph API in the given steps for sharing.
- `apiSearchContent`
- Locally
- :robot:
> [full-ci] [tests-only] Use sharing ng in given steps api search content suite

- services/storage-users/README.md
Super small fix. Don't tell anyone I'm wasting my time with this....
> [docs-only] Tiny Fix

- tests/acceptance/config/behat.yml
- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiSpacesShares/changingFilesShare.feature
- tests/acceptance/features/apiSpacesShares/checksum.feature
- tests/acceptance/features/apiSpacesShares/copySpaces.feature
- tests/acceptance/features/bootstrap/Sharing.php
- `apiSpacesShares/`
- `changingFilesShare.feature`
- `checksum.feature`
- `copySpaces.feature`
- Locally
- :robot:
> [full-ci] [tests-only] Used sharing-ng in given steps

- tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
- tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
- tests/acceptance/features/apiSpacesDavOperation/getFileByFileId.feature
- tests/acceptance/features/apiSpacesDavOperation/propfindByFileId.feature
- tests/acceptance/features/apiSpacesDavOperation/updateFileByFileId.feature
Part of https://github.com/owncloud/ocis/issues/8717
> [tests-only][full-ci] changing given step of creating share in feature file

- tests/acceptance/features/bootstrap/SharingNgContext.php
fixed typo and data types
Follow up #9097
> [tests-only] fix typo and data types (follow up #9097)

- docs/ocis/development/testing.md
- tests/acceptance/config/behat.yml
- tests/acceptance/docker/src/ocis-base.yml
- tests/acceptance/features/apiNotification/deleteNotification.feature
- tests/acceptance/features/apiNotification/emailNotification.feature
- tests/acceptance/features/apiNotification/notification.feature
- tests/acceptance/features/apiNotification/spaceNotification.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
- Part of https://github.com/owncloud/ocis/issues/8717#event-12535134605
> [tests-only][full-ci] updating given step for sharing and env in docs for starting email service

- changelog/unreleased/fix-collaboration-registry.md
- services/collaboration/pkg/helpers/registration.go
- services/collaboration/pkg/server/http/server.go
- services/collaboration/pkg/service/grpc/v0/service.go
Fixed the collaboration service GRPC namespace
- test case 1:
- test case 2:
- ...
> fixed the collaboration service GRPC namespace

- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiSharingNg/removeAccessToDrive.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
This PR adds tests for removing share links
- https://github.com/owncloud/ocis/issues/8810
- Locally
> [tests-only][full-ci]add tests for removing share link

- changelog/unreleased/bump-reva.md
- go.mod
- go.sum
- vendor/github.com/cs3org/reva/v2/pkg/storage/uploads.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/upload.go
- vendor/modules.txt
Bump reva to include
*   Enhancement [cs3org/reva#4673](https://github.com/cs3org/reva/pull/4673): Add virus filter to list uploads sessions
- test case 1:
- test case 2:
- ...
> [full-ci] chore: bump reva to latest stable version 2.19.7

- tests/acceptance/config/behat-core.yml
- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/coreApiFavorites/favoritesSharingToShares.feature
> [tests-only][full-ci]changing given from ocs to graph in favoritesSharingToShares feature

- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
- tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature
- `apiSpacesShares/`
- `shareSubItemOfSpaceViaPublicLink.feature`
- `shareUploadTUS.feature`
- Locally
- :robot:
> [full-ci] [tests-only] Use sharing ng in given steps api spaces shares suite

- .drone.star
> [stable-5.0] Report to builds channel 5.0

- tests/acceptance/features/bootstrap/ShareesContext.php
removing the use of a stepdefinition inside another stepdefinition in ShareesContext.php
- Part of https://github.com/owncloud/ocis/issues/8199
- test case 1:locally
- test case 2:ci
> [tests-only][full-ci] removing the usage of a stepdef inside another stepdef in ShareesContext.php

- docs/ocis/release_roadmap.md
- updated release roadmap as it was outdated
- Added release flavours and releases list
- added release plan for the future
todo:
- supported versions need to be defined
- change title eg. to "release life cycle"
- add link to public roadmap
fixes https://github.com/owncloud/ocis/issues/8841
> [devdocs] Added release -flavours and list

- tests/acceptance/features/bootstrap/SpacesTUSContext.php
removing the use of a stepdefinition inside another stepdefinition in SpacesTUSContext.php
- Part of https://github.com/owncloud/ocis/issues/8199
- test case 1:locally
- test case 2:ci
> [tests-only][full-ci]remove the usage of a stepdefinition inside another stepdefinition in SpacesTUSContext.php

- tests/acceptance/config/behat-core.yml
- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/bootstrap/Sharing.php
- tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
- tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
updating given statement of test suite to use graph API
- coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
- coreApiShareManagementBasicToShares/deleteShareFromShares.feature
Reva Edge bump : https://github.com/cs3org/reva/pull/4682
- locally
- ci
> [tests-only][full-ci]changing given from ocs to graph in feature file

- tests/TestHelpers/OcisHelper.php
Allow the posix storage driver in the tests.
> [tests-only] Allow the posix storage driver in the tests

- tests/acceptance/config/behat-core.yml
- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/bootstrap/PublicWebDavContext.php
- tests/acceptance/features/bootstrap/Sharing.php
- tests/acceptance/features/bootstrap/SharingNgContext.php
- tests/acceptance/features/coreApiSharePublicLink1/deletePublicLinkShare.feature
- tests/acceptance/features/coreApiSharePublicLink2/copyFromPublicLink.feature
- tests/acceptance/features/coreApiSharePublicLink2/multilinkSharing.feature
- tests/acceptance/features/coreApiSharePublicLink2/updatePublicLinkShare.feature
- tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
- `coreApiSharePublicLink2/`
- `copyFromPublicLink.feature`
- `multilinkSharing.feature`
- `updatePublicLinkShare.feature`
- `uploadToPublicLinkShare.feature`
- Locally
- :robot:
> [full-ci] [tests-only] Use sharing-ng in given steps for sharing

- deployments/examples/ocis_wopi/docker-compose.yml
Backport of #9225 ([docs-only] Typo fix in ocis_wopi)
> [docs-only] Backport: Typo fix in ocis_wopi

- changelog/unreleased/fix-share-mount-unmount.md
- services/graph/pkg/service/v0/api_drives_drive_item.go
- services/graph/pkg/service/v0/api_drives_drive_item_test.go
- tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
- Fixes [#8876](https://github.com/owncloud/ocis/issues/8876)
- test case 1:
- test case 2:
- ...
> fix the status code for multiple mount and unmount share

- changelog/unreleased/thumbnail-request-limit.md
- ocis-pkg/middleware/throttle.go
- services/thumbnails/README.md
- services/thumbnails/pkg/command/server.go
- services/thumbnails/pkg/config/defaults/defaultconfig.go
- services/thumbnails/pkg/config/http.go
- services/thumbnails/pkg/server/http/option.go
- services/thumbnails/pkg/server/http/server.go
- services/thumbnails/pkg/service/http/v0/service.go
- services/webdav/pkg/service/v0/search.go
- services/webdav/pkg/service/v0/service.go
Backport of https://github.com/owncloud/ocis/pull/9199
> [backport] feat: limit concurrent processing of thumbnail requests

- tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
Added tests for disabling share sync with non-existent resource, empty id, not shared resource id.
- `Scenario: try to disable share sync of a non-existent resource`
- `Scenario: try to disable share sync with empty resource id`
- `Scenario: try to disable share sync with not shared resource id`
- Locally
- :robot:
> [full-ci] [tests-only] Add test for disable sync with non-existing resource

- changelog/unreleased/bump-reva.md
- go.mod
- go.sum
- vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocdav/propfind/propfind.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/fs/ocis/blobstore/blobstore.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/fs/s3ng/blobstore/blobstore.go
- vendor/modules.txt
chore: bump reva to 56879111e06afa9e8c04ee71409548531cda7d76 so that we get https://github.com/cs3org/reva/pull/4695 and https://github.com/cs3org/reva/pull/4696 in.
> chore: bump reva to 56879111e06afa9e8c04ee71409548531cda7d76

- services/settings/README.md
Adds some documentation on how to create custom roles.
> [docs-only] Add documenation for custom roles

- tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
This PR add tests for multiple enable and disable share sync.
```feature
Scenario Outline: try to enable sync of already synced share
Scenario Outline: try to disable sync of already unsynced share
Scenario Outline: try to enable sync of already synced share shared from Project space
Scenario Outline: try to disable sync of already unsynced share shared from Project space
```
-  Related issue: https://github.com/owncloud/ocis/issues/8876 
- tlocally
-  ci
> [tests-only][full-ci] adding tests for multiple enable disable share

- changelog/unreleased/add-providerinfo-secure-view-flag.md
- services/collaboration/pkg/config/defaults/defaultconfig.go
- services/frontend/pkg/config/defaults/defaultconfig.go
followup to https://github.com/owncloud/ocis/pull/9277 because people believe the app name should be "Collabora", which it [clearly is not](https://www.collaboraoffice.com/collabora-online/) ... but whatever.
> default to Collabora

- vendor-bin/owncloud-codestyle/composer.json
Similar to https://github.com/owncloud/core/pull/41258
Use the latest code-style checker for PHP.
CI
> chore: use owncloud/coding-standard 5.1

- tests/ociswrapper/README.md
Added documentation for port, url, retry, admin-username, and admin-password options in the README file.
- https://github.com/owncloud/ocis/issues/8089
- Locally
> [docs] add docs for available ociswrapper serve sub-command options

- changelog/unreleased/bump-reva.md
Update reva to get the fix https://github.com/cs3org/reva/pull/4710
- Needed for #9310
- Fixes #8747
- test case 1:
- test case 2:
- ...
> [full-ci] chore: update reva to latest edge

- .make/check-env-var-annotations.sh
- docs/services/general-info/envvar-scopes.md
- services/collaboration/pkg/config/app.go
- services/collaboration/pkg/config/config.go
- services/collaboration/pkg/config/cs3api.go
- services/collaboration/pkg/config/debug.go
- services/collaboration/pkg/config/grpc.go
- services/collaboration/pkg/config/http.go
- services/collaboration/pkg/config/log.go
- services/collaboration/pkg/config/wopi.go
- services/frontend/pkg/config/config.go
- services/graph/pkg/config/config.go
- services/proxy/pkg/config/config.go
- services/storage-users/pkg/config/config.go
- services/thumbnails/pkg/config/config.go
- services/thumbnails/pkg/config/http.go
- services/web/pkg/config/config.go
Use placeholder for next version in env var descriptions.
refs #9254 
- Fixes https://github.com/owncloud/ocis/issues/9254
- test case 1:
- test case 2:
- ...
> docs: use placeholder for next release

- tests/acceptance/features/apiSharingNg/listPermissions.feature
This PR covers the scenario in various feature file to add `secure viewer` role while sharing the space.
- Part of  https://github.com/owncloud/ocis/issues/8428
> [tests-only][full-ci]adding test for sharing space via secure role

- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/bootstrap/Sharing.php
- tests/acceptance/features/coreApiShareOperationsToShares2/shareAccessByID.feature
The failing scenarios for ocs is removed and also removed from expected failures.
The related issues (https://github.com/owncloud/ocis/issues/2111, https://github.com/owncloud/ocis/issues/2540) are closed.
The test for sharingNg was added in PR https://github.com/owncloud/ocis/pull/8875
- Part of https://github.com/owncloud/ocis/issues/9324
The OCS is deprecated.
- :robot:
> [full-ci] [tests-only] Removed failing ocs scenarios

- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/bootstrap/PublicWebDavContext.php
- tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
- 403 if public has no permission
- 404 if file was deleted
- removed tests from expected failures file and closed issue
> [test-only] fix tests where public try to download file

- tests/acceptance/features/apiSharingNg/sharedByMe.feature
- tests/acceptance/features/apiSharingNg/sharedWithMe.feature
This PR updates the previous scenario and add the sharing permission `secure view` .
Scenerio Updated:
```feature
Scenario Outline: sharer lists the file share (Personal space)
Scenario Outline: sharer lists the folder share (Personal space)
Scenario Outline: sharer lists the file share (Project space)
Scenario Outline: sharer lists the folder share (Project space)
Scenario Outline: sharee lists the file share (Personal space)
Scenario Outline: sharee lists the folder share (Personal space)
Scenario Outline: sharee lists the file share (Project space)
Scenario Outline: sharee lists the folder share (Project space)
```
- Part of https://github.com/owncloud/ocis/issues/9334
- locally
- CI
> [tests-only][full-ci]adding secure view in apisharingNg feature file

- deployments/examples/ocis_wopi/.env
- deployments/examples/ocis_wopi/README.md
Closes #9223
- test case 1:
- test case 2:
- ...
> [docs-only] Backport wopi example 2

- .drone.star
suddenly `wopiValidatorTests-builtin-ocis` started to fail 
https://drone.owncloud.com/owncloud/ocis/35880/16/9
> try to fix wopi validator test

- changelog/unreleased/fix-settings-metadata-tests.md
- services/settings/pkg/store/metadata/assignments_test.go
- services/settings/pkg/store/metadata/bundles_test.go
- services/settings/pkg/store/metadata/permissions_test.go
- services/settings/pkg/store/metadata/values_test.go
We fix the settings metedata tests that had the data race
- Fixes [#9372](https://github.com/owncloud/ocis/issues/9372)
- test case 1:
- test case 2:
- ...
> Fix the settings metedata tests

- tests/acceptance/features/apiSharingNgLinkShare/linkShare.feature
- tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
This PR add tests coverage to create quick link share of a project-space drive using root endpoint.
``` feature
Scenario Outline: create quick link share of a project space drive using root endpoint
Scenario: create an internal quick link share of a project space drive using root endpoint
```
- Related to : https://github.com/owncloud/ocis/issues/9046
- locally
> [tests-only][full-ci] add tests to create quick link of space drive using root endpoint

- tests/acceptance/features/bootstrap/WebDav.php
This PR adds the third parameter folderDepth on listFolderAndReturnResponseXml function when it is being called in checkElementList.
- Resolves https://github.com/owncloud/ocis/issues/9346
- locally
> [full-ci][tests-only] use correct parameters in listFolderAndReturnResponseXml method

- deployments/examples/ocis_wopi/.env
- deployments/examples/ocis_wopi/collabora.yml
- deployments/examples/ocis_wopi/ocis.yml
- deployments/examples/ocis_wopi/onlyoffice.yml
Follow-up of #9412 with some minor adjustments to comment text only - no functional impact.
N/A
> [docs-only] [5.0] Adjust some text in ocis_wopi example

- deployments/examples/README.md
- deployments/examples/oc10_ocis_parallel/docker-compose.yml
- deployments/examples/ocis_hello/docker-compose.yml
- deployments/examples/ocis_ldap/docker-compose.yml
- deployments/examples/ocis_s3/docker-compose.yml
- deployments/examples/ocis_traefik/docker-compose.yml
Just tidying up a few typos in deployment examples, after looking at some of them yesterday.
These are the same in master and stable-5.0. I made the PR to master. I don't think any of this matters for stable-5.0 - but tell me if you want me to also make a backport to stable-5.0
N/A
> chore: adjust comments in deployment examples

- tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
This PR updates the previous scenarios regarding sharee trying to move file/folder within the shared folder with permission secure view too.
Scenario Updated:
```feature
Scenario Outline: sharer renames the shared item (spaces webdav)
Scenario Outline: share receiver renames the shared item (old/new webdav)
Scenario Outline: share receiver renames the shared item (spaces webdav)
Scenario: receiver tries to rename a received share with read permissions inside the Shares folder
```
- Part of: https://github.com/owncloud/ocis/issues/9334
- Locally
- CI
> [tests-only][full-ci] extend test for trying to move file/folder within shares-personal drive with secure view role

- docs/helpers/env_vars.yaml
- docs/helpers/extended_vars.yaml
Regular maintaining yaml helper files for docs.
Waiting for #9361 to be merged, some additional fixes get added when I rerun make docs-generate.
> [docs-only] [chore] Maintain envvar yaml file updates (doc helper stuff)

- tests/acceptance/features/apiDownloads/download.feature
- tests/acceptance/features/apiOcm/ocm.feature
- tests/acceptance/features/apiSpacesShares/changingFilesShare.feature
- tests/acceptance/features/bootstrap/FilesVersionsContext.php
- tests/acceptance/features/bootstrap/SpacesContext.php
This PR removes the usage of index paramater while getting a list of versions of a file in a project space.
~~~ feature
Scenario: user with role viewer cannot get versions of a file in the project space
~~~
- Related to : https://github.com/owncloud/ocis/issues/9342
- locally
> [tests-only][full-ci] remove unused index paramater in userTriesToDownloadFileVersions in spacesContext

- tests/acceptance/features/apiOcm/ocm.feature
- tests/acceptance/features/bootstrap/TrashbinContext.php
This PR removes throwExceptionIfNotFound parameter from restoreElement function and also removes the unused step defintion i.e. userTriesToRestoreElementInTrash function.
- Related to :  https://github.com/owncloud/ocis/issues/9344
- locally
> [full-ci][tests-only] remove throwExceptionIfNotFound parameter and unused userTriesToRestoreElementInTrash function

- tests/acceptance/features/bootstrap/WebDav.php
This PR  details that the expressions:
```php
// reverse the array to get the latest version first
\array_reverse($authors);
```
and
```php
// reverse the array to get the latest version first
\array_reverse($displaynames);
```
are not necessary for current case. This is because as mentioned in the issue #2914, the features for scenarios listed [here](https://github.com/owncloud/ocis/issues/9347#issuecomment-2186367081) are not yet implemented in ocis. So for current context, those expressions are removed. Also this removal causes no extra effects in the tests results. 
- https://github.com/owncloud/ocis/issues/9347
- Locally
- CI
>  [full-ci][tests-only] Remove unused array_reverse() functions

- services/search/README.md
Improves the readme of the search service after https://github.com/owncloud/ocis/issues/9103
> [docs-only] Reindex Readme

- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/coreApiWebdavMove2/moveShareOnOcis.feature
- test case 1:
- test case 2:
- ...
> [tests-only][full-ci] wait and check for sync status before performing MOVE

- .drone.star
- changelog/unreleased/fix-email-notification.md
- deployments/examples/ocis_full/inbucket.yml
- docs/ocis/development/testing.md
- ocis/pkg/runtime/service/service.go
- services/notifications/pkg/channels/channels.go
- services/notifications/pkg/channels/channels_test.go
- services/notifications/pkg/config/parser/parse.go
We fixed an error in the notification service that caused the email notification to fail when the user's display name contained special characters.
- Fixes [#9402](https://github.com/owncloud/ocis/issues/9402)
- test environment: local ocis + inbucket server
> fixed the notification service error when the user's display name contained special characters

- docs/architecture/posixfs-storage-driver.md
Naming is hard. Lets stay with the initial name. @micbar @tbsbdr
> [docs-only] Rename Joint Access Storage driver back to PosixFS

- docs/ocis/deployment/continuous_deployment.md
Reflect the recent changes in the docs.
- test case 1:
- test case 2:
- ...
> [docs-only] feat: change the docs to reflect the new deployments

- changelog/unreleased/fix-email-template.md
- services/notifications/pkg/email/composer.go
- services/notifications/pkg/service/service_test.go
fixed the email template when the description was marked as a link
- Fixes [8424](https://github.com/owncloud/ocis/issues/8424)
- test case 1:
- test case 2:
- ...
> fixed the email template when the description was marked as a link

- .drone.env
- changelog/unreleased/update-web-9.1.0.md
- services/web/Makefile
> [full-ci] chore: bump web to v9.1.0

- .drone.star
- Makefile
- tests/acceptance/config/.gherlintrc.json
This PR adds new CI pipeline to check for lint issues using gherlint.
- Related to : https://github.com/owncloud/QA/issues/833
- CI
> [full-ci][tests-only] add CI pipeline for checking lint issues using gherlint

- tests/acceptance/features/bootstrap/WebDav.php
This PR removes unused step definition function downloadedContentWhenDownloadingWithRangeShouldBe from WebDav.php
- Related to :
https://github.com/owncloud/ocis/issues/9345
https://github.com/owncloud/ocis/issues/9520
- locally
> [full-ci][tests-only] remove unused stepDef function related to download with range from WebDav.php

- tests/acceptance/features/bootstrap/WebDav.php
This PR removes the unused Given step definitions from WebDav.php .
For more, read this comment : https://github.com/owncloud/ocis/issues/9539#issuecomment-2213183131
- Related to : https://github.com/owncloud/ocis/issues/9539
- locally
> [tests-only][full-ci] remove unused Given step definitions from WebDav.php

- tests/acceptance/features/bootstrap/WebDav.php
This PR removes the unused When step definitions from WebDav.php .
For more, read this comment : https://github.com/owncloud/ocis/issues/9539#issuecomment-2213183131
- Related to : https://github.com/owncloud/ocis/issues/9539
- locally
> [tests-only][full-ci] remove unused When step definitions from WebDav.php

- services/thumbnails/pkg/config/defaults/defaultconfig.go
- services/thumbnails/pkg/config/http.go
- services/thumbnails/pkg/server/debug/server.go
- services/thumbnails/pkg/server/http/server.go
Adding CORS config options to the thumbnail service. Don't know if this is correct and needed, maybe the config options are already being applied somewhere else? Someone who knows ™️ should take a look.
> feat: thumbnail service CORS config

- tests/acceptance/features/bootstrap/WebDav.php
This PR removes the unused When step definitions from WebDav.php .
For more, read this comment : https://github.com/owncloud/ocis/issues/9539#issuecomment-2213183131
- Related to : https://github.com/owncloud/ocis/issues/9539
- locally
> [tests-only][full-ci] remove unused Then step definitions from WebDav.php

- .drone.star
- test case 1:
- test case 2:
- ...
> ci: remove storage name from pipeline names

- tests/TestHelpers/OcmHelper.php
- tests/acceptance/features/apiOcm/searchFederationUsers.feature
- tests/acceptance/features/bootstrap/FeatureContext.php
- tests/acceptance/features/bootstrap/OcmContext.php
- API test for  GET `/sciencemesh/find-accepted-users` endpoint
> [test-only] Find accepted user

- docs/ocis/development/testing.md
changed docs how to correct setup ocis with Inbucket
> [docs-only] change Setup Inbucket testing docs

- tests/acceptance/features/apiContract/sharesReport.feature
- tests/acceptance/features/apiContract/spacesSharesReport.feature
- tests/acceptance/features/bootstrap/SpacesContext.php
Tests that checks if the `remote-item-id` has been returned in search `REPORT` response for shared resources.
- Fixes https://github.com/owncloud/ocis/issues/9531
- test case 1:
- test case 2:
- ...
> [tests-only][full-ci] add remote item-id check in REPORT responses

- docs/helpers/env_vars.yaml
Just a small regular chore task...
> [docs-only] Just an update of the envvars yaml file for the docs helper

- docs/services/general-info/added-services.md
Follow-up of PR #9592 to adjust the text a little.
> Minor edit to added-services.md

- docs/ocis/development/testing.md
- tests/TestHelpers/OcmHelper.php
- tests/acceptance/config/behat.yml
- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiOcm/acceptInvitation.feature
- tests/acceptance/features/apiOcm/createInvitation.feature
- tests/acceptance/features/apiOcm/share.feature
- tests/acceptance/features/bootstrap/OcmContext.php
> [test-only] list Invitation

- services/antivirus/pkg/config/config.go
- services/clientlog/pkg/config/config.go
- services/collaboration/pkg/config/cs3api.go
- services/settings/pkg/settings/settings.go
@dragonchaser do i miss something or is it fine, ive also found some `removalVersion:"%%NEXT%%"`, are we in charge of that?
> chore!: remove deprecated configuration values

- .drone.env
- changelog/unreleased/bump-web-commitid.md
Bumps the commitID of web to current master
> [full-ci] Bump Web CommitID

- tests/acceptance/features/bootstrap/CliContext.php
- tests/acceptance/features/cliCommands/removeFileVersions.feature
This PR adds test for removing versions of a specific file using it's file-id using cli command 
- Coverage for : https://github.com/owncloud/ocis/issues/9472
- Part of: https://github.com/owncloud/ocis/issues/9529
- locally
- CI
> [tests-only][full-ci] adding test to remove old versions of a file using file-id using cli command

- .golangci.yml
> [docs-only] Fix Sonarcloud Import issue

- changelog/unreleased/fix-workers-lock.md
- services/graph/pkg/service/v0/utils.go
- Fixes [https://github.com/owncloud/ocis/issues/9642](https://github.com/owncloud/ocis/issues/9642)
- test case 1:
- test case 2:
- ...
> Fixed the channel lock in a workers pool

- changelog/unreleased/fix-missing-secure-view-attr.md
- services/search/pkg/search/search.go
Fix a missing SecureView permission attribute in the REPORT response
- Fixes [https://github.com/owncloud/ocis/issues/9607](https://github.com/owncloud/ocis/issues/9607)
- Fixes [https://github.com/owncloud/ocis/issues/9608](https://github.com/owncloud/ocis/issues/9608)
- test case 1:
- test case 2:
- ...
> Fix a missing SecureView permission attribute in the REPORT response

- changelog/unreleased/collaboration-logging.md
- services/collaboration/pkg/connector/contentconnector.go
- services/collaboration/pkg/connector/fileconnector.go
- services/collaboration/pkg/middleware/accesslog.go
Enhancement: Improve the collaboration service logging
We added more debug log information to the collaboration service. This is vital for scenarios when we need to debug in remote setups.
- test case 1:
- test case 2:
- ...
> feat: add more logging to collaboration service

- changelog/unreleased/fix-natsjskv-registry.md
- ocis-pkg/natsjsregistry/options.go
- ocis-pkg/natsjsregistry/registry.go
- ocis-pkg/registry/expiry.go
- ocis-pkg/registry/register.go
- ocis-pkg/registry/registry.go
- ocis-pkg/service/grpc/service.go
- ocis-pkg/service/http/service.go
Fixes TTL and Registration interval issues that lead to increased memory consumption
Fixes https://github.com/owncloud/ocis/issues/9650
> Fix issues with natsjskv registry

- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiGraph/changeRole.feature
- tests/acceptance/features/apiGraph/getAssignedRole.feature
- tests/acceptance/features/apiGraph/unassignRole.feature
- tests/acceptance/features/apiGraphUserGroup/addUserToGroup.feature
- tests/acceptance/features/apiGraphUserGroup/deleteGroup.feature
- tests/acceptance/features/apiGraphUserGroup/editGroup.feature
- tests/acceptance/features/apiGraphUserGroup/editUser.feature
- tests/acceptance/features/apiGraphUserGroup/getGroup.feature
- tests/acceptance/features/apiGraphUserGroup/getUser.feature
- tests/acceptance/features/apiGraphUserGroup/removeUserFromGroup.feature
- tests/acceptance/features/apiSpaces/disableAndDeleteSpaces.feature
- tests/acceptance/features/bootstrap/GraphContext.php
- tests/acceptance/features/bootstrap/SettingsContext.php
- tests/acceptance/features/coreApiWebdavUpload/uploadFile.feature
Added the following test scenarios
```feature
Scenario Outline: non-admin user tries to change the role of nonexistent user
Scenario: non-admin user tries to get assigned role of another user
Scenario: non-admin user tries to get assigned role of nonexistent user
Scenario: non-admin user tries to unassign role of another user
Scenario: non-admin user tries to unassign role of nonexistent user
Scenario: non-admin user tries to add a nonexistent user to a group
Scenario: admin user tries to delete nonexistent group
Scenario Outline: non-admin user tries to delete nonexistent group
Scenario Outline: non-admin user tries to rename nonexistent group
Scenario: admin user tries to edit nonexistent user's name
Scenario Outline: non-admin user tries to edit nonexistent user's name
Scenario …
```
> [tests-only][full-ci] extend test cases for non-admin actions to admin resources

- deployments/continuous-deployment-config/ocis_full/production.yml
- test case 1:
- test case 2:
- ...
> fix: fix production deployment

- tests/acceptance/features/apiContract/sharesReport.feature
test for https://github.com/owncloud/ocis/issues/9607
> [test-only] check secure view permissions in the Report response

- changelog/unreleased/fix-panic.md
- go.mod
- go.sum
- vendor/github.com/go-micro/plugins/v4/store/nats-js-kv/nats.go
- vendor/modules.txt
Panics should be avoided because they are bad.
Fixes https://github.com/owncloud/ocis/issues/9673
> Dont Panic

- docs/ocis/flow-docs/login-flow.md
- docs/ocis/flow-docs/request-flow.md
> [docs-only] remove <br> from mermaid charts

- deployments/examples/ocis_full/collabora.yml
Generate the proof keys for Collabora.
Recently a PR was merged to verify the proof keys of WOPI requests. It seems the example deployment didn't generate the proof keys, so now it wasn't possible for Collabora to access to the collaboration service because the proof keys verification was failing (Collabora can't send the keys, and the verification fails, so request is rejected).
This change will cause Collabora to generate and send the proof keys, so we can perform the verification and allow the requests normally.
As an alternative, the proof keys verification can be disabled, but it could have security implications, so generating the keys is a better option.
No open issue
Local deployment with similar configuration
> chore: generate proof keys for collabora

- deployments/continuous-deployment-config/ocis_full/onlyoffice-rolling.yml
- deployments/continuous-deployment-config/ocis_full/rolling.yml
- deployments/continuous-deployment-config/ocis_full/s3-rolling.yml
- deployments/continuous-deployment-config/ocis_keycloak/rolling.yml
- deployments/continuous-deployment-config/ocis_ldap/rolling.yml
> chore: update continuous deployments to latest rolling

- deployments/examples/ocis_full/.env
- deployments/examples/ocis_full/collabora.yml
- deployments/examples/ocis_full/docker-compose.yml
this fix can help to solve this issue https://github.com/owncloud/ocis/issues/9706#issuecomment-2257756493 with local running collabora v.24
related https://github.com/owncloud/web/pull/11301
> add collabora extra param

- docs/helpers/env_vars.yaml
Just a regular update task triggerd via changes coming from `make -C docs docs-generate`
> [docs-only] [chore] update env_vars.yaml

- tests/TestHelpers/WebDavHelper.php
- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/bootstrap/FavoritesContext.php
- tests/acceptance/features/bootstrap/FilesVersionsContext.php
- tests/acceptance/features/bootstrap/WebDav.php
- tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
- tests/acceptance/features/coreApiTrashbin/trashbinSharingToShares.feature
- tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
- tests/acceptance/features/coreApiWebdavProperties/setFileProperties.feature
> [tests-only][ful-ci] adjust tests and expected failure list

- tests/TestHelpers/WebDavHelper.php
- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
- tests/acceptance/features/apiSpacesShares/moveSpaces.feature
- tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
- tests/acceptance/features/coreApiSharePublicLink2/copyFromPublicLink.feature
- tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
- tests/acceptance/features/coreApiWebdavProperties/getFileProperties.feature
- Adjusted the test expectation
- added coverage for closed issues
> [tests-only][full-ci] adjust tests and expected-failure list

- changelog/unreleased/bump-gomicro-plugins.md
- go.mod
- go.sum
- vendor/github.com/go-micro/plugins/v4/store/nats-js-kv/nats.go
- vendor/modules.txt
Bumps go-micro pkg to include a fix for the watcher on delete events.
> [full-ci] Bump go-micro/plugins

- changelog/5.0.4_2024-05-13/bump-reva.md
- changelog/5.0.4_2024-05-13/fix-wopi-example.md
- changelog/5.0.4_2024-05-13/nats-reconnects.md
- changelog/5.0.5_2024-05-22/update-web-8.0.2.md
- changelog/5.0.6_2024-07-17/fix-email-notification.md
- changelog/5.0.6_2024-07-17/harden-postprocessing-restart.md
- changelog/5.0.6_2024-07-17/remove-revisions-cli.md
- changelog/5.0.6_2024-07-17/thumbnail-request-limit.md
- changelog/5.0.6_2024-07-17/update-web-8.0.4.md
added changelog `ocis 5.0.4` `ocis 5.0.5` `ocis 5.0.6` to master branch
> add changelog v5.0.4. 5.0.5 and 5.0.6

- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
Updated test cases for sharing via secure role 
```feature
Scenario Outline: copying a file to a folder with no permissions
Scenario Outline: copying a file into a shared folder shared via viewer and secure viewer permissions as the share
Scenario Outline: copying a file out of a shared folder shared via secure viewer permissions as the share
Scenario Outline: copying a folder between shares received from different users when one share is shared via Secure viewer
Scenario Outline: copying a file between shares received from different users when one share is shared via Secure viewer
```
- Part of https://github.com/owncloud/ocis/issues/9334
> [tests-only][full-ci]extending test cases for copying file when shared with secure viewer

- tests/acceptance/features/apiGraph/activities.feature
- tests/acceptance/features/bootstrap/GraphContext.php
Added test to check activity for file and folder deletion event.
- Bug: https://github.com/owncloud/ocis/issues/9712
- test case 1:
- test case 2:
> [tests-only] [full-ci] Test for file deletion activity

- tests/TestHelpers/GraphHelper.php
- tests/acceptance/expected-failures-API-on-OCIS-storage.md
- tests/acceptance/features/bootstrap/SharingNgContext.php
- tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
- Bug report: https://github.com/owncloud/ocis/issues/9753 
> [tests-only] fix COPY to mountpoint tests

- Makefile
- changelog/changelog-csv.tmpl
Allow to create the changelog in CSV format - needed for "the spreadsheet"
> [docs-only] Add a make target to create a changelog in csv format

- tests/acceptance/features/apiSharingNg1/sharedWithMe.feature
- tests/acceptance/features/bootstrap/SharingNgContext.php
This PR adds test to list multiple shares(more than 10).
- Related to: https://github.com/owncloud/ocis/issues/9737
- Bug Report: https://github.com/owncloud/ocis/issues/9642
- Locally
- CI
> [tests-only][full-ci] add test to list multiple shares

- deployments/examples/ocis_full/.env
- deployments/examples/ocis_full/ocis.yml
- docs/ocis/deployment/ocis_full.md
That adds an way of having the volumes configured easily.
> [docs-only] Add variables to .env to configure the data- and config directory

- .drone.star
- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiActivities/shareActivities.feature
Added test to check activity for file after sharing it to another user and also after removing the share.
```feature
Scenario: check activities after adding share to a file
Scenario: check activities after removing share from a file
```
- Related to: https://github.com/owncloud/ocis/issues/9543
- CI
- locally
> [full-ci][tests-only]add test for api activities after sharing a file

- tests/acceptance/features/bootstrap/TUSContext.php
Use `sha1` checksum algorithm in tests
> [tests-only] Use sha1 checksum algorithm in tests

- tests/acceptance/features/apiActivities/shareActivities.feature
This PR adds test to check api activities for sharee actions(add/edit/delete) on a file/folder. 
``` feature
Scenario: check sharee (add/edit/delete) activity for a file
```
- Bug Report: https://github.com/owncloud/ocis/issues/9712
-
> [test-only][full-ci] add test to check sharee activities

- docs/helpers/env_vars.yaml
- docs/helpers/extended_vars.yaml
Regular maintenance for envvar yaml files.
No texts to be reviewed, all coming from autogeneration.
> [docs-only][chore] Regular envvar yaml maintenance

- services/ocm/README.md
- services/ocm/pkg/config/config.go
Referencing: #9845
Found by chance, the change in the referenced PR was not enough, the envvar needed an update too...
@butonic fyi
> [docs-only] Update ennvar text and readme in ocm

- changelog/unreleased/fix_capability_disable_self_password_change.md
- services/frontend/pkg/revaconfig/config.go
Fixes: https://github.com/owncloud/enterprise/issues/6849
> fix(frontend): disable self password change if passwordProfile is read-only

- docs/ocis/release_roadmap.md
References: #9869 
My bad 🤦‍♂️ 
I changed the link in the incorrect order - fixed now.
Locally tested and works
> [docs-only] Link fix for dev docs

- changelog/unreleased/fix-graph-readonly-attributes.md
- go.mod
- go.sum
- services/graph/pkg/service/v0/users.go
- services/graph/pkg/service/v0/users_test.go
- vendor/github.com/owncloud/libre-graph-api-go/model_identity.go
- vendor/modules.txt
> fix(graph): treat memberOf and userType as read-only attributes

- tests/acceptance/features/apiActivities/activities.feature
Continued from: https://github.com/owncloud/ocis/pull/9875 as there was slight update in the translation (German-'de' in this scenario).
``` feature
Scenario: check activity message with different language
```
- Related to: https://github.com/owncloud/ocis/issues/9543
- Bug Report: https://github.com/owncloud/ocis/issues/9856
- Locally
- CI
> [tests-only][full-ci] adjust the activity language translation

- docs/helpers/env_vars.yaml
Regular update based on doc helper output.
Nothing to check as that is autogenerated.
> [docs-only][chore] Update envvars yaml

- docs/services/general-info/add-translations.md
Add an item to not forget maintaining the readme after adding the functionality.
> [docs-only] Update add-translations.md

- changelog/unreleased/graph-translation-path.md
- services/graph/README.md
- services/graph/pkg/config/config.go
- services/graph/pkg/l10n/translation.go
- services/graph/pkg/service/v0/spacetemplates.go
Fixes https://github.com/owncloud/ocis/issues/9899
> Add TRANSLATION_PATH envvar to graph service

- ocis/README.md
Follow up of https://github.com/owncloud/ocis/pull/9891#issuecomment-2306513066
> [docs-only] Forgotten revisions purge docs

- changelog/unreleased/fix-upload-response-code.md
We fixed a bug where the response code was incorrect when uploading a file over a locked file.
- Fixes [#7638](https://github.com/owncloud/ocis/issues/7638)
- test case 1:
- test case 2:
- ...
> [full-ci] Fix response code when upload a file over locked

- docs/services/general-info/registry.md
- ocis/README.md
- services/nats/README.md
Fixes: #8034 (Recently added nats-js-kv needs to be mentioned in the nats service readme)
Not only add missing text to the nats service, but also fixing existing content that was outdated.
> [docs-only ] Add and correct registry related content.

- docs/services/ocm/create_share_flow.md
This PR fixes the broken ocm create share flow in the docs https://owncloud.dev/services/ocm/create_share_flow/
> [docs-only] fix broken ocm create share flow diagram

- tests/acceptance/config/behat-core.yml
- tests/acceptance/config/behat.yml
Updated path -> `ldapInitialUserFilePath: /../config/ldap-users.ldif` as it is being used in Reva.
-
> [tests-only][full-ci] update path for ldap-user.ldif file for Reva

- tests/acceptance/bootstrap/CliContext.php
- tests/acceptance/bootstrap/CollaborationContext.php
- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiCollaboration/checkFileInfo.feature
This PR add tests for checking information of file passed on fakeoffice
- Fixes <#9844>
- test case 1:
- test case 2:
- ...
> [tests-only][full-ci]Add tests for checking file info on fake office

- tests/acceptance/bootstrap/FeatureContext.php
- tests/acceptance/features/apiCollaboration/wopi.feature
Added test to open open-document file with /app/open-with-web endpoint with and without app_name parameter.
- Locally
- CI
> [tests-only][full-ci] add test coverage to open open-document file with /app/open-with-web endpoint

- services/collaboration/README.md
- services/collaboration/pkg/config/app.go
- services/collaboration/pkg/config/wopi.go
References: #9686 (feat: Microsoft office 365 Cloud and Office Online Server support)
Some texts and description updates and fixes.
> [docs-only] Fix office365 texts

- .drone.star
- ocis/docker/manifest-latest.tmpl
Add `latest` pointer to ocis stable.
- Fixes #9792
- test case 1:
- test case 2:
- ...
> chore: add latest manifest to stable tag

- tests/acceptance/features/apiCollaboration/wopi.feature
Added test to open text file with /app/open-with-web endpoint with and without app_name parameter.
- Locally
- CI
> [tests-only][full-ci] add test coverage to open text file with /app/open-with-web endpoint

- ocis/README.md
- services/graph/README.md
- services/graph/pkg/config/unified_roles.go
Fixes: #9961 (CLI description for Unified Roles Management)
Add a description for Unified Roles Management:
* CLI command
* Graph service readme
* envvar description text update
@fschade I tried to find a descriptive text what UR are about, pls have a look if ok.
> [docs-only] Description + CLI for Unified Roles Management

- tests/acceptance/features/apiCollaboration/wopi.feature
Added test to open .odt file with /app/open-with-web endpoint with and without app_name parameter.
- Locally
- CI
> [tests-only][full-ci] test: Add test coverage for opening .odt file by public user with /app/open-with-web endpoint

- tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
Added test coverage for copying a file using fileId from project space:
| |from (space) | from (role) | to (space) | to (role) 
--|--|--|--|--|
| 1. | project | different permission | project | different permission 
| 2. | project | different permission | share | different permission
| 3. | project | different permission	| personal
- Part of https://github.com/owncloud/ocis/issues/9878
- locally
- CI :robot:
> [tests-only] [full-ci] Add test coverage for copying file using file id from `project space`

- tests/acceptance/features/apiCollaboration/wopi.feature
Added test to open shared open-document file with /app/open-with-web endpoint with and without app_name parameter.
- Locally
- CI
> [tests-only][full-ci] add test coverage to open shared open-document file with /app/open-with-web endpoint

- services/notifications/README.md
References: https://github.com/owncloud/docs-ocis/pull/980 (Reordering some text in notifications to improve readability)
> [docs-only] Update the notification service readme

- .drone.star
- tests/acceptance/features/apiCollaboration/checkFileInfo.feature
- tests/config/drone/only-office.json
This PR 
- add tests for checking file info on wopi server.
- run onlyoffice and collaborate on drone 
- Part of <https://github.com/owncloud/ocis/issues/9844>
- locally
> [tests-only][full-ci]Add tests for CheckFileInfo related to wopi protocol  

- tests/acceptance/TestHelpers/GraphHelper.php
- tests/acceptance/bootstrap/OcisConfigContext.php
- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
- tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
This PR adds test for new permission role `Space Editor Without Versions`
``` feature
Scenario: check the versions of a file in a shared space as editor without versions role
```
- Related to: https://github.com/owncloud/ocis/issues/9955
- locally
- CI
> [tests-only][full-ci] add tests for new role space editor without versions

- changelog/unreleased/fix-acitivity-filter.md
- services/activitylog/pkg/service/http.go
Fixed activity filter depth
- Fixes [#9850](https://github.com/owncloud/ocis/issues/9850)
- test case 1:
- test case 2:
- ...
> Fixed activity filter depth

- tests/acceptance/bootstrap/CollaborationContext.php
- tests/acceptance/features/apiCollaboration/wopi.feature
Added test to create text file with `/app/new` endpoint.
> [tests-only][full-ci]added test to create text file with `/app/new` endpoint

- tests/acceptance/bootstrap/OcmContext.php
- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiOcm/createInvitation.feature
- check email validation
- fixed test createInvitation.feature:63 and delete it from expected failures file because I don't know when it's gonna get fixed. 
- skipped temporally createInvitation.feature:138 - flaky
> check email validation

- tests/acceptance/features/apiCollaboration/wopi.feature
Added test to create file with .odt extension using `/app/new` endpoint.
> [tests-only][full-ci] added test to create file with .odt extension using `/app/new` endpoint

- changelog/unreleased/fix-ocm-space-sharing.md
- services/graph/pkg/service/v0/api_driveitem_permissions.go
Prevent adding the federated users as members of the space.
- Fixes  [#10051](https://github.com/owncloud/ocis/issues/10051)
- test case 1:
- test case 2:
- ...
> prevent adding the federated users as members of the space

- tests/acceptance/bootstrap/SearchContext.php
This PR updates `userSearchesUsingWebDavAPI` function which uses `REPORT` request to search for files/folders.
Updates:
- remove `spaceId` from the spaces webDav url : `https://localhost:9200/remote.php/dav/spaces/{space-id}`
- remove `username` from new webDav url : `https://localhost:9200/remote.php/dav/files/Alice`
- change request sending approach:
- directly send request using `HttpRequestHelper` instead of using `makeDavRequest` from `WebDavHelper`
- Related to: https://github.com/owncloud/ocis/issues/9991
- CI
- locally
> [tests-only][full-ci] refactor userSearchesUsingWebDavAPI function to update davPath for new and spaces dav versions

- services/activitylog/pkg/config/config.go
Fixes https://github.com/owncloud/ocis/issues/10013
> [docs-only] Fix typo in envvar

- services/graph/README.md
Add some details about the users and groups endpoints provided by the graph service.
> [docs-only] graph(docs): More details for the README

- ocis/README.md
Refernces: #10015 (fix: improve some wordings and cli table)
The table in the readme got an update, a human readable name was added before the UID.
The example (shortened) was taken from the referenced PR.
> [docs-only] Update the "List Unified Roles" example output

- changelog/unreleased/fileupdated-activity.md
- services/activitylog/pkg/service/http.go
- services/activitylog/pkg/service/response.go
- tests/acceptance/features/apiActivities/shareActivities.feature
Adds an Activity when a file is updated. 
Fixes https://github.com/owncloud/ocis/issues/10001
> Add FileUpdated Activity

- services/collaboration/pkg/middleware/tracing.go
Need that return in order to skip the tracing middleware. It's a weird case because the wopi context should exist, so the code shouldn't reach that point.
No open issue
Not tested. The code shouldn't be able to reach that point under normal circumstances.
> fix: missing return in the tracing middleware if we want to skip it

- docs/helpers/env_vars.yaml
Autogenerated as result of `make -C docs docs-generate`, regular chore task.
> [docs-only][chore] Update env_vars.yaml

- changelog/unreleased/fix-proxy-build-info.md
- services/proxy/pkg/metrics/metrics.go
The version string for the proxy service has been written as 'versions'; it needs to be changed.
[OCSRE-273 Jira Issue](https://kiteworks.atlassian.net/jira/software/c/projects/OCSRE/issues/OCSRE-273?filter=myopenissues&jql=project%20%3D%20%22OCSRE%22%20AND%20assignee%20IN%20%28currentUser%28%29%29%20AND%20statusCategory%20IN%20%28%22To%20Do%22%2C%20%22In%20Progress%
- test case 1:
- test case 2:
- ...
> Changing the "versions" string to "version" for Proxy Service

- tests/acceptance/bootstrap/OcmContext.php
- tests/acceptance/features/apiOcm/createInvitation.feature
example: https://drone.owncloud.com/owncloud/ocis/39157/43/10
> [test-only]fix email test

- tests/acceptance/bootstrap/GraphContext.php
- tests/acceptance/bootstrap/SharingNgContext.php
- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiOcm/share.feature
> [test-only] adjust ocm sharing tests

- changelog/unreleased/fix-activity-limit.md
- services/activitylog/pkg/service/http.go
Limits activities correctly.
Fixes https://github.com/owncloud/ocis/issues/10150
> Fix Activity Limit

- tests/acceptance/bootstrap/FeatureContext.php
Throw custom error for json schema errors. These errors could be helpful to pinpoint the error location and find what went wrong.
Some examples:
```
JSON Schema validation failed:
1. properties.value.items.0.properties.template.properties.variables.properties.user.properties.displayName:
- Const failed
Expected: Alice Hansen
Received: Alice
```
```
JSON Schema validation failed:
1. properties.required:
- Array is not unique
```
- Fixes https://github.com/owncloud/ocis/issues/10128
> [tests-only] custom error message for json validation error

- changelog/unreleased/fix-acitivity-folder.md
- services/activitylog/pkg/service/http.go
- services/activitylog/pkg/service/response.go
- tests/acceptance/features/apiActivities/activities.feature
- tests/acceptance/features/apiActivities/shareActivities.feature
- Fixes https://github.com/owncloud/ocis/issues/10148
We fixed the missing folder variable when the folder was renamed.
- test case 1:
- test case 2:
- ...
> We fixed the missing folder variable when folder renamed

- changelog/unreleased/fix-select-next-gateway-client.md
- services/collaboration/pkg/connector/contentconnector.go
- services/collaboration/pkg/connector/contentconnector_test.go
- services/collaboration/pkg/connector/fileconnector.go
- services/collaboration/pkg/connector/fileconnector_test.go
- services/collaboration/pkg/connector/httpadapter.go
- services/collaboration/pkg/connector/httpadapter_test.go
address sonarcloud complaints from https://github.com/owncloud/ocis/pull/10133 that got merged early
> [full-ci] address Gtw selector sonarcloud complaints

- tests/acceptance/features/apiCollaboration/wopi.feature
Add issue tag in the test scenarios related to creating file using `/app/new` endpoint.
> [tests-only][full-ci]add issue tag in file creating scenarios for /app/new endpoint

- changelog/unreleased/fix-ocm-space-sharing-code.md
- services/graph/pkg/service/v0/api_driveitem_permissions.go
- test case 1:
- test case 2:
- ...
> We fixed the error code for ocm space sharing

- changelog/unreleased/bump-reva.md
- go.mod
- go.sum
- vendor/modules.txt
Enhancement: Bump reva to 2.25.0
*   Bugfix [cs3org/reva#4854](https://github.com/cs3org/reva/pull/4854): Added ShareUpdate activity
*   Bugfix [cs3org/reva#4865](https://github.com/cs3org/reva/pull/4865): Better response codes for app new endpoint
*   Bugfix [cs3org/reva#4858](https://github.com/cs3org/reva/pull/4858): Better response codes for app new endpoint
*   Bugfix [cs3org/reva#4867](https://github.com/cs3org/reva/pull/4867): Fix remaining space calculation for S3 blobstore
*   Bugfix [cs3org/reva#4852](https://github.com/cs3org/reva/pull/4852): Populate public link user correctly
*   Bugfix [cs3org/reva#4859](https://github.com/cs3org/reva/pull/4859): Fixed the collaboration service registration
*   Bugfix [cs3org/reva#4835](https://github.com/cs3org/reva/pull/4835): Fix …
> [full-ci] chore: bump reva to v2.25.0

- deployments/examples/ocis_full/collabora.yml
- deployments/examples/ocis_full/debug-collaboration-collabora.yml
- deployments/examples/ocis_full/debug-collaboration-onlyoffice.yml
- deployments/examples/ocis_full/onlyoffice.yml
- ocis/docker/Dockerfile.linux.debug.amd64
Improve the docker compose
1. After #10174 we need the OCIS_URL in the collaboration service environment (@d7oc @mmattel IMPORTANT addition)
2. Improve the debug docker setup
- test case 1:
- test case 2:
- ...
> fix: improve docker compose

- .drone.star
same as #10192
not needed for master branch
example here https://drone.owncloud.com/owncloud/ocis/39506/1/1
> do not run coding standart php step when releasing

- tests/acceptance/bootstrap/SpacesContext.php
- tests/acceptance/features/apiSharingNg1/propfindShares.feature
Added the following test scenario:
```feature
Scenario Outline: check file-id of different PROPFIND requests to shared items
```
- Coverage for #9933
> [tests-only][full-ci] add test coverage for #9933

- changelog/unreleased/fix-delete-share-panic.md
- services/graph/pkg/service/v0/utils.go
Avoids the panic in https://github.com/owncloud/ocis/issues/10213
There might be another issue.
> Fix panic when deleting ocm shares

- docs/ocis/deployment/ocis_full.md
References: https://github.com/owncloud/ocis/issues/10053?notification_referrer_id=NT_kwDOADKtwbMxMjQxMjYwNjk3MjozMzIxMjgx#issuecomment-2391127835
* Small fixes
* Add an important note if deviating from the default
> [docs-only] Update ocis_full.md in dev docs, add an important note

- deployments/examples/ocis_full/README.md
References: https://github.com/owncloud/ocis/issues/10053?notification_referrer_id=NT_kwDOADKtwbMxMjQxMjYwNjk3MjozMzIxMjgx#issuecomment-2391127835
Make the readme more clear about where to get which documentation for which audience.
> [docs-only] Update deployment examples ocis_full README.md

- tests/acceptance/bootstrap/FeatureContext.php
- tests/acceptance/bootstrap/SpacesTUSContext.php
- tests/acceptance/bootstrap/TUSContext.php
- tests/acceptance/features/coreApiWebdavUploadTUS/uploadFile.feature
> [tests-only] add test coverage for #8804

- tests/acceptance/TestHelpers/BehatHelper.php
- tests/acceptance/bootstrap/ArchiverContext.php
- tests/acceptance/bootstrap/AuthContext.php
- tests/acceptance/bootstrap/CapabilitiesContext.php
- tests/acceptance/bootstrap/ChecksumContext.php
- tests/acceptance/bootstrap/CliContext.php
- tests/acceptance/bootstrap/CollaborationContext.php
- tests/acceptance/bootstrap/FavoritesContext.php
- tests/acceptance/bootstrap/FeatureContext.php
- tests/acceptance/bootstrap/FilesVersionsContext.php
- tests/acceptance/bootstrap/GraphContext.php
- tests/acceptance/bootstrap/NotificationContext.php
- tests/acceptance/bootstrap/OCSContext.php
- tests/acceptance/bootstrap/OcmContext.php
- tests/acceptance/bootstrap/PublicWebDavContext.php
- tests/acceptance/bootstrap/SearchContext.php
- tests/acceptance/bootstrap/SettingsContext.php
- tests/acceptance/bootstrap/ShareesContext.php
- tests/acceptance/bootstrap/SharingNgContext.php
- tests/acceptance/bootstrap/SpacesContext.php
- tests/acceptance/bootstrap/SpacesTUSContext.php
- tests/acceptance/bootstrap/TUSContext.php
- tests/acceptance/bootstrap/TagContext.php
- tests/acceptance/bootstrap/TrashbinContext.php
- tests/acceptance/bootstrap/WebDavLockingContext.php
- tests/acceptance/bootstrap/WebDavPropertiesContext.php
- tests/acceptance/config/behat.yml
Get the context and if not found, register it and return the context
- the failure in posixfs is not related to this PR.
> [tests-only][full-ci] get necessary contexts properly

- tests/acceptance/bootstrap/GraphContext.php
- tests/acceptance/features/apiActivities/activities.feature
This PR adds test to check activities with limit and sort filter (ascending | descending).
``` feature
Scenario: check activity with limit and sort filter(asc|desc)
```
- Bug Report: https://github.com/owncloud/ocis/issues/10150
- locally
- CI
> [tests-only][full-ci] add test to check api activities with limit and sort filter

- services/storage-system/README.md
Just a small text addon into the `storage-system` readme to describe its purpose.
> [docs-only] Describe the storage-system service purpose

- tests/acceptance/bootstrap/SearchContext.php
- tests/acceptance/features/apiSearch1/search.feature
This PR ensures that:
- file can/can't be searched either globally (in all drives) or from root of a specific drive (Personal drive, Shares drive, and project drive)
- Related to:  https://github.com/owncloud/ocis/issues/9948
- Locally
- CI
> [tests-only][full-ci] test: extend test coverage for searching a file

- docs/helpers/env_vars.yaml
Just a regular `env_vars.yaml` update generated via `make -C docs docs-generate`.
> [docs-only][chore] Regular env_vars.yaml update

- services/idp/pkg/server/debug/server.go
This PR refactores the check for ldap in IDP
> fix ldap check in idp

- ocis-pkg/handlers/checkgrpc.go
- services/search/pkg/server/debug/server.go
- services/settings/pkg/server/debug/server.go
- services/thumbnails/pkg/server/debug/server.go
This PR adds grpc health checks to search, settings & thumbnail.
refs #10281 
refs #8783
> Grpc checks

- services/audit/pkg/server/debug/server.go
- services/clientlog/pkg/server/debug/server.go
- services/eventhistory/pkg/server/debug/server.go
- services/notifications/pkg/server/debug/server.go
- services/search/pkg/server/debug/server.go
- services/sse/pkg/server/debug/server.go
- services/userlog/pkg/server/debug/server.go
refs #10281 
refs #10281 
Added services:
```
audit
clientlog
eventhistory
notifications 
search
sse
userlog
```
> the server probs added to the several services

- changelog/unreleased/bump-reva.md
- go.mod
- go.sum
- vendor/github.com/cs3org/reva/v2/internal/grpc/interceptors/eventsmiddleware/events.go
- vendor/github.com/cs3org/reva/v2/internal/grpc/services/usershareprovider/usershareprovider.go
- vendor/github.com/cs3org/reva/v2/internal/http/services/appprovider/appprovider.go
- vendor/github.com/cs3org/reva/v2/internal/http/services/appprovider/templates.go
- vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocdav/trashbin.go
- vendor/github.com/cs3org/reva/v2/pkg/mime/mime.go
- vendor/github.com/cs3org/reva/v2/pkg/ocm/storage/received/upload.go
- vendor/github.com/cs3org/reva/v2/pkg/rhttp/datatx/manager/tus/tus.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/decomposedfs.go
- vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/events.go
- vendor/modules.txt
- test case 1:
- test case 2:
- ...
> [full-ci] chore: bump reva to latest edge

- changelog/unreleased/fix-ocm-space-sharing.md
- services/graph/pkg/service/v0/api_driveitem_permissions.go
We forbid adding the federated users as members of the space via items invite.
- Fixes https://github.com/owncloud/ocis/issues/10051
- test case 1:
- test case 2:
- ...
> forbid adding the federated users as members of the space via items invite

- tests/acceptance/features/apiOcm/share.feature
This PR adds tests where the sharer lists the shares shared by him to a federated user.
``` feature
Scenario: sharer lists the shares shared by him to a federated user
```
- Bug Report: https://github.com/owncloud/ocis/issues/9908
- locally
- CI
> [tests-only][full-ci] add test to list shares shared to federated user

- docs/helpers/README.md
Improve the description of the helpers process.
> [docs-only] Update helpers/README.md

- services/antivirus/pkg/server/debug/server.go
- services/collaboration/pkg/server/debug/server.go
- services/frontend/pkg/server/debug/server.go
- services/gateway/pkg/server/debug/server.go
- services/graph/pkg/server/debug/server.go
- services/idp/pkg/server/debug/server.go
- services/ocm/pkg/server/debug/server.go
- services/ocs/pkg/server/debug/server.go
- services/policies/pkg/server/debug/server.go
- services/postprocessing/pkg/server/debug/server.go
- services/proxy/pkg/server/debug/server.go
- services/sharing/pkg/server/debug/server.go
- services/storage-users/pkg/server/debug/server.go
- test case 1:
- test case 2:
- ...
> checks added

- services/activitylog/pkg/server/debug/server.go
- services/antivirus/pkg/server/debug/server.go
- services/audit/pkg/server/debug/server.go
- services/clientlog/pkg/server/debug/server.go
- services/eventhistory/pkg/server/debug/server.go
- services/frontend/pkg/server/debug/server.go
- services/graph/pkg/server/debug/server.go
- services/notifications/pkg/server/debug/server.go
- services/policies/pkg/server/debug/server.go
- services/search/pkg/server/debug/server.go
- services/sse/pkg/server/debug/server.go
- services/userlog/pkg/server/debug/server.go
Fixed the wrong nats probe config.
- test case 1:
- test case 2:
- ...
> nats checks fixed

- changelog/unreleased/bump-reva.md
- go.mod
- go.sum
- vendor/modules.txt
Enhancement: Bump reva to 2.26.0
*   Bugfix [cs3org/reva#4880](https://github.com/cs3org/reva/pull/4880): Kept historical resource naming in activity
*   Bugfix [cs3org/reva#4874](https://github.com/cs3org/reva/pull/4874): Fix rename activity
*   Bugfix [cs3org/reva#4881](https://github.com/cs3org/reva/pull/4881): Log levels
*   Bugfix [cs3org/reva#4884](https://github.com/cs3org/reva/pull/4884): Fix OCM upload crush
*   Bugfix [cs3org/reva#4872](https://github.com/cs3org/reva/pull/4872): Return 409 conflict when a file was already created
*   Bugfix [cs3org/reva#4887](https://github.com/cs3org/reva/pull/4887): Fix ShareCache concurrency panic
*   Bugfix [cs3org/reva#4876](https://github.com/cs3org/reva/pull/4876): Fix share jail mountpoint parent id
*   Bugfix …
> [full-ci] [k6-test] chore: bump reva to v2.26.0

- tests/acceptance/bootstrap/CollaborationContext.php
- tests/acceptance/features/apiCollaboration/checkFileInfo.feature
This pull request adds test cases to ensure that the MIME type application/octet-stream is absent in the app/list endpoint. 
- Fixes: https://github.com/owncloud/ocis/issues/10179
- Test coverage for: https://github.com/owncloud/ocis/issues/10086
- Locally
- CI
> [tests-only][full-ci] test: Check absence of application/octet-stream MIME Type in app/list

- tests/acceptance/features/apiSharingNg1/sharedByMe.feature
- tests/acceptance/features/apiSharingNg1/sharedWithMe.feature
This PR adds tests to check his/her shares(share-by-me & share-with-me) shared to a group being member of a group. 
``` feature
Scenario: group member as a sharer lists the file and folder shares shared to group (Personal space)
Scenario: group member as a sharer lists the file and folder shares shared to group (Project space)
Scenario: group member as a sharee lists the file and folder shares shared via group invitation (Personal space)
Scenario: group member as a sharee lists the file and folder shares shared via group invitation (Project space)
```
- Part of: https://github.com/owncloud/ocis/issues/10124
- locally
- CI
> [tests-only][full-ci] add test to list shares sharedByMe/sharedWithMe being member of a group

- docs/helpers/env_vars.yaml
- docs/helpers/extended_vars.yaml
Regular maintenance task to update changes in `envvars.yaml` and `extended_vars.yaml` triggered by `make -C docs docs-generate`.
> [docs-only][chore] Update envvars.yaml and extended_vars.yaml

- changelog/unreleased/security-fixes.md
- ocis-pkg/service/grpc/client.go
- ocis/pkg/command/benchmark.go
- services/collaboration/pkg/connector/contentconnector.go
- services/collaboration/pkg/helpers/discovery.go
- services/collaboration/pkg/proofkeys/handler.go
- services/notifications/pkg/email/email.go
- services/proxy/pkg/middleware/signed_url_auth.go
We polished some of the sonarcloud issues.
fixes https://github.com/owncloud/ocis/issues/10374
> Security fixes

- changelog/unreleased/postprocessing-events.md
- services/postprocessing/pkg/service/service.go
> fix postprocessing events

- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiOcm/share.feature
This PR refactors the following test scenario:
``` feature
Scenario Outline: try to add federated user as a member of a project space (permissions endpoint)
```
- Bug Report: https://github.com/owncloud/ocis/issues/10051
- locally
- CI
> [tests-only][full-ci] refactor test to add federated user as a member of a project space using permissions endpoint

- changelog/unreleased/fix-disable-download-activity.md
- services/activitylog/pkg/service/service.go
We disable the public link download activity until we have a proper solution for it.
- Fixes  https://github.com/owncloud/ocis/issues/10293
- https://github.com/owncloud/ocis/issues/10231
- test case 1:
- test case 2:
- ...
> Disable download activity

- docs/helpers/env_vars.yaml
- docs/services/general-info/port-ranges.md
Fix some typos, update env_vars.yaml.
> [docs-only] fix docs

- docs/services/general-info/port-ranges.md
- services/ocdav/pkg/config/defaults/defaultconfig.go
This PR adds a new port-range to the ocdav service for the health checks.
> add new range for ocdav

- tests/acceptance/features/apiActivities/activities.feature
This PR adds tests to check activities of a folder after renaming it.
``` feature
Scenario: check activities of a folder after renaming
```
- Bug Report: https://github.com/owncloud/ocis/issues/10210
- locally
- CI
> [tests-only][full-ci] add test to check activities of a folder after renaming

- tests/acceptance/features/apiActivities/activities.feature
This PR adds tests to check activities of destination file and folder after moving a file into a folder.
``` feature
Scenario: check activities of destination folder after moving a file into it
Scenario: check activities of destinaton file and folder after moving a 0 byte file into it
Scenario: check activities of destinaton file and folder after moving a file by renaming destination file
Scenario: check activities of destinaton file and folder after moving a 0 byte file by renaming destination file
```
- https://github.com/owncloud/ocis/issues/9543#issuecomment-2431703972
- locally
- CI
> [tests-only][full-ci] add test to check move activities of destination file and folder

- changelog/unreleased/remove-deprecated-cli-commans.md
- services/storage-users/pkg/command/uploads.go
We removed the following deprecated CLI commands:
`ocis storage-users uploads list`
`ocis storage-users uploads clean`
- Fixes [<issue_link>](https://github.com/owncloud/ocis/issues/10428)
- test case 1:
- test case 2:
- ...
> Remove deprecated CLI commands

- services/collaboration/pkg/config/app.go
> [docs-only] Update collaboration envvar descriptions

- .drone.star
- deployments/continuous-deployment-config/ocis_full/onlyoffice-master.yml
- deployments/examples/ocis_full/onlyoffice.yml
- docs/ocis/deployment/continuous_deployment.md
Add https://ocis.ocis-onlyoffice.master.owncloud.works to the continuous deployments.
- test case 1:
- test case 2:
- ...
> [docs-only] feat: add ocis master deployment with OnlyOffice

- changelog/unreleased/collaboration-product-name.md
Changelog entry for https://github.com/owncloud/ocis/pull/10335
- test case 1:
- test case 2:
- ...
> chore: add changelog entry

- docs/helpers/env_vars.yaml
References: #10477 
* New code has been added that changed envvars
* We need to remove all `STORE_` envvars because the service has been removed
Missed to do that in the referenced PR.
With the code that is just in work, missing fixes get much easier highlighted.
> [docs-only] Update envvars.yaml based on recent changes

- changelog/unreleased/bump-reva.md
- go.mod
- go.sum
- vendor/modules.txt
Enhancement: Bump reva to 2.26.3
*   Bugfix [cs3org/reva#4908](https://github.com/cs3org/reva/pull/4908): Add checksum to OCM storageprovider responses
*   Enhancement [cs3org/reva#4910](https://github.com/cs3org/reva/pull/4910): Bump cs3api
*   Enhancement [cs3org/reva#4909](https://github.com/cs3org/reva/pull/4909): Bump cs3api
*   Enhancement [cs3org/reva#4906](https://github.com/cs3org/reva/pull/4906): Bump cs3api
- test case 1:
- test case 2:
- ...
> chore: update reva to 2.26.3

- docs/helpers/env_vars.yaml
As the title says, needed for added envvars.
> [docs-only] Update env_vars.yaml due to recent changes

- docs/services/general-info/env-var-deltas/5.0.0-7.0.0-added.adoc
Due to recent changes, the added envvar table needs an update
> [docs-only] Update added envvar table due to recent changes

- docs/services/general-info/env-var-deltas/5.0.0-7.0.0-added.adoc
This envvar was missing in the added table.
Should be final now (hopefully)... 😅
> [docs-only] One more added envvar change found

- changelog/7.0.0-rc.1_2024-11-07/fix-remove-non-working-ocm-setting.md
Fixed PR number in the changelog entry
- https://github.com/owncloud/ocis/pull/10425
> [docs-only] fix PR number

- changelog/7.0.0-rc.1_2024-11-07/bump-cs3-api.md
- changelog/7.0.0-rc.1_2024-11-07/concurrent-autoaccept.md
- changelog/7.0.0-rc.1_2024-11-07/fix-get-lock-header.md
- changelog/7.0.0-rc.1_2024-11-07/fix-memlimit-loglevel.md
- changelog/7.0.0-rc.1_2024-11-07/fix-proofkeys-proxy.md
- changelog/7.0.0-rc.1_2024-11-07/ggp-mimetype-thumbnails.md
- changelog/7.0.0-rc.1_2024-11-07/remove-deprecated-cli-commans.md
Continuation of https://github.com/owncloud/ocis/pull/10514
There were other incorrect issue and pr links
> docs: fix issue and PR numbers

- deployments/examples/ocis_full/.env
Based in a comment from @jvillafanez in [talk](https://talk.owncloud.com/channel/infinitescale?msg=uHKvLem5HBG6ty585), we need to add a comment in the `.env` file of the `ocis_full` deployment example to avoid app interlocking issues.
Note that this PR should go into v7.
> [docs-only] Add important comment to .env in ocis_full deployment

- changelog/unreleased/remove-mbreaker.md
- ocis-pkg/service/grpc/client.go
Removes the circuit breaker as it brought more issues than benefits.
> Remove gobreaker lib

- .drone.star
- tests/acceptance/run.sh
With this PR, the nightly builds will run on both configs, i.e. with and without `remote.php` in dav path.
Nightly builds currently runs with `WITH_REMOTE_PHP=false`. We want nightly builds to run with both the config.
- Suites have been regrouped to reduce the number of pipelines.
- Number of core API test pipelines are reduced from 10 to 7.
There will be two pipelines for every suites, and the pipelines are named as:
- `apiSpaces` - runs with config `remote.php` in dav path
- `apiSpaces-without-remote.php` - runs without config `remote.php` in dav path
The nightly builds would run similar to the following build:
- https://drone.owncloud.com/owncloud/ocis/40772
- https://drone.owncloud.com/owncloud/ocis/40854
- https://drone.owncloud.com/owncloud/ocis/40903
- …
> [tests-only][full-ci] run cron job on both config, with and without `remote.php` in dav path

- tests/acceptance/features/apiActivities/activities.feature
This PR adds tests to check activities of destination file and folder after copying a file into a folder.
``` feature
Scenario: check activities of destination file and folder after copying a file into it
Scenario: check activities of destination file and folder after copying a file by renaming the destination file
Scenario: check activities of destination file after copying a file into same folder by renaming the destination file
```
- https://github.com/owncloud/ocis/issues/9543#issuecomment-2437022281
- locally
- CI
> [tests-only][full-ci] add test to check copy activities of destination file and folder

- services/proxy/README.md
References: #10537 ([docs-only] Claim update process (proxy service readme))
Just a small text fix
> [docs-only] Text fix in proxy readme

- tests/acceptance/features/apiActivities/activitiesByFileId.feature
This PR adds tests to check activities of destination file and folder after moving a file using it's file-id into a folder.
``` feature
Scenario: check copy activity of destination resource
Scenario: check activities of destination file and folder after copying a file into it by renaming
Scenario: check activities of destination file and folder after copying file into same folder it BY RENAMING
```
- https://github.com/owncloud/ocis/issues/9543#issuecomment-2464530896
- CI
- Locally
> [tests-only][full-ci] add test to check activities of destination file and folder by copying a file using file-id

- services/idp/pkg/backends/cs3/identifier/cs3.go
- services/idp/pkg/backends/cs3/identifier/session.go
This seems obsolete code since it isn't being used at the moment.
It also seems a wrong approach: the session is being cached, which implies it will be reused in other requests. The problem is that the original context comes from the request, so the context will be done when the request finishes and the data contained in the context should be considered as obsolete. Using that cached context will cause problems because the context is already done, and the data in the context is likely useless and could be confusing.
No open issue. Since that piece of code is unused, this might have low priority.
The code seems potentially dangerous.
- test case 1:
- test case 2:
- ...
> fix: remove context from the session

- changelog/unreleased/limit-sharing-workers.md
- services/sharing/pkg/config/config.go
related https://github.com/owncloud/ocis/issues/10576
> fix sharing concurrency env

- changelog/unreleased/collaboration-gateway-selector.md
- services/collaboration/pkg/service/grpc/v0/option.go
- services/collaboration/pkg/service/grpc/v0/service.go
- services/collaboration/pkg/service/grpc/v0/service_test.go
> use gateway selector

- changelog/unreleased/fix-activity-mapping.md
- services/activitylog/pkg/service/response.go
Fixed the activity field mapping
- Fixes https://github.com/owncloud/ocis/issues/10228
- test case 1:
- test case 2:
- ...
> Fixed the activity field mapping

- .drone.env
- changelog/unreleased/update-web-11.0.4.md
- services/web/Makefile
- Bugfix [owncloud/web#11916](https://github.com/owncloud/web/issues/11916): Fix order in roles drop down
- Bugfix [owncloud/web#11923](https://github.com/owncloud/web/issues/11923): Allow create template with different editors
- Bugfix [owncloud/web#11924](https://github.com/owncloud/web/issues/11924): Extension actions in right sidebar
- Bugfix [owncloud/web#11929](https://github.com/owncloud/web/issues/11929): Unique request ids
> [full-ci] chore: bump web to v11.0.4

- go.mod
- services/collaboration/pkg/wopisrc/wopisrc.go
Seems this was missed in 109b23966c6
> Bump golang-jwt/jwt to v5

- tests/acceptance/features/apiActivities/activities.feature
This PR adds test coverage to ensure that activity messages correctly reference the parent folder for file operations
- Test coverage for bug: https://github.com/owncloud/ocis/issues/9536
- locally
- CI
> [tests-only][full-ci] Add test coverage for correct parent folder reference in activity messages

- .drone.star
- Removed unused oc10 volumes
- Use health check for ocis standalone services
- Run with and without remotephp pipelines on `full-ci` PRs
> [tests-only][full-ci] ci: cleanup drone config

- docs/services/general-info/env-var-deltas/5.0.0-7.0.0-added.adoc
- docs/services/general-info/env-var-deltas/5.0.0-7.0.0-deprecated.adoc
- docs/services/general-info/env-var-deltas/5.0.0-7.0.0-removed.adoc
This PR updates the added/removed/deprecated envvar adoc tables with containing recent changes.
> [docs-only] Update the added/removed/deprecated envvars adoc table

- docs/architecture/posixfs-storage-driver.md
> [docs-only] Update posixfs-storage-driver.md

- tests/acceptance/bootstrap/CollaborationContext.php
- tests/acceptance/bootstrap/NotificationContext.php
Cleanup https://github.com/owncloud/ocis/pull/10609#discussion_r1861535085
> [tests-only] do not use unnecessary array

- tests/acceptance/features/apiOcm/share.feature
This PR updates the following test scenario to check mimeType of federated share image file.
``` feature
Scenario: local user lists multiple federation shares
```
- Bug report: https://github.com/owncloud/ocis/issues/10495
- Locally
- CI
> [tests-only][full-ci] update test to check mimetype of federated share image file

- docs/helpers/env_vars.yaml
Referencing: #10683 (graph concurrent share listing)
Update the env_vars.yaml file necessary for docs generation via
`make -C docs docs-generate`
> [docs-only] Update env_vars.yaml

- ocis/README.md
Referfences: #10712 (Cleanup stale shares)
Add docs to the common command list.
Only merge when the referenced PR got merged.
> [docs-only] Add 'ocis shares cleanup' command to the common readme

- tests/acceptance/TestHelpers/Asserts/WebDav.php
- tests/acceptance/bootstrap/CapabilitiesContext.php
- tests/acceptance/bootstrap/CollaborationContext.php
- tests/acceptance/bootstrap/FeatureContext.php
- tests/acceptance/bootstrap/FilesVersionsContext.php
- tests/acceptance/bootstrap/OCSContext.php
- tests/acceptance/bootstrap/Provisioning.php
- tests/acceptance/bootstrap/ShareesContext.php
- tests/acceptance/bootstrap/Sharing.php
- tests/acceptance/bootstrap/SpacesContext.php
- tests/acceptance/bootstrap/TrashbinContext.php
- tests/acceptance/bootstrap/WebDav.php
- tests/acceptance/bootstrap/WebDavLockingContext.php
- tests/acceptance/bootstrap/WebDavPropertiesContext.php
1. This PR removes following method and variable
- getResponseXml
- setResponseXml
- getResponseXmlObject
- setResponseXmlObject
- $responseXml instance variable
- $responseXmlObject instance variable
2. removed unused method and step definition
3. replace exception with assertion
- Fixes https://github.com/owncloud/ocis/issues/10650
- CI
> [tests-only][full-ci]Remove duplicate function 

- tests/acceptance/check-deleted-suites-in-expected-failure.sh
Fixes the check for deleted files in the expected failure files in case of typos.
- typos in suite name
- typos in feature file name
```md
- [oreApiVersions/fileVersionAuthor.feature:14](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/coreApiVersions/fileVersionAuthor.feature#L14)
- [coreApiVersions/fileersionAuthor.feature:60](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/coreApiVersions/fileVersionAuthor.feature#L60)
- [coreApiVersions/fileVersionAuthor.feature:92](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/coreApiVersions/fileVersionAuthor.feature#L92)
```
```bash
The following test scenarios do not exist anymore:
They can be deleted from the 'expected-failures-API-on-OCIS-storage.md' …
```
> [tests-only][full-ci] fix check for deleted suites in expected failure file

- services/auth-app/README.md
This PR fixes a typo in auth-app documentation
- test case 1:
- test case 2:
- ...
> [docs-only] fixing auth-app api docs for creating token via impersonation API

- deployments/examples/ocis_full/collabora.yml
- deployments/examples/ocis_full/docker-compose.yml
- deployments/examples/ocis_full/inbucket.yml
- deployments/examples/ocis_full/minio.yml
- deployments/examples/ocis_full/ocis.yml
- deployments/examples/ocis_full/onlyoffice.yml
- deployments/examples/ocis_full/web_extensions/importer.yml
This PR:
* Does a proper naming of the traefik lables to identify what is letsencrypt related.
* Updates the collabora image, includes some bugfixes
> [docs-only][chore] Improve readbility of traefik labels

- deployments/examples/ocis_full/collabora.yml
- deployments/examples/ocis_full/docker-compose.yml
- deployments/examples/ocis_full/inbucket.yml
- deployments/examples/ocis_full/minio.yml
- deployments/examples/ocis_full/ocis.yml
- deployments/examples/ocis_full/onlyoffice.yml
- deployments/examples/ocis_full/web_extensions/importer.yml
> Revert "[docs-only][chore] Improve readbility of traefik labels"

- changelog/unreleased/fix-link-activity.md
- services/activitylog/pkg/service/http.go
- tests/acceptance/features/apiActivities/shareActivities.feature
We changed the link token to display name in the activity message.
- Fixes [#10295](https://github.com/owncloud/ocis/issues/10295)
- test case 1:
- test case 2:
- ...
> Fix link activity message

- deployments/continuous-deployment-config/ocis_full/master.yml
- deployments/continuous-deployment-config/ocis_full/onlyoffice-master.yml
- deployments/continuous-deployment-config/ocis_full/onlyoffice-rolling.yml
- deployments/continuous-deployment-config/ocis_full/production.yml
- deployments/continuous-deployment-config/ocis_full/rolling.yml
- deployments/continuous-deployment-config/ocis_full/s3-rolling.yml
- deployments/continuous-deployment-config/ocis_keycloak/rolling.yml
- deployments/continuous-deployment-config/ocis_ldap/rolling.yml
> Remove my ssh key for cd deployments

- tests/acceptance/features/apiSharingNgShareInvitation/updateShareInvitations.feature
This PR covers the tests for updating the share permissions role of a resource to a disabled permissions role. Updating the share permissions role to `Secure Viewer`, `Denied` and `Space Editor Without Versions` without enabling them.
Test coverage for https://github.com/owncloud/ocis/issues/10768
> [tests-only][full-ci] added test to update share permissions role of a resource to a permissons role which is not enabled

- .github/CODEOWNERS
- deployments/continuous-deployment-config/ocis_full/master.yml
- deployments/continuous-deployment-config/ocis_full/onlyoffice-master.yml
- deployments/continuous-deployment-config/ocis_full/onlyoffice-rolling.yml
- deployments/continuous-deployment-config/ocis_full/production.yml
- deployments/continuous-deployment-config/ocis_full/rolling.yml
- deployments/continuous-deployment-config/ocis_full/s3-rolling.yml
- deployments/continuous-deployment-config/ocis_keycloak/rolling.yml
- deployments/continuous-deployment-config/ocis_ldap/rolling.yml
Good bye 👋 
- test case 1:
- test case 2:
- ...
> [docs-only] chore: change access to deployments

- .drone.star
> [docs-only] Prepare stable branch

- services/storage-users/pkg/config/config.go
References: #10780 (S3 Improvements)
This PR updates the S3 PART_SIZE envvar description text.
Needs backport to stable-7
> [docs-only] Update S3 PART_SIZE envvar description text

- services/storage-users/pkg/config/config.go
References: #10789 ([docs-only] Update S3 PART_SIZE envvar description text)
Backport of the referenced PR.
> [docs-only] [7.0] Update S3 PART_SIZE envvar description text

- docs/services/general-info/env-var-deltas/5.0.0-7.0.0-added.adoc
Removing one cell entry as it was double present
> [docs-only] [chore] Just a small fix in v7 added envvars table

- docs/services/general-info/env-var-deltas/5.0.0-7.0.0-added.adoc
Backport of #10799 ([docs-only] [chore] Just a small fix in v7 added envvars table)
> [docs-only] [7.0] [chore] Just a small fix in v7 added envvars table

- changelog/unreleased/fix-graph-invite-createddatetime.md
- services/graph/pkg/service/v0/api_driveitem_permissions.go
The graph drives invite response now includes the `createdDateTime` field.
- Fixes [#10739](https://github.com/owncloud/ocis/issues/10739)
- test case 1:
- test case 2:
- ...
> The graph drives invite response now includes the createdDateTime field

- tests/acceptance/features/apiOcm/ocmEndpoint.feature
In this PR there is an added test for checking the response of ocm .well-known endpoint
Scenario added:
```console
Scenario: check the well known ocm endpoint response
```
- https://github.com/owncloud/ocis/issues/10726
- CI
- locally
> [tests-only][full-ci] Add test for checking the response of ocm .well-known endpoint

- deployments/examples/ocis_full/collabora.yml
- deployments/examples/ocis_full/docker-compose.yml
- deployments/examples/ocis_full/web_extensions/drawio.yml
- deployments/examples/ocis_full/web_extensions/externalsites.yml
- deployments/examples/ocis_full/web_extensions/jsonviewer.yml
- deployments/examples/ocis_full/web_extensions/progressbars.yml
- deployments/examples/ocis_full/web_extensions/unzip.yml
Just some small image version updates.
Tested, works fine.
Should go into 7.1
Backport to 7.0 would be good but is not mandatory
> [docs-only] Update image versions for ocis-full

- deployments/examples/ocis_full/collabora.yml
- deployments/examples/ocis_full/docker-compose.yml
- deployments/examples/ocis_full/web_extensions/drawio.yml
- deployments/examples/ocis_full/web_extensions/externalsites.yml
- deployments/examples/ocis_full/web_extensions/jsonviewer.yml
- deployments/examples/ocis_full/web_extensions/progressbars.yml
- deployments/examples/ocis_full/web_extensions/unzip.yml
> [docs-only][7.0] Update image versions for ocis-full

- docs/services/general-info/document-cli-commands.md
To help devs how to document cli commands
> [docs-only] Add how to document cli commands

- tests/acceptance/features/apiSharingNgLinkSharePermission/createLinkShare.feature
This PR adds test to try creating a link share of a folder with denied permission role.
``` feature
Scenario: try to create a public link share of a folder with denied permissions role
```
- Part of: https://github.com/owncloud/ocis/issues/10656
- Locally
- CI
> [tests-only][full-ci] add test to try creating folder link share with denied role

- docs/helpers/env_vars.yaml
Add the latest changes to envvars.yaml.
(Dont get confused with the changes, they are ok...)
> [docs-only] Update envvars.yaml with latest changes

- changelog/7.1.0-rc.1_2025-01-10/fix-graph-invite-createddatetime.md
This PR updates the PR number in `fix-graph-invite-createddatetime.md` changelog
- Part of: https://github.com/owncloud/ocis/issues/10851
- test case 1:
- test case 2:
- ...
> [docs-only] update PR number in `fix-graph-invite-createddatetime.md` changelog

- tests/acceptance/TestHelpers/EmailHelper.php
In CI, the empty mailbox check test scenario shows a false positive behaviour. So, retry once with wait allows the mail server to receive mails and the test behaves as expected.
- Fixes https://github.com/owncloud/ocis/issues/10903
> [full-ci][tests-only] check mails with wait if the mailbox is empty

- changelog/7.1.0-rc.2_2025-01-17/fix-mail-notifications-for-user-light.md
This PR updates the PR number in `fix-mail-notifications-for-user-light.md` changelog
- Part of: https://github.com/owncloud/ocis/issues/10851
> [docs-only] update PR number in `fix-mail-notifications-for-user-light.md` changelog

- deployments/examples/ocis_full/collabora.yml
Backport of #10922 ([docs-only] Update ocis_full collabora image version)
> [docs-only][7.0] Update ocis_full collabora image version

- .make/go.mk
- changelog/unreleased/enhancement-debug-docker-arm64.md
- ocis/docker/Dockerfile.linux.debug.arm64
implement debug docker for arm64 platform through `make debug-docker`
> feat: Implement debug docker for arm64 platform

- changelog/unreleased/fix-file-extension-check.md
- go.sum
- services/collaboration/pkg/service/grpc/v0/service.go
- services/collaboration/pkg/service/grpc/v0/service_test.go
Fixed Collaboration file extension check to case-insensitive comparison.
- Fixes [#10947](https://github.com/owncloud/ocis/issues/10947)
- test case 1:
- test case 2:
- ...
> Fixed Collaboration file extension check to case-insensitive comparison

- tests/acceptance/bootstrap/NotificationContext.php
This PR refactors the inbucket emails cleanup function such that it cleans up the emails of all the users created.
The tests were passing if a scenario was run individually but failed when run in CI(as it runs the whole feature file).
And due to this reason, some of the emails from previous scenarios were not cleaned up and caused the latter scenarios to fail.
See: https://drone.owncloud.com/owncloud/ocis/43065/20/7
In scenarios like
``` feature
Scenario: disable in-app notification for File rejected event (Project space)
```
the step `And user "Brian" should have "1" emails` was not used, so `$this->featureContext->emailRecipients` would be empty. Hence, there was no cleanup done.
https://github.com/owncloud/ocis/blob/f651e67e441e0ac12300c6e732c24444819f2523/tests/acceptance/bootstrap/Not …
> [tests-only][full-ci] cleanup inbucket emails of all created users after test

- .drone.star
Skipping the changelog pipeline on nightly CI runs. 
- Fixes https://github.com/owncloud/ocis/issues/10912
> [tests-only][full-ci] skip changelog pipeline in nightly ci run

- tests/acceptance/features/apiSettings/notificationSetting.feature
This PR adds test to check email notifications of user with role `User Light`.
``` feature
Scenario Outline: disable email notification for user light
```
- Bug Report: https://github.com/owncloud/ocis/issues/10864
- Locally
- CI
> [tests-only][full-ci] add test to check mail notification for user with role `User Light`

- .drone.env
- changelog/6.5.1_2025-02-05/update-web-to-v10.3.1.md
- ocis-pkg/version/version.go
- services/web/Makefile
- sonar-project.properties
Points to new stable-6.5 branch based on `v6.5.0`
> [full-ci] Release 6.5.1

- .drone.env
- changelog/7.0.1_2025-02-07/update-web-to-v11.0.7.md
- ocis-pkg/version/version.go
- services/web/Makefile
- sonar-project.properties
> [full-ci] release 7.0.1

- deployments/examples/ocis_full/collabora.yml
- deployments/examples/ocis_full/docker-compose.yml
- deployments/examples/ocis_full/onlyoffice.yml
Backport of #11006 ([docs-only] Update images for ocis_full deployment example)
> [docs-only][7.0] Update images for ocis_full deployment example

- tests/acceptance/features/apiOcm/deleteShare.feature
This PR adds test for deleting ocm shares.
Test Coverage for: https://github.com/owncloud/enterprise/issues/7075
- https://github.com/owncloud/ocis/issues/10971
> [tests-only][full-ci] added test to delete ocm shares

- changelog/unreleased/bump-libregraph-api.md
- go.mod
- go.sum
- services/graph/pkg/identity/ldap_education_class.go
- services/graph/pkg/identity/ldap_education_class_test.go
- services/graph/pkg/service/v0/educationclasses_test.go
- vendor/github.com/owncloud/libre-graph-api-go/model_education_class.go
- vendor/modules.txt
> [full-ci] Bump Libregraph-API

- changelog/unreleased/add-logging-user-delete.md
- services/graph/pkg/service/v0/users.go
Logging when deleting personal space was insufficient. See https://github.com/owncloud/ocis/issues/10603#issuecomment-2659062903
> Log errors when deleting personal spaces

- .drone.star
- docs/ocis/development/testing.md
- tests/acceptance/TestHelpers/CliHelper.php
- tests/acceptance/TestHelpers/EmailHelper.php
- tests/acceptance/TestHelpers/OcisConfigHelper.php
- tests/acceptance/TestHelpers/SettingsHelper.php
- tests/acceptance/bootstrap/EmailContext.php
- tests/acceptance/bootstrap/FeatureContext.php
- tests/acceptance/bootstrap/NotificationContext.php
- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiOcm/createInvitation.feature
- tests/acceptance/run.sh
This PR replaces Inbucket with Mailpit because Inbucket lacks many features. As a result, we had to make multiple API requests and implement additional logic in the test framework to retrieve emails.
- drone 
- run.sh
- deployed ocis testing docs
- tests framework
- removed unnecessary import 
- While making this replacement, we encountered a limitation in our current approach:
- Steps that check emails, such as
`And user "Brian" should have received the following email from user "Alice" about the share of project space "new-space",
only fetch the last received email and perform assertions on it.`
- This logic fails when we need to assert against all emails received by the user, as we currently retrieve only the latest email.
In this PR, we have only changed the email testing service and …
> [tests-only][full-ci] Replace inbucket with mailpit

- docs/ocis/development/testing.md
This PR updates the `NOTIFICATIONS_SMTP_PORT`  for mailpit email service in `testing.md`.
-
> [docs-only] update `NOTIFICATIONS_SMTP_PORT` for mailpit email service in `testing.md`

- tests/acceptance/TestHelpers/GraphHelper.php
- tests/acceptance/TestHelpers/HttpRequestHelper.php
- tests/acceptance/bootstrap/FeatureContext.php
- tests/acceptance/bootstrap/GraphContext.php
- tests/acceptance/bootstrap/Provisioning.php
- tests/acceptance/bootstrap/SettingsContext.php
- tests/acceptance/bootstrap/SharingNgContext.php
- tests/acceptance/bootstrap/SpacesContext.php
- tests/acceptance/features/apiArchiver/downloadByPath.feature
- tests/acceptance/features/apiGraph/userGDPRExport.feature
- tests/acceptance/features/apiGraphUserGroup/editUser.feature
- tests/acceptance/features/apiLocks/lockFiles.feature
- tests/acceptance/features/apiLocks/unlockFiles.feature
- tests/acceptance/features/apiSpaces/changeSpaces.feature
- tests/acceptance/features/apiSpaces/quota.feature
- tests/acceptance/features/apiSpaces/tag.feature
- tests/acceptance/features/apiSpacesShares/shareOperations.feature
- tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
- tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
- tests/acceptance/features/coreApiWebdavProperties/getQuota.feature
> [tests-only][full-ci] port quota update fix

- .drone.star
Adjust `.drone.star` file to stable-7.1 branch
> Adjust stable-7.1 drone config

- .drone.star
Adjusts the pipelines to run in the nightly
> Fix `.drone.star` for 7.0 release

- .drone.star
Adjusts the pipelines to run in the nightly
> Fix `.drone.star` for 7.1 release

- tests/acceptance/bootstrap/SpacesContext.php
- tests/acceptance/features/apiOcm/share.feature
This PR adds test to create a folder inside federated share(folder).
``` feature
Scenario: federation user creates folder inside shared folder
```
- Part of: https://github.com/owncloud/ocis/issues/10971
- Bug report: https://github.com/owncloud/ocis/issues/10582
- Locally
- CI
> [tests-only][full-ci] add test to create folder inside federated share

- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiGraphUserGroup/deleteUser.feature
This PR updates existing delete user test scenario to delete user containing `+` character in the username.
``` feature
Scenario Outline: admin user deletes a user
```
- Bug Report: https://github.com/owncloud/ocis/issues/11027
- Related to: https://github.com/owncloud/ocis/issues/11032
- Locally
- CI
> [tests-only][full-ci] Add test to delete user containing `+` character in the username

- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiOcm/share.feature
This PR adds test for federated user listing the shares shared with him for resources that are shared with permissions role editor. Current behavior doesn't list roles property in the json response.
- https://github.com/owncloud/ocis/issues/10971
- Bug Report: https://github.com/owncloud/ocis/issues/11054
> [tests-only][full-ci] added test for federated user to list share shared with Editor role

- deployments/examples/ocis_ocm/collabora-ocm.yml
- deployments/examples/ocis_ocm/docker-compose.yml
- deployments/examples/ocis_ocm/onlyoffice.yml
- deployments/examples/ocis_ocm/web_extensions/drawio.yml
- deployments/examples/ocis_ocm/web_extensions/externalsites.yml
- deployments/examples/ocis_ocm/web_extensions/jsonviewer.yml
- deployments/examples/ocis_ocm/web_extensions/progressbars.yml
- deployments/examples/ocis_ocm/web_extensions/unzip.yml
Refernces: #11095 ([docs-only] Add a deployment example for OCM)
This PR updates all images of `ocis_ocm` to be aligned with the `ocis_full` example.
(I will take care as part of my tasks to keep images in sync :smiley: )
> [docs-only] Update ocis_ocm example images

- changelog/unreleased/fix-parent-id-for-shares.md
- go.mod
- go.sum
- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- vendor/github.com/owncloud/reva/v2/internal/grpc/services/sharesstorageprovider/sharesstorageprovider.go
- vendor/modules.txt
Fix the parent-id for the share-jail root.
- Fixes [#10917](https://github.com/owncloud/ocis/issues/10917)
- test case 1:
- test case 2:
- ...
> [full-ci] Fix the parent-id for the share-jail root

- changelog/unreleased/adjust-capabilities.md
- services/frontend/pkg/revaconfig/config.go
Adjust the capabilities according to full text search configurations.
- Fixes [#11059](https://github.com/owncloud/ocis/issues/11059)
- test case 1:
- test case 2:
- ...
> Adjust the capabilities according to full text search configurations

- changelog/unreleased/update-graph-logs.md
- services/graph/pkg/service/v0/api_driveitem_permissions.go
- services/graph/pkg/service/v0/api_driveitem_permissions_links.go
- services/graph/pkg/service/v0/api_driveitem_permissions_links_test.go
- services/graph/pkg/service/v0/api_driveitem_permissions_test.go
- services/graph/pkg/service/v0/base.go
- services/graph/pkg/service/v0/service.go
graph service needs to log all errors with as much information as it has.
- Fixes #10989 
- test case 1:
- test case 2:
- ...
> feat: graph, improve errors logging with verbose info

- tests/acceptance/features/apiOptionalShareRole/editorWithVersions.feature
This PR adds test to list the file/folder shares shared with `FileEditorWithVersions` and `EditorWithVersions` roles.
```feature
Scenario: sharee lists the file share shared with FileEditorWithVersions permission role (Personal Space)
Scenario: sharee lists the file share shared with FileEditorWithVersions permission role (Project Space)
Scenario: sharee lists the folder share shared with EditorWithVersions permission role (Personal Space)
Scenario: sharee lists the folder share shared with EditorWithVersions permission role (Project Space)
```
- Part of: https://github.com/owncloud/ocis/issues/11055
- CI
- Locally
> [tests-only][full-ci] add test to list resources shared with editorWithVersions roles 

- changelog/unreleased/fix-space-membership-expired-duplicate.md
- go.mod
- go.sum
- vendor/github.com/owncloud/reva/v2/pkg/storage/utils/decomposedfs/spaces.go
- vendor/modules.txt
We fixed the SpaceMembershipExpired event duplication issue.
- Fixes [#10966](https://github.com/owncloud/ocis/issues/10966)
- test case 1:
- test case 2:
- ...
> [bump reva]Fix the SpaceMembershipExpired duplicate event

- tests/acceptance/features/apiOptionalShareRole/editorWithVersions.feature
This PR adds test to check versions after updating the permissions role to and from EditorWithVersions role in Project Space.
``` feature
Scenario Outline: sharee checks versions after updating the permission role of a shared file from other roles to FileEditorWithVersions (Project Space)
Scenario Outline: sharee tries to check versions after updating the permission role of a shared file from FileEditorWithVersions to other roles (Project Space)
Scenario Outline: sharee checks versions after updating the permission role of the shared folder from other roles to EditorWithVersions (Project Space)
Scenario Outline: sharee tries to check versions after updating the permission role of the shared folder from EditorWithVersions to other roles (Project Space)
```
- Part of: …
> [tests-only][full-ci] add test to check versions after changing roles to and from EditorWithVersions role in Project Space

- changelog/unreleased/fix-migrate-cli.md
- ocis/pkg/command/migrate.go
- Fixes [https://github.com/owncloud/ocis/issues/11145](https://github.com/owncloud/ocis/issues/11145)
- test case 1: 
- Create and share the folder `fl` 
- run cli command
Output:
```
Scanning storage 21608bf4-4dd0-425e-9eec-1e4315fd2fce (1/1)
Rebuilding space '34894192-ec29-46e5-97eb-6fafc9ac1699' 1/1...2025-03-18T21:12:34+01:00 INF Adding share to space New share=21608bf4-4dd0-425e-9eec-1e4315fd2fce:34894192-ec29-46e5-97eb-6fafc9ac1699:5bc2aae2-0e7f-4447-b5b9-3b7f7ab406a6 hostname= line=/Users/roman/projects/owncloud/reva/pkg/share/manager/jsoncs3/providercache/providercache.go:186 service=migrate shareID=21608bf4-4dd0-425e-9eec-1e4315fd2fce:34894192-ec29-46e5-97eb-6fafc9ac1699:5bc2aae2-0e7f-4447-b5b9-3b7f7ab406a6 …
```
> Fix migrate rebuild-jsoncs3-indexes cli

- tests/acceptance/TestHelpers/SettingsHelper.php
This PR try to solve flakiness in step `When user "Brian" lists all notifications `.
After debugging, highly doubt the root cause of the failure is long **values-list** response.
This PR replaces  use of api endpoint **values-list**  with the endpoint **values-get-by-unique-identifiers** so that we get **value-list** of language only.
- Fixes https://github.com/owncloud/ocis/issues/11073
- locally
> [tests-only][full-ci]Use `values-get-by-unique-identifiers` endpoint to get language value list

- tests/acceptance/bootstrap/OcmContext.php
- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiOcm/deleteFederatedConnections.feature
As mentioned in the comment: https://github.com/owncloud/ocis/issues/10223#issuecomment-2662435987, This PR adds tests scenario:
```gherkin
Scenario Outline: federated user tries to delete previously deleted federated connection and provider
```
Part of:  https://github.com/owncloud/ocis/issues/10971
Bug report: https://github.com/owncloud/ocis/issues/10223
- Locally
- CI
> [tests-only][full-ci] Test coverage for local&federated user trying to delete deleted federation connection with random idp

- .drone.star
> [tests-only][k6-test] ci: run k6 for master branch unless specified in PR title

- tests/acceptance/bootstrap/SettingsContext.php
- tests/acceptance/features/apiSettings/notificationSetting.feature
This PR add tests code to check if notification comes or not when share expiry notification is disabled for Personal and Project drive resource
- https://github.com/owncloud/ocis/issues/10802
- locally
> [tests-only][full-ci] Add share expiry related tests when notification is disabled

- ocis-pkg/version/version.go
- sonar-project.properties
> [full-ci][k6-test] release-7.1.2

- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiAuthApp/token.feature
- tests/acceptance/features/apiAuthApp/tokenUsingUserId.feature
This PR separates the auth-app token scenarios into two feature files, one using user-id and another without user-id.
And also refactors some of the scenario title to be more clearer.
- Originated from: https://github.com/owncloud/ocis/pull/11169#discussion_r2018196350
- Locally
- CI
> [tests-only][full-ci] separate and refactor auth-app token related scenarios

- tests/acceptance/bootstrap/OcmContext.php
This PR fixes an issue which happens locally on my MacBook Pro,
> @BeforeScenario # FeatureContext::before()
│
╳  8192: Creation of dynamic property OcmContext::$sharingNgContext is deprecated in /Users/deyan.zhekov/Projects/ownCloud/ocis/tests/acceptance/bootstrap/OcmContext.php line 62
- No related issues
Running locally any API acceptance test always fails
- Tested only locally
> [tests-only][full-ci] Fix failing tests on @BeforeScenario step

- tests/acceptance/features/apiAuthApp/tokenUsingUserId.feature
This PR adds test scenarios to create auth-app token with user-id and without expiry by admin user, non-existent user and non-admin user.
```feature
Scenario: admin tries to create auth-app token for another user with user-id and without expiry
Scenario: non-existent user tries to create auth-app token for another user using user-id and without expiry
Scenario: non-admin user tries to create auth-app token for another user using user-id and without expiry
```
- Part of: https://github.com/owncloud/ocis/issues/10619
- Locally
- CI
> [tests-only][full-ci] add test to create auth-app token using user-id without expiration

- tests/acceptance/bootstrap/AuthAppContext.php
- tests/acceptance/features/apiAuthApp/tokenUsingUserId.feature
This PR adds test to create auth-app token with user-id by non-existent user.
``` feature
Scenario: non-existent user tries to create auth-app token for another user using user-id
```
- Part of: https://github.com/owncloud/ocis/issues/10619
- Locally
- CI
> [tests-only][full-ci] add test to create auth-app token with user-id by non-existent user

- tests/acceptance/bootstrap/SharingNgContext.php
- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiSharingNgShares/sharedByMe.feature
- Added test coverage for sharer listing the link share of a project space using permissions endpoint
- Updated the existing test coverage for sharer listing the link share of a project space using root endpoint
- Bug report: https://github.com/owncloud/ocis/issues/8355
> [tests-only][full-ci] add test coverage for sharer listing link share of project space

- tests/acceptance/features/apiSharingNgAdditionalShareRole/listGrantsShareRole.feature
This PR adds tests for list grant role related to share with me and share by me feature
**Note** Only limited test cases has been added for additional role 
- https://github.com/owncloud/ocis/issues/10951
- locally
> [tests-only][full-ci]Add tests for list grant role related to `share by me` and `share with me`

- .drone.star
- tests/acceptance/TestHelpers/HttpRequestHelper.php
- tests/acceptance/bootstrap/FeatureContext.php
Removed the env `SEND_SCENARIO_LINE_REFERENCES` and made it work by default.
- Related to: https://github.com/owncloud/ocis/issues/11067
- Locally
- CI
> [tests-only][full-ci] Remove SEND_SCENARIO_LINE_REFERENCES env

- .drone.env
This PR only bumps the commit hash for the the `stable-11.0` branch used from `web` repository.
Updated only the `drone.env` file.
- https://github.com/owncloud/web/issues/12436
- only locally
> [full-ci] Update `master` branch - new commit for the `stable-11.0` branch in `web` repo

- .drone.env
Using the latest commit hash of branch stable-11.0 from web repository
This PR only bumps the commit hash for the `master` branch used from the `web` repository.
Updated only the `drone.env` file.
- https://github.com/owncloud/web/issues/12436
Just needed to do it.
- locally
> [full-ci] Update `stable-7.1` branch - new commit for the `stable-11.0` branch in `web` repo

- .drone.star
- tests/config/drone/check_go_bin_cache.sh
- tests/config/drone/check_web_cache.sh
This PR use minio command to check cache for web and gobin
- Fixes https://github.com/owncloud/ocis/issues/11224
- CI
-
> [tests-only][full-ci]Use minio client to check if cache exists

- tests/acceptance/bootstrap/AuthContext.php
- tests/acceptance/features/apiAuthApp/tokenUsage.feature
This PR adds test to access resource of another user by both admin and non-admin user using normal auth-app and impersonation token.
Using auth-app token scenarios:
```feature
Scenario: admin tries to access resource of another user using auth-app token
Scenario: non-admin user tries to access resource of another user using auth-app token
```
Using impersonation token scenarios:
```feature
Scenario: admin tries to access resource of another user using impersonation token
Scenario: non-admin user tries to access resource of another user using impersonation token
```
- Part of: https://github.com/owncloud/ocis/issues/10619
- Locally
- CI
> [tests-only][full-ci] add test to access resource of another user using impersonation token.

- changelog/unreleased/update-cli-delete-stale-uploads.md
- services/storage-users/pkg/command/uploads.go
> An oCIS command that iterates over [a single space | all spaces] and all files within it / them.
Checks every node for the nodestatus and deletes it if it's in processing status and no connected uploadinfo can be found for it.
Example:
```
./ocis storage-users uploads delete-stale-nodes --spaceid=9d408cec-8f0a-4d33-8715-89df1217a10c --dry-run=true --verbose=true
Spaces to cleanup: 1
- 9d408cec-8f0a-4d33-8715-89df1217a10c
Deleting stale processing nodes for space: 9d408cec-8f0a-4d33-8715-89df1217a10c
Found total 2 .mpk files
Found stale upload at /Users/mk/.ocis/storage/users/spaces/9d/408cec-8f0a-4d33-8715-89df1217a10c/nodes/ab/12/cd/34/-ef567890ab12cd34ef567890.mpk (Processing ID: 5329c14b-b786-4b27-8f7d-7429f03009d7)
Upload info missing at: …
```
> feat: cli, remove stale uploads

- changelog/unreleased/add-tags-validation.md
- go.mod
- go.sum
- services/frontend/pkg/config/config.go
- services/frontend/pkg/config/defaults/defaultconfig.go
- services/frontend/pkg/revaconfig/config.go
- services/graph/pkg/config/config.go
- services/graph/pkg/config/defaults/defaultconfig.go
- services/graph/pkg/service/v0/tags.go
- vendor/github.com/owncloud/reva/v2/pkg/owncloud/ocs/capabilities.go
- vendor/github.com/owncloud/reva/v2/pkg/tags/tags.go
- vendor/modules.txt
We limited the length of tags to avoid DOS attacks against the ocis server.
- Fixes [https://github.com/owncloud/enterprise/issues/7180](https://github.com/owncloud/enterprise/issues/7180)
- test case 1:
- test case 2:
- ...
> [full-ci] limited the length of tags

- tests/acceptance/features/apiSharingNgDriveInvitation/driveShareInvitations.feature
This PR adds the test for user trying to share space with `Secure Viewer` role. The bug report https://github.com/owncloud/ocis/issues/9303 mentions the issue regarding share receiver trying to download the space shared with `Secure Viewer` role. But with latest ocis, spaces cannot be shared with role `Secure Viewer`.
- Bug Report: https://github.com/owncloud/ocis/issues/9303
> [tests-only][full-ci] added test to share space with Secure Viewer role

- docs/ocis/development/testing.md
- tests/ociswrapper/README.md
Small updates on `testing.md` and `ociswrapper/README.md` documents.
- Part of: https://github.com/owncloud/ocis/issues/10948
:robot:
> [docs-only] update ociswrapper document

- changelog/unreleased/allow-setting-ids.md
- services/graph/pkg/service/v0/drives.go
Fixes https://github.com/owncloud/ocis/issues/11235
> Allow setting spaceIDs through graph API

- services/idp/license-checker-clarifications.json
- services/idp/package.json
- services/idp/pnpm-lock.yaml
Fix vulnerable dependency by updating package. 
- Fixes https://github.com/owncloud/ocis/security/dependabot/567
- test case 1:
- test case 2:
- ...
> [full-ci] bump: i18next-conv

- tests/ociswrapper/ocis/ocis.go
Bring back necessary log removed in https://github.com/owncloud/ocis/pull/11279
> [docs-only] test(wrapper): bring back log

- changelog/unreleased/claim-managed-spaces.md
- ocis-pkg/claimsmapper/claimsmapper.go
- ocis-pkg/claimsmapper/claimsmapper_test.go
- services/proxy/pkg/command/server.go
- services/proxy/pkg/config/config.go
- services/proxy/pkg/middleware/options.go
- services/proxy/pkg/middleware/space_manager.go
Allow managing space memberships from oidc claims
Requires https://github.com/owncloud/reva/pull/269
Fixes https://github.com/owncloud/ocis/issues/11196
> Claim Managed Spaces

- .drone.star
Do not use cache server and bucket name from secrets
Part of https://github.com/owncloud/QA/issues/883
> [full-ci][test-only] ci: add cache server and bucket varaibles

- services/proxy/pkg/config/config.go
Refernces: #11280 (Claim Managed Spaces)
Some small fixes in the envvar text for `OCIS_CLAIM_xxx`.
> [docs-only] Update OCIS_CLAIM_xxx envvar texts

- docs/helpers/env_vars.yaml
- docs/helpers/extended_vars.yaml
After a while, the needed update of the both files required by docs.
Note the mixup of lineitems is done by the process, but nothing has changed in reality - dont worry...
> [chore][docs-only] Update env_vars.yaml and extended_vars.yaml

- changelog/unreleased/fix-collaboration-lastmodifieddate.md
- services/collaboration/pkg/connector/fileconnector.go
- services/collaboration/pkg/connector/fileconnector_test.go
Fix regression in collaboration service, missing LastModifiedDate
- Fixes issue OCISDEV-10
- collaboration unit tests
> fix: LastModifiedDate in collaboration service

- changelog/unreleased/add-server-managed-spaces-capability.md
- services/frontend/README.md
- services/frontend/pkg/config/config.go
- services/frontend/pkg/revaconfig/config.go
- services/proxy/README.md
- services/proxy/pkg/config/config.go
Adds a capability to indicate the webUI to block adding/removing spaces to users
> Add server managed spaces capability

- changelog/unreleased/fix-share-role-translation.md
- services/graph/pkg/unifiedrole/conversion_test.go
- services/graph/pkg/unifiedrole/filter.go
- services/graph/pkg/unifiedrole/filter_test.go
- services/graph/pkg/unifiedrole/roles.go
- services/graph/pkg/unifiedrole/roles_test.go
Backport a fix https://github.com/owncloud/ocis/pull/11241
> [full-ci] backport issue-11025 to stable-7.1

- changelog/unreleased/fix-collaboration-lastmodifieddate.md
- services/collaboration/pkg/connector/fileconnector.go
- services/collaboration/pkg/connector/fileconnector_test.go
Backports to 7.1 https://github.com/owncloud/ocis/pull/11328
- Backports to 7.1 https://github.com/owncloud/ocis/pull/11328
- test case 1:
- test case 2:
- ...
> fix: collaboration, missing LastModifiedTime, 7.1

- services/settings/Makefile
cats the settings.pot file to see if it is formatted correctly
> [docs-only] Try to Find the Translation issue

- .drone.env
- changelog/unreleased/enhancement.md
- services/web/Makefile
- test case 1:
- test case 2:
- ...
> [full-ci] chore: bump web to 11.3.3

- tests/config/drone/notification.sh
This PR fixed the error from  [PR](https://github.com/owncloud/ocis/pull/11323)
- The CI step chat-notification failed due to a bash script error:
```console
/drone/src/tests/config/drone/notification.sh: line 27: [: !=: unary operator expected
```
- CI
> [full-ci] Fixed the matrix notification script file

- changelog/unreleased/fix-settings-translations.md
- services/settings/pkg/service/v0/service.go
master-port of https://github.com/owncloud/ocis/pull/11361
> Fix Notifications Settings Translation

- .drone.star
- tests/config/drone/notification.sh
This PR backport the master PR https://github.com/owncloud/ocis/pull/11323 and https://github.com/owncloud/ocis/pull/11360
> [full-ci] Backport: Add matrix notification

- changelog/unreleased/change-clientlog-reva-gateway-.md
- docs/helpers/env_vars.yaml
- services/clientlog/pkg/config/config.go
fixes #11314
- Fixes #11314
- test case 1:
- test case 2:
- ...
> fix: remove deprecated CLIENTLOG_REVA_GATEWAY

- tests/config/drone/notification.sh
This PR improves the clarity of build notification message sent to Element (Matrix) chat by dynamically identifying and labeling the source of the build based on the Drone CI event type [(branch, tag, or cron)](https://docs.drone.io/pipeline/environment/reference/drone-build-event/).
| Event | Message |
|--------|--------|
| cron(Nightly) | ![image](https://github.com/user-attachments/assets/25ebc942-f068-47d0-8be3-d191d4cc140d) |
| tag | ![image](https://github.com/user-attachments/assets/9f7cee38-32ac-42f3-8e22-f2f4232fce8f) |
| branch | ![image](https://github.com/user-attachments/assets/bf9990ae-2c92-4ab5-92a9-2d6a01759208) |
- locally
> [full-ci] Show build source (branch, tag, or cron) in Matrix notification

- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiActivities/activities.feature
- tests/acceptance/features/apiActivities/activitiesByFileId.feature
This PR adds the test for checking the activities of destination resources after copying a 0 byte file (using and not using file-id):
```gherkin
Scenario: check activities of destination resources after copying a 0 byte file
```
- Bug: https://github.com/owncloud/ocis/issues/10417
Locally and CI
> [tests-only][full-ci] Check activities after copying 0 byte file

- tests/acceptance/TestHelpers/GraphHelper.php
- tests/acceptance/TestHelpers/HttpRequestHelper.php
- tests/acceptance/bootstrap/FeatureContext.php
- tests/acceptance/bootstrap/GraphContext.php
- tests/acceptance/bootstrap/Provisioning.php
- tests/acceptance/bootstrap/SettingsContext.php
- tests/acceptance/bootstrap/SharingNgContext.php
- tests/acceptance/bootstrap/SpacesContext.php
- tests/acceptance/features/apiArchiver/downloadByPath.feature
- tests/acceptance/features/apiGraph/userGDPRExport.feature
- tests/acceptance/features/apiGraphUserGroup/editUser.feature
- tests/acceptance/features/apiLocks/lockFiles.feature
- tests/acceptance/features/apiLocks/unlockFiles.feature
- tests/acceptance/features/apiSpaces/changeSpaces.feature
- tests/acceptance/features/apiSpaces/quota.feature
- tests/acceptance/features/apiSpaces/tag.feature
- tests/acceptance/features/apiSpacesShares/shareOperations.feature
- tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
- tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
- tests/acceptance/features/coreApiWebdavProperties/getQuota.feature
> [full-ci][tests-only] port quota fixes

- tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
- tests/acceptance/features/coreApiShareOperationsToShares1/accessToShare.feature
Port https://github.com/owncloud/ocis/pull/11356
> [tests-only][full-ci] check share sync status before actions

- services/proxy/pkg/middleware/selector_cookie.go
Fix Issue OCISDEV-14
- Fixes OCISDEV-14
- test case 1:
- test case 2:
- ...
> fix: middleware, cookie missing secure flag

- changelog/unreleased/office-deployment-improvements.md
- deployments/examples/ocis_full/.env
- deployments/examples/ocis_full/collabora.yml
- deployments/examples/ocis_full/config/onlyoffice/local.json
- deployments/examples/ocis_full/onlyoffice.yml
Harden office installation:
* The wopi server isn't expected to be exposed with Collabora or OnlyOffice (it might be needed for Microsoft, but it isn't covered here)
* Connectivity between Collabora / OnlyOffice and the wopi server will be done through the docker network.
* OnlyOffice will use IP filters:
* It's expected that you can only open documents from the collaboration-oo host (the wopi server for OnlyOffice).
* The editor is expected to be used without any change
* The wopi server for OnlyOffice will use proof keys.
In general, you shouldn't need to change anything. If the installation worked before these changes, it should also work with this PR without touching anything else.
For new installations, you can still go through the regular installation steps. The only change is that …
> feat: office deployment hardening

- services/idp/package.json
- Fixes  OCISDEV-98
- test case 1:
- test case 2:
- ...
> chore: bump idp

- tests/acceptance/bootstrap/FeatureContext.php
- tests/acceptance/bootstrap/WebDav.php
- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/cliCommands/trashBin.feature
- tests/acceptance/features/cliCommands/uploadSessions.feature
Scenario changes:
- make sure that the uploads are stuck in postprocessing
- restart the upload sessions and check the successful upload
- test environment: :raised_back_of_hand:
> [tests-only] Fix post processing test scenarios

- tests/acceptance/TestHelpers/UploadHelper.php
- tests/acceptance/bootstrap/FeatureContext.php
- tests/acceptance/bootstrap/SpacesTUSContext.php
- tests/acceptance/bootstrap/WebDav.php
- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/cliCommands/uploadSessions.feature
Expire the uploads without delaying post-processing.
> [tests-only] fix upload expired cli test scenario

- services/collaboration/.mockery.yaml
- services/graph/.mockery.yaml
- services/graph/pkg/service/v0/api_driveitem_permissions_test.go
- services/storage-users/pkg/command/trash_bin.go
- test case 1:
- test case 2:
- ...
> chore: cleanup make generate, go vet is now clean

- .drone.star
- scripts/delete-stale-branches.sh
- test case 1:
- test case 2:
- ...
> feat: delete-stale-branches, enable

- scripts/delete-stale-branches.sh
- test case 1:
- test case 2:
- ...
> fix: ci, git error 128

- .drone.star
- test case 1:
- test case 2:
- ...
> fix: ci, delete stale-branches, use github token

- .drone.star
- scripts/delete-stale-branches.sh
> Revert "feat: delete-stale-branches, enable"

- .drone.star
This PR fixes an issue with the changelog summary for `Addams - 7.2.0`
Updating the `drone.star` file should fix the missing line in `CHANGELOG.md`
- Fixes https://github.com/owncloud/ocis/issues/11464
To have a proper Changelog summary we'll need to fix this issue before releasing `Addams - 7.2.0`
> [full-ci] Fix changelog issue in drone.star

- deployments/examples/ocis_full/collabora.yml
- deployments/examples/ocis_full/onlyoffice.yml
Fixed the container start command.
Container crashlooping with error `"No help topic for 'ocis'"`
- test case 1:
- test case 2:
- ...
> Fix collabora and onlyoffice in example full deployment.

- changelog/unreleased/fix-return-translated-role-definitions.md
- services/graph/pkg/service/v0/api_driveitem_permissions.go
- services/graph/pkg/service/v0/api_driveitem_permissions_test.go
- services/graph/pkg/service/v0/rolemanagement.go
- services/graph/pkg/service/v0/service.go
Backports fix for unified role translations
> [full-ci] chore: backport fix return translated role definitions

- changelog/unreleased/fix-cli-upload.md
- services/storage-users/pkg/command/uploads.go
backport: [OCISDEV-141] [CLI] Error while resuming an upload
> backport: [OCISDEV-141] [CLI] Error while resuming an upload

- services/ocdav/ocdav-openapi.yaml
Adds an openapi spec for the ocdav service.
> [docs-only] Add OpenAPI ocdav spec

- services/ocm/ocm-openapi.yaml
Add an openapi spec for the ocm api
https://kiteworks.atlassian.net/browse/OCISDEV-152
> [docs-only] Add OCM Api spec

- tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
- tests/acceptance/features/apiActivities/activities.feature
This PR adds test against checking activities while setting limit `-1` and `0` of a folder
- Bug report: https://github.com/owncloud/ocis/issues/9880
- Locally
- CI
> [tests-only] [full-ci] Add test for checking activities with limit filters applied

- go.mod
(CVE-2025-22874, 22871, 4673, 0913)
- test case 1:
- test case 2:
- ...
> fix: [OCISDEV-169] patch CVEs

- tests/acceptance/features/apiSharingNgShareInvitation/updateShareInvitations.feature
Backport of PR: https://github.com/owncloud/ocis/pull/11534
> [tests-only][full-ci] update expiration date time in test scenraios

- changelog/unreleased/fix-shared-by-me.md
- services/graph/pkg/service/v0/driveitems.go
- tests/acceptance/features/apiSharingNg1/sharedByMe.feature
fix: [OCISDEV-198] Fix space root handling in a graph sharedByMe
- Fixes https://github.com/owncloud/ocis/issues/8355 
- OCISDEV-198
- test case 1:
- test case 2:
- ...
>  fix: [OCISDEV-198] Fix space root handling in a graph sharedByMe

- .drone.star
This PR backported the master PR https://github.com/owncloud/ocis/pull/11547
> [tests-only][full-ci] Backport 7.1/disable clone on notification

- services/antivirus/pkg/server/debug/server.go
- services/graph/pkg/server/debug/server.go
- services/idp/pkg/server/debug/server.go
- services/search/pkg/server/debug/server.go
fixed the search readyz endpoint
- Fixes [#11552](https://github.com/owncloud/ocis/issues/11552)
- test case 1:
- test case 2:
- ...
> fix: [OCISDEV-219] fixed the search readyz endpoint

- .github/remove_stale_branches.yml
- test case 1:
- test case 2:
- ...
> ci: remove stale branches github action

- services/web/pkg/assets/server.go
- services/web/pkg/assets/server_test.go
- test case 1:
- test case 2:
- ...
> fix: [OCISDEV-175] server path validation

- changelog/unreleased/http_strict_transport_security.md
- services/proxy/pkg/middleware/security.go
- services/proxy/pkg/middleware/security_test.go
- test case 1:
- test case 2:
- ...
> fix: [OCISDEV-54] support for the Strict Transport Security mechanism

- docs/helpers/extendedEnv.go
`extendEnv.go` spend a lot of time on grep command for large codebases. Command in this PR has the same result, use whole CPU and is even x10 faster - faster result locally and hopefully on CI. 
- test case 1:
- test case 2:
- ...
> fix: [OCISDEV-235] make docs-generate, extendedVars.go

- changelog/unreleased/unified-roles-markdown-output.md
- services/graph/README.md
- services/graph/pkg/command/unified_roles.go
feat: [OCISDEV-202] Render the UnifiedRoles table output as Markdown format
- test case 1:
- test case 2:
- ...
> feat: [OCISDEV-202] Render the UnifiedRoles table output as Markdown format

- deployments/examples/ocis_keycloak/config/keycloak/ocis-realm.dist.json
Configuration changes for keycloak in order to provide a login flow with step up mechanism as described in https://www.keycloak.org/docs/latest/server_admin/index.html#_step-up-flow.
Note that the changes shouldn't affect the current setup, and the "new" authentication flow isn't active by default.
In order to activate it:
1. Go to keycloak admin console -> oCIS realm -> authentication -> flows.
2. Click on the "step up flow" (which should be marked as "not in use")
3. In the "actions" menu (top right), choose "bind flow", and then choose "browser flow".
At the moment, the server won't do anything with the new information, and the clients don't support the feature (not tested, but they might have problems). You can use https://playground.please-open.it/ to play around
Preparations for …
> feat: add step up auth flow in keycloak example

- tests/acceptance/bootstrap/CliContext.php
- tests/acceptance/features/cliCommands/authAppToken.feature
- tests/acceptance/features/cliCommands/backupConsistency.feature
- tests/acceptance/features/cliCommands/emailNotification.feature
- tests/acceptance/features/cliCommands/searchReIndex.feature
- tests/acceptance/features/cliCommands/staleUpload.feature
- tests/acceptance/features/cliCommands/trashBin.feature
- tests/acceptance/features/cliCommands/uploadSessions.feature
This PR adds a test for resume upload sessions of a single file using cli
command:
```
./ocis/bin/ocis storage-users uploads sessions --id=<upload-id> --resume --json
```
- part of https://github.com/owncloud/ocis/issues/11274
- test case 1:
- test case 2:
- ...
> [tests-only][full-ci] add tests for resume upload sessions of a single file using cli

- tests/acceptance/run.sh
This PR is backport PR of master https://github.com/owncloud/ocis/pull/11647  https://github.com/owncloud/ocis/pull/11654
- test case 1:
- test case 2:
- ...
> [tests-only][full-ci] Backport 7.1/ fix the correct regex on test script

- services/proxy/README.md
- services/proxy/pkg/userroles/oidcroles.go
- services/proxy/pkg/userroles/oidcroles_test.go
Allow wildcards in role assignments
- test case 1:
- test case 2:
- ...
](feat: [OCISDEV-226] Allow wildcards in role assignments)
> feat: [OCISDEV-226] Allow wildcards in role assignments

- .bingo/Variables.mk
- .bingo/variables.env
- protogen/gen/ocis/messages/settings/v0/settings.pb.go
When running `make generate` these files got changed:
* Variables.mk
remove empty lines 
* variables.env
remove empty lines 
* settings.pb.go
only a few things, but I dont understand them :sweat_smile:
Can one pls have a look on to see if these changes are valid and can be merged or need more changes to get ready
> Updates resulting on running make generate

- docs/helpers/env_vars.yaml
This PR only updates the `env_vars.yaml` file to have the latest state also in Balch.
Note that by design of the code that generates it, things are just scrambled a bit around (as usual)
> [docs-only] Update the env_vars.yaml file
