owncloud/ocis

services/graph/pkg/service/v0/driveitems.go, services/graph/pkg/service/v0/driveitems_test.go, services/graph/pkg/validate/libregraph.go, services/graph/pkg/validate/libregraph_test.go
as described in #7962 multi invites could get problematic, specially the error handling.
Therefore we've decided to restrict invitations to a maximum of one!
It contains validation (allow only user and group types, id), error handling and tests for that.
* already shared to the user // group -> 409
* wrong or empty libre.graph.recipient.type (group && user allowed) -> 400
* unknown user -> 400
* unknown group -> 400
* ~~disabled user  -> TODO~~ not part of this pr, will be handled globally via reva 
- Fixes https://github.com/owncloud/ocis/issues/7962
explicit error handling
- unit tests
- manual tests
=> fix: allow a maximum of one invite at a time

tests/acceptance/features/apiGraph/addUserToGroup.feature, tests/acceptance/features/apiGraph/createUser.feature, tests/acceptance/features/apiGraph/deleteUser.feature, tests/acceptance/features/apiGraph/editUser.feature, tests/acceptance/features/apiGraph/getUser.feature, tests/acceptance/features/apiGraph/removeUserFromGroup.feature, tests/acceptance/features/apiSharingNg/shareInvitations.feature, tests/acceptance/features/bootstrap/GraphContext.php
Scenarios Added:
- Scenario Outline: send share invitation to disabled user
- Locally
- :robot:
=> [full-ci] [tests-only] Added test for sending share invitation to disabled user

deployments/examples/ocis_wopi/docker-compose.yml
The example did not work for me, I believe the NATS settings need to be adjusted.
Wit this change, both collabora and onlyoffice work fine
- Fixes #8100
NATS seems not to work with mdns
- run collabora & onlyoffice on private ocis instance
- run the example locally
=> [docs-only] fix NATS configuration in wopi example

tests/acceptance/features/apiGraph/createUser.feature, tests/acceptance/features/apiGraph/editUser.feature, tests/acceptance/features/apiSharingNg/shareInvitations.feature, tests/acceptance/features/bootstrap/GraphContext.php
- Scenario Outline: send share invitation to deleted user
- Locally
- :robot:
=> [full-ci] [tests-only] Added test for sending share invitation to deleted user

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSharingNg/deletePermissions.feature, tests/acceptance/features/bootstrap/SharingNgContext.php
part of: https://github.com/owncloud/ocis/issues/8008
=> [tests-only]tests: add tests for removing share permission in link share

tests/TestHelpers/WebDavHelper.php, tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature, tests/acceptance/features/bootstrap/FilesVersionsContext.php, tests/acceptance/features/coreApiVersions/fileVersions.feature
Add API test coverage for https://github.com/owncloud/ocis/issues/777 and https://github.com/owncloud/ocis/issues/7738
- coverage for https://github.com/owncloud/ocis/issues/777 and https://github.com/owncloud/ocis/issues/7738
=> [tests-only] Added test coverage for checking file versions after MOVE

changelog/unreleased/fix-language-patching.md, services/graph/pkg/service/v0/users.go
Fixes patching of user language when ldap backend is `read-only`
Fixes https://github.com/owncloud/enterprise/issues/6235
=> Fix patching language settings

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSharingNg/shareInvitations.feature
Backport of PR: https://github.com/owncloud/ocis/pull/8168
=> [tests-only][full-ci] backport added test to send share invitation to user and gruop at once

services/search/pkg/search/search.go
That's an expected, totally valid case.
Fixes https://github.com/owncloud/ocis/issues/8180
=> Do not error-log when outdated resources can't be indexed anymore

changelog/unreleased/fix-upload-reset-logo.md, services/web/pkg/service/v0/branding.go
We fixed a bug when admin tried to update or reset the logo.
- Fixes [https://github.com/owncloud/ocis/issues/8101](https://github.com/owncloud/ocis/issues/8101)
- test environment and case in the attached issue
=> fix update and reset the logo

docs/helpers/configenvextractor.go
This PR changes the basepath for the docs helper from `~` (HOME) to `/etc`
refs #7972
=> change ocis basepath from home to

changelog/unreleased/cleanup-graph-driveitemsgo.md, services/graph/pkg/service/v0/driveitems.go
Main intend is to use proto getters to avoid panics.
Fixes https://github.com/owncloud/ocis/issues/7899
This also fixes some other issues that made my IDE sad and angry.
=> Cleanup `driveitems.go`

changelog/unreleased/cleanup-search-searchgo.md, services/search/pkg/search/search.go
Now uses proto getters to avoid panics
Fixes https://github.com/owncloud/ocis/issues/6850
=> Cleanup `search.go`

tests/acceptance/features/apiSharingNg/linkShare.feature
This PR adds following scenarios (creating link shares (public) to banned password):
```feature
Scenario Outline: create a file's link share with a password that is listed in the Banned-Password-List
Scenario Outline: update a file's link share with a password that is listed in the Banned-Password-List
```
=> [tests-only][full-ci]Added test for banned password to create public link

changelog/unreleased/fix-getdrives-response-code.md, services/graph/pkg/service/v0/drives.go
Return a 405 Status when UpdateSpace() or DeleteSpace() are not implemented in the backend for a certain type of drive (e.g. the virtual mountpoint drives created for shares).
Fixes: #7881
=> graph/drives: Fix status code for PATCH/DELETE on drives not allowing them

tests/acceptance/features/apiSpaces/tusUpload.feature, tests/acceptance/features/bootstrap/TUSContext.php, tests/acceptance/features/coreApiWebdavUploadTUS/uploadFile.feature
This PR extends the API test coverage for replacing file with zero-byte file via TUS upload
```feature
Scenario Outline: upload a zero-byte file in a shared folder
Scenario: upload a zero-byte file in a shared folder (spaces dav path)
Scenario: upload a zero-byte file in a project space
Scenario Outline: replace a shared file with zero-byte file
Scenario: replace a shared file with zero-byte file (spaces dav path)
Scenario: replace a file inside a project space with zero-byte file
Scenario: replace a file inside a shared project space with zero-byte file
Scenario Outline: upload a zero-byte file
Scenario Outline: replace a file with zero-byte file
Scenario Outline: replace a file inside a folder with zero-byte file
```
Closes https://github.com/owncloud/ocis/issues/8044 …
=> [tests-only][full-ci] Extend API test coverage for replacing file with zero-byte file via TUS upload

tests/acceptance/features/apiSharingNg/shareInvitations.feature, tests/acceptance/features/bootstrap/SharingNgContext.php
Added test scenario to send share invitation to unknown group.
Expected: sharing should fail with status code `400`
```feature
Scenario Outline: send sharing invitation to non-existing group
```
=> [tests-only][full-ci] added test to send share invitation to unknown group

tests/acceptance/features/apiSharingNg/reshare.feature, tests/acceptance/features/bootstrap/SharingNgContext.php
In this PR, added test to reshare a resource to other users.
```feature
Scenario Outline: reshare a file to user with different roles
Scenario Outline: reshare a folder to user with different roles
Scenario Outline: reshare a file inside project space to a user with different roles
Scenario Outline: reshare a folder inside project space to a user with different roles
```
=> [tests-only][full-ci] added test to reshare resources to other users SharingNg

tests/acceptance/features/coreApiVersions/fileVersions.feature
Added API test coverage for checking file versions after multiple restores.
**NOTE: file MUST be uploaded with empty content first**
Steps to reproduce bug (webUI):
1. create a new file with some content
2. check the version with 0 byte
3. restore the 0 byte version - OK
4. restore the <x> bytes versions - OK
5. content is empty - BAD
6. there is no versions - BAD
- test coverage for https://github.com/owncloud/enterprise/issues/6249
- waiting for https://github.com/cs3org/reva/pull/4456 in ocis
=> [tests-only] Added API test coverage for checking file versions after multiple restores

changelog/unreleased/fix-nats-registry.md, ocis-pkg/natsjsregistry/options.go, ocis-pkg/natsjsregistry/registry.go, ocis-pkg/registry/registry.go
Fixes a rather strange issue with the natsjskv registry.
Thanks @butonic @rhafer @dragonchaser @fschade for the help in debugging this!
=> Fix NatsRegistry

tests/TestHelpers/WebDavHelper.php, tests/acceptance/features/apiCors/cors.feature, tests/acceptance/features/bootstrap/SpacesContext.php
We had CORS tests only for OCS api but test is skipped because: https://github.com/owncloud/ocis/issues/5195
I added tests for graph api(lists all available spaces) and webDave(propfind request). I'm not sure that I need cover all endpoints. If I wrong please point it out to me in the review
=> [test-only] add more CORS tests

tests/acceptance/features/apiSharingNg/reshare.feature
Added test to reshare a resource to other users with higher role, for example, user receives a share with role `Viewer` and tries to reshare the resource with role `Editor`, which should not be possible. Likewise, a user receiving share with role `Uploader` should not have permission to reshare a resource.
Expected: resharing should not happen and should return status code `403`
```feature
Scenario: try to reshare a resource to higher roles
Scenario: user with role Uploader tries to reshare a folder
```
=> [tests-only][full-ci] Added test to reshare a resource to other users with higher roles

changelog/unreleased/fix-resource-name.md
After the sharer changed the name of a shared resource, the receiver can see the new name, but cannot access it by using the new name.
We fixed a problem where after renaming the resource as sharer the receiver saw a new name.
- Fixes [https://github.com/owncloud/ocis/issues/8242](https://github.com/owncloud/ocis/issues/8242)
- Related changes [https://github.com/cs3org/reva/pull/4463/files](https://github.com/cs3org/reva/pull/4463/files)
1. create a folder
2. share the folder
3. as sharer rename the folder
4. as receiver do a propfind on the share-jail `curl -XPROPFIND -uuu1:uu1 'https://localhost:9200/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668' -k | xmllint --format  -`
`d:href` element and `oc:name` should correlate …
=> fix the resource name

tests/acceptance/features/apiSharingNg/shareInvitations.feature, tests/acceptance/features/bootstrap/SharingNgContext.php
- Scenario Outline: send share invitation to wrong user id
- Locally
- :robot:
=> [full-ci] [tests-only] Added test for sending share invitation to wrong objectId

go.mod, go.sum, vendor/github.com/egirna/icap-client/client.go, vendor/github.com/egirna/icap-client/request.go, vendor/modules.txt
In certain cases, icap-client errors were concealed, which has now been fixed
- Fixes https://github.com/fschade/icap-client/pull/5#issue-2086377837
in my home-lab i found out that In certain cases errors are not displayed... this can lead to unnecessary leaks.
- local installation
=> chore: bump icap client which fixes defer error handling

services/graph/pkg/service/v0/driveitems.go
Just a tiny bugfix so I can set the size when starting upload sessions via graph. Helps with some joplin tests I have.
=> set size when starting an upload session via graph

tests/acceptance/features/apiSharingNg/shareInvitations.feature
- Scenario Outline: send share invitation to user with empty recipient type
- Scenario Outline: send share invitation to group with empty recipient type
- Locally
- :robot:
=> [full-ci] [tests-only] Add test to send share invitation with empty recipient type

services/storage-users/README.md, services/storage-users/pkg/command/uploads.go
This PR deprecates the `ocis storage-users uploads list` command:
```
NAME:
ocis storage-users uploads list - Print a list of all incomplete uploads (deprecated, use sessions)
USAGE:
ocis storage-users uploads list [command options] [arguments...]
OPTIONS:
--help, -h  show help
```
It also introduces the `ocis storage-users uploads sessions` command:
```
NAME:
ocis storage-users uploads sessions - Print a list of upload sessions
USAGE:
ocis storage-users uploads sessions [command options] [arguments...]
OPTIONS:
--id value      filter sessions by upload session id
--processing    filter sessions by processing status
--expired       filter sessions by expired status
--output value  output format to use (can be 'plain' or 'json',  experimental) (default: plain)
--help, -h      show help
``` …
=> add more upload session filters

services/graph/pkg/service/v0/driveitems.go
/graph/v1beta1/me/drive/sharedByMe parent reference missed name and path
- Needed by https://github.com/owncloud/web/pull/10392
provide more information to api consumers
=> enhancement: add parent name and path to shared the shared by me endpoint

tests/acceptance/features/apiSharingNg/shareInvitations.feature
- Scenario Outline: send share invitation to already shared user
- Locally
- :robot:
=> [full-ci] [tests-only] Added test for sending share invitation to user already received share

services/graph/pkg/service/v0/driveitems.go
use parent path in the parentReference graphApi property
- https://github.com/owncloud/web/pull/10392
=> fix: graph api sharing parentReference path

.drone.star, docs/ocis/development/testing.md, tests/TestHelpers/OcisHelper.php, tests/acceptance/docker/src/acceptance.yml, tests/acceptance/features/bootstrap/FeatureContext.php, tests/acceptance/features/bootstrap/Provisioning.php, tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
In this PR, the graph API is made the default API while testing. Also, this function `isTestingWithGraphApi()` is removed
- related to https://github.com/owncloud/ocis/issues/8276
- locally
- CI
=> [tests-only][full-ci] Make graph api default in test

changelog/unreleased/fix-concurrent-shares-config.md, services/web/pkg/config/defaults/defaultconfig.go
Fixes an issue where setting the config for concurrent share requests did not work.
- refs https://github.com/owncloud/ocis-charts/issues/473
=> fix: setting config for concurrent share requests

tests/acceptance/features/apiSharingNg/shareInvitations.feature, tests/acceptance/features/bootstrap/SharingNgContext.php, tests/acceptance/features/bootstrap/SpacesContext.php
Added test to share a disabled project space.
Expected: sharing should fail with 404 status code
```feature
Scenario Outline: send share invitation for disabled project space to user with different roles
Scenario Outline: send share invitation for deleted project space to user with different roles
```
=> [tests-only][full-ci] added test to share a disabled project space

services/proxy/pkg/middleware/oidc_auth.go
This PR verifies the expiry of claims retrieved from the cache.
Before adding tests I need to bump the mockito cmd and the way we generate mocks. Things have changed a lot there.
=> verify expiry of cached claims

changelog/unreleased/enhancement-idp-config-background-img.md, services/idp/pkg/config/config.go, services/idp/pkg/service/v0/service.go, services/idp/public/index.html, services/idp/src/App.jsx, services/idp/src/app.css, services/idp/src/index.tsx
This revision introduces a new environment variable `IDP_LOGIN_BACKGROUND_URL` that overrides the default background image of the IDP login page when present.
- Fixes #7674
First, I want to confess that I'm by no means a frontend developer. I'll happily accept any feedback :-)
One of the main motivations of this change is to get closer to improving consistency across the services that I host in my lab. It's possible to configure the PhotoPrism background image, and I wanted a similar look and feel with owncloud.
My original idea was to allow the user to upload or configure an image, but that's a fair bit of work and it doesn't need to be that complicated. Simply updating the stylesheet with an externally configurable address is good enough :tm: 
Discussed in #7674 was the eventual …
=> feat(idp): support login page background configuration

tests/TestHelpers/GraphHelper.php, tests/acceptance/features/apiSharingNg/sharedByMe.feature, tests/acceptance/features/bootstrap/GraphContext.php
This PR adds tests for listing shared by me resource shared from personal space for `sharingNG`.
Added scenarios: 
```feature
Scenario: user lists the file shared from personal space
Scenario: user lists the folder shared from personal space
Scenario: user lists resources shared from personal space
Scenario: user lists the shared file inside of a folder from personal space
```
https://github.com/owncloud/ocis/issues/8111
=>  [tests-only] Added test for sharingNg for endpoint sharedByMe from personal space

.make/go.mk, .vscode/launch.json, docs/ocis/development/debugging.md, ocis/Makefile, ocis/docker/Dockerfile.linux.debug.amd64
Added ability to debug the ocis binary in a docker compose stack via delve.
Remote debugging is the debug mode commonly used to work with a debugger and target running on a remote machine or a container for example a wopi stack `deployments/examples/ocis_wopi/docker-compose.yml`.
Below we describe the steps how to build the image, run the docker-compose and connect via remote debugger.
1. Build the image:
```bash
cd github.com/owncloud/ocis/ocis
make debug-docker
```
2. Change the tag label:
```bash
export OCIS_DOCKER_TAG=debug
```
3. Change the docker-compose `ocis` or `ocis-appprovider-collabora` or `ocis-appprovider-onlyoffice` depends on what do you want to debug:
For example `deployments/examples/ocis_wopi/docker-compose.yml`
```yaml
ocis:
image: …
```
=> added ability to debug the ocis in a docker compose stack via delve

tests/acceptance/features/apiSharingNg/sharedByMe.feature
This PR adds tests for listing shared by me resource shared from project space for `sharingNG`.
Added scenarios: 
```feature
Scenario: user lists the file shared from project space
Scenario: user lists the folder shared from project space
Scenario: user lists resources shared from project space
Scenario: user lists the shared file inside of a folder from project space
```
https://github.com/owncloud/ocis/issues/8111
=> [tests-only]Added tests for `SharingNg` test share by me from project

tests/acceptance/features/apiSharingNg/shareInvitations.feature
- Scenario Outline: send share invitation for resource of project space to user with different roles
- Scenario Outline: send share invitation for resource of project space to group with different roles
- Locally
- :robot:
=> [tests-only] Add test to share resource inside of space

changelog/unreleased/remove-useless-vars.md, services/frontend/pkg/config/config.go, services/frontend/pkg/config/defaults/defaultconfig.go, services/frontend/pkg/revaconfig/config.go
Stumbled over two environment variables for which even the description states that they are not allowed to be changed. This PR has two positive results:
- reduced the risk to misconfigure ocis
- will allow the  web team to remove capability checks in web, because ocis is the only allowed backend. Since other clients are checking those capabilities, we can't remove the capabilities entirely.
I consider this to be a bugfix because the description of the env vars hints towards broken ocis if those config variables are set to other values than those which I now hardcoded.
=> fix: hardcode config for spaces which was not allowed to change

tests/acceptance/features/apiSharingNg/shareInvitations.feature
Added more examples for:
- Scenario Outline: try to share a resource with invalid roles
Added scenario for file:
- Scenario Outline: try to share a file with invalid roles
- Locally
- :robot:
=> [full-ci] [tests-only] Added more test coverage for invalid roles

tests/acceptance/features/apiSharingNg/sharedWithMe.feature, tests/acceptance/features/bootstrap/FeatureContext.php
extend `sharedWithMe` json response assertion for newly added properties:
```
- "@UI.Hidden"
- "@client.synchronize"
```
- coverage for https://github.com/owncloud/ocis/pull/8322
=> [tests-only] extend share invite json response assertion

tests/acceptance/features/apiSharingNg/shareInvitations.feature, tests/acceptance/features/apiSharingNg/sharedByMe.feature
This PR cleanup `resourcetype` elements in the table row of the feature file as the resourceID of both file and folder can be received similarly. Thus, the step is redundant. 
Related issue: https://github.com/owncloud/ocis/issues/8349
=> [ tests only ] [ full-ci] removed datatable for resource type row

deployments/continuous-deployment-config/ocis_wopi/daily.yml, deployments/continuous-deployment-config/ocis_wopi/latest.yml, deployments/continuous-deployment-config/ocis_wopi/released.yml, deployments/examples/ocis_wopi/.env, deployments/examples/ocis_wopi/config/ocis/web-daily.yaml, deployments/examples/ocis_wopi/config/ocis/web-latest.yaml, deployments/examples/ocis_wopi/config/ocis/web-released.yaml, deployments/examples/ocis_wopi/docker-compose.yml
Add Uppy Companion to wopi example, so cloud imports work as soon as the importer app is shipped with oC Web.
Cloud imports need the Uppy Companion microservice.
Tested locally with my own build of oC Web.
=> Add Uppy Companion to wopi example

tests/acceptance/features/coreApiWebdavOperations/downloadFile.feature
Added API test to check `Content-Disposition` header for a file containing comma in its name
Coverage for:
- https://github.com/owncloud/ocis/issues/8361
- https://github.com/cs3org/reva/pull/4498
=> [tests-only] extend API test coverage for content-disposition header

tests/acceptance/features/coreApiWebdavOperations/downloadFile.feature
Added API tests to check Content-Disposition header with files having quotes (single `'` and double `"`) in their name
- Extending https://github.com/owncloud/ocis/pull/8378
=> [tests-only] API test coverage content-disposition header with filename having quotes

tests/acceptance/features/bootstrap/FeatureContext.php, tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
```feature
Scenario: sharer renames the shared item (old/new/spaces webdav)
Scenario: share receiver renames the shared item (old/new/spaces webdav)
```
- Test coverage for https://github.com/owncloud/ocis/issues/8242
=> [tests-only] add API test coverage for issue-8242

changelog/unreleased/fix-signed-url-expiry.md, services/proxy/pkg/command/server.go, services/proxy/pkg/middleware/signed_url_auth.go, services/proxy/pkg/middleware/signed_url_auth_test.go
- test case 1:
- test case 2:
- ...
=> fix: signed url expiry check and signature validation

Makefile, docs/services/_includes/.gitignore, docs/services/_includes/adoc/env-var-deltas/_index.md
This PR extends the make `docs-generate` step to pick up the adoc tables with the variable deltas.
=> adapt docs-generate step to pick up env var delta tables

changelog/unreleased/enhancement-skip-version-service-listing, ocis/pkg/command/version.go
The ocis version cmd listed all services by default. This is not always intended,
so we allow to skip the listing of the services by using the --skip-services flag.
@kobergj, @dragonchaser and myself had a good time finding out who likes line-breaks before errors in the cli output and who not, worth every second. THX for that, i loved the discussion 🤣 
- Fixes https://github.com/owncloud/ocis/issues/8070
=> enhancement: allow skipping service listing

changelog/unreleased/fix-extended-env-parser.md, docs/helpers/extendedEnv.go, docs/helpers/extended_vars.yaml
The extended envvar parser would be angry if there are two `os.Getenv` in the same line.
We fixed this.
=> Fix extended Envvar parsing

changelog/unreleased/fix-search-responce.md, services/search/pkg/engine/bleve.go, services/search/pkg/query/error.go, services/search/pkg/query/kql/cast.go, services/search/pkg/query/kql/dictionary_test.go, services/search/pkg/query/kql/kql_test.go, services/search/pkg/query/kql/validate.go
We fixed the search response code from 500 to 400 when the request is invalid
- Fixes [https://github.com/owncloud/ocis/issues/7812](https://github.com/owncloud/ocis/issues/7812)
- test case 1:
- test case 2:
- ...
=> fix search response

docs/helpers/extended_vars.yaml
This PR fixes the content of the `extended_envars.yaml` file based on recent changes in the micro registry setup.
=> [docs-only] Fixes the content of extended_envars.yaml

services/_includes/adoc/storage-users_configvars.adoc
Removing a not necessary line item in the adoc table, else this renders as:
```
OCIS_ASYNC_UPLOADS
``
```
See  the two not necessary ticks in the second line.
Note that this only does the change in the docs-stable-4.0 branch.
Master is clean.
=> Fix a typo

tests/acceptance/features/apiSharingNg/listPermissions.feature
This PR implements code to strictly validate json scheme and json response. Upto now using `maxItems` validate the json response only. Json scheme can contain any number of items but json response should contain maxItem number items 
- Fixes https://github.com/owncloud/ocis/issues/8333
- test case 1:
- test case 2:
- ...
=> [tests-only][full-ci]Strictly validate json scheme on tests steps

changelog/unreleased/speed-up-starttime.md, ocis/pkg/runtime/service/service.go
Improves the time the single binary needs to start from `8s` to `2.5s` by removing wait times and pinging nats/gateway instead.
Out of some reason there is still wait time of one second needed on the ci. I cannot reproduce locally. Can be tackled in subsequent PR.
=> Improve Single Binary Boot time

changelog/unreleased/enhancement-env-in-yaml.md, ocis-pkg/config/helpers.go
We added the ability to use environment variables in yaml config files. This allows to use environment variables in the config files of the ocis services which will be replaced by the actual value of the environment variable at runtime.
Example:
```yaml
web:
http:
addr: ${SOME_HTTP_ADDR}
```
This makes it possible to use the same config file for different environments without the need to change the config file itself. This is especially useful when using docker-compose to run the ocis services. It is a common pattern to create an .env file which contains the environment variables for the docker-compose file. Now you can use the same .env file to configure the ocis services.
- test case 1:
- test case 2:
- ...
=> feat: use env variable in yaml config files

changelog/5.0.0-rc.1_2023-12-27/enhancement-sse-messaging.md
An error crept into the changelog and accidentally mentioned a user
=> [docs-only] fix: changelog contributer mention

CHANGELOG.md, changelog/5.0.0-rc.1_2023-12-27/access-token-issuer.md, changelog/5.0.0-rc.1_2023-12-27/allow-configuring-additional-routes.md, changelog/5.0.0-rc.1_2023-12-27/passwod-policies-renaming.md
During working on release notes, I have identified that some point to the wrong PR.
This PR fixes the found one in the changelog folder but NOT in the CHANGELOG.md file.
@kulmann can you add a commit to fix what ever else is necessary that needs fixing too?
=> [docs-only] Fixing changelog references pointing to the wrong PR

changelog/unreleased/fix-search-error-message.md, services/webdav/pkg/service/v0/search.go
Fixed the error message returned by the invalid search request. now, the message only includes the necessary info
Current:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
<s:message>
{&#34;id&#34;:&#34;com.owncloud.api.search&#34;,&#34;code&#34;:400,&#34;detail&#34;:&#34;error: bad request: the expression can&#39;t begin from a binary operator: &#39;AND&#39;&#34;,&#34;status&#34;:&#34;Bad Request&#34;}
</s:message>
</d:error>
```
With Fix:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
<s:message>
error: bad request: the expression can&#39;t begin from a binary …
```
=> fix: bulky error message for invalid search request

tests/acceptance/config/behat.yml, tests/acceptance/features/apiSearch1/search.feature, tests/acceptance/features/bootstrap/SpacesContext.php
Added API test coverage for trying to search items with invalid search pattern.
Part of https://github.com/owncloud/ocis/issues/8440
Coverage for:
- https://github.com/owncloud/ocis/pull/7815
- https://github.com/owncloud/ocis/issues/7812
- https://github.com/owncloud/ocis/pull/8444
- https://github.com/owncloud/ocis/issues/8442
=> [tests-only] add API test coverage for trying to search with invalid pattern

tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
In this PR following scenarios are added related to sharingNG:
```
- Scenario: user lists the space file shared with them when sync is disabled
- Scenario: user lists the space folder shared with them when sync is disabled
```
- locally
- CI
=> [tests-only][full-ci] add tests to list space file shared with them when sync is disabled

tests/acceptance/features/apiSearch2/mediaTypeSearch.feature, tests/acceptance/features/bootstrap/WebDav.php
Added API tests related to search with mediatype filter. tests for these filters:
```
mediatype:folder
mediatype:document
mediatype:pdf
mediatype:image
mediatype:archive
```
extend test coverage
=> [tests-only] extend search tests for mediatype filter

tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature, tests/acceptance/features/bootstrap/SpacesContext.php, tests/acceptance/features/bootstrap/WebDav.php
Added API test coverage for these scenarios:
- try to MOVE file to space-id as its detination
- MOVE file to folder-id as its detination
Part of https://github.com/owncloud/ocis/issues/8440
Coverage for:
- https://github.com/owncloud/ocis/issues/6739
=> [tests-only] add API test coverage for file MOVE to space-id as destination

docs/ocis/adr/0016-files-metadata.md, docs/ocis/adr/0024-msgpack-metadata.md
This is a little after the fact, but we should document why we are no longer using xattrs and instead moved to msgpack.
cc @aduffeck anything to add from your side?
=> [docs-only] ADR-0024 msgpack metadata

tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
In this PR following scenarios are added related to sharingNG:
```
-   Scenario: group member lists the file shared with them from project-space when auto-sync is disabled
-   Scenario: group member lists the space folder shared with them from project-space when auto-sync is disabled
```
- locally
- CI
=> [tests-only][full-ci] add tests to list space files shared with group when auto sync is disable

tests/acceptance/features/apiSharingNg/sharedByMe.feature, tests/acceptance/features/bootstrap/GraphContext.php
This PR adds test coverage for `sharedByMe` after sharee gets deleted with clearing up the user cache and the group cache for the deleted sharee and the group respectively.
```feature
Scenario: user lists shared resources for deleted sharee
Scenario: user lists shared resources for deleted group
```
https://github.com/owncloud/ocis/issues/8111
=> [tests-only][full-ci]Added tests to lists shared by me after sharee is deleted

tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
Extends https://github.com/owncloud/ocis/pull/8459
Added tests for trying to MOVE to shares space-id
Coverage for: https://github.com/owncloud/ocis/issues/6739
=> [tests-only] extend tests: MOVE to Shares-space-id as destination

tests/TestHelpers/WebDavHelper.php, tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/features/bootstrap/AuthContext.php, tests/acceptance/features/bootstrap/SpacesContext.php, tests/acceptance/features/bootstrap/WebDav.php, tests/acceptance/features/coreApiAuth/webDavCOPYAuth.feature, tests/acceptance/features/coreApiAuth/webDavDELETEAuth.feature, tests/acceptance/features/coreApiAuth/webDavMOVEAuth.feature
Tests fixed according to https://github.com/owncloud/ocis/issues/3882#issuecomment-1156408457
>So I just tested this and requests to another users resources now always return 404.
I also opened a PR for the request body check: https://github.com/cs3org/reva/pull/2974
Part of https://github.com/owncloud/ocis/issues/8440
Tests fix for https://github.com/owncloud/ocis/issues/3882
=> [tests-only] fix MOVE with another user dav path scenarios

tests/acceptance/features/bootstrap/PublicWebDavContext.php, tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature
Added API test coverage for a scenarios where user tries to access public link using own basic auth
Coverage: https://github.com/owncloud/web/issues/10473
=> [tests-only] add test to try to download public link using basic auth

changelog/unreleased/deprecate-sharing-cs3-backends.md, ocis/pkg/command/migrate.go, services/sharing/pkg/config/config.go
The `cs3` user and public sharing drivers have already been replaced by `jsoncs3`. We now mark them as deprecated in preparation to kill a lot of unused code in reva.
We do have a migration cli to dump and load data from driver implementations. cs3 supports dump and jsoncs3 supports load, so a migration is possible.
=> Deprecate sharing cs3 backends

tests/acceptance/features/apiSharingNg/sharedWithMe.feature
Added scenario:
-  Scenario: user lists the file with same name shared by two users with him/her
-   Scenario: user lists the folder with same name shared by two users with him/her
- Part of https://github.com/owncloud/ocis/issues/7826
- Locally
- :robot:
=> [full-ci] [tests-only] Added tests to list sharedWithMe for file with same name shared by multiple users

tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
- `Scenario: user who is also a member of group lists the file shared with them`
- `Scenario: user who is also a member of group lists the folder shared with them`
- Locally
- :robot:
=> [full-ci] [tests-only] Added tests for auto-sync disabled

.drone.env, changelog/unreleased/update-web-8.0.0.md, services/web/Makefile
=> [full-ci] chore: bump web to v8.0.0-rc.5

tests/acceptance/features/apiSharingNg/linkShare.feature, tests/acceptance/features/apiSharingNg/updateShareInvitations.feature, tests/acceptance/features/bootstrap/SharingNgContext.php
This PR adds tests for removing expiration-date from share links and user share 
- Part of <https://github.com/owncloud/ocis/issues/8428>
- test case 1:
- test case 2:
- ...
=> [full-ci][tests-only]add tests coverage for removing expiration date from shares

tests/acceptance/features/apiSharingNg/sharedWithMe.feature, tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
Make array in json schema stricter by adding `minItems` and `maxItems`
Part of https://github.com/owncloud/ocis/issues/8333
=> [tests-only] make json scheme assertion strict

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiGraph/userGDPRExport.feature, tests/acceptance/features/apiGraphUserGroup/editUser.feature, tests/acceptance/features/apiGraphUserGroup/getGroup.feature, tests/acceptance/features/apiGraphUserGroup/getUser.feature, tests/acceptance/features/apiGraphUserGroup/getUserOwnInformation.feature, tests/acceptance/features/apiSharingNg/listPermissions.feature, tests/acceptance/features/apiSharingNg/shareInvitations.feature, tests/acceptance/features/apiSharingNg/sharedByMe.feature, tests/acceptance/features/apiSharingNg/sharedWithMe.feature, tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature, tests/acceptance/features/apiSharingNg/updateShareInvitations.feature, tests/acceptance/features/apiSpaces/changeSpaces.feature, tests/acceptance/features/bootstrap/FeatureContext.php, tests/acceptance/features/bootstrap/GraphContext.php, tests/acceptance/features/coreApiCapabilities/capabilities.feature, vendor-bin/behat/composer.json
Moving from `helmich/phpunit-json-assert` to [swaggest/json-schema](https://github.com/swaggest/php-json-schema) for json schema assertion.
- supports [JSON Schema Draft 7](http://json-schema.org/specification-links.html#draft-7), [JSON Schema Draft 6](http://json-schema.org/specification-links.html#draft-6), [JSON Schema Draft 4](http://json-schema.org/specification-links.html#draft-4)
- reports invalid schema
Example: https://drone.owncloud.com/owncloud/ocis/32272/15/6
```yml
"required": [
"opaque_id"
],
<-- ❌ INVALID -->
"properties": {
"type": "object",
"pattern": "^%user_id_pattern%:%user_id_pattern%:%user_id_pattern%$"
}
```
```yml
"required": [
"opaque_id"
],
<-- ✔️ VALID -->
"properties": {
"opaque_id": {
"type": "string",
"pattern": …
```
=> [tests-only] use new json schema assertion lib that supports latest schema drafts

changelog/unreleased/enhancement-add-epub-reader-to-web-default-apps.md, services/web/pkg/config/defaults/defaultconfig.go
- test case 1:
- test case 2:
- ...
=> Add epub-reader to apps default config

.drone.star
=> [full-ci] split e2e tests in ocis CI

changelog/unreleased/change-presigned-key-store.md, ocis/pkg/runtime/service/service.go, services/ocs/README.md, services/ocs/pkg/config/config.go, services/ocs/pkg/config/defaults/defaultconfig.go, services/ocs/pkg/server/http/server.go, services/ocs/pkg/service/v0/option.go, services/ocs/pkg/service/v0/service.go, services/ocs/pkg/service/v0/users.go, services/proxy/README.md, services/proxy/pkg/command/server.go, services/proxy/pkg/config/config.go, services/proxy/pkg/config/defaults/defaultconfig.go, services/proxy/pkg/middleware/options.go, services/proxy/pkg/middleware/signed_url_auth.go, services/proxy/pkg/middleware/signed_url_auth_test.go, services/store/pkg/store/options.go, services/store/pkg/store/store.go
The store service was born out of a misunderstanding ... we need to clean that up. This PR changes the default signing key store to nats, but allows configuring and using the old store service to running existing installations without changes to the deployment (if updating the configuratin).
The change does not need a migration as signing keys are just regenerated on the fly.
I don't know if the web ui will re download the signing key if it expired. I don't think it has a way of detecting that as the browser will handle the download. Maybe they should just forget the signing key ... every 5min? so it is periodically refetched?
I can see the ocis web ui being left open for a long time, so I set the new signing key TTL default to 12h. In the past it never expired, which IMO is a pad …
=> make store service configurable

.drone.env, services/web/Makefile, tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Bumping web to `v9.0.0-alpha.1`.
Didn't include changelog because the changelog in web is not sorted out for `master` currently.
=> [full-ci] chore: bump web to v9.0.0-alpha.1

tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
In this PR following scenarios are added related to sharingNG:
```
-   user who is also a member of group lists file shared with them from project-space
-   user who is also a member of group lists folder shared with them from project-space
```
- locally
- CI
=> [tests-only][full-ci] Add tests to list space files shared with user who is also member of group 

tests/acceptance/features/apiNotification/notification.feature, tests/acceptance/features/apiNotification/spaceNotification.feature, tests/acceptance/features/apiSharingNg/linkShare.feature, tests/acceptance/features/apiSharingNg/updateShareInvitations.feature, tests/acceptance/features/bootstrap/FeatureContext.php
More schema validation:
- report if there are invalid schema validators
```yml
"type": "object",
"key101": "value1"
```
- do not allow validators used for array in object and vice versa
```yml
"type": "object",
"items": {}
```
**NOTE:** For object and array types, we have to specify `type` validator. Currently, we haven't made `type` as the required validator.
Found these problems:
https://drone.owncloud.com/owncloud/ocis/32443/28/6, https://drone.owncloud.com/owncloud/ocis/32446/30/8
```
apiSharingNg/linkShare.feature:589
apiSharingNg/linkShare.feature:590
apiSharingNg/updateShareInvitations.feature:156
apiSharingNg/updateShareInvitations.feature:157
apiNotification/notification.feature:125
apiNotification/notification.feature:126
apiNotification/spaceNotification.feature:16 …
```
=> [tests-only] check for invalid schema validators

tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
In this PR following scenarios are added related to sharingNG:
```
- user lists the file with same name shared by user from two project-spaces with him/her
- user lists the folder with same name shared by user from two project-spaces with him/her
```
- locally
- CI
=> [tests-only][full-ci] Add tests to list same name resources shared by user from two project-spaces with him/her

.vscode/launch.json, ocis-pkg/shared/errors.go, ocis/pkg/init/init.go, services/auth-service/pkg/config/parser/parse.go, services/clientlog/pkg/config/parser/parse.go, services/frontend/pkg/config/parser/parse.go, services/graph/pkg/config/parser/parse.go, services/notifications/pkg/config/parser/parse.go, services/ocm/pkg/config/parser/parse.go, services/proxy/pkg/config/parser/parse.go, services/search/pkg/config/parser/parse.go, services/settings/pkg/config/parser/parse.go, services/storage-users/pkg/config/parser/parse.go, services/userlog/pkg/config/parser/parse.go
while we are configuring them in ocis init, we are not verifying if they are set. This allows the service to start with a broken configuration that leads to failing requests.
=> verify all system accounts are set

services/store/pkg/config/config.go, services/store/pkg/config/debug.go, services/store/pkg/config/grpc.go, services/store/pkg/config/log.go, services/store/pkg/config/tracing.go
follow up to https://github.com/owncloud/ocis/pull/8555
also needs to be backported to stable 5
=> deprecate store env vars

changelog/unreleased/select-next-clients-for-autoaccept.md, services/frontend/pkg/command/events.go
fixes autoaccepting shares when k8s decided to move the gateway pod
We need to pass down a selector and get a new client with Next(), right before the call.
Don't worry abouit the the Next() call itself. It stays in memory, as the registry uses a cache that is actively invalidated.
=> always select the next clients when autoaccepting shares

.drone.env, changelog/unreleased/update-web-8.0.1.md, services/web/Makefile, tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Bump web to `v8.0.1` brings 2 bugfixes and a German translation update.
=> [full-ci] chore: bump web to v8.0.1

.drone.star
=> [test-only] Port #8528 to stable

services/storage-users/pkg/config/config.go
Would be great if we could backport this to `stable-5.0`.
=> [docs-only] Just a small text fix for an envvar in storage-users

.drone.env, changelog/unreleased/update-web-9.0.0.md, services/web/Makefile, tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Bumping web to `v9.0.0-alpha.2`
=> [full-ci] chore: bump web to v9.0.0-alpha.2

changelog/unreleased/non-default-multipartuploads.md, services/storage-users/pkg/config/defaults/defaultconfig.go
Multipart uploads do cause extreme memory consumption
=> Disable Multiparts uploads

tests/acceptance/features/apiSharingNg/propfindShares.feature
As sharee, PROPFIND the shares, when two users share resources with the same name using graph API.
Restructured the scenario so that it will cover the folder as well.
- Part of https://github.com/owncloud/ocis/issues/8493
- Coverage for https://github.com/owncloud/ocis/issues/4421
- Locally
- :robot:
=> [full-ci] [tests-only] Added tests for PROPFIND as sharee for folder

changelog/unreleased/sharing-ng-spacepermissions.md, services/graph/pkg/service/v0/driveitems.go, services/graph/pkg/service/v0/driveitems_test.go, services/graph/pkg/service/v0/drives.go, services/graph/pkg/service/v0/graph_test.go, services/graph/pkg/service/v0/users.go, services/graph/pkg/service/v0/utils.go, services/graph/pkg/unifiedrole/unifiedrole.go, services/graph/pkg/unifiedrole/unifiedrole_test.go, tests/acceptance/features/apiSharingNg/listPermissions.feature, tests/acceptance/features/apiSharingNg/shareInvitations.feature
Make `GET https://localhost:9200/graph/v1beta1/drives/{{driveid}}/items/{{itemid}}/permissions` work for spaceroots
This is still missing link permission on the space root.
=> enhancement(sharing): Return space permissions when looking up space root

changelog/unreleased/fix-graph-internal-link.md, services/graph/pkg/service/v0/driveitems_test.go, services/graph/pkg/service/v0/links.go, tests/acceptance/features/apiSharingNg/linkShare.feature
Internal links shouldn't have a password
- Fixes [https://github.com/owncloud/ocis/issues/8619](https://github.com/owncloud/ocis/issues/8619)
- test case 1:
- test case 2:
- ...
=> internal links shouldn't have a password

tests/acceptance/features/apiAccountsHashDifficulty/assignRole.feature, tests/acceptance/features/apiAntivirus/antivirus.feature, tests/acceptance/features/apiAsyncUpload/delayPostprocessing.feature, tests/acceptance/features/apiContract/propfind.feature, tests/acceptance/features/apiCors/cors.feature, tests/acceptance/features/apiDownloads/spaceDownload.feature, tests/acceptance/features/apiGraph/assignRole.feature, tests/acceptance/features/apiGraph/changeRole.feature, tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature, tests/acceptance/features/apiGraph/getApplications.feature, tests/acceptance/features/apiGraph/unassignRole.feature, tests/acceptance/features/apiGraph/userGDPRExport.feature
kebab-case is used for the example table header name.
- Part of https://github.com/owncloud/QA/issues/829
- :robot:
=> [full-ci] [tests-only] Used kebab case for example table header name

tests/acceptance/features/apiCors/cors.feature, tests/acceptance/features/apiSharingNg/propfindShares.feature, tests/acceptance/features/bootstrap/SpacesContext.php
As sharee, PROPFIND the shares using the `new` dav path, when two users share resources with the same name using graph API.
- `Scenario Outline: sharee PROPFIND same name shares shared by multiple users using new dav path`
- Part of https://github.com/owncloud/ocis/issues/8493
- Locally
- :robot:
=> [full-ci] [tests-only] sharee PROPFINDs same name shares shared by multiple users

changelog/unreleased/improve-cors.md, ocis-pkg/config/config.go, services/frontend/pkg/config/defaults/defaultconfig.go, services/invitations/pkg/config/defaults/defaultconfig.go, services/ocdav/pkg/config/defaults/defaultconfig.go, services/ocm/pkg/config/defaults/defaultconfig.go, services/storage-users/pkg/config/defaults/defaultconfig.go, services/web/pkg/config/defaults/defaultconfig.go, services/webfinger/pkg/config/defaults/defaultconfig.go, sonar-project.properties, tests/acceptance/features/apiContract/copy.feature, tests/acceptance/features/apiCors/cors.feature
Enhencement: Change Cors default settings
We have changed the default CORS settings to set `Access-Control-Allow-Origin` to the `OCIS_URL` if not explicitely set
and `Access-Control-Allow-Credentials` to `false` if not explicitely set.
refs https://github.com/owncloud/ocis/issues/8514
=> [full-ci] adapt cors headers

docs/ocis/adr/0027-new-share-jail.md
As a follow up to https://github.com/owncloud/ocis/issues/8420 @rhafer and I agreed to come up with an ADR that describes how to properly fix the `oc:fileid` in the sharejail.
cc @dragotin @micbar please comment or commit. I'll merge this on friday as draft, unless we all agree, then I'll set the status to `accepted` before merging.
=> [docs-only] ADR-0027 New share jail

tests/acceptance/features/apiSharingNg/sharedWithMe.feature
This PR adds the tests to check the resource name when multiple users shares resource with the same name. We are basically checking if the suffix of the resource with the same name are correct or not.
https://github.com/owncloud/ocis/issues/8428
https://github.com/owncloud/ocis/issues/8471
=> [tests-only][full-ci] check same name resources shared by different users

changelog/unreleased/enhancement-strict-same-site-cookie.md, go.mod, go.sum, services/idp/pkg/backends/cs3/bootstrap/cs3.go, services/idp/pkg/config/config.go, services/idp/pkg/config/defaults/defaultconfig.go, vendor/github.com/libregraph/lico/bootstrap/backends/ldap/ldap.go, vendor/github.com/libregraph/lico/bootstrap/backends/libregraph/libregraph.go, vendor/github.com/libregraph/lico/bootstrap/bootstrap.go, vendor/github.com/libregraph/lico/bootstrap/config.go, vendor/github.com/libregraph/lico/bootstrap/settings.go, vendor/github.com/libregraph/lico/identifier/config.go, vendor/github.com/libregraph/lico/identifier/cookie.go, vendor/github.com/libregraph/lico/identifier/identifier.go, vendor/github.com/libregraph/lico/oidc/provider/config.go, vendor/github.com/libregraph/lico/oidc/provider/cookie.go, vendor/github.com/libregraph/lico/oidc/provider/provider.go, vendor/modules.txt
To enhance the security of our application and prevent Cross-Site Request Forgery (CSRF) attacks, we have updated the SameSite attribute of the build in Identity Provider (IDP) cookies to Strict.
This change restricts the browser from sending these cookies with any cross-site requests,
thereby limiting the exposure of the user's session to potential threats.
This update does not impact the existing functionality of the application but provides an additional layer of security
where needed.
Needs https://github.com/libregraph/lico/pull/131 ✅ 
https://www.authelia.com/configuration/session/introduction/#same_site-1
- Fixes enterprise issue xxx
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value
- local installation
=> enhancement: Make IDP cookies same site strict

services/graph/pkg/service/v0/driveitems.go, services/graph/pkg/service/v0/driveitems_test.go, services/graph/pkg/service/v0/drives.go, services/graph/pkg/service/v0/sharedbyme.go
To add a space member:
```
curl --request POST \
--url 'https://localhost:9200/graph/v1beta1/drives/0ec6cef0-9cd6-46a5-83ae-d4085a5f8a07$ae158e91-cb8b-45e0-ac9a-44ff5f6887d3/items/0ec6cef0-9cd6-46a5-83ae-d4085a5f8a07$ae158e91-cb8b-45e0-ac9a-44ff5f6887d3!ae158e91-cb8b-45e0-ac9a-44ff5f6887d3/invite' \
--data '{
"recipients": [
{
"@libre.graph.recipient.type": "user",
"objectId": "4c510ada-c86b-4815-8820-42cdf82c3d51"
}
],
"roles": [ <roleid> ]
}'
```
gives the response:
```
{
"value": [
{
"grantedToV2": {
"user": {
"displayName": "Albert Einstein",
"id": "4c510ada-c86b-4815-8820-42cdf82c3d51"
}
},
"id": "u:4c510ada-c86b-4815-8820-42cdf82c3d51",
"roles": [
"a8d5fe5e-96e3-418d-825b-534dbdf22b99"
]
}
]
}
```
To remove a permission:
```
curl --request DELETE \
--url …
```
=> [full-ci] More work on spaces support for sharing-ng

.drone.star
One of the e2e pipelines has ~20 mins of execution time. increasing the pipeline so that it balances out
Before:
Now:
=> [tests-only] increase e2e pipeline by 1

tests/acceptance/config/behat.yml, tests/acceptance/features/apiSpacesDavOperation/getFileByFileId.feature
In this PR the following scenario are added:
```feature
-   Scenario Outline: sharee gets content of a file inside a shared file when sync is disable
-   Scenario Outline: sharee gets content of a file inside a shared folder when sync is disable
```
- https://github.com/owncloud/ocis/issues/8662
-ci
- locally
=> [tests-only][full-ci] Add test for downloading resouces by user when auto sync is disabled

changelog/unreleased/enhancement-sharing-ng-role-names-and-descriptions.md, services/graph/pkg/unifiedrole/unifiedrole.go, tests/acceptance/features/apiSharingNg/listPermissions.feature
Adjusts display names and descriptions of sharing NG roles to align with the previously agreed upon terms.
=> refactor: adjust sharing ng role names and descriptions

go.mod
Set go version including the patch release to avoid an [unfixed bug in go.](https://github.com/golang/go/issues/66175)
After cleaning my go cache
```
go clean -modcache
go clean -cache
```
I couldn't build ocis anymore, `make generate` would stop with `ERR unable to parse packages error="err: exit status 1: stderr: go: downloading go1.22 (linux/amd64)\ngo: download go1.22 for linux/amd64: toolchain not available\n" dry-run=false version=v2.40.2`
setting the version in go.mod to `1.22.0` fixes the problem.
alternative workaround `GOTOOLCHAIN=go1.22.0 make generate`
- run `make generate` locally
=> set go version to 1.22.0

changelog/unreleased/add-spaceid-to-sse.md, changelog/unreleased/enable-drawio-by-default.md, services/web/pkg/config/defaults/defaultconfig.go
I guess it would be nice to have draw-io enabled by default - in addition I could not find any other way to enable it. :shrug: 
- test case 1:
- test case 2:
- ...
=> feat: enable draw-io extension by default

changelog/unreleased/mask-user-email-in-output.md, services/graph/pkg/config/config.go, services/graph/pkg/config/reva.go, services/graph/pkg/service/v0/users.go, services/ocs/pkg/config/config.go, services/ocs/pkg/config/reva.go, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiGraphUserGroup/editUser.feature, tests/acceptance/features/apiGraphUserGroup/getUser.feature, tests/acceptance/features/apiGraphUserGroup/searchUserIncludingEmail.feature
Bugfix: Mask user email in output
We have fixed a bug where the user email was not masked in the output and the user emails could be enumerated through
the sharee search. This is the ocis side which adds an suiting config option to mask user emails in the output.
refs #8726
=> filter user e-mail in graph/user requests

tests/acceptance/features/apiSpacesDavOperation/getFileByFileId.feature
In this PR, there is scenario added for downloading the resources by group when sync is disable.
Following scenario are added:
```
- user who is member of group gets content of a shared file when sync is disable
- user who is member of group gets content of a shared folder when sync is disable
```
-  https://github.com/owncloud/ocis/issues/8662
- ci
- locally
=> [tests-only][full-ci] Add test for downloading resources by group user when auto sync is disable

docs/README.md, docs/helpers/README.md, docs/helpers/env_vars.yaml, docs/helpers/extended_vars.yaml
Referencing: #8454 (Envar delta reflections)
As discussed with @dragonchaser 
Post merging the envvar delta reflections, we need to update the readme to document how and when to use the reflection go code. Additionally, updated and fixed envvar related yaml files have been added as they got updated by the process too.
As next step, I will provide the required adoc template files for added/removed and deprecated envvars to finalize the automation process.
@phil-davis mind to do a language review?
=> [docs-only] Update the docs helper readme and other related files

tests/acceptance/features/apiSharingNg/propfindShares.feature, tests/acceptance/features/bootstrap/SpacesContext.php
Added api test to check the driveItem id with `oc:fileid` from PROPFIND response. The `oc:fileid` should match the driveItem id from the sharedWithMe response, after the fixes in PR https://github.com/owncloud/ocis/pull/8467
```feature
Scenario Outline: check ids from sharedWithMe driveItemId with PROPFIND response
```
- https://github.com/owncloud/ocis/issues/8493
=> [tests-only][full-ci] added test to check id from shareWithMe and PROPFIND response

services/graph/pkg/service/v0/service.go
Requests to /raph/v1beta1/drives/{driveid}/root/permissions/{permissionid}setPassword were rooted to the wrong method.
=> fix(sharing-ng): Fix setPassword call for spaceroot

changelog/unreleased/fix-postprocessing-restart.md, services/postprocessing/README.md, services/postprocessing/pkg/config/defaults/defaultconfig.go, services/postprocessing/pkg/postprocessing/postprocessing.go, services/postprocessing/pkg/service/service.go, services/storage-users/pkg/command/uploads.go
- It was only working with an `inmemory` store
- Added a `restart` parameter to the `ocis storage-users uploads sessions` command. It will restart all listed sessions
=> Repair Restart Postprocessing Logic

changelog/unreleased/fix-remove-group-from-share.md, services/graph/pkg/service/v0/driveitems.go
We fixed a bug when unable to remove groups from space via graph
- Fixes [https://github.com/owncloud/ocis/issues/8768](https://github.com/owncloud/ocis/issues/8768)
- test case 1:
- test case 2:
- ...
=> fix removing groups from space

.drone.env, changelog/unreleased/update-web-9.0.0.md, services/web/Makefile
Bumps Web to `v9.0.0-alpha.4`, including recent security fixes, sharing NG, SSE for file creation and extension points.
=> [full-ci] chore: bump web to v9.0.0-alpha.4

tests/TestHelpers/GraphHelper.php, tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature, tests/acceptance/features/bootstrap/SharingNgContext.php
Changing wording for mount/unmount to enable and disable sync.
=> [tests-only][full-ci] changed wording of mount unmount to enable and disable sync

changelog/unreleased/next-before-making-calls.md, services/clientlog/pkg/service/service.go, services/graph/pkg/service/v0/api_drives_drive_item.go, services/storage-users/pkg/task/trash_bin.go, services/userlog/pkg/service/conversion.go, services/userlog/pkg/service/http.go, services/userlog/pkg/service/service.go
Following https://github.com/owncloud/ocis/pull/8570 I went over other places in ocis that use the selector and client. We now select the next client more often to spread out load.
I don't expect a huge impact from this PR.
=> always select next before making calls

changelog/unreleased/enhancement-strict-same-site-cookie.md, go.mod, go.sum, services/idp/pkg/backends/cs3/bootstrap/cs3.go, services/idp/pkg/config/config.go, services/idp/pkg/config/defaults/defaultconfig.go, vendor/github.com/libregraph/lico/bootstrap/backends/ldap/ldap.go, vendor/github.com/libregraph/lico/bootstrap/backends/libregraph/libregraph.go, vendor/github.com/libregraph/lico/bootstrap/bootstrap.go, vendor/github.com/libregraph/lico/bootstrap/config.go, vendor/github.com/libregraph/lico/bootstrap/settings.go, vendor/github.com/libregraph/lico/identifier/config.go, vendor/github.com/libregraph/lico/identifier/cookie.go, vendor/github.com/libregraph/lico/identifier/identifier.go, vendor/github.com/libregraph/lico/oidc/provider/config.go, vendor/github.com/libregraph/lico/oidc/provider/cookie.go, vendor/github.com/libregraph/lico/oidc/provider/provider.go, vendor/modules.txt
backport https://github.com/owncloud/ocis/pull/8716 to stable 5
=> backport enhancement: same site strict cookies to stable 5

changelog/unreleased/fix-graph-create-drive-item.md, services/graph/pkg/service/v0/api_drives_drive_item.go, services/graph/pkg/service/v0/api_drives_drive_item_test.go
We fixed the issue when creating a drive item with a random item id was allowed
- Fixes [https://github.com/owncloud/ocis/issues/8724](https://github.com/owncloud/ocis/issues/8724)
- test case 1:
- test case 2:
- ...
=> fix creating the drive item

services/postprocessing/README.md, services/storage-users/README.md
Referencing: https://github.com/owncloud/docs-ocis/pull/773 (Update of the restart postprocessing process)
When writing the above PR based on changes in ocis, I identified that readmes in ocis also need a fix to make things complete and inline.
=> [docs-only] fix two services readme to be inline with admin docs

tests/acceptance/features/apiSharingNg/deletePermissions.feature, tests/acceptance/features/bootstrap/SharingNgContext.php
=> [test-only] remove user/group from space

tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
Test for enable and disable sync of shared resource from Project Space
Merge this PR only after https://github.com/owncloud/ocis/pull/8786
- tlocally
- CI
- ...
=> [tests-only][full-ci]Enable disable sync from project space

services/frontend/pkg/config/config.go
While working on #8836, it turned out that the envvar description for `OCIS_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD` was not clear and the text could be misunderstood with respect to user roles respectively there was no relationship mentionened to all public shares.
The text now makes this clear.
Should be backported to stable-5.0
=> [docs-only] Make a frontend envvar description more clear

services/frontend/README.md
References:
https://github.com/owncloud/docs-ocis/pull/777 (Update the frontend description to improve password management)
#8607 (Improve dev docs on how to disable the password enforcement for public links)
This updates the frontend service readme to reflect the changes made in the referenced docs-ocis PR.
=> [docs-only] Update the frontent service readme adding more password descriptions

services/graph/pkg/errorcode/cs3.go, services/graph/pkg/errorcode/cs3_test.go, services/graph/pkg/errorcode/errorcode.go, services/graph/pkg/errorcode/errorcode_test.go, services/graph/pkg/service/v0/api_driveitem_permissions.go, services/graph/pkg/service/v0/api_driveitem_permissions_links.go, services/graph/pkg/service/v0/api_driveitem_permissions_test.go, services/graph/pkg/service/v0/api_drives_drive_item.go, services/graph/pkg/service/v0/api_drives_drive_item_test.go, services/graph/pkg/service/v0/base.go, services/graph/pkg/service/v0/drives.go, services/graph/pkg/service/v0/sharedwithme.go, services/graph/pkg/service/v0/utils.go
cc @fschade 
related: https://github.com/owncloud/ocis/pull/8578 (will have conflicting changes when this is merged)
=> always use error interface when returning errors

services/frontend/pkg/config/config.go
Based on a discussion with @tbsbdr, we can remove the EXPERIMENTAL string from the `OCIS_SHOW_USER_EMAIL_IN_RESULTS` envvar text in the frontend service.
This is already fixed in master.
=> [docs-only] Remove EXPERIMENTAL from envvar text

tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
Adding test feature file that covers test for enabling and disabling sync of share shared from Project space to group
- tlocally
- CI
=> [tests-only][full-ci]added test for enable disable share shared by project space to group

deployments/examples/ocis_wopi/docker-compose.yml
podman doesn't have a "local" log driver. Also it's docker-compatibility socket does live in a different location (especially when running rootless podman).
With this change you can run the deployement with a recent podman version using:
LOG_DRIVER=journald DOCKER_SOCKET_PATH=/run/user/1000/podman/podman.sock podman compose start
=> Allow to run wopi example deployment with podman

changelog/unreleased/fix-adding-wopi-doc-on-public-share.md, services/proxy/pkg/middleware/public_share_auth.go
The public share authentication middleware only allowed to open existing documents the /app/new route was missing.
Fixes #8691
=> fix(public-share-auth): allow to create new documents in public share folder

.drone.env, changelog/unreleased/fix-graph-unmount-item.md, services/graph/pkg/service/v0/api_drives_drive_item.go, services/graph/pkg/service/v0/api_drives_drive_item_test.go, tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
We fixed the issue when unmount item from share will result in 200 status code
- Fixes [https://github.com/owncloud/ocis/issues/8731](https://github.com/owncloud/ocis/issues/8731)
- test case 1:
- test case 2:
- ...
=> fix unmount item from share

.drone.env, changelog/unreleased/update-web-9.0.0.md, services/web/Makefile, tests/acceptance/features/apiSharingNg/sharedWithMe.feature
Bumps Web to `v9.0.0-alpha.5`.
=> [full-ci] chore: bump web to v9.0.0-alpha.5

docs/services/general-info/new-service-checklist.md
References: https://github.com/owncloud/docs-ocis/issues/793 (Add a monitoring / metrics section)
Add metrics / monitoring to the checklist for new services.
Small text fixes.
When a new serice does not need this, it can be omitted, but we need to write it down as item so it does not get forgotten.
=> [docs-only] Update new-service-checklist in dev docs

tests/acceptance/config/behat-core.yml, tests/acceptance/features/apiGraphUserGroup/getUser.feature, tests/acceptance/features/apiGraphUserGroup/searchUserIncludingEmail.feature, tests/acceptance/features/bootstrap/GraphContext.php, tests/acceptance/features/bootstrap/ShareesContext.php, tests/acceptance/features/coreApiSharees/sharees.feature
tests for https://github.com/owncloud/ocis/issues/8726
=> [test-only]check email in the search sharee request

changelog/unreleased/sharing-sse.md, services/clientlog/pkg/service/service.go
Logic to decide what is a `rename` and what is a `move` was bonked. Should be working now.
Fixes https://github.com/owncloud/ocis/issues/8854
=> Unbonk rename logic

tests/TestHelpers/GraphHelper.php, tests/acceptance/features/apiSharingNg/listPermissions.feature, tests/acceptance/features/apiSharingNg/sharedWithMe.feature, tests/acceptance/features/bootstrap/SharingNgContext.php
This PR has added tests for listing permission using `/drives/{driveID}/root/permissions` api endpoint. 
- https://github.com/owncloud/ocis/issues/8351
- locally
=> [tests-only][full-ci]Add tests for listing drive root permission

tests/TestHelpers/GraphHelper.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSharingNg/removeAccessToDrive.feature, tests/acceptance/features/apiSharingNg/removeAccessToDriveItem.feature, tests/acceptance/features/bootstrap/SharingNgContext.php
https://owncloud.dev/libre-graph-api/#/drives.root/DeletePermissionSpaceRoot
=> [test-only] remove access to drive tests

tests/acceptance/features/apiSharingNg/shareInvitations.feature, tests/acceptance/features/apiSharingNg/sharedByMe.feature, tests/acceptance/features/bootstrap/GraphContext.php, tests/acceptance/features/bootstrap/Provisioning.php, tests/acceptance/features/bootstrap/SharingNgContext.php, tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature, tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
Do not try to delete already deleted groups
Fixes this error in AfterScenario hooks:
```php
│
╳  HTTP status code 404 is not the expected value 204
╳  Failed asserting that 404 matches expected 204.
│
└─ @AfterScenario # FeatureContext::afterScenario()
```
https://github.com/owncloud/ocis/issues/8864
=> [tests-only] do not try to delete already deleted groups

changelog/unreleased/nats-reconnects.md, ocis-pkg/natsjsregistry/registry.go
Repairs reconnects on the natsjs kv registry
New behaviour:
- when nats gets disconnected -> no change
- when nats gets reconnected -> registry reconnects correctly
- when nats connection is closed -> os.Exit as there is no way to recover without initializing everything
Fixes https://github.com/owncloud/ocis/issues/8783
=> Fix nats reconnects

.drone.star, composer.json, vendor-bin/behat/composer.json
upgrading php version in the drone to run ocis test
Php 8.3 doesn't work for CS-fixer, thus changing to 8.2
Fixes: https://github.com/owncloud/ocis/issues/8831
=> [tests-only] [full-ci] changed php version

.drone.star
Backport of PR: https://github.com/owncloud/ocis/pull/8929
=> [tests-only][full-ci]backport remove web smoke tests from nightly and full-ci

tests/acceptance/features/apiSharingNg/sharedByMe.feature
Added following scenarios:
```feature
Scenario: sharer lists the file and folder shares shared to group (Project space)
Scenario: sharer lists the file share after sharee is disabled (Personal space)
Scenario: sharer lists the file share after sharee (user) is deleted (Project space)
Scenario: sharer lists the file share after sharee (group) is deleted (Project space)
Scenario: sharer lists the file share after sharee is disabled (Project space)
```
- https://github.com/owncloud/ocis/issues/8111
=> [tests-only] extend list sharedbyme API tests coverage

changelog/unreleased/fix-well-known-rewrite.md, services/proxy/pkg/command/server.go, services/proxy/pkg/staticroutes/oidc_well-known.go, services/proxy/pkg/staticroutes/staticroutes.go
fixes https://github.com/owncloud/ocis/issues/8703
I also moved the oidcUrl from a struct property to a parameter of the handler func as it is only used there. By moving the parsing of the url right next to the handler we improve the [Locality of Behavior](https://htmx.org/essays/locality-of-behaviour/).
=> always initialize http handler

changelog/unreleased/fix-docker-compose-wopi.md, deployments/examples/ocis_wopi/config/ocis-appprovider-collabora/entrypoint-override.sh, deployments/examples/ocis_wopi/docker-compose.yml
- Fixes [https://github.com/owncloud/ocis/issues/8474](https://github.com/owncloud/ocis/issues/8474)
- test case 1:
- test case 2:
- ...
=> fix the docker-compose wopi

tests/TestHelpers/GraphHelper.php, tests/acceptance/features/apiSharingNg/listPermissions.feature, tests/acceptance/features/bootstrap/SharingNgContext.php
This PR adds a test coverage for listing all the permission allowed for a project space and share the project space with all those roles allowed.
```feature
Scenario: space admin invites to a project space with all allowed roles
```
- Fixes https://github.com/owncloud/ocis/issues/8336
- Locally
- Drone CI
=> [tests-only][full-ci] List permission and share a project space with allowed roles

changelog/unreleased/sharing-secure-view-role.md, services/graph/pkg/unifiedrole/unifiedrole.go, services/graph/pkg/unifiedrole/unifiedrole_test.go, tests/TestHelpers/GraphHelper.php, tests/acceptance/features/apiSharingNg/listPermissions.feature
Adds a new share role "Secure View". This role is applicable for files, folders and spaces and only allows viewing them (and their content).
- refs https://github.com/owncloud/web/issues/10765
=> feat: add secure view share role

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiArchiver/downloadByPath.feature
Changed `Given` step for share using SharingNg in `apiArchiver/downloadByPath.feature` file.
=> [tests-only] [full-ci] Change given step using SharingNG for share in apiArchiver/downloadByPath.feature file

tests/acceptance/features/apiAsyncUpload/delayPostprocessing.feature, tests/acceptance/features/apiNotification/spaceNotification.feature, tests/acceptance/features/bootstrap/ArchiverContext.php, tests/acceptance/features/bootstrap/AuthContext.php, tests/acceptance/features/bootstrap/ChecksumContext.php, tests/acceptance/features/bootstrap/FeatureContext.php, tests/acceptance/features/bootstrap/FilesVersionsContext.php, tests/acceptance/features/bootstrap/GraphContext.php, tests/acceptance/features/bootstrap/NotificationContext.php, tests/acceptance/features/bootstrap/OcisConfigContext.php, tests/acceptance/features/bootstrap/Provisioning.php, tests/acceptance/features/bootstrap/PublicWebDavContext.php, tests/acceptance/features/bootstrap/SearchContext.php, tests/acceptance/features/bootstrap/SettingsContext.php, tests/acceptance/features/bootstrap/Sharing.php, tests/acceptance/features/bootstrap/SharingNgContext.php, tests/acceptance/features/bootstrap/SpacesContext.php, tests/acceptance/features/bootstrap/SpacesTUSContext.php, tests/acceptance/features/bootstrap/TUSContext.php, tests/acceptance/features/bootstrap/TagContext.php, tests/acceptance/features/bootstrap/TrashbinContext.php, tests/acceptance/features/bootstrap/WebDav.php, tests/acceptance/features/bootstrap/WebDavLockingContext.php, tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Tidy up some things in the acceptance test code, such as:
- declare variables where the IDE thinks that they may not be set
- remove unused private vars in classes
- update PHPdoc of functions to match reality
- declare all parameter and return types
- fixup some Behat step functions that did not use some parameter(s). Mostly add `?:` in the step regex so that the not-needed item is not passed through as a parameter.
- use `print_r()` in cases where we are generating a test-failure message including something that might be an array.
- do not provide default values for private vars that already have their type declared (current PHP already provides those default values without needing to specify them)
- delete functions that are not used (I have only deleting the ones that are "obviously" …
=> [tests-only] code review of acceptance tests

tests/acceptance/features/apiSharingNg/removeAccessToDrive.feature, tests/acceptance/features/bootstrap/SharingNgContext.php
`Scenario: user cannot remove himself from the project space if he is the last manager`
`Scenario: user of a group cannot remove own group from project space if it is the last manager`
=> [test-only] user deletes own access of the space

services/frontend/pkg/command/events.go, services/graph/pkg/identity/cache.go, services/postprocessing/pkg/command/server.go, services/search/pkg/config/http.go, services/settings/pkg/command/server.go, services/sharing/pkg/command/server.go, services/storage-publiclink/pkg/command/server.go, services/storage-shares/pkg/command/server.go, services/storage-system/pkg/command/server.go, services/storage-users/pkg/command/server.go, services/thumbnails/pkg/command/server.go, services/userlog/pkg/command/server.go, services/users/pkg/command/server.go, services/web/pkg/command/server.go, services/webdav/pkg/command/server.go, services/webfinger/pkg/command/server.go
log and tracing related changes extracted from https://github.com/owncloud/ocis/pull/8909
=> log and trace fixes

services/ocm/README.md
* The correct name is not `providers.json`, but `ocmproviders.json`
* The trailing comma causes a syntax error during ocis startup: "error":"unable to register services: rgrpc: grpc service ocmproviderauthorizer could not be started,: invalid character ']' looking for beginning of value"
(The table in https://doc.owncloud.com/ocis/5.0/deployment/services/s-list/ocm.html#environment-variables has the name spelled with a hyphen (looks like `ocm-providers.json`) which is misleading, as it is just a soft-hyphen due to the narrow column, and the hyphen disappears during copy/paste. )
- test case 1:
- test case 2:
- ...
=> Fix: README.md ocmproviders.json example

changelog/unreleased/update-web-9.0.0.md
Fixes formatting of the web bump changelog item. A `## Summary` sneaked in which didn't belong there.
- Fixes https://github.com/owncloud/ocis/issues/8887
=> chore: fix web changelog formatting

tests/acceptance/config/behat.yml, tests/acceptance/features/apiAntivirus/antivirus.feature, tests/acceptance/features/bootstrap/FeatureContext.php, tests/acceptance/features/bootstrap/PublicWebDavContext.php
Changing `Given` statement of apiantivirus feature file to use graph api
- Part of  https://github.com/owncloud/ocis/issues/8717#event-12535134605
- locally
- CI
=> [tests-only][full-ci] changed given statement of sharing link in api antivirus feature file

tests/acceptance/features/apiSharingNg/sharedWithMe.feature
Added following scenarios:
```feature
Scenario: sharee lists the folder share after the sharer is disabled (Personal space)
Scenario: sharee lists the same name file and folder shares received from different projects (Project space)
```
- https://github.com/owncloud/ocis/issues/7826
=> [tests-only] extend list sharedwithme API tests coverage

tests/acceptance/features/apiGraphUserGroup/getGroup.feature, tests/acceptance/features/apiGraphUserGroup/getUser.feature
Added the following user/group search scenarios:
```feature
Scenario Outline: user searches for groups with special characters (search term with quotation)
| tea-lovers | -lovers |
| tea@lovers | @lovers |
| -_.ocgrp   | -_.     |
| _ocgrp@    | _oc     |
Scenario: user searches for a non-existent user/group
Scenario Outline: user searches for other users having special characters in displayname (search term with quotation)
| -_.ocusr         | -_.         |
| _ocusr@          | _oc         |
| Alice-Wonderland | -Wonderland |
| Alice@Wonderland | @Wonderland |
```
Taken from https://github.com/owncloud/web/pull/10858
- https://github.com/owncloud/web/issues/10259
=> [tests-only] add API tests to search user/group with special chars

deployments/examples/ocis_keycloak/config/ocis/csp.yaml, deployments/examples/ocis_keycloak/docker-compose.yml
ocis_keycloak deployment example doesn't work with current latest ocis because the PR #8777 has hardened some security.
This PR fixes the problem by adding custom `csp.yaml` file in the deployment example 
- https://github.com/owncloud/ocis/pull/8777
=> fix(deployment): keycloak blocked due to security violation in ocis_keycloak example

tests/acceptance/config/behat.yml, tests/acceptance/features/apiDownloads/download.feature, tests/acceptance/features/apiDownloads/spaceDownload.feature
Changed `Given` step for sharing space using SharingNg in 
- `apiDownloads/download.feature`
- `apiDownloads/spaceDownload.feature`
=> [tests-only] [full-ci] Change given step for sharing space in apiDownloads

changelog/unreleased/config-autoprovision-claims.md, services/proxy/pkg/command/server.go, services/proxy/pkg/config/config.go, services/proxy/pkg/config/defaults/defaultconfig.go, services/proxy/pkg/user/backend/cs3.go
We introduce the new environment variables "PROXY_AUTO_PROVISION_CLAIM_USERNAME", "PROXY_AUTO_PROVISION_CLAIM_EMAIL", and "PROXY_AUTO_PROVISION_CLAIM_DISPLAYNAME" which can be used to configure the OIDC claims that should be used for auto-provisioning user accounts.
The automatic fallback to use the 'email' claim value as the username when the 'preferred_username' claim is not set, has been removed.
Also it is now possible to autoprovision users without an email address
=> Autoprovsioning fixes

tests/acceptance/features/apiContract/sharesReport.feature
Changed `Given` step for share using SharingNg in `apiContract/sharesReport.feature` file.
=> [tests-only] [full-ci] Use sharingNG in given step for sharing in `sharesReport.feature` file

tests/TestHelpers/GraphHelper.php, tests/acceptance/features/apiSharingNg/sharedWithMe.feature, tests/acceptance/features/bootstrap/SharingNgContext.php
This PR adds test for sharingNg to hiding the shared resources shared from project and personal space
```feature
Scenario Outline: sharee hides the shared resource (Personal space)
Scenario Outline: sharee hides the shared resource (Project space)
Scenario Outline: sharee lists the shares after hiding (Personal space)
Scenario Outline: sharee lists the shares after hiding (Project space)
```
https://github.com/owncloud/ocis/issues/8888
=> [tests-only][full-ci]Added test for hide shared resources (personal and project space) in shares

.golangci.yml
- migrate setting skip-dirs to exclude-dirs - see https://github.com/golangci/golangci-lint/pull/4509
- tagalign linter sorts now according to our used order: yaml, env, desc, introductionVersion
=> test: fix linter tagalign to respect oCIS custom order + migrate skip-dirs to exclude-dirs

tests/TestHelpers/GraphHelper.php, tests/acceptance/features/apiSharingNg/shareInvitations.feature, tests/acceptance/features/apiSharingNg/updateShareInvitations.feature, tests/acceptance/features/bootstrap/SharingNgContext.php
This PR adds tests for updating expiration and role of shared project
- https://github.com/owncloud/ocis/issues/8810
- Locally
=> [tests-only][full-ci]Add tests for update shares using root endpoint

.drone.star
Currently only the nightly CI results are reported to the `builds` channel. Other results of merge CI etc. are reported to the `infinitescale` channel on https://talk.owncloud.com/channel/infinitescale
This PR makes all drone CI be reported to the `builds` channel.
That channel is already reviewed every morning, looking for "real" failures of CI for all the repos that report there. So the at-least-daily check of the `builds` channel will pick-up any recurring failures of ocis CI.
CI
=> chore: report all drone CI results to builds channel

changelog/unreleased/max-input-image.md, services/antivirus/pkg/config/config.go, services/thumbnails/pkg/config/config.go, services/thumbnails/pkg/config/defaults/defaultconfig.go, services/thumbnails/pkg/server/grpc/server.go, services/thumbnails/pkg/thumbnail/imgsource/cs3.go, services/thumbnails/pkg/thumbnail/imgsource/webdav.go
Yet another hardening around the thumbnail service.
- :hand:
=> feat: add maximum image file size to be processed by the thumbnailer

tests/acceptance/config/behat.yml, tests/acceptance/features/apiSpaces/changeSpaces.feature, tests/acceptance/features/apiSpaces/disableAndDeleteSpaces.feature, tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature, tests/acceptance/features/apiSpaces/filePreviews.feature, tests/acceptance/features/apiSpaces/listSpaces.feature, tests/acceptance/features/apiSpaces/publicLink.feature, tests/acceptance/features/apiSpaces/removeSpaceObjects.feature, tests/acceptance/features/bootstrap/PublicWebDavContext.php, tests/acceptance/features/bootstrap/SharingNgContext.php, tests/acceptance/features/bootstrap/SpacesContext.php
Changed `Given` step for sharing using SharingNg in apiSpaces:
- `changeSpaces.feature`
- `disableAndDeleteSpaces.feature`
- `editPublicLinkOfSpace.feature`
- `filePreviews.feature`
- `listSpaces.feature`
- `publicLink.feature`
- `removeSpaceObjects.feature`
=> [tests-only] [full-ci] Use sharing ng in api spaces

changelog/unreleased/fix-wopi-example.md, deployments/examples/ocis_wopi/docker-compose.yml
Fix the ocis wopi example after it was broken since https://github.com/owncloud/ocis/pull/8984
@DeepDiver1975 The appprovider-onlyoffice was starting a second ocis fullstack service and the service registry was used from the ocis container. This broke a lot of service registrations. The services from the app-provider were registered after the ones from the ocis container but the requests were routed to the ocis container while the "real services" were running in the app-provider container.
@wkloucek @d7oc Interesting. First accidental use of two full stack ocis servers side by side 😄 
Fixes: #3826 
- test case 1:
- test case 2:
- ...
=> fix: service startup appprovider onlyoffice

tests/TestHelpers/GraphHelper.php, tests/acceptance/features/apiSharingNg/linkShare.feature, tests/acceptance/features/bootstrap/SharingNgContext.php
This PR adds tests for setting password on share link
- https://github.com/owncloud/ocis/issues/8810
- Locally
=> [tests-only][full-ci]Add tests for setting password on share link

tests/acceptance/features/bootstrap/TrashbinContext.php, tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
Added more trashbin restore API tests
Taken from https://github.com/owncloud/web/pull/10890
- https://github.com/owncloud/web/issues/10259
- :computer:
=> [tests-only] extend trashbin restore API tests

tests/acceptance/features/apiSpaces/restoreSpaces.feature, tests/acceptance/features/apiSpaces/setQuota.feature, tests/acceptance/features/apiSpaces/tag.feature, tests/acceptance/features/apiSpaces/trashBin.feature, tests/acceptance/features/apiSpaces/tusUpload.feature, tests/acceptance/features/apiSpaces/uploadSpaces.feature
Changed `Given` step for sharing using SharingNg in apiSpaces:
- `restoreSpaces.feature`
- `setQuota.feature`
- `tag.feature`
- `trashBin.feature`
- `tusUpload.feature`
- `uploadSpaces.feature`
=> [tests-only] [full-ci] Use sharingNG in remaining feature file of apiSpaces folder

changelog/unreleased/nats-reconnects.md, ocis-pkg/natsjsregistry/registry.go
=> [stable-5.0] Fix nats reconnects

tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature, tests/acceptance/features/coreApiWebdavDelete/deleteFile.feature
Added more delete API tests for special character files
Taken from https://github.com/owncloud/web/pull/10889
- https://github.com/owncloud/web/issues/10259
=> [tests-only] extend delete API tests

changelog/unreleased/add-get-drive-item-endpoint.md, services/graph/mocks/drives_drive_item_provider.go, services/graph/pkg/service/v0/api_drives_drive_item.go, services/graph/pkg/service/v0/api_drives_drive_item_test.go, services/graph/pkg/service/v0/service.go
Adds an endpoint for getting drive items via ID.
- Fixes https://github.com/owncloud/ocis/issues/8915
=> enhancement: add get driveItem endpoint

.drone.env, changelog/unreleased/update-web-8.0.2.md, services/web/Makefile, tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
chore: bump ownCloud Web to v8.0.2
This is a bugfix release, most importantly fixing issues with the IDP logout page being shown.
=> [full-ci] chore: bump ownCloud Web to v8.0.2

.drone.star
This PR backports the e2e runner implementation from PR: https://github.com/owncloud/ocis/pull/8736 and PR https://github.com/owncloud/ocis/pull/8739
Part of: https://github.com/owncloud/ocis/issues/8794
=> [tests-only][full-ci] backport e2e runner implementation

tests/acceptance/features/apiSharingNg/sharedWithMe.feature
The expected JSON schema is adjusted in `apiSharingNg/sharedWithMe.feature`
- Fixes https://github.com/owncloud/ocis/issues/9159
- Locally
- :robot:
=> [full-ci] [tests-only] Adjusted the json schema

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpacesShares/shareSpaces.feature, tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature, tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature, tests/acceptance/features/bootstrap/Sharing.php, tests/acceptance/features/bootstrap/SpacesContext.php
- `apiSpacesShares/`
- `shareSpaces.feature`
- `shareSpacesViaLink.feature`
- `shareSubItemOfSpace.feature`
- Locally
- :robot:
=> [full-ci] [tests-only] Use sharing ng in given steps api spaces shares suite

tests/acceptance/features/apiSharingNg/listPermissions.feature, tests/acceptance/features/apiSharingNg/updateShareInvitations.feature, tests/acceptance/features/bootstrap/SharingNgContext.php
This PR has added tests for listing permission using `/drives/{driveID}/root/permissions` api endpoint. 
- https://github.com/owncloud/ocis/issues/8810
- locally
=> [tests-only][full-ci]extend list permission tests coverage for root endpoint

changelog/unreleased/enhancement-add-watermark-text.md, services/collaboration/pkg/connector/fileconnector.go, services/collaboration/pkg/connector/fileconnector_test.go
We've added the watermark text for the Secure View mode.
- Issue [https://github.com/owncloud/ocis/issues/9067](https://github.com/owncloud/ocis/issues/9067)
- test case 1:
- test case 2:
- ...
=> Added the watermark text for the Secure View mode

tests/acceptance/config/behat-core.yml, tests/acceptance/features/bootstrap/Sharing.php, tests/acceptance/features/coreApiShareOperationsToShares1/accessToShare.feature, tests/acceptance/features/coreApiShareOperationsToShares1/changingFilesShare.feature, tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature, tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesPendingFiltered.feature, tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFiltered.feature, tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFilteredEmpty.feature, tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFiltered.feature, tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFilteredEmpty.feature
Changed `Given` step for sharing using SharingNg in `coreApiShareOperationsToShares1`:
1. `accessToShare.feature`
2. `changingFilesShare.feature`
3. `gettingShares.feature`
4. `gettingSharesPendingFiltered.feature`
5. `gettingSharesReceivedFiltered.feature`
6. `gettingSharesReceivedFilteredEmpty.feature`
7. `gettingSharesSharedFiltered.feature`
8. `gettingSharesSharedFilteredEmpty.feature`
=> [tests-only] [full-ci] Use sharingNg in coreApiShareOperationsToShares1

tests/acceptance/config/behat-core.yml, tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/features/bootstrap/PublicWebDavContext.php, tests/acceptance/features/bootstrap/Sharing.php, tests/acceptance/features/bootstrap/WebDav.php, tests/acceptance/features/bootstrap/WebDavPropertiesContext.php, tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature, tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature, tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature, tests/acceptance/features/coreApiSharePublicLink1/deletePublicLinkShare.feature
- `coreApiSharePublicLink1/`
- `accessToPublicLinkShare.feature`
- `changingPublicLinkShare.feature`
- `createPublicLinkShare.feature`
- `deletePublicLinkShare.feature`
- Locally
- :robot:
=> [full-ci] [tests-only] Use `sharing-ng` in given steps for sharing

deployments/examples/ocis_wopi/.env, deployments/examples/ocis_wopi/docker-compose.yml
Adding a command plus comments in the ocis_wopi traefik section how to deal with the Letsencrypt staging environment.
This is important if we will create real certificates based on external resolvable URL's.
One needs to test the setup upfront obtaining real certificates as Letsencrypt has a narrow rate limit that last 1 week !!
Staging needs to be set actively, so we do not have any issues.
Such a setting is important for the easy entry docs for proper customer satisfaction.
Backport to 5.0 necessary
@tbsbdr fyi
(References: https://doc.traefik.io/traefik/user-guides/docker-compose/acme-dns/ this staging entry was found on many docs)
=> [docs-only] Update ocis_wopi docker-compose.yml --> add staging for letsencrypt

deployments/examples/ocis_wopi/.env, deployments/examples/ocis_wopi/docker-compose.yml
Backport of #9172 ([docs-only] Update ocis_wopi docker-compose.yml --> add staging for letsencrypt)
The backport is necessary for our easy entry docs.
=> [docs-only] Backport of #9172 (add staging for letsencrypt in ocis_wopi)

changelog/unreleased/csp.md, deployments/examples/ocis_wopi/config/ocis/csp.yaml, services/proxy/pkg/config/csp.yaml, tests/acceptance/features/coreApiWebdavOperations/downloadFile.feature, tests/parallelDeployAcceptance/features/apiWebdavOperations/downloadFile.feature
When refreshing the oidc client loads ocis in an iframe - which was disallowed until this fix.
- Fixes #9163 
- cd deployment/example/ocis_wopi
- docker compose up
- xdg-open https://ocis.owncloud.test/
- login
- open developer console in browser
- wait 5m
- see token expiring and being refreshed
- observe to stay logged in
=> fix: token refresh in single binary and wopi deployment example

tests/acceptance/config/behat-core.yml, tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature, tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature, tests/acceptance/features/coreApiWebdavEtagPropagation2/copyFileFolder.feature, tests/acceptance/features/coreApiWebdavEtagPropagation2/createFolder.feature, tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature
- `coreApiWebdavEtagPropagation1/`
- `deleteFileFolder.feature`
- `moveFileFolder.feature`
- `coreApiWebdavEtagPropagation1/` 
- `copyFileFolder.feature`
- `createFolder.feature`
- `upload.feature`
- Locally
- :robot:
=> [full-ci] [tests-only] Use sharing-ng in given steps for sharing

tests/acceptance/config/behat-core.yml, tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature, tests/acceptance/features/coreApiShareUpdateToShares/updateShareGroupAndUserWithSameName.feature
Used sharingNG in given steps for sharing.
- `coreApiShareUpdateToShares/updateShare.feature`
- Locally
- :robot:
=> [tests-only] [full-ci] Update given step using sharingNg in coreApiShareUpdateToShares

tests/acceptance/features/bootstrap/SpacesContext.php
removing the use of a stepdefinition inside another stepdefinition in SpacesContext.php
- Part of https://github.com/owncloud/ocis/issues/8199
- test case 1: locally
- test case 2: ci
=> [tests-only][full-ci] removing the usage of a stepDefinition inside another stepDefinition in SpacesContext.php

services/collaboration/pkg/connector/contentconnector.go, services/collaboration/pkg/connector/contentconnector_test.go, services/collaboration/pkg/middleware/wopicontext.go, services/collaboration/pkg/service/grpc/v0/service.go
make use of https://github.com/cs3org/reva/pull/4686
=> try using viewOnlyToken to download file if available

changelog/unreleased/thumbnail-request-limit.md, ocis-pkg/middleware/throttle.go, services/thumbnails/README.md, services/thumbnails/pkg/command/server.go, services/thumbnails/pkg/config/defaults/defaultconfig.go, services/thumbnails/pkg/config/http.go, services/thumbnails/pkg/server/http/option.go, services/thumbnails/pkg/server/http/server.go, services/thumbnails/pkg/service/http/v0/service.go, services/webdav/pkg/service/v0/search.go, services/webdav/pkg/service/v0/service.go
Creating thumbnails can be quite intensive with respect to memory and cpu consumption.
Limiting the number of concurrent requests can help to relax this situation.
In case a request is rejected `429/Too Many Requests` will be returned and clients can retry later.
Make OCIS/ByCS robust ...
- set `THUMBNAILS_MAX_CONCURRENT_REQUESTS` to 1
- upload a lot of pictures
- see 429 on some of the thumbnail requests
- to fully enforce this: place a sleep in https://github.com/owncloud/ocis/pull/9199/files#diff-a9a24a55f3b593d160f93b1d5488f9328ecb4beae99f60ecd098807bcf9e707aR94
=> feat: limit concurrent processing of thumbnail requests

changelog/unreleased/update-storage-users-doc.md, services/storage-users/README.md
- test case 1:
- test case 2:
- ...
=> [docs-only]  added the details to the 'Restore Trash-Bins Items' doc section'

tests/acceptance/features/bootstrap/Sharing.php
removing the use of a stepdefinition inside another stepdefinition in Sharing.php
- Part of https://github.com/owncloud/ocis/issues/8199
- test case 1:locally
- test case 2:ci
=> [tests-only][full-ci] removing the usage of a stepdef inside another stepdef in Sharing.php

changelog/unreleased/enhanacement-clamav-example.md, deployments/examples/ocis_clamav/README.md, deployments/examples/ocis_clamav/docker-compose.yml, docs/ocis/deployment/ocis_clamav.md
add example to demonstrate how to use of clamav as virus scanner
=> enhancement: add clamav docker compose example

tests/acceptance/config/behat-core.yml, tests/acceptance/features/bootstrap/SharingNgContext.php, tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature, tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature, tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature, tests/acceptance/features/coreApiSharePublicLink1/deletePublicLinkShare.feature, tests/acceptance/features/coreApiSharePublicLink2/multilinkSharing.feature, tests/acceptance/features/coreApiSharePublicLink2/updatePublicLinkShare.feature, tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature, tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature, tests/acceptance/features/coreApiVersions/fileVersions.feature, tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature, tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature, tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature, tests/acceptance/features/coreApiWebdavOperations/propfind.feature, tests/acceptance/features/coreApiWebdavProperties/getFileProperties.feature
skipping test on reva related to created link share as graph is not implemented in Reva edge.
Reva edge bump: https://github.com/cs3org/reva/pull/4682
- locally
- CI
=> [tests-only][full-ci] adding skip-on-reva tag for test related to sharing link

docs/ocis/adr/0028-activities-service.md
Adds ADR for the new activities service, please add your thoughts below.
Fixes https://github.com/owncloud/ocis/issues/9075
=> [docs-only] enhancement(docs): first draft of the activities service adr

services/graph/pkg/config/defaults/defaultconfig.go, services/graph/pkg/server/http/server.go, services/invitations/pkg/config/defaults/defaultconfig.go, services/proxy/pkg/config/defaults/defaultconfig.go, services/sse/pkg/server/http/server.go, services/userlog/pkg/config/defaults/defaultconfig.go, services/userlog/pkg/server/http/server.go, services/web/pkg/server/http/server.go
we did not always stick to the correct service name pattern:
* http services should live in the `com.owncloud.web` namespace
* grpc services should live in the `com.owncloud.api` namespace
* we could add a `com.owncloud.debug` namespace for all the debug ports ... (not part of this pr)
it seems the userlog code got copy pasted into several services ...
We need to add a changelog for this and maybe add the env vars to the helmchart in case someone intends to mix versions ...
=> fix service names for userlog, graph, invitations, sse and web

docs/ocis/backup.md
Adds documentation about ocis base data structure and backup possibilities.
Fixes https://github.com/owncloud/ocis/issues/9005
=> [docs-only] Backup Docs

services/proxy/pkg/user/backend/cs3.go
This is a fixup for commit 799b12b8dda00d860ad91a7143a8e06b2096d218 adjusting the service name of the graph service to the new value.
Closes: #9258
=> fix(autoprovision): fixup the service name of the graph service

changelog/unreleased/tokenInfo-endpoint-replacement.md, services/proxy/pkg/command/server.go, services/proxy/pkg/middleware/authentication_test.go, services/proxy/pkg/middleware/basic_auth.go, services/proxy/pkg/middleware/oidc_auth.go, services/proxy/pkg/middleware/oidc_auth_test.go, services/proxy/pkg/middleware/public_share_auth.go
[https://github.com/owncloud/ocis/issues/8858](https://github.com/owncloud/ocis/issues/8858)
- test case 1:
- test case 2:
- ...
=> [full-ci] [bump-reva] Replacement for TokenInfo endpoint

changelog/unreleased/enhancement-web-server-compression.md, services/web/pkg/server/http/server.go
Adds a compression middleware to the web server to reduce the request size when delivering static files. This speeds up loading times in web clients.
The chi middleware we're using for this currently supports `gzip` as compression algorithm. We might want to extend this to support `br` (Brotli) in the future, since it's a newer and more performant algorithm. But for now, any compression is a big step up.
- refs https://github.com/owncloud/web/issues/7964
=> feat: web server compression

services/thumbnails/README.md
References: #9199 (feat: limit concurrent processing of thumbnail requests)
Content fix:
- If NO thumbnail is available, we return 404 (and not if it is avaialble)
- Make the resolution list multi-lined again for improved readbility
=> [docs-only] Update thumbnails README.md

services/storage-users/README.md
References: #9228 ([docs-only] added the details to the 'Restore Trash-Bins Items' doc section')
Aligning one list item of `Example cases for expired uploads` to the admin docs.
The original sentence was confusing.
=> [docs-only] Update storage-users README.md

services/storage-users/README.md, services/thumbnails/README.md
There are two service readme's that need some fixing:
* thumbnail:
One linebreak added was too much -> removed
(if there is no connsecutive follow up line, the line break character will be printed as it is)
* storage-users:
Link fixes, text fixes, render fixes
Rendered locally, looks fine.
=> [docs-only] fix two service readme's

tests/acceptance/features/apiSharingNgLinkShare/linkShare.feature
This PR add tests coverage for share-ng endpoint to update share link of a folder in project-space using permissions endpoint.
```feature
Scenario Outline: update link share of a folder inside project-space using permissions endpoint
```
- Related to: https://github.com/owncloud/ocis/issues/9046
- locally
=> [tests-only][full-ci]Add test for updating link of a folder in project-space using permissions endpoint.

tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/features/bootstrap/WebDav.php, tests/acceptance/features/coreApiAuth/webDavSpecialURLs.feature
The issue was about test scenarios that send various unusual combinations of paths in the URL that have multiple `/` characters together - sending paths like `/remote.php//dav/spacessomeSpaceId/textfile1.txt`
Previously some of these were "crashing" the server and returning 5xx HTTP status codes. But that has been fixed "some time ago". The test scenarios had expectations for various 2xx and 4xx status codes, but the actual exact codes that are returned are a bit different from what was put in the tests. This PR adjusts the expected codes so that they match what really happens.
There are different codes like 200, 201, 204, 400, 404, 412 etc. because these kind of requests are, in a sense, all invalid. But it is also easy for a human to see what is intended by each request, and some server …
=> [tests-only] test: adjust tests related to issue 1667

changelog/unreleased/prevent-thumbnailer-from-showing-secureview-previews.md, services/thumbnails/pkg/service/grpc/v0/service.go, services/webdav/pkg/service/v0/service.go
Bugfix: Don't show thumbnails for secureview shares.
We have fixed a bug where thumbnails were shown for secureview shares.
refs https://github.com/owncloud/ocis/issues/9249
=> Thumbnailer respect secure view

services/thumbnails/README.md
Referencing: owncloud/ocis#9299 (Thumbnailer respect secure view)
Adding a short sentence about the thumbnail behavior when using SecureView.
=> [docs-only] Update thumbnail README.md with respect to SecureView

services/graph/mocks/role_service.go, services/graph/pkg/service/v0/users.go, services/graph/pkg/service/v0/users_filter.go, services/graph/pkg/service/v0/users_test.go
This addresses some low hanging fruits for improving the GetUsers call when filtering users by role-assignment (and expanding the assignments).
The first commit avoids a lot of extra queries to the settings service when `$expand=appRoleAssignment` is used together with filtering.
The second commit switch the filtering code to use the new ListRoleAssignmentsFiltered request in the settings service. Reducing the number of queries to the settings service to a single request. (Orignally it was one per existing user + one per user that matched the filter).
On my system with 1000 users (external LDAP) assigned to the `User` role and the metadata service using and NFS volume the query time for: `$filter=(appRoleAssignments/any(m:m/appRoleId eq …
=> graph: Small improvments for filtering users by role

tests/acceptance/features/apiSharingNgLinkShare/linkShare.feature
This PR add tests coverage for share-ng endpoint to update share link of a resource in project-space
```feature
Scenario Outline: update role of a folder's link share inside project-space using permissions endpoint
Scenario Outline: update role of a file's link share inside a project-space using permissions endpoint
Scenario Outline: update role of a file's link share to internal inside a project-space using permissions endpoint
Scenario Outline: update role of a folder's link share to internal inside project-space using permissions endpoint
```
- Related to : https://github.com/owncloud/ocis/issues/9046
- locally
=> [tests-only][full-CI] adding test for updating share link of a resource in project space.

tests/acceptance/features/bootstrap/WebDav.php, tests/acceptance/features/coreApiAuth/webDavSpecialURLs.feature
These test scenarios in `webDavSpecialURLs.feature` were recently updated to specify the actual HTTP status codes that are returned by oCIS. But when we run these scenarios on reva we get slightly different HTTP status codes.
These are tests for unusual edge-case calls to end-points, using double-slash in unexpected parts of the URL. The main thing is that these unusual cases do not "crash" the server, and they do return "some reasonable response". If oCIS and reva are a little different then it does not really matter.
A new step definition has been added that allows us to specify the HTTP status codes expected on oCIS and on reva as separate/different lists. That step definition is used in the tests to specify what we observe as the current behavior on oCIS and reva.
This problem was …
=> test: check for status codes that are different on oCIS and reva

Makefile, changelog/unreleased/activity-service.md, docs/services/general-info/port-ranges.md, ocis-pkg/config/config.go, ocis-pkg/config/defaultconfig.go, ocis/pkg/command/services.go, ocis/pkg/init/init.go, ocis/pkg/runtime/service/service.go, services/activitylog/Makefile, services/activitylog/README.md, services/activitylog/cmd/activitylog/main.go, services/activitylog/pkg/command/health.go, services/activitylog/pkg/command/root.go, services/activitylog/pkg/command/server.go, services/activitylog/pkg/command/version.go, services/activitylog/pkg/config/config.go, services/activitylog/pkg/config/debug.go, services/activitylog/pkg/config/defaults/defaultconfig.go, services/activitylog/pkg/config/log.go, services/activitylog/pkg/config/parser/parse.go, services/activitylog/pkg/config/serviceconfig.go, services/activitylog/pkg/config/tracing.go, services/activitylog/pkg/logging/logging.go, services/activitylog/pkg/metrics/metrics.go, services/activitylog/pkg/service/options.go, services/activitylog/pkg/service/service.go, services/activitylog/pkg/service/service_test.go
Adds the activitylog service. As of now it only stores activities. Retrieving them comes with https://github.com/owncloud/ocis/issues/9196
For more info see also the ADR: https://owncloud.dev/ocis/adr/0028-activities-service/
Fixes https://github.com/owncloud/ocis/issues/9195
=> Activitylog Service

changelog/unreleased/max-input-image.md, services/thumbnails/pkg/config/defaults/defaultconfig.go
Thumbnail max input width and height need to be the same, because images can be portrait or landscape.
- Fixes https://github.com/owncloud/ocis/issues/9234
=> fix: thumbnail max input height

.drone.star, changelog/unreleased/add-consistency-check-command.md, docs/ocis/backup.md, ocis/pkg/backup/backup.go, ocis/pkg/backup/backup_test.go, ocis/pkg/backup/provider.go, ocis/pkg/command/backup.go
Adds consistency check command
Fixes https://github.com/owncloud/ocis/issues/9004
E2E testing needs additional ticket: https://github.com/owncloud/ocis/issues/9286
=> Add command to check ocis backup consistency

.drone.env, changelog/unreleased/update-web-9.0.0.md, services/web/Makefile
bumping `web` to `v9.0.0-alpha.7`
=> [full-ci] chore: bump web to v9.0.0-alpha.7

changelog/unreleased/natsjskv-registry-encoding.md, ocis-pkg/natsjsregistry/registry.go
Encodes natsjskv registry keys
Fixes https://github.com/owncloud/ocis/issues/9382
=> Encode registry keys

.drone.star, ocis/docker/manifest.production.tmpl, ocis/docker/manifest.tmpl
This is a POC for deploying docker and binary build artifacts according to https://github.com/owncloud/ocis/issues/9264.
**What is known:**
- Production release docker tags: `owncloud/ocis:x.x.x`
- Rolling release docker tags: `owncloud/ocis-rolling:x.x.x` _(including production tags)_
- Production binary builds go to: `stable` subfolder
- Rolling binary builds go to: `rolling` subfolder
- Daily binary builds go to: `daily` subfolder
**Q?:**
- What kind of builds go to `testing` subfolder? Pre-releases - alpha, beta, rc?
- Docker tag for daily builds? `owncloud/ocis-rolling:latest`?
- What should happen to previous docker tags and binary builds? (move to respective docker repo and binary subfolders?) - not related to this PR though
**PR implementation:** tag release type from …
=> [ci] upload artifacts of production, rolling or daily

docs/architecture/joint-access-storage-driver.md, docs/architecture/posixfs.md
This documentation should explain technical background, design options and opportunities and show how to set up at this stage.
Later, the setup section might be moved to other area of doc.
@aduffeck @mmattel @hodyroff
=> [docs-only] Dev docs about collaborative storage

changelog/unreleased/fix-search-hidden.md, services/search/pkg/search/service.go, services/search/pkg/search/service_test.go
The hidden shares have been excluded from a search result.
- Fixes [7383](https://github.com/owncloud/ocis/issues/7383)
- test case 1:
- test case 2:
- ...
=> The hidden shares have been excluded from a search result

.drone.star, ocis/docker/manifest-latest.tmpl, ocis/docker/manifest.production-latest.tmpl
- Change `latest` docker to point to the "latest stable tag"
- Introduce `master` tag for  `owncloud/ocis-rolling` for the builds from the master branch.
- test case 1:
- test case 2:
- ...
=> ci: use latest docker for tags and add master tag

.drone.star
improvement of #9400 to avoid building `latest` tag on pre-releases 
`drone starlark --build.ref "refs/tags/v5.0.0" --repo.slug "owncloud/ocis" --build.event "tag" --max-execution-steps=10000000000 --format`
`drone starlark --build.ref "refs/tags/v5.0.0-alpha.1" --repo.slug "owncloud/ocis" --build.event "tag" --max-execution-steps=10000000000 --format`
=> ci: do not build "latest" docker tag on prerelease

tests/acceptance/features/apiSpaces/filePreviews.feature, tests/acceptance/features/apiSpacesShares/shareOperations.feature
This PR adds scenario to download files shared via secure viewer role.
```feature
Scenario Outline: download preview of shared file shared via Secure viewer permission role
Scenario: sharee cannot download file shared with Secure viewer permission by share
Scenario: sharee cannot download file inside folder shared with Secure viewer permission by sharee
```
- Part of https://github.com/owncloud/ocis/issues/9334
=> [tests-only][full-ci] downloading file shared via secure view role

deployments/examples/ocis_keycloak/config/keycloak/clients/android_app.json, deployments/examples/ocis_keycloak/config/keycloak/clients/cyberduck.json, deployments/examples/ocis_keycloak/config/keycloak/clients/desktop_client.json, deployments/examples/ocis_keycloak/config/keycloak/clients/ios_app.json, deployments/examples/ocis_keycloak/config/keycloak/clients/web.json, deployments/examples/ocis_keycloak/config/keycloak/ocis-realm.dist.json, deployments/examples/ocis_keycloak/docker-compose.yml
In preparation to implement #5538 this PR bumps keycloak to the latest release and also add out demo groups to the configuration and assign the demo users accordingly. The client configs are update to now return the "groups" claim by default.
For ease of reviewing the detailed config changes the first commit just prettifies/normalizes the JSON files (using `jq .` ).
So the real changes are in the last two commits.
=> keycloak example: Bump keycloak to 25.0.0. and add demo groups

tests/acceptance/features/apiSharingNg/listPermissions.feature, tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
Here following test coverage scenario is added for the issue-9151
```feature
Scenario: non-member user tries to list the permissions of a project space using root endpoint
```
Also, there is added of issue tag which was removed in the PR https://github.com/owncloud/ocis/pull/9331/files
- Related: https://github.com/owncloud/ocis/issues/8428 and https://github.com/owncloud/ocis/issues/9151
- ci
- locally
=> [tests-only][full-ci] add test coverage for list permission for non-member user in project-space

.drone.star, tests/TestHelpers/OcmHelper.php, tests/acceptance/config/behat.yml, tests/acceptance/features/apiOcm/ocm.feature, tests/acceptance/features/bootstrap/OcmContext.php, tests/config/drone/providers.json
related #1329
how to start two ocis instances:
- create providers.json file:
<details>
<summary>  providers.json </summary>
```
[
{
"name": "localhost:9200",
"full_name": "Local",
"organization": "Owncloud",
"domain": "localhost",
"homepage": "https://owncloud.com",
"services": [
{
"endpoint": {
"type": {
"name": "OCM",
"description": "CERNBox Open Cloud Mesh API"
},
"name": "CERNBox - OCM API",
"path": "https://localhost:9200/ocm/",
"is_monitored": true
},
"api_version": "0.0.1",
"host": "localhost:9200"
}
]
},
{
"name": "anotherlocalhost:10200",
"full_name": "Local 10200",
"organization": "Owncloud",
"domain": "anotherlocalhost",
"homepage": "https://owncloud.com",
"services": [
{
"endpoint": {
"type": {
"name": "OCM",
"description": "CERNBox Open Cloud Mesh API"
},
"name": "CERNBox - …
```
=> [full-ci]first api test for ocm

tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
This PR updates the previous scenarios regarding sharee trying to move file/folder within the shared folder with permission secure view too.
Scenario Updated:
```feature
Scenario: receiver tries to rename a received share with read permissions inside the Shares folder
```
- Part of: https://github.com/owncloud/ocis/issues/9334
- Locally
- CI
=> [tests-only][full-ci] extend test for trying to move file/folder within shared folder with secure view role

tests/acceptance/features/bootstrap/SpacesContext.php
This PR fixes the issue to check status code where getStatusCode() returns an int and addCreatedSpace() was not being called.
- Related to : https://github.com/owncloud/ocis/issues/9341
- locally
=> [full-ci][tests-only] fix status code check in theUserCreatesASpaceWithQuotaUsingTheGraphApi in SpacesContext

.drone.env, changelog/unreleased/update-web-8.0.3.md, services/web/Makefile
This is a bugfix release, please see the changelog for more details:
- Bugfix [owncloud/web#10814](https://github.com/owncloud/web/issues/10814): Vertical scroll for OcModal on small screens
- Bugfix [owncloud/web#10918](https://github.com/owncloud/web/issues/10918): Resource deselection on right-click
- Bugfix [owncloud/web#10920](https://github.com/owncloud/web/pull/10920): Resources with name consist of number won't show up in trash bin
- Bugfix [owncloud/web#10941](https://github.com/owncloud/web/issues/10941): Space not updating on navigation
- Bugfix [owncloud/web#11063](https://github.com/owncloud/web/issues/11063): Enforce shortcut URL protocol
=> [full-ci] chore: bump ownCloud Web to v8.0.3

changelog/unreleased/fix-sharingng-permission-listings.md, services/graph/pkg/service/v0/api_driveitem_permissions.go, services/graph/pkg/service/v0/drives.go, services/graph/pkg/service/v0/educationuser.go, services/graph/pkg/service/v0/users.go, services/graph/pkg/service/v0/utils.go, tests/acceptance/features/apiSharingNg/listPermissions.feature
This PR fixes an issue where the sharing-ng service was not able to list permissions for personal and virtual drive items.
- Fixes https://github.com/owncloud/ocis/issues/8922
- acceptance tests
=> fix(sharing-ng): permission listings for personal and virtual drive items

changelog/unreleased/consistency-fail-flag.md, ocis/pkg/backup/backup.go, ocis/pkg/command/backup.go
Adds a `--fail` flag to the ocis consistency command. If set to true, the command will return a non-zero exit code if any inconsistencies are found.
Fixes https://github.com/owncloud/ocis/issues/9411
=> Add `--fail` flag to consistency command

tests/acceptance/features/bootstrap/SharingNgContext.php, tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature, tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
The test failure in `coreApiShareManagementToShares/moveReceivedShare.feature:172` was mostly due to the share being unavailable to the receiver in time. Since the sharing/accepting-share is an async task, we couldn't come up with the better solution for waiting for the shares to be accepted during the share creation step. So, added a Given step which waits for the share to be synced.
Usage:
```feature
Given user "Alice" has sent the following resource share invitation:
| resource        | TMP      |
| space           | Personal |
| sharee          | grp1     |
| shareType       | group    |
| permissionsRole | Viewer   |
And user "Carol" has a share "/TMP" synced
When user "Carol" moves folder "/Shares/TMP" to "/Shares/new" using the WebDAV API
```
- trying to fix …
=> [tests-only] add a Given step to check for the share sync status

changelog/unreleased/deprecate-gateway-envvars.md, services/clientlog/pkg/config/config.go, services/collaboration/pkg/config/cs3api.go
Deprecates service specific gateway envvars for simplicity.
Fixes https://github.com/owncloud/ocis/issues/9332
=> [docs-only] Deprecate gateway envvars

services/clientlog/pkg/config/config.go, services/collaboration/pkg/config/cs3api.go
References: #9452 ([docs-only] Deprecate gateway envvars)
1. There was a typo in the deprecation note
2. Harmonizing the envvar text in the collaboration service to align with the others.
=> [docs-only] Fix envvar description

changelog/unreleased/index-all-spaces.md, ocis-pkg/kql/dictionary_gen.go, services/search/pkg/command/index.go, services/search/pkg/search/debouncer.go, services/search/pkg/search/debouncer_test.go, services/search/pkg/search/events.go, services/search/pkg/search/mocks/searcher.go, services/search/pkg/search/service.go, services/search/pkg/search/service_test.go, services/search/pkg/service/grpc/v0/service.go
Allows reindexing all spaces with one command. Also removes the redundant `uid` parameter from search service
Fixes https://github.com/owncloud/ocis/issues/9103
=> Allow reindexing all spaces

changelog/unreleased/harden-postprocessing-restart.md, services/postprocessing/pkg/service/service.go
Restarts all requested uploads even if one fails.
Fixes https://github.com/owncloud/enterprise/issues/6690
=> Fix bulk postprocessing restart

changelog/unreleased/activitylog-fixes.md, services/activitylog/pkg/command/server.go, services/activitylog/pkg/service/http.go, services/activitylog/pkg/service/response.go, services/activitylog/pkg/service/service.go
Fixes multiple small activitylog issues:
* understand ids of format `uuid1$uuid2`
* return an empty list instead of null when there are no activities.
* return messages even if resource/user/space got removed meanwhile
* delete the document from the store when the corresponding item is purged
* allow sorting result `"asc"` (default) or `"desc"` using the `"sort"` kql parameter
=> Activitylog fixes

changelog/unreleased/fix-dockerfile-for-posixfs.md, ocis/docker/Dockerfile.linux.amd64, ocis/docker/Dockerfile.linux.arm64
add bash and inotify-wait to the docker files of ocis, needed for posixfs
=> Fix docker files

changelog/unreleased/activitylog-fixes.md, services/activitylog/pkg/service/http.go, services/activitylog/pkg/service/response.go
Adds the space even if it can't get the resource because it was deleted.
=> Activitylog Spaces

tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature, tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
wait and check for sync status before performing the action
- Fixes https://github.com/owncloud/ocis/issues/9428#issuecomment-2186879551
Reduce test flakiness
=> [tests-only][full-ci] wait and check for sync status before action

changelog/unreleased/empty-trash-dirs.md, ocis/pkg/command/trash.go, ocis/pkg/trash/trash.go
This PR adds a cli command that allows purging empty dirs in trash folder structures.
refs #9271 
refs #9393
=> Delete empty trash dirs

deployments/examples/ocis_wopi/.env, deployments/examples/ocis_wopi/README.md
This are small fixes to the .env file:
* `latest` does not point to 5.0.5 as rolling was introduced with 6.
If we write that text, we confuse users and the wrong version (master) gets used. Note we are on stable5.
For master, the text including latest, if it points to the latest production version, would be correct.
* Companion is optional and not included in the minimal deployment, see readme.
* Removing some blanks as those are not ordinary comments but commented commands. Same as we do with other commented commands.
* Backtick corrections in the readme file.
=> Fix ocis wopi env settings

.drone.env, changelog/unreleased/update-web-8.0.4.md, services/web/Makefile
- Bugfix [owncloud/web#11092](https://github.com/owncloud/web/issues/11092): Browser confirmation dialog after closing editor
- Bugfix [owncloud/web#11091](https://github.com/owncloud/web/issues/11091): Button focus when closing editor
- Bugfix [owncloud/web#10942](https://github.com/owncloud/web/issues/10942): Keyboard navigation breaking
- Bugfix [owncloud/web#11086](https://github.com/owncloud/web/pull/11086): Opening public links with an expired token
=> [full-ci] chore: bump ownCloud Web to v8.0.4

.drone.star, changelog/unreleased/fix-secure-view.md, services/collaboration/pkg/helpers/discovery.go, services/collaboration/pkg/service/grpc/v0/service.go, services/graph/pkg/unifiedrole/unifiedrole.go, services/graph/pkg/unifiedrole/unifiedrole_test.go, tests/acceptance/features/apiSharingNg/listPermissions.feature
Polish Secure view
1. Fix `view_comment` mode for pdfs - needed for Secure Viewable PDF files
2. Remove the secure viewer role from space roots.
- Fixes #9392 
- test case 1:
- test case 2:
- ...
=> fix: polish secure view

tests/TestHelpers/HttpRequestHelper.php, tests/TestHelpers/SettingsHelper.php, tests/acceptance/features/apiSharingNg/sharedWithMe.feature, tests/acceptance/features/bootstrap/FeatureContext.php, tests/acceptance/features/bootstrap/GraphContext.php, tests/acceptance/features/bootstrap/NotificationContext.php, tests/acceptance/features/bootstrap/OCSContext.php, tests/acceptance/features/bootstrap/SettingsContext.php, tests/acceptance/features/bootstrap/SharingNgContext.php
Implemented retry when listing the shares if auto-sync is enabled but client.synchronize is false. If the auto-sync is disabled then the retry will be skipped.
Scenarios can pass with retry:
```feature
When user "Brian" lists the shares shared with him using the Graph API
│ auto-sync share for user 'Brian' is enabled
│ but share 'textfile0.txt' was not auto-synced, retrying (1)...
│ 
Then the HTTP status code should be "200"
```
- Revert https://github.com/owncloud/ocis/commit/4e66cc730e633cd3ff3dac787e9bd5f92c0b7224
- Fixes #8864, Fixes #8859
=> [tests-only] retry if auto-sync is enabled but client.synchronize is false

services/storage-users/pkg/config/config.go, services/storage-users/pkg/config/defaults/defaultconfig.go, services/storage-users/pkg/revaconfig/config.go, services/storage-users/pkg/revaconfig/drivers.go, services/storage-users/pkg/revaconfig/user.go
This PR adapts to the latest reva changes and fixes the config so that `posixfs` can emit events. It also enables async uploads by default as we also do with the `ocis` driver.
Depends on https://github.com/cs3org/reva/pull/4739
=> Fix posixfs events

changelog/unreleased/remove-revisions-cli.md, ocis/README.md, ocis/pkg/command/revisions.go, ocis/pkg/revisions/revisions.go
Adds a cli to remove revisions:
```
ocis revisions purge
```
Fixes https://github.com/owncloud/ocis/issues/9472
=> Purge-Revision Cli

changelog/unreleased/autoprovsion-groups.md, services/proxy/README.md, services/proxy/pkg/config/config.go, services/proxy/pkg/config/defaults/defaultconfig.go, services/proxy/pkg/middleware/account_resolver.go, services/proxy/pkg/user/backend/backend.go, services/proxy/pkg/user/backend/cs3.go
Requires: https://github.com/cs3org/reva/pull/4738 :heavy_check_mark: 
- ~~groupmembership are not deleted yet~~
- ~~config knobs for the group claim are missing~~ 
- ~~The sync process is currently triggered with every single request, we need to limit this to e.g. once per accesstoken lifetime (or once per userinfo cache ttl)~~
- ~~documentation is missing~~
To avoid syncing group memberships with every single incoming request I add a small ttl based cache that keeps track of when group memberships were last updated for a specific user. Currently the ttl is hardcode to 1 minute, I am still pondering whether to turn that into a configuration option.
=> autoprovisioning: Manage group memberships

docs/helpers/env_vars.yaml
References: #9361 (Activity API)
After #9361 was merged, we need to update the helper yaml file to show correct values in docs.
=> [docs-only] update env_vars.yaml post Activitylog API merge

tests/acceptance/features/bootstrap/WebDav.php, tests/acceptance/features/coreApiWebdavUploadTUS/uploadFile.feature
Added API tests for trying to create TUS upload with path `..`.
- Coverage: https://github.com/owncloud/ocis/issues/1002
=> [tests-only][full-ci] add TUS upload API test for invalid ".." path

services/app-provider/pkg/config/defaults/defaultconfig.go
The external service address is used to look up the service in the registry. So we can set this to a better default than emptystring.
=> set correct default external service address

tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/features/coreApiWebdavProperties/getFileProperties.feature
The tests extended to cover PROPFIND shared file by sharer.
- Part of https://github.com/owncloud/ocis/issues/9119
- Locally
- :robot:
=> [full-ci][tests-only] Extended the tests to cover profind by sharer to shared file

.drone.star, changelog/unreleased/remove-revisions-cli.md, ocis/README.md, ocis/pkg/command/revisions.go, ocis/pkg/revisions/revisions.go
This is a backport of #9497 
refs #9552
=> Backport purge revision to 5.0.5

tests/acceptance/features/bootstrap/CliContext.php, tests/acceptance/features/cliCommands/resetUserPassword.feature
Adding test scenario for changing password of non existing user via cli
- Part of https://github.com/owncloud/ocis/issues/9529
-  locally and CI
=> [tests-only][full-ci] added cli test for changing password of non-existing user

.drone.env, changelog/unreleased/update-web-9.2.0.md, services/web/Makefile
bumping web to pre-release `v9.2.0-alpha.1`
=> [full-ci] chore: bump web to v9.2.0-alpha.1

docs/services/general-info/added-services.md
This PR adds a page to dev docs to describe which services are available / been added per release.
We have a similar page in the [admin docs](https://doc.owncloud.com/ocis/next/deployment/services/services.html).
=> [docs-only] Add page to dev docs with services per release

changelog/unreleased/missing-wopi-keys.md, services/app-provider/pkg/config/config.go, services/collaboration/pkg/config/wopi.go, services/collaboration/pkg/connector/contentconnector.go, services/collaboration/pkg/connector/contentconnector_test.go, services/collaboration/pkg/connector/fileconnector.go, services/collaboration/pkg/connector/fileconnector_test.go, services/collaboration/pkg/middleware/wopicontext.go, services/collaboration/pkg/service/grpc/v0/service.go, services/collaboration/pkg/service/grpc/v0/service_test.go
Implementation of #9398 
Related to #6540 (which was used in the former reva app provider)
https://learn.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/online/discovery#ui_llcc
https://api.onlyoffice.com/editors/wopi/discovery#ui
https://api.onlyoffice.com/editors/wopi/discovery#lang
https://sdk.collaboraonline.com/docs/advanced_integration.html#url-query-parameters
- ✅ Disable Chat in `ocis_full` example with onlyoffice
- ✅  Change Language in `ocis_full` example with onlyoffice
- ✅  Change Language in `ocis_full` example with collabora
=> Add more wopi features, language, disable chat

docs/templates/ADOC.tmpl
As part of a necessary admin docs cleanup.
Adds some space between deprecations - if present - and standard envvar printout.
Also added more explanations as comment.
Backport to `stable-5.0` necessary.
=> [docs-only] Docs adoc template: make a space between deprecations and standard

docs/templates/ADOC.tmpl
Backport of:
#9598 ([docs-only] Docs adoc template: make a space between deprecations and standard)
=> [docs-only] [5.0] Docs adoc template: make a space between deprecations and standard

tests/acceptance/features/apiNotification/emailNotification.feature
This PR covers the test for sending mail notification if the sender has comma(,) in his/her display name
- Resolves https://github.com/owncloud/ocis/issues/9530
- Locally
- CI
=> [tests-only][full-ci] test: add test coverage for mail notification with comma(,) in display name of sender

tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/CliContext.php, tests/acceptance/features/cliCommands/removeFileVersions.feature
This PR adds test for removing versions via cli command
- Coverage for: https://github.com/owncloud/ocis/issues/9472
- Part of https://github.com/owncloud/ocis/issues/9529
- locally
- CI
=> [tests-only][full-ci] adding test to remove old versions of resources using cli command

changelog/unreleased/log-useragent-and-remoteaddr.md, services/proxy/pkg/middleware/oidc_auth.go
The proxy will now log `user_agent`, `client.address`, `network.peer.address` and `network.peer.port` to help operations debug authentication errors. The latter three follow the [Semantic Conventions 1.26.0 / General / Attributes](https://opentelemetry.io/docs/specs/semconv/general/attributes/) naming to better integrate with log aggregation tools.
Trying to help pin down the occurrence very old access tokens... like 120+ days.
=> Log user agent and remote addr on auth errors

tests/acceptance/features/apiSearchContent/propfindExtractedProps.feature
Added scenarios for checking audio, location, image and photo props of the file from `Personal` space by space admin and `Shares` space by sharee.
- Part of https://github.com/owncloud/ocis/issues/9180
- CI
=> [tests-only] add test coverage for new props from personal space

changelog/unreleased/fix-401-on-admin-resources-by-nonadmin.md, services/graph/pkg/middleware/requireadmin.go, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiGraph/changeRole.feature, tests/acceptance/features/apiGraphUserGroup/addUserToGroup.feature, tests/acceptance/features/apiGraphUserGroup/createUser.feature, tests/acceptance/features/apiGraphUserGroup/deleteUser.feature, tests/acceptance/features/apiGraphUserGroup/editUser.feature, tests/acceptance/features/apiGraphUserGroup/getGroup.feature, tests/acceptance/features/apiGraphUserGroup/removeUserFromGroup.feature, tests/acceptance/features/apiGraphUserGroup/searchUserIncludingEmail.feature
With this PR, all the graph `admin requests` if done by the `non-admin` users will respond with `403 Forbidden` instead of `401 Unauthorized`.
Motivation: https://github.com/owncloud/ocis/pull/5742#issuecomment-1482547906
>Now the `401 Unauthorized` vs `403 Forbidden` vs `404 Not Found` status code may look tricky, but hara are the guidelines:
>
>- we don't want to expose existence of resources if a user has no access to them, so we return a `404 Not Found` instead of a `403 Forbidden`.
>- when a user has access to a resource but tries to execute an action that he does not have enough permissions for, e.g. when he tries to write to a read only share, we return a `403 Forbidden`
- We are expecting `403` in some test scenarios.
But the above comment doesn't describe more about `401 …
=> fix: return 403 when non-admin tries to do admin requests

tests/acceptance/features/bootstrap/CliContext.php, tests/acceptance/features/bootstrap/GraphContext.php, tests/acceptance/features/bootstrap/Provisioning.php, tests/acceptance/features/cliCommands/resetUserPassword.feature
Added cli test for updating administrator credentials.
Previously, I directly changed the credential of administration but doing so fails the CI on ociswrapper as the admin credential is hardcoded. 
Reference: https://drone.owncloud.com/owncloud/ocis/37023/43/5
due to https://github.com/owncloud/ocis/blob/ce199d56ab83d7aedc44f9c74439a7b2e60464af/.drone.star#L2130
Therefore, creating a new admin user to cover this scenario. 
-  Closes https://github.com/owncloud/ocis/issues/9581
- ...
=> [tests-only][full-ci] added test for updating admin password via cli

changelog/unreleased/fix-natsjskv-registry.md, go.mod, go.sum, ocis-pkg/natsjsregistry/registry.go, ocis-pkg/natsjsregistry/watcher.go, vendor/github.com/go-micro/plugins/v4/store/nats-js-kv/nats.go, vendor/modules.txt
Fixes: https://github.com/owncloud/ocis/issues/9535
Needs upstream go-micro change: https://github.com/micro/plugins/pull/142
=> Repair Natsjskv Registry

services/collaboration/pkg/connector/httpadapter.go, services/collaboration/pkg/middleware/accesslog.go, services/collaboration/pkg/server/http/server.go
Rise log level to info for the access log for the collaboration service. Information logged will be the same as the proxy service
https://github.com/owncloud/ocis/issues/8769#issuecomment-2235891654
Manually tested
```
{"level":"info","service":"collaboration","proto":"HTTP/1.1","request-id":"3e2bb28fdcc7/OSVUm62V06-000001","traceid":"00000000000000000000000000000000","remote-addr":"172.19.0.2:58614","method":"GET","status":200,"path":"/wopi/files/a27f186f006161194130058f922640fc4c92d6465d81921da83f425cce3bd45b","duration":15.772503,"bytes":565,"time":"2024-07-18T08:42:29Z","line":"/home/juan/src/ocis/ocis/services/collaboration/pkg/middleware/accesslog.go:34","message":"access-log"}
{"level":"info","service":"collaboration","proto":"HTTP/1.1","request-id":"3e2bb28fdcc7/OSVUm62V06-000002", …
```
=> feat: use info level for access log to the collaboration service

tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/CliContext.php, tests/acceptance/features/cliCommands/searchReIndex.feature
Adding test scenario for reindexing spaces via cli
- Part of https://github.com/owncloud/ocis/issues/9529
- test case 1: locally
- test case 2: CI
- ...
=> [tests-only][full-ci] search: reindex command for spaces

tests/acceptance/features/bootstrap/CliContext.php, tests/acceptance/features/cliCommands/removeFileVersions.feature
This PR adds test for removing versions of files from a specific space using space-id using CLI command
- Coverage for : https://github.com/owncloud/ocis/issues/9472
- Part of : https://github.com/owncloud/ocis/issues/9529
- locally
- CI
=> [tests-only][full-ci] adding test to remove old versions of files from a space using space-id using CLI 

docs/helpers/templates/adoc-generator.go.tmpl, docs/templates/ADOC.tmpl, docs/templates/ADOC_global.tmpl
This PR adds the `IntroductionVersion` to the adoc outputs and replaces `%%NEXT%%` and `%%NEXT_PRODUCTION_VERSION%%` in the same outputs.
refs #9525 
refs #9316
=> Fix docs helpers

docs/helpers/env_vars.yaml, docs/helpers/extended_vars.yaml, docs/templates/ADOC.tmpl, docs/templates/ADOC_global.tmpl
Just a small fix to the used templates for adoc table generation.
The envvar files are just updated by the process.
=> [docs-only] Fix ADOC.tmpl and ADOC_global.tmpl (missing entry)

changelog/unreleased/bugfix-missing-invitation-in-permissions.md, services/graph/pkg/service/v0/api_driveitem_permissions.go, services/graph/pkg/service/v0/base.go
Fixes a bug where the `invitation` property is missing in the response when creating, listing or updating graph permissions.
- Fixes https://github.com/owncloud/ocis/issues/9571
=> fix: missing invitation in permission responses

changelog/unreleased/fix-trash-command.md, ocis/pkg/trash/trash.go
The `ocis trash purge-empty-dirs` commands should work on any storage provider, not just `storage/users`
Fixes https://github.com/owncloud/ocis/issues/9615
=> Fix trash command

.drone.env, services/web/pkg/config/defaults/defaultconfig.go, tests/config/drone/ocis-config.json
The `draw-io` app has been removed from the Web default apps, hence this removes it here as well.
The app is now available via the [web-extensions repository](https://github.com/owncloud/web-extensions).
I guess we can omit a changelog item since it will be included in the Web changelog?
See https://github.com/owncloud/web/issues/11248
=> [full-ci] feat: remove draw-io from default web config

services/frontend/pkg/config/config.go, services/graph/pkg/config/config.go
The env var description for `ShowUserEmailInResults` suggested that emails will be omitted from the result if set to `true`. The opposite is the case.
=> [docs-only] fix env var description showing emails in results

tests/acceptance/features/apiSharingNg1/listPermissions.feature
This PR adds tests for `invitation` property which was missing while listing permissions via the `.../graph/v1beta1/drives/{driveId}/items/{itemId}/permissions` endpoint
- Part of https://github.com/owncloud/ocis/issues/8428
- test case 1: locally
- test case 2: CI
- ...
=> [test-ony][full-ci] adding tests for `invitation` property which was missing in permissions responses

.drone.env, changelog/unreleased/remove-unavailable-web-config-options.md, services/web/pkg/config/defaults/defaultconfig.go, services/web/pkg/config/options.go
- test case 1:
- test case 2:
- ...
=> [full-ci] Remove config options that ain't available in web anymore

tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/CliContext.php, tests/acceptance/features/bootstrap/TrashbinContext.php, tests/acceptance/features/cliCommands/cleanupEmptyTrashBin.feature
This PR adds test for deleting empty trash bin via cli
Reference PR: https://github.com/owncloud/ocis/pull/9483
- Part of https://github.com/owncloud/ocis/issues/9529
- locally 
- ci
- ...
=> [tests-only][full-ci] cli test for delete empty trash bin directory

tests/TestHelpers/GraphHelper.php, tests/acceptance/features/apiGraph/activities.feature, tests/acceptance/features/bootstrap/GraphContext.php
Using the new API endpoint `/v1beta1/extensions/org.libregraph/activities`, this test checks file activity information after a user has already uploaded a file.
- CI :robot:
=> [tests-only] [full-ci] Add test to check activity after uploading a file

changelog/unreleased/initdiffmode.md, ocis/pkg/command/init.go, ocis/pkg/init/functions.go, ocis/pkg/init/init.go, ocis/pkg/init/structs.go
Enhancement: Add `--diff` to the `ocis init` command to show the diff of the configuration files
We have added a new flag `--diff` to the `ocis init` command to show the diff of the configuration files.
This is useful to see what has changed in the configuration files when you run the `ocis init` command.
The diff is stored to the ocispath in the config folder as ocis.config.patch and can be applied using the
linux `patch` command.
#3645
=> add diff mode to init

changelog/unreleased/ignore-address-for-kubernetes-registry.md, ocis-pkg/registry/registry.go
We no longer pass an address to the go micro kubernetes registry implementation. This causes the implementation to autodetect the namespace and not hardcode it to `default`.
related https://github.com/owncloud/ocis/issues/8589
=> ignore addresses for kubernetes registry

changelog/unreleased/add-grpc-max-connection-age-env.md, ocis-pkg/service/grpc/keepalive.go, ocis-pkg/service/grpc/service.go
We added a GRPC_MAX_CONNECTION_AGE env var that allows limiting the lifespan of connections. A closed connection triggers grpc clients to do a new DNS lookup to pick up new IPs.
see https://github.com/owncloud/ocis/pull/9488
reva part in https://github.com/cs3org/reva/pull/4772
=> allow configuring grpc max connection age

deployments/examples/ocis_full/onlyoffice.yml
Currently, we have a lot of problems with proof keys and onlyoffice.
- test case 1:
- test case 2:
- ...
=> [docs-only] Disable proof key validation for OnlyOffice

changelog/unreleased/fix-natsjskv-registry-2.md, ocis-pkg/natsjsregistry/watcher.go
- fixes a bug introduced with https://github.com/owncloud/ocis/pull/9656
- we must pass a pointer to unmarshal
- on error we must stop the watcher
=> fix unmarshaling

services/proxy/README.md
=> [docs-only]: Clarify wording in the autoprovisioning section

changelog/unreleased/enhancement-local-app-configuration.md, services/web/README.md, services/web/pkg/apps/apps.go, services/web/pkg/apps/apps_test.go
Introduce a new feature which allows configuring applications individually instead of using the global apps.yaml file.
With that, each application can have its own configuration file, which will be loaded by the WEB service.
The local configuration has the highest priority and will override the global configuration.
The Following order of precedence is used: local.config > global.config > manifest.config.
Besides the configuration, the application now be disabled by setting the `disabled` field to `true` in one of the configuration files.
APP/manifest.json
```json
{
"entrypoint": "index.js",
"config": {
"from_manifest": 1,
"bar": 1
}
}
```
apps.yaml
```yaml
bar:
config:
from_global: 1
bar: 2
```
APP/config.json
```json
{
"config": {
"from_local": 1,
"bar": 3
}
}
```
result …
=> isolated app configuration

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpacesShares/copySpaces.feature
Adding test scenario for sharing file via secure roles among the spaces
```feature
Scenario: user copies a file from share space with secure viewer role to personal space
Scenario Outline: user copies a file from share space with secure viewer role to project space with different role
Scenario Outline: user copies a file from share space with different role to share space with role viewer or space viewer
```
- Part of https://github.com/owncloud/ocis/issues/9334
- ...
=> [tests-only][full-ci] added test coverage for sharing file between spaces via secure view role

changelog/unreleased/use-less-selectors.md, services/proxy/pkg/command/server.go, services/proxy/pkg/proxy/proxy_integration_test.go, services/proxy/pkg/router/router.go, services/proxy/pkg/router/router_test.go, services/proxy/pkg/user/backend/cs3.go
The proxy now shares the service selector for all host lookups.
We were creating a new selector for ever host in the routing policy config. Each one was registering a new nats watcher, wasting memory and traffic.
=> use less selectors

tests/acceptance/features/apiSpacesShares/copySpaces.feature, tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
This PR adds tests for copying files from shares space to personal space with secure viewer role using both old and new dav-path-versions.
```
Scenario Outline: user copies a file from share space with secure viewer role to personal space
```
- Related to : https://github.com/owncloud/ocis/issues/9334
- locally
- CI
=> [tests-only][full-ci] added test for copying files between spaces with secure viewer role using old/new dav-path-versions

changelog/unreleased/fix-natsjskv-registry-2.md, ocis-pkg/natsjsregistry/registry.go, ocis-pkg/natsjsregistry/watcher.go, ocis-pkg/registry/service.go
The registry internally now distinguishes services by version and will aggregate all nodes of the same version into a single service, as expected by the registry cache and watcher.
=> Nats registry fixes

.drone.star
not needed show dashboardId. 
https://grafana.k6.infra.owncloud.works/ -> should open a default dashboard
=> update grafana link

changelog/unreleased/auth-app-api.md, services/auth-app/README.md, services/auth-app/pkg/command/server.go, services/auth-app/pkg/config/config.go, services/auth-app/pkg/config/defaults/defaultconfig.go, services/auth-app/pkg/server/http/option.go, services/auth-app/pkg/server/http/server.go, services/auth-app/pkg/service/option.go, services/auth-app/pkg/service/service.go, services/proxy/pkg/config/defaults/defaultconfig.go
Adds an API to create, list and delete app tokens to the auth-app service
```bash
~/:curl --insecure -XPOST -u admin:admin https://localhost:9200/auth-app/tokens\?expiry\=24h | jq
{
"token": "3s2K7816M4vuSpd5",
"expiration_date": "2024-08-08T13:42:42.796888022+02:00",
"created_date": "2024-08-07T13:42:42+02:00",
"label": "Generated via API"
}
~/:curl --insecure -XPOST -u admin:admin https://localhost:9200/auth-app/tokens\?expiry\=24h\&userName\=einstein 
{
"token": "8T6kmxj5307S4lP9",
"expiration_date": "2024-08-08T13:44:31.025199075+02:00",
"created_date": "2024-08-07T13:44:31+02:00",
"label": "Generated via Impersonation API"
}
~/:curl --insecure -XPOST -u admin:admin https://localhost:9200/auth-app/tokens\?expiry\=24h\&userID\=4c510ada-c86b-4815-8820-42cdf82c3d51 | jq
{
"token": …
```
=> App Token API

services/graph/pkg/identity/backend.go, services/graph/pkg/identity/ldap.go, services/graph/pkg/identity/ldap_test.go, services/graph/pkg/service/v0/users_test.go
LDAP users without a UserType attribute get the UserType "Member" by default. Federated users get the UserType "Federated".
Related #9702
=> (fix)graph: Always set UserType in /users responses

deployments/examples/ocis_full/.env, deployments/examples/ocis_full/docker-compose.yml, deployments/examples/ocis_full/inbucket.yml, deployments/examples/ocis_full/ocis.yml, deployments/examples/ocis_full/s3ng.yml
Fixes: #9632 (ocis_full deployment example is missing to startup (at least) the notification service)
* This PR moves the start of the notification service from `inbucket.yml` to `ocis.yml`
* Improve `.env` readability + some fixes
* Make comments in yml files consistently be in a new line where applicapable
Note that #9772 ([docs-only] Add variables to .env to configure the data- and config directory) adds some good stuff with regards to volumes. I will rebase that PR post merging this one and check the texts and approve/merge it afterwards.
=> [docs-only] Fixes to the ocis full deployment example

changelog/unreleased/change-ocmproviders-defaultpath.md, services/ocm/pkg/config/defaults/defaultconfig.go
We moved the default location of the `ocmproviders.json` config file out of the data directory of the ocm service to the ocis config directory.
=> save ocm providers config file to config path (not user space) 

tests/acceptance/features/apiGraph/activities.feature, tests/acceptance/features/bootstrap/GraphContext.php
Added test to check activity for move file event.
- https://github.com/owncloud/ocis/issues/9712
- test case 1:
- test case 2:
=> [tests-only] [full-ci] Test to check move activity of file

changelog/unreleased/collaboration-improved-tracing.md, services/collaboration/pkg/command/server.go, services/collaboration/pkg/connector/contentconnector.go, services/collaboration/pkg/middleware/proofkeys.go, services/collaboration/pkg/middleware/tracing.go, services/collaboration/pkg/middleware/wopicontext.go, services/collaboration/pkg/server/grpc/server.go, services/collaboration/pkg/server/http/server.go, services/proxy/pkg/middleware/tracing.go
Improve tracing of the collaboration service. This includes:
* Content data upload and download through the WOPI server will be traced. Upload and download times are shown now.
* Some file and user metadata included in the collaboration span. This can help to filter traces by user or by file. It might be useful if users come from different idps, or files are stored in multiple places
* Included the request method in the span name.
It might be better if the `X-WOPI-Override` header was part of the span name, but it seems we'd need to replace the otelchi middleware with our custom version. For now, the header is included as span attribute.
no open issue
This should reflect better how much time is spent in other services, specially since the upload and download times weren't being shown …
=> feat: include additional metadata for tracing the collaboration service

tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/features/bootstrap/FavoritesContext.php, tests/acceptance/features/bootstrap/TrashbinContext.php, tests/acceptance/features/bootstrap/WebDav.php, tests/acceptance/features/coreApiAuth/webDavLOCKAuth.feature, tests/acceptance/features/coreApiAuth/webDavPOSTAuth.feature, tests/acceptance/features/coreApiAuth/webDavPUTAuth.feature, tests/acceptance/features/coreApiFavorites/favorites.feature, tests/acceptance/features/coreApiFavorites/favoritesSharingToShares.feature, tests/acceptance/features/coreApiMain/checksums.feature, tests/acceptance/features/coreApiTrashbin/trashbinDelete.feature, tests/acceptance/features/coreApiTrashbin/trashbinSharingToShares.feature, tests/acceptance/features/coreApiWebdavMove1/moveFolder.feature, tests/acceptance/features/coreApiWebdavMove2/moveFile.feature, tests/acceptance/features/coreApiWebdavOperations/refuseAccess.feature, tests/acceptance/features/coreApiWebdavOperations/search.feature, tests/acceptance/features/coreApiWebdavProperties/copyFile.feature, tests/acceptance/features/coreApiWebdavProperties/createFileFolder.feature, tests/acceptance/features/coreApiWebdavUpload/uploadFile.feature
Updated the issue tags and scenario steps.
=> [tests-only][full-ci] adjust tests and expected-failure list

deployments/examples/ocis_full/.env, docs/ocis/deployment/ocis_full.md
Found while working on the deployment example for ocis rolling:
We must mention the correct addresses for the release types available.
If we dont add this, we quickly end up in frustration if one oversees to set the correct entry on setup.
=> [docs-only] Text only, fix text defaults for ocis container (production/release)

.gitignore, Makefile, tests/qa-activity-report/generate-qa-activity-report.go
related https://github.com/owncloud/ocis/issues/9730
report for api test:
how to generate: `MONTH=08 YEAR=2024 go run tests/qa-activity-report/generate-qa-activity-report-finish.go`
how to generate using MAKE: `make generate-qa-activity-report MONTH=08 YEAR=2024`
generated report: 
```
Test-Type,Date,Tests Added,Tests Changed,Tests Deleted,commit-ID
API Test,2024-08-07,2,0,0,610731f4937446dc9bb07c216e7f06e3a75c52b3
API Test,2024-08-06,2,0,0,8113997a84e5676d4b110fd9f9b813f2bd6d379b
API Test,2024-06-24,3,1,1,b1e55a2853a6ef7c41ac909dda38402a02cbdee0
API Test,2024-08-05,13,0,5,558bbcc6aefa894ff60b3b6899570586c97bdee3
API Test,2024-08-05,0,3,0,62c024bc667b7ebb1b568b45cc6745f39806ae8e
API Test,2024-08-05,0,2,0,903131f76782a3e0251c16cbc75bcc67e3f96ca7
API …
```
=> generate report for api test

changelog/unreleased/federated-user-roles.md, services/graph/mocks/drive_item_permissions_provider.go, services/graph/pkg/service/v0/api_driveitem_permissions.go, services/graph/pkg/service/v0/api_driveitem_permissions_test.go, services/graph/pkg/service/v0/sharedwithme_test.go, services/graph/pkg/service/v0/utils.go, services/graph/pkg/unifiedrole/unifiedrole.go, services/graph/pkg/unifiedrole/unifiedrole_test.go, services/storage-users/pkg/revaconfig/drivers.go, services/web/pkg/theme/theme.go, tests/acceptance/features/apiGraph/roleManagementEndpoint.feature
When listing permissions clients can now fetch the list of available federated sharing roles by sending a `GET /graph/v1beta1/drives/{driveid}/items/{itemid}/permissions?$filter=@libre.graph.permissions.roles.allowedValues/rolePermissions/any(p:contains(p/condition, '@Subject.UserType=="Federated"'))` request. Note that this is the only supported filter expression. Federated sharing roles will be omitted from requests without this filter.
The `/roleManagement/permissions/roleDefinitions` also returns the new roles. Filtering them is done in a subsequent PR which requires https://github.com/owncloud/ocis/pull/9727
server part of https://github.com/owncloud/ocis/issues/9745
```json
$ curl 'https://cloud.owncloud.test/graph/v1beta1/drives/storage-users-2%244c510ada-c86b-4815-8820-42cdf82c3d51 …
```
=> allow querying federated sharing roles

tests/acceptance/features/apiGraph/activities.feature
Adds test to check activity for file rename event.
-  https://github.com/owncloud/ocis/issues/9744
- CI
- locally
=> [tests-only] [full-ci] Test for resource(file|folder) rename activity

deployments/examples/ocis_full/.env
This is just a mini fix for the `.env` file in the ocis_full deployment example removing a blank for consistency reasons as all lines of the same type should have the same look and feel.
=> [docs-only] Mini text only fix for .env

changelog/unreleased/ocm_users_graph.md, services/graph/pkg/service/v0/users.go, services/graph/pkg/service/v0/users_filter.go, services/graph/pkg/service/v0/users_test.go, tests/TestHelpers/GraphHelper.php, tests/acceptance/features/apiOcm/searchFederationUsers.feature, tests/acceptance/features/bootstrap/GraphContext.php
This adds support for equality filters on the `userType` property of users  for the /users endpoint.
It also changes the behavior of the /users endpoint to only return federated users when explicitly request via a `userType` filter.
E.g. to search for federated users with matching "albert" you can use:
`$filter=userType eq 'Federated'&$search="albert"`
Related Issue: #9702
=> feat(graph): add support for filtering users by type

deployments/examples/ocis_full/.env, deployments/examples/ocis_full/ocis.yml, docs/ocis/deployment/ocis_full.md
References: #9798 ([docs-only] deployments: Default to "ocis-rolling" for the ocis_full example for now)
Found turing testing.
The referenced PR was incomplete as it only covered ocis.yml but not the office suites yaml files. This leaded to the situation that ocis started rolling but the office containers started production.
This PR fixes this by setting the default in the .env file correctly to rolling which is then used in all yaml files that need the ocis image.
=> [docs-only] Fix the default deployment release type

tests/acceptance/features/apiActivities/shareActivities.feature
This  PR adds test to check activity for a file after creating share link.
- Related to: https://github.com/owncloud/ocis/issues/9543
- locally
- CI
=> [test-only][full-ci] add test for api activities of a file after link creation and deletion

deployments/examples/ocis_full/collabora.yml, deployments/examples/ocis_full/docker-compose.yml, deployments/examples/ocis_full/ocis.yml, deployments/examples/ocis_full/onlyoffice.yml
References: #9772 ([docs-only] Add variables to .env to configure the data- and config directory)
While working on the deployment examples the following popped up which now is fixed:
* The volumes used, which now can be configured via #9772, also need to be added in the two office yml definitions.
* Traefik is updated from 3.0.3 to 3.1.2
The traefik update had no issues during testing.
=> Fix some deployment stuff

tests/acceptance/features/apiGraph/activities.feature
Added test to check activity of file and folder inside another folder.
- https://github.com/owncloud/ocis/issues/9712
- test case 1:
- test case 2:
- ...
=> [tests-only] [full-ci] Test to check activities of a folder

vendor-bin/owncloud-codestyle/composer.json
https://github.com/owncloud/coding-standard/releases/tag/5.3.0 updates the config for php-cs-fixer to remove deprecated fixer rules, and replace them with the relevant new rules.
Previously, php-cs-fixer was warning:
```
- Rule "braces" is deprecated. Use "single_space_around_construct", "control_structure_braces", "control_structure_continuation_position", "declare_parentheses", "no_multiple_statements_per_line", "braces_position", "statement_indentation" and "no_extra_blank_lines" instead.
- Rule "no_spaces_inside_parenthesis" is deprecated. Use "spaces_inside_parentheses" instead.
```
Now those warnings are no longer emitted. But a similar set of new rules are enforced.
Local run of
```
make test-php-style
```
=> test: require at least coding-standard 5.3

services/graph/pkg/service/v0/users.go, services/idm/idm.go, services/idm/ldif/base.ldif.tmpl, services/idm/ldif/demousers.ldif.tmpl, services/idm/pkg/command/server.go, services/idm/pkg/config/config.go, services/idm/pkg/config/defaults/defaultconfig.go
=> graph: add identities property to non-admin response of GetUsers

services/ocm/README.md
Fixes: 9794 (Document the location of ocmproviders.json --> config directory)
Introduced with #9778, the location of the `ocmproviders.json` file is now expected to be in the root of the ocis config directory. This was not documented - fixed now.
=> [docs-only] Document the expected location of the ocmproviders.json file

tests/acceptance/features/apiActivities/shareActivities.feature
This PR adds test where a sharer checks api activities of a space after a member is added and removed.
``` feature
Scenario: check add member to space activity
Scenario: check remove member from space activity
```
- Related to: https://github.com/owncloud/ocis/issues/9543
- locally
- CI
=> [tests-only][full-ci] add test to check add and remove member acivities

deployments/examples/ocis_wopi/.env, deployments/examples/ocis_wopi/collabora.yml, deployments/examples/ocis_wopi/ocis.yml, deployments/examples/ocis_wopi/onlyoffice.yml
Same as we have recently added with rolling, the ocis volumes config and data paths are now configurable.
This will go on merging into the upcoming 5.0.7 release.
The reason to do so is:
* Align the configurations in versions
* Ease the prod - to - prod upgrade when released
The deployment description in the admin docs in master already has the relevant content, only selective text backports need to be made AFTER the 5.0.7 release is published.
@dragotin, @tbsbdr fyi
=> [docs-only][stable-5.0] ocis_wopi deployment example, make data and config volumes configurable

changelog/unreleased/add-virus-filter.md, changelog/unreleased/assimilate-clean-into-sessions.md, go.mod, services/storage-users/README.md, services/storage-users/pkg/command/uploads.go, services/storage-users/pkg/command/uploads_test.go, vendor/github.com/test-go/testify/LICENSE, vendor/github.com/test-go/testify/require/doc.go, vendor/github.com/test-go/testify/require/forward_requirements.go, vendor/github.com/test-go/testify/require/require.go, vendor/github.com/test-go/testify/require/require.go.tmpl, vendor/github.com/test-go/testify/require/require_forward.go, vendor/github.com/test-go/testify/require/require_forward.go.tmpl, vendor/github.com/test-go/testify/require/requirements.go, vendor/modules.txt
Backport of https://github.com/owncloud/ocis/pull/9041
Fixes https://github.com/owncloud/ocis/issues/9003
=> [full-ci] Backport Sessions Command

services/ocm/README.md
I tried to make the setup and what goes inside the ocmproviders file clearer.
=> [docs-only] update ocm service readme

docs/ocis/release_roadmap.md
The image link in the release roadmap for `semver-schema` was incorrect and therefore broken.
This is fixed now.
@tbsbdr @micbar fyi
=> [docs-only] Fix dev docs release roadmap image link

services/collaboration/pkg/connector/fileconnector.go, services/collaboration/pkg/helpers/cs3.go, services/collaboration/pkg/middleware/wopicontext.go, services/collaboration/pkg/service/grpc/v0/service.go
We're using the file id from the access token, so changing the file id in the URL shouldn't matter. However, the file id must represent a single file.
It will also help to detect unwanted changes in the URL.
The `HashResourceId` is used to generate the `/wopi/files/abcdef123` URLs. This is needed in the `OpenInApp` method (when the user requests opening a file in Collabora or any other WOPI app) as well as in the `PutRelativeFile` method (when the user saves the document with a different file name).
The URL is expected to be stable and point to a single file. So far, we've used the data contained in the access token to get the file id. While this is fine, the file id contained in the URL could be different.
For example, `/wopi/files/abc` and `/wopi/files/123` both could point to the same …
=> fix: verify file id in URL matches the one inside the access token

tests/acceptance/features/apiActivities/activities.feature
This PR adds test to check activity after changing the systems language to your preferred one.(German 'de' in this case).
``` feature
Scenario: check activity message with different language
```
- Related to : https://github.com/owncloud/ocis/issues/9543
- Bug Report : https://github.com/owncloud/ocis/issues/9856
- Locally
- CI
=> [tests-only][full-ci] add test to check activity after language translation

services/collaboration/pkg/connector/contentconnector_test.go, services/collaboration/pkg/connector/fileconnector.go, services/collaboration/pkg/connector/fileconnector_test.go, services/collaboration/pkg/middleware/wopicontext.go, services/collaboration/pkg/service/grpc/v0/service.go, services/collaboration/pkg/service/grpc/v0/service_test.go
Simplify `OpenInApp` method. This contains:
* Custom sublogger to compact log calls
* Simplify and move the code to get the appURL
* Move the code to generate the query params for the appURL
We've also temporarily removed the `HostViewURL` and `HostEditURL` for 2 reasons:
* Current values are wrong. The values are expected to point to an ocis URL, not to Collabora (or other WOPI app)
* It keeps the `OpenInApp` code simpler
Those values might can back with https://github.com/owncloud/ocis/pull/9686
No opened issue
Code is simpler and easier to follow
- test case 1:
- test case 2:
- ...
=> Collaboration openinapp refactor

tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiArchiver/downloadById.feature, tests/acceptance/features/apiArchiver/downloadByPath.feature, tests/acceptance/features/apiSpacesShares/copySpaces.feature, tests/acceptance/features/bootstrap/ArchiverContext.php, vendor-bin/behat/composer.json
- https://github.com/owncloud/ocis/issues/4636
- https://github.com/owncloud/ocis/issues/7208
=> [tests-only] adjust expected-failure list and archive related tests

changelog/unreleased/list-ocm-permissions.md, services/graph/pkg/service/v0/api_driveitem_permissions.go, services/graph/pkg/service/v0/base.go, services/graph/pkg/service/v0/utils.go
The libre graph API now returns OCM shares when listing driveItem permissions.
fixes: https://github.com/owncloud/ocis/issues/9898
related: https://github.com/owncloud/ocis/issues/9735
=> List OCM permissions as graph drive item permissions

services/notifications/pkg/config/config.go, services/web/pkg/config/config.go
Fixes: #9887 (Some deprecated envvars have a release number set and not the prepared variable defined)
All current deprecated envvars have as version `%%NEXT_PRODUCTION_VERSION%%` set except two - fixed now.
=> [docs-only] Set the correct removal version

services/gateway/README.md
References: #9490 (set the configured protocol transport for service metadata)
As discussed with @butonic, adding that _configurable service endpoints_ are currently experimental.
=> [docs-only] Update README.md of the gateway service

changelog/unreleased/ocm-listing-fixes.md, services/graph/pkg/service/v0/sharedbyme.go
The sharedByMe endpoint now includes ocm shares if ocm is enabled.
fixes https://github.com/owncloud/ocis/issues/9908
=> list ocm shares in sharedByMe

tests/acceptance/features/apiCollaboration/wopi.feature
Added test to open text file with `/app/open` endpoint with and without `app_name` parameter.
=> [tests-only][full-ci] add test coverage to open text file with `/app/open` endpoint

tests/acceptance/config/behat.yml, tests/acceptance/features/apiCollaboration/wopi.feature
Added test for sharee to open `.odt` file with `/app/open` endpoint with and without `app_name` parameter.
=> [tests-only][full-ci]added test for sharee to open file with `/app/open` endpoint

tests/acceptance/bootstrap/FeatureContext.php, tests/acceptance/features/apiCollaboration/wopi.feature
This PR adds the test for public user to open file using `/app/open` endpoint with and without `app_name` parameter.
=> [tests-only][full-ci]Added test for public user using `/app/open` endpoint

tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
Added test coverage for copying file using fileId from share space:
| |from (space) | from (role) | to (space) | to (role) 
--|--|--|--|--|
| 1. | share | different permission | project | different permission 
| 2. | share | different permission | share | different permission
| 3. | share | different permission	| personal
- Part of https://github.com/owncloud/ocis/issues/9878
- locally 
- CI :robot:
=> [tests-only] [full-ci] Add test coverage for copying file using file id from share space

tests/acceptance/features/apiCollaboration/wopi.feature
Added test to open file with unsupported file format with `/apps/open` endpoint with and without `app_name` in URL query parameter.
=> [tests-only][full-ci] added test to open file with unsupported file format

.drone.env, changelog/unreleased/update-web-8.0.5.md, services/web/Makefile
- Bugfix [owncloud/web#11395](https://github.com/owncloud/web/pull/11395): Missing space members for group memberships
- Bugfix [owncloud/web#11263](https://github.com/owncloud/web/pull/11263): Show more toggle in space members view not reactive
- Bugfix [owncloud/web#11263](https://github.com/owncloud/web/pull/11263): Space show links from other spaces
- Bugfix [owncloud/web#11303](https://github.com/owncloud/web/pull/11303): Uploading nested folders
=> [full-ci] chore: bump ownCloud Web to v8.0.5

tests/acceptance/features/apiCollaboration/wopi.feature
Added test to send post request to `/app/open` endpoint with non-existing file id.
=> [tests-only][full-ci]added test to open file with non-existing file id

services/ocm/README.md, services/ocm/pkg/config/config.go
References: #9814 ([docs-only] update ocm service readme)
* After clarification with @micbar, the ocm service is started, for the time being, automatically with the runtime.
* After clarification with @butonic the `OCM_OCM_INVITE_MANAGER_JSON_FILE` is maintained by the instance. This makes it clear that the location is therefore different compared to `OCM_OCM_PROVIDER_AUTHORIZER_PROVIDERS_FILE`...
=> [docs-only] Small ocm text fix

tests/acceptance/features/apiCollaboration/wopi.feature
Added test to send post request to `/app/open` endpoint with different view mode, `view_mode=[view | read | write]`
=> [tests-only][full-ci]added test for open file using `/app/open` endpoint with different view mode

services/ocm/README.md, services/ocm/pkg/config/config.go
The default path shows `/var/lib/ocis/storage/ocm` but the description text only `$OCIS_BASE_DATA_PATH:/storage`. Fixed by adding `/ocm`.
The readme also has a text fix which was a leftover.
=> [docs-only] Small fix for ocm envvar description text

docs/services/general-info/add-translations.md, services/activitylog/pkg/service/l10n/.tx/config, services/graph/pkg/l10n/.tx/config, services/notifications/pkg/email/l10n/.tx/config, services/userlog/pkg/service/l10n/.tx/config
The translation docs missed the entry that we need to have `resource_name` added in the definition when setting up a new translation for a service. This leaded to the situation that we have thought we defined a name to show up in TX as `ocis-<service-name>` but its showed up as `<service-name>.pot`. Then we manually needed to fix the name in TX for ease of identification.
This is now fixed not only in the dev docs, but also corrected in the TX definition of all 4 services which have translations set up.
@kobergj @2403905 fyi 😃 
Thanks for @DeepDiver1975 pointing me to the missing piece
=> [docs-only] Update translation docs + transifex configuration (add resource_name)

changelog/unreleased/enhancement-ocm-handle-invite-generated-event.md, services/audit/pkg/service/service.go, services/audit/pkg/service/service_test.go, services/audit/pkg/types/conversion.go, services/audit/pkg/types/events.go, services/audit/pkg/types/messages.go, services/audit/pkg/types/types.go, services/notifications/pkg/channels/channels.go, services/notifications/pkg/command/server.go, services/notifications/pkg/email/email.go, services/notifications/pkg/email/templates.go, services/notifications/pkg/service/sciencemesh.go, services/notifications/pkg/service/service.go, services/ocm/pkg/config/config.go, services/ocm/pkg/config/defaults/defaultconfig.go, services/ocm/pkg/revaconfig/config.go
By now, the sciencemesh part in reva was responsible to notify the invitee that a invitaion happened, in ocis we have a event driven approach.
This PR introduces that and handles those invitation events in the notification service by sending mails.
- Fixes https://github.com/owncloud/ocis/issues/9583
- Needs: https://github.com/cs3org/reva/pull/4832
- Needs: https://github.com/owncloud/web/pull/11512
- not at all right now, next step
=> [full-ci] enhancement: handle ocm event notifications

tests/acceptance/features/apiCollaboration/wopi.feature
Added test to send post request to /app/open-with-web endpoint with different view mode, view_mode=[view | read | write]
- Locally
- CI
=> [tests-only][full-ci] test: add test coverage for opening file using /app/open-with-web  endpoint with different view mode

deployments/examples/ocis_full/ocis.yml
There was a quote in a variable which should not be there.
=> [docs-only] Typo fix ocis.yml

services/graph/README.md
Removing one character that prevents a section heading from being auto-referenced in the TOC.
=> [docs-only] Fix a typo in graph service readme

tests/acceptance/features/apiCollaboration/wopi.feature
Added test to open file with unsupported file format with `/app/open-with-web` endpoint with and without app_name in URL query parameter.
- Locally
- CI
=> [tests-only][full-ci] test: add test coverage for opening file with unsupported file fromat using /app/open-with-web endpoint

tests/acceptance/bootstrap/FilesVersionsContext.php, tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
This PR adds tests to check versions of a file inside a Personal and Project space that is shared via link with viewer and editor roles.
``` feature
Scenario Outline: check the versions of a file in a space shared via link as viewer/editor
Scenario Outline: check the versions of a file in a personal space shared via link as viewer
```
- Related to: https://github.com/owncloud/ocis/issues/9955
- locally
- CI
=> [tests-only][full-ci] add tests to check versions of file in a space shared via link with viewer/editor role

services/idp/src/components/Loading.jsx, services/idp/src/containers/Goodbye/Goodbyescreen.jsx, services/idp/src/containers/Login/Chooseaccount.jsx, services/idp/src/containers/Login/Consent.jsx, services/idp/src/containers/Welcome/Welcomescreen.jsx
Ignores the eslint react errors for `react/no-is-mounted` to make CI green again.
This is only a temporary solution, updating the pnpm version in our node docker images should make this obsolete. However, with the release around the corner I don't want to do this because I'm afraid of the overall impact. pnpm likes to break stuff with releases, unfortunately.
=> fix: eslint react errors when building idp service

deployments/examples/ocis_full/ocis.yml
during the testing release I catch one error: 
- I tried to start ocis-full without enabling inbucket and get some error: 
```
2024-09-12 11:40:55 the 'smtp_sender' must be a valid single RFC 5322 address. parsing error: the address cannot be empty
```
because 
are empty and we set it https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_full/inbucket.yml#L4-L10
when inbucket is enabled
I guess it happens after https://github.com/owncloud/ocis/commit/3cc29ce99bd5025cec2f9dfef2feb613b4136449
=> Running ocis without inbucket by default

changelog/unreleased/fix-ocm-invite-email.md, services/notifications/pkg/email/templates.go, services/notifications/pkg/service/sciencemesh.go
The golang conditional construction moved out from the transifex template
- test case 1:
- test case 2:
- ...
=> The golang conditional construction moved out from the transifex template

tests/acceptance/bootstrap/FeatureContext.php, tests/acceptance/features/apiCollaboration/wopi.feature
Added test to send post request to /app/open-with-web endpoint with non-existing file id.
- Locally
- CI
=> [tests-only][full-ci] test: add test coverage for opening file with non-existing fileId using /app/open-with-web endpoint

docs/services/general-info/envvar-scopes.md
References: #10043 ([docs-only][chore] Update env_vars.yaml)
@phil-davis raised an important question that was not covered in our dev docs:
Does adding an envvar to an existing one change the introduction version --> No
This is now documented.
=> [docs-only] Clarify introduction version when adding an envvar to an existing one

.drone.star, tests/acceptance/TestHelpers/OcmHelper.php, tests/acceptance/bootstrap/FeatureContext.php, tests/acceptance/bootstrap/OcmContext.php, tests/acceptance/config/behat.yml, tests/acceptance/features/apiOcm/createInvitation.feature
related https://github.com/owncloud/ocis/issues/9583
test for receiving an email if the user specified an email when creating a federation share invitation
=> [test-only] ApiTest. Check email notification ocminvite

changelog/6.4.0_2024-09-12/enhancement-unified-roles-management.md, services/graph/pkg/command/unified_roles.go, services/graph/pkg/unifiedrole/roles.go, tests/acceptance/features/apiGraph/roleManagementEndpoint.feature, tests/acceptance/features/apiSharingNg1/listPermissions.feature
Improve some wordings and cli output.
```
+----------------------------+--------------------------------------+----------+--------------------------------+--------------------------------+------------------------------------------+
|            NAME            |                 UID                  | ENABLED  |          DESCRIPTION           |           CONDITION            |         ALLOWED RESOURCE ACTIONS         |
+----------------------------+--------------------------------------+----------+--------------------------------+--------------------------------+------------------------------------------+
| Viewer                     | b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5 | enabled  | View and download.             | exists @Resource.File          | libre.graph/driveItem/path/read …
```
=> fix: improve some wordings and cli table

changelog/unreleased/fix-ocm-token.md, services/ocm/pkg/config/config.go, services/ocm/pkg/config/defaults/defaultconfig.go, services/ocm/pkg/config/reva.go, services/ocm/pkg/revaconfig/config.go
We now pass the JWT secret to the reva runtime.
The ocm service only picks up the shared jwt because the sharedConf package is a singleton and other services in ocis initialize it ... 😞
=> fix ocm token

tests/acceptance/bootstrap/CollaborationContext.php, tests/acceptance/features/apiCollaboration/checkFileInfo.feature
This PR add tests coverage for checking file info with different view-mode
- https://github.com/owncloud/ocis/issues/9844
- Locally
=> [tests-only][full-ci] Add test coverage for checking file info with different view mode

tests/acceptance/features/apiCollaboration/wopi.feature
Added test to create .odt file inside a shared folder using `/app/new` endpoint.
=> [tests-only][full-ci] added test to create .odt file inside shared folder using `/app/new` endpoint

tests/acceptance/TestHelpers/CollaborationHelper.php, tests/acceptance/TestHelpers/EmailHelper.php, tests/acceptance/TestHelpers/GraphHelper.php, tests/acceptance/TestHelpers/OcmHelper.php, tests/acceptance/bootstrap/CollaborationContext.php, tests/acceptance/features/apiCollaboration/checkFileInfo.feature
This PR has test coverage for check file info on different office suites with valid access token and invalid file id
- https://github.com/owncloud/ocis/issues/9844
- locally
=> [tests-only][full-ci]Add test for sending request to check file info with invalid file id

tests/acceptance/features/apiActivities/activities.feature
Added test for default depth activity filter i.e. `depth:-1`
- https://github.com/owncloud/ocis/issues/9850
- locally
- CI :robot:
=> [tests-only] [full-ci] Add test for default depth activity filter

changelog/unreleased/ldap-signin-timestamp.md, deployments/examples/ocis_ldap/config/ldap/schemas/10_owncloud_schema.ldif, ocis-pkg/oidc/context.go, services/graph/.mockery.yaml, services/graph/pkg/identity/backend.go, services/graph/pkg/identity/cs3.go, services/graph/pkg/identity/ldap.go, services/graph/pkg/identity/ldap_education_school.go, services/graph/pkg/identity/mocks/backend.go, services/graph/pkg/server/http/server.go, services/graph/pkg/service/v0/graph.go, services/graph/pkg/service/v0/option.go, services/graph/pkg/service/v0/service.go, services/proxy/pkg/command/server.go, services/proxy/pkg/middleware/account_resolver.go, services/proxy/pkg/middleware/oidc_auth.go, services/proxy/pkg/middleware/options.go
Related issue: https://github.com/owncloud/enterprise/issues/6726
To allow tracking new user signins we're are now emitting an `UserSignedIn` event from the proxy's account resolve middleware.
A goroutine, started as part of the graph service (the only service that might have write access to the idm database currently) consumes that event and updates a new LDAP attribute `ocLastSignInTimestamp` on the user object.
The PR does not yet expose the attribute on the `users` endpoint. Support for that will be added in a separate PR.
=> Allow to track last sign-in time of users

services/notifications/pkg/email/templates.go
While translating the text on Transifex, I identified that the source needs a small change to fix the meaning. This is because the reciever needs to go into _his_ federation settings...
=> [docs-only] Fix translatable text string in notifications

tests/acceptance/TestHelpers/CollaborationHelper.php, tests/acceptance/bootstrap/CollaborationContext.php, tests/acceptance/features/apiCollaboration/wopi.feature
Added test for public user to create .odt file using `/app/new` endpoint inside a shared folder.
=> [tests-only][full-ci] added test for public user to create .odt file inside public folder

tests/acceptance/bootstrap/CollaborationContext.php, tests/acceptance/features/apiCollaboration/wopi.feature
Added test to create odt file inside a deleted parent folder.
=> [test-only][full-ci] added test to create odt file inside deleted parent folder

changelog/unreleased/fix-acitivity-leak.md, services/activitylog/pkg/service/http.go
Fixes: https://github.com/owncloud/ocis/issues/9860
=> Fix unauthorized activity get

tests/acceptance/bootstrap/CollaborationContext.php, tests/acceptance/features/apiCollaboration/wopi.feature
Added test for public user to create odt file inside public space using `/app/new` endpoint.
=> [tests-only][full-ci] added test for public user to create odt file inside public space

changelog/unreleased/fix-acitivity-update-public-link.md, services/activitylog/pkg/command/server.go, services/activitylog/pkg/service/http.go, services/activitylog/pkg/service/response.go, services/activitylog/pkg/service/service.go
- Fixes [#10012](https://github.com/owncloud/ocis/issues/10012)
Added the LinkUpdated activity in the space context
- test case 1:
- test case 2:
- ...
=> Added the LinkUpdated activity in the space context

tests/acceptance/bootstrap/NotificationContext.php, tests/acceptance/bootstrap/OcmContext.php, tests/acceptance/config/behat.yml, tests/acceptance/features/apiOcm/createInvitation.feature
related #10059 
fixed two issues: 
- different invitation token
it happened because we didn't `clearInbucketMessages` in the `ocmContext` and as a result, we've had several emails to Brian
- ignoring extra spaces and blank lines 
it's weird. I can't explain it. As a solution -> I trim all spaces and blank lines and compare only the text with the body of the email
=> [test-only] fix ocm email test - issue/10059

changelog/unreleased/collaboration-wopi-logs.md, services/collaboration/pkg/middleware/wopicontext.go
Include additional logs for errors inside the wopicontext middleware.
There have been cases where the wopi server returns a 401 (unauthorized) code, which suggest a problem in the wopicontext middleware, however, there are no logs about the cause of the error, which makes it very difficult to debug.
This PR just adds new logs for error cases. There is no change in the behavior nor in the log information.
Related to https://github.com/owncloud/ocis/issues/10053
Troubleshooting for those 401 errors should be easier.
Partially tested manually by making a request to the wopi server with wrong data. Seen the "missing access token" and "failed to parse jwt token". The rest might require a more carefully crafted token, so it's more difficult to prove, but the risk is very low.
=> fix: include additional logging in the wopicontext middleware

.drone.star
I am seeing errors like this in ci:
```
INFO: Sensor Code Quality and Security for Go [go]
INFO: 1101 source files to be analyzed
INFO: The Go analyzer is running in a context where unchanged files can be skipped.
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 19.415s
INFO: Final Memory: 21M/108M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarScanner execution
java.lang.IllegalArgumentException: 181 is not a valid line offset for pointer. File services/auth-basic/pkg/config/config.go has 162 character(s) at line 51
at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java …
```
=> bump sonarcloud cli 5.0 -> 11.0

changelog/unreleased/remove-metadata-backend.md, services/storage-system/README.md, services/storage-system/pkg/config/config.go, services/storage-system/pkg/config/defaults/defaultconfig.go, services/storage-system/pkg/revaconfig/config.go, services/storage-users/README.md, services/storage-users/pkg/config/config.go, services/storage-users/pkg/config/defaults/defaultconfig.go, services/storage-users/pkg/revaconfig/drivers.go
Fixes: #8462
Removes deprecated `XXX_METADATA_BACKEND` envvars
=> Remove METADATA_BACKEND

docs/helpers/env_vars.yaml
References: #10113 (Remove METADATA_BACKEND)
The `env_vars.yaml` file needed an update after merging #10113
Autogenerated with `make -C docs doc-generate`
Due to the removal, a lot of things got reordered, though only a few things have changed in reality
=> [docs-only][chore] Update env_vars.yaml based on recent code changes

changelog/unreleased/collaboration-fileinfo-error-code.md, services/collaboration/pkg/connector/fileconnector.go, services/collaboration/pkg/connector/fileconnector_test.go
The `CheckFileInfo` request will now return a 404 error code if the target file isn't found
https://github.com/owncloud/ocis/issues/10097
Server should return a proper error code instead of a generic 500
Manually tested following steps in https://github.com/owncloud/ocis/issues/10097 , and unit tests added for this specific case
=> fix: return 404 code if file isn't found on CheckFileInfo request

tests/acceptance/features/apiActivities/activities.feature
skipping the test so to ublock the CI
- https://github.com/owncloud/ocis/issues/10127
=> [tests-only] skip activity translation test

changelog/unreleased/forbid-activities-for-sharees.md, services/activitylog/pkg/service/http.go
Forbids sharees to see item activities
Fixes https://github.com/owncloud/ocis/issues/9849
=> [full-ci] Forbid Sharee access to Activities

changelog/unreleased/enhancement-load-csp-if-exists.md, services/proxy/pkg/config/defaults/defaultconfig.go
The Content Security Policy (CSP) configuration file is now loaded by default if it exists.
The configuration file looked for should be located at `$OCIS_BASE_DATA_PATH/proxy/csp.yaml`.
If the file does not exist, the default CSP configuration is used.
- Fixes https://github.com/owncloud/ocis/issues/10021
=> enhancement: Load CSP configuration file if it exists

Makefile
The ci keeps running into the default 5min timeout quite often recently.
See e.g.:
https://drone.owncloud.com/owncloud/ocis/39281/6/4
https://drone.owncloud.com/owncloud/ocis/39282/6/4
=> increase bingo get timeout to 10min

services/activitylog/pkg/service/http.go, services/activitylog/pkg/service/response.go, services/postprocessing/pkg/postprocessing/postprocessing.go, services/postprocessing/pkg/service/service.go, tests/acceptance/features/apiActivities/activities.feature, tests/acceptance/features/apiActivities/shareActivities.feature
~Bumps reva~
Fixes https://github.com/owncloud/ocis/issues/9676
=> [full-ci] Fix Activitylog for PublicLink users

tests/acceptance/bootstrap/CollaborationContext.php, tests/acceptance/config/behat.yml, tests/acceptance/features/apiCollaboration/checkFileInfo.feature
This PR add tests for edge cases
- https://github.com/owncloud/ocis/issues/9844
- locally
=> [tests-only][full-ci]add edge case for check file info

tests/acceptance/bootstrap/GraphContext.php, tests/acceptance/features/apiActivities/activities.feature, tests/acceptance/features/apiActivities/shareActivities.feature
This PR adds test where a sharee checks api activities.
``` feature
Scenario: sharee tries to check the activities of a shared folder using share mount-point id
Scenario: sharee tries to check the activities of unshared file
Scenario: sharee tries to check the activities of a shared folder using folder id
```
- Related to : https://github.com/owncloud/ocis/issues/9543
=> [tests-only][full-ci] add test to check acivities by sharee

changelog/unreleased/fix-acitivity-translation.md, services/activitylog/pkg/service/response.go
```
+ make l10n-read
make[1]: Entering directory '/drone/src/ocis/services/activitylog'
go-xgettext -o ./pkg/service/l10n/activitylog.pot --keyword=l10n.Template -s pkg/service/response.go
panic: unknown type: _someField
```
- test case 1:
- test case 2:
- ...
=> Fix the panic for the translation-sync in the activities service.

changelog/unreleased/fix-email-translations.md, services/notifications/README.md, services/notifications/pkg/command/server.go, services/notifications/pkg/service/service.go, services/notifications/pkg/service/service_test.go
Fixes custom translation path feature for notifications service and corrects its documentation.
=> Fix email translationPath and docu

changelog/unreleased/wopi-host-urls.md, services/collaboration/pkg/connector/fileconnector.go, services/collaboration/pkg/connector/fileconnector_test.go, tests/acceptance/features/apiCollaboration/checkFileInfo.feature
This adds 4 important missing properties for OnlyOffice and Microsoft365.
- Switch the View modes (View / Edit) in Microsoft365 and Microsoft Office Online
- Adds a "Share" button to open the share dialogue.
- Adds a "Version History" link in the files menu
If you click these buttons, you get a new tab openend with the file list and the sidebar is opened in the desired mode.
- test case 1:
- test case 2:
- ...
=> feat: add wopi host and sharing urls

.drone.star
while creating a tag I noticed that we run coding-standart-php but we don't run tests
I removed this step from CI if we create tag
=> [test-only] do not run coding standart php step when releasing

.drone.star, tests/acceptance/features/apiActivities/activities.feature, tests/config/translations/de/LC_MESSAGES/activitylog.po, tests/config/translations/de/LC_MESSAGES/notifications.po, tests/config/translations/de/LC_MESSAGES/userlog.po, tests/config/translations/es/LC_MESSAGES/notifications.po, tests/config/translations/es/LC_MESSAGES/userlog.po
Cofigure custom translation for tests. Translations are used for activities, antivirus and notifications tests. 
To configure the custom translation use the env `OCIS_TRANSLATION_PATH` which takes the path to the base folder where the translation file exists. Currently the translation files exists in `tests/config/translations` folder.
`OCIS_TRANSLATION_PATH=tests/config/translations`
Docs:
- https://owncloud.dev/services/activitylog/#translations
- https://owncloud.dev/services/userlog/#translations
- https://owncloud.dev/services/notifications/#translations
- Fixes https://github.com/owncloud/ocis/issues/10127
=> [tests-only][full-ci]configure custom translation for tests

tests/acceptance/TestHelpers/CollaborationHelper.php, tests/acceptance/TestHelpers/GraphHelper.php, tests/acceptance/TestHelpers/HttpRequestHelper.php, tests/acceptance/bootstrap/FeatureContext.php, tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/features/apiContract/copy.feature, tests/acceptance/features/apiContract/propfind.feature, tests/acceptance/features/apiContract/sharesReport.feature, tests/acceptance/features/apiContract/spacesReport.feature, tests/acceptance/features/apiContract/spacesSharesReport.feature, tests/acceptance/features/apiLocks/lockFiles.feature, tests/acceptance/features/apiSearchContent/extractedProps.feature, tests/acceptance/features/apiSharingNg1/propfindShares.feature, tests/acceptance/features/apiSpaces/tag.feature, tests/acceptance/features/apiSpacesDavOperation/propfindByFileId.feature
- compare the file-id pattern not the actual id in PROPFIND/REPORT response
- because we were doing the same PROPFIND request to get the file-id and compare with similar PROPFIND request
- step changes:
```diff
-Then the "REPORT/PROPFIND" response should contain a space/mountpoint "<name>" with these key and value pairs:
-Then the "REPORT/PROPFIND" response to user "<user>" should contain a space/mountpoint "<name>" with these key and value pairs:
+Then as user "<user>" the REPORT/PROPFIND response should contain a space/resource "<name>" with these key and value pairs:
```
- added `jsonSchemaRegexToPureRegex` to convert existing json schema regex to php regex
- moved `sendScenarioLineReferencesInXRequestId` to `HttpRequestHelper`
- fix `X-Request-Id` header tests to make it pass when …
=> [tests-only][full-ci] fix shares propfind tests

changelog/unreleased/fix-ldap-attributename-case.md, services/graph/pkg/identity/ldap.go, services/graph/pkg/identity/ldap_education_class.go, services/graph/pkg/identity/ldap_education_user.go, services/graph/pkg/identity/ldap_group.go
There were a couple of places where we were using the case-sensitive GetAttributeValue method instead of the case-insensitive variant.
Fixes: #10200
=> fix(graph): treat LDAP attribute names case-insensitive everywhere

tests/acceptance/bootstrap/PublicWebDavContext.php, tests/acceptance/config/behat.yml, tests/acceptance/features/apiActivities/shareActivities.feature, tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature, tests/acceptance/features/coreApiSharePublicLink2/updatePublicLinkShare.feature, tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
This PR adds tests to check api activities of public user's actions (add|edit|delete) on a publicly shared resource.
``` feature
Scenario: user checks public's activities on a publicly shared file
Scenario: user checks public's activities on a publicly shared folder
```
- Bug Report: https://github.com/owncloud/ocis/issues/9676
- Locally
- CI
=> [tests-only][full-ci] add tests to check activities after public actions

tests/acceptance/bootstrap/GraphContext.php, tests/acceptance/features/apiActivities/shareActivities.feature
This PR adds test to check activities of project space after updating its public link share(role,expiration date and password).
- Bug Report: https://github.com/owncloud/ocis/issues/10012
- locallly
- CI
=> [tests-only][full-ci] add tests to check activites of space after updating public share link

tests/acceptance/features/apiActivities/activities.feature
This PR adds test to check api activities for edit action on a file.
- Bug Report: https://github.com/owncloud/ocis/issues/10001
- locally
- CI
=> [tests-only][full-ci] add test to check edit activity for a file

tests/acceptance/config/behat.yml, tests/acceptance/features/apiCollaboration/checkFileInfo.feature
This PR adds tests for getting file info of file inside the project drive.
- https://github.com/owncloud/ocis/issues/9844
- Locally
=> [tests-only][full-ci]add tests for check project drive file info

services/proxy/pkg/middleware/signed_url_auth.go
Some reverse proxies replace $ with %24 in the URLs to be signed leading to a mismatch in the signature.
Fixes part of https://github.com/owncloud/ocis/issues/10180
=> Work around a problem with reverse proxies changing URLs being signed

tests/acceptance/TestHelpers/OcmHelper.php, tests/acceptance/bootstrap/OcmContext.php, tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiOcm/deleteFederatedConnections.feature, tests/acceptance/features/apiOcm/share.feature
related https://github.com/owncloud/web/issues/11688
- tests for deleting federated connection
- created bugs: #10213 #10216
=> [test-only] delete connection tests

changelog/unreleased/continue-listing-shares-on-error.md, services/graph/pkg/service/v0/sharedwithme.go, services/graph/pkg/service/v0/utils.go
We now continue listing received shares when one of the shares cannot be statted or converted to a driveItem.
related: https://github.com/owncloud/ocis/issues/10213
=> continue listing shares on error

tests/acceptance/bootstrap/GraphContext.php, tests/acceptance/features/apiActivities/activities.feature
This PR adds tests to check api activities with sort filter (ascending and descending).
``` feature
Scenario: check activity with sort filter
```
- locally
- CI
=> [tests-only][full-ci] add test to check api activities with sort filter

tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/bootstrap/SpacesTUSContext.php, tests/acceptance/bootstrap/WebDavLockingContext.php
Use existing methods to get the space or space-id and remove unnecessary ones
=> [tests-only] use existing method to get space

tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiCollaboration/wopi.feature, tests/acceptance/features/apiOcm/share.feature
related https://github.com/owncloud/ocis/pull/10060
https://github.com/owncloud/ocis/issues/10051
cc @2403905
=> [test-only] add federated users to space

.drone.star, tests/acceptance/bootstrap/CliContext.php, tests/acceptance/features/cliCommands/uploadSessions.feature
This PR adds test for CLI command related to uploads sessions.
Test scenario covered:
```feature
Scenario: user lists all upload sessions
Scenario: user lists all upload sessions that are currently postprocessing
Scenario: user lists all upload sessions that are infected by virus
Scenario: user lists all expired upload sessions
Scenario: user cleans all expired upload sessions
```
- https://github.com/owncloud/ocis/issues/10167
=> [tests-only][full-ci] add tests for CLI command uploads sessions

changelog/unreleased/fix-use-existing-thumbnails.md, services/thumbnails/pkg/service/grpc/v0/service.go
Thumbnails were  re-created even if we already had a matching thumbnail in the storage.
Seem that this was introduced with https://github.com/owncloud/ocis/pull/9299
=> Don't re-create thumbnail if we have one already

changelog/unreleased/fix-thumbnail-ratelimit.md, ocis-pkg/service/grpc/handler/ratelimiter/ratelimiter.go, ocis-pkg/service/grpc/option.go, ocis-pkg/service/grpc/service.go, services/thumbnails/pkg/command/server.go, services/thumbnails/pkg/config/defaults/defaultconfig.go, services/thumbnails/pkg/config/grpc.go, services/thumbnails/pkg/config/http.go, services/thumbnails/pkg/server/grpc/option.go, services/thumbnails/pkg/server/grpc/server.go, services/thumbnails/pkg/server/http/option.go, services/thumbnails/pkg/server/http/server.go, services/webdav/pkg/service/v0/service.go
The `THUMBNAILS_MAX_CONCURRENT_REQUESTS` setting was not working correctly. Previously it was just limiting the number of concurrent thumbnail downloads. Now the limit is applied to the number thumbnail generations requests.
Related issue https://github.com/owncloud/enterprise/issues/6612#issuecomment-2389007634
=> move thumbnailer ratelimiter to grpc service

docs/helpers/env_vars.yaml, docs/services/_index.md
* When readers find the services in dev docs, we now add a note that this is dev docs related and they should go for the admin docs if not particular searching for dev stuff. Helps clarifying issues when a reader has questions. Locally tested, renders fine.
* By running the make command, the env_vars.yaml file got updated too. No harm to merge it as it anyways a regular task.
=> [docs-only] Add short description in dev docs for services

changelog/unreleased/enhancement-load-idp-logo-from-theme.md, services/idp/src/App.jsx, services/idp/src/components/ResponsiveScreen.jsx, services/idp/src/infiniteScaleContext.js
- Fixes https://github.com/owncloud/web/issues/11603
- test case 1:
- test case 2:
- ...
=> Use idp logo from theme

changelog/unreleased/fix-thumbnail-ratelimit.md, services/webdav/pkg/service/v0/service.go
We're now setting a 'Retry-After' in the webdav response when the  thunbnailer is rate limiting the requests. For now the timeout is just  a random number between 1 and 15 seconds.
=> fix(webdav): Set Retry-After header for 429 responses

services/idp/Makefile
We're always using the logo from the theme now so the logo.svg is not needed anymore.
Followup of https://github.com/owncloud/ocis/pull/10274 where the reference to the logo.svg got removed.
=> fix: don't fetch idp logo.svg anymore

deployments/examples/ocis_full/docker-compose.yml
Updating the traefik image version (patch only, 3.1.2 -> 3.1.6) for our `ocis_full` deployment example
=> [docs-only] Update traefik image in ocis_full deployment

.drone.star
1. running k6 tests automatically in CI during the release process
for that we need
- create empty PR with `[k6-test] `title  
2. do not fail `ocis-log` and `open-grafana-dashboard` if `k6-load-test` has exit 1. related https://github.com/owncloud/cdperf/pull/69
3. added to info how to run k6 test to ocis release process doc [how to run k6 test]( https://infinite.owncloud.com/pdf-viewer/project/engineering/oCIS%20Release%20Process/QA-rollingReleaseProcess.pdf?fileId=31e6d44f-f373-557c-9ab3-1748fc0c650d%244994cd9c-1c17-4254-829a-f5ef6e1ff7e3%217ce4f911-5274-400e-a9ef-bd8c564ccff4&contextRouteName=files-spaces-generic&contextRouteParams.driveAliasAndItem=project%2Fengineering%2FoCIS%20Release%20Process&contextRouteQuery.fileId=31e6d44f-f373-557c-9ab3-1748fc0c650d%244994cd9c-1c17-4254-829a-f5 …
=> [k6-test]trigger k6 test in CI

ocis-pkg/handlers/checker.go, services/nats/pkg/server/debug/server.go
This PR adds health & readiness checks for the nats service
=> add nats checks

tests/acceptance/bootstrap/CliContext.php, tests/acceptance/features/cliCommands/uploadSessions.feature
This PR adds test to restart upload sessions using CLI command.
```feature
Scenario: restart upload sessions that are processing
Scenario: restart specific upload sessions
```
- https://github.com/owncloud/ocis/issues/10167
=> [tests-only][full-ci] added test to restart upload sessions using CLI command

changelog/unreleased/secure-ocm-by-default.md, services/ocm/pkg/config/defaults/defaultconfig.go
=> use secure config defaults for OCM

.drone.star
=> [tests-only] ci: enable e2e pipelines

changelog/unreleased/template-conversions-for-apps.md, services/collaboration/pkg/connector/fileconnector.go, services/collaboration/pkg/connector/fileconnector_test.go, services/collaboration/pkg/connector/fileinfo/onlyoffice.go, services/collaboration/pkg/middleware/wopicontext.go, services/collaboration/pkg/middleware/wopicontext_test.go, services/collaboration/pkg/server/http/server.go, services/collaboration/pkg/service/grpc/v0/service.go, services/collaboration/pkg/service/grpc/v0/service_test.go
Adds server-side template processing for WebOffice
We are supporting the following mime types:
- **MimeType:** `application/vnd.ms-word.template.macroenabled.12`
**TargetExtension:** `docx`
- **MimeType:** `application/vnd.oasis.opendocument.text-template`
**TargetExtension:** `docx`
- **MimeType:** `application/vnd.openxmlformats-officedocument.wordprocessingml.template`
**TargetExtension:** `docx`
- **MimeType:** `application/vnd.oasis.opendocument.spreadsheet-template`
**TargetExtension:** `xlsx`
- **MimeType:** `application/vnd.ms-excel.template.macroenabled.12`
**TargetExtension:** `xlsx`
- **MimeType:** `application/vnd.openxmlformats-officedocument.spreadsheetml.template`
**TargetExtension:** `xlsx`
- **MimeType:** `application/vnd.oasis.opendocument.presentation-template` …
=> Template Files for WebOffice

ocis-pkg/checks/checkgrpc.go, ocis-pkg/checks/checkhttp.go, ocis-pkg/checks/checknats.go, ocis-pkg/checks/checktcp.go, ocis-pkg/handlers/checker.go, ocis-pkg/handlers/checker_test.go, services/activitylog/pkg/server/debug/server.go, services/antivirus/pkg/server/debug/server.go, services/audit/pkg/server/debug/server.go, services/clientlog/pkg/server/debug/server.go, services/eventhistory/pkg/server/debug/server.go, services/frontend/pkg/command/health.go, services/graph/pkg/server/debug/server.go, services/idp/pkg/server/debug/server.go, services/invitations/pkg/server/debug/server.go, services/nats/pkg/server/debug/server.go, services/notifications/pkg/server/debug/server.go, services/ocs/pkg/server/debug/server.go, services/proxy/pkg/server/debug/server.go, services/search/pkg/server/debug/server.go, services/settings/pkg/server/debug/server.go, services/sse/pkg/server/debug/server.go, services/thumbnails/pkg/server/debug/server.go, services/userlog/pkg/server/debug/server.go, services/web/pkg/server/debug/server.go, services/webdav/pkg/server/debug/server.go, services/webfinger/pkg/server/debug/server.go
WIP
-  https://github.com/owncloud/ocis/issues/10281
- test case 1:
- test case 2:
- ...
=> enhancement: simplify ready and health check handler usage

changelog/unreleased/fix-group-sharing-panic.md, services/frontend/pkg/command/events.go
This is a mixed lot of share related fixes which weve found during load testing:
- it bumps reva
- it reduces the share auto accept errors during load testing
- Fixes https://github.com/owncloud/ocis/issues/10036#issuecomment-2346023045
- load tests
=> chore|bugfix: mixed sharing errors lot

tests/acceptance/features/apiOcm/share.feature
This PR adds test to list permissions of a resource shared to a federated user.
``` feature
Scenario: user lists permissions of a resource shared to a federated user
```
- BUg Report: https://github.com/owncloud/ocis/issues/9898
- locally
- CI
=> [tests-only][full-ci] add test to list permissions of a resource shared to a federated user

services/collaboration/README.md
References: https://github.com/owncloud/docs-ocis/pull/1014 (Fix envvar name in collaboration service)
Documentation for collaboration refers to
`COLLABORATION_APP_WOPISRC` instead of `COLLABORATION_WOPI_SRC`
=> [docs-only] Fix envvar name in collaboration service readme

tests/acceptance/bootstrap/FilesVersionsContext.php, tests/acceptance/config/behat.yml, tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature, tests/acceptance/features/coreApiVersions/disableFileVersioning.feature
This PR has added tests for checking file version when version is disabled using config
- https://github.com/owncloud/ocis/issues/10095
- locally
=> [tests-only][full-ci] Add tests for version disable config

tests/acceptance/bootstrap/CliContext.php, tests/acceptance/features/cliCommands/uploadSessions.feature
This PR adds the test to clean upload sessions that are not processing using CLI command.
```feature
Scenario: clean all upload sessions that are not processing
```
- https://github.com/owncloud/ocis/issues/10167
=> [tests-only][full-ci] add test to clean upload sessions that are not processing using CLI command

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiOcm/share.feature
This PR adds ocm test to check activities of a resource from personal drive shared to a federated user.
``` feature
Scenario: local user shares resources from project space to federation user
```
- locally
- CI
=> [tests-only][full-ci] add test to share project drive's resource to a federated user

changelog/unreleased/fix-activitylog-issues.md, services/activitylog/pkg/service/http.go, services/activitylog/pkg/service/service.go
Fixes the `max payload exceeded` error
Also speeds up fetching of activities when a limit is set.
Fixes https://github.com/owncloud/ocis/issues/9462
=> Fix Activitylog Issues

changelog/unreleased/fix-panic-nats.md, services/idm/pkg/command/server.go, services/nats/pkg/command/server.go, services/nats/pkg/server/nats/nats.go, services/postprocessing/pkg/command/server.go
- Fixes https://github.com/owncloud/ocis/issues/10360
- test case 1:
- test case 2:
- ...
=> Fix panic when stopping the nats

changelog/unreleased/postprocessing-events.md, services/postprocessing/pkg/config/config.go, services/postprocessing/pkg/config/defaults/defaultconfig.go, services/postprocessing/pkg/postprocessing/postprocessing.go, services/postprocessing/pkg/service/service.go
We increased the number of go routines that pull events from the queue to three and made the number off workers configurable. Furthermore, the postprocessing delay no longer introduces a sleep that slows down pulling of events, but asynchronously triggers the next step.
related: https://github.com/owncloud/ocis/issues/10259
To make more options like MaxAckPending configurable we need to make changes to go micro and reva. Task for a subsequent PR.
=> Postprocessing events

services/settings/pkg/config/config.go
Fixes: #10359 (Settings service: 2 envvars needed to be added to existin ones)
This PR fixes that the settings service has two envvars that do not start with `SETTINGS_` making these envvars unfindable. There is NO code change!
Note that the original (wrong named) envvars are not marked for deprecation which could/should be done but is not a hard requirement.
Prepared as requested in the referenced issue, merging whenever this fits.
=> [docs-only] ADDING 2 envvars to existing ones in settings service

tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/bootstrap/WebDav.php, tests/acceptance/features/apiActivities/activitiesByFileId.feature
This PR adds test to check add, edit, rename and move activities of a file using file-id path.
``` feature
Scenario: check add activity for a file using file-id
Scenario: check edit activity for a file using file-id
Scenario: check rename activity for a file using file-id
Scenario: check move activity for a file using file-id
```
- Part of:  https://github.com/owncloud/ocis/issues/9543
- Bug Report: https://github.com/owncloud/ocis/issues/9744
- locally
- CI
=> [tests-only][full-ci] add test to check add, edit, rename & move activities for a file using file-id path

services/gateway/README.md
References:
#9490 (set the configured protocol transport for service metadata)
#10362 ([docs-only] ADDING 2 envvars to existing ones in settings service)
Note that 10362 is not mandatory, but if merged timely, we need to update this PR to fix the envvar names.
Based on a discussion with @butonic, the current readme text needs some sharpening and an overview what is meant with that (experimental) change.
=> [docs-only] Update gateway readme

tests/acceptance/config/behat.yml, tests/acceptance/features/cliCommands/uploadSessions.feature
This PR adds the test to clean the upload sessions that are not in postprocessing and not virus infected.
```bash
ocis storage-users uploads sessions --processing=false --has-virus=false --clean
```
- https://github.com/owncloud/ocis/issues/10167
=> [tests-only][full-ci] added test to clean upload sessions that are not in postprocessing and not infected by virus

changelog/unreleased/sse-keepalive.md, services/sse/README.md, services/sse/pkg/config/config.go, services/sse/pkg/service/service.go
To prevent intermediate proxies from closing the SSE connection admins can now configure a `SSE_KEEPALIVE_INTERVAL`.
=> make sse keepalive interval configurable

changelog/unreleased/fix-put-relative.md, services/collaboration/pkg/connector/connector.go, services/collaboration/pkg/connector/fileconnector.go, services/collaboration/pkg/connector/fileconnector_test.go
Bugfix: Fix put relative wopi operation for microsoft
We fixed a bug in the put relative wopi operation for microsoft. The response now contains the correct properties.
- test case 1:
- test case 2:
- ...
=> fix: add missing urls to putRelative

tests/acceptance/bootstrap/TrashbinContext.php
I have uncommented and removed `TODO` because I don't find anything that should be done here. The comment isn't that clear. `Deeper structure` might suggest making sure the code works for files deep inside the folders, but when I tried creating files and deleting them, the code seemed to work. 
- Part of https://github.com/owncloud/ocis/issues/10389#event-14942395659
- test case 1:
- test case 2:
- ...
=> [tests-only]removed to do comment inside Trashbin

changelog/unreleased/fix-remove-non-working-ocm-setting.md, services/ocm/pkg/config/config.go, services/ocm/pkg/config/defaults/defaultconfig.go, services/ocm/pkg/revaconfig/config.go
The feature never really worked correctly and it's added value is at least arguable.
I think we do not need to go through the usual deprecation cycle here since the feature was not really working at any time. If you disagree please  holler.
For details see  #10355
=> Remove 'OCM_OCM_PROVIDER_AUTHORIZER_VERIFY_REQUEST_HOSTNAME' setting

services/thumbnails/README.md
References: https://github.com/owncloud/ocis/pull/10310#issuecomment-2440339813
Add macOS libvips build dependencies for ease of building ocis with vips enabled.
=> [docs-only] Add libvips build dependencies for macOS

.golangci.yml, changelog/unreleased/registry-cache-fixes.md, go.mod, go.sum, vendor/go-micro.dev/v4/registry/cache/cache.go, vendor/modules.txt
We now invalidate cache entries when any of the nodes was not updated.
Upstream PR in https://github.com/micro/go-micro/pull/2736
=> registry cache fixes

tests/acceptance/TestHelpers/SetupHelper.php, tests/acceptance/bootstrap/FeatureContext.php, tests/acceptance/config/behat.yml
Delete to-do in behat config. `ocPath` is no longer in use in our testcode and baseurl is not `http://localhost:8080` 
- Part of https://github.com/owncloud/ocis/issues/10389
=> [tests-only][full-ci]removed to do comment-in-behat-config

changelog/unreleased/fix-memlimit-loglevel.md, ocis-pkg/shared/memlimit.go
set the memlimit default loglevel to error.
- Fixes [<issue_link>](https://github.com/owncloud/ocis/issues/10428)
- test case 1:
- test case 2:
- ...
=> set the memlimit default loglevel to error

changelog/unreleased/fix-ocm-data-server-url.md, services/ocm/pkg/config/config.go, services/ocm/pkg/config/defaults/defaultconfig.go, services/ocm/pkg/revaconfig/config.go
=> fix(ocm): add data_server_url to ocm storage provider

deployments/examples/ocis_ldap/docker-compose.yml
during the upgrade testing https://github.com/owncloud/ocis/issues/10373 I found that all created users and groups are gone after ocis update
- we added volumes to docker ldap example deployments
=> add volume to ldap to keep users and groups

changelog/unreleased/restart-postprocessing.md, services/postprocessing/README.md, services/postprocessing/pkg/command/postprocessing.go, services/storage-users/pkg/command/uploads.go
Allows differentiating between "restart" and "resume" postprocessing
=> Restart Postprocessing Properly

changelog/unreleased/fix-proofkeys-proxy.md, services/collaboration/pkg/middleware/proofkeys.go
Bugfix: Respect proxy url when validating proofkeys
We fixed a bug where the proxied wopi URL was not used when validating proofkeys. This caused the validation to fail when the proxy was used.
- Relates to https://github.com/owncloud/enterprise/issues/6790 
- Tested with the WOPI online validator of microsoft365
=> fix: proofkeys validation with proxy

.drone.star, services/collaboration/pkg/config/app.go, services/collaboration/pkg/config/defaults/defaultconfig.go, services/collaboration/pkg/connector/fileconnector.go, services/collaboration/pkg/connector/fileconnector_test.go, services/collaboration/pkg/helpers/registration.go, services/collaboration/pkg/service/grpc/v0/service.go, services/collaboration/pkg/service/grpc/v0/service_test.go
Introduce the `Provider` option to handle some differences between web office products. This will be used instead of the `Name`. Note that the `Name` will still be used in other places such as service names, and it will be shown in the web interface.
The intention is to provide a bit of extra branding: you could have a specific Collabora installation fully customized and branded to your liking, so you could use `BBox` as `Name` and keep `Collabora` as `Provider`.
**Note**: There are some issues with the naming used as `Name`, so it's highly recommended to use only alphanumeric chars. Spaces are known to cause issues.
https://github.com/owncloud/ocis/issues/10306
We need to distinguish between the name and the provider.
- test case 1:
- test case 2:
- ...
Need to …
=> feat: include a provider option to allow custom app names

changelog/unreleased/fix-get-lock-header.md, services/collaboration/pkg/connector/fileconnector.go, services/collaboration/pkg/connector/fileconnector_test.go
Bugfix: Return wopi lock header in get lock response
We fixed a bug where the wopi lock header was not returned in the get lock response. This is now fixed and the wopi validator tests are passing.
- test case 1:
- test case 2:
- ...
=> fix: wopi lock header in get lock response

deployments/examples/ocis_full/onlyoffice.yml
Just adding two comments in `onlyoffice.yml` what to do if one wants to use oo-enterprise edition.
Because this change is up to the user, we (currently) do not provide any `.env` handling.
=> [docs-only] Add comment in ocis_full / onlyoffice.yml

services/collaboration/pkg/config/app.go, services/collaboration/pkg/config/defaults/defaultconfig.go, services/collaboration/pkg/connector/fileconnector.go, services/collaboration/pkg/connector/fileconnector_test.go
Use only the app name for the lock. The lock owner should show `OnlyOffice` (the app name) instead of `com.github.owncloud.collaboration.OnlyOffice` (the lock name + app name)
https://github.com/owncloud/web/issues/11008
Manually checked with a propfind request. It shows just the app name
* The `LockName` configuration option becomes unused with this change. We can remove the option.
=> feat: use only the app name in order to name the lock

services/sse/pkg/config/config.go
The `SSE_KEEPALIVE_INTERVAL` envvar had a "wrong" introduction version. it should be `7.0.0` as all other have too.
=> [docs-only] SSE_KEEPALIVE_INTERVAL envvar version consistenty

docs/helpers/env_vars.yaml
When running `make -C docs docs-generate` , the `env_vars.yaml` file only gets new or updated items, but items are not automatically removed, or deprecation infos where the envvar stays but value changes do also do not get updated. This must be done manually - with this PR.
Necessary for the added/removed envvar handling for ocis 7.
**Removing:**
ANTIVIRUS_ICAP_SCAN_TIMEOUT
FRONTEND_ENABLE_RESHARING
GRAPH_ENABLE_RESHARING
SHARING_ENABLE_RESHARING
STORAGE_SYSTEM_OCIS_METADATA_BACKEND
WEB_ASSET_PATH
=> [docs-only] Remove/fix deprecated items from env_vars.yaml

changelog/unreleased/concurrent-autoaccept.md, services/frontend/pkg/command/events.go, services/frontend/pkg/config/config.go, services/frontend/pkg/config/defaults/defaultconfig.go
Shares for groups are now concurrently accepted. Tha default of 25 goroutinges can be changed with the new `FRONTEND_MAX_CONCURRENCY` environment variable.
=> concurrent autoaccept

changelog/unreleased/fix-backup-consistency-cmd.md, ocis/pkg/backup/backup.go
'ocis backup consistency' was stumbling over revision (and trash) nodes whose timestamp lacked the nanosecond component (which happens if the nanoseconds of the mtime are 0)
Fixes: #9498
=> fix: 'ocis backup consistency' file regex

changelog/unreleased/collaboration-product-name.md, services/collaboration/pkg/config/defaults/defaultconfig.go
This is mostly to help with the upgrade from OCIS 6 to 7. The `COLLABORATION_APP_PRODUCT` is new in OCIS 7 and is needed in order to identify the target product (Collabora, OnlyOffice) and distinguish it from the app name, which could be a brand (CoolBox3, PrivateOffice, etc)
In OCIS 6, the `COLLABORATION_APP_NAME` acted as product name, so it was mostly limited to "Collabora", "OnlyOffice" and "Microsoft" values, but this won't be the case any longer.
The problem comes during the upgrade, where the product name might not be filled yet. This means that an "OnlyOffice" product (set in `COLLABORATION_APP_NAME`) might be mistakenly consider as a "Collabora" product (the default). This mistake could cause issues: so far we've detected that the "OnlyOffice" editor would open in view-only mode …
=> fix: copy app name if product name isn't provided

docs/helpers/changed_envvars.py, docs/services/general-info/env-var-deltas/5.0.0-7.0.0-added.adoc, docs/services/general-info/env-var-deltas/5.0.0-7.0.0-deprecated.adoc, docs/services/general-info/env-var-deltas/5.0.0-7.0.0-removed.adoc, docs/services/general-info/env-var-deltas/make-adoc-table-from-python.txt
This PR:
* Adds a Python script generating the delta files automatically based on configuration. Note that we can compare any version that has been tagged or branched including master after v6! This means we do not need to wait until releasing has been done.
* Adds added/removed/deprecated adoc files for the admin docs. This is very important to finalize the upgrade/migration guide
Note that the respective .md files can only be created AFTER releasing as this requires (currently) a semver version to be accessed which mster is not.
I will file a second PR with some necessary doc helper stuff.
NOTE: To make this PR work, else hugo wants to render adoc files but has no parser configured, we needed to adapt config.yaml from hugo at its source to exclude directories: …
=> [docs-only] Create envvar delta files after v5 to master (v7.0.0)

changelog/unreleased/fix-gateway-nats-checks.md, ocis-pkg/registry/register.go, services/gateway/pkg/server/debug/server.go
We now only check if nats is available when the gateway actually uses it. Furthermore, we added a backoff for checking the readys endpoint.
=> only check nats if it is used

changelog/unreleased/concurrent-autoaccept.md, services/frontend/pkg/command/events.go
not only update multiple members concurrently but also handle multiple events concurrently
=> fix autoaccept concurrency

changelog/unreleased/concurrent-userlog.md, services/userlog/pkg/config/config.go, services/userlog/pkg/config/defaults/defaultconfig.go, services/userlog/pkg/service/service.go, services/userlog/pkg/service/service_suit_test.go, services/userlog/pkg/service/service_test.go
We now start multiple go routines that process events. The default of 5 goroutines can be changed with the new `USERLOG_MAX_CONCURRENCY` environment variable.
related https://github.com/owncloud/ocis/issues/10036#issuecomment-2345943669
=> concurrent userlog

changelog/unreleased/fix-ocm-file-preview.md, services/graph/pkg/service/v0/api_driveitem_permissions.go, services/graph/pkg/service/v0/api_driveitem_permissions_links.go, services/graph/pkg/service/v0/api_drives_drive_item.go, services/graph/pkg/service/v0/utils.go, services/graph/pkg/service/v0/utils_test.go, vendor/google.golang.org/protobuf/internal/msgfmt/format.go, vendor/google.golang.org/protobuf/testing/protocmp/reflect.go, vendor/google.golang.org/protobuf/testing/protocmp/util.go, vendor/google.golang.org/protobuf/testing/protocmp/xform.go, vendor/modules.txt
File shares need to use the base64 encoded path as the opaqueID, while for folder shares the base64 encode '/' should work.
Fixes #10495
=> fix(graph): Use the correct opaqueId when Statting OCM shares

services/graph/pkg/service/v0/api_driveitem_permissions.go
Federated users are sharing the cache with regular users. So can't we need to check the user type to determine if the user is federated.
Fixes #10488
=> fix(graph/ocm): Fix ocm share creation when user is in cache

ocis/docker/Dockerfile.linux.amd64, ocis/docker/Dockerfile.linux.arm64, ocis/docker/Dockerfile.linux.debug.amd64
References:
https://github.com/owncloud/docs-ocis/pull/1029 (Migration and Update Guide for 5 to 7)
https://github.com/owncloud/ocis/issues/10373#issuecomment-2468525545 (Release 7.0.0)
Add `patch` command to the ocis image.
=> add patch command to the ocis image

changelog/unreleased/fix-auth-app.md, services/auth-app/pkg/service/service.go
We fixed a user id and mane mismatch in the impersonated auth-app API request
- Fixes [#10292](https://github.com/owncloud/ocis/issues/10292)
- test case 1:
- test case 2:
- ...
=> fix impersonated request user mismatch

ocis/pkg/init/functions.go, ocis/pkg/init/init.go
This PR fixes
- missing remove of tmp file if the patch is empty on `ocis init --diff`
- generate an uuid for the collaboration wopi secret if the old config does not contain it.
refs  #10560 
refs #10444
=> Fix ocis init

changelog/unreleased/max-concurrency.md, services/frontend/pkg/config/defaults/defaultconfig.go, services/userlog/pkg/config/defaults/defaultconfig.go
Fixes the performance degradation.
Fixes https://github.com/owncloud/ocis/issues/10545
=> Performance Degradation

tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/features/apiActivities/activitiesByFileId.feature
This PR adds tests to check activities of destination file and folder after moving a file using it's file-id into a folder.
``` feature
Scenario: check activities of destination folder after moving a file into it using file-id
Scenario: check activities of destinaton file and folder after moving a 0 byte file using file-id
Scenario: check activities of destinaton file and folder after moving a file by renaming destination file using file-id
Scenario: check activities of destinaton file and folder after moving a 0 byte file by renaming destination file using file-id
```
- https://github.com/owncloud/ocis/issues/9543#issuecomment-2431703972
- locally
- CI
=> [tests-only][full-ci] add test to check activities of destination file and folder by moving a file using file-id

ocis-pkg/shared/errors.go
When there is an issue reported from a `ocis <service-name> health` command, we should advice to run `ocis init --diff` and not `ocis init`. The diff option will only generate a patchable delta file which can be reviewed and applied while an init without diff will overwrite the config.
We do the same when upgrading...
=> [docs-only] Improve error messages for health command output

changelog/unreleased/limit-sharing-workers.md, services/sharing/pkg/config/config.go, services/sharing/pkg/config/defaults/defaultconfig.go, services/sharing/pkg/revaconfig/config.go
We now restrict the number of workers that look up shares to 5. The number can be changed with `SHARING_USER_JSONCS3_MAX_CONCURRENCY`.
=> limit the number of workers of the jsoncs3 share manager

changelog/unreleased/fix-node-cache-ttl-updates.md, go.mod, go.sum, vendor/go-micro.dev/v4/registry/cache/cache.go, vendor/modules.txt
We now only udpate the TTL of the node that is created or updated.
=> fix node cache ttl updates

docs/services/general-info/env-var-deltas/5.0.0-7.0.0-added.adoc
Fixes: #10576 (Added envvars table needs an update due to newly added envvars)
The added table needed an update after merging a new envvar.
=> [docs-only] Update the added envvars adoc table

changelog/unreleased/max-concurrency.md, docs/helpers/env_vars.yaml, services/sharing/pkg/config/defaults/defaultconfig.go
Like for `frontend` and `userlog` use only 1 worker for `sharing` service
=> Use 1 Worker for sharing 

changelog/unreleased/reuse-go-micro-service.md, services/graph/pkg/service/v0/drives.go, services/graph/pkg/service/v0/graph_test.go
go micro clients must not be reinitialized. The internal selector will spawn a new go routine to watch for registry changes.
=> reuse go-micro service clients

changelog/unreleased/collaboration-public-keys.md, services/collaboration/pkg/proofkeys/handler.go
Return an error properly if we can't get the public keys.
In addition, ensure the new keys are cached to prevent unneeded hits to the "/hosting/discovery" endpoint, and log when we're requesting new keys.
Steps to reproduce the original issue seems unclear. WOPI requests are expected to come from the WOPI app (OnlyOffice in this case), and those should be the only ones triggering the issue, so it shouldn't be possible that a request to the discovery endpoint fails when the service is making a request. There might be some race condition, but it seems weird.
https://github.com/owncloud/ocis/issues/10588
Wrong error value was causing a panic because we assume we got the keys although it wasn't true.
Note that you can adjust the cache time of the public keys with …
=> fix: properly return an error and use cache for public keys if possible

changelog/unreleased/log-grpc-requests.md, ocis-pkg/service/grpc/service.go
When log level is set to debug we will now also log grpc requests.
This adds lines like these (below is a full page reload)
```
2024-10-29T12:52:52+01:00 DBG grpc call content-type=application/grpc+proto duration=1.005583 endpoint=RoleService.ListRoleAssignments headers=null line=/home/jfd/Repositories/ocis/ocis-pkg/service/grpc/service.go:113 method=RoleService.ListRoleAssignments service=com.owncloud.api.settings traceid=67e577dbfcb349c565b8fc29c79550bc
2024-10-29T12:52:52+01:00 DBG grpc call content-type=application/grpc+proto duration=0.71773 endpoint=RoleService.ListRoleAssignments headers=null line=/home/jfd/Repositories/ocis/ocis-pkg/service/grpc/service.go:113 method=RoleService.ListRoleAssignments service=com.owncloud.api.settings traceid=9e886ffd9dd79a1459b1ead2df1e3a46 …
```
=> log grpc requests in debug mode

changelog/unreleased/fix-thumbnails-statuscode.md, services/thumbnails/pkg/service/grpc/v0/service.go
Return 403 instead of 500 when the image is too large (in dimensions or file size).
=> Fix thumbnails status code

tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature, tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature, tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
This pull request focuses on refactoring the `When` steps and their corresponding step definitions within the test suite. The changes are specifically related to the operations of moving, copying, and renaming files and folders.
- Refactored the structure of `(moves|copies) using file-id` actions
- Removed the `renames using file-id` action from the existing step definition and created a separate step definition specifically for renaming files.
These changes are made to align the existing test codes with the [PR #10409](https://github.com/owncloud/ocis/pull/10409) ensuring consistency across the test suites, making it easier to understand, maintain, and extend in the future.
- locally
- CI
=> [tests-only][full-ci] refactor `When` steps and step defns while moving, copying and renaming files and folders

docs/architecture/collaborative-storage.md
Notes about components of a storage driver, especially collaborative storage.
Lots more to add and clarify probably. Maybe not ready to merge.
=> [docs-only] Initial commit of collaborative storage notes

tests/acceptance/bootstrap/TUSContext.php, tests/acceptance/bootstrap/WebDav.php, tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature, tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature, tests/acceptance/features/coreApiVersions/fileVersions.feature, tests/acceptance/features/coreApiWebdavUpload/uploadFile.feature, tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtime.feature
```feature
Scenario Outline: upload a file with the same mtime and same content multiple times (atleast 3 times)
Scenario Outline: upload a file with the same mtime and different content multiple times (atleast 3 times)
```
- Test coverage for https://github.com/owncloud/ocis/issues/10496
- test environment: :raised_hands: :robot:
=> [tests-only] add tests to check file uploads with same mtime and different content

tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/bootstrap/SpacesTUSContext.php, tests/acceptance/config/behat.yml, tests/acceptance/features/apiCors/cors.feature, tests/acceptance/features/apiOcm/share.feature, tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature, tests/acceptance/features/cliCommands/uploadSessions.feature
This PR adds test to upload a file to a shared folder via TUS by a federated user.
``` feature
Scenario: federated user upload file to a shared folder via TUS
```
- Bug Report: https://github.com/owncloud/ocis/issues/10285
- locally
=> [tests-only][full-ci] add test to upload file to a shared folder via TUS by federated user

deployments/examples/ocis_full/collabora.yml, deployments/examples/ocis_full/docker-compose.yml, deployments/examples/ocis_full/onlyoffice.yml
This PR updates the image versions used for our ocis_full deployment examples.
I tested this with my Hetzner deployment and have not found any issue.
=> [docs-only] Update imgage versions for the ocis_full deployment example

services/auth-app/README.md
Fixes: #10605 (Minimal description in dev docs for auth-app token generation via API necessary)
This PR adds the description how to manage tokens using the API.
@ScharfViktor fyi
=> [docs-only] Describe CLI-API commands in auth-app to manage tokens

.drone.star, tests/acceptance/TestHelpers/BehatHelper.php, tests/acceptance/TestHelpers/OcisHelper.php, tests/acceptance/bootstrap/Provisioning.php, tests/acceptance/bootstrap/PublicWebDavContext.php, tests/acceptance/docker/src/run-tests.sh, tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
- remove test env variables that are not required anymore
- error handling ldap user/group creation
- remove unnecessary log lines
- test case 1:
- test case 2:
- ...
=> [tests-only] cleanup unnecessary env variables 

deployments/examples/ocis_full/.env, deployments/examples/ocis_full/clamav.yml, deployments/examples/ocis_full/ocis.yml
As discussed with @micbar and @dragonchaser:
The current situation adding ocis services to the startup caused, that any item added has overwritten other settings made. This is now fixed by adapting the `.env`, `ocis.yml` and `clamav.yml` files accordingly.
=> [docs-only] Fix ocis_full for services to be started manually

services/auth-app/README.md
References: #10620 ([docs-only] Describe CLI-API commands in auth-app to manage tokens)
Just a small capitalization fix for curl commands
=> [docs-only] Fix capitalization of some curl commands

services/proxy/README.md
Fixes: #10623 (Cannot login using OIDC (Authentik) from 6.X to 7.x rc: 401 unauthorized)
This PR adds a CSP description to the proxy readme.
The text is also added to the admin docs via the migration PR.
=> [docs-only] Add CSP to proxy readme

changelog/unreleased/fix-denied.md, services/graph/pkg/config/defaults/defaultconfig.go, services/graph/pkg/service/v0/api_driveitem_permissions.go, services/graph/pkg/service/v0/api_driveitem_permissions_test.go, services/graph/pkg/service/v0/base.go, services/graph/pkg/unifiedrole/conversion.go, services/graph/pkg/unifiedrole/conversion_test.go, services/graph/pkg/unifiedrole/export_test.go, services/graph/pkg/unifiedrole/roles.go, services/graph/pkg/unifiedrole/roles_test.go, services/web/pkg/theme/theme.go
After updating an ocis 5.0.9 to ocis 7.0.0-rc.3, existing denials are breaking the web client.
- test case 1:
- test case 2:
- ...
=> fix: fix deny access to prevent a regression

docs/helpers/env_vars.yaml
For an "unknown" reason, we needed to recreate the `env_vars.yaml` file because new deprecations did not show up.
Discussed with @dragonchaser
=> [docs-only] The env_var.yaml file needs to be recreated

docs/helpers/changed_envvars.py, docs/services/general-info/env-var-deltas/5.0.0-7.0.0-added.adoc, docs/services/general-info/env-var-deltas/5.0.0-7.0.0-deprecated.adoc, docs/services/general-info/env-var-deltas/5.0.0-7.0.0-removed.adoc
The table containing deprecations did not contain additional info like the reason for the deprecation (deprecationInfo). This is now fixed and the table updated.
=> [docs-only] Show more info in deprecation table

tests/acceptance/bootstrap/WebDav.php, tests/acceptance/features/apiOcm/share.feature
This PR adds test to download thumbnail preview of a federated shared image.
``` feature
Scenario: local user downloads thumbnail preview of a federated shared image
```
- Bug Report: https://github.com/owncloud/ocis/issues/10495
- Locally
- CI
=> [tests-only][full-ci] add tests to download thumbnail preview of a federated share image

tests/acceptance/bootstrap/OcmContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiOcm/acceptInvitation.feature, tests/acceptance/features/apiOcm/createInvitation.feature, tests/acceptance/features/apiOcm/deleteFederatedConnections.feature
This PR refactors multiple when steps in OCM test scenarios where it's possible to do so and align the steps with the scenario title.
Originated from https://github.com/owncloud/ocis/pull/10264#issuecomment-2428602642
- Comment: https://github.com/owncloud/ocis/pull/10264#issuecomment-2428602642
- Locally
- CI
=> [tests-only][full-ci] refactor multiple when steps in OCM tests

tests/acceptance/run.sh
`run.sh` could cause bash running into memory issue when the loading a large log file. When running the test with  `DEBUG_ACCEPTANCE_API_CALLS=1` the bash process executing `run.sh` used so much memory (>25GB) that is was finally getting OOM killed.
I was able to track this down to the `echo ${TEMP_CONTENT} > ${TEST_LOG_FILE}` call that rewrites the log file with `null` bytes being removed. I don't quite understand why, but there seems to be an issue with ${} expansion with IFS is set to `""`. Anyway. I've just replaced the code with an `sed` call doing the `null` byte removal inplace now. Should be a lot more efficient as well.
=> Reduce memory footprint in test runner

services/antivirus/README.md
References: https://github.com/owncloud/ocis/issues/6803#issuecomment-2470184180 (antivirus seems to keep files in memory)
We do not have any better approach than the current referenced one.
Better to note it down than nothing.
It is subject of change anyways but an anchor point for next steps.
=> [docs-only] Add memory considerations to the antivirus service

changelog/unreleased/graph-skip-fetching-members.md, services/graph/pkg/identity/cache.go
We now skip fetching group members when they are not needed.
related: https://github.com/owncloud/ocis/issues/10692#issuecomment-2510840046
=> graph skip fetching members

services/graph/pkg/identity/ldap.go, services/graph/pkg/identity/ldap_education_class.go, services/graph/pkg/identity/ldap_group.go
This fixes the 'graph/v1.0/users' endpoint to allow a combination of a memberOf filter in $filter with a search string in $search.
Allowing queries like:
```
$filter=(memberOf/any(m:m/id eq 509a9dcd-bb37-4f4f-a01a-19dca27d9cfa))&$search="example"
```
Fixes: https://github.com/owncloud/enterprise/issues/6600
=> fix(graph): Allow to combine $search and $filter in users query

docs/services/general-info/env-var-deltas/5.0.0-7.0.0-added.adoc, docs/services/general-info/env-var-deltas/5.0.0-7.0.0-deprecated.adoc, docs/services/general-info/env-var-deltas/5.0.0-7.0.0-removed.adoc
Referencing: #10704 ([docs-only] Update env_vars.yaml)
Updated added/removed/deprecated envvars tables + manual fixes
=> [docs-only] Updated added/removed/deprecated envvars tables

changelog/unreleased/thumbnail-create-and-rename.md, services/thumbnails/pkg/thumbnail/storage/filesystem.go
Use a temporary file and then rename in order to prevent a race condition. This should help to prevent getting thumbnails with 0 byte content or with partial content.
According to the documentation, the won't be name collisions in the FS with the temporary files, so every thumbnail will be written into a unique file before trying to rename it to the final file (0 byte or partial content shouldn't happen).
**NOTE:** The previous `os.Create` call creates a file with 0666 permissions. The new `os.CreateTemp` creates the file with 0600 permissions, so the new thumbnails will have different permissions on the FS. This shouldn't cause problems though.
https://github.com/owncloud/ocis/issues/10684
This increases the stability of the system by preventing the error from happening.
Basic case has …
=> fix: use a tmp file and rename to prevent a possible race condition

tests/acceptance/bootstrap/WebDav.php, tests/acceptance/features/apiOcm/share.feature
This PR adds test to share both original and copied folder to a federation user.
``` feature
Scenario: local user shares copied folder to federation user
```
- Bug Report: https://github.com/owncloud/ocis/issues/10488
- Locally
- CI
=> [tests-only][full-ci] add test to share copied folder to remote user

tests/acceptance/TestHelpers/GraphHelper.php, tests/acceptance/TestHelpers/WebDavHelper.php, tests/acceptance/bootstrap/AuthContext.php, tests/acceptance/bootstrap/FeatureContext.php, tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature, tests/acceptance/features/apiSpacesShares/copySpaces.feature, tests/acceptance/features/coreApiAuth/webDavMKCOLAuth.feature, tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature, tests/acceptance/features/coreApiWebdavProperties/copyFile.feature, tests/acceptance/features/coreApiWebdavProperties/setFileProperties.feature, tests/acceptance/features/coreApiWebdavUpload/uploadFile.feature
- removed duplicate step
```diff
-Then for user :sharee the space Shares should contain these files
+Then user :sharee should have a share :share shared by user :sharer from space :space
+Then user :sharee should not have a share :share shared by user :sharer from space :space
```
- fixed tests for reva (https://drone.owncloud.com/cs3org/reva/5743/15/6)
```
Syntax error (JsonException)
...
Type error: FeatureContext::getJsonDecodedResponse(): Return value must be of type array, null returned (Behat\Testwork\Call\Exception\FatalThrowableError)
```
- skipped sharing tests for reva
=> [tests-only][full-ci] fix tests for reva

changelog/unreleased/fix-onlyoffice-file-location.md, services/collaboration/pkg/connector/fileconnector.go, services/collaboration/pkg/connector/fileconnector_test.go, services/collaboration/pkg/helpers/scope.go, services/collaboration/pkg/middleware/wopicontext.go
Fixed the FileInfo.BreadcrumbFolderURL in a collaboration api"
- Fixes [#7004](https://github.com/owncloud/enterprise/issues/7004)
- test case 1:
- test case 2:
- ...
=> fixed the FileInfo.BreadcrumbFolderURL in a collaboration api

changelog/unreleased/me_drives_ocm_shares.md, services/graph/pkg/service/v0/drives.go
OCM shares don't have mountpoints currently. So they're no supposed to show up in the drives list on the graph service.
Fixes: #10689
=> fix(graph): Don't return OCM shares in the drives list

tests/acceptance/TestHelpers/GraphHelper.php, tests/acceptance/bootstrap/FeatureContext.php, tests/acceptance/features/apiOcm/searchFederationUsers.feature, tests/acceptance/features/apiOcm/share.feature, tests/acceptance/features/coreApiWebdavProperties/createFileFolder.feature
Updated the issue tags and test coverage for etag in federation sharing
- https://github.com/owncloud/ocis/issues/9813
- https://github.com/owncloud/ocis/issues/9568
- https://github.com/owncloud/ocis/issues/9534 : https://github.com/cs3org/reva/pull/4823
=> [tests-only] update issue tags

tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSharingNg1/propfindShares.feature
Check the `oc:file-parent` of shares
- Bu report: https://github.com/owncloud/ocis/issues/9933#issuecomment-2388850236
=> [tests-only][full-ci] check parent-id of shares

tests/acceptance/TestHelpers/UploadHelper.php, tests/acceptance/TestHelpers/WebDavHelper.php, tests/acceptance/bootstrap/WebDav.php, tests/acceptance/features/coreApiVersions/fileVersions.feature
This PR removes the `chunkingToUse` variable from the code-base which in turn makes the use of existing TUS chunk upload endpoint by default.
- Fixes: https://github.com/owncloud/ocis/issues/10596
- locally
- CI
=> [tests-only][full-ci] refactor: Set chunking version 1 as default

tests/acceptance/bootstrap/OcisConfigContext.php, tests/acceptance/features/apiSharingNg1/sharedByMe.feature
This PR adds the test to list shares `sharedByMe` after the share role has been disabled, with precondition 
`enable role` -> `share` -> `disable role`
=> [tests-only][full-ci] added test to list shares sharedByMe after the share role has been disabled

tests/acceptance/features/apiOcm/share.feature
This PR adds test to check if federated user can update a shared file after local user updates the role from `Viewer` to `File Editor`
See: https://github.com/owncloud/web/issues/11991#issuecomment-2513801486
``` feature
Scenario: federated user tries to update a shared file after local user updates role
```
- Bug Report: https://github.com/owncloud/ocis/issues/9926
- Locally
- CI
=> [tests-only][full-ci] add test for federated user trying to update shared file after local user updates role

tests/acceptance/features/apiSharingNg1/sharedWithMe.feature
In this PR: 
-  Added the "Denied" role to the list of additional permissions.
- Updated methods to handle the "Denied" role and added assertions to check the presence or absence of shares based on the role.
- Added new scenarios to validate the "Denied" role for both folders and files across Personal and Project spaces.
- Related to: https://github.com/owncloud/ocis/issues/10656
- CI
- Locally
=> [tests-only][full-ci] Tests for sharing resource with Denied role in Personal and Project space

tests/acceptance/features/apiOcm/share.feature
This PR adds test to list the drives by federation user and check that federation shares doesn't get listed.
See: https://github.com/owncloud/ocis/issues/10689#issuecomment-2516587617
``` feature
Scenario: federation user lists ocm shares
```
- Bug report: https://github.com/owncloud/ocis/issues/10689
- Locally
- CI
=> [tests-only][full-ci] add test to list drives by federation user

tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/features/apiOcm/share.feature
This PR adds test to remove access of a shared resource to federated user.
``` feature
Scenario Outline: local user removes access of federated user from a resource
```
- Bug Report: https://github.com/owncloud/ocis/issues/10213
- Locally
- CI
=> [tests-only][full-ci] add tests to remove access of shared resource to federated user

tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/features/apiGraphUserGroup/deleteUser.feature, tests/acceptance/features/apiOcm/share.feature, tests/acceptance/features/apiSpaces/listSpaces.feature, tests/acceptance/features/apiSpaces/spaceManagement.feature
This PR fixes typo in following then steps:
``` feature
And the json responded should not contain a space with name "Shares"
And the json responded should only contain spaces of type "personal"
````
Updated to:
``` feature
And the json response should not contain a space with name "Shares"
And the json response should only contain spaces of type "personal"
````
- Originated from: https://github.com/owncloud/ocis/pull/10753#discussion_r1886620122
- Locally
- CI
=> [tests-only][full-ci] fix typo in `Then` scenario steps

tests/acceptance/features/apiSharingNg1/removeAccessToDrive.feature, tests/acceptance/features/apiSharingNg1/removeAccessToDriveItem.feature
This PR adds the test to remove access to share after the share role has been disabled.
=> [tests-only][full-ci] added test to remove access to share after the share role has been disabled

changelog/unreleased/enhancement-in-app-notifications-filtering.md, services/userlog/pkg/service/filter.go, services/userlog/pkg/service/filter_test.go, services/userlog/pkg/service/service.go, services/userlog/pkg/service/service_test.go
Add filtering of userlog based on settings. Should be merged after https://github.com/owncloud/ocis/pull/10706
- Closes https://github.com/owncloud/ocis/issues/10769
- test environment: localhost
- test case 1: unshare space with user that has in-app notifications for space unshared disabled
=> Add filtering of userlog based on settings

tests/acceptance/bootstrap/ArchiverContext.php, tests/acceptance/features/apiOcm/share.feature
This PR adds test to download files and folders as archive by OCM user
``` feature
Scenario: federated user downloads shared resources as an archive
```
- Bug :https://github.com/owncloud/ocis/issues/10272#issuecomment-2437419295
- locally
- CI
=> [tests-only][full-ci] add test to download files and folders as archive by ocm user

tests/acceptance/features/apiSharingNg1/removeAccessToDrive.feature, tests/acceptance/features/apiSharingNg1/removeAccessToDriveItem.feature
This PR adds the test to remove access to group share after the share role has been disabled.
=> [tests-only][full-ci]added test to delete share access from group after the share role has been disabled

tests/acceptance/bootstrap/AuthContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiAntivirus/serviceAvailabilityCheck.feature, tests/acceptance/features/apiCollaboration/serviceAvailabilityCheck.feature, tests/acceptance/features/apiNotification/serviceAvailabilityCheck.feature, tests/acceptance/features/apiServiceAvailability/serviceAvailabilityCheck.feature
The problem lies in the test code, which is sending requests to the following incorrect URL: https://localhost:9200/ocalhost:9229/healthz and https://localhost:9200/ocalhost:9229/readyz
As a result, the server returns a 200 status code, but the request is not directed to the intended endpoint, causing tests to pass erroneously.
This PR update test code base to send request to proper url
**Note:** This PR isolates the problematic service into a separate scenario for testing. Once issue #10661 is resolved, the scenario separation introduced in this PR should be reverted.
A follow-up QA point has been added in #10316.
Part of 
- https://github.com/owncloud/ocis/issues/10661
- https://github.com/owncloud/ocis/issues/10316
- https://github.com/owncloud/ocis/issues/10715
- locally
=> [full-ci][tests-only] Refactor service health and ready url in tests

tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/features/apiSharingNg1/sharedWithMe.feature
- Added new scenarios to check the share access before and after changing permission role the "Denied" role across Personal and Project spaces.
- Used the `$spaceName`  variable properly inside the function `userShouldOrShouldNotBeAbleToDownloadFileFromSpace` which was unused (was just placed in the params list) previously.
- Related to: https://github.com/owncloud/ocis/issues/10656
- CI 
- Locally
=> [tests-only][full-ci] Tests for checking share access after changing share role to and from "Denied"

tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/features/apiSharingNg1/enableDisablePermissionsRole.feature
This PR adds the test to list the available drives after the share role has been disabled.
=> [tests-only][full-ci]added test to list drives after the share role has been disabled

tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
This PR confirms that `createdDateTime` is not missing in the response while sharing the items via `.../invite` endpoint.
Bug report has been done for drive invitation so this PR only touches resource invitation
- https://github.com/owncloud/ocis/issues/10077
- Related to: https://github.com/owncloud/ocis/issues/8428
- https://github.com/owncloud/ocis/issues/10739
- locally
- CI
=> [tests-only][full-ci] test: check if share creation date is not missing in share invite response

tests/acceptance/features/apiSharingNg1/listPermissions.feature
This PR adds test to try listing permissions of a disabled project space using root endpoint of the graph API.
``` feature
Scenario: user tries to list permissions of a disabled project space using root endpoint
```
- Part of: https://github.com/owncloud/ocis/issues/10727
- Bug: https://github.com/owncloud/ocis/issues/9764
- Locally
- CI
=> [tests-only][full-ci] add test to try listing permissions of a disabled project space

services/settings/pkg/store/defaults/defaults.go, services/settings/pkg/store/defaults/templates.go
References: #10812 (Notification Option Translations)
As discussed with @kobergj, some translation sources need an update to be correct
=> [docs-only] Update settings source strings for translation

deployments/examples/ocis_full/.env
The image needs to be set to production and not to rolling in stable 7.
(empty = production...)
Missed to update this...
=> [docs-only][stable-7.0] ocis_full: point ocis to production and not to rolling

.drone.star, tests/acceptance/bootstrap/SettingsContext.php, tests/acceptance/config/behat.yml, tests/acceptance/features/apiAccountsHashDifficulty/assignRole.feature, tests/acceptance/features/apiGraph/getAssignedRole.feature, tests/acceptance/features/apiSettings/settings.feature
This PR adds test to check the response of settings api endpoints.
``` feature
Scenario: disable auto-sync share
Scenario: assign role to user
Scenario: user lists assignments
Scenario: switch language
Scenario: user lists existing roles
```
- Part of: https://github.com/owncloud/ocis/issues/8800
- Locally
- CI
=> [tests-only][full-ci] add tests to check settings api response

docs/services/general-info/add-translations.md
The translation docs missed a note how and where to manually start a sync process - fixed.
=> [docs-only] Add a note to translation docs how to manual start syncing.

changelog/unreleased/enhancement-mail-notifications-grouping.md, services/notifications/README.md, services/notifications/pkg/command/root.go, services/notifications/pkg/command/send_email.go, services/notifications/pkg/command/server.go, services/notifications/pkg/config/config.go, services/notifications/pkg/config/defaults/defaultconfig.go, services/notifications/pkg/email/composer.go, services/notifications/pkg/email/email.go, services/notifications/pkg/email/templates.go, services/notifications/pkg/service/filter.go, services/notifications/pkg/service/filter_test.go, services/notifications/pkg/service/job.go, services/notifications/pkg/service/persistence.go, services/notifications/pkg/service/sciencemesh.go, services/notifications/pkg/service/service.go, services/notifications/pkg/service/service_test.go, services/notifications/pkg/service/shares.go, services/notifications/pkg/service/spaces.go, services/notifications/pkg/service/splitter.go, services/notifications/pkg/service/splitter_test.go, services/settings/pkg/service/v0/servicedecorator.go
Allow grouping of multiple events in a single email.
Needs to be merged after https://github.com/owncloud/ocis/pull/10838
https://github.com/owncloud/ocis/issues/10793
- test environment: localhost
- test case 1: Test if grouped email can be sent successful (trigger multiple events, run cli command, check mailbox)
=> Grouped email notifications

docs/helpers/changed_envvars.py, docs/services/general-info/env-var-deltas/7.0.0-7.1.0-added.adoc, docs/services/general-info/env-var-deltas/7.0.0-7.1.0-deprecated.adoc, docs/services/general-info/env-var-deltas/7.0.0-7.1.0-removed.adoc
This PR adds new tables for added/deprecated and removed envvars for 7.1
As we integrate 7.1 into 7.0, we need to backport this into 7.0
=> [docs-only] Add new tables for added/deprecated/removed envvars for 7.1 

changelog/unreleased/fix-in-app-notifications-filtering.md, services/userlog/pkg/service/filter.go, services/userlog/pkg/service/filter_test.go
Adjust userlogFilter to also filter PostprocessingStepFinished events
- Fixes https://github.com/owncloud/ocis/issues/10867
=> fix: Filtering of PostprocessingStepFinished events

changelog/unreleased/fix-grouped-mail-notifications-empty-body.md, services/notifications/pkg/command/send_email.go, services/notifications/pkg/service/job.go
Prevent empty email body for grouped email notifications.
- Relates to https://github.com/owncloud/ocis/issues/10793
=> fix: Empty email body for grouped email

changelog/unreleased/consistenly-name-roles.md, services/proxy/pkg/userroles/defaultrole.go, services/settings/pkg/service/v0/settings.go, services/settings/pkg/store/defaults/defaults.go
References: #10870 (Transition from 'Guest' user to 'User Light' was incomplete in terms of translatable strings)
This PR does most likely not fix the issue completely, but contributes to make things consistable and understandable.
The change was defined in: https://github.com/owncloud/ocis/blob/9e1fe81069b526d76ed4da5d8044cb03ca3e1a4c/changelog/3.0.0_2023-06-06/rename-guest-role.md?plain=1
Note that the UUID's of the roles are the same.
* Changing:
`roleId = settingsService.BundleUUIDRoleGuest` --> `roleId = settingsService.BundleUUIDRoleUserLight`
* Replacing
`BundleUUIDRoleGuest` with `BundleUUIDRoleUserLight` in `services/settings/pkg/service/v0/settings.go`
* Adding comments
=> Rename role for consistency (leftover from change in v3)

tests/acceptance/features/apiSharingNg1/enableDisablePermissionsRole.feature
This PR adds test to update share role to an existing role after the assigned share role is disabled. This PR covers the test for updating the roles to:
- `Secure Viewer` to other existing permissions role (Personal Space resource)
- `Secure Viewer` to other existing permissions role (Project Space resource)
- `Space Editor Without Versions` to other existing permissions role
Currently, trying to update the permissions role from `Denied` to other existing permissions role takes more than `30` seconds to sync, which makes the tests execution longer. So, currently scenario related to  updating the permissions role from `Denied` to other roles has been removed from this PR and will be added on the next PR and move this PR forward as this PR has been on hold for long time.
- …
=> [tests-only][full-ci] added test to update share role to existing role after the assigned share role is disabled

tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/features/apiSharingNg1/filterPermissions.feature
This PR  add tests for list permission with filter and select query for personal space 
Query `$select=@libre.graph.permissions.actions.allowedValues` has bug pined in issue so not covered in this PR
- https://github.com/owncloud/ocis/issues/10728
- locally
=> [tests-only][full-ci]Add tests for lists permission with query for personal space

tests/acceptance/config/behat.yml, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiAccountsHashDifficulty/assignRole.feature, tests/acceptance/features/apiCors/cors.feature, tests/acceptance/features/apiGraph/getAssignedRole.feature, tests/acceptance/features/apiSettings/settings.feature
This PR
- Shifts already existing settings API test scenarios into `apiSettings` test suite.
- Removes the following scenarios
```feature 
Scenario Outline: get assigned role of a user via setting api
Scenario Outline: only admin user can see assignments list
Scenario Outline: only admin user can see all existing roles
```
as they are covered in
``` feature 
Scenario Outline: user lists assignments
Scenario Outline: user lists existing roles
```
- Originated from: https://github.com/owncloud/ocis/pull/10827#discussion_r1906578562
- Locally
- CI
=> [tests-only][full-ci] shift existing settings api test scenarios to `apiSettings` test suite

.drone.star, .github/release_template.md
- Marked ocis 7 as production release - respective tags: 7.1, 7.1.0-rc.1 ... will be marked as production
- Updated the release template to check the above point
Part of https://github.com/owncloud/ocis/issues/10851
=> chore: mark 7 production release

changelog/unreleased/fix-grouped-email-missing-newline.md, services/notifications/pkg/email/composer.go
Bugfix: Fix missing newline in grouped email
`\n` is now replaced by `<br>` in the HTML email body
- Relates to https://github.com/owncloud/ocis/issues/10793
=> fix: Missing new lines in grouped email

changelog/unreleased/fix-email-templates.md, services/notifications/pkg/email/templates/html/email.html.tmpl, services/notifications/pkg/email/templates/text/email.text.tmpl
Fix email templates to not contain white spaces / new lines if .CallToAction is nil
- Relates to https://github.com/owncloud/ocis/issues/10793
=> fix: Email templates to not contain white spaces / new lines

tests/ociswrapper/wrapper/handlers/handler.go
This PR resolves the issue of unwanted OS environment duplication in the OCIS wrapper when the rollback API is triggered.
```
2025/01/20 14:48:40 [ociswrapper] os enviroment while staring ocis [SYSTEMD_EXEC_PID=xxx SSH_AUTH_SOCK=/run/xxxx/xxxx/keyring/ssh SESSION_MANAGER=local/xxxx:@/tmp/.ICE-unix/xxxx,unix/xxxx:/tmp/.ICE-unix/3446 GNOME_TERMINAL_SCREEN=/org/gnome/xxxx LANG=en_US.UTF-8 XDG_CURRENT_DESKTOP=ubuntu:GNOME PWD=/xxxx WAYLAND_DISPLAY=wayland-0 LC_IDENTIFICATION=xxx QT_IM_MODULE=xxx LC_MEASUREMENT=bho_NP DESKTOP_SESSION=ubuntu XDG_MENU_PREFIX=gnome- PNPM_HOME=/home/amrita/.local/share/pnpm PROXY_ENABLE_BASIC_AUTH=true 
SYSTEMD_EXEC_PID=xxx SSH_AUTH_SOCK=/run/xxxx/xxxx/keyring/ssh SESSION_MANAGER=local/xxxx:@/tmp/.ICE-unix/xxxx,unix/xxxx:/tmp/.ICE-unix/3446 …
```
=> [tests-only][full-ci]Remove os enviroment duplication from ocis wrapper

tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/features/apiActivities/shareActivities.feature, tests/acceptance/features/apiCollaboration/wopi.feature, tests/acceptance/features/apiSharingNg1/listPermissions.feature, tests/acceptance/features/apiSharingNg1/removeAccessToDrive.feature, tests/acceptance/features/apiSharingNg1/sharedByMe.feature, tests/acceptance/features/apiSharingNgLinkSharePermission/createLinkShare.feature, tests/acceptance/features/apiSharingNgLinkSharePermission/updateLinkShare.feature, tests/acceptance/features/apiSharingNgLinkShareRoot/createLinkShare.feature, tests/acceptance/features/apiSharingNgLinkShareRoot/updateLinkShare.feature, tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature, tests/acceptance/features/apiSpaces/publicLink.feature, tests/acceptance/features/apiSpaces/uploadSpaces.feature, tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature, tests/acceptance/features/apiSpacesShares/publicLinkDownload.feature, tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature, tests/acceptance/features/coreApiWebdavUpload/uploadFile.feature
Similar to PR: https://github.com/owncloud/ocis/pull/10850
This PR refactors the `space link share` creation steps such that the datatable uses permissions roles `displayName`. Previously, permissions role value was used.
In this PR following are the changes made in datatable:
from `view` => to `View`
from `internal` => to `Internal`
from `edit` => to `Edit`
from `upload` => to `Upload`
from `createOnly` => to `File Drop`
from `blocksDownload` => to `Secure View`
See: https://owncloud.dev/libre-graph-api/#/drives.root/CreateLinkSpaceRoot
Refactored steps:
``` feature
Given user "Alice" has created the following space link share:
When user "Brian" creates the following space link share using root endpoint of the Graph API:
When user "Alice" tries to create the following space link share …
```
=> [tests-only][full-ci] use displayname of permissions role in space link share creation step

tests/acceptance/features/apiSettings/notificationSetting.feature
This PR adds test to disable in-app notification for `Share Removed` event.
``` feature
Scenario: disable in-app notification for Share Removed event
```
For `Share Removed` event, only in-app notifications can be enabled/disabled.
- Locally
- CI
=> [full-ci][tests-only] add test to disable in-app notification for `Share Removed` event

tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/config/behat.yml, tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
This PR 
- verifies that the resources, in both personal and project spaces, shared with denied permission roles don't appear while sharee lists all drives. 
-  Adds  `OcisConfigContext` context  for the suite `apiSharingNgShareInvitation`.
- Related to: https://github.com/owncloud/ocis/issues/10656
- CI
- Locally
=> [tests-only][full-ci] Tests for availability of resources shared with Denied role while listing all drives

tests/acceptance/bootstrap/OcisConfigContext.php, tests/acceptance/features/apiSharingNg1/filterPermissions.feature
This PR adds tests for list permission with filter and select query for project space 
Query `$select=@libre.graph.permissions.actions.allowedValues` has bug pined in issue so not covered in this PR
- refactor enable permission 
-  Part of https://github.com/owncloud/ocis/issues/10728
- locally
=> [tests-only][full-ci] Add tests for filtering permission on project space resource

deployments/examples/ocis_full/collabora.yml
Update the collabora image.
Backport to 7.0
Tested with my Hetzer deployment, no issues found.
=> [docs-only] Update ocis_full collabora image version

changelog/unreleased/enhancement-share-removed-email.md, services/notifications/pkg/command/server.go, services/notifications/pkg/email/templates.go, services/notifications/pkg/service/job.go, services/notifications/pkg/service/service.go, services/notifications/pkg/service/service_test.go, services/notifications/pkg/service/shares.go, services/settings/pkg/store/defaults/defaults.go
Add email notification for share removed
- Closes https://github.com/owncloud/ocis/issues/10904
- test environment: localhost
- test case 1: share removed instant
- test case 2: share removed instant but disabled
- test case 3: share removed instant but disabled
- test case 4: share removed daily
- test case 5: share removed daily but disabled
- test case 6: share removed weekly
- test case 7: share removed weekly but disabled
=> feat: Add email notification for share removed

tests/acceptance/features/apiSettings/notificationSetting.feature
This PR refactors the following scenarios to include disabling mail notifications for `Share removed` event.
This is a recently added new feature : https://github.com/owncloud/ocis/issues/10904
``` feature
Scenario: disable in-app notification for Share Removed event
Scenario: disable in-app notification for Share Removed event (Project space)
```
Refactored into:
``` feature
Scenario: disable mail and in-app notification for Share Removed event
Scenario: disable mail and in-app notification for Share Removed event (Project space)
```
- Locally
- CI
=> [tests-only][full-ci] refactor scenario to disable mail notification for `Share removed` event

tests/acceptance/features/apiSharingNg1/filterPermissions.feature
This PR re-order upload related step to avoid post-processing flakiness. This PR doesn't fix flakiness just avoid it from happening.
- Part of https://github.com/owncloud/ocis/issues/10898
- CI
=> [tests-only][full-ci] Re-order tests step to avoid post processing flakiness

tests/acceptance/features/apiSettings/notificationSetting.feature
This PR adds test to check notification after disabling notifications for `Added a space member` event.
``` feature
Scenario: disable mail and in-app notification for Added as space member event
```
- Locally
- CI
=> [tests-only][full-ci] add test to disable notifications for `Added as space member` event

tests/acceptance/features/apiOcm/propfind.feature
Added API test to check the `oc:share-types` property of shared resource that is shared to federated user. Property is checked before and after the federated share has been removed.
Test coverage for issue: https://github.com/owncloud/ocis/issues/10262
Part of https://github.com/owncloud/ocis/issues/10073
=> [tests-only][full-ci]added test for checking share-types property of shared resource shared to federated user

tests/acceptance/bootstrap/SettingsContext.php, tests/acceptance/features/apiSettings/notificationSetting.feature
This PR adds test to set the `email sending interval` to `never`. 
``` feature
Scenario: set email sending interval to never
```
In default, the `email sending interval` is set to `instant`.
- Locally
- CI
=> [tests-only][full-ci] add test to set receiving email intervals to never

tests/acceptance/features/apiSettings/notificationSetting.feature
This PR refactors the notifications test scenarios such that there are no multiple steps that requests to list all the in-app notifications 
Originated from: https://github.com/owncloud/ocis/pull/10928#discussion_r1942218165
In some notification test scenarios, we were using steps like follow:
``` feature
When user "Brian" lists all notifications
Then the HTTP status code should be "200"
And user "Brian" should get a notification with subject "Space shared" and message:
```
In this case, listing all notifications request(`listAllNotifications`) was called twice. 
- Locally
- CI
=> [tests-only][full-ci] refactor scenarios to remove multiple `listAllNotifications` request in steps

tests/acceptance/features/apiSettings/notificationSetting.feature
This PR adds test to disable notification for `Removed as space member` event.
``` feature
Scenario: disable mail and in-app notification for Removed as space member event
```
- Locally
- CI
=> [tests-only][full-ci] add test to disable notification for `Removed as space member` event

tests/acceptance/TestHelpers/TusClient.php, tests/acceptance/bootstrap/SpacesTUSContext.php, tests/acceptance/bootstrap/TUSContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/expected-failures-without-remotephp.md, tests/acceptance/features/apiOcm/share.feature, tests/acceptance/features/apiSpaces/tusUpload.feature, tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature
Since current test uses TUS library for tus operations and is unable to get and check the response.
Due to this, there was no check for the location header on TUS upload. 
So, in this PR, following things are done:
- TUS wrapper class is made and able to check the header response.
- added step on tus scenario for status code check
- https://github.com/owncloud/ocis/issues/10649
- Bug: https://github.com/owncloud/ocis/issues/10469
- CI
- locally
- ...
=> [tests-only][full-ci] add tests for checking the header location for tus upload

tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/features/apiOcm/listPermissions.feature, tests/acceptance/features/apiSharingNg1/filterPermissions.feature
This PR shifts and adds test coverage for filtering permission for federated user.
Also add some tests related to listing permission after resource share to check roles 
- Part of  https://github.com/owncloud/ocis/issues/10728
- Locally.
=> [tests-only][full-ci]Add tests for filtering permission of project resource

tests/acceptance/bootstrap/NotificationContext.php, tests/acceptance/features/apiAntivirus/antivirus.feature, tests/acceptance/features/apiNotification/deleteNotification.feature, tests/acceptance/features/apiNotification/deprovisioningNotification.feature, tests/acceptance/features/apiNotification/emailNotification.feature, tests/acceptance/features/apiNotification/notification.feature, tests/acceptance/features/apiNotification/serviceAvailabilityCheck.feature, tests/acceptance/features/apiNotification/spaceNotification.feature, tests/acceptance/features/apiOcm/createInvitation.feature, tests/acceptance/features/apiSettings/notificationSetting.feature
This PR fix notification retry test code and cleanup mail and in-app after every notification-related scenario
A new tag @notification has been introduced, which does in-app and mail notification cleanup in the after hook.
@email will be used for specifying email-related tests scenario 
- Removed **@skipOnStable3.0** tag because there is no used of it.
- Part of https://github.com/owncloud/ocis/issues/10802
- Locally
=> [tests-only][full-ci] Fix notification cleanup and retry

deployments/examples/ocis_full/collabora.yml, deployments/examples/ocis_full/docker-compose.yml, deployments/examples/ocis_full/onlyoffice.yml
This PR updates images of the `ocis_full` deploment examples.
Tested locally, works without issues.
Needs backport to 7.0 (to be available for 7.1)
=> [docs-only] Update images for ocis_full deployment example

.drone.star
Skip change log pipeline for nightly
backport of PR: https://github.com/owncloud/ocis/pull/10960
=> [tests-only][full-ci] backport skip changelog pipeline in nightly ci run

tests/acceptance/features/apiOcm/acceptInvitation.feature, tests/acceptance/features/apiOcm/deleteFederatedConnections.feature, tests/acceptance/features/apiOcm/listPermissions.feature, tests/acceptance/features/apiOcm/ocmNotifications.feature
This PR adds test to disable mail and in-app notification for `Share Received` event for OCM.
``` feature
Scenario: federated user disables mail and in-app notification for "Share Received" event
```
- Bug Report: https://github.com/owncloud/ocis/issues/10718
-
=> [tests-only][full-ci] add test to disable mail and in-app notifications when receiving a federated share

tests/acceptance/bootstrap/OcmContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiOcm/acceptInvitation.feature
This PR adds API test for a user trying to accept federation share invitation from same instance.
- Part of: https://github.com/owncloud/ocis/issues/10971
- Bug report: https://github.com/owncloud/ocis/issues/11004
=> [tests-only][full-ci]added test for user trying to accept federation share invitation from same instance

tests/acceptance/bootstrap/Sharing.php, tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/bootstrap/SpacesContext.php
This PR stores share related response to use in later step to get permission id and expiration date
- Fixes https://github.com/owncloud/ocis/issues/10992
- CI
=> [tests-only][full-ci] Store share invite response

tests/acceptance/features/apiNotification/emailNotification.feature
This PR adds 4 tests for checking mail notification alert for file and folder, which have been unshared.
Add the following scenarios:
- user gets an email notification when a folder is unshared
- user gets an email notification when space admin unshares a folder
- user gets an email notification when a file is unshared
- user gets an email notification when space admin unshares a file
- Part of https://github.com/owncloud/ocis/issues/10937
- Test coverage for https://github.com/owncloud/ocis/issues/10904
- extend notification tests
- Locally
=> [tests-only][full-ci] When file or folder is unshared user received an email notification

tests/acceptance/TestHelpers/GraphHelper.php, tests/acceptance/TestHelpers/HttpRequestHelper.php, tests/acceptance/bootstrap/FeatureContext.php, tests/acceptance/bootstrap/GraphContext.php, tests/acceptance/bootstrap/NotificationContext.php, tests/acceptance/bootstrap/Provisioning.php, tests/acceptance/bootstrap/SettingsContext.php, tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/features/apiArchiver/downloadByPath.feature, tests/acceptance/features/apiGraph/userGDPRExport.feature, tests/acceptance/features/apiGraphUserGroup/editUser.feature, tests/acceptance/features/apiLocks/lockFiles.feature, tests/acceptance/features/apiLocks/unlockFiles.feature, tests/acceptance/features/apiSpaces/changeSpaces.feature, tests/acceptance/features/apiSpaces/quota.feature, tests/acceptance/features/apiSpaces/tag.feature, tests/acceptance/features/apiSpacesShares/shareOperations.feature, tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature, tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature, tests/acceptance/features/coreApiWebdavProperties/getQuota.feature
I have added a store to save all drives (`personal`, `shares` and `project`) and use it to get the necessary properties. If the requested drive is unavailable in the store then a request to `me/drives` is made to get the drives.
I have also made the changes to the user store and user deletion flow. These stores should work with the local and remote server setup.
- Fix for https://github.com/owncloud/ocis/issues/10603
- test environment: :robot:
=> [tests-only][full-ci] use store for drives

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiOcm/share.feature
This PR adds tests coverage for federated expired share 
- Part of https://github.com/owncloud/ocis/issues/10971
- Bug coverage of https://github.com/owncloud/ocis/issues/11033
- locally
=> [tests-only][full-ci]Add test for ocm share expiry

tests/acceptance/bootstrap/SpacesContext.php
Do not try to store spaces that have the `deleted` property. This property can sometimes appear on deleted spaces, but the deletion was partial or something else happened during the process.
See https://github.com/owncloud/ocis/issues/10603#issuecomment-2668380050
- Follow up: https://github.com/owncloud/ocis/pull/11000
=> [tests-only][full-ci] skip spaces that are marked as deleted

docs/ocis/development/testing.md, tests/acceptance/docker/src/acceptance.yml, tests/acceptance/docker/src/email.yml, tests/acceptance/docker/src/ocis-base.yml
This PR changes docker code related to running tests in docker. 
`https://owncloud.dev/ocis/development/testing/#running-test-suite-in-docker`
- added missing env in documentation
- https://github.com/owncloud/ocis/issues/11020
- locally
-
=> [docs-only]Replace docker inbucket with mailpit

tests/acceptance/features/apiNotification/emailNotification.feature, tests/acceptance/features/apiNotification/serviceAvailabilityCheck.feature, tests/acceptance/features/apiOcm/acceptInvitation.feature, tests/acceptance/features/apiOcm/createInvitation.feature, tests/acceptance/features/apiOcm/deleteFederatedConnections.feature, tests/acceptance/features/apiOcm/listPermissions.feature, tests/acceptance/features/apiOcm/ocmNotifications.feature, tests/acceptance/features/apiSettings/notificationSetting.feature
This PR removes notification and email tag from unrelated scenarios and moved 
`Scenario: federated user gets an email notification if their email was specified when creating the federation share invitation` scenario from `tests/acceptance/features/apiOcm/createInvitation.feature` to `tests/acceptance/features/apiOcm/ocmNotifications.feature`
- Part of https://github.com/owncloud/ocis/issues/11020
- CI
=> [tests-only][full-ci]Remove notification and email tag from unrelated scenario

tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiOcm/share.feature
This PR adds test to hide federated shared resource.
``` feature
Scenario: federated user hides the shared resource
```
- Part of: https://github.com/owncloud/ocis/issues/10971
- Bug Report: https://github.com/owncloud/ocis/issues/10719
- Locally
- CI
=> [tests-only][full-ci] add test to hide federated shared resource

tests/acceptance/bootstrap/ArchiverContext.php, tests/acceptance/bootstrap/OcmContext.php, tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiOcm/enableDisablePermissionsRole.feature
This PR adds tests to enable and disable the share permissions role **Secure VIewer** for federated shares.
Test Coverage for https://github.com/owncloud/ocis/issues/10824 and https://github.com/owncloud/ocis/issues/10822
=> [tests-only][full-ci] added test to enable disable Secure Viewer permissions role for federated shares

tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
This PR adds the test for sharing resources after disabling the permissions role.
Originated from comment: https://github.com/owncloud/ocis/pull/11057#discussion_r1972832365
=> [tests-only][full-ci]added test to share resources after the permissions role is disabled

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiOcm/share.feature
This PR has removed steps which seems impossible to occur after the bug gets fixed
-  https://github.com/owncloud/ocis/issues/11033
- Locally
=> [tests-only][full-ci]Refactor step  related to sharee access to expired shared resource

tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiOcm/share.feature
This PR adds following test scenarios to enable sync of federated share.
``` feature
Scenario: enable sync of a federated shared resource
Scenario: enable sync of one of multiple federated shared resources
```
Enabling sync of a federated share when there's only one share in `shared with me` doesn't throw any error but enabling sync of a federated share when there are multiple shares in `shared with me` gives `400 Bad Request` error but `@client.synchronize` is set to true.
See comments: https://github.com/owncloud/ocis/issues/10719#issuecomment-2667986780 and https://github.com/owncloud/ocis/issues/10719#issuecomment-2668011171
- Part of: https://github.com/owncloud/ocis/issues/10971
- Bug Report: https://github.com/owncloud/ocis/issues/10719
- Locally
- CI
=> [tests-only][full-ci] add test to enable sync of federated shared resource

changelog/unreleased/update-postprocessing-logs.md, services/postprocessing/pkg/service/service.go
- log each incoming event (debug level)
- log events that instruct the service to retry an event on info level
- log errors it encounters on error level
- log postprocessing restart events
- log the outcome of all operations even if they were successful
- make sure all postprocessing steps are tracked in the logs
- Fixes: #10998 
User Story: The postprocessing service is the center piece of uploads in ocis. Unfortunately logging is scarce. We need to improve logging so we can easily trace failing uploads
- test environment: 
- test case 1:
- test case 2:
- ...
=> feat: Improve logging in the postprocessing service

tests/acceptance/TestHelpers/SettingsHelper.php, tests/acceptance/bootstrap/SettingsContext.php, tests/acceptance/features/apiAntivirus/antivirus.feature, tests/acceptance/features/apiAntivirus/enableDisableNotification.feature, tests/acceptance/features/apiSettings/notificationSetting.feature
Sometimes setting related tests fails when getting bundles list. To avoid such flakiness setting id has been hard coded. 
Shifted two scenarios to antivirus suite so that tests run when antivirus service is setup
- Fixes https://github.com/owncloud/ocis/issues/11088
- CI
=> [tests-only][full-ci]Hard code setting id's to avoid flakiness in tests

.drone.star, tests/acceptance/TestHelpers/GraphHelper.php, tests/acceptance/config/behat.yml, tests/acceptance/features/apiOptionalShareRole/editorWithVersions.feature
This PR creates a separate test suite for optional roles i.e. `apiOptionalSharingRoles`(more tests will be added later).
I have added tests to share and list versions of a file shared with `FileEditorWithVersions` and `EditorWithVersions` role.
``` feature
Scenario: sharee checks version of a file shared with FileEditorWithVersions role
Scenario: sharee checks version of a file inside a folder shared with EditorWithVersions role
```
- Part of: https://github.com/owncloud/ocis/issues/11055
- Locally
- CI
=> [tests-only][full-ci] add test to share resources with `FileEditorWithVersions` and `EditorWithVersions` role

tests/acceptance/features/apiSettings/notificationSetting.feature
This PR adds test for disabling in-app and mail notifications for `Space membership expired` event.
``` feature
Scenario: disable mail and in-app notification for "Space Membership Expired" event
```
- Bug report: https://github.com/owncloud/ocis/issues/10882
- Locally
- CI
=> [tests-only][full-ci] add test to disable mail and in-app notifications for `Space membership expired` event

tests/acceptance/TestHelpers/OcisConfigHelper.php, tests/acceptance/bootstrap/OcisConfigContext.php, tests/ociswrapper/README.md, tests/ociswrapper/wrapper/handlers/handler.go, tests/ociswrapper/wrapper/wrapper.go
After each scenario, we need to reset the oCIS state, terminate all services, and remove the stored service environment variable configuration for each service. Added **rollback** endpoint for terminating all services and removing the stored service
environment variable configuration  
1. run oCIS  and start oCIS service 
2. run oCIS and update oCIS env with PUT method 
- `curl -XPUT 'http://localhost:5200/config' -d'{"OCIS_EXCLUDE_RUN_SERVICES":"storage-users"}'`
3. run multiple ocis service
- `curl -XPOST 'http://localhost:5200/services/audit' -d'{"OCIS_LOG_LEVEL":"info"}'` 
- `curl -XPOST 'http://localhost:5200/services/storage-users' -d'{"OCIS_LOG_LEVEL":"info"}'` 
4. update running service 
- `curl -XPATCH 'http://localhost:5200/services/storage-users' -d'{"OCIS_LOG_LEVEL":"warn"}'` …
=> [tests-only][full-ci]Support services rollback in ociswrapper

tests/acceptance/features/apiOptionalShareRole/editorWithVersions.feature
This PR adds test to check versions after updating the permissions role to and from EditorWithVersions role.
``` feature
Scenario Outline: sharee checks versions after updating the permission role of a shared file from other roles to FileEditorWithVersions
Scenario Outline: sharee tries to check versions after updating the permission role of a shared file from FileEditorWithVersions to other roles
Scenario Outline: sharee checks versions after updating the permission role of the shared folder from other roles to EditorWithVersions
Scenario Outline: sharee tries to check versions after updating the permission role of the shared folder from EditorWithVersions to other roles
```
- Part of: https://github.com/owncloud/ocis/issues/11055
- CI
- Locally
=> [tests-only][full-ci] add test to check versions after changing roles to and from EditorWithVersions role

changelog/unreleased/fix-app-auth.md, services/proxy/pkg/command/server.go, services/proxy/pkg/middleware/authentication.go, services/proxy/pkg/middleware/options.go
Allow the app-auth announce `www-authenticate: basic` header.
- Fixes [#11113](https://github.com/owncloud/ocis/issues/11113)
- test case 1:
- test case 2:
- ...
=> Allow the app-auth announce www-authenticate: basic header.

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiOcm/acceptInvitation.feature
This test updates error message in the test case when user sends the federeated connection invitation to the same instance. The bug was fixed with updated error message in https://github.com/cs3org/reva/pull/5077.
- Bug Report: https://github.com/owncloud/ocis/issues/11004
- https://github.com/owncloud/ocis/issues/10971
=> [tests-only][full-ci] update error message in json response when user invite themselves to federated connection

tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/features/apiSharingNg1/enableDisablePermissionsRole.feature
This PR adds the test to share resource with Editor role, disabling the Editor role and users listing the shares.
=> [tests-only][full-ci] added test to list shares after disabling Editor role

tests/acceptance/bootstrap/OcmContext.php, tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/features/apiOcm/share.feature
This PR adds the tests for sharing resources concurrently to federated users.
- sharing multiple resources to a single federated user
- sharing multiple resources to multiple federated users
- https://github.com/owncloud/ocis/issues/11035
=> [tests-only][full-ci] added test to share resources concurrently to federated user

tests/acceptance/bootstrap/OcmContext.php, tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
The flaky reported in https://github.com/owncloud/ocis/issues/11126 is probably due to the async server tasks. I have added a share sync check and also checked the shared role. The step that checks the sync status runs with retries until the timeout.
- Fixes https://github.com/owncloud/ocis/issues/11126
- test environment: :raised_back_of_hand:
=> [tests-only][full-ci] check share sync and role

tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/features/apiNotification/notification.feature
This PR add tests for checking in-app and mail notification alert for resource share expiry of personal .
- Project drive have bug i.e generate 2 notification for share expire event (partially fixed)
-  Don't use the list all notification step in this scenario; it may gives flakiness
Bug coverage of - https://github.com/owncloud/ocis/issues/10966
- Part of https://github.com/owncloud/ocis/issues/10937
- Locally
=> [tests-only][full-ci] Add tests for share expiry

.drone.star
Currently, we are running k6 pipeline on both the master and stable branches' nightlies. Since the k6 test runner server is the same for both, the pipeline cannot pass.
Example builds:
- https://drone.owncloud.com/owncloud/ocis/44556/63/1
- https://drone.owncloud.com/owncloud/ocis/44557/67/1 
Run k6-tests daily basis for the master branch only. If `k6-test` is specified in the PR title, then the tests should run on the PR as well no matter the branch name. Meaning you can run k6 tests in other branches if necessary by adding `k6-test` in the PR title.
Only the nightly build of master branch will have the k6 pipeline running. This prevents the failures caused by the many k6 nightly pipelines running together.
- resolves https://github.com/owncloud/ocis/issues/11141
=> [tests-only][full-ci]ci: run k6 only for master branch nightly unless specified in PR title

changelog/unreleased/fix-ocm-share-notifications.md, go.mod, go.sum, services/ocm/pkg/revaconfig/config.go, services/userlog/pkg/command/server.go, services/userlog/pkg/service/conversion.go, services/userlog/pkg/service/filter.go, services/userlog/pkg/service/service.go, vendor/github.com/owncloud/reva/v2/internal/grpc/services/ocmcore/ocmcore.go, vendor/github.com/owncloud/reva/v2/pkg/events/ocmcore.go, vendor/modules.txt
- Subscribe to OCM share events from rava: https://github.com/owncloud/reva/pull/255/files
- Convert to userlog notifications accessible via GET (and visible in web UI)
- Resolves [#11042](https://github.com/owncloud/ocis/issues/11042)
- 2 instances: ocm and federated
1. start instances
2. invite federated instance
3. share and unshare directory in ocm instance
4.1. GET endpoint returns notifications
4.2. notice notifications in federated intance
```
curl "https://localhost:10200/ocs/v2.php/apps/notifications/api/v1/notifications?format=json" \
-u admin:admin -k | jq
{
"ocs": {
"meta": {
"message": "",
"status": "",
"statuscode": 200
},
"data": [
{
"notification_id": "d114d33a-330d-4b3e-8e61-3cc6f24f2dd4",
"app": "userlog",
"user": "Albert Einstein",
"datetime": …
```
=> feat: OCM, share notifications

ocis-pkg/generators/natsnames.go, ocis-pkg/natsjsregistry/options.go, ocis-pkg/natsjsregistry/registry.go, ocis-pkg/registry/registry.go, services/activitylog/pkg/command/server.go, services/antivirus/pkg/service/service.go, services/audit/pkg/command/server.go, services/clientlog/pkg/command/server.go, services/eventhistory/pkg/command/server.go, services/frontend/pkg/command/events.go, services/graph/pkg/server/http/server.go, services/notifications/pkg/command/send_email.go, services/notifications/pkg/command/server.go, services/policies/pkg/command/server.go, services/postprocessing/pkg/command/postprocessing.go, services/postprocessing/pkg/command/server.go, services/proxy/pkg/command/server.go, services/search/pkg/service/grpc/v0/service.go, services/sharing/pkg/revaconfig/config.go, services/sse/pkg/command/server.go, services/storage-users/pkg/event/event.go, services/storage-users/pkg/revaconfig/config.go, services/userlog/pkg/command/server.go
Change the connection names according to the format `hostname:pid:service:type`
```
root@f0895c1d67d2:/# nats account report connections
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                  Top 24 Connections out of 24 by subs                                                                                 │
├─────┬──────────────────────────────┬──────────────────────────────────────────────────────────┬──────────────┬──────────────────┬─────────┬────────┬─────────┬──────────┬──────────┬───────────┬──────┤
│ CID │ Name                         │ Server …
```
=> Nats connection names

changelog/unreleased/fix-app-auth-rest-status.md, services/auth-app/pkg/service/service.go
Bugfix: Fix app-auth, REST status code when creating token for non-existent user (Impersonation)
Now app-auth REST returns status code 404 when creating token for non-existent user (Impersonation)
- Fixes #10815
- test environment: same as in the issue
```
➜  curl -kv -XPOST 'https://localhost:9200/auth-app/tokens?expiry=72h&userName=mosss' -uadmin:admin
* Host localhost:9200 was resolved.
...
* Server auth using Basic with user 'admin'
...
< HTTP/1.1 404 Not Found
< Content-Length: 15
< Content-Security-Policy: child-src 'self'; connect-src 'self' blob: https://raw.githubusercontent.com/owncloud/awesome-ocis/; default-src 'none'; font-src 'self'; frame-ancestors 'self'; frame-src 'self' blob: https://embed.diagrams.net/; img-src 'self' data: blob: …
```
=> fix: app-auth, REST user not found code

tests/acceptance/bootstrap/FeatureContext.php, tests/acceptance/features/cliCommands/uploadSessions.feature
Hypothesis:
- The file post processing logic for virusscan seems correct. Test seems to have correct expectations.
- The reason for random fails can be timing of results propagation.
- The is some small wait time added after requests 
Potential fix:
- explicitly wait a bit longer for the processing results to propagate, there is 10s window set with delay
Test CI output spotted in https://drone.owncloud.com/owncloud/ocis/44766/37/10
```
Scenario: list all upload sessions that are currently in postprocessing                            # /drone/src/tests/acceptance/features/cliCommands/uploadSessions.feature:25
Given the following configs have been set:                                                       # OcisConfigContext::theConfigHasBeenSetToValue()
| config                           | …
```
=> [full-ci] fix: test, file postprocessing flakyness

tests/ociswrapper/wrapper/handlers/handler.go
Hypothesis:
- In handler Post: service was started with ocis.ServiceEnvConfigs containing only last env key-value
- In test: possible that test was ok when server was started with default config due to timing
Potential fix:
- use ocis.ServiceEnvConfigs in MethodPost to persist the env config and scope serviceEnvMap only to MethodPatch
Note:
- ~~the timing issue may still not be fixed properly - haven't found it yet.~~
- by using persistant ocis.ServiceEnvConfigs[serviceName] the env variables persist correctly across the requests
Found in: https://drone.owncloud.com/owncloud/ocis/44783/20/6
```
@env-config
Scenario: check services health and readiness while running separately                     # /drone/src/tests/acceptance/features/apiServiceAvailability/serviceAvailabilityCheck.feature: …
```
=> [full-ci] fix: test, handler flakyness 

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiContract/propfindShares.feature
Added test to check `oc:shareid` on propfind response on the sharejail root.
Current, behavior using `spaces` dav path the `oc:shareid` property is empty and for `old` and `new` dav paths the `oc:shareid` property is not available in the response.
- Bug report: https://github.com/owncloud/ocis/issues/8510
=> [tests-only][full-ci] add test to check oc:shareid on propfind response on the sharejail root

tests/acceptance/features/apiSharingNgAdditionalShareRole/listGrantsShareRole.feature
This PR add tests which update share permissions from/to list grant-related share permissions
- https://github.com/owncloud/ocis/issues/10951
- locally
=> [tests-only][full-ci]Add tests for updating list grant related shares permission 

tests/acceptance/features/apiOcm/ocmNotifications.feature
This PR adds test to disable in-app notification for `Share Removed` event by federated user(OCM).
NOTE :exclamation: => Email notifications are not implemented yet for OCM
``` feature
Scenario: federated user disables in-app notification for "Share Removed" event
```
- Part of: https://github.com/owncloud/ocis/issues/11062
- Bug report: https://github.com/owncloud/ocis/issues/11042
- Locally
- CI
=> [tests-only][full-ci] add test to disable in-app notification for share removed event by federated user

tests/acceptance/features/apiOcm/ocmNotifications.feature
This PR adds test to check in-app notification when a federation user receives a share from local user.
NOTE :exclamation: => Email notifications are not implemented yet for OCM
``` feature
Scenario: federation user gets an in-app notification for share received from local user
```
- Part of: https://github.com/owncloud/ocis/issues/11062
- Bug report: https://github.com/owncloud/ocis/issues/10718
- Locally
- CI
=> [tests-only][full-ci] add test to check in-app notification for share received from federation user

tests/acceptance/bootstrap/WebDavPropertiesContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiContract/propfindShares.feature
Added test to check `oc:share-types` property by sharer after the sharee is deleted.
The current behavior contains `<oc:share-types><oc:share-type>0</oc:share-type></oc:share-types>` in the response.
The `oc:share-types` property should be empty after the sharee is deleted.
```xml
<d:multistatus xmlns:s="http://sabredav.org/ns" xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
<d:response>
<d:href>/remote.php/dav/spaces/a9439309-d04d-4855-8e66-aade543fa429$78d13b96-8de1-4dfa-8886-c932831e6c04/testFolder/</d:href>
<d:propstat>
<d:prop>
<oc:share-types></oc:share-types>
</d:prop>
<d:status>HTTP/1.1 200 OK</d:status>
</d:propstat>
</d:response>
```
- Bug report: https://github.com/owncloud/ocis/issues/9463
=> [tests-only][full-ci]added test to check share-types property by sharer after sharee is deleted

tests/acceptance/features/apiOcm/ocmNotifications.feature
This PR adds test to check in-app notification by federation user when local user unshares a resource to federation user.
NOTE :exclamation: => Email notifications are not implemented yet for OCM
```feature
Scenario: federation user gets an in-app notification for share removed from local user
```
- Part of: https://github.com/owncloud/ocis/issues/11062
- Bug report: https://github.com/owncloud/ocis/issues/11042
- Locally
- CI
=> [tests-only][full-ci] add test to check in-app notification for share removed event OCM

tests/acceptance/features/apiNotification/spaceNotification.feature, tests/acceptance/features/apiSpaces/spaceManagement.feature
This PR adds only one scenario to check if an user receives an email notification when the space membership expire. 
- https://github.com/owncloud/ocis/issues/10882
- https://github.com/owncloud/ocis/issues/10937
- Locally
=> [tests-only][full-ci] Add test to receive an email notification when space membership expire

tests/acceptance/bootstrap/GraphContext.php, tests/acceptance/features/apiSharingNgAdditionalShareRole/listGrantsShareRole.feature
This PR only adds one scenario which checks JSON response of the share received resource. Other activities related tests cases will be covered in next PR without using JSON scheme 
- https://github.com/owncloud/ocis/issues/10951
- locally
=> [tests-only][full-ci]Add test cases to validate JSON response for shared resource activity listing (list grant roles)

tests/acceptance/bootstrap/ArchiverContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpacesShares/shareOperations.feature
This PR adds test for share receiver trying to download the folder shared with Secure Viewer role.
- Bug Report: https://github.com/owncloud/ocis/issues/9369
=> [tests-only][full-ci]added test to download archive of folder shared with Secure Viewer role

.drone.star, tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/features/apiSharingNgAdditionalShareRole/listGrantsShareRole.feature
This PR adds tests for listing permission when listGrantPermission is enabled .
Only a limited test scenario has been added.
move two folder to another pipeline to balance
- https://github.com/owncloud/ocis/issues/10951
- Locally
=> [tests-only][full-ci]Add tests related to list permission for listgrant role

.drone.env, .drone.star
Port PR https://github.com/owncloud/ocis/pull/11172 and bump web commit id
Part of https://github.com/owncloud/web/issues/12436
=> [full-ci][tests-only] chore: port skip k6 and web bump

tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/features/apiSharingNgAdditionalShareRole/listGrantsShareRole.feature
Shares are linked to the resources. user is the owner of the resources. So it is better to write `resource has a share` if mentioning multiple shares of same resource.
Renamed
```feature
Then user "Brian" should have the following shares of the file "textfile1.txt":
```
to
```feature
Then for user "Brian" file "textfile1.txt" should have the following shares:
```
=> [tests-only] test: rename step name

tests/acceptance/features/apiNotification/spaceNotification.feature
This PR only updates the scenario, which checks if an user receives an email notification when the space membership expire.
Previous PR https://github.com/owncloud/ocis/pull/11215
- https://github.com/owncloud/ocis/issues/10882
- Part of https://github.com/owncloud/ocis/issues/10937
Improvements to reduce the steps to execute the given scenario
- tested locally
=> [tests-only][full-ci] Update test to receive an email notification when space membership expire

changelog/unreleased/update-delete-notification-by-id.md, services/userlog/pkg/service/http.go, services/userlog/pkg/service/service.go
Ocis shall implement the oc10 delete request for single notifications.
Bulk operation must be done via the ocis style delete request with json body.
Fixes [https://github.com/owncloud/enterprise/issues/6307](https://github.com/owncloud/enterprise/issues/6307)
- test environment: local test
List einstein notifications
```bash
curl "https://localhost:9200/ocs/v2.php/apps/notifications/api/v1/notifications?format=json" -u einstein:relativity -k | jq
200 OK
{
"ocs": {
"meta": {
"message": "",
"status": "",
"statuscode": 200
},
"data": [
{
"notification_id": "6b24e986-3cb1-42ef-9e81-3d186eb5a9ae",
"app": "userlog",
"user": "admin",
"datetime": "2025-04-03T11:47:19.023043+02:00",
"object_id": "f44f9f18-2f57-4213-a82b-0795357bf74a$3f2367f5-3749-4b22-a77b-c55a1ee740a3!0f3a9b09-a6c3-4db2-a7d7-315e2 …
```
=> feat: userlog, delete notification by id

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSharingNgPermissions/listPermissions.feature
This PR adds the missing property `cretaedDateTime` property while requesting members of project space using root endpoint `/graph/v1beta1/drives/{driveId}/root/permissions`
- Bug Report: https://github.com/owncloud/ocis/issues/10077
=> [tests-only][full-ci] add missing property createdDateTime while listing permissions of space using root endpoint

changelog/unreleased/update-wopi-token-check.md, services/collaboration/pkg/connector/fileconnector_test.go, services/collaboration/pkg/middleware/wopicontext.go, services/collaboration/pkg/middleware/wopicontext_test.go, services/collaboration/pkg/service/grpc/v0/service_test.go, services/thumbnails/pkg/service/http/v0/service.go
- test case 1:
- test case 2:
- ...
=> fix: wopi context token check

.drone.star, tests/acceptance/bootstrap/CliContext.php, tests/acceptance/features/cliCommands/staleUpload.feature
This PR adds tests for listing and deleting stale uploads. 
To create stale upload `POSTPROCESSING_DELAY` env has been used to start processing after some time so that we can stop ocis and delete ***.info** file inside `.ocis/storage/users/uploads`
Scenario covered
- list and delete all stale uploads (which list and delete  every user stale upload)
-  list and delete stale upload of specific space (which list and delete stale upload of specific user specific space)
- https://github.com/owncloud/ocis/issues/11246
- CI
=> [tests-only][full-ci] Add cli test for deleting stale uploads

tests/acceptance/bootstrap/EmailContext.php, tests/acceptance/features/apiSettings/notificationSetting.feature, tests/ociswrapper/ocis/ocis.go
concurrently read from command running in pseudo-terminal instead of reading at the end. This helps to preserve the output from the command.
- Fixes https://github.com/owncloud/ocis/issues/11201
Run CLI tests in MacOS
=> [full-ci][tests-only] read concurrently from command running in pseudo-terminal

changelog/unreleased/claim-managed-spaces.md, services/proxy/pkg/middleware/space_manager.go
When using claim managed spaces, this will allow having multiple claims for the same space. The system will automatically use the one with the highest permission
=> Allow Multiple Spaceclaims

tests/acceptance/features/apiNotification/notification.feature, tests/acceptance/features/apiNotification/spaceNotification.feature, tests/acceptance/features/apiSettings/notificationSetting.feature
This PR introduces updates for some of the API acceptance tests by adding a new initial step, which configures the user role.
Adding this step allows the examples to set a new user role - `User Light`.
Examples data for the modified scenarios are also extended to cover the `User Light` role.
Covering the following scenarios for in-app and email notifications:
- Share Received
--> notificationSetting.feature (Line 68)-> disable mail and in-app notification for "Share Received" event
- Share Removed
--> notificationSetting.feature (Line 163) -> disable mail and in-app notification for "Share Removed" event
--> notificationSetting.feature (Line 260) -> disable mail and in-app notification for "Share Removed" event (Project space)
- Share Expired
--> notificationSetting.feature (Line 884) -> …
=> [tests-only][full-ci] Extend notification tests for `User Light` role

changelog/unreleased/fix-error-on-listing-space-members.md, services/graph/pkg/service/v0/api_driveitem_permissions.go
Handle gracefully the error mentioned by the issues. Unblock the space members API by recognizing the reva 'AlreadyExists'. Return HTTP OK 200 with remaining shares instead of HTTP Internal Server Error 5XX.
- Fixes [#11119](https://github.com/owncloud/ocis/issues/11119)
- test environment: [gist with scripts for upgrade and listing members](https://gist.github.com/mklos-kw/0ea8b208a77ebc19246389c19c8588e6)
=> fix: list shares, handle reva errors more gracefully

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSharingNgShares/sharedWithMe.feature
check file actions after share creation. This is to prevent possible flakiness that can occur due to existing issue https://github.com/owncloud/ocis/issues/8464
Note: if this becomes flaky again then maybe we should skip this test
=> [tests-only][full-ci] check resource creation with share creation

README.md, docs/ocis/guides/_index.md, docs/ocis/guides/migrate-data-rclone.md, docs/ocis/guides/ocis-mini-eval.md
This PR adds a minimalistic guide to run ocis based on `docker run` (not compose !) - for eval only !
To have a local rendering, check out and run `make -C docs docs-serve` and open a browser with URL:
`http://localhost:1313/ocis/guides/ocis-mini-eval/`
=> [docs-only] Add a minimalistic docker run example

tests/acceptance/bootstrap/TagContext.php, tests/acceptance/config/behat.yml, tests/acceptance/expected-failures-without-remotephp.md, tests/acceptance/features/apiSpaces/tag.feature
This PR add tests related to exceeding amount of tag (> 100) . 
Expected behaviour : only first 100 tags should be created and return 200 status code.
Discussion done here : https://github.com/owncloud/enterprise/issues/7180
> Yes, this seems to be expected behaviour for now. Compare this comment: 
> https://github.com/owncloud/reva/blob/main/pkg/tags/tags.go#L116
- https://github.com/owncloud/ocis/issues/11243
- locally
=> [tests-only][full-ci]Add tests for exceeding tags amount

tests/acceptance/features/apiSettings/notificationSetting.feature
This PR adds test for disabling in-app notifications for space deleted event.
enabling or disabling notification for email is not available for this event.
>Note: All notifications related to a space will be deleted when the space is deleted, which is to be expected for now.
- https://github.com/owncloud/ocis/issues/10941
- test case 1: locally
- test case 2:
- ...
=> [tests-only][full-ci] adding test for disabling in-app notifications for space deleted event

changelog/unreleased/update-ocis_full_images.md, deployments/examples/ocis_full/collabora.yml, deployments/examples/ocis_full/docker-compose.yml, deployments/examples/ocis_full/onlyoffice.yml
Fixes: #11066 (ocis_full update collabora image results in startup failure)
References: #11109 (Maintenance example)
The images for `collabora`, `onlyoffice` and `traefik` got updated.
Additionally, the startup in `collabora.yml` is fixed. It starts now as expected and is healthy.
Note the changelog, because this update needs to be part of the upgrade process/documentation due to the changed collabora.yml file.
Tested locally, an office file was editable with both web apps.
When merged, #11109 must be rebased.
=> [docs-only] Update the ocis_full example for new image versions

docs/helpers/changed_envvars.py
This PR updates the python script we use to automatically create added/deprecated and removed envvar tables required for the documentation. The changes are for improved maintainability and updated versions.
* Add good practices for Python code 
* Use variable and return value type annotations
* Use a main definition
* Update the versions to what I think will come next (`stable-7.2`)
(Can be adapted if needed later on, does no harm if we use a name instead a semver, because it is only a filename component)
A local testrun returned expected results
=> [docs-only] Update the Python script which creates adoc delta envvar tables

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSharingNgShares/sharedWithMe.feature
This scenario can pass sometimes when using space path thus causing the flaky behavior. Therefore, let's skip the test for space dav path until the bug is fixed
Failures:
- https://drone.owncloud.com/owncloud/ocis/45617/24/5
- https://github.com/owncloud/ocis/issues/8464
- Followup on: #8576, #11311
=> [tests-only[full-ci] skip flaky share test

.drone.env, changelog/unreleased/bump-web-to-11.3.2.md, services/web/Makefile
This update brings markdown editor fixes based on user feedback.
=> [full-ci] chore: bump Web to 11.3.2

tests/acceptance/bootstrap/CliContext.php, tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/features/cliCommands/trashBin.feature
This PR adds cli tests for restoring trashed resources 
- specific item
- all item of specific space at once
- https://github.com/owncloud/ocis/issues/11248
- locally
=> [full-ci][tests-only]Add tests for restoring specific and all trashed resources of specific space at once

tests/acceptance/TestHelpers/GraphHelper.php, tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSharingNgPermissions/listPermissions.feature
This PR has added tests for listing single sharing permission for resources using [/v1beta1/drives/{drive-id}/items/{item-id}/permissions/{perm-id}](https://owncloud.dev/libre-graph-api/#/drives.permissions/GetPermission
) api endpoint.
- https://github.com/owncloud/ocis/issues/8616
- part of https://github.com/owncloud/ocis/issues/9524
- test case 1:
- test case 2:
- ...
=> [test-ony][full-ci] add test for list single permission for resources

tests/acceptance/TestHelpers/SettingsHelper.php, tests/acceptance/bootstrap/FeatureContext.php, tests/acceptance/bootstrap/SettingsContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSettings/settings.feature
Check the personal bundle settings value after an update.
Currently, we have test scenarios to change `auto-accept-shares` and `language` settings. PR adds the checks for them.
- taken from https://github.com/owncloud/ocis/pull/11336
- related https://github.com/owncloud/ocis/issues/11335
- test environment: :raised_back_of_hand:
=> [full-ci][tests-only] check personal settings value after update

tests/acceptance/bootstrap/CliContext.php, tests/acceptance/features/cliCommands/trashBin.feature
This PR adds tests for purging trashed resources resources
used ocis env to set expiration time interval 
- STORAGE_USERS_PURGE_TRASH_BIN_PERSONAL_DELETE_BEFORE
- STORAGE_USERS_PURGE_TRASH_BIN_PROJECT_DELETE_BEFORE
- https://github.com/owncloud/ocis/issues/11248
- locally
=> [tests-only][full-ci] Add tests related to purge expired trash resources

services/search/pkg/config/engine.go, services/search/pkg/engine/bleve.go, services/search/pkg/engine/bleve/index.go, services/search/pkg/engine/bleve/option.go, services/search/pkg/engine/bleve_test.go, services/search/pkg/service/grpc/v0/service.go
Previously, the search service opened a write connection to the bleve index and kept that connection opened as long as the service was running. This means that the search service was locking out other processes from accessing the index, including the bleve cli and other replicas of the search service. Replicas of the service can't be spawned because they won't be able to access the index.
We've added a new flag to the search service in order to scale the service.
For environments where scaling isn't needed, it's recommended to set the `SEARCH_ENGINE_BLEVE_SCALE` as false (default value). This will keep the current behavior of locking the bleve index for exclusive access. This is expected to have a better performance because we won't create new connections every time, and the load in the …
=> feat: allow scaling of the search service

changelog/unreleased/add-space-editor-without-trashbin-role.md, services/graph/README.md, services/graph/pkg/config/defaults/defaultconfig.go, services/graph/pkg/unifiedrole/conversion.go, services/graph/pkg/unifiedrole/export_test.go, services/graph/pkg/unifiedrole/filter.go, services/graph/pkg/unifiedrole/roles.go, services/graph/pkg/unifiedrole/roles_test.go, services/web/pkg/theme/theme.go
Added a new built-in role: `SpaceEditorWithoutTrashbin`. This role is a subset of the `SpaceEditor` role, but it does not have list/restore resources in trashbin permissions.
- resolves https://github.com/owncloud/ocis/issues/11206
=> feat: add SpaceEditorWithoutTrashbin role

deployments/examples/oc10_ocis_parallel/docker-compose.yml, deployments/examples/ocis_full/collabora.yml, deployments/examples/ocis_full/ocis.yml, deployments/examples/ocis_full/onlyoffice.yml, deployments/examples/ocis_hello/docker-compose.yml, deployments/examples/ocis_keycloak/docker-compose.yml, deployments/examples/ocis_ldap/docker-compose.yml, deployments/examples/ocis_ocm/ocis.yml
Fix signal delivery in the docker containers for the deployment examples. This will allow a clean shutdown process in the oCIS containers.
https://github.com/owncloud/ocis/issues/11399
Signals weren't being delivered to oCIS. Docker needed to kill the containers because they didn't stop.
Manually tested. Just start the containers and stop them after a while. Shutting down the whole docker stack takes around 3 seconds, so docker doesn't need to kill the containers.
=> feat: container signals will reach ocis

deployments/examples/ocis_full/.env, deployments/examples/ocis_full/collabora.yml, deployments/examples/ocis_full/docker-compose.yml, deployments/examples/ocis_full/mailserver.yml
This PR updates the image version of the `ocis_full` deployment example.
Tested on Hetzner with master, works.
Should be merged before Addams so it is part of the derived docs.
=> [docs-only] Update ocis_full image versions

tests/acceptance/bootstrap/CliContext.php, tests/acceptance/bootstrap/FeatureContext.php, tests/acceptance/features/cliCommands/searchReIndex.feature
Delete previous search service data on the search re-indexing scenarios.
This deletes the `<ocis-data>/search` folder where search indexes are store. Deleting the previous index data and running reindexing scenarios on clean data makes the tests more stable.
=> [tests-only][full-ci] fix search reindexing cli tests

tests/acceptance/bootstrap/CliContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/cliCommands/uploadSessions.feature
This PR adds test to resume all the uploads sessions using the CLI command. 
```bash
ocis storage-users uploads sessions --resume
```
While resuming the upload sessions, currently it returns an error, reported in https://github.com/owncloud/ocis/issues/11290.
- Part of: https://github.com/owncloud/ocis/issues/11274
- Bug Report: https://github.com/owncloud/ocis/issues/11290
=> [tests-only][full-ci] added test to resume all uploads sessions

services/search/README.md
References: #11029 (feat: allow scaling of the search service)
* Updates the readme of the search service, it can now be instantiated.
* Minor text updates
=> [docs-only] Update the search service README

tests/ociswrapper/ocis/ocis.go, tests/ociswrapper/wrapper/handlers/handler.go
Handle empty service name when using `StartService`. The default should be `ocis`. Refactored to use the default value.
=> [full-ci][tests-only] refactor(wrapper): handle empty service name

deployments/examples/ocis_full/web_extensions/drawio.yml, deployments/examples/ocis_full/web_extensions/externalsites.yml, deployments/examples/ocis_full/web_extensions/jsonviewer.yml, deployments/examples/ocis_full/web_extensions/progressbars.yml, deployments/examples/ocis_full/web_extensions/unzip.yml
This PR updates the image versions for `ocis_full/web-extensions`.
Related to tags/images created in https://github.com/owncloud/web-extensions/releases on 2025.06.20
Note that importer is handled in another PR #10880 (chore: update importer)
=> [docs-only] Updating ocis_full web-extensions image versions

tests/acceptance/bootstrap/CliContext.php, tests/acceptance/features/cliCommands/uploadSessions.feature
This PR covers test scenario for restarting the upload sessions that are expired and after restarting the ocis service.
- https://github.com/owncloud/ocis/issues/11274
=> [tests-only][full-ci] restart upload sessions of unfinished uploads

tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/features/apiSharingNgAdditionalShareRole/SpaceEditorWithoutTrashbin.feature
Check that the user with `SpaceEditorWithoutTrashbinRole` role cannot restore the trashed file
From https://github.com/owncloud/ocis/pull/11448/files#r2168717736
- https://github.com/owncloud/reva/pull/293
=> [full-ci][tests-only] add step to try to restore trashed file

tests/acceptance/TestHelpers/GraphHelper.php, tests/acceptance/bootstrap/SettingsContext.php, tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSettings/settings.feature
Added test scenarios to enable share sync after disabling it
```feature
Scenario: enable auto-sync-shares after disabling it
```
- Coverage for: https://github.com/owncloud/ocis/issues/11335
- test environment: :raised_back_of_hand:
=> [tests-only][full-ci] add API test to enable share sync after disabling

docs/helpers/env_vars.yaml, services/frontend/pkg/config/config.go, services/notifications/pkg/config/config.go, services/settings/pkg/config/config.go
Some envvars did not had the full semver for their introduction version: `7.1` --> `7.1.0`
This causes some helpers not to function (catch the items) properly.
The PR also updates the `env_vars.yaml` file accordingly
=> [docs-only] Fix missing patch number in introduction version

changelog/unreleased/fix-cli-upload.md, services/storage-users/pkg/command/uploads.go, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
Backport to JIRA: [OCISDEV-141](https://kiteworks.atlassian.net/browse/OCISDEV-141)
Bugfix: Fix storage-users cli
Fix `storage-users uploads --resume` command.
https://github.com/owncloud/ocis/pull/11464
https://github.com/owncloud/ocis/issues/11290
=> Backport [OCISDEV-141]

changelog/unreleased/fix-watermark-viewer-role.md, services/collaboration/pkg/connector/fileconnector.go, services/collaboration/pkg/connector/fileconnector_test.go
JIRA: [OCISDEV-164](https://kiteworks.atlassian.net/browse/OCISDEV-164)
---
Fix the OCM role editor
Fix the issue when the watermark is visible to user with a viewer role in Collabora
https://github.com/owncloud/ocis/pull/11484
https://github.com/owncloud/ocis/issues/11474
=> backport: [OCISDEV-151] the watermark is visible to user with a `viewer role` in Collabora

docs/ocis/guides/ocis-local-docker.md
The "Discover OCIS with Docker" lacks the critical piece of ownership of the folders. Otherwise it will not start.
The documentation for the Discovery of OCIS lacks the information of the required user for the files that need to be read by OCIS
-
I wanted to give it a spin, this part of the documentation seemed more appropriate and therefore failed upon that.
Used the commands from the "Minimalistic Evaluation Guide for oCIS with Docker"
=> Update Discover OCIS with Docker Documentation

tests/acceptance/features/apiSharingNgDriveInvitation/updateDriveShareInvitations.feature, tests/acceptance/features/apiSharingNgItemInvitation/updateItemShareInvitations.feature
This PR updates the date time in test scenarios. Most of the test failed with `400` error due to some test containing dates which had already passed (yesterday's date).
Failed builds:
- https://drone.owncloud.com/owncloud/ocis/47061/31/5
- https://drone.owncloud.com/owncloud/ocis/47060/31/5
- https://drone.owncloud.com/owncloud/ocis/47062/31/5
- https://drone.owncloud.com/owncloud/ocis/47063/30/5
- https://drone.owncloud.com/owncloud/ocis/47064/26/5
=> [tests-only][full-ci] update expiration date time in test scenraios

ocis-pkg/oidc/client.go
Assuming a compatible telemetry is available in the external IDP, requests made by oCIS against the IDP will contain telemetry data to propagate the information to the IDP.
Send the telemetry headers to the IDP
https://github.com/owncloud/ocis/issues/11298
The IDP can follow the opentelemetry standard, so sending the headers would allow us to link the requests
Manually tested during login and logout. Checked with Keycloak 26.2.5 and jaeger 2.7.0
Note that Keycloak makes a "backchannel logout" request, which is catched by ocis, which also sends another requests to the ".well-known" Keycloak endpoint. This means that the token is caught and then resent to Keycloak
=> fix: propagate telemetry to the IDP

.drone.star
Replaces the hardcoded GitHub repo (`owncloud/ocis`) in the `wget` command with `ctx.repo.slug`, making the URL generation dynamic.
=> [tests-only][full-ci] CI: Replace hardcoded repo in wget URL with dynamic ctx.repo.slug

ocis-pkg/middleware/tracing.go, ocis-pkg/oidc/client.go, ocis-pkg/tracing/tracing.go, services/collaboration/pkg/connector/contentconnector.go, services/search/pkg/content/cs3.go, services/thumbnails/pkg/thumbnail/imgsource/cs3.go, services/thumbnails/pkg/thumbnail/imgsource/webdav.go, services/webdav/pkg/service/v0/service.go
The "tracing.GetNewRequest" and "tracing.GetNewRequestWithContext" aim to replace the "http.NewRequest" and "http.NewRequestWithContext" respectively by including tracing data.
For requests that have been already created, such as the case of some reva requests, "tracing.InjectTracingHeaders" is provided.
Note that some outgoing requests might be required NOT to use tracing headers.
Described above
No open issue
Improve visibility of the traces
Manually checked with jaeger and the affected services.
There are some services that still have the `http.NewRequest` method:
* antivirus -> A new background context is created for each event that we're processing. This context doesn't have "previous data", so we won't get the whole picture, just from that point onward.
In addition, we'd need some …
=> feat: Homogenize tracing of requests to other services

docs/_index.md
This PR replaces the old talk link with matrix.
I also changes the admin doc link from `next` to `latest`
=> [docs-only] Fix chat link in dev docs

deployments/examples/ocis_full/.env, deployments/examples/ocis_full/config/onlyoffice/entrypoint-override.sh, deployments/examples/ocis_full/onlyoffice.yml, deployments/examples/ocis_full/web_extensions/externalsites.yml
feat: added the onlyoffice ee license to the ocis deployment.
- test case 1:
- test case 2:
- ...
=> feat: added the onlyoffice ee license to the ocis deployment.

changelog/unreleased/update_ocis_full.md, deployments/examples/ocis_full/.env, deployments/examples/ocis_full/collabora.yml, deployments/examples/ocis_full/docker-compose.yml, deployments/examples/ocis_full/onlyoffice.yml
This PR updates the `ocis_full` deployment example:
* Fix description texts
* Move image version from collabora, onlyoffice and traefik  `.yaml` files to `.env` file
* Ease OnlyOffice EE license handling
* Set the default ocis image base to production 
Note that it is not advised to use the latest version for images where a specific version is preferred. We know from experience that issues may arise, especially with web office images. They need individual testing!
Everything has been tested on Hetzner including OnlyOffice-ee, the latter without license key = trial period.
=> [docs-only] Update the ocis_full deployment example

changelog/unreleased/fix-capabilities-public-path.md, services/proxy/pkg/middleware/authentication.go
Following the same behavior as OCS v1, we added the OCS v2 capabilities endpoint to the public paths.
Capabilities can be retrieved in public links context same as with OCS v1.
- resolves https://github.com/owncloud/web/issues/13130
- test environment: macos, chrome
- test case 1: open public link and see successful capabilities request in network tab
=> fix: [OCISDEV-330] add OCS v2 capabilities endpoint to public paths

deployments/examples/ocis_full/.env
This PR updates the `ocis_full` deployment images where a version number is required.
* traefik and collabora
* web-extensions
NOT UPDATED YET - on the works, commit will be added when versions are available @mzner @LukasHirt
=> [docs-only] Update the ocis_full images for Balch

services/idp/ui_config/webpack.config.js
Remove file-loader from webpack.config.js to avoid error with new Go version. The file-loader is also legacy loader from older webpack versions. Since we are using webpack 5, we don't need it anymore. We are already using the asset modules instead.
Drop legacy code, exclude unwanted files in prod builds, and prevent build errors with Go v1.25.x.
- test environment: macos, go v1.25.1, node v22.19.0, pnpm v10.4.1
- test case 1: run `make -C ocis clean generate build`
=> chore(idp): [OCISDEV-352] remove file-loader from webpack.config.js

docs/architecture/upload-processing.md
The mermaid diagrams in `docs/architecture/upload-processing/upload-processing.md` were broken.
Fixed and locally tested - works again.
=> [docs-only] Fix mermaid diagrams
