owncloud/ocis

go.mod, go.sum, pkg/command/phoenix.go, pkg/command/phoenix_ocis.go
Depends on https://github.com/owncloud/ocis-phoenix/pull/28
Usage:
`ocis phoenix --web-config-apps "files, markdown-editor, pdf-viewer, draw-io"`
=> Make Phoenix's command parse a list of available apps

pkg/command/konnectd.go
I assumed that ocis will call the required [hooks](https://github.com/owncloud/ocis-konnectd/blob/05b45e4802e88ddb51a3cc9ea47b65102f15754a/pkg/command/server.go#L33) "automatically". Turns out this is not the case. 
Should all sub-commands be modified to call Before, or are we able to centralize this somehow? Is it the responsibility of the service to care for the hook calling order in ocis?
I didn't wrap the before call in Before because this would require to call configureServer twice.
Please advice. 
Closes #121
=> Call urfave before hook

README.md
Move the prerequisites before the quickstart section to make sure people read them and execute them beforehand.
=> Move readme prerequisites before the quickstart

Makefile
Without this I get `could not launch process: could not open debug info` when trying to attach to a runnig ocis-debug process.
This PR allows me to attach to a running process with the debugger.
=> do not strip debug data for debug build

.drone.star
Phoenix acceptance tests were failing in ocis ci due to missing phoenix config.json file inside dist folder
This pr adds config.json inside dist of phoenix source
=> Added config.json inside phoenix dist

tests/config/drone/identifier-registration.yml
analog to https://github.com/owncloud/phoenix/pull/3374
with `trusted: yes` in the configuration the authentication of the webapp (phoenix) in kopano is not needed
the basic configuration when starting `ocis server` has that setting set, so we avoid different environments and confusion during testing
=> [Tests-only] remove need to authorize phoenix in kopano

tests/config/drone/identifier-registration.yml
for the logout to work correctly with kopano, we need the `/` at the end of the uri
=> [Tests-only] add slash at the end of redirect_uri to allow correct logout

docs/bridge.md
Update bridge documentation to current code status
Also we probably have to erase or rewrite this part due to finally the decision taken was in favor of a non core change in the oauth app: owncloud/oauth2#255 :
```
Patch owncloud
While the UserSession in ownCloud 10 is currently used to test all available IAuthModule implementations, it immediately logs out the user when an exception occurs. However, existing owncloud 10 instances use the oauth2 app to create Bearer tokens for mobile and desktop clients.
To give the openidconnect app a chance to verify the tokens we need to change the code a bit. See https://github.com/owncloud/core/pull/37043 for a possible solution.
Note: The PR is hot … as in younger than this list of steps. And it messes with authentication. Use with caution.
```
=> Update bridge documentation

docs/login-flow.md, docs/request-flow.md
Login flow
- remove dedicated konnectd to simplify diagram. Is expressed by the alt description anyway
- clarify discovery: we currently neet to have an idp preconfigured, so we can always redirect clients to that idp.
- the Idp MUST authenticate all users, including guest users. Either the build in konnectd is used with glauth, or an external idp is used.
- external idps can use glauth to let ocis handle provisioning of guest accounts or an out of bounts process is used to provision guest accounts, which then requires them to be synced to the accounts service as well
Request flow
- clarify where account provisioning and token minting are happening, see https://github.com/owncloud/ocis-glauth/issues/13
=> update login and request flow diagrams

docs/bridge.md
@davitol this should solve your https://github.com/owncloud/oauth2/issues/262#issuecomment-624466154
In the logs of glauth you should see what datastore is used:
```
2020-05-06T17:19:01+02:00 INF Using backend datastore=owncloud name=glauth service=glauth verbosity=3
```
=> udpate bridge doc to use correct glauth datastore

.drone.star
Phoenix already uses `owncloudci/nodejs:11` docker images when running acceptance tests.
https://github.com/owncloud/phoenix/blob/master/.drone.star - runWebuiAcceptanceTests
```
'image': 'owncloudci/nodejs:11',
```
Make it consistent here.
=> [Tests-Only] Use owncloudci/nodejs:11 for phoenixWebUIAcceptanceTests

.drone.star
Part of issue #303 
Specify the branch, and commit in that branch, to use when fetching the ownCloud10 core API test runner code. And also for when fetching the phoenix UI test runner code.
=> [Tests-Only] Run API and UI tests from specified branch-commits

changelog/unreleased/update-reva-config, pkg/command/revastoragepubliclink.go
Add missing changelog for the eos config change.
Fixed the reva public link service command to register properly.
=> Fix reva public link service command + changelog

Makefile, changelog/unreleased/update-reva-config
part of https://github.com/owncloud/ocis/pull/336
=> fix home storage configuration for eos

.drone.star
Run the test infrastructure from:
- apiTests - core commit d5c495eeff535a61856762ae7f8baf6e74abeecf
- UI tests - phoenix commit f9a0874dc016ee0269c698914ef3f2c75ce3e2e6 (that got merged last night in #334 )
To demonstrate that the latest test code passes against the current OCIS.
If it passes, then it is fine to merge. At least this will demonstrate that the test code is all OK with the current OCIS master.
Note: these commit ids should be updated regularly
=> [Tests-Only] Bump core and phoenix test commit IDs to latest

.drone.star, docs/testing.md
See core PR https://github.com/owncloud/core/pull/37616 - all these tags no longer need to be specified.
`skipOnOcis` is the important one.
PR #346 demonstrated that this will work.
=> [Tests-Only] Remove unneeded TestAlsoOnExternalUserBackend local_storage skipOnLDAP tags

go.mod, go.sum, pkg/command/run.go, pkg/runtime/runtime.go
1. start runtime: `ocis server`
on another session:
2. `ocis kill phoenix`
3. `export PHOENIX_HTTP_ADDR=localhost:9888`
4. `ocis run phoenix`
5. `lsof -i:9888`
expected: phoenix running on `localhost:9888`, as propagated from the parent process environment. `ocis run` will receive the environment of the caller process
=> Set process environment

docs/testing.md
Fixes #352
Add doc for cloning testing app while running tests for skeleton files.
=> [Docs] Add doc for cloning testing app for running tests

docs/testing.md
Add env variable for path to skeleton directory in documentation to run API acceptance tests.
=> [Docs] Add skeleton dir path env variable in test run

.drone.star
Part of issue https://github.com/owncloud/user_ldap/issues/578
Remove the offending `HOSTNAME`env var in CI. Use the latest osixia/openldap
See similar fix in https://github.com/owncloud/phoenix/pull/3738
=> [Tests-Only] Use latest osixia/openldap in CI

config/eos-docker.env, docker-compose.yml, docs/development.md, docs/eos.md
This PR adds a new docker-compose.yml file that allows developers to quickly spin up a development environment for ocis using both: the owncloud storage driver as well as the eos storage driver. For the latter it also contains the necessary eos containers
1. start a container for ocis: `docker-compose up -d ocis`
> Note: On MacOS do not mount a local folder at the owncloud storage drivers data location. It uses a fuse based driver which does not support extended attributes.
2. initialize empty shares list: `docker-compose exec ocis bash -c "echo '{}' > /var/tmp/reva/shares.json"`
3. compile ocis inside the container using `docker-compose exec ocis make clean build`. this makes sure that all cgo bindings are there and the binary will work properly when resolving ldap users
4. run ocis …
=> initial docker-compose.yml for developers

.drone.star
This will include https://github.com/owncloud/phoenix/pull/3748 tests for comma in the file name, among other recent stuff in phoenix. More test scenarios running = less regressions.
=> [Tests-Only] Update phoenix tests commit

.drone.star
to the latest commit id from phoenix master.
(may as well do this now, #366 is updating the core commit id for tests but is blocked waiting for a suitable `ocis-reva` to become available)
=> [Tests-Only] Bump phoenix test commit id

go.mod, go.sum, pkg/command/store.go
First draft of adding go-micro store as part of the runtime. For the purposes of this PR, we're using [the `file` implementation](https://github.com/micro/go-micro/blob/master/store/file/file_test.go) of the store.
Please note we're not using `ocis-pkg` because it does not yet have support for the [`Store` argument](https://github.com/owncloud/ocis/pull/384/files#diff-9fcb30ab872bfea3331cf945e7918d8bR46).
=> Add Micro Store

.drone.star
Related Issue: https://github.com/owncloud/ocis/issues/303
Use phoenix assets packaged in the binary to run the webUI tests in CI.
=> [Tests-only] use built in phoenix to run ui tests

.drone.star
So that we have the latest phoenix test-runner scenarios when testing.
=> [Tests-Only] Update phoenix acceptance test commit id

changelog/unreleased/simplify-tracing.md, docs/tracing.md, pkg/command/glauth.go, pkg/command/graph-explorer.go, pkg/command/graph.go, pkg/command/konnectd.go, pkg/command/ocs.go, pkg/command/phoenix_ocis.go, pkg/command/phoenix_simple.go, pkg/command/proxy.go, pkg/command/revaauthbasic.go, pkg/command/revaauthbearer.go, pkg/command/revafrontend.go, pkg/command/revagateway.go, pkg/command/revasharing.go, pkg/command/revastorageeos.go, pkg/command/revastorageeosdata.go, pkg/command/revastoragehome.go, pkg/command/revastoragehomedata.go, pkg/command/revastorageoc.go, pkg/command/revastorageocdata.go, pkg/command/revastoragepubliclink.go, pkg/command/revastorageroot.go, pkg/command/revausers.go, pkg/command/settings.go, pkg/command/thumbnails.go, pkg/command/webdav.go, pkg/flagset/flagset.go
With this PR, the `OCIS_TRACING_*` config variables become the global config for all services. If you want to set individual tracing config for each service, set `OCIS_TRACING_ENABLED=false` (which is the default) and configure tracing for all services individually.
Tracing documentation updated as well, to reflect both different usages (global config and per-service config).
Implementation for https://github.com/owncloud/product/issues/92
=> Simplify config

.drone.star
This demonstrates that current OCIS master is still passing with the latest core API tests.
=> [Tests-Only] Bump core commit for API tests 2020-08-15

tests/acceptance/features/apiOcisSpecific/apiWebdavPreviews-previews.feature
1) put back the local preview test scenarios that demonstrate the current preview behavior (they were deleted in #409 )
2) Adjust the test expectations to match what actually happens currently
=> Put back local preview test scenarios

.drone.star, docs/testing.md, tests/acceptance/expected-failures-on-EOS-storage.txt, tests/acceptance/expected-failures-on-OC-storage.txt
In the same way as https://github.com/owncloud/ocis-reva/pull/444
In preparation for running API acceptance tests with EOS  storage, have 2 expected-failures files. These can contain the expected-failures on each storage.
Note: the 2 files will have many scenarios listed that are the same, for things that fail on both OC and EOS storage. IMO that is OK, because as things get fixed they might get fixed on one storage first, and then the other. So the lists can be reduced independently when needed.
If we find that it would be better to have a common-expected-failures.txt and 2 smaller expected-failures files for specific OC and EOS storage then we can do that. But it will require changes to the core `run.sh` script to support combining multiple expected-failures files.
=> [Tests-Only] Implement separate expected-failures files for OC and EOS storage

changelog/unreleased/integrate-accounts-cli.md, pkg/command/accounts.go
Closes https://github.com/owncloud/ocis/pull/422
Closes https://github.com/owncloud/product/issues/115
```
~/c/o/ocis:λ bin/ocis accounts ls
+--------------------------------------+--------------------------------+----------------------+----------------+
|                  Id                  |          DisplayName           |         Mail         | AccountEnabled |
+--------------------------------------+--------------------------------+----------------------+----------------+
| 4c510ada-c86b-4815-8820-42cdf82c3d51 | Albert Einstein                | einstein@example.org | true           |
| 820ba2a1-3f54-4538-80a4-2d73007e30bf | Kopano Konnectd                | idp@example.org      | true           |
| 932b4540-8d16-481e-8ef4-588e4b6b151c | Richard Feynman                | …
```
=> Integrate account-management cli-commands

changelog/unreleased/add-missing-env-vars.md, docker-compose.yml
REVA_FRONTEND_URL and REVA_DATAGATEWAY_URL need to be set to the OCIS_DOMAIN so upload is not using localhost ;-)
cc @jnweiger
=> set missing env vars

.drone.star, tests/acceptance/expected-failures-on-OC-storage.txt
Some changes were made to the `toImplementOnOcis` tag in core PR https://github.com/owncloud/core/pull/37774 so that:
- test scenarios related to group sharing are not run at the moment (most of them were already tagged `toImplementOnOcis`  but this makes it consistent by tagging a couple more scenarios)
- adjust some sharing tests to run more of them. For some `acceptShare` scenarios they currently fail, so they are added to the expected failures.
This is the same as https://github.com/owncloud/ocis-reva/pull/448
=> [Tests-Only] Bump core commit for tests 20200820

.drone.star
Solves an issue that whenever some tests use basic auth the IDP was
wrong. This would make Reva use the wrong internal user id and IDP
and prevent matching some data like shares to the correct user id.
First part of: https://github.com/owncloud/product/issues/161
Second part will be reenabling the failing tests.
=> Add missing LDAP IDP value

changelog/unreleased/clear-external-apps.md, pkg/command/phoenix_ocis.go
We have a new feature in ocis-phoenix, that creates a default set of external apps if there is no config.json for ocis-web provided. There was this line in ocis, that was blocking the default set of external apps from ocis-phoenix. As it was not doing what it comment promised anyway, we can safely remove it and let ocis-phoenix handle the defaults.
=> External app config

changelog/unreleased/settings-update-2020-08-21.md, go.mod, go.sum
State is WIP until we have releases for ocis-phoenix, ocis-settings and ocis-accounts with the respective required commits.
This will bring:
- refactored data model in ocis-settings
- uuids in ocis-settings
- endpoints for role- and permission-management in ocis-settings
- ~~role selection in accounts ui of ocis-accounts~~
tags for:
=> Bring basic roles and permissions for ocis-settings

.drone.star
Gets us recent changes in core acceptance test code in `run.sh` etc.
e.g. https://github.com/owncloud/core/pull/37841
https://github.com/owncloud/core/pull/37838
https://github.com/owncloud/core/pull/37844
- do not run any tests tagged `local_storage`. Those are not currently useful at all, an cause `BeforeScenario` prblems:
```
@local_storage @skipOnEncryptionType:user-keys @encryption-issue-42 @skip_on_objectstore
Scenario Outline: Deleting a folder into external storage moves it to the trashbin                # /srv/app/testrunner/tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature:160
Given using <dav-path> DAV path                                                                 # FeatureContext::usingOldOrNewDavPath()
And the administrator has invoked occ command …
```
=> [Tests-Only] Bump core commit id

docs/testing.md
This PR edits the testing docs to run the tests without ldap server.
- https://github.com/owncloud/product/issues/176
=> Adjust testing docs to run tests without ldap server

.drone.star
Before this gets merged we need to add the `webhook_username` and `webhook_password` to the secrets.
=> add webhook step to drone build to update ocis.owncloud.works

tests/acceptance/config/behat.yml
Local API tests are getting:
https://cloud.drone.io/owncloud/ocis/1317/3/7
```
148 scenarios (143 passed, 5 undefined)
1118 steps (1092 passed, 21 undefined, 5 skipped)
3m58.15s (15.84Mb)
--- FeatureContext has missing steps. Define them with these snippets:
/**
* @Given as :arg1 file :arg2 should exist in the trashbin
*/
public function asFileShouldExistInTheTrashbin($arg1, $arg2)
{
throw new PendingException();
}
...
```
Trashbin tests were introduced in #489 but TrashbinContext was not added.
=> [Tests-Only] Add TrashbinContext to local acceptance tests

docker-compose.yml, docs/eos.md
when accessing /eos we need to use the `eos` driver that does not apply the home layout. The first path segment is provided by clients accessing the `/dav/files/<userid>` endpoint. This PR will make the current configuration work with the existing code in reva for the eos driver as well as the ocdav implementation for the `/dav/files` endpoint.
The `/Shared` folder only makes sense for the `/home` namespace. when accessing `/eos` it is not part of the tree.
=> use eos driver for /eos namespace

changelog/unreleased/update-settings-26_08_2020.md, go.mod, go.sum
This PR updates ocis-settings to 0.3.1 and ocis-accounts to 0.4.1
Steps of things to do in the release ticket: https://github.com/owncloud/ocis/issues/497
=> Update ocis-settings to 0.3.1 and ocis-accounts to 0.4.1

changelog/unreleased/permission-checks-in-ocis-accounts.md, go.mod, go.sum
This PR brings ocis-accounts, ocis-settings, ocis-proxy and ocis-pkg/v2 to ocis. Main feature is permission checks for account management. Admin role has the account management permission, user role doesn't have it. Thus, regular users will not be able to fetch or modify users in the accounts app anymore.
In the future we will hide the accounts UI extension for users without account mgmt permissions entirely.
=> Bring account management from ocis-accounts

tests/acceptance/expected-failures-on-OC-storage.txt
I raised issues about why these new test scenarios fails. Add links in the expected failures file.
=> [Tests-Only] Add issue links for failing acceptSharesToSharesFolder scenarios

.drone.star
Gets us these test-related changes:
https://github.com/owncloud/phoenix/pull/4005 [tests-only] Add ocis-accounts default admin user to tests
https://github.com/owncloud/phoenix/pull/4050 [tests-only] mark some tests as @ocisSmokeTest
https://github.com/owncloud/phoenix/pull/4051 [tests-only] Skip a test that blows up the environment on ocis
https://github.com/owncloud/phoenix/pull/4036 [Tests-Only]Added test for accessing a permalink anonymously
=> [tests-only] Bump Phoenix UI test commit id

changelog/unreleased/update-accounts-create-users.md, changelog/unreleased/update-accounts-delete-users.md, changelog/unreleased/update-accounts-enable-disable-users.md, changelog/unreleased/update-proxy-disable-cache.md, go.mod, go.sum
This PR updates ocis-accounts to a version with our new enable/disable, delete and create features in the web ui. It also updates ocis-proxy with a bugfix for this feature: modified accounts were not updated in the accounts cache in ocis-proxy. Since ocis-accounts is already taking care of caching accounts, we removed the accounts cache in ocis-proxy entirely (at least for now) to spare us from cache invalidation in the proxy when updating an account in ocis-accounts.
=> Update proxy and accounts for enable/disable, create, delete accounts

changelog/unreleased/update-reva-10_09_2020.md, go.mod, go.sum, tests/acceptance/expected-failures-on-OC-storage.txt
- ocis-reva v0.13.1-0.20200910085648-26465bbdcf46
- fixes file operations for received shares by changing OC storage default config
- adds ability to overwrite storage registry rules
Closes https://github.com/owncloud/product/issues/193
Closes https://github.com/owncloud/product/issues/205
=> Update ocis-reva 2020-09-10

tests/acceptance/expected-failures-on-OC-storage.txt
`apiShareManagementBasic` suite was renamed in core, and new suites made. Expected failures for this suite were accidentally left in expected-failures-on-OC-storage. CI did not fail, because this suite never runs, so the code in CI never gets to process these at all.
Clean it up.
=> [Tests-Only] Cleanup old entries from expected-failures-on-OC-storage

.drone.star, tests/acceptance/expected-failures-on-OCIS-storage.txt, tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt
Gets https://github.com/owncloud/core/pull/37882 "[Tests-Only] Add some more flexible provisioning API tests for getUsers"
=> [Tests-Only] Bump core commit for tests 20200914

.drone.star
Gets us:
https://github.com/owncloud/core/pull/37913 [Tests-Only] Report HTTP status when file content is wrong
That helps to see the HTTP  status of a test when the downloaded file content is wrong.
=> [Tests-Only] Bump core commit for tests 20200915

changelog/unreleased/improve-reva-service-descriptions.md, pkg/command/revastorageeos.go, pkg/command/revastorageeosdata.go, pkg/command/revastoragehome.go, pkg/command/revastoragehomedata.go, pkg/command/revastorageoc.go, pkg/command/revastorageocdata.go
The descriptions make it clearer that the services actually represent a
mount point in the combined storage. Each mount point can have a
different driver.
=> Improve reva storage service descriptions

.drone.star
- After the migration to drone.owncloud.com, arm64 and arm arches are available again.
- Enable the docker build pipelines
@xoxys @felixboehm @hodyroff
=> Re enable arm64 and arm docker piplines

glauth/changelog/unreleased/add-build-info-metric.md, glauth/pkg/command/root.go, glauth/pkg/command/server.go, glauth/pkg/config/config.go, glauth/pkg/metrics/metrics.go, ocis/pkg/command/glauth.go
Since the glauth service is not a go-micro service we can not use the registry to list all glauth services, that is why there is no version command (yet).
This adds build information to the glauth service
=> add build information to metrics

ocis-reva/changelog/unreleased/enable-treetime-accounting.md, ocis-reva/pkg/command/drivers.go
We enabled treetime accounting in the ocis driver.
=> enable ocis driver treetime accounting

.drone.star
- The unit and basic integration tests are executed in different pipelines
- The coverage needs to be uploaded to a coverage provider
- Collect all coverage reports in an S3 Cache (cache.owncloud.com)
- Add a `coverage-upload` pipeline after all unit tests have run
- Upload the complete coverage reports in one step
=> [Tests-Only] Send coverage to S3 Cache

ocis/config/eos-docker.env
This configuration file was missing after the mono repo was created.
=> readd the eos docker config

proxy/changelog/unreleased/add-autoprovision-accounts-flag.md, proxy/pkg/command/server.go, proxy/pkg/config/config.go, proxy/pkg/flagset/flagset.go, proxy/pkg/middleware/account_uuid.go, proxy/pkg/middleware/options.go
Added a new `PROXY_AUTOPROVISION_ACCOUNTS` environment variable. When enabled, the proxy will try to create a new account when it cannot match the username or email from the oidc userinfo to an existing user. Enable it to learn users from an external identity provider. Defaults to false.
fixes https://github.com/owncloud/product/issues/219
fixes https://github.com/owncloud/ocis/issues/629
=> Add autoprovision accounts flag

ocs/pkg/server/http/svc_test.go
Add HTTP api test for
- GET /ocs/vx.php/cloud/capabilities
- GET /ocs/vx.php/config
Moved from https://github.com/owncloud/ocis-ocs/pull/60
=> [Tests-Only] Ocs http test config and capabilities endpoints

ocis/docker-compose.yml
added volumes for the different submodules to make the docker compose file work with the replaces in go.mod
Fixes: https://github.com/owncloud/product/issues/242
=> modify docker-compose file to work with mono repo

docs/extensions/storage/testing.md
1. default ocis data-root has changed
2. the proxy address should be used everywhere, so that all ocis functions are availiable
=> [docs-only] Fix docs

storage/templates/CONFIGURATION.tmpl
The storage driver config was not parsed, because it doesn't belong to a command.
Fixed that in the template
=> [docs-only] Add Storage Driver Config to flaex

.drone.star, ocs/pkg/server/http/svc_test.go
SonarCloud reports that `svc_test.go` is the code with the highest amount of duplications - https://sonarcloud.io/component_measures?id=owncloud_ocis&metric=duplicated_blocks&selected=owncloud_ocis%3Aocs%2Fpkg%2Fserver%2Fhttp%2Fsvc_test.go&view=list
I wanted to see what SonarCloud does when improving this sort of stuff. And also to not touch "real"  code at first. So here is a refactoring of test code.
Does it seem "a good thing" to add a bunch of constants that remove the main repeated crud throughout the tests?
=> [Tests-Only] Refactor svc_test to add constants for repeated strings

docs/ocis/eos.md, ocis/docker-compose.yml
reva was renamed to storage, including all commands and env. variables
=> [docs-only] rename reva to storage in EOS docs & docker-compose

.drone.star
using new switch from https://github.com/owncloud/core/pull/38005 to decides how to provision the skeleton folder 
tests pass, except one flaky MOVE test, see https://github.com/owncloud/product/issues/249
=> [tests-only] new env. variable to set how files/folders are provisioned for tests

.drone.star
`.drone.star` syntax is currently broken.
Hotfix
=> [Tests-Only] Fix .drone.star syntax

ocis/pkg/runtime/options.go, ocis/templates/CONFIGURATION.tmpl, ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt, ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt
1) "standardize" the expected-failures files:
a) remove blank lines
b) have a comment line `#` before and after each actual comment
c) adjust words of comments to be the same in each file
This reduces the "rubbish" in a diff of the `owncloud` and `ocis` expected failures files. There are still differences, but they are "real".
2)  fix a couple of minor typos
=> [tests-only] Adjust expected-failures files to be similar

.drone.star
Includes core PR https://github.com/owncloud/core/pull/38009 in the test code.
=> [tests-only] Bump core commit for tests to include core PR 38009

.drone.star
Gets test code from core PR https://github.com/owncloud/core/pull/38011
=> [tests-only] Bump core commit for tests as at 20201015

ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt, ocis/tests/acceptance/features/apiOcisSpecific/apiAuthOcs-ocsDELETEAuth.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiAuthOcs-ocsPOSTAuth.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiAuthOcs-ocsPUTAuth.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiShareCreateSpecial2-createShareWithInvalidPermissions.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiShareManagementBasic-createShare.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiShareOperations-gettingShares.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiSharePublicLink1-createPublicLinkShare.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiSharePublicLink2-updatePublicLinkShare.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiSharePublicLink2-uploadToPublicLinkShare.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiShareUpdate-updateShare.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiTrashbin-trashbinDelete.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiWebdavMove1-moveFolderToBlacklistedName.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiWebdavMove2-moveFile.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiWebdavMove2-moveFileToBlacklistedName.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiWebdavProperties1-setFileProperties.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiWebdavProperties2-getFileProperties.feature, ocis/tests/acceptance/features/apiOcisSpecific/apiWebdavUpload1-uploadFile.feature
Apply minor differences from the test files in `cs3org/reva` to here in `owncloud/ocis` so that there is less brain-pain when comparing the state of the tests between the 2 repos.
=> [tests-only] Sync tests with cs3org reva

changelog/unreleased/glauth-micro-client, glauth/pkg/command/server.go
... was causing file descriptor leaks
=> Use micro default client for connections to account service

ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt, ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt, ocis/tests/acceptance/features/apiOcisSpecific/apiShareManagementBasic-deleteShare.feature
1. fix the description in the expected failures files why apiShareManagementBasicToShares/deleteShareFromShares.feature:43 & :44 fail
2. extend the bug-demonstration scenario to make sure it fails if #720 get fixed
=> [tests-only] tests to demonstrate issue #720

.drone.star, ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt, ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt
1) Includes these core test-related PRs in the testing:
https://github.com/owncloud/core/pull/38020 [Tests-Only] Fix mixed-case and uppercase username in API test
https://github.com/owncloud/core/pull/38022 [tests-only] remove unused folder parameter from Favorites test-functions
https://github.com/owncloud/core/pull/38023 [Tests-Only]Refactored bug demonstration scenarios for api test
https://github.com/owncloud/core/pull/38024 [Tests-Only]Refactored some more bug demonstration scenarios for webUI test
https://github.com/owncloud/core/pull/38025 [Tests-Only] Oc10 bug demonstration scenarios added separately for webUI tests
https://github.com/owncloud/core/pull/38026 [tests-only] Remove misleading error output from run.sh
Note: some of these refactor webUI tests, which are not run in …
=> [tests-only] Bump core commit for API tests

accounts/pkg/indexer/index/cs3/autoincrement.go, accounts/pkg/indexer/index/cs3/non_unique.go, accounts/pkg/indexer/index/cs3/unique.go, accounts/pkg/indexer/indexer.go, accounts/pkg/indexer/option/option.go, accounts/pkg/storage/cs3.go, changelog/unreleased/mint-token-with-uid.md
The eos driver expects the uid and gid from the opaque map of a user. While the proxy does mint tokens correctly, the accounts service wasn't.
=> Mint token with uid and gid

accounts/pkg/service/v0/accounts.go, changelog/unreleased/fix-id-or-username-query-handling.md
The code was stopping execution when encountering an error while loading an account by id. But for or queries we can continue execution.
=> Fix id or username query handling

docs/extensions/accounts/getting-started.md, docs/extensions/konnectd/getting-started.md, docs/extensions/ocs/getting-started.md, docs/extensions/proxy/getting-started.md, docs/extensions/settings/getting-started.md, docs/extensions/store/getting-started.md, docs/extensions/thumbnails/getting-started.md, docs/extensions/webdav/getting-started.md
We could consider just pasting the usage printed by the commands to the docs since they are 'documentation' and are easier to update.
For example here the usage from the accounts service:
```
NAME:
ocis accounts - Start accounts server
USAGE:
ocis accounts command [command options] [arguments...]
COMMANDS:
list, ls        List existing accounts
add, create, a  Create a new account
update          Make changes to an existing account
remove, rm      Removes an existing account
inspect         Show detailed data on an existing account
version         Print the versions of the running instances
help, h         Shows a list of commands or help for one command
OPTIONS:
--http-namespace value             Set the base namespace for the http namespace (default: "com.owncloud.web") …
```
=> [Docs-only] add version command to docs

ocis/docker-compose-eos-test.yml, ocis/docker/eos-ocis/entrypoint
We introduce a PR that adds a new docker compose file for testing on eos.
```
cd ocis
docker-compose -f docker-compose-eos-test.yml up
```
=> introduce docker-compose eos setup

.drone.star, ocis/vendor-bin/behat/composer.json
Issue https://github.com/owncloud/core/issues/38067
See issue for details - `behat` acceptance tests need to use PHP  7.4 for the dependencies to sort themselves out with composer 2.0
=> [tests-only] Adjust PHP dependencies for composer 2.0

changelog/unreleased/konnectd-switchacc-consent.md, konnectd/ui/src/containers/Login/Login.js
Multiple prompt values are allowed and this change fixes the check for
select_account if it was used together with other prompt values. Where
select_account previously was ignored, it is now processed as required,
fixing the use case when a RP wants to trigger select_account first
while at the same time wants also to request interactive consent.
=> Fix processing for prompt select_account with consent

docs/extensions/storage/_index.md
Migrating from https://github.com/owncloud/ocis-reva/pull/482 
> https://owncloud.github.io/extensions/storage/ port reference seemed broken.
=> Fix md table on doc's index: use '|' as column delimiter

deployments/examples/ocis_oc10_backend/docker-compose.yml
Fix  "letsencrypt" is used in service "traefik" but no declaration was found in the volumes section.
=> Add letsencrypt as named volume

.drone.star
Makes sure that we are testing with the code in core PR  https://github.com/owncloud/core/pull/38077
There should be no change needed to OCIS other than bumping the core commit id.
=> [tests-only] Bump core commit id to include test code of PR 38077

.drone.star, ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt, ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt
Includes changes from:
https://github.com/owncloud/core/pull/38075 [Tests-Only] Remove skipOnOcis tags
https://github.com/owncloud/core/pull/38079 [Tests-Only] unskip etag propagation tests for oc storage in ocis
https://github.com/owncloud/core/pull/38080 [tests-only] Adjust skipOnOcis-OC-Storage for etag test scenarios
This gets more of the API test scenarios running in CI. So we will know if their pass/fail status changes with new PRs.
=> [Tests-Only] update core commitid for test runner

changelog/unreleased/ocs-map-userid-to-username.md, ocs/pkg/service/v0/users.go
the ocs should always expose the username. it is oblivious of our persistent account.id
=> hide account.id in ocs api, use username

.drone.star, ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt, ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt
Includes changes to core tests from
https://github.com/owncloud/core/pull/38092 Update sabre/dav (4.1.2 => 4.1.3) Webdav PUT of a file into a non-existent folder is expected to return 409.
https://github.com/owncloud/core/pull/38095 [Tests-Only] Refactored Oc10 bug demonstration scenarios that were tagged issue-core-nnnn
https://github.com/owncloud/core/pull/38093 [Tests-Only] fix user initialize and check on ocis
https://github.com/owncloud/core/pull/38096 [tests-only] skip on old oCV10 for scenarios that were added or changed by issue 38089
https://github.com/owncloud/core/pull/38097 [tests-only] Fix acceptance test exit status when running a single scenario
https://github.com/owncloud/core/pull/38098 [tests-only] Only use user 'moss' when isTestingOnOcis
This should make the API test …
=> [tests-only] Bump core commit for tests 2020-11-09

accounts/pkg/command/server.go, accounts/pkg/service/v0/permissions.go, changelog/unreleased/fix-820.md
The go routines cause a race condition that sometimes causes the tests to fail. The ListRoles request would not return all permissions.
=> fix 820 - race condition

.drone.star
This brings phoenix UI test improvements from:
https://github.com/owncloud/phoenix/pull/4291 [tests-only] remove skipOnOCIS tag from moveFiles test
https://github.com/owncloud/phoenix/pull/4297 [tests-only] fix loginAsUser
https://github.com/owncloud/phoenix/pull/4285 [Tests-Only] update ocis commit id for running acceptance tests (note: this does not change any of the actual test code that will be used here)
=> [tests-only] Bump phoenix commit id used for UI tests

.drone.star, accounts/pkg/config/config.go, accounts/pkg/flagset/flagset.go, accounts/pkg/service/v0/accounts.go, accounts/pkg/service/v0/service.go, changelog/unreleased/change-hashing-algorithm.md
Even though SHA-512 is currently considered a secure algorithm it is not the best choice for password hashing. As this change introduces a breaking change it is beast to introduce it as early as possible to prevent us from having to implement a migration strategy
Closes: https://github.com/owncloud/product/issues/195
=> change hashing algorithm from SHA-512 to bcrypt

changelog/unreleased/ocis-root-config.md, glauth/pkg/command/server.go, konnectd/pkg/command/server.go, ocis-phoenix/pkg/command/server.go, ocis/pkg/command/glauth.go, ocis/pkg/command/konnectd.go, ocis/pkg/command/ocs.go, ocis/pkg/command/phoenix.go, ocis/pkg/command/proxy.go, ocis/pkg/command/settings.go, ocis/pkg/command/storageauthbasic.go, ocis/pkg/command/storageauthbearer.go, ocis/pkg/command/storagefrontend.go, ocis/pkg/command/storagegateway.go, ocis/pkg/command/storagehome.go, ocis/pkg/command/storagemetadata.go, ocis/pkg/command/storagepubliclink.go, ocis/pkg/command/storagesharing.go, ocis/pkg/command/storageuserprovider.go, ocis/pkg/command/storageusers.go, ocis/pkg/command/store.go, ocis/pkg/command/thumbnails.go, ocis/pkg/command/webdav.go, ocis/pkg/tracing/tracing.go, ocs/pkg/command/server.go, proxy/pkg/command/server.go, settings/pkg/command/server.go, store/pkg/command/server.go, thumbnails/pkg/command/server.go, webdav/pkg/command/server.go
service names were all showing up as `ocis` in jaeger before this PR
=> Fix tracing service names

.drone.star, ocis/tests/acceptance/config/behat.yml, ocis/tests/acceptance/features/apiBasic/addUser.feature, ocis/tests/acceptance/features/apiBasic/createShareToSharesFolder.feature, ocis/tests/acceptance/features/apiBasic/uploadFile.feature, ocis/tests/acceptance/features/apiBasic/webDavPUTAuthInvalid.feature
The acceptance tests currently use ACCOUNTS_HASH_DIFFICULTY of 4, the minimum value. This is good for getting the general tests to run fast. Not too much time is spent computing the hash of test user passwords. But we should also have a small number of tests that confirm that the default setting (currently 11) does actually work.
1) Make ACCOUNTS_HASH_DIFFICULTY optional/settable in .drone.star
2) Add a short local API test pipeline that sets accounts_hash_difficulty to "default". It runs a new local suite called `apiBasic`. I put some basic tests in there that confirm:
- user can be created
- share can be created and sharee can access it
- file can be uploaded
- some attempts to do things with an invalid password fail
That should confirm that with the higher "default" hash difficulty …
=> [tests-only] Add tests using the default ACCOUNTS_HASH_DIFFICULTY

.drone.star
A pipeline triggers on status success (https://docs.drone.io/pipeline/triggers/#by-status). But we want notifications be triggered on failure.
=> fix status trigger for missing notification on failing pipelines

accounts/pkg/config/config.go, accounts/pkg/flagset/flagset.go, accounts/pkg/server/http/server.go, changelog/unreleased/web-assets-caching.md, konnectd/pkg/server/http/server.go, ocis-phoenix/pkg/config/config.go, ocis-phoenix/pkg/flagset/flagset.go, ocis-phoenix/pkg/server/http/server.go, ocis-phoenix/pkg/service/v0/service.go, ocis-pkg/middleware/header.go, ocis-pkg/middleware/static.go, ocis-pkg/service/debug/service.go, ocs/pkg/server/http/server.go, settings/pkg/config/config.go, settings/pkg/flagset/flagset.go, settings/pkg/server/http/server.go, webdav/pkg/server/http/server.go
Introducing http caching headers for static web assets.
Also renamed the `Cache` middleware to `NoCache` because it was doing the opposite of what the name suggests.
=> Asset caching

deployments/examples/ocis_oc10_backend/ocis/config/web/config.json
Web config of bridge setup was pointing to ocis for the switch to `Classic Design` and `Settings`. Changed it to oc10.
This is not docs but deployment example config. However, it doesn't affect the code base, so running as "[docs-only]"...
=> [docs-only] Fix link urls to oc10 in web config

ocis/docker-compose-eos-test.yml
To better pin a version build from source or a build with an image from docker hub.
Also switch the alternatives: Before we defaulted to build from source, now we can use a prebuilt image from dockerhub to speed things up. 
As discussed with @micbar -- it should be possible to use environment variables there. 
Not sure where to merge it. Probably not for master at all. My view of the world is probably still way off.
=> introduce OCIS_EOS_TAG and BRANCH into docker-compose-eos-test.yml

changelog/unreleased/dont-nag-about-basicauth.md, proxy/pkg/middleware/basic_auth.go
warning on every request is spamming the logs. /cc @felixboehm
=> Show basic_auth warning only on startup

.drone.star, changelog/unreleased/update-phoenix-0.25.0.md, ocis-phoenix/Makefile
Update static web assets to 0.25.0
=> Update phoenix 0.25.0

accounts/pkg/command/add_account.go, changelog/unreleased/check-role-management-permissions.md, proxy/pkg/middleware/create_home.go, settings/pkg/service/v0/service.go, settings/pkg/service/v0/settings.go
Enhancement: add permission check when assigning and removing roles 
Everyone could add and remove roles from users.  
Added a new permission and a check so that only users with the role management permissions can assign and unassign roles.
Fixes https://github.com/owncloud/ocis/issues/879
=> add permission check to role management

.drone.star, ocis/vendor-bin/behat/composer.json
1) bump the core commit id for API tests - gets us:
https://github.com/owncloud/core/pull/38120 [Tests-Only] Update issue tags for test scenarios
https://github.com/owncloud/core/pull/38127 [tests-only] Fix tests WebDav.php BadResponseException
2) Adjust behat composer.json for API tests to be like oC10 core - does similar to core PRs:
https://github.com/owncloud/core/pull/38122 [tests-only] Bump test tool dependencies
https://github.com/owncloud/core/pull/38128 [tests-only] Use guzzle7 in acceptance tests
3) Bump core commit to include core PR https://github.com/owncloud/core/pull/38130
4) Use phpunit9 in acceptance tests like https://github.com/owncloud/core/pull/38130
5) bump the core commit id for API tests to include core PR https://github.com/owncloud/core/pull/38131
=> [tests-only] Bump core commit id for API tests

changelog/unreleased/enable-dynamic-client-registration.md, konnectd/pkg/flagset/flagset.go
=> Enable dynamic client registration

changelog/unreleased/ocis-version-command.md, ocis/go.mod, ocis/pkg/command/version.go
The version command was only implemented in the extensions.
This adds the version command to ocis to list all services in the ocis namespace.
=> add version command to ocis

changelog/unreleased/pkg-serve-index-html.md, ocis-pkg/middleware/static.go
It's already the default behaviour of `http.FileServer` to serve an `index.html`.
Fixes https://github.com/owncloud/ocis-pkg/issues/63
=> Serve index html

deployments/examples/ocis_oc10_backend/docker-compose.yml, proxy/changelog/unreleased/add-basic-auth-option.md, proxy/go.mod, proxy/pkg/config/config.go, proxy/pkg/flagset/flagset.go, proxy/pkg/middleware/signed_url_auth.go, proxy/pkg/middleware/signed_url_auth_test.go
When running the bridge with ownCloud10, we need an option to disable handling of signed urls in the proxy, because we want oc10 to take care of it then. This PR introduces a config option for that and makes use of it in the bridge deployment example.
Please note: deployment example uses the ocis image from dockerhub, so unless this PR is merged, the config option will not have any effect in the deployment example.
=> Add option to disable signing keys in the proxy

.drone.star
Fixes https://github.com/owncloud/ocis/issues/895
Enable nightly test runs in CI.
=> [CI] enable nightly test runs

.drone.star
Fix the cron build cases in drone.starlark.
=> [tests-only] [CI] fix the nightly builds pipelines

.drone.star
Even if the nightly tests were enabled the ci, the tests didn't ran last night. this was because there was a bug in starlark code for creating suite names
last night's build https://drone.owncloud.com/owncloud/ocis/1657
Working example of cron build  https://drone.owncloud.com/owncloud/ocis/1680
=> [CI] fix pipelines names in ci

changelog/unreleased/web-assets-caching.md, ocis-phoenix/pkg/service/v0/service.go, ocis-pkg/middleware/static.go
This is a bug fix. The `Last-Modified` header is meant for content validation when the expiration is reached or when revalidation is enforced. Without an expiration or forced revalidation it doesn't have any effect.
This PR sets the expiration date to now+ttl on service start and enforces revalidation on every request, based on the last modified date. I.e. the request will hit the server to check if the last-modified date of the resource changed. Which it only does, if the service is restarted in the meantime.
=> Set expires headers and force asset revalidation

.drone.star, changelog/unreleased/update-phoenix-0.26.0.md, changelog/unreleased/update-phoenix-0.27.0.md, changelog/unreleased/update-web-0.26.0.md, ocis-phoenix/Makefile
This updates phoenix to 0.27.0, which contains a bugfix regarding extension loading:
There was an error in the extension loading handlers which caused routes to be loaded multiple times when extensions from the config.json were unavailable. We hardened the extension loading handlers to just skip those extensions without side effects.
=> Update phoenix to 0.27.0

.drone.star
Get's latest core API test code, including https://github.com/owncloud/core/pull/38138
=> [tests-only] Bump commit id for API tests

accounts/go.mod, accounts/go.sum, changelog/unreleased/reva-update-2020-11-25.md, ocis-pkg/go.mod, ocis-pkg/go.sum, ocis/go.sum, ocs/go.mod, ocs/go.sum, proxy/go.mod, proxy/go.sum, storage/go.mod, storage/go.sum, tests/acceptance/features/apiOcisSpecific/apiShareWebdavOperations-propfind.feature
Update reva to `v1.4.1-0.20201125144025-57da0c27434c`
Mostly to bring fixes to pressing changes such as fd leaks and correct dav response code.
=> Update reva to v1.4.1-0.20201125144025-57da0c27434c

.drone.star
without volumes section in pipeline, the volumes are not reused between the steps. This leads to go dependency downloads in every step (see former pipelines).
=> [tests-only] fix gopath volume for ocis modules testing

.drone.star
In my view it is better to generate dependencies from the pipeline itselves, since this deduplicates code (the generation of the list of names is really similar to pipeline generation itself). It also ensures that generated dependencies and the actually generated pipelines are always the same. This might not the case with a separate generation like it is now.
=> [tests-only] optimize dependency generation

accounts/go.mod, accounts/go.sum, changelog/unreleased/update-reva-to-e6a621.md, ocis-pkg/go.mod, ocis-pkg/go.sum, ocis/go.sum, ocs/go.mod, ocs/go.sum, proxy/go.mod, proxy/go.sum, storage/go.mod, storage/go.sum
* Fix capabilities response for multiple client versions #1331 [cs3org/reva#1331](Fix capabilities response for multiple client versions #1331)
* Fix home storage redirect for remote.php/dav/files [cs3org/reva#1342](https://github.com/cs3org/reva/pull/1342)
=> Reva update v1.4.1-0.20201127111856-e6a6212c1b7b

.drone.star, tests/acceptance/expected-failures-on-OCIS-storage.txt, tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt
- Added failing TUS tests `apiWebdavUploadTUS/uploadToShare.feature:52` and `apiWebdavUploadTUS/uploadToShare.feature:53` to expected failure file
- Bump core commit id for API tests
=> [Tests-Only] Add failing Tus test to expected failure file

.drone.star
oCIS binary is build once and then provided for all tests (acceptance test, ui tests, but not for go linting, ...).
Diffs between master and branch look good for following tests:
- drone starlark
- drone starlark --build.event cron
- drone starlark --build.event pull
- drone starlark --build.event pull --build.message "[docs-only..]"
- drone starlark --build.message "[docs-only..]"
=> [tests-only] cache ocis build artifact for testing

.drone.star
to reduce the amount of "log noise" that drone CI needs to save.
=> [tests-only] Set OCIS_LOG_LEVEL to warn in CI

.drone.star
get tests from https://github.com/owncloud/core/pull/38164 into the ocis test run
=> [tests-only] bump core test commit id to get TUS chunking tests

docs/Makefile
Update of owncloud.github.io fails: https://drone.owncloud.com/owncloud/owncloud.github.io/161/1/3
This is because of rsyncing files (https://drone.owncloud.com/owncloud/ocis/1923/85/3) including .gitignore files and then automatically commiting them (https://drone.owncloud.com/owncloud/ocis/1923/85/6).
In this process the configuration.md for ocis gets lost.
=> [docs-only] fix failed docs deployment

.drone.star
#1003 did not fix the gitignore issue for owncloud.github.io documentation.
The files where gitignore files are filtered out by rsync were not used at all. This is changed by this PR.
=> [docs-only] fix gitignores in hugo docs

.drone.star
bump commit id of core API tests to get https://github.com/owncloud/core/pull/38185 & https://github.com/owncloud/core/pull/38179 & https://github.com/owncloud/core/pull/38180﻿
=> [tests-only] bump oc10 test commit id to get TUS  tests

ocis/docker-compose-eos-test.yml, ocis/docker-compose.yml, ocis/docker/eos-ocis-dev/Dockerfile, ocis/docker/eos-ocis/Dockerfile
- EOS Base image from `4.6.5` to `4.8.26`
=> update eos-base image

changelog/unreleased/proxy-allow-insecure-upstreams.md, proxy/pkg/config/config.go, proxy/pkg/flagset/flagset.go, proxy/pkg/proxy/proxy.go
At the moment we can disable certificate verification for the OIDC provider in the proxy. But you can not disable certificate verification for upstream servers defined in the proxy-config.json.
For some situations like testing, it is desirable to turn off certificate verification for upstream servers in the proxy.
=> make insecure upstream servers configurable

changelog/unreleased/storage-public-link-expiration.md, storage/pkg/command/frontend.go, tests/acceptance/features/apiOcisSpecific/apiCapabilities-capabilitiesWithNormalUser.feature
The public link expiration was enabled by default and didn't have a default expiration span by default, which resulted in already expired public links coming from the public link quick action. We fixed this by disabling the public link expiration by default.
Fixes https://github.com/owncloud/ocis/issues/987
=> Disable public link expiration by default

deployments/examples/ocis_keycloak/docker-compose.yml, deployments/examples/ocis_traefik/docker-compose.yml, deployments/examples/owncloud10_with_oc_web/docker-compose.yml
Traefik complains that `'example@example.com'` has invalid characters. The quotes must not be there.
=> [docs-only] remove singlequotes around email address

deployments/examples/ocis_keycloak/README.md, deployments/examples/ocis_keycloak/docker-compose.yml, deployments/examples/ocis_traefik/README.md, deployments/examples/ocis_traefik/docker-compose.yml, deployments/examples/owncloud10_with_oc_web/README.md, deployments/examples/owncloud10_with_oc_web/docker-compose.yml
This reverts all path settings to default. This seems more simple and less to break for the example deployments.
For example the current deployment examples do not start properly because of a missing folder structure. Also not everything was persisted, eg. because of missing `STORAGE_SHARING_USER_JSON_FILE`.
```
ocis_1     | 2020-12-09T22:27:40Z ERR error starting the grpc server error="unable to register services: rgrpc: grpc service usershareprovider could not be started,: error loading the file containing the shares: error opening/creating the file: /var/tmp/ocis/shares.json: open /var/tmp/ocis/shares.json: no such file or directory" service=storage
ocis_1     | process [storage-sharing] exited with code: 1
```
Path logic will be also tackled in #1048
=> use default paths

accounts/pkg/config/config.go, accounts/pkg/flagset/flagset.go, accounts/pkg/proto/v0/accounts.pb.micro_test.go, accounts/pkg/service/v0/accounts_permission_test.go, accounts/pkg/service/v0/groups.go, ocs/pkg/server/http/svc_test.go
As noticed in #1048 (https://github.com/owncloud/ocis/pull/1048#discussion_r540457917) AccountsDataPath is not used anymore except for logging.
=> get rid of unused AccountsDataPath

.drone.star
Binaries in https://download.owncloud.com/ocis/ocis/testing/ are outdated. Instead latest testing binaries are uploaded to https://download.owncloud.com/ocis/ocis/testing/ocis/dist/release/.
This should be because of the differing `strip_prefix` strings.
For master: `'strip_prefix': 'dist/release/'`
For releases: `'strip_prefix': 'ocis/dist/release/'`
This PR applies the same strip_prefix for both cases.
TODO after merge:
=> [docs-only] fix testing uploads

accounts/pkg/command/root.go, changelog/unreleased/runtime-cleanup.md, glauth/pkg/command/root.go, konnectd/pkg/command/root.go, ocis-phoenix/pkg/command/root.go, ocis/pkg/command/root.go, ocis/pkg/runtime/runtime.go, ocs/pkg/command/root.go, settings/pkg/command/root.go, storage/pkg/command/root.go, store/pkg/command/root.go, thumbnails/pkg/command/root.go, webdav/pkg/command/root.go
changes are in preparation for [refs/pman#6](https://github.com/refs/pman/pull/6)
=> Small runtime cleanup

changelog/unreleased/allow-ldap-user-backend.md, deployments/examples/cs3_users_ocis/.env, deployments/examples/cs3_users_ocis/README.md, deployments/examples/cs3_users_ocis/config/ldap/ldif/10_owncloud_schema.ldif, deployments/examples/cs3_users_ocis/config/ldap/ldif/20_users.ldif, deployments/examples/cs3_users_ocis/config/ldap/ldif/30_groups.ldif, deployments/examples/cs3_users_ocis/config/ocis/.gitignore, deployments/examples/cs3_users_ocis/config/ocis/identifier-registration.dist.yaml, deployments/examples/cs3_users_ocis/config/ocis/proxy-config.json, deployments/examples/cs3_users_ocis/docker-compose.yaml, proxy/pkg/command/server.go, proxy/pkg/config/config.go, proxy/pkg/flagset/flagset.go, proxy/pkg/middleware/_account_resolver_test.go, proxy/pkg/middleware/account_resolver.go, proxy/pkg/middleware/authentication.go, proxy/pkg/middleware/basic_auth.go, proxy/pkg/middleware/create_home.go, proxy/pkg/middleware/options.go, proxy/pkg/middleware/signed_url_auth.go, proxy/pkg/user/backend/accounts.go, proxy/pkg/user/backend/backend.go, proxy/pkg/user/backend/cs3.go
Hides user and auth related communication behind a facade (provider/user.go) to minimize logic-duplication across middlewares. Allows to switich the account backend from accounts to cs3.
```
PROXY_ACCOUNT_BACKEND_TYPE=cs3
PROXY_ACCOUNT_BACKEND_TYPE=accounts
````
```
mkdir -p  ~/ldapserver/bootscheama
```
Create file ~/ldapserver/bootschema/owncloud.lidif
```
#
#
dn: cn=owncloud,cn=schema,cn=config
objectClass: olcSchemaConfig
cn: owncloud
olcAttributeTypes: ( 1.3.6.1.4.1.39430.1.1.1 NAME 'ownCloudQuota' DESC 'User Quota (e.g. 2 GB)' EQUALITY caseExactMatch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 SINGLE-VALUE )
olcAttributeTypes: ( 1.3.6.1.4.1.39430.1.1.2 NAME 'ownCloudUUID' DESC 'A non-reassignable and persistent account ID)' EQUALITY uuidMatch SUBSTR …
```
=> Skip account-service by talking to CS3 user-api

deployments/examples/ocis_traefik/docker-compose.yml
Fixes a issue where deleted users get re-provisioned from claims. 
Closes #1072
=> Disable auto-provisioning

accounts/pkg/flagset/flagset.go, changelog/unreleased/make-all-paths-configurable.md, docs/extensions/storage/storages.md, docs/ocis/getting-started.md, konnectd/pkg/flagset/flagset.go, ocis-pkg/indexer/index/cs3/non_unique.go, ocis/docker-compose-eos-test.yml, settings/pkg/flagset/flagset.go, settings/ui/tests/run-acceptance-test.sh, storage/pkg/command/frontend.go, storage/pkg/command/sharing.go, storage/pkg/command/storagehome.go, storage/pkg/command/storagemetadata.go, storage/pkg/command/storageusers.go, storage/pkg/config/config.go, storage/pkg/flagset/driverlocal.go, storage/pkg/flagset/driverowncloud.go, storage/pkg/flagset/frontend.go, storage/pkg/flagset/sharing.go, storage/pkg/flagset/storagehome.go, storage/pkg/flagset/storagemetadata.go, storage/pkg/flagset/storageusers.go, store/pkg/flagset/flagset.go, store/pkg/service/v0/service.go
Aligned all services to use a subdir of `/var/tmp/ocis/` by default. Also made some missing temp paths configurable via env vars and config flags.
This does change default paths and also two env vars which were missing the STORAGE_ prefix. Nothing critical.
related: https://github.com/owncloud/ocis/pull/1048
=> Make all paths configurable and default to a subdir of the /var/tmp/ocis

.drone.star
Things changed:
- declare volumes once and use them like "named volumes"
- sanity check: issue warning if pipeline or step name exceeds 50 characters
- sanity check: issue warning if volume is declared in step but not in pipeline
- sanity check: issue warning if depends_on is referencing non existing pipeline
- helper: print count of all used docker images and versions
- add helper for depends_on mangement: "pipelineDependsOn" and "pipelinesDependsOn"
=> [tests-only] refactor drone definition

changelog/unreleased/web-assets-caching.md, glauth/go.sum, konnectd/go.sum, ocis-pkg/middleware/static.go, onlyoffice/go.sum, settings/go.sum, store/go.sum, thumbnails/go.sum, web/go.sum, web/pkg/service/v0/service.go, webdav/go.sum
Seems to be unstable at the moment. Needs investigation.
Please note that this PR has no changelog, but instead removes a changelog entry, because it disables caching again. We might want to bring the changelog entry back when we re-enable asset caching. I opened [this ticket](https://github.com/owncloud/ocis/issues/1094) to remind us that we want to re-enable asset caching.
=> Disable static assets caching

changelog/unreleased/settings-permissions.md, ocis-pkg/middleware/account.go, settings/go.sum, settings/pkg/proto/v0/settings.pb.micro_test.go, settings/pkg/service/v0/service.go, settings/pkg/service/v0/settings.go
This PR introduces permission checks for the write access http endpoints, so this already improves security.
There is another issue, that users can save values of other users. This is not tackled, yet. Could happen in a separate PR if we want to merge this one here quickly.
=> Introduce permission checks for WRITE access via http

.drone.star
While looking at other stuff, I noticed that there was some code-duplication of the `redis` and `selenium`  sevices in `.drone.star`. Refactor it.
=> [tests-only] Call redis() and selenium() functions in .drone.star

changelog/unreleased/runtime-update.md, ocis/go.mod, ocis/go.sum
- enhances the overall behavior of our runtime
- runtime `db` file configurable
- two new env variables to deal with the runtime
- `RUNTIME_DB_FILE` and `RUNTIME_KEEP_ALIVE`
- `RUNTIME_KEEP_ALIVE` defaults to `false` to provide backwards compatibility
- if `RUNTIME_KEEP_ALIVE` is set to `true`, if a supervised process terminates the runtime will attempt to start with the same environment provided.
=> Update OCIS Runtime

.drone.star
docs only pipelines fail since #973. Eg. https://drone.owncloud.com/owncloud/ocis/2303
[docs-only] is in the PR title to demonstrate that it works again.
=> [docs-only] [CI only] fix docs-only pipelines

.drone.star
Gets test code from web PRs:
https://github.com/owncloud/web/pull/4508 Fix random typos
https://github.com/owncloud/web/pull/4509 Fix: Delete file in trashbin UI test step not working
https://github.com/owncloud/web/pull/4512 Support an EXPECTED_FAILURES_FILE for web UI tests
Note: this does not actually add an expected-failures file for web UI tests here in `owncloud/ocis` - that will come in a later PR when there are test scenarios enabled in `owncloud/web` that fail here in `owncloud/ocis`
=> [tests-only] Bump webCommit for UI tests

docs/ocis/development/testing.md
1. LDAP and REDIS are not needed anymore (REDIS is only needed for owncloud-storage but default OCIS-storage does not need it)
2. general tests need to be executed from the oc10 repo, only the ocis specific (bug-demo) tests can be run from the ocis repo
=> [tests-only] fix test documentation

docs/extensions/konnectd/_index.md, docs/extensions/storage/storages.md, docs/ocis/development/testing.md
Change `OCIS` to `oCIS` in docs to make the naming consistent.
=> [docs-only] make OCIS name consistent throught the docs

ocis/pkg/flagset/flagset.go, proxy/pkg/flagset/flagset.go
ocis and proxy are the only extensions which have a default for tracing endpoints. There shouldn't be a default at all, because there is a comparison if OCIS_TRACING_COLLECTOR is empty:
https://github.com/owncloud/ocis/blob/a591d651198758ca1d958b40c55a7984cc99f521/proxy/pkg/command/server.go#L81-L89
Which calls this: https://github.com/census-ecosystem/opencensus-go-exporter-jaeger/blob/30c8b0fe8ad9d0eac5785893f3941b2e72c5aaaa/jaeger.go#L88-L98
For example if you want to use OCIS_TRACING_ENDPOINT at the moment you have to explicitly override OCIS_TRACING_COLLECTOR with an empty string. The  configuration looks like this:
```
export OCIS_TRACING_COLLECTOR=""
export OCIS_TRACING_ENABLED=true
export OCIS_TRACING_ENDPOINT=127.0.0.1:6831
```
After the merge this would look like this:
``` …
```
=> make tracing defaults consistent

thumbnails/pkg/thumbnail/storage/filesystem.go
When we try to load the thumbnail from the store for the first time we expect it to fail so we shouldn't log with level warn.
=> reduce warn logs

tests/acceptance/docker/Makefile, tests/acceptance/docker/src/acceptance.yml, tests/acceptance/docker/src/run-tests.sh
needs #1149 merged first. 
removes duplication https://github.com/owncloud/ocis/pull/1117#issuecomment-747571408
=> [Tests-only] use .drone.env for checking out tests in docker based acceptance tests

docs/ocis/getting-started.md
replaced the testing releases with the 1.0.0 in the curl lines
=> [docs-only] Update getting-started.md

docs/ocis/development/testing.md
PR #1149 changed the way that the core commit id and branch are specified.
Update the `testing.md` instructions.
=> [docs-only] Update docs about CORE_COMMITID and CORE_BRANCH

deployments/examples/cs3_users_ocis/.env, deployments/examples/cs3_users_ocis/monitoring_tracing/docker-compose-additions.yml, deployments/examples/ocis_keycloak/.env, deployments/examples/ocis_keycloak/monitoring_tracing/docker-compose-additions.yml, deployments/examples/ocis_traefik/.env, deployments/examples/ocis_traefik/docker-compose.yml, deployments/examples/ocis_traefik/monitoring_tracing/docker-compose-additions.yml, deployments/examples/owncloud10_with_oc_web/.env, docs/Makefile, docs/ocis/deployment/monitoring-tracing.md, docs/ocis/static/monitoring_tracing_overview.drawio.svg
Add documentation on how our monitoring and tracing story / infrastructure looks like. Add optional monitoring and tracing configuration for our deployment examples for a simple start.
External documentation in https://github.com/owncloud-devops/monitoring-tracing-server and https://github.com/owncloud-devops/monitoring-tracing-client is currently worked on.
Screenshot of the new page in docs:
=> [docs-only] add monitoring and tracing for ocis_traefik

sonar-project.properties
Updated the sonar excludes.
Things in `sonar.exclusions` don't need to be listed `sonar.coverage.exclusions` since it will take it from the former.
Added new non source folders like `deployments/` and `tests/`.
=> [Tests-Only] clean up sonar excludes

changelog/unreleased/generate-secure-state.md, konnectd/ui/src/utils.js
Replaced Math.random with a cryptographically secure way to generate the oidc state token using the javascript crypto api.
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random
=> generate cryptographically secure state token

changelog/unreleased/roles-cache.md, ocis-pkg/roles/cache.go, ocis-pkg/roles/cache_test.go, ocis-pkg/sync/cache_test.go
this pr updates existing roles cache to use newly added sync cache
* add tests for roles cache
* add changelog
* use strings in sync cache tests
=> update roles cache to use sync.cache

accounts/package.json, accounts/yarn.lock
The log output of `acccountsUITests` has this problem referencing `nightwatch-vrt`
https://drone.owncloud.com/owncloud/ocis/2765/73/7
```
yarn run v1.22.4
$ cucumber-js --retry 1 --require-module @babel/register --require-module @babel/polyfill --require ${TEST_INFRA_DIRECTORY}/acceptance/setup.js --require ui/tests/acceptance/stepDefinitions --require ${TEST_INFRA_DIRECTORY}/acceptance/stepDefinitions --format node_modules/cucumber-pretty -t "${TEST_TAGS:-not @skip and not @skipOnOC10}" /drone/src/accounts/ui/tests/acceptance/features
Feature: Accounts
Scenario: admin checks accounts list
✖ failed
Error: ENOENT: no such file or directory, scandir '/drone/src/accounts/node_modules/nightwatch-vrt/assertions'
at Object.readdirSync (fs.js:948:3)
at Function.readFolderRecursively …
```
=> [tests-only] Add nightwatch-vrt to accounts package.json

changelog/unreleased/expose-docker-image, ocis/docker/Dockerfile.linux.amd64, ocis/docker/Dockerfile.linux.arm, ocis/docker/Dockerfile.linux.arm64
This PR adds port exposure information to our released docker images. Expose see: https://docs.docker.com/engine/reference/builder/#expose
This adds information only. But for the user it is nice to see which ports of a docker container offer services.
=> add expose to docker images

changelog/unreleased/docker_image_volume.md, ocis/docker/Dockerfile.linux.amd64, ocis/docker/Dockerfile.linux.arm, ocis/docker/Dockerfile.linux.arm64
Adds a volume declaration to our docker images.
This makes it easier for the user to understand where data is stored.
=> add volume to docker image

docs/ocis/deployment/basic-remote-setup.md
A little clearification in the simple remote setup documentation.
=> [docs-only] Make cert handling in the docs more clear.

tests/acceptance/expected-failures-API-on-EOS-storage.md, tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md, tests/acceptance/expected-failures-webUI-on-OWNCLOUD-storage.md
"OCIS extension" repos were archived. So, the issues in these archived repos have been moved to ocis. This PR adjust the link to issues in expected-failure file.
- https://github.com/owncloud/ocis/issues/1215
- CI
=> [Tests-Only] Adjust the links in the expected-failures file

.github/dependabot.yml
Setup dependabot for Go.
Also added config for the npm dependencies in accounts, settings, konnectd, and onlyoffice since I don't know if this config file would disable npm scanning.
=> add GitHub native dependabot config

docs/ocis/getting-started.md
current version of docs are still using ocis 1.0.0 as an example for binary installation. This PR slightly updates the wording and changes the ocis installation example
we need clean docs 🚀
=> update docs to use latest ocis

changelog/unreleased/account-roles-fix.md, ocis-pkg/middleware/account.go
=> Check if roles are present in user object before looking those up

.drone.star, deployments/continuous-deployment-config/cs3_users_ocis/latest.yml, deployments/continuous-deployment-config/cs3_users_ocis/released.yml, deployments/continuous-deployment-config/ocis_keycloak/latest.yml, deployments/continuous-deployment-config/ocis_keycloak/released.yml, deployments/continuous-deployment-config/ocis_traefik/latest.yml, deployments/continuous-deployment-config/ocis_traefik/released.yml, deployments/examples/cs3_users_ocis/docker-compose.yml
Add continuous deployment of our deployment examples to CI.
- Fixes #1387
- Blocked by #1174 9that PR is merged now, so not blocked any more)
Having up to date test instances.
- in CI https://drone.owncloud.com/owncloud/ocis/3059/1/3
=> continuous deployment

.github/dependabot.yml
Updated the max PR limit so that dependabot doesn't DoS the CI server.
=> lower the open pull request limit for dependabot

docs/ocis/deployment/basic-remote-setup.md, docs/ocis/release_roadmap.md, ocis/Makefile
fixes #1397
Basic Remote Setup after PR is merged:
=> [docs-only] work on basic remote setup scenario

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
This PR bump core commit id for API tests  and also removes api-tests that are not failing on ocis anymore.
- https://github.com/owncloud/core/issues/38367
- Also see: https://github.com/owncloud/core/pull/38374
- CI
=> [Tests-Only] Bump core commit id for API tests 

changelog/unreleased/ocis_config_file_option.md, ocis/pkg/config/config.go, ocis/pkg/flagset/flagset.go
The oCIS root command offers a config file option `ocis --config-file` which does not do anything.
- Fixes #1618 confusion caused by the available option
As far as I know, there aren't any plans to support a single config file which can be load by the oCIS root command.
=> remove ocis config file option

deployments/examples/ocis_keycloak/config/ocis/entrypoint-override.sh, deployments/examples/ocis_traefik/config/ocis/entrypoint-override.sh
This PR removes demo users from accounts for the keycloak deployment example since they will be provided by Keycloak itself.
On the long run we should make demo users optional (default: not use them?). This would make this script obsolete.
- #1628 
Even after #1628 is applied, thumbnails will not be shown for demo users logging in with keycloak if the demo users are already present in accounts.
- running oCIS Keycloak example locally
=> [docs-only] keycloak example: remove demo users from accounts

deployments/continuous-deployment-config/cs3_users_ocis/latest.yml, deployments/continuous-deployment-config/cs3_users_ocis/released.yml, deployments/continuous-deployment-config/ocis_keycloak/latest.yml, deployments/continuous-deployment-config/ocis_keycloak/released.yml, deployments/continuous-deployment-config/ocis_traefik/latest.yml, deployments/continuous-deployment-config/ocis_traefik/released.yml
Continuously deployed servers are pruned every night. This also includes LetsEncrypt certificates. This means we are requesting new certificates every night and therefore run in certificate issuing limits.
This PR carries the certificates from the pruned to the new instances to circumvent this.
Implemented in https://github.com/owncloud-devops/continuous-deployment/pull/8
=> [docs-only] fix certificate issuing limit for continuously deployed examples

docs/ocis/release_notes.md
Prominently add breaking changes to oCIS 1.2.0 changelog and show migrations
- #1654 
- fixes #1569 
Users should be able to migrate from pre 1.2.0 to 1.2.0
=> [docs-only] add breaking changes and migration

deployments/examples/ocis_keycloak/docker-compose.yml
Sharing does currently not work when using the oCIS with Keycloak deployment example.
Sharing is not possible due the current value of `STORAGE_LDAP_IDP`. This must be set to the full Keycloak realm to be used with oCIS.
- With https://ocis.ocis-keycloak.latest.owncloud.works/
- Login as einstein, then logout (einstein account will be created by this)
- Login as marie
- Create a folder as marie and share it to einstein
-  Login as einstein and go to "Shared with me"
- You will see nothing before this PR is merged, after that you will see the share.
=> [docs-only] fix sharing in Keycloak deployment example

accounts/pkg/command/version.go, changelog/unreleased/use-registry-interface.md, idp/pkg/command/version.go, ocis-pkg/registry/registry.go, ocis-pkg/service/grpc/service.go, ocis-pkg/service/http/service.go, ocis/pkg/command/root.go, ocis/pkg/command/version.go, ocs/pkg/command/version.go, proxy/pkg/command/version.go, settings/pkg/command/version.go, storage/pkg/service/external/external.go, store/pkg/command/version.go, thumbnails/pkg/command/version.go, webdav/pkg/command/version.go
We added initial support to use nats and kubernetes as a service registry using `MICRO_REGISTRY=nats` and `MICRO_REGISTRY=kubernetes` respectively.
Multiple nodes can be given with `MICRO_REGISTRY_ADDRESS=1.2.3.4,5.6.7.8,9.10.11.12`.
=> Use registry interface value

changelog/unreleased/fix-tokencache-ttl.md, proxy/pkg/middleware/authentication.go
The TTL was supplied to the middleware as a duration and then in that middleware multiplied by `time.Second` again. Durations should not be multiplied because they result in unintended values.
```go
time.Second * 1 = 1s
time.Second * time.Second = 277777h46m40s
```
=> fix token cache TTL

glauth/pkg/server/glauth/ocis.go, graph/pkg/service/v0/groups.go, graph/pkg/service/v0/users.go, ocis-pkg/conversions/strings.go, ocis-pkg/conversions/strings_test.go, ocis-pkg/indexer/index/disk/non_unique.go, thumbnails/pkg/thumbnail/resolutions.go
Pre allocating slices with a target size reduces the number of allocations because we already know how big the slice will be and therefore need to allocate only once
=> pre allocate slices

accounts/go.mod, accounts/go.sum, changelog/unreleased/update-reva-to-53f39499762e.md, graph/go.mod, graph/go.sum, ocis-pkg/go.mod, ocis-pkg/go.sum, ocis/go.mod, ocs/go.mod, ocs/go.sum, proxy/go.mod, proxy/go.sum, storage/go.mod, storage/go.sum, tests/acceptance/expected-failures-API-on-OCIS-storage.md
Update reva. This includes:
* quota querying and tree accounting [cs3org/reva#1405](https://github.com/cs3org/reva/pull/1405)
=> update reva to v1.6.1-0.20210218130854-a954e7242e7a

Makefile, docs/Makefile
Adds a make target to run hugo server without dependencies on docker (native installed hugo) and skips protobuf generation.
This need arose for our non-developer documentation writer.
=> [docs-only] Native hugo serve

docs/ocis/development/testing.md
Expected - failure files were changed to `.md` from `.txt` but the documentation still mentioned expected-failure files to be `.txt` , this PR fixes that.
- https://github.com/owncloud/ocis/issues/1634
- locally
=> [docs-only] Expected-failures files changed to .md from .txt in documentation

changelog/unreleased/add-missing-gatewaysvc-config.md, storage/pkg/command/authbasic.go, storage/pkg/command/authbearer.go, storage/pkg/flagset/authbasic.go, storage/pkg/flagset/authbearer.go
The auth provider `ldap` and `oidc` drivers now need to be able talk to the reva gateway. We added the `gatewayscv` to the config that is passed to reva.
=> add missing gatewaysvc config

changelog/unreleased/accounts-init-regression.md, ocis/pkg/runtime/runtime.go
As it turns out the race condition between `accounts <-> storage-metadata` still remains. This PR is a hotfix and it should be followed up with a proper fix. Either:
- block the accounts initialization until the storage metadata is ready (using the registry) or
- allow the accounts service to initialize and use a message broker to signal the accounts the metadata storage is ready to receive requests.
=> Delay accounts service startup

changelog/unreleased/remove-log-secret.md, ocis-pkg/middleware/openidconnect.go, proxy/pkg/middleware/oidc_auth.go
secrets should not be exposed in the logs
=> remove JWT from logs

changelog/unreleased/update-web-2.0.2.md, docs/extensions/web/releasing.md, web/Makefile
Updates `web` to 2.0.2 and also updates the web release documentation (which was still referring to the old `phoenix` structure)
- Belongs to #1775
=> Update web version to 2.0.2

changelog/unreleased/fix-jpeg-thumbnails.md, tests/acceptance/expected-failures-webUI-on-OWNCLOUD-storage.md, webdav/pkg/dav/thumbnails/thumbnail.go, webdav/pkg/service/v0/service.go
Quick fix to support `.jpeg` files again. Ideally this should also be changed when rewriting the thumbnails API.
=> fix jpeg thumbnails

changelog/unreleased/thumbnails-support-gifs.md, tests/acceptance/expected-failures-webUI-on-OWNCLOUD-storage.md, thumbnails/pkg/thumbnail/imgsource/webdav.go, webdav/pkg/service/v0/service.go
Added support for gifs to the thumbnails service.
=> add support for gifs to the thumbnails service

Makefile, accounts/Makefile, glauth/Makefile, graph-explorer/Makefile, graph/Makefile, idp/Makefile, ocis-pkg/Makefile, ocis/Makefile, ocs/Makefile, onlyoffice/Makefile, proxy/Makefile, settings/Makefile, storage/Makefile, store/Makefile, thumbnails/Makefile, web/Makefile, webdav/Makefile
CI produces a lot of `bash: go: command not found` warnings in the `make ci-node-generate` steps since merge of PR #1714.
This is because these pipeline steps don't have Go installed but the `.bingo/Variables.mk` which is included in every Makefile tests for the existence of Go. This included dependency is only needed if Go tooling is used and therefore Go must be available.
The warnings will be suppressed by conditionally including the Bingo Makefile if Go is present.
- See CI run
=> [CI-only] suppress `bash: go: command not found` warnings

graph-explorer/pkg/flagset/flagset.go, graph/pkg/flagset/flagset.go, ocis-pkg/config/config.go, ocis/pkg/command/root.go, ocis/pkg/flagset/flagset.go
- add `config-file` flag & `OCIS_CONFIG_FILE` env variable to the ocis single binary.
- propagate log config to graph and graph-explorer.
=> Cleanup from Runtime

changelog/unreleased/runtime-address-configurable.md, ocis-pkg/config/config.go, ocis/pkg/command/kill.go, ocis/pkg/command/list.go, ocis/pkg/command/run.go, ocis/pkg/flagset/flagset.go, ocis/pkg/runtime/service/service.go
Without any configuration the ocis runtime will start on `localhost:6060` unless specified otherwise. Usage:
- `OCIS_RUNTIME_PORT=6061 bin/ocis server`
- overrides the oCIS runtime and starts on port 6061
- `OCIS_RUNTIME_PORT=6061 bin/ocis list`
- lists running extensions for the runtime on `localhost:6061`
All subcommands are updated and expected to work with the following environment variables:
```
OCIS_RUNTIME_HOST
OCIS_RUNTIME_PORT
```
=> Runtime port and host configurable

docs/ocis/getting-started.md
Adds a short warning about firewall. An activated firewall that does not allow mDNS breaks oCIS.
=> [docs-only] Add warning about firewall configuration.

.adr-dir, docs/ocis/adr/0001-introduce-accounts-service.md, docs/ocis/adr/0002-persist-accounts-using-cs3-storage.md, docs/ocis/adr/0003-external-user-management.md, docs/ocis/adr/_index.md
I moved the adrs to a collapsed subsection of the ocis docs, added the hugo header and commited the `.adr-dir`. The adr tools don't work out of the box. Use https://github.com/butonic/adr-tools to manage them. Maybe we should add them to the tools dir?
=> [docs-only] Refine adrs

.make/go.mk, changelog/unreleased/build-all-targets.md
Make build target `build` used to build a binary twice, the second occurrence having symbols for debugging. We split this step in two and added `build-all` and `build-debug` targets.
- `build-all` now behaves as the previous `build` target, it will generate 2 binaries, one for debug.
- `build-debug` will build a single binary for debugging.
=> Update Build Targets

docs/ocis/deployment/basic-remote-setup.md, docs/ocis/development/extensions.md
Fixed a typo and updated the `config.json` docs for extension development to reference correct ports.
- Docs only
=> [docs-only] Fix typo and update http->https, port numbers

deployments/examples/ocis_keycloak/config/keycloak/ocis-realm.dist.json
Keycloak has a restriction for Dynamic Client Registration in default settings. In order to effectively use it we need to disable the `Trusted Host` restriction.
Without this restriction dynamic client registration works for the iOS and Android apps.
- test case 1:
- test case 2:
- ...
=> [deployment examples]  Keycloak: allow dynamic client registration from any host

changelog/unreleased/fix-unaligned-atomic-operation-on-arm32.md, ocis-pkg/sync/cache.go
This fixes an "unaligned 64-bit atomic operation" panic on 32-bit ARM, (in my case a Raspberry Pi 4, running 32-bit Raspbian).
The panic happens (at least) during the first login after a service (re)start.
This issue has been spotted in other Golang projects too. (e.g. https://github.com/census-instrumentation/opencensus-go/commit/01b39586f932bbb0b4e1cb6499e454c470e9138b)
The Golang project documents this at https://golang.org/pkg/sync/atomic/#pkg-note-BUG mentioning it is the "caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically" and "The first word in (...) an allocated struct (...) can be relied upon to be 64-bit aligned"
- Fixes issue #1887 
It fixes a crash on 32-bit ARM (and likely other 32-bit systems).
- Repeated the following multiple times …
=> move uint64s to beginning of struct to ensure they are 64-bit aligned

changelog/unreleased/change-default-path-for-thumbnails.md, thumbnails/pkg/flagset/flagset.go, thumbnails/pkg/thumbnail/storage/filesystem.go
Changes the default path for thumbnails from `<os tmp dir>/ocis-thumbnails` to `/var/tmp/ocis/thumbnails`
- Fixes #1891 
As requested in #1891 
- test case 1:
- test case 2:
- ...
=> change default path for thumbnails

storage/pkg/command/drivers.go, storage/pkg/config/config.go, storage/pkg/flagset/driverocis.go
Currently the system user UUID for oCIS storage is hardcoded in the driver configuration:
https://github.com/owncloud/ocis/blob/dea1fa87a97bcabe1aacf89028441b583898399d/storage/pkg/command/drivers.go#L94
On the accounts side it is configurable:
https://github.com/owncloud/ocis/blob/dea1fa87a97bcabe1aacf89028441b583898399d/accounts/pkg/flagset/flagset.go#L178-L184
It should be configurable on both sides.
=> make reva ocis storage driver uuid configurable

.drone.star
replaces `thegeeklab/wait-for:latest` with `owncloudci/wait-for:latest`
Was not really needed but we needed to maintain our own wait-for for https://github.com/owncloud-docker/ubuntu/pull/56, so we also can use it for our CI purposes.
=> switch to owncloudci/wait-for

accounts/go.sum, glauth/go.sum, ocis/go.mod, ocis/go.sum, ocis/pkg/config/config.go, proxy/pkg/proxy/proxy.go
oCIS shouldn't know anything explicitly about an extension. It should provide interfaces which any extension can use. Therefore ocis-hello shouldn't be treated differently and all references to it will be removed in this PR
- Related to https://github.com/owncloud/ocis-hello/pull/104
See what is needed to get an arbitrary extension running with oCIS
=> remove ocis-hello references

docs/ocis/migration.md
Fixes some typos and wording in `docs/ocis/migration.md`
=> [docs-only] fix migration docs

changelog/unreleased/config-parsing-run-subcommand.md, ocis-pkg/config/config.go, ocis/pkg/runtime/service/service.go
What the descriptions says. Currenntly it is not possible to parse a single config file from an extension when running on supervised mode.
a) global ocis config file on /etc/ocis/ocis.yaml with the contents:
```yaml
proxy:
http:
addr: "0.0.0.0:6200"
accounts:
http:
addr: "0.0.0.0:8888"
Storage:
Reva:
StorageMetadata:
Port:
HTTPAddr: "0.0.0.0:7777"
```
b) a proxy config file /etc/ocis/proxy.json with the contents:
```json
{
"http": {
"addr": "0.0.0.0:5200"
},
"debug": {
"addr": "0.0.0.0:5201"
}
}
```
Running everything:
1) run ocis server // What will happen? /etc/ocis/ocis.yaml will get parsed and all extensions will inherit their config from it
2) run ocis kill proxy // What will happen? supervised proxy will die
3) run ocis run proxy // What will happen? /etc/ocis/proxy.json gets parsed …
=> Allow config parsing on supervise mode only with `run` subcommand

.drone.env
With this PR:
- core commit ID as testrunner is updated to the latest up to the date of PR creation.
- part of https://github.com/owncloud/QA/issues/662
=> [Tests-Only] Updated core commit id to the latest up to 2020/04/21

changelog/unreleased/fix-storage-metadata-default.md, storage/pkg/command/storagemetadata.go, storage/pkg/flagset/storagemetadata.go
=> Change the order where we ser STORAGE_METADATA_ROOT

changelog/unreleased/stop-supervisor-if-failure.md, ocis/pkg/runtime/service/service.go
closes https://github.com/owncloud/ocis/issues/1616
Steps to make the supervisor fail:
`PROXY_HTTP_ADDR=0.0.0.0:9144 bin/ocis server`
=> Stop supervisor if a service fails to start

tests/acceptance/expected-failures-API-on-OCIS-storage.md
This reverts commit 26ee19d6fee65f3ddc88484220184c0c29ae27dd.
Somehow that commit https://github.com/owncloud/ocis/commit/26ee19d6fee65f3ddc88484220184c0c29ae27dd got onto master branch without the normal PR and CI process. It needs to be revert to make CI green again.
- Fixes https://github.com/owncloud/core/issues/38657
CI
=> [tests-only] Revert "adjust expected failures for ocis"

.drone.star, changelog/unreleased/ocs-user-deprovisioning.md, ocs/go.mod, ocs/pkg/config/config.go, ocs/pkg/flagset/flagset.go, ocs/pkg/service/v0/users.go, tests/acceptance/expected-failures-API-on-OCIS-storage.md
Use the CS3 API and Reva to deprovision users completely.
Two new environment variables introduced:
```
OCS_IDM_ADDRESS
OCS_STORAGE_USERS_DRIVER
```
`OCS_IDM_ADDRESS` is also an alias for `OCIS_URL`; allows the OCS service to mint jwt tokens for the authenticated user that will be read by the reva authentication middleware.
`OCS_STORAGE_USERS_DRIVER` determines how a user is deprovisioned. This kind of behavior is needed since every storage driver deals with deleting differently.
This is being tested with:
```console
make test-acceptance-api \
TEST_SERVER_URL=https://localhost:9200 \
TEST_OCIS=true \
SKELETON_DIR=/Users/aunger/code/owncloud/core/apps/testing/data/apiSkeleton \
BEHAT_FEATURE=tests/acceptance/features/apiBugDemonstration/apiWebdavPreviews-previews.feature \ …
```
=> Rework of PR#755

docs/extensions/accounts/releasing.md, docs/extensions/settings/releasing.md, docs/extensions/web/releasing.md, settings/package.json
Within the `v1.5.0` release of oCIS, I had to work on the `accounts` and `settings` extensions and almost forgot adding their respective `embed.go` files to Git. After searching for a while and requesting help from @fschade I managed to do so, but documenting this in written form will help both outside contributors as well as team members in the future.
=> [docs-only] Add release guides for accounts & settings, fix issue link in settings/package.json

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
This includes recent core acceptance test code related to "delete file" steps from PRs:
https://github.com/owncloud/core/pull/38658
https://github.com/owncloud/core/pull/38660
CI
=> [tests-only] Bump core commit id for tests

.github/settings.yml
Translation sync is not allowed to push to oCIS master branch:
```
latest: Pulling from plugins/git-action
--
2 | Digest: sha256:491ee1e85144d8a47dfd1eece5484dcb847f7ceb2a98f8daaadb8485778aa2d7
3 | Status: Image is up to date for plugins/git-action:latest
4 | + git push origin master:master
5 | Warning: Permanently added 'github.com,140.82.121.4' (RSA) to the list of known hosts.
6 | remote: error: GH006: Protected branch update failed for refs/heads/master.
7 | remote: error: Required status check "continuous-integration/drone/pr" is expected. At least 1 approving review is required by reviewers with write access.
8 | To github.com:owncloud/ocis.git
9 | ! [remote rejected]   master -> master (protected branch hook declined)
10 | error: failed to push some refs to …
```
=> fix enforce_admins

docs/ocis/development/testing.md
Remove `DELETE_USER_DATA_CMD` env used in API tests running scripts from testing docs.
- Fixes https://github.com/owncloud/ocis/issues/2008
=> [Tests-Only] remove DELETE_USER_DATA_CMD env from api tests running scripts

changelog/unreleased/web-samesite.md, web/pkg/service/v0/service.go
- Fixes #2012 
Changed SameSite settings to Strict for Web to prevent warnings in Firefox
- locally in Firefox
=> change samesite settings for web

docs/ocis/getting-started/_index.md
Reference ocis.owncloud.com as our demo instance in the developer docs. Also provide some path to the continuously deployed examples.
=> [docs-only] reference demo instance in docs

changelog/unreleased/enhancement-user-profile-picture-capability, storage/pkg/command/frontend.go
~Needs a PR in `reva` merged and then the `reva` version to be updated, will finalize this PR once that's done~
Adds the newly introduced capability in the latest `reva` version to oCIS' capabilities
- Fixes #2031
=> Add profile_picture to user capabilities

deployments/examples/cs3_users_ocis/docker-compose.yml, deployments/examples/ocis_keycloak/docker-compose.yml, deployments/examples/ocis_traefik/docker-compose.yml, deployments/examples/ocis_wopi/docker-compose.yml
For the deployment examples we switched to HTTPS internally in https://github.com/owncloud/ocis/commit/3eb9e122a4b90ddd1d82bdacbe34a3f8f86c0926#diff-82183c58020714d66867eb24da3765200d315ec2508b7816916567ce534142c7 because there was some configuration dependency whether oCIS runs with https or http and we wanted to stick as close to the default configuration as possible:
```
THUMBNAILS_WEBDAVSOURCE_BASEURL: http://localhost:9200/remote.php/webdav/
```
The need to set THUMBNAILS_WEBDAVSOURCE_BASEURL was removed in #1898 so we can use http internally again.
Using http between oCIS has the advantage that we don't have to set `insecureSkipVerify` on Traefik.
=> deployment examples: switch to http internally

docs/ocis/deployment/continuous_deployment.md
ocis.ocis-web.latest.owncloud.works was added to deployment examples in https://github.com/owncloud/web/pull/5145
=> [docs-only] add reference to ocis.ocis-web.latest.owncloud.works

tests/acceptance/docker/Makefile, tests/acceptance/docker/src/acceptance.yml, tests/acceptance/docker/src/ocis-base.yml, tests/acceptance/docker/src/run-tests.sh
Fix acceptance test setup which can be run by devs locally in docker
CI and oCIS has changed a lot and the docker based acceptence test setup for devs has not gotten much love.  
- run tests `make -C tests/acceptance/docker <xxx> OCIS_IMAGE_TAG=1.6.0` where <xxx> is:
- respectively check that `make -C tests/acceptance/docker show-test-logs` reports no unexpected failures / passes
=> [tests-only] first fixes

.drone.star
- Fixes https://github.com/owncloud/ocis/issues/2097
- :robot:
=> [Tests-Only] Removed web suite lists

accounts/pkg/service/v0/index.go, changelog/unreleased/fix-groups-index.md
When multiple groups are created like:
`group1` `Group1` and `GROUP1` they are separate groups for the accounts service but the index saw them as the same group.
First noticed it in the reva update PR: https://github.com/owncloud/ocis/pull/2104
The tests were failing because of this 'bug'.
=> fix: make groups index case sensitive

.drone.star
Webhippie redis img is outdated by >1year (similar case in [web](https://github.com/owncloud/web/commit/c5257f291c3bb8c7a2bfb1b770407ede6c5b3f3b) recently), nodejs was inconsistent between `14` and `latest` and is now unified
=> [tests-only] Replace webhippie nodejs & redis imgs in CI

changelog/unreleased/fix-use-configured-registry, storage/pkg/service/external/external.go
The go-micro registry-singleton ignores the ocis config and defaults to mdns
- Fixes #2119
The storage was always advertised via mdns, ignoring the registry configuration
=> Use ocis registry for refresh

docs/ocis/development/getting-started.md, graph-explorer/go.mod, graph/go.mod
docs state that a developer needs at least Go 1.15 but actually it is 1.16. Graph and Graph Explorer should also use Go 1.16 for consistency reasons, since all other extensions are using this version too.
=> unifiy go version

tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
This PR adjusts the issues in the expected failures file by replacing the closed issues with correct open issues.
- https://github.com/owncloud/ocis/issues/2078
The expected-to-fail scenarios in expected failures files are tagged with related issues. However, some of the issues are already closed but the tests still fail. So, the correct issues are to be added according to current the reason of failure.
- CI
=> [Tests-Only]Replace closed issues with correct issues in expected failures file

changelog/unreleased/status_php_authentication.md, proxy/pkg/middleware/oidc_auth.go
`/status.php` is expected not to be authentication protected. This is currently true if you don't sent the `authorization` header. If you send an invalid or expired authorization header you will get an 401 unauthorized - so it is not really an unauthenticated endpoint. This PR adds the `/status.php` to the dirty ignore list which is already there because of `/konnect/v1/userinfo`.
- Fixes https://github.com/owncloud/client/issues/8538
=> ignore authentication header on status.php

tests/acceptance/expected-failures-API-on-OCIS-storage.md
While adjusting the issues in expected failures files, some tests were added twice while working together. So this Pr removes such tests.
- https://github.com/owncloud/ocis/issues/2078
- CI
- [d] Tests only (no source changes)
=> [Tests-Only]Remove tests that have been added twice

.drone.env, tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Bumped commit IDs of `core` to get the latest core API test scenarios
part of https://github.com/owncloud/QA/issues/662
=> [full-ci] [tests-only] Bump core and web commit id

accounts/go.mod, accounts/go.sum, changelog/unreleased/update-reva-v1.8.1-0.20210622125952-b54b15943d02.md, changelog/unreleased/update-reva-v1.9.md, glauth/go.sum, graph-explorer/go.sum, graph/go.mod, graph/go.sum, idp/go.sum, ocis-pkg/go.mod, ocis-pkg/go.sum, ocis/go.sum, ocs/go.mod, ocs/go.sum, onlyoffice/go.sum, proxy/go.mod, proxy/go.sum, settings/go.sum, storage/go.mod, storage/go.sum, store/go.sum, tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md, thumbnails/go.mod, thumbnails/go.sum, web/go.sum, webdav/go.sum
This update includes
* [set Content-Type correctly](https://github.com/cs3org/reva/pull/1750)
* [Return file checksum available from the metadata for the EOS driver](https://github.com/cs3org/reva/pull/1755)
* [Sort share entries alphabetically](https://github.com/cs3org/reva/pull/1772)
* [Initial work on the owncloudsql driver](https://github.com/cs3org/reva/pull/1710)
* [Add user ID cache warmup to EOS storage driver](https://github.com/cs3org/reva/pull/1774)
* [Use UidNumber and GidNumber fields in User objects](https://github.com/cs3org/reva/pull/1573)
* [EOS GRPC interface](https://github.com/cs3org/reva/pull/1471)
* [switch references](https://github.com/cs3org/reva/pull/1721)
* [remove user's uuid from trashbin file key](https://github.com/cs3org/reva/pull/1793)
* [fix restore …
=> [full-ci] update reva to v1.9

.drone.star, deployments/continuous-deployment-config/ocis_hello/latest.yml, deployments/continuous-deployment-config/ocis_s3/latest.yml, deployments/examples/ocis_hello/.env, deployments/examples/ocis_hello/README.md, deployments/examples/ocis_hello/config/ocis/config.dist.json, deployments/examples/ocis_hello/config/ocis/entrypoint-override.sh, deployments/examples/ocis_hello/config/ocis/proxy-config.json, deployments/examples/ocis_hello/docker-compose.yml, deployments/examples/ocis_hello/monitoring_tracing/docker-compose-additions.yml, deployments/examples/ocis_s3/.env, deployments/examples/ocis_s3/README.md, deployments/examples/ocis_s3/config/ocis/entrypoint-override.sh, deployments/examples/ocis_s3/docker-compose.yml, deployments/examples/ocis_s3/monitoring_tracing/docker-compose-additions.yml, docs/ocis/deployment/continuous_deployment.md, docs/ocis/deployment/ocis_hello.md, docs/ocis/deployment/ocis_s3.md, docs/ocis/deployment/ocis_wopi.md
add two new deployment examples and add them to the continuous deploymen:
- oCIS with S3 as user storage driver
- oCIS with Hello extension
We want to showcase the S3 and Extension usecase.
- https://drone.owncloud.com/owncloud/ocis/5594
=> add hello and s3 deplyoment example

tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
This PR adjusts the tests in the exepected failures file which were linked with some closed issues.
- Fixes https://github.com/owncloud/ocis/issues/2078
- CI
=> [Tests-Only] Adjust expected failures for remaining closed issues

.drone.star
This PR enables fail-early system for tests running in CI.
When ever a test suite fails, it stops the particular build so that the resources are not wasted.
The drone.star is adjusted such that for the suites where earlyFail feature is set to True, any test failure in that suite stops the build. If we do not want the failing tests in a suite to stop the build, we can adjust `earlyFail: False` for the particular test suite.
Whenever a test suite fails, a github comment is generated which helps us identify which test failure actually stopped the build.
- https://github.com/owncloud/QA/issues/672
- CI
=> [Tests-Only]Add earlyFail

changelog/unreleased/closed-channel-bug.md, ocis-pkg/sync/trap.go, storage/pkg/command/authbasic.go, storage/pkg/command/authbearer.go, storage/pkg/command/gateway.go, storage/pkg/command/groups.go, storage/pkg/command/sharing.go, storage/pkg/command/storagehome.go, storage/pkg/command/storagepubliclink.go, storage/pkg/command/storageusers.go, storage/pkg/command/users.go
When attempting to run a service through the runtime that is currently running and fails to start, a race condition still redirect os Interrupt signals to a closed channel.
1. `ocis server`
2. `ocis run proxy`
3. `ctrl+c` on step 1
You should see a panic message on screen:
Not cool.
=> Prevent race condition on starting an already running service

changelog/unreleased/spare-port-80.md, storage/pkg/command/groups.go
=> Use correct debug address

docs/ocis/development/testing.md
update testing docs to include STORAGE_DRIVER env var
- Fixes https://github.com/owncloud/ocis/issues/2259
- 
👀
=> [docs-only] update testing docs to include STORAGE_DRIVER env var

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
This will include the test code changes in core PR https://github.com/owncloud/core/pull/39001 and that makes some of the chunking tests pass now - much better.
Similar PR to cs3org/reva is https://github.com/cs3org/reva/pull/1893
Note: I raised issue #2305 to investigate the "odd" old chunking test that now passes on "owncloud" storage but fails on "OCIS" storage.
CI
=> [tests-only] [full-ci] Bump commit id for tests

docs/ocis/development/getting-started.md
Actually, I don't know if this still holds true. AFAICT we will be releasing an ocis binary that bundles all extensions. So ... will they really be released individually? For bug fix releases a release process for them would be quicker, but then we would also need to build individual docker containers ...
@micbar @dragotin @wkloucek what do you think? Maybe an ADR is in order?
=> [docs-only] Clarify why we keep separate go.mod files

ocis-pkg/middleware/openidconnect.go, ocis-pkg/oidc/claims.go, ocis-pkg/oidc/context.go, proxy/pkg/command/server.go, proxy/pkg/config/config.go, proxy/pkg/flagset/flagset.go, proxy/pkg/middleware/account_resolver.go, proxy/pkg/middleware/account_resolver_test.go, proxy/pkg/middleware/basic_auth.go, proxy/pkg/middleware/oidc_auth.go, proxy/pkg/middleware/options.go, proxy/pkg/proxy/policy/selector.go, proxy/pkg/proxy/policy/selector_test.go, proxy/pkg/user/backend/accounts.go, proxy/pkg/user/backend/accounts_test.go, proxy/pkg/user/backend/backend.go, proxy/pkg/user/backend/cs3.go, proxy/pkg/user/backend/test/backend_mock.go
To be able to use custom OIDC claims when authenticating users we introduced two new parameters: `PROXY_USER_OIDC_CLAIM=email` and `PROXY_USER_CS3_CLAIM=mail`. The default will use the OIDC `email` claim to look up a user in the CS3 API with a `mail` claim. More robust mappings are recommended, eg. an `ownclouduuid` OIDC claim and an `userid` CS3 lookup.
=> use claims map instead of struct

changelog/unreleased/claims-policy-selector.md, ocis-pkg/oidc/claims.go, proxy/config/proxy-example-migration.json, proxy/config/proxy-example-regex.json, proxy/pkg/command/server.go, proxy/pkg/config/config.go, proxy/pkg/flagset/flagset.go, proxy/pkg/middleware/account_resolver.go, proxy/pkg/middleware/options.go, proxy/pkg/middleware/selector_cookie.go, proxy/pkg/proxy/policy/selector.go, proxy/pkg/proxy/policy/selector_test.go, proxy/pkg/proxy/proxy.go
Using the proxy config file, it is now possible to let let the IdP determine the routing policy by sending an `ocis.routing.policy` claim or by matching username, email or id using regexes. 
This PR can stand on its own. But the proxy and the docs need an overhaul in subsequent PRs:
=> add claims and regex policy selector

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
A number of test scenarios that use new chunking have been skipped, so they get removed from expected-failures. New chunking is planned to be implemented on OCIS.
After this, I will look for any remaining tests that use new chunking.
Similar reva PR is https://github.com/cs3org/reva/pull/1921
CI
=> [tests-only] [full-ci] Bump core commit id for tests

changelog/unreleased/oidc-token-basic-auth.md, proxy/pkg/middleware/basic_auth.go
fixes https://github.com/owncloud/ocis/issues/2094
=> forward basic auth to OpenID connect token authentication endpoint

.make/go.mk, changelog/unreleased/ocs-cache-warmup.md, storage/pkg/command/frontend.go, storage/pkg/config/config.go, storage/pkg/flagset/frontend.go
This PR introduces a couple of changes:
- Since v1.26.0, protobuf [panics](https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict) in case of namespace conflicts instead of warning. This does not allow us to integrate extensions in oCIS for which the proto bindings were generated separately, despite the fact that `go_package` was [different](https://github.com/cernbox/ocis-canary/blob/main/pkg/proto/v0/canary.proto#L5) for the extensions' protobufs. For the time being, we set this back to warn (like it was in the previous versions) until we can find a solution.
- We added a cache warmup strategy for the resources in the ocs layer. We stat every resource when a user lists their shares, which introduced a bit of latency. To handle that, we introduced a cache …
=> Add ocs cache warmup config and warn on protobuf ns conflicts

.drone.star, tests/acceptance/cancelBuilds.sh
This PR tries to get recent builds for a particular branch and then cancel all the old builds running for that PR when a new build starts running.
- https://github.com/owncloud/QA/issues/674
- [] Acceptance tests added
=> [Tests-Only] Cancel old builds for same pr

.drone.star
the `stop-recent-builds` pipeline fails for forks because drone.owncloud.com doesn't know that repo (comming from `ctx.build.source_repo`). Instead we always need to use `ctx.repo.slug` since this acts as identifier for the target repo in drone.
Example
PR from fork to oCIS failed in this step:
```
alpine: Pulling from drone/cli
--
2 | Digest: sha256:29517295f5c1dd9ef78645f08afe360a47bc3e2bbac70c7dd755c61551b4202f
3 | Status: Image is up to date for drone/cli:alpine
4 | + drone build ls ishank011/ocis --status running > /drone/src/recentBuilds.txt
5 | client error 404: {"message":"Not Found"
```
=> [CI][docs-only] fix stop-recent-builds for forks

docs/ocis/release_notes.md
- Adds oCIS 1.10.0 and Web 4.0.0 Release Notes
- Reworks oCIS 1.9.0 Release Notes to include Web 3.4.1 changes
=> [docs-only] oCIS 1.10.0 Release Notes

accounts/pkg/storage/cs3.go, changelog/1.10.0_2021-08-06/update-reva-v1.11.1-0.20210809134415-3fe79c870fb5.md, go.mod, go.sum, graph/pkg/middleware/auth.go, graph/pkg/service/v0/users.go, ocis-pkg/indexer/index/cs3/autoincrement.go, ocis-pkg/indexer/index/cs3/non_unique.go, ocis-pkg/indexer/index/cs3/unique.go, ocis-pkg/middleware/account.go, ocs/pkg/middleware/requireselforadmin.go, ocs/pkg/middleware/requireuser.go, ocs/pkg/service/v0/groups.go, ocs/pkg/service/v0/users.go, proxy/pkg/middleware/account_resolver.go, proxy/pkg/middleware/account_resolver_test.go, proxy/pkg/middleware/create_home.go, proxy/pkg/middleware/signed_url_auth.go, proxy/pkg/proxy/policy/selector.go, proxy/pkg/proxy/policy/selector_test.go, proxy/pkg/proxy/proxy.go, tests/acceptance/expected-failures-API-on-OCIS-storage.md, thumbnails/pkg/service/v0/service.go, thumbnails/pkg/thumbnail/imgsource/cs3.go
Update REVA from v1.11.1-0.20210809134415-3fe79c870fb5 to v1.11.1-0.20210812105259-756bdced1d22
* Enh cs3org/reva#1803: /dav/spaces endpoint
* Fix cs3org/reva#1987: fix windows build
* Fix cs3org/reva#1985: Quota stubs
* Cha cs3org/reva#1982: Move user context methods into separate package
* Fix cs3org/reva#1980: propagate after restoring a file version
The change moves Token and User related Context functions and headers to the new `github.com/cs3org/reva/pkg/ctx` package.
=> [full-ci] update reva to 756bdced1d22

changelog/unreleased/switch-jwt-lib.md, go.mod, go.sum, proxy/pkg/middleware/oidc_auth.go
The old library [github.com/dgrijalva/jwt-go](https://github.com/dgrijalva/jwt-go) is now unmaintained and was replaced by the community maintained fork [github.com/golang-jwt/jwt](https://github.com/golang-jwt/jwt).
=> switch jwt library

go.mod, go.sum
pull in https://github.com/cs3org/reva/pull/1990
=> pull in owncloudsql fixes from reva

ocis/pkg/runtime/service/service.go, storage/pkg/command/groups.go, storage/pkg/command/users.go
The services ared called "storage-userprovider" and "-groupprovider".
The 'ocis help' output was missleading. This also renames the structs
accordingly.
=> Fix naming of the user- and groupprovider services

storage/pkg/flagset/users.go
=> fix wrongly named env var

.github/dependabot.yml
The repository now only holds one go.mod file at the root of the repository. Changed the path in the dependabot config to the repo root.
=> [docs-only] fix the directory path for dependabot

changelog/unreleased/update-reva.md, go.mod, go.sum, tests/acceptance/expected-failures-API-on-OCIS-storage.md
Updating reva for the upcoming release.
This is just a preparation, later today when reva has been tagged I'll update to the tagged version.
=> update reva to v1.12

docs/ocis/deployment/ocis_hello.md, docs/ocis/deployment/ocis_keycloak.md, docs/ocis/deployment/ocis_s3.md, docs/ocis/deployment/ocis_traefik.md, docs/ocis/deployment/ocis_wopi.md
Some deployment examples take some time to start. Therefore a user could be confused that it is not working yet. So I added following hint to all examples:
`You may need to wait some minutes until all services are fully ready, so make sure that you try to reload the pages from time to time.`
=> [docs-only] add hint about service startup time

changelog/unreleased/set-quota-permission.md, settings/pkg/service/v0/settings.go
In preparation for the upcoming spaces features a `SetSpaceQuota` permission was added.
I'm not entirely sure about the permission to role assignment. Especially about the ResourceType:
```
BundleId: BundleUUIDRoleAdmin,
Setting: &settings.Setting{
Id:          SetSpaceQuotaPermissionID,
Name:        SetSpaceQuotaPermissionName,
DisplayName: "Set Space Quota",
Description: "This permission allows to manage space quotas.",
Resource: &settings.Resource{
Type: settings.Resource_TYPE_SYSTEM,
},
Value: &settings.Setting_PermissionValue{
PermissionValue: &settings.Permission{
Operation:  settings.Permission_OPERATION_READWRITE,
Constraint: settings.Permission_CONSTRAINT_ALL,
},
},
},
```
=> add set space quota permission

deployments/continuous-deployment-config/cs3_users_ocis/latest.yml, deployments/continuous-deployment-config/cs3_users_ocis/released.yml, deployments/continuous-deployment-config/ocis_hello/latest.yml, deployments/continuous-deployment-config/ocis_keycloak/latest.yml, deployments/continuous-deployment-config/ocis_keycloak/released.yml, deployments/continuous-deployment-config/ocis_s3/latest.yml, deployments/continuous-deployment-config/ocis_traefik/latest.yml, deployments/continuous-deployment-config/ocis_traefik/released.yml, deployments/continuous-deployment-config/ocis_wopi/latest.yml, deployments/continuous-deployment-config/ocis_wopi/released.yml
This adds developer ssh access to continuously deployed instances, eg:
`ssh admin@ocis.ocis-traefik.latest.owncloud.works`.
- Possible after https://github.com/owncloud-devops/continuous-deployment/pull/21/files
- same as https://github.com/owncloud/web/pull/5765
Provide SSH access to continuously deployed instances to a wider audience to investigate, debug, ...
=> add developer ssh access to continously deployed instances

accounts/pkg/tracing/tracing.go, glauth/pkg/tracing/tracing.go, go.mod, go.sum, graph-explorer/pkg/tracing/tracing.go, graph/pkg/tracing/tracing.go, idp/pkg/tracing/tracing.go, ocis-pkg/tracing/tracing.go, ocis-pkg/tracing/tracing_test.go, ocs/pkg/tracing/tracing.go, proxy/pkg/tracing/tracing.go, settings/pkg/tracing/tracing.go, store/pkg/tracing/tracing.go, thumbnails/pkg/tracing/tracing.go, web/pkg/tracing/tracing.go, webdav/pkg/tracing/tracing.go
Closes https://github.com/owncloud/ocis/issues/2453
Requires https://github.com/cs3org/reva/pull/2029 to function entirely.
=> Use tracing agent instead of collector

changelog/unreleased/set-english-default-dropdown.md, settings/pkg/service/v0/settings.go, settings/ui/tests/acceptance/features/settings.feature
Show English as default language in the settings
https://github.com/owncloud/ocis/issues/2126
Manually tested in a fresh environment
1. Login with a user
2. Check the settings page
English is selected a language
=> Set english as default language

deployments/examples/ocis_wopi/docker-compose.yml
Add an icon to the Collabora app provider driver in the deployment example
=> add icon to collabora app provider in deployment example

changelog/unreleased/spaces-post.md, docs/extensions/graph/spaces.md, go.mod, go.sum, graph/pkg/service/v0/drives.go, graph/pkg/service/v0/service.go, tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Spaces can now be created on `POST /drive/{drive-name}`. Only users with the `create-space` permissions can perform this operation.
Allowed body form values are:
- `quota` (bytes) maximum amount of bytes stored in the space.
- `maxQuotaFiles` (integer) maximum amount of files supported by the space.
It also adds docs for the new API.
=> Create Storage Spaces through the Graph API

docs/ocis/migration.md, docs/ocis/storage-backends/cephfs.md
@dragotin @micbar @C0rby @refs @aduffeck Just a heads up on what I found upstream and where I see room for imprevement.
=> [docs-only] Docs storage backend cephfs

.drone.env
This PR bumps core  and web commit ids to the latest
- Part of  https://github.com/owncloud/QA/issues/689
=> [full-ci][tests-only] Bump commit ids for tests

changelog/unreleased/redirect-invalid-links-to-oC-web.md, web/pkg/service/v0/service.go
Web owns the "/" route in oCIS proxy which will match everything not matching any other more specific route. All these requests will end in the static file serve block which just returns a 404 not found. Ideally we would display a dedicated not found page which is should be included in the static files. Until we have a site like this we can redirect requests to the root, from which oC Web is served. This helps people having non valid links (eg. oC 10 links like https://foo.bar/index.php/apps/pdfviewer...) to not beeing stuck to a blank page saying "not found".
- Redirect should be replaced with a proper not found page when available -> https://github.com/owncloud/web/issues/5804
Bookmarked links from eg. ownCloud 10 which are no longer supported after an migration will lead to ownCloud …
=> redirect to root when file not found

changelog/unreleased/proxy-policy-claim-precedence.md, proxy/pkg/middleware/selector_cookie.go, proxy/pkg/proxy/policy/selector.go, proxy/pkg/proxy/policy/selector_test.go
When determining the routing policy we now let the claim override the cookie so that users are routed to the correct backend after login.
needed for https://github.com/owncloud/ocis/pull/2302
plays together with https://github.com/owncloud/openidconnect/pull/18
=> allow overriding the cookie based route by claim

changelog/unreleased/fix-username-encoding.md, ocs/pkg/middleware/requireselforadmin.go
We now properly decode the username when reading it from a url parameter
related to https://github.com/owncloud/ocis/pull/2302
=> use proper url path decode on the username

changelog/unreleased/fix-redirect-invalid-links-to-oC-web.md, web/pkg/service/v0/service.go
Invalid links ending with a slash have not been redirected after #2493. This is cared of in this PR.
- Fixes https://github.com/owncloud/ocis/pull/2493
- test case 1:
- test case 2:
- ...
=> fix: redirect invalid links to oC Web (#2493)

changelog/unreleased/remove-notifications-placeholder.md, storage/pkg/command/frontend.go
Complementary change for https://github.com/cs3org/reva/pull/1819
=> Remove placeholder notifications endpoint in capabilities

tests/acceptance/docker/src/ocis-image.yml
For running the acceptance tests in docker we setup a volume that is
shared between the ocis and oc10/testsuite container. Since ocis needs
to be able to write to that volume we're switching it to run as root.
Closes #2497
I am not really happy with this solution. It would be nicer to find a way to setup the permission of the volume so that the default user of the ocis container could actually write there. But I didn't really find a good way for that.
=> tests: Run ocis container as root for testsuite

.drone.env
Among other things, this gets the test code changes in core PR https://github.com/owncloud/core/pull/39251 running in CI.
Issue https://github.com/owncloud/QA/issues/689
=> [full-ci] [tests-only] Bump commit ids for tests

changelog/unreleased/reva-ldap-tls.md, storage/pkg/command/authbasic.go, storage/pkg/command/groups.go, storage/pkg/command/users.go, storage/pkg/config/config.go, storage/pkg/flagset/ldap.go
Reva is moving away from the hardcoded "insecure" setting for LDAP (see https://github.com/cs3org/reva/pull/2053)
connections. For this to happend ocis needs some adjustments. In order to avoid an "insecure" by default config in ocis this commit adds the new parameters "insecure" and "cacert" to the LDAP configuration for the auth-, user- and groups-provider. To make the out of the box experience as smooth as possible the default setting for "cacert" points to the certificate that is generated for glauth on startup.
To avoid any hickup with the CI this should ideally be merged together with (or before) the changes from https://github.com/cs3org/reva/pull/2053 reach this repo.
=> Allow reva to use safer TLS defaults for LDAP

changelog/unreleased/reva-auth-tokens.md, ocs/pkg/config/config.go, ocs/pkg/flagset/flagset.go, ocs/pkg/service/v0/service.go, ocs/pkg/service/v0/users.go, proxy/pkg/command/server.go, proxy/pkg/config/config.go, proxy/pkg/flagset/flagset.go, proxy/pkg/middleware/account_resolver.go, proxy/pkg/middleware/account_resolver_test.go, proxy/pkg/middleware/basic_auth.go, proxy/pkg/middleware/create_home.go, proxy/pkg/middleware/options.go, proxy/pkg/middleware/signed_url_auth.go, proxy/pkg/user/backend/accounts.go, proxy/pkg/user/backend/accounts_test.go, proxy/pkg/user/backend/backend.go, proxy/pkg/user/backend/cs3.go, proxy/pkg/user/backend/test/backend_mock.go, storage/pkg/command/authbearer.go, storage/pkg/config/config.go, storage/pkg/flagset/authbearer.go
When using the CS3 proxy backend, we previously obtained the user from reva's userprovider service and minted the token ourselves. This required maintaining a shared JWT secret between ocis and reva, as well duplication of logic. This PR delegates this logic by using the `Authenticate` method provided by the reva gateway service to obtain this token, making it an arbitrary, indestructible entry. Currently, the changes have been made to the proxy service but will be extended to others as well.
Closes https://github.com/owncloud/ocis/issues/2525
=> Use reva's Authenticate method instead of spawning token managers

changelog/unreleased/expose-reva-archiver.md, proxy/pkg/proxy/proxy.go, storage/pkg/command/frontend.go, storage/pkg/config/config.go, storage/pkg/flagset/frontend.go
Expose the reva archiver configuration
https://github.com/owncloud/ocis/issues/2507
1. Access ocis with the admin user
2. Create folder "zzz" and upload some files there
3. Connect to the archiver service:
1. Assuming you've started a basic ocis installation with `ocis server`
2. In the same host
```
root@f13b05e8714d:/# curl -v -u admin:admin -JO http://localhost:9140/archiver?dir=/home/zzz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:9140...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9140 (#0)
* Server auth using Basic with user 'admin'
> GET /archiver?dir=/home/zzz HTTP/1.1
> Host: localhost:9140 …
```
=> Expose configuration for the reva archiver

.drone.star
adding the deployment example was missed in #2302, since it only happens on master
=> enable continous deployment for migration example

.drone.star
PRs with [docs-only]  in their title do currently not check the changelog. This is a very short task and should be run on all PRs since adding an invalid changelog item would fail the CI on master after merging the PR.
This PR already demonstrates, that now the changelog step is run on [docs-only] PRs, too. (since it got the keyword in the title).
=> check changelog also on [docs-only] PRs

changelog/unreleased/fix-account-resolver.md, proxy/pkg/middleware/account_resolver.go
https://github.com/owncloud/ocis/pull/2528/files#diff-623d75273ecaa16479d6e4250fc36a6a015841b8e569bd5c2dedd7af30c0c19cL111-L122 This part was removed and hasn't been replaced. This caused the token to be empty in certain cases.
- manually, locally
=> fix the account resolver middleware

.drone.star
PRs run on a smaller set of tests to save time and resources. This means some bugs might slip through reviews and end on master. Full CI will then be run on the tag when releasing and the bug might pop up. Since this is a little bit late, this PR changes the already existing nightly CI run to run a full-ci equivalent. Developers will be informed about a failed pipeline in the chat.
=> [tests-only] run full-ci during night (cron)

.drone.star
`plugins/s3:1` has an outdated CA store - it was build 2018-09-18. Therefore we got this error:
```
RequestError: send request failed
caused by: Put ******/cache/owncloud/ocis/e4bb5b8bef0527a312437b64cda97cc715e3ab5d-6950/cache/checkstyle/accounts_checkstyle.xml: x509: certificate has expired or is not yet valid
```
`plugins/s3:latest` is just 4 months old and therefore has a valid CA store...
Was caused by https://community.letsencrypt.org/t/help-thread-for-dst-root-ca-x3-expiration-september-2021/149190
=> update plugins/s3:1 to plugins/s3:latest

changelog/unreleased/update-reva-to-477bb18843a97c6e392dd316e8735ccbe44f16ed.md, go.mod, go.sum
This PR updates cs3org/reva to v1.13.1-0.20211001063718-477bb18843a9
- full CI
=> [full-ci] Update reva to  v1.13.1-0.20211001063718-477bb18843a9

changelog/unreleased/reva-gateway-endpoint-config.md, storage/pkg/command/appprovider.go, storage/pkg/command/authbasic.go, storage/pkg/command/authbearer.go, storage/pkg/command/frontend.go, storage/pkg/command/gateway.go, storage/pkg/command/groups.go, storage/pkg/command/sharing.go, storage/pkg/command/storagehome.go, storage/pkg/command/storagemetadata.go, storage/pkg/command/storagepubliclink.go, storage/pkg/command/storageusers.go, storage/pkg/command/users.go, storage/pkg/flagset/sharing.go, storage/pkg/flagset/users.go
This is needed in order to provide Reva with a valid configuration. This is only a patch until a more robust solution is found as it keeps the nightly builds from passing.
It also improves config parsing by memoizing the cli flags parsed for a given storage subcommand, preventing unnecessary code execution when iterating over flags and applying them to the flagset.
- test case 1:
- test case 2:
- ...
=> [full-ci] Add Gateway flag to default config

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
and add expected failures for new tests related to issue https://github.com/owncloud/ocis/issues/2711
Part of issue https://github.com/owncloud/QA/issues/695
=> [tests-only] [full-ci] Bump core commit id to include empty skeleton test changes

docs/ocis/deployment/ocis_keycloak.md
Using an external OIDC IDP means that, that IDP also needs to serve  the OIDC discovery information.
- Fixes: https://github.com/owncloud/ocis/issues/2676
=> [docs-only] Add note about OIDC discovery redirect for Keycloak

docs/ocis/development/testing.md
the command as shown by the help has the string `storage` at the end
=> [docs-only] fix make command to run single feature

changelog/unreleased/fix-basic-auth-config.md, storage/pkg/command/frontend.go
Make basic auth only work when explicitly configured.
- Fixes https://github.com/owncloud/ocis/issues/2466
Basic auth was still working even though `PROXY_ENABLE_BASIC_AUTH` was set to false.
=> fix basic auth configuration

.drone.star, docs/ocis/development/continuous-integration.md
this PR uses `owncloudci/drone-skip-pipeline` to pipelines depending on changes.
- Same as https://github.com/owncloud/web/pull/5914 + https://github.com/owncloud/web/pull/5936
do not rely on magic flags to make CI runs more effective
- CI
=> skip on docs only

.drone.star, deployments/examples/ocis_wopi/docker-compose.yml
use self hosted icons for office apps in oCIS WOPI deployment example
-  Same as https://github.com/owncloud/web/pull/6000
Don't fetch the image from a third party
=> use selfhosted icons in oCIS WOPI deployment example

changelog/unreleased/fix-mediaviewer-url-encoded.md, webdav/pkg/dav/requests/thumbnail.go
Users with a username like `foo@baz.test` can not view images in the media viewer. This PR fixes that.
some oCIS installations might use email addresses as username.
- locally
=> fix opening images in media viewer for some usernames

deployments/examples/cs3_users_ocis/config/ocis/proxy-config.json, deployments/examples/oc10_ocis_parallel/config/ocis/proxy-config.dist.json, deployments/examples/ocis_hello/config/ocis/proxy-config.json, proxy/config/proxy-example-migration.json, proxy/config/proxy-example-regex.json, proxy/config/proxy-example.json
Some deployment examples miss the archiver and / or the app endpoint. These are added in this PR.
=> [deployment examples] make archiver work for deployment examples with custom proxy config

deployments/examples/oc10_ocis_parallel/config/ocis/proxy-config.dist.json
Migration deployment:
If  a users opens a `/index.php/login` or `/login` bookmark and is already migrated to oCIS, the user will not be gracefully redirected to the login screen / oC Web. Therefore I added a forward to the Web extension for these paths, which will then do a redirect.
You can try out the bug behavior on: https://cloud.oc10-ocis-parallel.latest.owncloud.works. Log in as einstein and see that you use oCIS. Then navigate to https://cloud.oc10-ocis-parallel.latest.owncloud.works/index.php/login and see that you are stuck.
After this PR you will be redirected to oC Web when you follow the second link
=> [deployment examples] redirect oCIS users from oC10 login to oC Web

tests/acceptance/features/apiArchiver/downloadById.feature, tests/acceptance/features/bootstrap/ArchiverContext.php
When using a user-agent that contains `Windows NT` in its name the endpoint replies with a ZIP archive an not a TAR archive.
These tests are checking this behavior
part of #2510
=> [tests-only] test zip archive download

tests/acceptance/features/apiSpaces/uploadSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
We don't need to have 2 steps like this to check that a resource exists (or not) in a space:
```
When user "Alice" lists the content of the space with the name "Project Venus" using the WebDav Api
Then the propfind result of the space should contain these entries:
```
This PR refactors the code to use:
```
Then the space "Project Venus" should contain these entries:
```
I remember the username that created a space, so that the `Then` step can use that username when checking what resources exist (or not) in a space.
CI
=> [tests-only] Refactor spaces API tests

.drone.star, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiArchiver/downloadById.feature
test if the archiver endpoint works correctly with Shares
part of #2510
:robot:
=> [tests-only] test archiver endpoint with shares

ocis/docker/Dockerfile.linux.amd64, ocis/docker/Dockerfile.linux.arm, ocis/docker/Dockerfile.linux.arm64
Adds `attr` and `tree` to the docker image, to have these tools at hand when you need them.
When running oCIS I may want to inspect extended attributes:
```
~/storage/users/nodes $ getfattr -d -m '' f4fead7f-d43e-45e2-b998-1eb84577048e/
user.ocis.blobid=""
user.ocis.blobsize="0"
user.ocis.name="4c510ada-c86b-4815-8820-42cdf82c3d51"
user.ocis.owner.id="4c510ada-c86b-4815-8820-42cdf82c3d51"
user.ocis.owner.idp="https://ocis.owncloud.test"
user.ocis.owner.type="primary"
user.ocis.parentid="root"
user.ocis.propagation="1"
user.ocis.space.name="Albert Einstein"
user.ocis.tmtime="2021-11-15T12:03:13.921006821Z"
user.ocis.treesize="1028608"
```
And I want to have a way to see what files exist in a file tree.
=> add attr and tree as inspection / debugging tools to the docker image

changelog/unreleased/fix-basic-auth-with-custom-user-claim, proxy/pkg/command/server.go, proxy/pkg/middleware/authentication.go, proxy/pkg/middleware/basic_auth.go
We've fixed authentication with basic if oCIS is configured to use a non-standard claim
as user claim (`PROXY_USER_OIDC_CLAIM`). Prior to this bugfix the authentication always
failed and is now working.
- Unblocks https://github.com/owncloud/ocis/issues/2387
Make basic auth login work.
- test case 1:
- test case 2:
- ...
=> fix basic auth with custom user claim

.drone.env
Includes the core SetupHelper changes merged today in PR https://github.com/owncloud/core/pull/39505
It will be good to know the strict_types checking in that change passes when run in the oCIS environment.
Part of issue https://github.com/owncloud/QA/issues/699
=> [tests-only] Bump core commit id to include recent SetupHelper core changes

deployments/examples/oc10_ocis_parallel/config/oc10/10-custom-config.sh, docs/ocis/deployment/oc10_ocis_parallel.md
oC10 OpenID Connect app 2.1.0 was released and includes the changes needed for the parallel deployment. Therefore we can remove the incompleteness warning from the docs.
- Fixes #2549
=> remove warning from parallel deployment docs

tests/acceptance/features/apiSpaces/uploadSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
This PR adds a test step:
```
Then for user "Alice" the space "Project Venus" should contain these entries:
| mainFolder        |
```
The step specifies the user. That will be specially useful when we have the functionality to grant users various access to a space. Then we can easily have test scenarios that check what different users can access resources in the pace.
I left the other step code for:
```
Then the space "Project Venus" should contain these entries:
| mainFolder        |
```
Because we will sometimes want to do a general check that some resource actually exists in a space, without mentioning a specific user. In that case the test code has to choose a username to authenticate the API request - currently it chooses the username that created the space (and in future it can do …
=> [tests-only] Add test step about 'space contains for user'

docs/clients/rclone/_index.md, docs/clients/rclone/webdav-sync-basic-auth.md, docs/clients/rclone/webdav-sync-oidc.md
Adds documentation how to use Rclone with oCIS.
- Community ticket about Rclone issues https://github.com/owncloud/ocis/issues/2767
Showcase a tool that speaks WebDAV an also works with OpenID Connect. 
- on my machine
=> Rclone documentation

changelog/unreleased/fix-s3ng-metadata-storage.md, storage/pkg/command/storagedrivers/home.go, storage/pkg/command/storagedrivers/metadata.go, storage/pkg/command/storagedrivers/user.go, storage/pkg/config/config.go
The s3ng config for the metadata storage was missing the account service information so the permissions were not set up correctly. 
This commit fixes the configuration so that s3ng can be used for the metadata storage as well.
- Fixes https://github.com/owncloud/ocis/issues/2668
Manual testing.
=> Fix s3ng metadata storage

accounts/accounts.go, glauth/Makefile, graph-explorer/graph_explorer.go, graph/Makefile, idp/Makefile, idp/idp.go, ocis-pkg/Makefile, ocis/Makefile, ocs/Makefile, proxy/Makefile, settings/settings.go, storage/Makefile, store/Makefile, thumbnails/Makefile, web/web.go, webdav/Makefile
- simplify embed rule for Web (possible since https://github.com/owncloud/web/pull/5988 landed in Web 4.5.0)
- add `go:generate` step to all `go:embed` steps, so that one can use the `go generate ./...` command to get all assets
- don't run `go generate ./...` anymore in CI, since it is no longer needed (was needed for fileb0x only)
=> go embed / generate improvements

changelog/unreleased/change-rename-app-provider-env.md, storage/pkg/config/config.go
this PR removes all `APP_PROVIDER_BASIC_*` environment variables. Their `APP_PROVIDER_*` replacements have been added in #2811 .
These two PRs together are performing a rename.
=> Rename `APP_PROVIDER_BASIC_*` environment variables

thumbnails/pkg/config/config.go, thumbnails/pkg/config/mappings.go, thumbnails/pkg/preprocessor/fontloader.go, thumbnails/pkg/preprocessor/preprocessor.go, thumbnails/pkg/preprocessor/textanalyzer.go, thumbnails/pkg/preprocessor/textanalyzer_test.go, thumbnails/pkg/service/v0/service.go
Allow usage of custom fonts for the text previews so non-latin chars (or chars not supported by the "goregular" font) can be shown
https://github.com/owncloud/ocis/issues/2620
Files containing non-latin can have a proper preview
- test case 1:
- test case 2:
- ...
Start the thumbnails service using the `THUMBNAILS_TXT_FONTMAP_FILE` pointing to a json file, for example `THUMBNAILS_TXT_FONTMAP_FILE=/myfonts/fontMap.json`. Note that all the fonts referred by the font map file must be downloaded manually and be present in the FS.
The json file must contain a json object with the following info:
* A "fontMap" key, which contains a map of script => font_file
* A "defaultFont" key, which contains the default font to be used in case the target script isn't found in the fontMap …
=> Allow rendering a text preview using custom fonts

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
Bump core commit id to use refactored core API tests from branch https://github.com/owncloud/core/tree/acceptance-test-changes-waiting-2021-11 PR https://github.com/owncloud/core/pull/39514
That is new and changed core test code. We are not merging it in  core yet because of release-10.9.0 that is in progress in core. But it would be good to use it in oCIS. So I have made this PR.
https://github.com/owncloud/QA/issues/699
CI
=> [tests-only] [full-ci] Bump commit id to use refactored core API tests

changelog/unreleased/fix-create-group-without-name.md, ocs/pkg/middleware/requireadmin.go, ocs/pkg/middleware/requireselforadmin.go, ocs/pkg/middleware/requireuser.go, ocs/pkg/service/v0/config.go, ocs/pkg/service/v0/groups.go, ocs/pkg/service/v0/response/version.go, ocs/pkg/service/v0/service.go, ocs/pkg/service/v0/users.go, tests/acceptance/expected-failures-API-on-OCIS-storage.md
We've fixed the behavior for group creation on the OCS api, where it was
possible to create a group with an empty name. This was is not possible
on oC10 and is therefore also forbidden on oCIS to keep compatibility.
This PR forbids the creation and also ensures the correct status codef
or both OCS v1 and OCS v2 apis.
- Fixes https://github.com/owncloud/ocis/issues/2823
- test case 1:
- test case 2:
- ...
=> [full-ci] Bugfix: Disallow creation of a group with empty name via the OCS api

go.mod, graph/pkg/config/config.go, graph/pkg/config/mappings.go, graph/pkg/identity/backend.go, graph/pkg/identity/cs3.go, graph/pkg/identity/ldap.go, graph/pkg/identity/ldap/reconnect.go, graph/pkg/identity/ldap_test.go, graph/pkg/service/v0/errorcode/errorcode.go, graph/pkg/service/v0/graph.go, graph/pkg/service/v0/groups.go, graph/pkg/service/v0/service.go, graph/pkg/service/v0/users.go
This adds LDAP support to the Graph API's `/users` and `/groups` endpoints. In order to keep the existing CS3 based code working during the transition phase I created a simple configurable backend mechanism and move the CS3 implementation into it's own backend.
This is still just a read-only implemetation. Support of Create,Update, Delete will be implemented at a later point in time.
Manually using graph-explorer and an external LDAP Server
=> Add (read-only) LDAP backend to Graph users/groups endpoints

changelog/unreleased/user-claim-fallback.md, proxy/pkg/user/backend/accounts.go
Some IDPs (e.g. Authelia) don't add the "preferred_username" claim.
Fallback to the "email" claim in that case.
Fixes: #2644
To fully work, this needs: https://github.com/cs3org/reva/pull/2314
=> OIDC: fallback to "email" if IDP doesn't provide "preferred_username" claim

changelog/unreleased/fix-basic-auth-route-claim-selector.md, proxy/pkg/proxy/policy/selector.go
We've fixed the claim selector based routing for requests using basic auth.
Previously requests using basic auth have always been routed to the DefaultPolicy
when using the claim selector despite the set cookie because the basic auth
middleware fakes some OIDC claims.
Now the cookie is checked before routing to the DefaultPolicy and therefore 
set cookie will also be respected for requests using basic auth.
- Unblocks https://github.com/owncloud/ocis/issues/2387
Using basic auth for testing the parallel deployment
- locally
=> Fix claim selector based routing for basic auth

accounts/pkg/command/server.go, changelog/unreleased/supervisor-stop-routine.md, glauth/pkg/command/server.go, graph-explorer/pkg/command/server.go, graph/pkg/command/server.go, idp/pkg/command/server.go, ocis/pkg/command/storagemetadata.go, ocis/pkg/runtime/cmd/run.go, ocis/pkg/runtime/service/service.go, ocs/pkg/command/server.go, proxy/pkg/command/server.go, settings/pkg/command/server.go, store/pkg/command/server.go, thumbnails/pkg/command/server.go, web/pkg/command/server.go, webdav/pkg/command/server.go
Supervised goroutines now shut themselves down on context cancellation propagation. This method still does not stop reva go-routines, since the Reva runtime does not work with contexts.
=> [Runtime] Removed trap goroutine in favor of context propagation cancelation

changelog/unreleased/public-link-signature-auth.md, proxy/pkg/middleware/public_share_auth.go
Added signature authentication to the public share auth middleware.
To support archive downloads in password protected public links we need some way to authenticate the requests.
We can't provide the password via the `Authorization` header because the download is triggered via browser mechanisms like `<a href=` and not via `fetch` or `XmlHttpRequests`.
Here the public share signature comes into play. To support archive downloads you can take the `signature` and `expiration` parameters from a files `downloadURL` and append them to the archive download url.
This could look like this:
```
curl -k 'https://localhost:9200/archiver?public-token=urxyrXobvuXYaFi&id=ZTFhNzNlZGUtNTQ5Yi00MjI2LWFiZGYtNDBlNjljYTgyMzBkOnVyeHlyWG9idnVYWWFGaS9hZGM1Nzc3MS0wNTI2LTQxYzgtYTk3Yy0wNDk5NWZjY2FkMzE=&id=ZTFhNzNlZG …
```
=> enable signature auth in public share auth middleware

changelog/unreleased/update-spaces-handle-non-existent.md, docs/extensions/storage/spaces.md, docs/ocis/adr/0007-api-for-spaces.md, go.mod, go.sum, graph/pkg/service/v0/drives.go, graph/pkg/service/v0/service.go, tests/acceptance/features/apiSpaces/changeSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
- Handle empty spaces during update
- Change the update space api scheme to `PATCH /drives/{drive-id}`
- Needs https://github.com/cs3org/reva/pull/2354
- Needs rebase after merging #2858
=> Graph api rest

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
core PR https://github.com/owncloud/core/pull/39540 prohibits space at the start or end of a group name. It should be merged to core master after the 10.9.0 release process is finished.
That has been cherry-picked into core PR https://github.com/owncloud/core/pull/39514 so that the new and changed API test scenarios can be run from oCIS. Let's see the CI  results...
CI
=> [tests-only] [full-ci] Bump core commit id to include new group name tests

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
This core PR https://github.com/owncloud/core/pull/39598 adds a bug demonstration test for core and the current OCIS behavior is okay. This PR removes the working OCIS test from the expected to fail file. 
https://github.com/owncloud/QA/issues/703 and https://github.com/owncloud/core/issues/39597
- CI
- Locally
=> [tests-only][full-ci]Remove a test scenario from expected to fail file

changelog/unreleased/enhancement-add-new-file-capability.md, docs/extensions/storage/apps.md, storage/pkg/config/config.go
We've added the new file capability of the app provider to the ocs capabilities, so that
clients can discover this url analogous to the app list and file open urls.
- Needs https://github.com/cs3org/reva/pull/2379 first
- Needed by https://github.com/owncloud/web/pull/5890#issuecomment-993905242
=> add new file url of the app provider to the ocs capabilities

.github/settings.yml
Enable Dependabot to merge PRs after they got a review and CI was green.
This makes it possible to use the `@dependabot merge` comment on the PR, which will merge the PR after your CI passes on it
=> enable dependabot to merge PRs

changelog/unreleased/enhancement-add-new-file-capability.md, storage/pkg/command/frontend.go
Fix of https://github.com/owncloud/ocis/pull/2884 and https://github.com/cs3org/reva/pull/2379, since "new_url" was added as option, but was not hooked up in the oCIS frontend part...
After this fix we get:
```bash
curl -k 'https://localhost:9200/ocs/v1.php/cloud/capabilities?format=json' -u einstein:relativity | jq '.ocs.data.capabilities.files.app_providers'
```
```json
[
{
"enabled": true,
"version": "1.0.0",
"apps_url": "/app/list",
"open_url": "/app/open",
"new_url": "/app/new"
}
]
```
Unblocks https://github.com/owncloud/web/pull/5890
=> fix app provider "new url" capability

changelog/unreleased/add-missing-machineauth-ocis-subcommand.md, ocis/pkg/command/storageauthmachine.go
We added the ocis subcommand to start the machine auth provider.
=> Add ocis storage-auth-machine subcommand

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
Release 10.9.0 has been merged to core master. The pending core acceptance test changes have also been merged to core master. Go back to running the core API  tests from core master.
- Part of https://github.com/owncloud/QA/issues/703
CI
=> [tests-only] [full-ci] Bump core commit id for tests and use core master

.drone.env, changelog/unreleased/update-web-4.8.0.md, settings/ui/tests/acceptance/features/settings.feature, settings/ui/tests/acceptance/helpers/language.js, settings/ui/tests/acceptance/pageobjects/filesPageSettingsContext.js, tests/acceptance/expected-failures-webUI-on-OCIS-storage-ocisSmokeTest.md, tests/acceptance/expected-failures-webUI-on-OCIS-storage.md, web/Makefile
The next oCIS release is a bit away but we released a minor version of web which we should try to bring into oCIS to have all the Reva edge stuff test against it 👷🏽
=> [full-ci] Bump web to v4.8.0

changelog/unreleased/enhancement-spaces-capability.md, storage/pkg/command/frontend.go
`curl -k 'https://localhost:9200/ocs/v1.php/cloud/capabilities?format=json' -u einstein:relativity | jq '.ocs.data.capabilities.spaces'`
gives
``` json
{
"version": "0.0.1",
"enabled": true
}
```
- Follow up on https://github.com/cs3org/reva/pull/2015
=> enable spaces capability

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
This PR bumps
- core commit id after https://github.com/owncloud/core/pull/39648
- Part of https://github.com/owncloud/QA/issues/711
- :robot:
=> [tests-only][full-ci] bump core commit id (2022-01-06)

docs/ocis/deployment/ocis_wopi.md
This PR adds some details about development for the app provider frontend when using the wopi deployment example for it.
=> Add web development docs to the ocis wopi deployment example

.drone.star
Since REVA edge was introduced to oCIS yesterday, we can't use the owncloudSql storage driver for now, because it lacks an implementation.
Missing function:
https://github.com/cs3org/reva/blob/edge/pkg/storage/fs/owncloudsql/owncloudsql.go#L1953-L1956
=> [tests-only] temporarily disable parallel deployment tests

go.mod, go.sum
Signed-off-by: Jörn Friedrich Dreyer <jfd@butonic.de>
=> Bump github.com/owncloud/libre-graph-api-go from 0.7.0 to 0.8.0

changelog/unreleased/enhancement-spaces-capability.md, storage/pkg/command/frontend.go, storage/pkg/config/config.go, storage/pkg/config/defaultconfig.go
Some deployments don't want to show early stages of the spaces feature
set in the clients. It can now be disabled in the capabilities.
Give admins the power to decide for their own if they want to announce the project spaces feature set.
=> Make the project spaces capability configurable

changelog/unreleased/reva-update-07451f6cd8067.md, go.mod, go.sum
Signed-off-by: Jörn Friedrich Dreyer <jfd@butonic.de>
=> update REVA to v1.16.1-0.20220112085026-07451f6cd806

changelog/unreleased/spaces-filters.md, graph/pkg/service/v0/drives.go, tests/acceptance/features/apiSpaces/listSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
This adds two possible filter terms (driveType, id) to the /me/drives endpoint on the graph api. These can be used with the odata query parameter "$filter".
We only support the "eq" operator for now.
This is leveraging the `spaces-registry` branch and needs to be rebased after that one has been merged.
```sh
curl -L -X GET "https://localhost:9200/graph/v1.0/me/drives?$filter=id eq 'f98b7cc7-15ba-4715-9d16-23a746dfe648'" \
-H "Authorization: Basic YWRtaW46YWRtaW4="
```
```sh
curl -L -X GET "https://localhost:9200/graph/v1.0/me/drives?$filter=driveType eq 'project'" \
-H "Authorization: Basic YWRtaW46YWRtaW4="
```
- curl
- needs API tests
=> Spaces filters

graph/pkg/config/config.go, graph/pkg/config/defaultconfig.go, graph/pkg/identity/backend.go, graph/pkg/identity/cs3.go, graph/pkg/identity/ldap.go, graph/pkg/identity/ldap/reconnect.go, graph/pkg/service/v0/instrument.go, graph/pkg/service/v0/logging.go, graph/pkg/service/v0/service.go, graph/pkg/service/v0/tracing.go, graph/pkg/service/v0/users.go
Sending a POST request to /graph/v1.0/users with this body:
```
{
"displayName": "Test User",
"mail": "test@example.org",
"onPremisesSamAccountName": "test",
"passwordProfile": {
"password": "secret"
}
}
```
Will create the user `test`. The call will respond with the just created user (including the server generated ID:
```
{
"displayName": "Test User",
"id": "2b7f0f9c-0739-103c-926e-03e52584738a",
"mail": "test@example.org",
"onPremisesSamAccountName": "test"
}
```
//cc @refs
=> Add support for user creation and deletion to GraphAPI (LDAP backend)

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
This PR adjusts the expected failures files after the tests related to the spaces webDAV added in apiFavorites folder.
- https://github.com/owncloud/ocis/issues/2854
- https://github.com/owncloud/core/pull/39686
- CI
- https://github.com/owncloud/core/pull/39667/commits
=> [tests-only][full-ci] adjust expected failures (apiFavorites)

changelog/unreleased/fix-ldapretry.md, graph/pkg/identity/ldap/reconnect.go
The reconnect package was missing the retry loop for LDAP Write
Operations (add, delete, mod, modrdn)
Fixes: #2974
=> graph: Fix LDAP retry handling

deployments/examples/ocis_keycloak/docker-compose.yml
docker-compose doesn't like bare boolean values in the `environment`
section. From the compose-file docs:
Any boolean values (true, false, yes, no) need to be enclosed in quotes to
ensure they are not converted to True or False by the YML parser.
=> Fix docker-compose ocis_keycloak example

changelog/unreleased/single-space-enpoint.md, graph/pkg/service/v0/drives.go, graph/pkg/service/v0/graph.go, graph/pkg/service/v0/service.go, tests/acceptance/features/apiSpaces/listSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
Add `GET https://ocis.test/graph/v1.0/drives/{driveId}`
Give the clients the possibility to lookup a single space by ID
- added acceptance test for personal space
- added acceptance test for a project space
=> add GetSingleDrive handler

.drone.star
Unit test result upload needs a custom clone step without a merge to master of the PR branch. Threfore we cloned the source repo of the branch. But when a fork has an outdated default branch, we may not find the target commit ID of the PR. Therefore we now always clone owncloud/ocis and just add the fork (if it is a fork) as an additional remote, in order to get the PR commit.
- Makes pipline of https://github.com/owncloud/ocis/pull/2989 green
=> fix fork handling for the unit test result upload

changelog/unreleased/delete-spaces.md, go.mod, go.sum, graph/pkg/service/v0/drives.go, graph/pkg/service/v0/service.go, graph/pkg/service/v0/service_test.go, proxy/pkg/middleware/create_home.go
Added a new graph endpoint to delete and purge spaces.
We needed a way to delete spaces.
- locally using curl and the graph-explorer
=> implement graph endpoint to delete spaces

docs/extensions/storage/storagedrivers.md
Very simple docs fix stating **owncloud** is the default storage driver (incorrect) off the back of raising [this issue](https://github.com/owncloud/ocis/issues/2969) and seeing [this update](https://github.com/owncloud/ocis/commit/7803ad5fbdde0cbb8a8cf7dd89ef4066708398bf) earlier today.
=> Change outdated documentation ("owncloud" driver is not the default)

accounts/ui/store/index.js, settings/ui/store/index.js
I did not test this, but grepping for `loadConfig`, `LOAD_CONFIG` or simply `config` I could not find any usage of the app config.
Config handling has been refactored in oC Web, so this code is basically dead.
See https://github.com/owncloud/web/issues/3726
=> Remove obsolete loadConfig

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
This PR adjusts the expected failures files after the tests related to the spaces webDAV added in apiAuthWebDav suites.
- includes
-    https://github.com/owncloud/ocis/pull/3037
- https://github.com/owncloud/ocis/issues/3029
- https://github.com/owncloud/core/pull/39718
- https://github.com/owncloud/QA/issues/715
- CI
- https://github.com/owncloud/core/pull/39718/commits
=> [tests-only][full-ci]Update expected failure after spaces tests added on `apiAuthWebDav` suites

changelog/unreleased/fix-default-client-registry-settings.md, ocis-pkg/service/grpc/service.go
We've fixed the default grpc client to use the registry settings. Previously it always
used mdns.
- test case 1:
- test case 2:
- ...
=> make default client respect the registry settings

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
core PR https://github.com/owncloud/core/pull/39728 has refactored the tests related to issue #3047 
This PR bumps the core commit id to include the refactored test scenarios. I have added comments in issue #3047 about each scenario that fails in oCIS.
#3047 
https://github.com/owncloud/core/pull/39728
https://github.com/owncloud/QA/issues/715
CI
=> [tests-only] [full-ci] Bump core commit id to include core PR 39728 test changes

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
This PR adjusts the expected failures files after the tests related to the spaces webDAV added in apiWebdavProperties1 suites.
- https://github.com/owncloud/ocis/issues/3042
- https://github.com/owncloud/core/pull/39733
- https://github.com/owncloud/QA/issues/715
- CI
- Locally
=> [tests-only][full-ci]Update expected failure after spaces added on apiWebdavProperties1

storage/pkg/config/defaultconfig.go
With https://github.com/cs3org/reva/pull/2436 the groupfilter setting
for the user provider was adjusted to no longer use a go-template value
as the input. Adjust our default to match those changes. For details
see:
https://github.com/cs3org/reva/blob/edge/changelog/unreleased/ldap-usergroupfilter-template.md
=> Adjust UserGroupFilter default to match latest reva changes

.vscode/launch.json, changelog/unreleased/change-default-log-level.md, ocis-pkg/log/log.go
The default log level is now "error"
=> change default log level to error

.drone.star, changelog/unreleased/change-remove-owncloud-storage-driver.md, deployments/examples/oc10_ocis_parallel/docker-compose.yml, docs/extensions/storage/storagedrivers.md, docs/ocis/deployment/oc10_ocis_parallel.md, storage/pkg/command/storagedrivers/user.go, storage/pkg/config/config.go, storage/pkg/config/defaultconfig.go, tests/acceptance/docker/Makefile, tests/acceptance/docker/src/ocis-base.yml
We've removed the ownCloud storage driver because it was no longer
maintained after the ownCloud SQL storage driver was added.
If you have been using the ownCloud storage driver, please switch
to the ownCloud SQL storage driver which brings you more features and
is under active maintenance.
- Found in https://github.com/owncloud/ocis/issues/2969
- REVA part: https://github.com/cs3org/reva/pull/2495
=> [full-ci] remove the owncloud storage driver

changelog/unreleased/fix-ldap-del-usermembership.md, graph/pkg/identity/ldap.go
Upon deleting a User from the LDAP backend, we also need to cleanup
the user's group memberships as LDAP itself doesn't make any promises
about referential integrity.
- Fixes #3027
=> Delete group memberships when deleting a user

.drone.star, tests/parallelDeployAcceptance/expected-failures-API.md, tests/parallelDeployAcceptance/features/apiShareManagement/acceptShares.feature
This PR fixes the sharing tests that were not working in parallel deployment pipelines
- Fixes https://github.com/owncloud/ocis/issues/3069
- test environment: local & CI
=> [tests-only] Fix sharing tests in parallel deployment tests

tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Fix errors in the feature file links in expected-failures files. A few have got out-of-date line numbers, wrong feature file names etc.
I have a PHP script that I used to parse locally and find these. I will think about where to put that so that we can automatically find these accidental errors. They don't cause an actual problem for CI, it is just confusing for real people if they look at or click a link that is wrong.
=> [tests-only] [full-ci] Fix expected-failures references

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
This PR adds spaces tests to the expected failures files after the tests related to the spaces added in apiWebDavEtagpropagation2 suites.
- https://github.com/owncloud/ocis/issues/3075
- https://github.com/owncloud/core/pull/39744
- https://github.com/owncloud/QA/issues/715
- CI
- Locally
=> [tests-only][full-ci]Add expected failure for spaces tests on  apiWebDavEtagpropagation2 suite

ocis-pkg/roles/manager.go, ocs/pkg/middleware/requireselforadmin.go, ocs/pkg/service/v0/groups.go
This PR includes two workaround to get the CS3 backend for the ocs API to a somewhat working state. With this we'd no longer need to switch to the reva implemenation of ocs, e.g. when using an external LDAP server.
- Partial Fix for #2646
When using an external LDAP server we currently have to adjust the proxy configuration to point to the reva implemation of the ocs API. With this fix this should no longer be needed. I aware that these are mainly workarounds, but as we (at least to my understanding) agreed on removing the /ocs/cloud/users and ./groups services in the (not so long) run, I think they should be good enough. (btw, the /users/userid/groups implementation in reva also just returns an empty list, so we're not loosing anything here)
manually using the WebUI / curl
=> Fixes for /ocs/cloud/users when using the CS3 user backend

docs/ocis/adr/0015-events.md
writing down the decision process about events in ocis/reva
=> [docs-only] Events adr

thumbnails/pkg/server/grpc/server.go, thumbnails/pkg/service/v0/decorators/base.go, thumbnails/pkg/service/v0/decorators/instrument.go, thumbnails/pkg/service/v0/decorators/logging.go, thumbnails/pkg/service/v0/decorators/tracing.go, thumbnails/pkg/service/v0/service.go
Implement a decorator pattern, allowing extension of the target interface. This means additional methods can be added in the interface in the future.
Thumbnail's instrument, logging and tracing files have been moved to the decorators package.
No issue opened
There are plans to for the thumbnails to implement a config service. With these changes, adding the implementation will be easier
Manually checked by uploading a file. No changes in the thumbnail service were detected
=> Use decorator pattern and allow more methods to be decorated

protogen/docs/GRPC.tmpl
It seems that owncloud.dev have some trouble with some of the links in the documentation containing `.`. This PR will replace those `.` with `_`
No opened issue
Clicking in the faulty links downloads a file instead of showing the contents. This is a bad behavior that needs to be fixed.
It's working with hugo. Checked by cloning the repo, run `make docs-serve` and finally access the link.
=> Change the links to use "_" instead of "."

changelog/unreleased/restore-spaces.md, go.mod, go.sum, graph/pkg/service/v0/drives.go, tests/acceptance/expected-failures-API-on-OCIS-storage.md
Restore spaces by sending to the Patch Drive Graph endpoint. Get information when a drive is deleted (Check it's root for "deleted" flag) 
```bash
curl -k https://localhost:9200/graph/v1.0/me/drives -u admin:admin 
```
```json
...
{
"driveType": "project",
"id": "db589b97-f2ea-4864-bf5f-55a43325f77a",
"lastModifiedDateTime": "2022-02-04T09:07:45.824270628+01:00",
"name": "Project PUPPELE",
"owner": {
"user": {
"id": "ddc2004c-0977-11eb-9d3f-a793888cd0f8"
}
},
"quota": {
"remaining": 1000000000,
"state": "normal",
"total": 1000000000,
"used": 0
},
"root": {
"id": "db589b97-f2ea-4864-bf5f-55a43325f77a",
"webDavUrl": "https://localhost:9200/dav/spaces/db589b97-f2ea-4864-bf5f-55a43325f77a"
}
}
...
```
```bash
curl -X DELETE -k https://localhost:9200/graph/v1.0/drives/db589b97-f2ea-4864-bf5f-55 …
```
=> Restoring spaces graph endpoint

changelog/unreleased/drive-permissions.md, go.mod, go.sum, graph/pkg/service/v0/drives.go, tests/acceptance/expected-failures-API-on-OCIS-storage.md
Added permissions to graph drives when listing drives.
A drive looks like this after this change:
```json
{
"driveType": "personal",
"id": "058bff95-6708-4fe5-91e4-9ea3d377588b",
"lastModifiedDateTime": "2022-02-03T11:15:11.464382312+01:00",
"name": "Maurice Moss",
"owner": {
"user": {
"id": "058bff95-6708-4fe5-91e4-9ea3d377588b"
}
},
"root": {
"id": "058bff95-6708-4fe5-91e4-9ea3d377588b",
"permissions": [
{
"grantedTo": [
{
"user": {
"id": "058bff95-6708-4fe5-91e4-9ea3d377588b"
}
}
],
"roles": [
"manager"
]
}
],
"webDavUrl": "https://localhost:9200/dav/spaces/058bff95-6708-4fe5-91e4-9ea3d377588b"
}
}
```
We want to see who has access to a space.
=> add permissions to the graph drives

deployments/examples/oc10_ocis_parallel/.env, deployments/examples/oc10_ocis_parallel/config/oc10/10-custom-config.sh, deployments/examples/oc10_ocis_parallel/config/oc10/11-testing-app.sh, deployments/examples/oc10_ocis_parallel/docker-compose.yml, deployments/examples/oc10_ocis_parallel/testing/docker-compose-additions.yml, deployments/examples/ocis_hello/docker-compose.yml, deployments/examples/ocis_ldap/docker-compose.yml, deployments/examples/ocis_s3/docker-compose.yml, deployments/examples/ocis_traefik/docker-compose.yml, deployments/examples/ocis_wopi/docker-compose.yml, docs/ocis/development/testing.md
This adds documentation on how to run the acceptance tests for parallel deployment setup locally.
- Closes  https://github.com/owncloud/ocis/issues/3097
Guide to  run parallel deployment tests locally
=> [docs-only] Add doc on running parallel deployment tests locally

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpaces/deleteSpaces.feature, tests/acceptance/features/apiSpaces/restoreSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
- added api test: restoring disabled space
- added test that only user with manager permissions can see the disabled space
- added check,  if the space is disabled, it is displayed in the response:
```
"root": {
"deleted": {
"state": "trashed
},
```
=> [tests-only] apiTests. restoring disabled space

graph/pkg/config/config.go, graph/pkg/config/defaultconfig.go, graph/pkg/identity/ldap/reconnect.go, graph/pkg/service/v0/service.go
To allow skipping TLS Certificate verification in development environments.
=> Add "insecure" flag to graph LDAP backend

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/expected-failures-webUI-on-OCIS-storage-ocisSmokeTest.md, tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
core PR https://github.com/owncloud/core/pull/39782 added a lint check of the expected-failures file.
This PR bumps the CORE_COMMITID so that the lint check will be run. After this, if we make invalid changes to an expected-failures file then the lint check will report the problem and fail the CI pipeline/
Part of https://github.com/owncloud/QA/issues/721
CI
=> [tests-only] [full-ci] Bump CORE_COMMITID to include expected-failures linter

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
This PR adjusts the expected failures files after the tests related to the spaces webDAV added in api move suite.
- https://github.com/owncloud/ocis/issues/3107
- https://github.com/owncloud/core/pull/39774
- https://github.com/owncloud/QA/issues/721
- CI
- Locally
=> [tests-only][full-ci]Adjust expected failure for api move suites

.github/stale.yml
The stale bot has been finding issues labelled QA:team. Make those exempt from the stale bot - we can manage those ourselves.
=> Do not make QA issues stale

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
bump core commit id to the latest up to date `2022-02-16`
part of https://github.com/owncloud/QA/issues/721
> PR to verify https://github.com/owncloud/core/pull/39792
=> [full-ci][tests-only] bump core commit id to the latest upto `2022-02-16`

.drone.env
Bumps the core commit id for tests in master branch. Gets the code from https://github.com/owncloud/core/pull/39793 running in CI for the edge branch.
, 
This is similar to https://github.com/cs3org/reva/pull/2556 and https://github.com/cs3org/reva/pull/2557
The core test code changes should not be really relevant her in oCIS, because the test code uses the graph API end points to fins out space ids. But the commit id bump makes sure that there is no accidental side-effect.
=> [tests-only] [full-ci] Bump core commit id to include PR 39793 getPersonalSpaceIdForUser changes

changelog/unreleased/unify-file-ids.md, go.mod, go.sum, graph/pkg/service/v0/driveitems.go, graph/pkg/service/v0/drives.go, graph/pkg/service/v0/graph_test.go
We changed the file IDs to be consistent across all our APIs (WebDAV, LibreGraph, OCS). We removed the base64 encoding. Now they are formatted like `<storageID>!<opaqueID>`. They are using a reserved character ``!`` as a URL safe separator.
Reva PR https://github.com/cs3org/reva/pull/2542
FileIDs should be consistent across all APIs
- Manually
- CI
```bash
curl -L -X PROPFIND 'https://localhost:9200/dav/spaces/6afcb97a-e632-447d-b832-1334a8a9634f' \
-H 'Depth: infinity' \
-H 'Authorization: Basic YWRtaW46YWRtaW4='
```
```xml
<d:multistatus xmlns:s="http://sabredav.org/ns" xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
<d:response>
<d:href>/dav/spaces/6afcb97a-e632-447d-b832-1334a8a9634f/</d:href>
<d:propstat>
<d:prop>
<oc:id>6afcb97a-e632-447d-b832-1334a8a9634f!6afcb97a-e632-447d-b832-1 …
```
=> [full-ci] Unify id format

tests/acceptance/features/apiSpaces/listSpaces.feature, tests/acceptance/features/apiSpaces/shareSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
the currentl logic parsing the json file and using specific key -> values breaks when we have unsorted lists.
We need to refactor this @phil-davis @ScharfViktor
=> add Api test for adding space managers

.drone.env, changelog/unreleased/update-web-5.1.0.md, web/Makefile
Brings web assets up to date for the most recent web release. Changelog:
https://github.com/owncloud/web/releases/tag/v5.1.0
Doesn't bring much value for oCIS, but let's still keep it up to date.
=> [full-ci] Update web assets to v5.1.0

changelog/unreleased/fix-storage-metadata-env-var-name.md, storage/pkg/config/config.go
Currently **STORAGE_METADATA_GRPC_PROVIDER_ADDR** environment variable used as the way to set the GRPC bind port for the service.  All other services use the format **<SERVICE_NAME>_GRPC_ADDR for GRPC**, and **<SERVICE_NAME>_HTTP_ADDR** for HTTP.
This change brings it in line with the others, as it's confusing why this one is different.
Simple test is to run the following:
`docker run -d --name ocis -e OCIS_RUN_EXTENSIONS="storage-metadata" -e STORAGE_METADATA_GRPC_ADDR="0.0.0.0:9215" owncloud/ocis`
Check port this service is bound to (expect it to bind to external address):
`docker exec -it ocis /usr/bin/nc -zv 172.17.0.2:9215`
Expect to see:
`172.17.0.2:9215 (172.17.0.2:9215) open`
This is possibly a breaking change but a search of the source code finds no specific references to this …
=> fix: align storage metadata GPRC bind port with other variable names

changelog/unreleased/add-ordering-list-drives.md, graph/pkg/service/v0/drives.go, graph/pkg/service/v0/drives_test.go, graph/pkg/service/v0/graph_test.go, graph/pkg/service/v0/ordering.go, sonar-project.properties
Implements orderby name and lastModifiedDateTime
- Fixes #3200 
- manually
```sh
curl -L -X GET "https://localhost:9200/graph/v1.0/me/drives/?$orderby=lastModifiedDateTime desc" \
-H "Authorization: Basic YWRtaW46YWRtaW4="
```
```sh
curl -L -X GET "https://localhost:9200/graph/v1.0/me/drives/?$orderby=name asc" \
-H "Authorization: Basic YWRtaW46YWRtaW4="
```
=> add orderby name and lastModifiedDateTime

graph/pkg/service/v0/service.go
Silence the warning about Insecure being true. `Insecure` is not our default configuration, but need it to work in some cases.
=> Fix linter issue

.drone.env
core PR https://github.com/owncloud/core/pull/39813 enhanced the test code that checks the `status.php` end-point. Bump the CORE_COMMITID so that we run that code in CI.
=> [tests-only] [full-ci] Bump CORE_COMMITID to include core PR 39813

changelog/unreleased/changeNatsPort.md, go.mod, go.sum, nats/pkg/config/defaultconfig.go, storage/pkg/command/sharing.go
Change Nats port and bump reva version
- test case 1:
- test case 2:
- ...
=> bump reva and change nats port

graph/pkg/middleware/requireadmin.go, graph/pkg/service/v0/option.go, graph/pkg/service/v0/service.go
Only users with the account management permission should be able to
create, update or delete users. This also restricts access to the APIs
that allow listing all Groups/all Users.
Fixes #3177
=> Add permission checks to `users` and `groups` Graph API

deployments/examples/oc10_ocis_parallel/docker-compose.yml, deployments/examples/ocis_keycloak/docker-compose.yml
Keycloak switch to Quarkus with their v17 release (instead of Wildfly). The Quarkus based docker images don't support automatic setup yet (https://github.com/keycloak/keycloak/issues/10216). Therefore this PR changes the Keycloak Docker Tag from `latest` to `legacy`, to stay on the Wildfly based distribution for now (it will be supported until June 2022).
- Fixes broken deployment examples using Keycloak
- test case 1:
- test case 2:
- ...
=> [deployment examples] switch to Keycloak legacy (Wildfly)

changelog/unreleased/fix-events-config.md, nats/pkg/config/config.go, storage/pkg/command/sharing.go, storage/pkg/config/config.go, storage/pkg/config/defaultconfig.go
make events settings configurable
- Fixes individual service deployments and kubernetes deployments
- locally
=> make events settings configurable

docs/extensions/graph/groups.md, docs/extensions/graph/users.md
This address a couple of review issues raised in #3149
=> [docs-only] Fix typos in graph user and groups docs

changelog/unreleased/enhancement-web-cache-control.md, changelog/unreleased/enhancement-web-spa-fileserver.md, storage/pkg/command/groups.go, web/pkg/assets/server.go, web/pkg/service/v0/service.go
Adding a custom fileServer implementation was neede due the requirement of having nice and clean URLs without a hash `http://foo.tld/#foo/bar`. To get a more detailed insight please read [6277](https://github.com/owncloud/web/issues/6277).
The implementation behaves similar to the nginx try_files setting and always falls back to the index.html file if a requested resource is not found.
It also injects a  `base` tag into the html files which is needed for web to sniff what mode to use (`hash` or `history`).
We cannot get rid of the `hash` mode for now because we still use it in oc10 and maybe in custom deployments.
A nice side effect is that we're now able to re-enable cache headers for the web service.
- Fixes https://github.com/owncloud/web/issues/6277
- Fixes …
=> add spa fileserver to the web service

changelog/unreleased/fix-capabilities-for-public-links.md, proxy/pkg/middleware/basic_auth.go, proxy/pkg/middleware/basic_auth_test.go
Requesting capabilities from password protected links wasn't possible.
- requirement for https://github.com/owncloud/web/pull/6471
- requested by: https://github.com/owncloud/web/issues/5863
allow public links with password protection to request capabilities.
- tests added
-
=> allow requesting capabilities from password protected links

changelog/unreleased/notifications-service.md, notifications/cmd/notifications/main.go, notifications/pkg/channels/channels.go, notifications/pkg/command/health.go, notifications/pkg/command/root.go, notifications/pkg/command/server.go, notifications/pkg/command/version.go, notifications/pkg/config/config.go, notifications/pkg/config/debug.go, notifications/pkg/config/defaultconfig.go, notifications/pkg/config/log.go, notifications/pkg/config/parser/parse.go, notifications/pkg/config/service.go, notifications/pkg/logging/logging.go, notifications/pkg/service/service.go, ocis-pkg/config/config.go, ocis-pkg/config/defaultconfig.go, ocis/pkg/command/notifications.go, ocis/pkg/runtime/service/service.go
Implemented the minimal version of the notifications service to be able to notify a user when they received a share.
Currently the message is hard coded and there is only one communication channel for email. In the future we could have templated messages which could also be formatted by the the communication channel. Also a HTTP/REST service could be added to allow other services to send messages to users.
I implemented the functionality to also send messages to groups but this doesn't work currently since we don't have an authenticated context which we need to communicate with the gateway. On solution for this would be to have a service user but maybe we could have other solutions like [mTLS](https://www.cloudflare.com/learning/access-management/what-is-mutual-tls/) for service to …
=> Enh: First version of the notifications service

changelog/unreleased/spaces-thumbnails.md, thumbnails/pkg/service/v0/service.go, thumbnails/pkg/thumbnail/imgsource/cs3.go, webdav/pkg/dav/requests/thumbnail.go, webdav/pkg/service/v0/service.go
Added support for thumbnails in spaces.
The thumbnail code in the webdav and thumbnails module feel a bit hacky now after many adjustments.
When we have some more time we should invest a bit of it to make the API of the thumbnails service better.
Maybe even consider a HTTP API for the thumbnails service since serving large content through GRPC is not recommended. (4 MB is already large for GRPC)
=> support thumbnails in spaces

changelog/unreleased/spaces-thumbnails.md, thumbnails/pkg/thumbnail/imgsource/cs3.go
When requesting files using spaces references, the path needs to be relative. I thought it was working, when I tested it because I was using files which were already in the thumbnails service cache. The thumbnails service never had to load these files from the storage and that's why I never encountered this issue.
Lesson learned: when working with the thumbnailer, clear the thumbnails cache!
=> fix spaces thumbnails

.make/go.mk, go.mod, go.sum, idm/Makefile, idm/cmd/idm/main.go, idm/pkg/command/health.go, idm/pkg/command/root.go, idm/pkg/command/server.go, idm/pkg/command/version.go, idm/pkg/config/config.go, idm/pkg/config/debug.go, idm/pkg/config/defaultconfig.go, idm/pkg/config/log.go, idm/pkg/config/parser/parse.go, idm/pkg/config/service.go, idm/pkg/config/tracing.go, idm/pkg/logging/logging.go, idm/pkg/server/debug/option.go, idm/pkg/server/debug/server.go, idp/pkg/service/v0/service.go, ocis-pkg/config/config.go, ocis-pkg/config/defaultconfig.go, ocis-pkg/log/logrus_wrapper.go, ocis/pkg/command/idm.go, ocis/pkg/runtime/service/service.go
This add a new service "idm" providing and LDAP service (via ldaps) on port 9230.  If not existing it will bootstrap an initial LDAP tree and administrative user as well as a self-signed Certificate and Key (similar to what is done for glauth).
The service is currently not integrated with the other serivce. I.e. changes to point e.g. the graph service and cs3 user and group providers will follow in another PR.
Manual test:
`OCIS_LOG_LEVEL=debug ocis/bin/ocis server`
```
LDAPTLS_REQCERT=allow ldapsearch -x -H ldaps://:9230 -b o=libregraph-idm -Duid=libregraph,o=libregraph-idm -w admin
#
#
dn: o=libregraph-idm
o: libregraph-idm
objectClass: organization
dn: ou=users,o=libregraph-idm
objectClass: organizationalUnit
ou: users
dn: ou=groups,o=libregraph-idm
objectClass: organizationalUnit
ou: …
```
=> embed libgraph/idm as a service

docs/ocis/adr/0016-files-metadata.md
This PR adds a missing weight to the markdown header of `ocs/ocis/adr/0016-files-metadata.md`to fix the navigation menu order.
manual
=> Add missing weight to header to fix menu sorting

accounts/pkg/service/v0/accounts.go, graph/pkg/service/v0/graph.go, graph/pkg/service/v0/service.go, graph/pkg/service/v0/users.go
Similar to what the accounts service is doing, all new users get
the User role assigned now. Otherwise creating the user's personal space
upon login is not working.
This also add validation for the username an mail address the GraphAPI endpoints that allow updating attributes and fixes the valid mail regex in the accounts service.
- Partial Fixes #3247 
- manual
=> graph: Assign new user the default user role

changelog/unreleased/spaces-etags.md, go.mod, go.sum, graph/pkg/service/v0/drives.go
Added etags in the response of list drives.
Example response:
```json
{
"value": [
{
"driveType": "public",
"id": "7993447f-687f-490d-875c-ac95e89a62a4",
"lastModifiedDateTime": "1970-01-01T01:00:00+01:00",
"name": "Public shares",
"root": {
"id": "7993447f-687f-490d-875c-ac95e89a62a4!7993447f-687f-490d-875c-ac95e89a62a4",
"webDavUrl": "https://localhost:9200/dav/spaces/7993447f-687f-490d-875c-ac95e89a62a4"
}
},
{
"driveType": "personal",
"id": "ddc2004c-0977-11eb-9d3f-a793888cd0f8",
"lastModifiedDateTime": "2022-03-03T11:33:39.81499861+01:00",
"name": "Admin",
"owner": {
"user": {
"id": "ddc2004c-0977-11eb-9d3f-a793888cd0f8"
}
},
"quota": {
"remaining": 297848631296,
"state": "normal",
"total": 297848661180,
"used": 29884
},
"root": {
"eTag": "\"853fc6056d1620e4d19f22552f7b731f\"",
"id": …
```
=> include spaces etags in drives listing

tests/acceptance/features/apiSpaces/changeSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
Created tests for method: 
PATCH `https://localhost:9200/graph/v1.0/drives/spaceId --data-raw '{"special":[{"specialFolder":{"name":"readme"},"id":"fileId"}]}'`
1. I create a readmi file or an image file in the .space folder
2. I add the file to a special section in space (using method PATCH)
3. I check that the files are added to the space response
=> [tests-only] ApiTest: set space image/description to space

.github/settings.yml, docs/extensions/port-ranges.md
Port Ranges are the only left "real" page in the GH wiki. Therefore the PR moves it to owncloud.dev and disables the wiki.
=> migrate GH wiki to owncloud.dev

changelog/unreleased/gif-thumbnails.md, thumbnails/pkg/thumbnail/generator.go
Some GIFs with certain frame disposal strategies resulted in glitchy thumbnails. This PR makes sure to respect the disposal strategy of the source GIF.
=> improve gif thumbnail generation

changelog/unreleased/fix-network-on-individual-services.md, deployments/examples/ocis_individual_services/docker-compose.yml
Tidy up the `deployments/examples/ocis_individual_services` example so that the instructions work.
No need for manually creating a network via `docker create network ocis-net` (not in example instructions).
Tested in Windows 10 / WSL 2 Ubuntu and works as expected.
=> fix: remove need for external ocis-net network

.drone.star, Makefile, audit/Makefile, audit/pkg/service/service.go, audit/pkg/service/service_test.go, audit/pkg/types/constants.go, audit/pkg/types/conversion.go, audit/pkg/types/events.go, audit/pkg/types/types.go, changelog/unreleased/sharing-audit-events.md, go.mod, go.sum
Adds sharing events to the audit logging service
- unit tests run in ci-pipeline
=> Share events for audit logging

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
Bump to the latest core commit id.
Note: this brings in tests for the new "product" data item in the capabilities and status requests. That needs to be sorted out in reva and oCIS, so I raised issue #3317 - I might sort it out in the reva commit id update, but even if I do, the changes will need to be pulled into ocis (whenever that happens next)
https://github.com/owncloud/QA/issues/731
CI
=> [tests-only] [full-ci] Bump core commit id

docs/ocis/storage-backends/dcfsnfs.md
This adds some documentation to the devdocs about running oCIS on a NFS share.
- Fixes ocis-2271
=> [docsonly] Documentation about a test running oCIS over NFS.

proxy/pkg/user/backend/cs3.go, storage/pkg/config/defaults/defaultconfig.go
External users, when logging in for the first time, have no role
assigned and are unable to create their home because that requires the
create-space permission. This assigns users that don't have a role assigned
to the default user role and persists that assignment in the settings
service so that CreateHome can pick it up when checking permissions
later.
This also disables the auto creation of the user's home in the reva
auth provider (i.e. when using basic auth) as the role assignement has
not happenend at that point. So the home creation will now always happen
in the CreateHome middleware in the proxy.
- manually
-
=> Fix CreateHome for external users

changelog/unreleased/update-reva.md, go.mod, go.sum, tests/acceptance/expected-failures-API-on-OCIS-storage.md
Updating REVA so that the web team can use oCIS master to work on spaces features.
=> [full-ci] update reva to v2.0.0-20220316045927-99115670eb33

changelog/unreleased/password-reset-link.md, idp/pkg/config/service.go, idp/pkg/service/v0/service.go, idp/ui/public/index.html, idp/ui/src/containers/Login/Login.js, idp/ui/src/reducers/common.js
Added a configurable passwort reset link to the login page.
It can be set via `IDP_PASSWORD_RESET_URI`. If the option is not set, the link will not be shown.
It looks like this:
=> add password reset link to login page

changelog/unreleased/graph-getusers-err.md, graph/pkg/service/v0/users.go
A missing return statement caused GetUsers to return missleading results
when the identity backend returned an error.
=> Fix error handling in GetUsers

.drone.env
Includes latest test code for API tests.
In particular PR https://github.com/owncloud/core/pull/39893 which added some extra options for LDAP-based testing. So this commit-id bump will confirm that the existing tests still work the same in oCIS.
https://github.com/owncloud/QA/issues/735
CI
=> [tests-only] [full-ci] Bump CORE_COMMITID

.drone.star
PR https://github.com/owncloud/ocis/pull/3347 has mistakenly used `selenium` docker image for `deploy` pipeline.
This fixes the image name
Failing CI pipelines
=> [full-ci] Fix image name for deploy pipeline

.drone.env
Gets test changes from https://github.com/owncloud/core/pull/39914 running in oCIS CI.
https://github.com/owncloud/QA/issues/735
CI
=> [tests-only] Bump core commit id to include cofre PR 39914

idm/ldif/base.ldif.tmpl
This is a quick workaround to make the settings service work with idm after b7c934b1b1. We need to to provide a better 
solution for service users like that (they shouldn't need to be present in ldap)
See: https://github.com/owncloud/ocis/issues/3343
=> Add service user for settings service

docs/extensions/idm/setup.md
More an more people are looking into libregraph/idm related things. This adds some words about how to use idm with the current code (instead of spreading the info across multiple github issues)
=> [docs-only] Add a few words about idm and how to enable it

docs/ocis/getting-started/demo-users.md, settings/pkg/service/v0/settings.go, settings/pkg/store/defaults/defaults.go
The global "Space Manager" role is now called "Space Admin" to be different from the per space "Space Manager"
=> rename space manager to space admin

tests/acceptance/features/apiSpaces/shareSubItemOfSpace.feature, tests/acceptance/features/apiSpaces/shareSubItemOfSpaceViaPublicLink.feature, tests/acceptance/features/bootstrap/SpacesContext.php
added tests sharing subItems inside of the space:
- via sharing
- via public link
Only users with the **manager space role** can be able to share resources within the space
Users with editor and viewer space role cannot be able to share resources within the space. 
They get 404 Error with "No share permission" message. for client would certainly be better to get 403. 
code here:
https://github.com/cs3org/reva/blob/9e040c93d60ec5faf6c8b0347ce9ecf8d6c6ab70/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/shares.go#L192-L196
=> [tests-only] ApiTests: sharing subItems inside of space

go.mod, go.sum
updates lico to get libregraph/lico#32, which uses github.com/gofrs/uuid instead of github.com/satori/go.uuid since it has a known vulnerability https://pkg.go.dev/vuln/GO-2020-0018
=> update lico to get libregraph/lico#32

.drone.env, changelog/unreleased/add-remote-item-fix-spaceID.md, go.mod, go.sum, graph/pkg/service/v0/driveitems.go, graph/pkg/service/v0/drives.go, graph/pkg/service/v0/graph_test.go, tests/acceptance/expected-failures-webUI-on-OCIS-storage.md, tests/acceptance/features/apiSpaces/listSpaces.feature, tests/config/drone/ocis-config.json, web/pkg/config/defaults/defaultconfig.go
Change: Add remote item to mountpoint and fix spaceID
A mountpoint represents the mounted share on the share receivers side. The original resource is located where the grant has been set. This item is now shown as libregraph remoteItem on the mountpoint. While adding this, we fixed the spaceID for mountpoints.
```json
{
"driveAlias": "mountpoint/test",
"driveType": "mountpoint",
"id": "a0ca6a90-a365-4782-871e-d44447bbc668!28430982-37ee-4492-9cef-dc94a7807211",
"name": "Test",
"owner": {
"user": {
"id": "ddc2004c-0977-11eb-9d3f-a793888cd0f8"
}
},
"quota": {
"remaining": 0,
"state": "normal",
"total": 0,
"used": 0
},
"root": {
"eTag": "\"3cacbbbd2838ff0996d4723f049a2c9e\"",
"id": "a0ca6a90-a365-4782-871e-d44447bbc668!28430982-37ee-4492-9cef-dc94a7807211",
"remoteItem": {
"eTag": …
```
=> [full-ci] Fix shares graph

changelog/unreleased/graph-patch-mail.md, graph/pkg/service/v0/users.go
Skip the mail validator if 'mail' attribute is not present in the request.
See https://github.com/owncloud/ocis/issues/3167#issuecomment-1076296242
- manually
=> graph: Allow PATCH on user without 'mail' in body

graph/pkg/service/v0/groups.go, graph/pkg/service/v0/users.go
Fix a possible panic when checking for missing attribute ('err' was used
without actually being set). Return more helpful messages when required
attributes of a user or group are missing.
See https://github.com/owncloud/ocis/issues/3167#issuecomment-1078866841
=> graph: Fix handling of required attributes for users and groups

changelog/unreleased/update-reva.md, go.mod, go.sum
=> [full-ci] update reva to v2.1.0

changelog/unreleased/graph-user-sort.md, graph/pkg/service/v0/drives.go, graph/pkg/service/v0/groups.go, graph/pkg/service/v0/ordering.go, graph/pkg/service/v0/users.go
The GraphAPI endpoints for users and groups support ordering now.
User can be ordered by displayName, onPremisesSamAccountName and mail.
Groups can be ordered by displayName.
Example: https://localhost:9200/graph/v1.0/groups?$orderby=displayName asc
- Fixes #3360
- manually
=> Add sorting to GraphAPI users and groups

changelog/unreleased/fix-ocs-config-values.md, storage/pkg/command/frontend.go
together with https://github.com/cs3org/reva/pull/2692/files, we now return the same (weird / wrong) info as oC10:
oCIS /ocs/v2.php/config
```xml
<ocs>
<meta>
<status>ok</status>
<statuscode>200</statuscode>
<message>OK</message>
</meta>
<data>
<version>1.7</version>
<website>ownCloud</website>
<host>localhost:9200</host>
<contact/>
<ssl>false</ssl>
</data>
</ocs>
```
https://cloud.owncloud.com/ocs/v2.php/config:
```xml
<ocs>
<meta>
<status>ok</status>
<statuscode>200</statuscode>
<message/>
<totalitems/>
<itemsperpage/>
</meta>
<data>
<version>1.7</version>
<website>ownCloud</website>
<host>cloud.owncloud.com</host>
<contact/>
<ssl>false</ssl>
</data>
</ocs>
```
- Related to https://github.com/owncloud/ocis/issues/1338
=> ensure the same data on /ocs/v?.php/config like oC10 [full-ci]

changelog/1.19.1_2022-03-29/fix-special-urls.md, graph/pkg/service/v0/driveitems.go, sonar-project.properties
This is a bugfix for release 1.19.0
https://github.com/owncloud/ocis/issues/3377
=> fix special urls, prepare changelog, bump version

docs/ocis/release_notes.md
- Release Notes for 1.19.1
- Release Notes for 1.19.0
Related #3377
=> Release Notes 1.19.0

changelog/unreleased/make-config-dir-configurable.md, ocis-pkg/config/helpers.go
We have added an `OCIS_CONFIG_DIR` environment variable the will take precedence over the default `/etc/ocis`, `~/.ocis` and `.config` locations. When it is set the default locations will be ignored and only the configuration files in that directory will be read.
=> Make config dir configurable via `OCIS_CONFIG_DIR` env var

tests/acceptance/features/apiSpaces/changeSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
Created test:
- check the contents of the readmi file
- space image check
- set a new readmi file description
- set a new space image
I added test after bug with url https://github.com/owncloud/ocis/issues/3419.  The test passes, despite the url error, because we strictly set the url in the test.
=> [tests-only] apiTests: getting readmi file and spaceImage file

.drone.env
Routine core commit id bump for tests
- Part of: https://github.com/owncloud/QA/issues/736
- CI
=> [tests-only][full-ci] Bump core commit id for tests

.drone.star, accounts/pkg/service/v0/service.go
I don't think that the high hash difficulty is in any way relevant for CI and that we can save some time by reducing it.
Also reduced the hash difficulty for the demo users in case any of them is used in the CI. 
This doesn't introduce any security risk since a production setup shouldn't use the demo users nor the default passwords.
=> reduce hash difficulty in CI and of demo users

.drone.star
Fix incorrect variable assignment when adding pipelines.
- test case 1:
- test case 2:
- ...
=> [tests-only] fix variable overwrite

changelog/unreleased/update-reva.md, go.mod, go.sum
Update reva to latest edge as preparation to the release
=> [full-ci] update reva

ocis/pkg/command/kill.go, ocis/pkg/command/list.go, ocis/pkg/command/run.go
Improves the error message for following commands if the runtime is not started / reachable:
- ocis list
- ocis kill
- ocis run
The error message now looks like this: `Failed to connect to the runtime. Is the runtime running and did you configure the right runtime address ("localhost:9250")`
- Fixes [Fix error message when the runtime has not started but you file a command for it](https://github.com/owncloud/ocis/issues/3458)
Make oCIS commands more human friendly
- locally
=> improve runtime connect error messages

.drone.star, .vscode/launch.json, accounts/pkg/config/defaults/defaultconfig.go, changelog/unreleased/no-demo-users.md, deployments/examples/oc10_ocis_parallel/.env, deployments/examples/oc10_ocis_parallel/docker-compose.yml, deployments/examples/ocis_hello/.env, deployments/examples/ocis_hello/docker-compose.yml, deployments/examples/ocis_individual_services/.env, deployments/examples/ocis_individual_services/docker-compose.yml, deployments/examples/ocis_keycloak/.env, deployments/examples/ocis_keycloak/docker-compose.yml, deployments/examples/ocis_ldap/.env, deployments/examples/ocis_ldap/docker-compose.yml, deployments/examples/ocis_s3/.env, deployments/examples/ocis_s3/docker-compose.yml, deployments/examples/ocis_traefik/.env, deployments/examples/ocis_traefik/docker-compose.yml, deployments/examples/ocis_wopi/.env, deployments/examples/ocis_wopi/docker-compose.yml, docs/ocis/deployment/_index.md, docs/ocis/getting-started/_index.md, docs/ocis/getting-started/demo-users.md, idm/pkg/config/defaults/defaultconfig.go
Disable the creation of the demo users by default
- Fixes #3181 
- Strengthen the security
- CI
- Manually
=> [full-ci] set demo users to default off

changelog/unreleased/change-replace-deprecated-substr, changelog/unreleased/enhancement-replace-deprecated-substr, idp/ui/src/containers/Login/Chooseaccount.js, idp/ui_config/paths.js, settings/ui/components/SettingsBundle.vue
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated
I tested the return of each statement to make sure it's still the same as before
=> refactor: replace deprecated String.prototype.substr()

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
- Part of: https://github.com/owncloud/QA/issues/736
- CI
=> [full-ci][tests-only] Bump core commit id for tests

docs/architecture/services-communication.md, docs/extensions/storage/_index.md, docs/extensions/storage/namespaces.md, docs/extensions/storage/spaces.md, docs/extensions/storage/spacesprovider.md, docs/extensions/storage/spacesregistry.md, docs/extensions/storage/terminology.md, docs/ocis/_index.md, docs/ocis/adr/0014-microservices-runtime.md, docs/ocis/config.md, docs/ocis/deployment/monitoring-tracing.md, docs/ocis/flow-docs/public-upload-flow.md
SVG images on owncloud.dev regularly exceeded the available display space. But there is no working "width=100%" constraint for the svg tag.
Therefore this PR uses the "figure" tag instead which already ensures that the image does not exceed the page space (width)
- supersedes / closes #3447
Also show SVGs completely on small screens
- `make -C docs docs-serve`
=> ensure svg width does not exceed the page space

docs/ocis/release_notes.md
=> [docs-only] oCIS 1.20.0 release notes

.drone.star, changelog/unreleased/single-file-edit.md, deployments/examples/oc10_ocis_parallel/docker-compose.yml, extensions/storage/pkg/command/frontend.go, extensions/storage/pkg/command/sharing.go, go.mod, go.sum
Enhancement: Add capability for public link single file edit
It is now possible to share a single file by link with edit permissions. Therefore we need a public share capability to enable that feature in the clients. At the same time we improved the WebDAV permissions for public links.
- Uses https://github.com/cs3org/reva/pull/2743
- Uses https://github.com/owncloud/web/pull/6787
- manually
=> [full-ci] update reva and add capability

changelog/unreleased/ocs-cs3-fatal.md, extensions/ocs/pkg/service/v0/users.go
The ocs API was just exiting with a fatal error on any update request,
when configured for the cs3 backend. Now it returns a proper error.
Closes: #3483
=> return proper errors when ocs/cloud/users is using the cs3 backend

tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
https://github.com/owncloud/ocis/pull/3556 bumped middleware version and there was a passing test, This PR removes the passing test from expected to fail.
a similar thing was done on web recently: https://github.com/owncloud/web/pull/6794
- CI
=> [tests-only][full-ci] Remove passing test from expected to fail

changelog/unreleased/update-linkshare-capabilities.md, extensions/storage/pkg/command/frontend.go
We discovered while working on https://github.com/owncloud/web/pull/6749 that oCIS announces passwords as enforced (which they aren't) and expiration dates as not enabled (which they are) for public links. This PR updates capabilities so we can cleanup the web frontend implementation which has relied on weird workarounds before
=> Update password enforcement & expiration date capabilities for public links

changelog/unreleased/update-reva.md, go.mod, go.sum
Update reva after the merge of master into edge with full CI
- test case 1:
- test case 2:
- ...
=> [full-ci] Update reva to latest edge

.drone.star, .make/release.mk, changelog/unreleased/change-load-config-from-only-one-dir.md, docs/helpers/configenvextractor.go, docs/ocis/config.md, docs/ocis/deployment/systemd.md, ocis-pkg/config/defaults/paths.go, ocis-pkg/config/helpers.go, ocis/docker/Dockerfile.linux.amd64, ocis/docker/Dockerfile.linux.arm, ocis/docker/Dockerfile.linux.arm64
We've changed the configuration file loading behavior and are now only loading
configuration files from ONE single directory. This directory can be set on
compile time or via an environment variable on startup (`OCIS_CONFIG_DIR`).
We are using following configuration default paths:
- Docker images: `/etc/ocis/`
- Binary releases: `$HOME/.ocis/config/`
- Should be merged after #3569
- Unblocks #3551, because we can now write the initiated config file to the SINGLE known location. Before this PR, we wouldn't know where to write the config file.
- Part of https://github.com/owncloud/ocis/pull/3480, which tries to add also flags to specify config files directly
Make config file loading less confusing for users.
=> load configuration only from one directory

docs/ocis/deployment/oc10_ocis_parallel.md, docs/ocis/deployment/ocis_hello.md, docs/ocis/deployment/ocis_individual_services.md, docs/ocis/deployment/ocis_keycloak.md, docs/ocis/deployment/ocis_ldap.md, docs/ocis/deployment/ocis_s3.md, docs/ocis/deployment/ocis_traefik.md, docs/ocis/deployment/ocis_wopi.md
Describes how to add hosts to the hosts file on Windows
- test case 1:
- test case 2:
- ...
=> Document C:\Windows\System32\Drivers\etc\hosts

changelog/unreleased/urlencoding-graph-api.md, extensions/graph/pkg/service/v0/driveitems.go
URL encode the webdav URL in the drives responses.
- Fixes https://github.com/owncloud/ocis/issues/3538
When a file name contains spaces the resulting URL would contain spaces and subsequent requests could fail because of that.
- test environment: locally
- Via the graph-explorer
-
=> url encode the webdav URL in the graph API

extensions/graph/pkg/service/v0/drives.go
- test case 1:
- test case 2:
- ...
=> [tests-only] Unescape path in graph getdrive

extensions/gateway/pkg/command/command.go
=> add storageproviderids to config

changelog/unreleased/idp-cert-wait.md, extensions/idp/pkg/service/v0/service.go
Upon first start with the default configurtation the idm service creates
a server certificate, that might not be finished before the idp service
is starting. Add a check to idp similar to what the user, group, and
auth-providers implement.
Fixes: #3623
=> idp: Check if CA cert if present

changelog/unreleased/libregraph-idm-switch.md, extensions/web/pkg/config/defaults/defaultconfig.go, extensions/web/pkg/service/v0/service.go
The switch to libregraph/idm happend we can enable the new UI.
=> Enable user-management webui

changelog/unreleased/graph-me-drives.md, changelog/unreleased/update-reva.md, extensions/audit/pkg/service/service_test.go, extensions/audit/pkg/types/conversion.go, extensions/graph/pkg/service/v0/drives.go, extensions/graph/pkg/service/v0/graph_test.go, extensions/graph/pkg/service/v0/service.go, go.mod, go.sum, tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/expected-failures-graphAPI-on-OCIS-storage.md, tests/acceptance/features/bootstrap/SpacesContext.php
This combines
- #3624 
- #3629 
- test case 1:
- test case 2:
- ...
=> [full-ci] Bump reva  & merge unrestrict combined

.drone.star, changelog/unreleased/align-service-naming.md, extensions/group/pkg/config/defaults/defaultconfig.go, extensions/storage-shares/pkg/config/defaults/defaultconfig.go, ocis-pkg/config/config.go, ocis/pkg/runtime/service/service.go
We now reflect the configured service names when listing them in the ocis runtime.
Follow up PRs:
- always use the correct service names in the `.drone.star` file `OCIS_RUN_EXTENSIONS`
partly fixes https://github.com/owncloud/ocis/issues/3603
=> Align service naming

changelog/unreleased/spaces-capabilities.md, changelog/unreleased/update-reva.md, extensions/frontend/pkg/command/command.go, extensions/frontend/pkg/config/config.go, extensions/frontend/pkg/config/defaults/defaultconfig.go
Adds new `share_jail` and `projects` feature flags to the `spaces` capability.
- Fixes https://github.com/owncloud/ocis/issues/3615
- related https://github.com/cs3org/reva/pull/2795
- needed for https://github.com/owncloud/web/pull/6593
Provide a switch to indicate to clients to still use the old user home webdav endpoint.
just in CI
=> Spaces capability feature flags

ocis/pkg/init/init.go
fixes a bug introduced with https://github.com/owncloud/ocis/pull/3606
=> fix service names in init

.vscode/launch.json, changelog/unreleased/metadata-gateway.md, ocis-pkg/config/config.go
`METADATA_USER_ID` was not routed to the env variable in the single process use case. 
Also added it to the launch.json
=> fix env variable for metadata user ID

docs/helpers/extractor.go.tmpl
This PR adds missing pointer types to the configextractor to generate markdown for the docs.
=> Add pointers to the config var extractor

.drone.env
Bump the core commit id for tests. The significant core test change was https://github.com/owncloud/core/pull/40004 but that PR refactored federation tests, which are not yet run in oCIS. So there are no changes needed to expected failures files.
https://github.com/owncloud/QA/issues/738
CI
=> [tests-only] Bump CORE_COMMITID

docs/helpers/extractor.go.tmpl
This PR replaces `;` by `<br/>`  when generating the config tables.
Fixes #3600
=> replace `;` by `<br/>`

extensions/webdav/pkg/service/v0/service.go
Implement a workaround for `chi.RegisterMethod` for the webdav search.
- Fixes https://drone.owncloud.com/owncloud/ocis/11281/38/5
chi.RegisterMethod writes to a global map. Other parts of chi read that map and since we start multiple chi router in different goroutines we concurrently read/write to the map which is not valid and results in panics
- test environment: locally via curl 
```
curl -X REPORT -k https://localhost:9200/remote.php/dav/files/admin -i -u 'admin:.AT*+DatuZlfO!QS@TAyF5#EKz68fd0%'
HTTP/1.1 400 Bad Request
Cache-Control: no-cache, no-store, max-age=0, must-revalidate, value
Content-Length: 209
Content-Security-Policy: frame-ancestors 'none'
Content-Type: application/xml; charset=utf-8
Date: Tue, 03 May 2022 14:37:50 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT …
```
=> implement workaround for chi.RegisterMethod

changelog/unreleased/change-ocis-docker-volume-permissions.md, ocis/docker/Dockerfile.linux.amd64, ocis/docker/Dockerfile.linux.arm, ocis/docker/Dockerfile.linux.arm64
- reduce volume permissions
- update alpine base image
- test case 1:
- test case 2:
- ...
=> reduce docker image volume permissions and update alpine

changelog/unreleased/new-space-id-functions.md, extensions/audit/pkg/types/conversion.go, extensions/graph/pkg/service/v0/driveitems.go, extensions/graph/pkg/service/v0/drives.go, extensions/thumbnails/pkg/service/grpc/v0/service.go, extensions/thumbnails/pkg/thumbnail/imgsource/cs3.go, go.mod, go.sum
Changed code to use the new space ID util functions so that everything works with the new spaces ID format.
We had multiple functions to parse or format the storage space id.
When we recently changed the format of the storage space id some places broke. Instead of just fixing the broken things locally I replaced it with the correct implementation from the Reva package. This package is used everywhere and will hopefully be kept compatible to the changing formats.
This will also fix thumbnails in spaces.
Needs this Reva PR first: https://github.com/cs3org/reva/pull/2816.
- test environment: locally
=> [full-ci] use new space ID util functions

changelog/unreleased/new-space-id-functions.md, extensions/thumbnails/pkg/service/grpc/v0/service.go, extensions/thumbnails/pkg/thumbnail/imgsource/cs3.go, extensions/webdav/pkg/service/v0/service.go
Fix thumbnails requests with full spaces reference (`<providerid>$<spaceid>!<nodeid>`).
=> reduce hacky reference handling in thumbnailer

extensions/proxy/pkg/config/config.go, ocis-pkg/config/config.go, ocis/pkg/init/init.go
We are going to treat yaml tags as lower case env vars. There should never be a `-` in the yaml tag. This PR changes all `-` to `_`, even when that will prevent finding service names like `auth-basic` when grepping the config, because it will be called `auth_basic`. The same applies to env vars where the prefix is `AUTH_BASIC_` for all env vars of the `auth-basic` service.
=> make yaml tags always use underscore

.drone.star, .vscode/launch.json, changelog/unreleased/change-ocis-init.md, extensions/idm/ldif/base.ldif.tmpl, extensions/idm/pkg/command/server.go, extensions/idm/pkg/config/parser/parse.go, extensions/settings/pkg/config/parser/parse.go, extensions/settings/pkg/service/v0/service.go, extensions/settings/pkg/service/v0/settings.go, extensions/settings/pkg/store/defaults/defaults.go, extensions/settings/pkg/store/metadata/assignments.go, extensions/settings/pkg/store/metadata/assignments_test.go, extensions/settings/pkg/store/metadata/store.go, ocis-pkg/config/config.go, ocis-pkg/config/parser/parse.go, ocis-pkg/shared/errors.go, ocis-pkg/shared/shared_types.go, ocis/pkg/init/init.go
The UUID is generated by `ocs init` now and stored in the config file. To avoid that every ocis install uses the same UUID
- Fixes #3524
=> Get rid of hardcoded admin user uuid

.vscode/launch.json
This PR adds the missing `OCIS_SYSTEM_USER_API_KEY` to  `launch.json`
=> fix missing system user api key

docs/extensions/notifications/_index.md, extensions/notifications/pkg/config/config.go, extensions/notifications/pkg/config/defaults/defaultconfig.go
- added abstract
- dropped default password
- used neutral email
- added some descriptions
=> update notifications docs

docs/helpers/adoc-generator.go.tmpl
Prepends `\` to http defaults in adoc generation
Refs #3686
=> prepend http by  in adoc generator

tests/acceptance/expected-failures-webUI-on-OCIS-storage.md, tests/config/drone/ocis-config.json
Sets shares in the sidebar to "extended" in the drone web config to remove an expected failure
=> Extend shares in web sidebar in CI

changelog/unreleased/fix-thumbnails-dav.md, extensions/proxy/pkg/config/config.go, extensions/proxy/pkg/config/defaults/defaultconfig.go, extensions/proxy/pkg/middleware/basic_auth.go, extensions/webdav/pkg/constants/constants.go, extensions/webdav/pkg/dav/requests/thumbnail.go, extensions/webdav/pkg/service/v0/service.go
adds more routes to the proxy for thumbnail previews.
also adds omitempty to the routes config struct, to slim down the configuration example in https://owncloud.dev/extensions/proxy/configuration/
- fixes https://github.com/owncloud/ocis/issues/3558
- locally
=> add more proxy routes for thumbnails

docs/helpers/adoc-generator.go.tmpl, docs/templates/ADOC.tmpl
This PR fixes a small bug resulting in a broken output of the adoc rendering because of unescaped `|`.
Also an unneeded line wrap is removed.
Fixes #3711
=> escape adoc pipe & remove linewrap in output

.drone.env
becaue core PR https://github.com/owncloud/core/pull/40058 has been merged.
https://github.com/owncloud/QA/issues/738
CI
=> [tests-only] [full-ci] Change back to commit id on core master

changelog/unreleased/fix-configure-idp-secrets-env.md, extensions/idp/pkg/config/config.go
Bugfix: Make IDP secrets configurable via environment variables
We've fixed the configuration options of the IDP to make the IDP secrets again
configurable via environment variables.
- test case 1:
- test case 2:
- ...
=> expose IDP secret configuration via environment variables

changelog/unreleased/graph-explorer-env-doc.md, extensions/graph-explorer/pkg/config/http.go, extensions/graph-explorer/pkg/config/log.go, extensions/graph-explorer/pkg/config/tracing.go
Added descriptions tags to the graph-explorer config tags so that they will be included in the documentation.
/cc @mmattel
=> add description tags to graph-explorer config

.drone.star
remove dependencies from nightly example deploys to ensure they run even if tests fail, like eg. https://drone.owncloud.com/owncloud/ocis/11690
- test case 1:
- test case 2:
- ...
=> remove dependencies from nightly example deploys

extensions/search/pkg/search/index/index.go, extensions/search/pkg/search/index/index_test.go, extensions/search/pkg/search/mocks/IndexClient.go, extensions/search/pkg/search/provider/events.go, extensions/search/pkg/search/provider/events_test.go, extensions/search/pkg/search/provider/searchprovider.go, extensions/search/pkg/search/provider/searchprovider_test.go, extensions/search/pkg/search/search.go, extensions/search/pkg/service/v0/service.go
This PR fixes a problem when searching in sharey by making the search results relative to the mountpoint space instead of the grant space.
It also adds more debug logs and changes the search to still continue and return whatever it can find in case there's a problem searching within one space.
Fixes #3701
Fixes #3700
=> More fixes to searching in shares

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
https://github.com/owncloud/QA/issues/739
CI
=> [tests-only] [full-ci] Bump CORE_COMMITID for tests

changelog/unreleased/share-jail-fixes.md, extensions/webdav/pkg/dav/requests/thumbnail.go, extensions/webdav/pkg/service/v0/service.go
Bugfix: Fix Thumbnails for IDs without a trailing path
The routes in the chi router were not matching thumbnail requests without a trailing path.
- Fixes #3760 
- test case 1:
- test case 2:
- ...
=> fix thumbnails for empty trailing paths

extensions/search/pkg/search/index/index.go, extensions/search/pkg/search/index/index_test.go, extensions/search/pkg/search/mocks/IndexClient.go, extensions/search/pkg/search/provider/events.go, extensions/search/pkg/search/provider/events_test.go, extensions/search/pkg/search/provider/searchprovider.go, extensions/search/pkg/search/provider/searchprovider_test.go, extensions/search/pkg/search/search.go, extensions/webdav/pkg/service/v0/search.go
This PR fixes a few smaller issues with the file search like searching for files or directories with spaces or digits and enables advanced search features. In addition to the plain filename search it is now possible to specify search criteria on metadata as well, e.g.
1. Search for files small than 100 bytes
`size:<100`
1. Search for pdfs that were modified after May 11th
`+name:*pdf +mtime:>"2022-05-11"`
=> Improve search

changelog/unreleased/fix-app-provider-unused-transfer-secret.md, extensions/app-registry/pkg/config/parser/parse.go
We've fixed the startup of the app provider by removing the startup dependency
on a configured transfer secret, which was not used. This only happend if you
start the app provider without runtime (eg. `ocis app-provider server`) and didn't
have configured all oCIS secrets.
- Fixes startup of the app provider in https://github.com/owncloud/ocis-charts/pull/43
only have dependencies on secrets that are needed
- none
=> remove unused transfer secret from app provider

changelog/unreleased/fix-search-grpc-addr-env.md, extensions/search/pkg/config/grpc.go
We've fixed the gprc server address configuration environment variable by renaming it from
`ACCOUNTS_GRPC_ADDR` to `SEARCH_GRPC_ADDR`
WARNING: this could be considered as a breaking change!?
- Needed for https://github.com/owncloud/ocis-charts/pull/43
- none
=> Bugfix: Rename the search extensions environment variable for the grpc server address

extensions/app-provider/pkg/config/config.go, extensions/app-registry/pkg/config/config.go, extensions/audit/pkg/config/config.go, extensions/auth-basic/pkg/config/config.go, extensions/auth-bearer/pkg/config/config.go, extensions/auth-machine/pkg/config/config.go, extensions/frontend/pkg/config/config.go, extensions/gateway/pkg/config/config.go, extensions/graph-explorer/pkg/config/config.go, extensions/graph/pkg/config/config.go, extensions/groups/pkg/config/config.go, extensions/idm/pkg/config/config.go, extensions/idp/pkg/config/config.go, extensions/nats/pkg/config/config.go, extensions/notifications/pkg/config/config.go, extensions/ocdav/pkg/config/config.go, extensions/ocs/pkg/config/config.go, extensions/proxy/pkg/config/config.go, extensions/search/pkg/config/config.go, extensions/settings/pkg/config/config.go, extensions/sharing/pkg/config/config.go, extensions/storage-publiclink/pkg/config/config.go, extensions/storage-shares/pkg/config/config.go, extensions/storage-system/pkg/config/config.go, extensions/storage-users/pkg/config/config.go, extensions/store/pkg/config/config.go, extensions/thumbnails/pkg/config/config.go, extensions/users/pkg/config/config.go, extensions/web/pkg/config/config.go, extensions/webdav/pkg/config/config.go
Removes the composition of the `Commons` config, since it is not used and confusing to devs and produces undesirable IDE autocompletion.
`Commons` should only be used:
- in ./ocis or ./ocis-pkg to copy common configuration into the Commons struct
- in ./extensions/xxx to copy configuration out of the Commons struct
- Needs https://github.com/owncloud/ocis/pull/3799 first
- Needs https://github.com/owncloud/ocis/pull/3798 first
Removes undesired IDE autocompletion
-
=> remove composition of Commons

changelog/unreleased/fix-storage-users-config.md, extensions/storage-users/pkg/config/config.go
We've fixed multiple environment variable configuration options for the storage-users extension:
* `STORAGE_USERS_GRPC_ADDR` was used to configure both the address of the http and grpc server.
This resulted in a failing startup of the storage-users extension if this config option is set,
because the service tries to double-bind the configured port (one time for each of the http and grpc server). You can now configure the grpc server's address with the environment variable `STORAGE_USERS_GRPC_ADDR` and the http server's address with the environment variable `STORAGE_USERS_HTTP_ADDR`
* `STORAGE_USERS_S3NG_USERS_PROVIDER_ENDPOINT` was used to configure the permissions service endpoint for the S3NG driver and was therefore renamed to `STORAGE_USERS_S3NG_PERMISSIONS_ENDPOINT`
* It's now …
=> Bugfix: Fix multiple configuration environment variables for the storage-users extension

deployments/examples/oc10_ocis_parallel/docker-compose.yml, deployments/examples/ocis_hello/docker-compose.yml, deployments/examples/ocis_ldap/docker-compose.yml, deployments/examples/ocis_s3/docker-compose.yml, deployments/examples/ocis_traefik/docker-compose.yml, deployments/examples/ocis_wopi/docker-compose.yml
setting the environment variable OCIS_INSECURE=true breaks the graph api ldaps connection because GRAPH_LDAP_INSECURE needs always be true, since we have a ldaps connection to the idm and don't use the ca cert in the graph extension
As a workaround for our deployment examples we set:
```
OCIS_INSECURE: "${INSECURE:-false}"
GRAPH_LDAP_INSECURE: true
```
=> workaround ldaps insecure bind for graph https://github.com/owncloud/ocis/issues/3812

docs/ocis/development/beta-testplan.md
The abilitiy to add users via /ocs was removed in ocs. Also the accounts service no longer exists.
=> [docs-only] beta-testplan: Adjust curl examples to use graph instead of accounts/ocs

tests/acceptance/features/apiSpaces/download.feature, tests/acceptance/features/apiSpaces/listSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
=> ApiTest. download files

docs/architecture/protocol-changes.md
@dragotin @mmattel I wanted to get this off my uncommited doc / diagram list. Might be worth a blog post to go into the detail of what clients can expect and what the payload of these requests and responses looks like.
The proxy is left out as it only forwards requests to specific storage providers. We could use example urls with different hosts to indicate that the spaces can be located on different hosts.
I would like to add a sequence diagram for what happens on the server side as well, but this should be a starting point for client developers ... hm we coulvd add examples below it ... and link to https://owncloud.dev/libre-graph-api/#/me.drives/ListMyDrives
=> [docs-only] add client protocol overview

changelog/unreleased/fix-remove-legacy-accounts-routes.md, deployments/examples/oc10_ocis_parallel/config/ocis/proxy.yaml, deployments/examples/ocis_hello/config/ocis/proxy.yaml, extensions/proxy/pkg/config/defaults/defaultconfig.go, tests/parallelDeployAcceptance/drone/ocis/proxy.yaml
Bugfix: remove legacy accounts proxy routes
We've removed the legacy accounts routes from the proxy default config.
There were no longer used since the switch to IDM as the default user
backend. Also accounts is no longer part of the oCIS binary and therefore
should not be part of the proxy default route config.
+ update routes on the deployments (fixes login error into oCIS in the parallel deployment)
- test case 1:
- test case 2:
- ...
=> proxy config revamp

deployments/examples/oc10_ocis_parallel/docker-compose.yml, deployments/examples/ocis_hello/docker-compose.yml, deployments/examples/ocis_ldap/docker-compose.yml, deployments/examples/ocis_s3/docker-compose.yml, deployments/examples/ocis_traefik/docker-compose.yml, deployments/examples/ocis_wopi/docker-compose.yml
`docker-compose up` inside deployments/examples give this error:
```bash
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.ocis.environment.GRAPH_LDAP_INSECURE contains true, which is an invalid type, it should be a string, number, or a null
```
This PR fixes the error by enclosing boolean value into string.
=> [deployments] Enclose boolean with string in docker-compose env

changelog/unreleased/enhancement-registry-cache.md, ocis-pkg/registry/registry.go
Enhancement: Introduce service registry cache
We've improved the service registry / service discovery by
setting up registry caching (TTL 20s), so that not every requests
has to do a lookup on the registry.
- none
- don't put too much pressure on the service registry
- speed up requests (since a registry lookup takes time)
- ci
=> introduce service registry cache

extensions/storage-system/pkg/config/config.go
add missing `OCIS_SYSTEM_USER_ID` config environmnt variable to storage-system
- test case 1:
- test case 2:
- ...
=> add `OCIS_SYSTEM_USER_ID` environment variable to the storage-system configuration

changelog/unreleased/idp-directly-use-cs3-to-authenticate.md, extensions/idp/pkg/backends/cs3/bootstrap/cs3.go, extensions/idp/pkg/backends/cs3/identifier/cs3.go, extensions/idp/pkg/backends/cs3/identifier/session.go, extensions/idp/pkg/backends/cs3/identifier/user.go, extensions/idp/pkg/config/config.go, extensions/idp/pkg/config/defaults/defaultconfig.go, extensions/idp/pkg/config/parser/parse.go, extensions/idp/pkg/config/reva.go, extensions/idp/pkg/service/v0/service.go, go.mod, go.sum
The IDP now directly authenticates users using the CS3 API instead of LDAP.
=> IDP: allow using cs3 api to authenticate users

changelog/unreleased/update-reva.md, go.mod, go.sum, tests/acceptance/expected-failures-API-on-OCIS-storage.md
bump reva to 80f88dfbc02d to include https://github.com/cs3org/reva/pull/2884 and https://github.com/cs3org/reva/pull/2883
```
runsh: Total unexpected passed scenarios throughout the test run:
apiShareReshareToShares2/reShareSubfolder.feature:178
apiShareReshareToShares2/reShareSubfolder.feature:179
apiShareReshareToShares3/reShareUpdate.feature:61
apiShareReshareToShares3/reShareUpdate.feature:62
apiShareUpdateToShares/updateShare.feature:131
apiShareUpdateToShares/updateShare.feature:132
apiShareUpdateToShares/updateShare.feature:133
apiShareUpdateToShares/updateShare.feature:134
apiShareUpdateToShares/updateShare.feature:135
apiShareUpdateToShares/updateShare.feature:136
apiShareUpdateToShares/updateShare.feature:155
apiShareUpdateToShares/updateShare.feature:156 …
```
=> update reva to v2.3.2-0.20220519173447-80f88dfbc02d

extensions/idp/pkg/config/defaults/defaultconfig.go
We currently have an [issue in web](https://github.com/owncloud/web/issues/7030) which causes a hard page load / redirect to the personal space view after token expiry / during token refresh. Fixing the issue in web is quite some work as it involves a lot of loose ends (see linked ticket). In order to mitigate this annoying behaviour I'd like to increase the access token duration to 1 day.
Do we need a changelog item for this?
Is 10 minutes a conscious decision / reasonable value? Or do we want to have e.g. 30 or 60 minutes when we fixed the issue in web and can revert to a smaller value again here?
- Related to https://github.com/owncloud/web/issues/7030
Mitigate an annoying redirect during token refresh.
=> Increase access token duration to 1 day

changelog/unreleased/update-reva.md, go.mod, go.sum
- test case 1:
- test case 2:
- ...
=> [full-ci] update reva to 2.4.0

deployments/examples/oc10_ocis_parallel/testing/docker-compose-additions.yml
In the tests,  `LDAP_GROUP_BASE_DN` and `LDAP_USER_BASE_DN` are different than `ou=groups,dc=owncloud,dc=com` and `ou=users,dc=owncloud,dc=com` respectively. Due to this, running parallel deployment tests locally was not possible.
In this PR, I have added LDAP_GROUP_BASE_DN and LDAP_USER_BASE_DN with necessary values to the `testing/docker-compose-additions.yml`.
Running parallel deployment tests locally was not successful
=> [deployments] Add specific LDAP_GROUP_BASE_DN and LDAP_USER_BASE_DN needed for tests

docs/architecture/protocol-changes.md
I added a few sequence diagrams for PROPFIND requests with examples for the different webdav endpoints, proxy and gateway based sharding. This is conceptual and does not 100% accurately represent the payload on the wire. This is actually part of https://github.com/cs3org/reva/issues/2881
=> [docs-only] add PROPFIND sequence diagram examples

.drone.env
Update core commit id to the latest up to date `2022-05-25`
- Part of https://github.com/owncloud/QA/issues/742
- :robot:
=> [tests-only][full-ci] Bump core commit id to the latest upto 2022-05-25

docs/ocis/getting-started/_index.md
update getting started docs to use beta2
- test case 1:
- test case 2:
- ...
=> update getting started docs to beta2

docs/ocis/getting-started/_index.md
=> [docs-only] add docs for macOS ulimits

changelog/unreleased/fix-user-autoprovision.md, extensions/graph/pkg/middleware/auth.go
We can't use ReadPlainFromOpaque here since the OpaqueEntry entry is
"json" encoded (not "plain").
Fixes: #3893
=> graph: Fix role-id extraction from token

changelog/unreleased/fix-allow-empty-environment-variables, ocis-pkg/config/envdecode/envdecode.go
allow overwriting a default value by setting an empty enviornment variable
assuming, that you don't want to have a ldap ca cert, you may want to set `LDAP_CACERT=""`. This didn't work prior to this change.
- locally
=> allow overwriting a default value by setting an empty envirionment variable

changelog/unreleased/graph-cacert.md, extensions/graph/pkg/config/config.go, extensions/graph/pkg/config/defaults/defaultconfig.go, extensions/graph/pkg/service/v0/service.go
Added a config option to the graph service to provide a TLS certificate to be used to verify the LDAP server certificate.
Closes: https://github.com/owncloud/ocis/issues/3818
=> add config option to provide TLS certificate

.gitignore
The PHP dependencies of acceptance tests were moved into `vendor-php` some time ago. I  sometimes have them locally, and have to remember not to accidentally commit them with `git add -A`
Add them to `.gitgnore` so that they do not get accidentally committed.
Checked that my local vendor-php folder is now ignored.
=> [tests-only] Git ignore vendor-php

go.mod, go.sum, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
update ocis to include https://github.com/cs3org/reva/pull/2888, https://github.com/cs3org/reva/pull/2909, https://github.com/cs3org/reva/pull/2905, https://github.com/cs3org/reva/pull/2903 and https://github.com/cs3org/reva/pull/2907
=> [full-ci] update reva to v2.4.2-0.20220601110755-6b47effc3759

.drone.env
This gets the test code from https://github.com/owncloud/core/pull/40114 running in CI.
https://github.com/owncloud/QA/issues/742
CI
=> [tests-only] [full-ci] Bump core commit id for tests as at 2022-06-01

.drone.star, changelog/unreleased/fix-ldap-filter-envvar.md, deployments/examples/oc10_ocis_parallel/config/oc10/ldap-config.tmpl.json, deployments/examples/oc10_ocis_parallel/docker-compose.yml, deployments/examples/ocis_ldap/docker-compose.yml, docs/extensions/storage/users.md, extensions/auth-basic/pkg/config/config.go, extensions/groups/pkg/config/config.go, extensions/users/pkg/config/config.go, tests/parallelDeployAcceptance/drone/oc10/ldap-config.tmpl.json
There was a naming inconsitency for the enviroment variables used to define
LDAP filters for user and groups queries. Some services used `LDAP_USER_FILTER`
while others used `LDAP_USERFILTER`. This is now changed to use `LDAP_USER_FILTER`
and `LDAP_GROUP_FILTER`
Closes: #3890
=> Fix inconsistent env var naming for LDAP filter configuration

changelog/unreleased/graph-webdav-url.md, extensions/graph/pkg/service/v0/drives.go, extensions/graph/pkg/service/v0/graph_test.go
Fixed the webdav URL of drive roots in the graph API.
Fixes: https://github.com/owncloud/ocis/issues/3706
=> fix webdav URL of drive roots in graph API

changelog/unreleased/update-reva.md, go.mod, go.sum, tests/acceptance/expected-failures-API-on-OCIS-storage.md
bring https://github.com/cs3org/reva/pull/2919, https://github.com/cs3org/reva/pull/2904 and more to ocis
=> [full-ci] update reva to v2.4.2-0.20220607110316-1e461b750389

changelog/unreleased/update-reva.md, go.mod, go.sum
update to include https://github.com/cs3org/reva/pull/2918 and https://github.com/cs3org/reva/pull/2931
=> update reva to v2.5.1-0.20220608092821-954c578109df

changelog/unreleased/container-created-audit.md, extensions/audit/pkg/service/service.go, extensions/audit/pkg/types/constants.go, extensions/audit/pkg/types/conversion.go, extensions/audit/pkg/types/types.go
Handle the event `ContainerCreated` in the audit service.
=> handle event container created in audit service

changelog/unreleased/make-ocdav-service-behave.md, extensions/ocdav/pkg/command/server.go
The ocdav service now properly passes the tracing config and shuts down when receiving a kill signal.
=> Make ocdav service behave

changelog/unreleased/thumbnails-log.md, extensions/thumbnails/pkg/service/grpc/v0/decorators/logging.go
Reduced the log severity when no thumbnail was found from warn to debug.
This reduces the spam in the logs.
=> make thumbnails service log less noisy

changelog/unreleased/make-idp-only-wait-for-certs-when-using-ldap.md, extensions/idp/pkg/service/v0/service.go
When configuring cs3 as the backend the IDP no longer waits for an LDAP certificate to appear.
=> Make idp only wait for certs when using ldap

deployments/examples/ocis_wopi/config/wopiserver/entrypoint-override.sh, deployments/examples/ocis_wopi/docker-compose.yml
removes unused configuration options / code from the wopi deployment example
- Fixes irritation by unused code
- locally, docker-compose up -d
=> remove unused configuration options from the wopi deployment example

.drone.star, deployments/examples/oc10_ocis_parallel/docker-compose.yml
simplifies the ldap configuration of the parallel deployment and fixes some wrong configuration options. 
- test case 1:
- test case 2:
- ...
=> simplify and fix ldap configuration

changelog/unreleased/update-reva-beta.4.md, go.mod, go.sum, ocis-pkg/tracing/tracing.go
update reva to include
https://github.com/cs3org/reva/pull/2975 
https://github.com/cs3org/reva/pull/2974 
https://github.com/cs3org/reva/pull/2962
=> [full-ci] update reva to v2.5.2-0.20220616180355-84264e82e451

.drone.env
Includes new API test scenarios related to core oC10 issue https://github.com/owncloud/core/issues/40140
Note: those are test scenarios related to quota. Those are currently skipped on oCIS/reva test pipelines, because with the graphAPI for users/groups/spaces the quota concept will work differently. So actually the new test scenarios are not run in this CI, so we do not get any new results or unexpected failures.
https://github.com/owncloud/QA/issues/744
CI
=> [tests-only] [full-ci] Bump CORE_COMMITID for API tests

docs/templates/ADOC.tmpl
This PR adapts the antorra template for the env vars in extensions to ignore entries in curly brackets `{}`. Enforcing antorra not to try to render them as variables.
fixes #3969
=> advise antorra to ignore entries in curly brackets

changelog/unreleased/update-reva-beta.4.md, go.mod, go.sum
include 
https://github.com/cs3org/reva/pull/2987
https://github.com/cs3org/reva/pull/2985
https://github.com/cs3org/reva/pull/2984
=> [full-ci] update reva to v2.5.2-0.20220617105144-3b2537f536e0

extensions/sharing/pkg/config/defaults/defaultconfig.go, extensions/sharing/pkg/revaconfig/config.go
we now use the `cs3` drivers to persist user shares and public links
=> [full-ci] change default sharing driver to cs3

docs/helpers/adoc-generator.go.tmpl
Minor fix to the doc generator, makes adoc-generator escape links for antorra.
=> make adoc-generator escape links for antorra

deployments/examples/ocis_wopi/docker-compose.yml
updates both Collabora and OnlyOffice in the WOPI deployment example to have up to date versions. This needed config changes on both document servers.
- test case 1:
- test case 2:
- ...
=> update collabora and onlyoffice in the wopi deployment example

.github/ISSUE_TEMPLATE/bug_report.md
removes non existing environment variables from the bug template.
I see a lot of issues which say that oCIS is started with `STORAGE_FRONTEND_UPLOAD_DISABLE_TUS`, but that option doesn't even exist (and may not be obvious to all people)
- none
=> remove non existing env variables from bug template

deployments/examples/ocis_keycloak/.env, deployments/examples/ocis_keycloak/docker-compose.yml, docs/ocis/deployment/ocis_keycloak.md
- removes secrets from keycloak deployment example because we already call ocis init
- removes demo users settings from keyclok deployment example because the demo users come from keycloak
- 
have a clean example
- test case 1:
- test case 2:
- ...
=> remove secrets configuration and demo users from keycloak deployment example

extensions/graph/pkg/identity/ldap.go
`curl -ki  'https://localhost:9200/graph/v1.0/groups/?$expand=members' -u admin:admin`
did not properly expand group members for groups that just had a single member.
=> Fix `$expand=members` query for groups with just a single member

extensions/frontend/pkg/config/config.go
The config option descriptions for `EnableFavorites` and `EnableResharing` had said `Disable...` instead of `Enable ...`.
=> fix configuration descriptions

changelog/unreleased/idp-default-files.md, extensions/idp/pkg/command/server.go, extensions/idp/pkg/config/defaults/defaultconfig.go
Automatically generate the signing key and encryption secret when the idp service starts
- Fixes https://github.com/owncloud/ocis/issues/3909
oCIS can now be restarted without invalidating all existing user sessions.
- test environment: locally
- Start ocis and check the config directory of the idp service
- Log in with a user
- Restart ocis
- Refresh the browser window and verify that user is still logged in
=> idp automatically generates signing key and encryption secret

changelog/unreleased/migrate-command.md, ocis/pkg/command/migrate.go
This PR fixes a problem with the `migrate` command where the settings from the ocis configuration file were not being used.
=> Actually use the sharing configuration from the config file

tests/acceptance/expected-failures-API-on-OCIS-storage.md
This PR is to update the expected failure of search request with `REPORT` method. Previously all the request related to it were linked with issue `REPORT` method not implemented, but now those request gives `405` method not allowed.
isuue : https://github.com/owncloud/ocis/issues/4034
=> Expected to failure update for search request with REPORT method

deployments/examples/ocis_keycloak/docker-compose.yml
ocis was missing a config directory in the keycloak deployment example
- 
- test case 1:
- test case 2:
- ...
=> add ocis config volume to keycloak deployment example

changelog/unreleased/fix-csp-silent-refresh.md, services/web/pkg/middleware/silentrefresh.go
For a silent token renewal via iframe we need to allow `self` as frame ancestor.
If a refresh token exists (i.e. when `offline_access` is present in the requested scopes) this is not needed.
- Works towards https://github.com/owncloud/web/issues/7030
=> Allow self for iframes in web service

.drone.env, tests/acceptance/config/behat.yml, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpaces/search.feature, tests/acceptance/features/bootstrap/SpacesContext.php, tests/acceptance/features/bootstrap/TusContext.php
Changes in 2 PR. related with https://github.com/owncloud/core/pull/40174
- added tests for searches resources in the project space and shared jail 
- added fail in expected failures https://github.com/owncloud/ocis/issues/4014
=> ApiTest. search entity from project space and shares jail

changelog/unreleased/use-ldappassword-exop.md, go.mod, go.sum, services/graph/pkg/config/config.go, services/graph/pkg/config/defaults/defaultconfig.go, services/graph/pkg/identity/ldap.go, services/graph/pkg/identity/ldap/reconnect.go
By default the graph API will now use the LDAP Password Modify Extended
Operation for setting user passwords. By this we make sure that the
LDAP server can e.g. properly hash the password with and algorithm that
it supports.
This can be reverted to the old behaviour (using "normal" LDAP modify
requests) by setting GRAPH_LDAP_SERVER_USE_PASSWORD_MODIFY_EXOP=false
Fixes: #3778
=> Use LDAP Modify Password ExtOp for updating passwords

changelog/unreleased/fix-remove-unused-ocs-backend-config.md, deployments/examples/ocis_individual_services/docker-compose.yml, docs/helpers/environment-variable-docs-generator.go.tmpl, services/ocs/pkg/config/config.go, services/search/pkg/config/config.go
fixes open issues in https://github.com/owncloud/ocis/issues/3793#issuecomment-1171034214
- Fixes https://github.com/owncloud/ocis/issues/3793#issuecomment-1171034214
- `make -C docs docs-serve`
=> config descriptions reloaded

docs/ocis/development/getting-started.md
=> go 1.18 is required

changelog/unreleased/fix-sensitive-values-proxy-debug-config.md, go.mod, go.sum, ocis-pkg/shared/shared_types.go, services/proxy/pkg/config/config.go, services/proxy/pkg/config/debug.go, services/proxy/pkg/server/debug/server.go
`curl localhost:9205/config | jq .` returns some secrets prior this PR. Now it returns:
```json
{
"Commons": {
"Log": {
"Level": "",
"Pretty": false,
"Color": false,
"File": ""
},
"Tracing": {
"Enabled": false,
"Type": "",
"Endpoint": "",
"Collector": ""
},
"OcisURL": "",
"TokenManager": {
"JWTSecret": "************"
},
"Reva": null,
"MachineAuthAPIKey": "************",
"TransferSecret": "************",
"SystemUserID": "09fd4b5e-6fa8-4d56-9f51-10a91a1f0c04",
"SystemUserAPIKey": "************",
"AdminUserID": "af02240f-de66-4f30-a574-00bb8f3ad69b"
},
"Service": {
"Name": "proxy"
},
"Tracing": {
"Enabled": false,
"Type": "",
"Endpoint": "",
"Collector": ""
},
"Log": {
"Level": "",
"Pretty": false,
"Color": false,
"File": ""
},
"Debug": {
"Addr": "127.0.0.1:9205",
"Token": "",
"Pprof": …
```
=> mask sensitive values in /config proxy debug server endpoint

changelog/unreleased/fix-startup-error-logging.md, services/app-provider/pkg/command/server.go, services/app-registry/pkg/command/server.go, services/auth-basic/pkg/command/server.go, services/auth-bearer/pkg/command/server.go, services/auth-machine/pkg/command/server.go, services/frontend/pkg/command/server.go, services/gateway/pkg/command/server.go, services/graph-explorer/pkg/command/server.go, services/graph/pkg/command/server.go, services/groups/pkg/command/server.go, services/idp/pkg/command/server.go, services/nats/pkg/command/server.go, services/ocdav/pkg/command/server.go, services/ocs/pkg/command/server.go, services/proxy/pkg/command/server.go, services/search/pkg/command/server.go, services/sharing/pkg/command/server.go, services/storage-publiclink/pkg/command/server.go, services/storage-shares/pkg/command/server.go, services/storage-system/pkg/command/server.go, services/storage-users/pkg/command/server.go, services/store/pkg/command/server.go, services/thumbnails/pkg/command/server.go, services/users/pkg/command/server.go, services/web/pkg/command/server.go, services/webdav/pkg/command/server.go
improves startup error logging
- Fixes https://github.com/owncloud/ocis/issues/3460
- first start `ocis server` then start `ocis xxx server` and see a speaking error message
=> improve startup error logging

services/thumbnails/pkg/config/config.go
This typo fixes a minor typo in a variable description.
=> Fix typo in variable description

docs/helpers/adoc-generator.go.tmpl, docs/templates/ADOC.tmpl
Fixes: https://github.com/owncloud/ocis/issues/4097 (Some env content provided does not make it into the documentation)
Adding the `pass` macro for those two cells is neccessary because the content are go slices (arrays) which would be interpreted differently in Antora.
=> Update the adoc table generation

changelog/unreleased/polish-search.md, services/search/pkg/search/index/index.go, services/search/pkg/search/provider/searchprovider.go, services/search/pkg/service/v0/service.go, services/webdav/pkg/service/v0/search.go, tests/acceptance/expected-failures-API-on-OCIS-storage.md
This PR improves feedback when providing invalid queries and adds support for limiting the number of results returned.
Fixes #4016 
Fixes #4017
=> Polish search

docs/templates/ADOC.tmpl, services/frontend/pkg/config/config.go, services/thumbnails/pkg/config/config.go
Fixes: https://github.com/owncloud/ocis/issues/4097 (Some env content provided does not make it into the documentation)
* Compared to the default value where we use the antora `pass` macro, we cant use that macro here because of `[]text` which would render to `[text]`. To have the string correctly passed, we need to use plus symbols `+[]text+` which then renders correctly to `[]text`.
* The pass macro for the description was not correct because we escape html, removed.
* Fixed the text for the description when using arrays to describe the separators.
Note that the supported types at FRONTEND are described in the defaults, therefore removed.
=> Fix adoc type + text

.drone.env
Bump core commit id for tests (latest upto July 7, 2022)
- to include https://github.com/owncloud/core/pull/40180 from oC/core
- this pr will retry for requests with response HTTP status code 425
- expected to fix https://github.com/owncloud/ocis/issues/4091 async behaviour of etag propagation
- https://github.com/owncloud/ocis/issues/4091
- https://github.com/owncloud/QA/issues/748
=> [tests-only][full-ci] Update core commit id to the latest upto July 7, 2022

changelog/unreleased/fix-ocis-run-services.md, ocis-pkg/config/config.go
`OCIS_RUN_SERVICES` was introduced as successor to `OCIS_RUN_EXTENSIONS` because
we wanted to call oCIS "core" extensions services. We kept `OCIS_RUN_EXTENSIONS` for
backwards compatibility reasons.
It turned out, that setting `OCIS_RUN_SERVICES` has no effect since introduced. `OCIS_RUN_EXTENSIONS`.
`OCIS_RUN_EXTENSIONS` was working fine all the time.
We now fixed `OCIS_RUN_SERVICES`, so that you can use it as a equivalent replacement for `OCIS_RUN_EXTENSIONS`
-
- test case 1:
- test case 2:
- ...
=> fix `OCIS_RUN_SERVICES`

.drone.star
Issue #3023 caused an infinite loop in the back-end, so the related test scenario was skipped. PR #4076 has pulled in the fix from oCIS, so we can unskip the test now.
The actual fix was applied to reva edge in https://github.com/cs3org/reva/pull/3009
- Fixes #3023 
CI
=> [tests-only] [full-ci] Do not skip tests for issue-3023

tests/acceptance/features/apiSpaces/changeSpaces.feature, tests/acceptance/features/apiSpaces/deleteSpaces.feature, tests/acceptance/features/apiSpaces/download.feature, tests/acceptance/features/apiSpaces/filePreviews.feature, tests/acceptance/features/apiSpaces/listSpaces.feature, tests/acceptance/features/apiSpaces/quota.feature, tests/acceptance/features/apiSpaces/removeSpaceObjects.feature, tests/acceptance/features/apiSpaces/resharing.feature, tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature, tests/acceptance/features/apiSpaces/restoreSpaces.feature, tests/acceptance/features/apiSpaces/search.feature, tests/acceptance/features/apiSpaces/shareSpaces.feature, tests/acceptance/features/apiSpaces/shareSubItemOfSpace.feature, tests/acceptance/features/apiSpaces/shareSubItemOfSpaceViaPublicLink.feature, tests/acceptance/features/apiSpaces/uploadSpaces.feature, tests/acceptance/features/bootstrap/GraphContext.php, tests/acceptance/features/bootstrap/SpacesContext.php
- "creating project space" moved to background
- many scenarios are combined into one
- added test re-sharing to the group
=> ApiTests. refactoring apiSpace suite

docs/helpers/adoc-generator.go.tmpl
This PR fixes the doc templates to include slices properly in the adoc output.
fixes #4128 
closes #4128
=> fix adoc for slices

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpaces/shareSpaces.feature
- added api test for an issue https://github.com/owncloud/ocis/issues/4127
- test added to expected failures
=> ApiTest. owner does not see the space after deleting the access

.drone.star
To run:
- localApiTests
- coreApiTests
- parallelDeployment tests
we need `owncloud/core` & `owncloud/testing`
these are now cached at first and used as the cached artifact on the test pipeline.
- Fixes: https://github.com/owncloud/ocis/issues/4059
- have less unrelated errors on the CI
- :robot:
=> [tests-only] [full-ci] cache core repos for testing

services/settings/package.json, services/settings/yarn.lock
Package isn't needed anymore since https://github.com/owncloud/web/pull/7193 got merged. This should reduce the security warning (noise) on the NPM/JS side by a bit
=> [tests-only] Remove unused nightwatch-vrt dep

tests/acceptance/features/bootstrap/SpacesContext.php
In the after scenario of the local Api tests, a cleanup job is initialized to delete all spaces of the type `project`.
For this we do not need to remember the spaces (only needed in between of the tests not on the after Scenario).
If we have no `project` type spaces the Query API will return `{value: []}` which is not acceptable for the remember function `rememberTheAvailableSpaces`, due to which we see an unnecessary error as:
```console
╳  No drives were found on that endpoint
╳  Failed asserting that an array has the key 0.
│
└─ @AfterScenario # SpacesContext::cleanDataAfterTests()
```
With this PR:
- no more spaces cleanup. Why? cause the spaces for any users will be cleared when it is deleted. see https://github.com/owncloud/ocis/commit/f01d56fe5fef946eb523db8d31d8d49ff1c4e7ff. we …
=> [tests-only] remove dedicated spaces cleanup for the localAPI tests

services/search/pkg/config/config.go, services/search/pkg/config/defaults/defaultconfig.go
drone configures `GATEWAY_GRPC_ADDR=0.0.0.0:9142` while the default is `127.0.0.1:9142`. during testing the reva config might not be copied correctly.
this error
```
{"level":"error","service":"search","error":"error: not found: unknown client id","authRes":{"status":{"code":6,"message":"unknown client id","trace":"00000000000000000000000000000000"}},"time":"2022-07-12T11:52:06.978647891Z","message":"error using machine auth"}
{"level":"error","service":"search","error":"error: not found: unknown client id","time":"2022-07-12T11:52:06.978668069Z","message":"failed to stat the changed resource"}
```
is logged when the testsuite cleaned the user before the event could be consumed and acted upon. unrelated to this PR
=> fix search reva addr config parsing

changelog/unreleased/feature-optional-events-in-graph-service.md, services/graph/pkg/config/config.go, services/graph/pkg/server/http/server.go, services/graph/pkg/service/v0/graph.go
We've changed the graph service so that you also can start it without any
event bus.
Therefore you need to set `GRAPH_EVENTS_ENDPOINT` to an empty string.
The graph API will not emit any events in this case.
Test case:
Assumption: No events / nats service is running. Then:
- Running `ocis graph server` will not expose any api before this PR.
- When running `GRAPH_EVENTS_ENDPOINT="" ocis graph server` with this PR, the graph api will be exposed.
- 
Be able to start the graph service without any event bus.
=> make graph service events optional

deployments/examples/ocis_wopi/.env, deployments/examples/ocis_wopi/config/wopiserver/entrypoint-override.sh, deployments/examples/ocis_wopi/config/wopiserver/wopiserver.conf.dist, deployments/examples/ocis_wopi/docker-compose.yml, docs/ocis/deployment/ocis_wopi.md
after https://github.com/cs3org/wopiserver/commit/d9b241da81305dee037ed376e8d358ab88f79845, we can remove the IOP secret from our wopi example deployment. It is still configurable and could also be removed from the Code at some point in time
- test case 1:
- test case 2:
- ...
=> remove unused iopsecret from wopi example

.drone.star
The release process is 
1. create a branch 
2. bump version & prepare changelog 
3. commit version bump 
4. Create a pull request from release branch against master with full-ci
5. Tag 
6. merge the PR
Since we are already running full ci in step 4, it should not be necessary to run it fully in step 5.
This PR makes necessary changes so that we don't run full ci in tagging as well.
- Fixes: https://github.com/owncloud/ocis/issues/3630
- CI
=> [full-ci] [tests-only] Do not run full-ci on tagging

deployments/examples/ocis_ldap/docker-compose.yml, docs/ocis/deployment/ocis_ldap.md
The admin from the LDAP needs to be assigned to the ocis Admin Role.
- test case 1:
- test case 2:
- ...
=> [docs-only] fix ocis_ldap admin user

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpaces/copySpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
This PR adds `COPY` request implementation for copying `files` between different spaces (`Personal`, `Shares Jail`, `Project`)
https://github.com/owncloud/ocis/issues/4087
=> [tests-only][full-ci]Added test scenarios for copy Request

.drone.star
The `retry` script is already in the `nodejs` docker image. We do not need to fetch it from the `retry` repo.
See issue https://github.com/owncloud-ci/retry/issues/7
This is a follow-up of PR #4223 
CI
=> [tests-only] [full-ci] Do not fetch the retry script in CI

changelog/unreleased/exclude-services-option.md, ocis-pkg/config/config.go, ocis/pkg/runtime/service/service.go
Until now if one wanted to use a custom version of a service, one
needed to provide `OCIS_RUN_SERVICES` which is a list of all services to start.
Now one can provide `OCIS_EXCLUDE_RUN_SERVICES` which is a list of only services not to start
- test case 1:
- test case 2:
- ...
=> Allow providing list of services not to start

.drone.env, tests/acceptance/features/apiSpaces/copySpaces.feature, tests/acceptance/features/apiSpaces/shareSpacesViaLink.feature, tests/acceptance/features/apiSpaces/shareSubItemOfSpaceViaPublicLink.feature, tests/acceptance/features/bootstrap/SpacesContext.php
- added api tests.  
- for using some gerkin steps from core I created PR: https://github.com/owncloud/core/pull/40222
=> [tests-only] ApiTest. Share space via link

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpaces/moveSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
This PR adds various tests scenarios for `MOVE` within and with different spaces
This PR Depends on https://github.com/owncloud/ocis/pull/4126
Part of : https://github.com/owncloud/ocis/issues/4087
=> [tests-only][full-ci]Added implementation and Scenarios for `MOVE` request operation

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
after fixing https://github.com/owncloud/ocis/issues/4262 I deleted passed tests from expected failures
=> [tests-only] Remove passed tests from expected failures

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpaces/createFileFolderWhenSharesSpaceExist.feature
All the tests related to the `Shares` folder from core is to be implemented in ocis. This PR adds tests to create files and folders when space `Shares Jail` exists. Since `Shares` folder is not created on `OCIS` like as in `core`. Those Tests are shifted here. 
https://github.com/owncloud/ocis/issues/4154
https://github.com/owncloud/ocis/issues/3033
https://github.com/owncloud/core/pull/40239
I have not updated the expected to failure command. see this comment https://github.com/owncloud/ocis/issues/3033#issuecomment-1195214016
=> [tests-only][full-ci]Add Tests for creating Files and Folder When Space Shares Jail exists for core PR 40239

tests/acceptance/expected-failures-API-on-OCIS-storage.md
- Removed the closed issue #3880 occurrence from the expected failures list
- Assigned scenarios to respective open issues
- Part of https://github.com/owncloud/QA/issues/716
- :robot:
=> [tests-only] removed closed issue #3880 from expected failures list

tests/acceptance/expected-failures-API-on-OCIS-storage.md
- Remove closed issue #3167 from the list of the expected failures.
- Replaced with respective open issue
- Part of https://github.com/owncloud/QA/issues/716
- :robot:
=> [tests-only] remove closed issue #3167 from the list of expected failures

.drone.env, .drone.star, tests/acceptance/expected-failures-API-on-OCIS-storage.md
Brings in core PR https://github.com/owncloud/core/pull/40247 which removes an unwanted scenario from oCIS CI
Part of issue https://github.com/owncloud/QA/issues/753
CI
=> [tests-only] [full-ci] Bump commit id for core API tests

tests/acceptance/features/bootstrap/SpacesContext.php
This failed in drone CI:
https://drone.owncloud.com/owncloud/ocis/13901/42/8
```
runsh: Total unexpected failed scenarios throughout the test run:
apiSpaces/restoreSpaces.feature:63
apiSpaces/restoreSpaces.feature:64
```
```
Failed step: When user "Brian" restores a disabled space "restore a space" without manager rights
Notice: Undefined index: restore a space in /drone/src/tests/acceptance/features/bootstrap/SpacesContext.php line 270
```
Enhance the test code so that it checks for the existence of the array key, rather than just crashing like this.
Put the space name and username in single quotes in error messages. That will make messsages easier to understand. For example, "Undefined index: restore a space in..." - 'restore a space' is actually the name of the space, and that confused …
=> [tests-only] Enhance getSpaceByNameManager test code

tests/acceptance/docker/Makefile
My IDE noticed this. The `clean` target in `tests/acceptance/docker/Makefile` mentions `clean-files` but `clean-files` is not correctly defined.
What was broken because of this? Or what is going to break by fixing it?
CI
=> [tests-only] Fix clean-files target in tests/acceptance/docker/Makefile

changelog/unreleased/fix-search-in-received-shares.md, services/search/pkg/search/provider/searchprovider.go, services/search/pkg/search/provider/searchprovider_test.go
It apparently broke as a fallout of the shareid refactoring in reva.
/cc @micbar @JanAckermann
=> Fix search in received shares

.drone.star
- e2e tests will run at every PR and merge
- added `skipIfUnchanged`
- added tag [skip-e2e] so that we have the option of running CI without e2e test
=> Run e2e at every PR

changelog/unreleased/enhancement-access-token-validation.md, go.mod, go.sum, services/proxy/pkg/command/server.go, services/proxy/pkg/config/config.go, services/proxy/pkg/config/defaults/defaultconfig.go, services/proxy/pkg/config/parser/parse.go, services/proxy/pkg/middleware/authentication.go, services/proxy/pkg/middleware/oidc_auth.go, services/proxy/pkg/middleware/oidc_auth_test.go, services/proxy/pkg/middleware/options.go
Try to verify access_token as JWT and extract expiry
We try to parse the access token as a JWT now. Verifying the signature using the keys downloaded from the jwks_uri of the IDP. Currently we only use it to extract the expiry information from the JWT. This could be reworked to extract other claims from the token for authorization purposes.
=> Add access_token verification

services/frontend/pkg/revaconfig/config.go
We can't resolve alias links in Web yet, but creating those will be possible within the next few days. Hence we figured it would be best to temporarily set the alias link capability to `false` (see https://github.com/owncloud/web/pull/7133#issuecomment-1191287739).
=> Set the alias link capability to `false`

changelog/unreleased/fix-ldap-invalid-users-groups.md, services/graph/pkg/identity/ldap.go, services/graph/pkg/identity/ldap_test.go
We fixed an issue where ocis would exit with a panic when LDAP users or groups where missing required attributes (e.g. the id)
User and Groups missing any of the required attributes are now ignored.
- Fixes #4274
=> Fix handling of invalid LDAP users and groups

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpaces/changeSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
- added api test. for now user admin can change only own quota 
- if admin tries to change quota another user, he get 403: https://github.com/owncloud/ocis/issues/4325
- failed tests added to expected failures
- changed method `getSpaceByName`. If user admin call this method, he get **ALL** spaces `/graph/v1.0/drives`. in other cases users still see own personal space and project spaces(if user is member) `/graph/v1.0/me/drives`. 
- brought back "cleaning after tests". But we can enable it, if admin get ability to disable and delete others spaces.
=> [test-only]Api test. add tests for changing quota of the personal space

changelog/unreleased/user-expand-drive.md, go.mod, go.sum, services/graph/pkg/service/v0/users.go
Enhancement: Expand personal drive on the graph user
We can now list the personal drive on the users endpoint via the graph API. A user can add an `$expand=drive` query to list the personal drive of the requested user.
- Fixes #4327 
```sh
curl -L -X GET "https://localhost:9200/graph/v1.0/users/f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c/?$expand=drive" \
-H "Authorization: Basic YWRtaW46YWRtaW4="
```
```json
{
"displayName": "Marie Skłodowska Curie",
"drive": {
"driveAlias": "personal/marie",
"driveType": "personal",
"id": "1284d238-aa92-42ce-bdc4-0b0000009157$f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c",
"lastModifiedDateTime": "2022-08-03T17:38:40.549113+02:00",
"name": "Marie Skłodowska Curie",
"owner": {
"user": {
"id": "f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c"
}
},
"quota": {
"remaining": …
```
=> add expand query for personal drive

changelog/unreleased/fix-unrestricted-quota.md, services/graph/pkg/service/v0/drives.go
Unrestricted quota should show up on the graphAPI
- Fixes #4328 
Make it possible for clients to process the response better.
```sh
curl -L -X PATCH "https://localhost:9200/graph/v1.0/drives/1284d238-aa92-42ce-bdc4-0b0000009157$03d2043d-3ee1-44e2-b0e8-482c89457897" \
-H "Authorization: Basic YWRtaW46YWRtaW4=" \
-H "Content-Type: application/json" \
--data-raw " {
\"quota\": {
\"total\": 0
}
}"
```
```json
{
"description": "Elon Musk wants to fly to pluto too",
"driveAlias": "project/mission-to-pluto",
"driveType": "project",
"id": "1284d238-aa92-42ce-bdc4-0b0000009157$03d2043d-3ee1-44e2-b0e8-482c89457897",
"lastModifiedDateTime": "2022-08-08T19:18:54.916757584+02:00",
"name": "Mission to Pluto",
"owner": {
"user": {
"id": "03d2043d-3ee1-44e2-b0e8-482c89457897"
}
},
"quota": {
"remaining": …
```
=> fix unrestricted quota

tests/acceptance/features/apiSpaces/checksum.feature, tests/acceptance/features/bootstrap/SpacesContext.php
This PR adds the tests for checksum related to `/Shares` which is removed from this PR https://github.com/owncloud/core/pull/40271 as `/Shares` related implementation is not in core and is shifted to ocis.
Note: Most of the tests for the checksum is run from core on ocis. This test added on ocis is only related to `/Shares` (Shares Jail)
Note: Expected to failure for this PR is removed in this PR https://github.com/owncloud/ocis/pull/4364
=> [tests-only][full-ci]Add `/Shares` realated tests from core

Dockerfile
Update golang to v1.18 in the root Dockerfile
- Fixes #4370 
- manually
```sh
docker build -t ocis .
COPY ./ /ocis/
WORKDIR /ocis/ocis
RUN make ci-node-generate
-FROM owncloudci/golang:1.17 as build
+FROM owncloudci/golang:1.18 as build
COPY --from=generate /ocis /ocis
WORKDIR /ocis/ocis
RUN make ci-go-generate build
-FROM alpine:3.13
+FROM alpine:3.15
RUN apk update && \
apk upgrade && \
...skipping...
[+] Building 431.1s (18/18) FINISHED
=> [internal] load build definition from Dockerfile                                                                                                                                                                     0.0s
=> => transferring dockerfile: 1.24kB …
```
=> Use golang 1.18

tests/acceptance/features/apiSpaces/copySpaces.feature, tests/acceptance/features/apiSpaces/moveSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
While Sharing space, the available roles are only `manager`, `editor` and `viewer`. So in case if we pass other value the default value `viewer` is set through API. So a validation code has been added to prevent it.
=> [tests-only][full-ci]Select Available role only while sharing space

.drone.star, tests/config/drone/check_web_cache.sh
- Zip the `web`, `yarn` files to be cached.
- Unzip the cache on restore
- Part of https://github.com/owncloud/QA/issues/756
- :robot:
=> [ci] zip before cache and unzip on restore

.vscode/launch.json, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature, tests/acceptance/features/apiSpaces/shareSubItemOfSpace.feature, tests/acceptance/features/apiSpaces/shareSubItemOfSpaceViaPublicLink.feature, tests/acceptance/features/bootstrap/SpacesContext.php
- Members of the project space should be able to see public link or share resourses
- added api tests
- created bug #4347 and failed tests moved to expected failures 
note: I could not add tests for: check that **folder** contains link because there were difficulties in getting folderID (should hard parsing xml). I've marked it as a technical debt
=> [test-only]Api test. check that link or share exist for space members

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md, tests/acceptance/features/apiSpaces/etagPropagation.feature, tests/acceptance/features/bootstrap/SpacesContext.php
This PR adds the tests for etag propagation when deleting files and folders related to `/Shares` which is removed from this PR https://github.com/owncloud/core/pull/40288 as `/Shares` related implementation is not in core and is shifted to ocis.
https://github.com/owncloud/QA/issues/761
Note: Most of the tests for the `etag` check when deleting files and folder is run from core API suites on ocis. This test added on ocis is only related to `/Shares` (Shares Jail)
=> [tests-only][full-ci]Add etag propagation for delete files folder for spaces

services/search/pkg/command/server.go, services/search/pkg/engine/bleve.go, services/search/pkg/server/grpc/server.go, services/search/pkg/service/grpc/v0/service.go
Search service kept alive even if an error happens due initialization... this is changed to let the service die and the runtime can handle the re-initialization.
be able to use `restart: always` docker option.
=> [full-ci] let search service exit 

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/bootstrap/SpacesContext.php
- added the ability to delete personal space after each test
- deleted failed test from expected failures
Part of issue #4390
=> [tests-only] [full-ci] ApiTest. after each test users delete their personal space

services/search/pkg/engine/engine.go
bleve tend to convert []string{"foo"} to type string if slice contains only one value
bleve: []string{"foo"} -> "foo"
bleve: []string{"foo", "bar"} -> []string{"foo", "bar"}
this is fixed now and always returns a slice of T
fixes https://github.com/owncloud/enterprise/issues/5303
=> [full-ci] fix tag proposals

.drone.star, tests/acceptance/config/behat.yml, tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiGraph/createGroupCaseSensitive.feature, tests/acceptance/features/bootstrap/GraphContext.php
Group names are case insensitive with oCIS, we cannot create groups with the same name but different lower and upper cases. So, tests to check group creation with different lower and upper cases are added as suggested in https://github.com/owncloud/ocis/issues/4291#issuecomment-1210956364
- Part of https://github.com/owncloud/ocis/issues/4291
- Related to https://github.com/owncloud/ocis/issues/4291#issuecomment-1210956364
- Locally
- CI
=> [full-ci] [tests-only] Added test for creating group with case sensitive

tests/acceptance/features/bootstrap/SpacesContext.php
Part2 of issue https://github.com/owncloud/ocis/issues/4390
- method works well and clears project spaces
But there is one little problem when we run tests without creating project space and method https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/bootstrap/SpacesContext.php#L897-L904 tries to remember no spaces:
=> [tests-only] [full-ci] ApiTest. after each test users-manager delete their project space

changelog/unreleased/missing-unprotected-paths.md, services/proxy/pkg/middleware/authentication.go
When ownCloud Web uses the vue router hash mode we need `/index.html#/whatever-ruotes` to be unprotected as well.
`open with web` internally resolves into `/external`, so I needed to shorten the unprotected path prefix `/external/spaces` to `/external`.
=> fix: add index.html to unprotected paths in auth middleware

services/proxy/pkg/middleware/authentication.go
index.html itself needs to be unprotected as well... in https://github.com/owncloud/ocis/pull/4458 I only added the `/index.html#/` path prefix, which is not enough...
=> fix: add index.html to unprotected paths

changelog/unreleased/enhancement-add-preview-file-mime-types-to-web-default-config, services/web/pkg/config/defaults/defaultconfig.go
Enhancement: Add previewFileMimeTypes to web default config
We've added previewFileMimeTypes to the web default config, so web can determine which preview types are supported
by the backend.
Part of: https://github.com/owncloud/web/pull/7474
- test case 1:
- test case 2:
- ...
=> Add previewFileMimeTypes to defaultconfig.go

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpaces/changingFilesShare.feature, tests/acceptance/features/apiSpaces/moveSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
Restore the scenarios removed by core PR https://github.com/owncloud/core/pull/40302.
- Part of https://github.com/owncloud/ocis/issues/4154
- :robot:
=> [tests-only] restore scenarios removed from core#40302

.drone.env, tests/acceptance/features/apiSpaces/favorite.feature, tests/acceptance/features/bootstrap/SpacesContext.php
This PR adds the tests for favorite properties related to `/Shares` which is removed from this PR https://github.com/owncloud/core/pull/40274 as `/Shares` related implementation is not in core and is shifted to ocis.
=> [tests-only][full-ci]Add /Shares related favorite tests on ocis which are removed from core

changelog/unreleased/bugfix-disable-public-link-default-expiration.md, services/frontend/pkg/revaconfig/config.go
The `public.expire_date` capability has misleading naming, as it represents the default expiration date configuration. `enabled: true` requires that a default number of days is provided as well. Since that's not done we should disable the default expiration (or decide to add a default amount of days). This PR disables the default expiration date for public links so that clients behave correctly.
- Fixes https://github.com/owncloud/ocis/issues/4445
=> [full-ci] disable misconfigured default expiration date public links

tests/TestHelpers/GraphHelper.php, tests/acceptance/features/apiGraph/changeOwnPassword.feature, tests/acceptance/features/bootstrap/GraphContext.php, tests/acceptance/features/bootstrap/SpacesContext.php
- added api tests for changing own password
in case the user sends an incorrect current password, we get a 500 Server error.  @rhafer Is it correct? 
maybe we should return 400 with "incorrect current password"? 
in the comparison oc10 returns 200 and message:
=> [test-only] apiTest. change own password

changelog/unreleased/refactor-proxy.md, services/proxy/pkg/command/server.go, services/proxy/pkg/config/config.go, services/proxy/pkg/config/defaults/defaultconfig.go, services/proxy/pkg/middleware/authentication.go, services/proxy/pkg/proxy/proxy.go, services/proxy/pkg/proxy/proxy_integration_test.go, services/proxy/pkg/router/router.go, services/proxy/pkg/router/router_test.go
- Fixes https://github.com/owncloud/ocis/issues/4401
- test case 1:
- test case 2:
- ...
=> [full-ci] Refactor proxy to get rid of the hardcoded unprotected lists

.drone.env
This PR bumps core commit id for tests
- Part of: https://github.com/owncloud/QA/issues/763
- CI
=> [full-ci][tests-only]Bump commit id for tests

tests/TestHelpers/GraphHelper.php, tests/acceptance/features/bootstrap/SpacesContext.php
See comment https://github.com/owncloud/ocis/pull/4488#discussion_r961492404
`restoreSpace` has the needed header coded inside it. Do the same for `deleteSpace`
=> [tests-only] Hardcode header in GraphHelper::deleteSpace

changelog/unreleased/bugfix-i18n-login-page.md, services/idp/src/containers/Login/Login.jsx, services/idp/src/i18n.ts, services/idp/src/locales/de/translation.json
We've fixed several translations on the login page. Also, the browser language is now being used properly to determine the language.
- Fixes https://github.com/owncloud/web/issues/7550
=> Fix translations on login page

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpaces/copySpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
This PR adds the tests for copy properties related to `/Shares` which is removed from this PR https://github.com/owncloud/core/pull/40278 as `/Shares` related implementation is not in core and is shifted to ocis.
Note: Most of the tests for the `copy` is run from core API suites on ocis. This test added on ocis is only related to `/Shares` (Shares Jail)
=> [tests-only][full-ci]Add `/Shares` related copy tests on ocis which are removed from core

.drone.env, tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/SpacesContext.php
This PR of using the resource (code) from core as much as possible since there has been a duplication of code that already exists in core. A method to set the space id sets the space id of (Space) not implemented on core is added to make it work. This is an example with `favorite.feature` of ocis. A few adjustment has been done in core for this to works. Can be seen in this Core PR https://github.com/owncloud/core/pull/40328.
https://github.com/owncloud/core/pull/40328
=> [tests-only][full-ci]Reuse code from code for `favorites.feature` in ocis

tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/SpacesContext.php
This PR makes adjustment to use the existing locking method from core and removes the duplicated code.
https://github.com/owncloud/ocis/issues/4509
=> [tests-only][full-ci]Reuse locking method from core

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpaces/search.feature
issue was closed #4014, but the failed tests still existed
- with the existing implementation we cannot find the folder "folder" in the search response. but we still check that search result contains subfolders
- in test we have checking that response should contain 4 entries
folder "folder" is mountpoint and looks like id
but the other folders we can find with the existing implementation:
=> [tests-only] Api test. fix search test

services/graph/pkg/service/v0/password.go, services/graph/pkg/service/v0/password_test.go, tests/acceptance/features/apiGraph/changeOwnPassword.feature
Up to now the /me/changePassword endpoint return a 500 Status when
issue a password change with the old password set to the wrong password.
This changes the code to return 400 (Bad Request) with an additional
message that the old password is wrong. This does not seem to weaken the
security of /me/changePassword (i.e. for allowing easier brute-force
attacks) as the endpoint is only available to already authenticated
users (and only for changing their own passwords)
See #4480
=> graph: Fix Status code when updating the password

changelog/unreleased/orientate-thumbnails.md, services/thumbnails/pkg/preprocessor/preprocessor.go
The thumbnailer now makes use of the exif orientation information to automatically orientate pictures before generating thumbnails.
- Fixes https://github.com/owncloud/ocis/issues/4477
|Before|After|
|---------|------|
|![image](https://user-images.githubusercontent.com/5579653/188472842-56e933db-1d7e-49e8-b743-c2f73ce0482c.png)|![image](https://user-images.githubusercontent.com/5579653/188473165-b0f4476d-3f27-4cab-abd8-c172b6f81fb0.png)|
=> auto orientate pictures for thumbnails

protogen/proto/buf.lock
Update the buf lock file in the hope that this will fix the CI builds:
E.g.: https://drone.owncloud.com/owncloud/ocis/15253/3/4
=> update buf lock

changelog/unreleased/refactor-proxy.md, services/proxy/pkg/middleware/authentication.go, services/proxy/pkg/middleware/public_share_auth.go, services/proxy/pkg/middleware/public_share_auth_test.go, services/proxy/pkg/router/router.go
The endpoints are no longer hashed by path name in the directors map since that made iterating over the endpoints unstable. They are now stored in a slice in the order in which the are defined in the configuration.
This also includes a fix to make the archiver work for public-links (https://github.com/owncloud/ocis/pull/4461#pullrequestreview-1093104888)
- Fixes  #4497
=> proxy: Avoid sorting endpoints for every request

services/graph/pkg/service/v0/users.go
previously the homespace was just marked as trashed
Fixes: #4195
=> graph: purge home space when deleting a user

changelog/unreleased/delete-orphaned-spaces.md, services/settings/pkg/store/defaults/defaults.go
This is assigned to the Admin role by default and allows to cleanup orphaned spaces (e.g. where the owner as been deleted)
Fixes: #4196
Required for https://github.com/cs3org/reva/pull/3203 to fully work
=> Add new "delete-all-spaces" permission

.drone.star, tests/acceptance/expected-failures-API-on-OCIS-storage.md
This PR removes the unrelated test from this issue [Listing shares does not show a path for parent folders](https://github.com/owncloud/ocis/issues/1231) and add to the actually related issue
=> [full-ci][tests-only]Refactor expected-failure file

tests/acceptance/features/apiSpaces/moveSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
This PR adds the tests for move properties related to `/Shares` which is removed from this PR https://github.com/owncloud/core/pull/40294 as `/Shares` related implementation is not in core and is shifted to ocis.
=> [tests-only][full-ci]Add /Shares related move tests on ocis which are removed from core

tests/acceptance/features/apiSpaces/shareOperations.feature, tests/acceptance/features/bootstrap/SpacesContext.php
This PR reuses code from core for the `shareOperation.feature` in `ocis` and avoid duplication.
https://github.com/owncloud/ocis/issues/4509
=> [tests-only][full-ci]Reuse code from core for `shareOperation`

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
Part Of : https://github.com/owncloud/QA/issues/763
=> [tests-only][full-ci] Bump Core commit for 2022-09-09

changelog/unreleased/update-reva-beta8.md, go.mod, go.sum, ocis/pkg/command/migrate.go, services/sharing/pkg/config/config.go, services/sharing/pkg/config/defaults/defaultconfig.go, services/sharing/pkg/revaconfig/config.go, tests/acceptance/expected-failures-API-on-OCIS-storage.md
This PR allows for configuring the jsoncs3 public share manager from https://github.com/cs3org/reva/pull/3199
FIxes https://github.com/owncloud/ocis/issues/3881
Fixes https://github.com/owncloud/ocis/issues/2164
=> [full-ci] Add support for the jsoncs3 public share manager

changelog/unreleased/update-reva-beta8.md, go.mod, go.sum
- test case 1:
- test case 2:
- ...
=> [full-ci] Update reva to v2.10.0

services/frontend/pkg/config/config.go, services/frontend/pkg/config/defaults/defaultconfig.go, services/frontend/pkg/revaconfig/config.go
Listing the received shares for a user that has 150 incoming shares currently takes 6-10sec. (that is with the gateway cache enabled by locally reverting https://github.com/cs3org/reva/pull/3167)
While the internal listing of shares is in the 140ms ballpark with https://github.com/cs3org/reva/pull/3148 the ocs api also returns file and path information, requiring a stat and a getpath for every share, adding up to hundreds of internal stat requests.
reva can cache the stat requests with an in memory cache or in redis, dropping the response time for the same user from 8sec to 700ms on my machine. The difference between 140ms and 700ms is spent on GetPath calls that we could get rid of completely by requesting the path in the stat request in the fieldmask. something for another PR.
This PR …
=> enable a 300sec in memory cache for resource infos when listing shares on the ocs API

changelog/unreleased/fix-search-webdav-permissions.md, services/search/pkg/search/provider/searchprovider.go
We now correctly render the `oc:permissions` of resources as a string.
fixes https://github.com/owncloud/ocis/issues/4575
=> fix search report webdav permissions

changelog/unreleased/enhancement-web-applications.md, services/web/pkg/config/config.go
allows to configure applications for web.
- 
Modify the app switcher in web
- `web.yaml`:
```
web:
config:
applications:
-  icon: swap-box
url: https://owncloud.com
target: _self
title:
de: ownCloud Webseite
en: ownCloud Webpage
```
=> allow to configure applications for web

docs/services/frontend/_index.md, docs/services/sharing/_index.md
I added a few basic infos about sharing related services.
@dragotin the info from https://github.com/owncloud/ocis/pull/4438#issuecomment-1241825616 is pretty outdated, as @aduffeck and I managed to reduce listing of 500 shares as a recipient from 46 down to 4 seconds. A combination of different public share manager implementations share manager bugs and ocs performance tuning.
I still added an explanation for the only worthwile option to enable the resource stat info cache in the ocs service. I put that on the frontend index page. That seems to currently be the best place.
=> [docs-only] update sharing docs

services/idp/public/index.html, services/idp/src/app.css
Closes: https://github.com/owncloud/ocis/issues/4212
We were using the Open Sans font only as a fallback to the "Inter" font which we served ourselves so removing the google font does no harm.
=> remove the Open Sans font

docs/templates/ADOC.tmpl
This fixes the adoc template because eMails in the form `<me@example.com>` were not rendered (note the less than/ greater than symbols)
The change uses a better way for passthrough, see [pass-macro in asciidoc](https://docs.asciidoctor.org/asciidoc/latest/pass/pass-macro/#single-double-plus)
- References #4589 (Notification service env variable update needed)
Render eMail addresses in the form as written above
Local build with `make -C docs docs-generate`
Then check all services adoc files if the output is correct ✔️
=> [Docs] Fixing the adoc template

changelog/unreleased/add-email-templating.md, services/audit/pkg/types/events.go, services/notifications/pkg/channels/channels.go, services/notifications/pkg/command/server.go, services/notifications/pkg/config/config.go, services/notifications/pkg/email/email.go, services/notifications/pkg/email/templates/shareCreated.email.tmpl, services/notifications/pkg/email/templates/sharedSpace.email.tmpl, services/notifications/pkg/service/service.go
We have added email templating to ocis. Which are send on the SpaceShared and ShareCreated event.
refs #4303 
refs https://github.com/cs3org/reva/pull/3252
=> Add email templating

go.mod, go.sum, ocis-pkg/registry/registry.go, ocis-pkg/service/grpc/service.go, ocis/pkg/command/server.go, services/graph/pkg/service/v0/drives.go, services/graph/pkg/service/v0/service.go, services/ocs/pkg/service/v0/service.go, services/proxy/pkg/command/server.go, services/search/pkg/command/index.go, services/webdav/pkg/service/v0/service.go
Default to in-memory registry in single-binary mode
This avoids various issues of the old "mdns" default. At least for the simple single process setup (#3134, #4597). When starting the services individually we still default to "mdns".
This needs: https://github.com/cs3org/reva/pull/3258
=> [full-ci] Default to in-memory registry in single-binary mode

docs/templates/ADOC.tmpl
This is a small fix which just adds a blank to the type and default value field in the pass thru definition.
**Reason**: while it renders totally fine, when building the site with Antora 2.3 (our outdated version), we get many warnings about an `unterminated pass block` when using `++++`. This happens when there is no type or no default value set. When adding a blank, the warning goes away. 
`++++` -->  `++ ++`
renders to
`<p></p>` --> `<p> </p>`
This warning will possibly change respectively go away totally with Antora 3.1.1 (lets see) and we can remove the blank.
=> [docs] Add a blank to type and default value pass thru

changelog/unreleased/fix-unfindable-entities.md, services/search/pkg/search/provider/events.go, services/search/pkg/search/provider/events_test.go, services/search/pkg/search/provider/searchprovider.go, services/search/pkg/search/provider/searchprovider_test.go
This PR fixes a problem where directories or empty files weren't findable because they were to the search index improperly when created through a share or publicshare.
=> Fix unfindable entities

.drone.env, .drone.star, tests/acceptance/expected-failures-API-on-OCIS-storage.md
This PR removes the cloning of the testing app , as it's not really needed here
=> [full-ci][tests-only]Run ocis tests without testing-app

.drone.star, tests/config/drone/check_web_cache.sh
The `web` is cached for the CI with these three:
- the web itself (install & build)
- web-acceptance (yarn install)
- web-e2e (yarn install)
While performing the caching, the web.tar.gz is checked inside the `$CACHE_BUCKET/ocis/web-test-runner/$WEB_COMMITID` location.
But somehow, there was only web.tar.gz and no acceptance.tar.gz and e2e.tar.gz for the current pinned web commit id. This was very uncommon because every time we build a new web for the new commit id, at the same time the acceptance of an e2e cache should also be built and saved inside the bucket. But sometimes strange things happen.
To cope with this case, I've divided the web caching pipeline into 3, all separately caching their stuff. Each pipeline will check for its target in the cache-store. If available, they exit as …
=> [ci] fix restore for web cache

changelog/unreleased/fix-bring-back-settings-ui.md, services/web/pkg/config/defaults/defaultconfig.go, services/web/pkg/service/v0/service.go
Bugfix: Bring back the settings UI in Web
We've fixed the oC Web configuration in oCIS so that the settings UI will be shown again in Web.
- test case 1:
- test case 2:
- ...
=> bring back the settings ui

.drone.star
Ran into trouble when trying to bump nodejs to it's current stable version (v16) on https://github.com/owncloud/ocis/pull/4057 as the `arm` docker build step had memory issues on installing dependencies. 
Update: Node v15 doesn't work since the updated `eslint` in the settings service requires either v14 or v16. Best guess is that the `owncloudci/nodejs` image for node16 doesn't work with `arm`
=> Bump nodejs in CI

changelog/unreleased/fix-autoprovison-token.md, services/proxy/pkg/middleware/account_resolver.go
To successfully authenticate a user after it was autoprovisioned, we need to get a valid reva token.
Fixes: #4616
=> Request revatoken via machine auth after autoprovsioning user

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiArchiver/downloadByPath.feature
This PR refactors HTTP status code for downloading non-existing archive resources
- Fixes [Closed issue downloading an archive with invalid path returns HTTP/500 still exist in expected-to-failure #4695](https://github.com/owncloud/ocis/issues/4695)
- Locally
=> [tests-only][full-ci]Refactor download archive related scenario

docs/ocis/deployment/ocis_s3.md
This path `cd ocis/deployment/examples/ocis_s3` that's mentioned in the docs is not valid, so this PR fixes that
- Part of: https://github.com/owncloud/ocis/issues/4595
=> [docs-only] Fix path name in ocis_s3 docs

changelog/unreleased/fix-share-notifications.md, ocis-pkg/config/defaultconfig.go, ocis-pkg/config/parser/parse.go, services/notifications/pkg/channels/channels.go, services/notifications/pkg/command/server.go, services/notifications/pkg/email/templates/shareCreated.email.tmpl, services/notifications/pkg/email/templates/sharedSpace.email.tmpl, services/notifications/pkg/service/service.go
- Notications for group shares caused nil pointer derefs
- Notifications for group shares did not send mails (failed to lookup group members)
- Notifications mails might contain the wrong link
Fixes: #4703 , #4688
=> Multiple fixes for notification service

.drone.env
This PR bumps core commit id for tests
- Part of: https://github.com/owncloud/QA/issues/766
- CI
=> [tests-only][full-ci]Bump core commit id for tests

changelog/unreleased/tokeninfo-endpoint-auth.md, services/proxy/pkg/middleware/authentication.go, services/proxy/pkg/middleware/authentication_test.go
Make the tokeninfo endpoint unprotected as it is supposed to be available to the public.
=> Make tokeninfo endpoint unprotected

services/web/pkg/config/defaults/defaultconfig.go
preview app was listed twice in web config.json which leads to acceptance test errors in web.
=> remove duplicated web preview app

services/search/pkg/content/tika.go, services/search/pkg/content/tika_test.go
Content extractor also scanned empty files which is unnecessary, this pr takes care of it and skips the tika request in those cases.
=> Skip content extraction for 0 byte files

services/app-provider/pkg/revaconfig/config.go, services/app-registry/pkg/revaconfig/config.go, services/auth-basic/pkg/revaconfig/config.go, services/auth-bearer/pkg/revaconfig/config.go, services/auth-machine/pkg/revaconfig/config.go, services/frontend/pkg/revaconfig/config.go, services/gateway/pkg/revaconfig/config.go, services/groups/pkg/revaconfig/config.go, services/ocdav/pkg/command/server.go, services/sharing/pkg/revaconfig/config.go, services/storage-publiclink/pkg/revaconfig/config.go, services/storage-shares/pkg/revaconfig/config.go, services/storage-system/pkg/revaconfig/config.go, services/storage-users/pkg/revaconfig/config.go, services/users/pkg/revaconfig/config.go
Part of https://github.com/cs3org/reva/issues/2976 to make reva master and edge comparable at the request level.
Requires https://github.com/cs3org/reva/pull/3229 to get metrics like this:
```
$ curl 127.0.0.1:9165/metrics -s | grep _requests | grep -v '#' | grep -v 'promhttp_metric_'
ocis_app_provider_grpc_requests_total 0
ocis_app_registry_grpc_requests_total 1
ocis_auth_basic_grpc_requests_total 1
ocis_auth_bearer_grpc_requests_total 0
ocis_auth_machine_grpc_requests_total 1
ocis_frontend_http_requests_total 1
ocis_gateway_grpc_requests_total 1013
ocis_groups_grpc_requests_total 0
ocis_sharing_grpc_requests_total 1
ocis_storage_publiclink_grpc_requests_total 0
ocis_storage_shares_grpc_requests_total 0
ocis_storage_system_grpc_requests_total 858
ocis_storage_system_http_requests_total …
```
=> enable request tracking prometheus middleware in reva

changelog/unreleased/fix-static-asset-caching.md, services/web/pkg/assets/server.go, services/web/pkg/service/v0/service.go
we should not cache the index.html for oC web. If we cache the index.html it may require bundles that are no longer available after an update.
- Fixes with caching
- ...
=> don't cache the web index.html

tests/acceptance/expected-failures-API-on-OCIS-storage.md
- Remove the closed issue.
- Update with the relevant one.
- Part of https://github.com/owncloud/ocis/issues/4686
- :robot: 
---
Signed off by @kiranparajuli589
=> [tests-only] remove closed issue pin from the expected failures and update with the relevant one

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpacesShares/changingFilesShare.feature, tests/acceptance/features/apiSpacesShares/copySpaces.feature, tests/acceptance/features/apiSpacesShares/moveSpaces.feature, tests/acceptance/features/bootstrap/SpacesContext.php
When we copy or move file with same name we have 2 option:
- keep both- the new file changes its name as `new (1).txt`
- replace- we change the contents of the file and the file has the old version
I added:
related: https://github.com/owncloud/ocis/issues/4797
=> [test-only] Api-test. Overwriting a file while coping and moving

tests/acceptance/features/apiSpaces/search.feature, tests/acceptance/features/bootstrap/SpacesContext.php
- added test for checking parentID for project space and shares jail.
Need clarify: 
- for folder 1 level in project space parentId should be spaceId?
<oc:file-parentId>: `1284d238-aa92-42ce-bdc4-0b0000009157$105adae8-b126-43d1-93d8-6744e01d8d8c!105adae8-b126-43d1-93d8-6744e01d8d8c` 
spaceId: `1284d238-aa92-42ce-bdc4-0b0000009157$105adae8-b126-43d1-93d8-6744e01d8d8c`
- for folder 1 level in shares jail should be mountpoint?  
<oc:file-parentId> : `1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51!4c510ada-c86b-4815-8820-42cdf82c3d51` 
mountpointId: `a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668!1284d238-aa92-42ce-bdc4-0b0000009157:4c510ada-c86b-4815-8820-42cdf82c3d51:eb54855b-94a3-43ee-bd97-0f6963ea460b`
=> [test-only] Apitest. Add checking parentId

services/search/pkg/engine/bleve.go
searching for wildcards in bleve is expensive, not sure if we use it wrong, but for now this pr contains a workaround where we're filtering out non matches manually after the search is done. 
once more time is there we should investigate if a different field analyzer or something else could fix this.
=> filter out search path manually

services/proxy/pkg/user/backend/cs3.go
Fixed a bug introduced in https://github.com/owncloud/ocis/commit/87eaf72020a71f9714ec2c1b396023f32a5d8523 due to improper preparation _(missing Account-Id)_ of context before the invocation of `AssignRoleToUser`. 
- Fixes [#4787 ](https://github.com/owncloud/ocis/issues/4787)
External user backend (e.g. external LDAP) deployments couldn't log in due to the infinite loop / error caused at login.
Tested in the aforementioned external LDAP auth. environment.
=> Add UserID to context during initial login

changelog/unreleased/logging-improvements.md, ocis-pkg/log/log.go, ocis-pkg/middleware/logger.go, services/graph/pkg/identity/cs3.go, services/graph/pkg/identity/ldap.go, services/graph/pkg/middleware/auth.go, services/graph/pkg/service/v0/drives.go, services/graph/pkg/service/v0/errorcode/errorcode.go, services/graph/pkg/service/v0/graph.go, services/graph/pkg/service/v0/groups.go, services/graph/pkg/service/v0/users.go, services/proxy/pkg/middleware/accesslog.go, services/thumbnails/pkg/service/http/v0/service.go, services/webdav/pkg/service/v0/search.go, services/webdav/pkg/service/v0/service.go
We improved the logging of several http services. If possible and present, we now log the `X-Request-Id`.
In ocis, we have the following log levels
FATAL means that the application is about to stop a serious problem or corruption from happening. This level of logging shows that the application’s situation is catastrophic, such that an important function is not working. For example the application is unable to connect to the data store due to config errors or not able to parse the config
This is the default log level, all errors on this level are important for admins because they need to fix them.  This log level is used when a severe issue is stopping functions within the application from operating correctly. Ocis logs all kind of inter service communication errors on this level because …
=> harden drives api and improve logging

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiSpacesShares/copySpaces.feature, tests/acceptance/features/apiSpacesShares/moveSpaces.feature
I noticed that after overwriting through copying, the file goes to the trash. for this reason the file loses its old versions when we overwrite it. we simply delete the file and replace it with a new one
I added checking that:
- after overwriting through copying trash should not have file
- after overwriting through moving trash should have file. @phil-davis Here we can check that the versions are saved. I should restore file from trash. but I have wrong Destination. the file tries to restore to the place where we moved it to, not where it came from
=> [test-only] Api test checking trash after overwriting

services/idp/src/reducers/login.js
Not having good insights into the idp web ui, @JammingBen and I debugged the Chooseaccount page, which is shown in case of a client login. Seemed only logical to us that the `loading` application state needs to be cleared when a `RECEIVE_CONSENT` or `RECEIVE_LOGON` event is catched. But since we're not familiar with the code base and there is no test coverage whatsoever, we're not sure if we break something else with this change... needs manual testing with various clients.
- Fixes https://github.com/owncloud/ocis/issues/4704
- hopefully doesn't create new issues 😕
=> fix: clear loading state if consent or logon received

changelog/unreleased/settings-values.md, services/settings/pkg/service/v0/service.go
Added checks that users can only set and list their own settings.
=> prohibit users form setting and listing other user's values

.drone.env, tests/acceptance/expected-failures-API-on-OCIS-storage.md
Updated the oC/core commit iD for the tests to the latest upto oct 28, 2022
part of https://github.com/owncloud/QA/issues/768
---
=> [tests-only][full-ci] bump oC/core commit ID for the tests

docs/ocis/development/beta-testplan.md
issue https://github.com/owncloud/ocis/issues/2131 is closed, so we don't need to mention it in the testplan
=> delete reference to issue 2131

tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md, tests/acceptance/features/apiAccountsHashDifficulty/addUser.feature, tests/acceptance/features/apiAccountsHashDifficulty/createShareToSharesFolder.feature, tests/acceptance/features/apiAccountsHashDifficulty/uploadFile.feature, tests/acceptance/features/apiAccountsHashDifficulty/webDavPUTAuthInvalid.feature, tests/acceptance/features/apiGraph/changeOwnPassword.feature, tests/acceptance/features/apiGraph/createGroupCaseSensitive.feature, tests/acceptance/features/apiSpaces/search.feature, tests/acceptance/features/apiSpacesShares/copySpaces.feature, tests/acceptance/features/apiSpacesShares/createFileFolderWhenSharesSpaceExist.feature, tests/acceptance/features/apiSpacesShares/etagPropagation.feature, tests/acceptance/features/apiSpacesShares/moveSpaces.feature
Interspacing between two scenarios is made consistent as documented https://github.com/owncloud/docs-server/pull/697/files#diff-12a0f404a5bbbda65e50018a487cd725797106d670f4308b921d2081dc4b3516R1129-R1154:~:text=more%20relevant%20discussion.-,%3D%3D%3D%3D%20Inter%2Dscenario%20spacings,%2D%2D%2D%2D,-Commenting%20on%20lines
- apiAccountsHashDifficulty
- apiArchiver
- apiContract
- apiGraph
- apiSpaces
- apiSpacesShares
- Part of https://github.com/owncloud/QA/issues/769
- :robot:
=> [full-ci] [tests-only] Refactored inter scenarios space

changelog/unreleased/validate-space-names.md, services/graph/pkg/service/v0/drives.go, services/graph/pkg/service/v0/drives_test.go
We now return `BAD REQUEST` when space names are
-  too long (max 255 characters)
-  containing evil characters (`/`, `\`, `.`, `\\`, `:`, `?`, `*`, `"`, `>`, `<`, `|`)
Additionally leading and trailing spaces will be removed silently.
fixes this: https://github.com/owncloud/ocis/issues/4925
=> Validate Space Names

changelog/unreleased/settings-permissions-check.md, services/settings/pkg/service/v0/service.go, services/settings/pkg/service/v0/service_test.go
The settings service allowed anyone to assign roles to any user. This change is an improvement but generally the settings service code needs some more work and some other methods need checks as well but I will tackle those in other PRs.
=> [full-ci]fallback to stored roles

changelog/unreleased/rename-authprovider.md, services/auth-basic/README.md, services/auth-basic/pkg/config/config.go
Improves auth-basic readme and rename envvar
=> Improve AuthBasic Readme

changelog/unreleased/enable-privatelinks-capability.md, services/frontend/pkg/revaconfig/config.go
Enable private links capability.
```json
{
"ocs": {
"meta": {
"status": "ok",
"statuscode": 100,
"message": "OK"
},
"data": {
"capabilities": {
"core": {
"pollinterval": 60,
"webdav-root": "remote.php/webdav",
"status": {
"installed": true,
"maintenance": false,
"needsDbUpgrade": false,
"version": "10.11.0.0",
"versionstring": "10.11.0",
"edition": "Community",
"productname": "Infinite Scale",
"product": "Infinite Scale",
"productversion": "2.0.0-beta.8+dev"
},
"support-url-signing": true
},
"checksums": {
"supportedTypes": [
"sha1",
"md5",
"adler32"
],
"preferredUploadType": "SHA1"
},
"files": {
"privateLinks": true,
"bigfilechunking": false,
"undelete": true,
"versioning": true,
"favorites": false,
"blacklisted_files": [],
"tus_support": {
"version": "1.0.0",
"resumable": "1.0.0", …
```
=> enable private links

changelog/unreleased/mintls12.md, services/audit/pkg/command/server.go, services/graph/pkg/server/http/server.go, services/graph/pkg/service/v0/service.go, services/notifications/pkg/channels/channels.go, services/notifications/pkg/command/server.go, services/proxy/pkg/command/server.go, services/proxy/pkg/proxy/proxy.go, services/search/pkg/service/v0/service.go, services/thumbnails/pkg/thumbnail/imgsource/cs3.go, services/thumbnails/pkg/thumbnail/imgsource/webdav.go
should help with the sonarcloud security rating
=> use min tls 1.2

tests/acceptance/expected-failures-webUI-on-OCIS-storage-ocisSmokeTest.md
webUI acceptance test `webUIPrivateLinks/accessingPrivateLinks.feature:9` is passing as we can now see `copy-private-link` button.
Maybe this was enabled in PR https://github.com/owncloud/ocis/pull/4599 yesterday
Previously this scenario used to fail in the following step:
```feature
✖ When the user copies the private link of the file "lorem.txt" using the webUI # stepDefinitions/privateLinksContext.js:5
Timed out while waiting for element <.oc-files-private-link-copy-url> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10019ms)
```
- Closes https://github.com/owncloud/ocis/issues/4977
- test environment: local & CI
=> [tests-only][full-ci] Remove passing copy-private-link test from expected failure

services/frontend/pkg/config/config.go, services/frontend/pkg/config/defaults/defaultconfig.go, tests/acceptance/expected-failures-webUI-on-OCIS-storage-ocisSmokeTest.md
Improved some frontend env descriptions, found while reviewing #4950
@butonic @rhafer following question to complete this PR, additional commits may be necessary,
see picture below:
1. `FRONTEND_CHECKSUMS_SUPPORTED_TYPES` is an array. Are there more supported values than the default ones: [sha1 md5 adler32] and in case which ones.
2. `FRONTEND_CHECKSUMS_PREFERRED_UPLOAD_TYPES` the name is plural, but the type is not an array (like above). Therefore:
-- is the type correct?
-- are there defaults? (currently missing)
-- should the description be aligned to the above one?
=> Improve frontend env descriptions

tests/acceptance/config/behat.yml, tests/acceptance/features/apiGraph/createUser.feature, tests/acceptance/features/bootstrap/GraphContext.php
=> [test-only] add API acceptance tests to create user using the admin privilege

changelog/unreleased/rename-authprovider.md, services/auth-basic/README.md, services/auth-basic/pkg/config/config.go
fix leftover from https://github.com/owncloud/ocis/pull/4966
fixes https://github.com/owncloud/ocis/issues/4972
=> [docs-only] Auth basic readme fix env var rename
